### ISSUE TITLE
serf discovery

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#1002]
I'm toying with the idea of using serf for discovery.

It would provide gossip-based cluster membership in a very easy to setup way.

So easy, in fact, it could replace the default `token`-based discovery: Just pass the address of **any** node in the cluster to `swarm join` and you're done.

I guess the way to lay it down would be to start the manager as is (no addresses) and then start every node with the address of the manager. Everyone will self-discover after that.

The problem is knowing the address of the manager: You won't know that until it's started so it might not be as easy as token?

/cc @vieux @abronan @ehazlett @nathanleclaire

**Comment by abronan** [comment]
I like the idea but: we probably need an additional port + it's own set of certs for the TLS config which brings us to a number of up to 9 possible flags just for TLS (for docker daemons, the gossip discovery, and the optional storage backend). Or we reuse the certs from the docker daemons for the gossip discovery but this might not be a good idea.

**Comment by nathanleclaire** [comment]
Careful not to duplicate `libnetwork` work here.  In the experimental overlay network stuff I've been toying around with, I recall an embedded serf being used for discovery already.  cc @mrjana @mavenugo for comment.

**Comment by docteurklein** [comment]
@nathanleclaire @aluzzardi I can confirm the usage of serf on the experimental branch.
I had to open the port 7946 to allow service discovery.
Now I can't tell who is doing this, but it makes sense for either libnetwork or swarm to do it.

**Comment by abronan** [comment]
There is a proposal ongoing in #1198

**Comment by abronan** [comment]
Closing this one in favor of #1198
