### ISSUE TITLE
Swarm's docker events inconsistent with actual docker events

### ISSUE THREAD

**Issue by viranch** [docker/swarm#1006]
Running `docker -H <manager_ip>:<manager_port> events` yields events with inconsistent status fields when restarting containers:

```bash
TOKEN=`docker run --rm swarm create`
docker run -d -p 2375:2375 swarm manage token://$TOKEN
docker run -d swarm join --addr=<host_ip>:4444 token://$TOKEN # docker is listening on tcp port 4444
```

Run sample container: `docker run -d --name sleeping ubuntu:14.04 sleep 10000`

Now running `docker events` and restarting the container with `docker restart sleeping` gives following events:
```
2015-06-30T10:01:23 46c384...: (from ubuntu:14.04) die
2015-06-30T10:01:23 46c384...: (from ubuntu:14.04) start
2015-06-30T10:01:23 46c384...: (from ubuntu:14.04) restart
```

OTOH attaching to docker events via swarm manager (`docker -H localhost:2375 events`) gives following events:
```
2015-06-30T10:04:43 46c384...: (from ubuntu:14.04 node:docker-test) restart
2015-06-30T10:04:43 46c384...: (from ubuntu:14.04 node:docker-test) restart
2015-06-30T10:04:43 46c384...: (from ubuntu:14.04 node:docker-test) restart
```

Notice the last word on each line of the 2 outputs. The first gives the event status as `die`, `start`, `restart` while another one gives `restart` for all 3. The 2nd should ideally be compatible, with the first one.

**Comment by mountkin** [comment]
I open a PR to fix this problem: https://github.com/samalba/dockerclient/pull/126 
ping @aluzzardi

**Comment by vieux** [comment]
@

**Comment by vieux** [comment]
@mountkin can you open another PR to update the godeps ?

**Comment by mountkin** [comment]
#1018  @vieux
