### ISSUE TITLE
Unable to Connect to a Node having Docker Daemon Exposed on a Port different from 2375

### ISSUE THREAD

**Issue by VincenzoFerme** [docker/swarm#1007]
I followed the instruction reported on the [official Docker Swarm documentation](http://docs.docker.com.s3-website-us-east-1.amazonaws.com/swarm/install-manual/).

I am not able to get the **swarm** working correctly when the Docker daemon's exposed port on a node is different from 2375.

The command I run to join my node is:

```
docker run -d swarm join --addr=<node_ip>:2376 token://<cluster_id>
```

The command I run to start the master is:

```
docker run -d -p 2377:2375 -v <local_cert_path>:/cert/:ro swarm -debug manage --tlsverify --tlscacert=/cert/ca.pem --tlscert=/cert/cert.pem --tlskey=/cert/key.pem token:///<cluster_id>
```

The error I get, when the port is different from 2375 (as it is in the example), is:

```
time="2015-06-30T15:01:07Z" level=error msg="Get https://<node_ip>:2375/v1.15/info: dial tcp <node_ip>:2375: connection refused"
```

It seams that for some reason, the utilised port is always the 2375 one.

Thanks for the support.

**Comment by vieux** [comment]
@VincenzoFerme when you do a `swarm list token://<cluster_id>` do you see 2375 or 2376 ?

**Comment by VincenzoFerme** [comment]
@vieux 2375

**Comment by vieux** [comment]
@VincenzoFerme I don't know what to say besides "retry" I cannot reproduce:

```
$ swarm create
0aa4429e87dba4d5a58d5879bacdf6c2
$ docker run -d swarm join --addr=1.2.3.4:2376 token://0aa4429e87dba4d5a58d5879bacdf6c2
d15d1654cf0402bb68e2068b89d37a7e62bbb82935e9e747318589a9b531c48d
$ swarm list token://0aa4429e87dba4d5a58d5879bacdf6c2
1.2.3.4:2376
```

**Comment by VincenzoFerme** [comment]
@vieux you are right! I did again all the steps and it works as expected. I really don't see the difference from when I got the error....thank you!
