### ISSUE TITLE
Lists don't render properly on filters page

### ISSUE THREAD

**Issue by thaJeztah** [docker/swarm#1021]
originally reported by @alvinr here: https://github.com/docker/docker/issues/14192

# Problem

See 

![screen shot 2015-06-24 at 4 06 07 pm](https://cloud.githubusercontent.com/assets/336450/8367753/772a554c-1b56-11e5-83a4-39e841c3e4f7.png)

Looks like this should be a list but it is not formatted as a list. May be a generic issue across all lists - would need to be confirmed.

# Reproduce
See https://docs.docker.com/swarm/scheduler/filter/

**Comment by thaJeztah** [comment]
I had a quick look at the source of this document, and I think the problem here is that there's no blank line before the list; there are actually a number of lists in the document that miss a blank line and are not rendered properly.

@alvinr are you interested in creating a PR to fix this? Or do you want me to create one?

**Comment by vieux** [comment]
@moxiegirl
