### ISSUE TITLE
Manager leadership election can fail when paired with Consul 0.5.2

### ISSUE THREAD

**Issue by jsipprell** [docker/swarm#1025]
Using `swarm 0.4.0 (d0b0491)`, `docker 1.7.1-rc1` and `consul 0.5.2` w/ a multi-engine cluster that has two independent manager containers on different docker engines. Heartbeat and ephemeral timing are all unchanged from the defaults (20s and 60s, I believe).

If sufficient time passes (often > 30min or so) without a leadership change and the current primary manager is terminated, leadership election of the failover manager does not complete or does not fully complete and the following errors are logged:

From the swarm instance that should be in replica->primary transition:

> `manager_1 | time="2015-07-04T17:59:29Z" level=error msg="failed to acquire lock: Unexpected response code: 500 (rpc error: rpc error: Invalid session)" `

From the local consul client instance for that docker engine (logs are from two separate occurrences):

> `2015/07/04 15:44:26 [ERR] http: Request /v1/kv/docker/swarm/leader?acquire=3d2f35d7-48fd-031c-c60b-17eadf4f9a0b&flags=3304740253564472344, error: rpc error: rpc error: Invali
d session`

Best Regards,

Jesse

**Comment by aanm** [comment]
@jsipprell how many "Unexpected response code: 500" do you see?

**Comment by abronan** [comment]
Thanks @jsipprell, I will try to reproduce. I think that in that case, the key stays locked forever and the session is not released properly which leaves all other instances unable to lock the key in return.

In the meantime I'm working on changes for the Consul default Lock that we are using for the Leader Election process so it can use custom Sessions and not default ones. This way we are in control of what may happen in the background with sessions (like we do for ephemeral keys and discovery node entries).

**Comment by jsipprell** [comment]
@aanm AFAICT, there is only a single "Unexpected response code: 500" per incident (per consul/swarm/docker engine anyway).

**Comment by abronan** [comment]
@jsipprell Can you reproduce each time your run the cluster for a long time or is this occasional? I tried two times (using `master`) running the cluster for 2 hours and killing the current Primary would rightfully elect a new one. Could you try with the latest `master` and see if you can reproduce again? Thanks!

**Comment by jsipprell** [comment]
@abronan I'll rebuild from latest master and give it a shot.

Unfortunately, I've noticed there can be a very significant delay between occurrences. I just made it happen but it had been up for many hours w/out leadership change beforehand.

Here's a little more consul debug output context from right around the latest event:

> 2015/07/08 18:04:24 [DEBUG] http: Request /v1/kv/docker/swarm/leader?acquire=83165fd1-6f6a-bb34-fda8-b6e3e224bd0e&flags=3304740253564472344 (992.163µs)
> 2015/07/08 18:04:25 [DEBUG] memberlist: TCP connection from: 10.1.69.177:52545
>2015/07/08 18:04:29 [DEBUG] http: Request /v1/kv/docker/swarm/leader?index=374930&wait=15000ms (1.355243ms)
> 2015/07/08 18:04:29 [ERR] http: Request /v1/kv/docker/swarm/leader?acquire=83165fd1-6f6a-bb34-fda8-b6e3e224bd0e&flags=3304740253564472344, error: rpc error: Invalid session
> 2015/07/08 18:04:29 [DEBUG] http: Request /v1/kv/docker/swarm/leader?acquire=83165fd1-6f6a-bb34-fda8-b6e3e224bd0e&flags=3304740253564472344 (69.801361ms)
> 2015/07/08 18:04:30 [DEBUG] http: Request /v1/kv/docker/swarm/leader?index=379885&wait=15000ms (15.518667947s)
> 2015/07/08 18:04:37 [DEBUG] http: Request /v1/session/renew/5ea60f58-07c0-2024-858c-e6b8e731a6fc (927.324µs)```

Note that the session `5ea60f58-07c0-2024-858c-e6b8e731a6f` *did* show up on consul's session list prior to election event and, for a brief moment, this same uuid showed up in the `session` key of the json output from http://localhost:8500/v1/kv/docker/swarm/leader when the election occurred (logging is all from the node that was still running `swarm manage`)

**Comment by jsipprell** [comment]
I am able to intermittently reproduce the issue, _even at short time intervals_, however I cannot reproduce it consistently.

Therefore, I suspect the issue is likely caused by a race condition in consul's session handling related to numerous other simultaneous activities, although it is very likely an _expected_ race condition.

The consul documentation strongly suggests that session validity is not strongly deterministic, and that one should rigorously handle session failures and assert retries appropriately.

By slightly refactoring `Candidate.RunForElection()` (in `leadership/candidate.go`) into a private method and using this to add retry semantics which recreates the entire lock on failure (and thus the lock session) in `Candidate.campaign` (w/ a maximum retry rate of once-per-five seconds to prevent busy-wait looping), I was able to produce deterministic recovery even for this edge-case:

> manager_1 | time="2015-07-09T05:42:16Z" level=debug msg="Watch triggered with 3 nodes" discovery=consul 
> manager_1 | time="2015-07-09T05:42:26Z" level=debug msg="Watch triggered with 3 nodes" discovery=consul 
> manager_1 | time="2015-07-09T05:42:36Z" level=debug msg="Watch triggered with 3 nodes" discovery=consul 
> manager_1 | time="2015-07-09T05:42:39Z" level=debug msg="Updated engine state" id="A5OK:UA52:TH2D:ZAM4:YSIC:7VP5:SDOJ:L7CI:V4NL:3PQR:5CW2:455D" name=XXXXXX 
> manager_1 | time="2015-07-09T05:42:40Z" level=error msg="failed to acquire lock: Unexpected response code: 500 (rpc error: rpc error: Invalid session)" 
> manager_1 | time="2015-07-09T05:42:40Z" level=error msg="retrying election ..." 
> manager_1 | time="2015-07-09T05:42:40Z" level=info msg="Cluster leadership acquired" 
> manager_1 | time="2015-07-09T05:42:40Z" level=info msg="New leader elected: 10.1.76.140:2475" 

>> _("retrying election …" is emitted by the retry code I added)_

Some sort of retry mechanism is probably desirable irrespective of this specific issue in order to handle situations like the local consul client being restarted from underneath swarm or transient network events.

If interested I can provide a PR, although I suspect you'll want something a bit more elegant and design-specific (providing an api context or pass-through cancellation mechanism in libkv's `Locker` interface in order to prevent any lingering goroutine leakage comes to mind).

**Comment by aluzzardi** [comment]
ping @abronan

**Comment by abronan** [comment]
Closed by #1078 

@jsipprell Let us know if you still have an issue with Consul and feel free to reopen an issue if this is the case. Now no matter which one of the store you are using, it should retry after some time (on Lock failure, etc.).

**Comment by 14msitaqadeer** [comment]
i also hit with the issue like that, while installing consul on three different nodes:
ERRO[3353] discovery error: Unexpected response code: 500 (No cluster leader)
