### ISSUE TITLE
"No such image" error during build + push

### ISSUE THREAD

**Issue by tony-spataro-rs** [docker/swarm#1028]
I'm using swarm to build images and push them to DockerHub. For some reason I'm unable to push after building, even though `docker images` shows my newly-built image. Adding a 10s delay between build and push doesn't seem to help.

@aluzzardi asked me to add some debug output to my build; I've got a [gist with failing build output](https://gist.github.com/tony-spataro-rs/a34fed2c404b7fef66b4).

**Comment by vieux** [comment]
@tony-spataro-rs looks like it's a bug on swarm, we don't push all the tags. Right now to fix the issue please use `docker push rightscale/test1_service:experimental_didio`

**Comment by tony-spataro-rs** [comment]
Woo hoo; thank you, sir! I'll build swarm from master and test later this week.
