### ISSUE TITLE
key used by master election do not use the given path prefix

### ISSUE THREAD

**Issue by cloudfly** [docker/swarm#1037]
I want to start multiple swarm manager by using etcd.

eg.
```
swarm manager --replication --addr=127.0.0.1:2375 etcd://127.0.0.1:4001/myapp/swarm
```
the key used to elect master, is always `/docker/swarm/leader`, ignoring prefix `/myapp/swarm`

this is designed on purpose, or a negligence ?

**Comment by jimmyxian** [comment]
@cloudfly 
Etcd used here has two purposes:
* Used for discovery serivice:  The path is user defined `etcd://127.0.0.1:4001/myapp/swarm`
* Leader Election: The path is const `const leaderElectionPath = "docker/swarm/leader"`

**Comment by cloudfly** [comment]
@jimmyxian 
yes, I know.

same with `leaderElectionPath`, `discoveryPath` is also a const string in code.
```
 discoveryPath = "docker/swarm/nodes"
```

swarm-0.3 changed the discovery path, it join with prefix, now use `/myapp/swarm/docker/swarm/nodes`. 

but the `leaderElectionPath` not. 

swarm-0.3 now write two place on my etcd. so uncomfortable.

**Comment by jimmyxian** [comment]
@cloudfly 
Yeah, maybe we can use the same prefix.
ping @aluzzardi @abronan

**Comment by abronan** [comment]
I'm not in favor of using the same prefix for a simple reason: it can have a different meaning for both leader election and discovery. Using the leader election key with a `mydiscovery/` prefix does not make much sense in the context of leader election.

You might want to separate the key space for both mechanisms.

Right now we enforce it but a specific flag could be included for leader election if we want to modify the path with a given prefix.

**Comment by cloudfly** [comment]
I think it's necessary for user to custom the prefix for leader election path.  

It will be more convenient to manage the my path. I had save all my data under /my-cluster-name, and do not want anything outside of there.

**Comment by abronan** [comment]
@cloudfly Yes I think it's necessary too, adding a new flag you can then specify the same prefix for `discovery` and `leader election` so you can keep those under the same key space.

**Comment by vieux** [comment]
@cloudfly @abronan I agree not the exact same prefix, but why not append `/leader` to the current path, so in your example it would become `/myapp/swarm/leader` so we don't have to use another flag.

**Comment by cloudfly** [comment]
I do not know how others use swarm and etcd, here is mine.

My `etcd` serves several services, like swarm, calico and others. In order to seprarate  them,  I create `/myapp/swarm` for swarm-0.2, which used only by swarm. 

but swarm-0.3 now write the leader key outside there, and can not be custom. I don't think it's a good design.

my opinion is, user give a prefix, then
- discovery use `<prefix>/nodes/`
- election use `<prefix>/leader`

I feel this looks simple and better. but there maybe other users prefer separating them into different place. so adding a flag make users having a choice, more flexible. 

@vieux 's notion is good for me, I just want to use a new flag to realize like this.

**Comment by aluzzardi** [comment]
It should append the path to the prefix - if it doesn't, then it's a bug on
my side as this was the intended behavior.
