### ISSUE TITLE
Resolve domain names between containers

### ISSUE THREAD

**Issue by jossemarGT** [docker/swarm#1047]
Greetings!

I'm trying to make that certain containers resolve a domain name (which can't be wrote in the /etc/hosts because it has multiple subdomains) that points to other container, the easiest approach was to install dnsmasq in the host machine and use it, but, when we're talking about clustering (with swarm) I still trying to figure out what's the best way to accomplish the same task.

Does anyone can give me a hint?  Thanks in advance :octocat:

**Comment by icycrystal4** [comment]
-dns

**Comment by jossemarGT** [comment]
Thanks @icycrystal4 that's exactly what I'm doing, but, having it as container which changes its ip every up. 

That made me try another approach like having a core service pod which also has the dns container and only expose the host IP which is fixed. Actually I can't afford to have an external dns because I'm attempting to do "development boxes" which has to run locally.

I'll leave this issue open if swarm team don't mind, just in case someone else has a better approach.
