### ISSUE TITLE
Disable tls on token discovery with local token server.

### ISSUE THREAD

**Issue by wayerr** [docker/swarm#1060]
We use swarm with local token discovery service (yes, we use undocumented feature):
`swarm manage token://<host>/swarm_token_discovery/<clusterId>`
But we need to setup TLS and import CA on each node with swarm, because ['https' is hardcoded](https://github.com/docker/swarm/blob/master/discovery/token/token.go#L38). In local network it is an extra work.

**Comment by aluzzardi** [comment]
Out of curiosity - why not using consul, etcd or zookeeper instead of reimplementing the token protocol?

As for the problem itself, why not using a properly signed TLS certificate on the token server?

**Comment by wayerr** [comment]
> ... why not using consul ...

Our project already contains service discovery system, and in this case we can choice: reimplement token-based discovery, write plugin for swarm or port system to consul (etcd or zookeper). Of course we  chose most easy way.

>why not using a properly signed TLS certificate on the token server?

Obtaining of a signed certificate is outside the scope of liability of developers. Now we use self signed certificate, but swarm distributed as docker image, and it does not allow us to install our CA in to swarm image. Therefore we forced to use swarm compiled from sources.

**Comment by amitshukla** [comment]
Closing as this issue is very old. Please reopen if you are still need help/want to propose an enhancement.
