### ISSUE TITLE
Panic in Swarm Manager at (*Etcd).Watch call

### ISSUE THREAD

**Issue by wrotki** [docker/swarm#1064]
I ran 2 machine swarm  cluster (swarm version 0.3.0 (28cd51b)), using Etcd cluster management option overnight. The cluster initially works just fine, but then after some time (haven't determined how long yet - just started to dig in deeper) I start to  see the following panic happening very frequently (container runs with autorestart):

time="2015-07-16T04:03:35Z" level=info msg="Listening for HTTP" addr=":2375" proto=tcp 
time="2015-07-16T04:03:35Z" level=info msg="Cluster leadership lost" 
time="2015-07-16T04:03:35Z" level=info msg="New leader elected: 54.205.93.129:3376" 
time="2015-07-16T04:03:36Z" level=info msg="Registered Engine ip-10-111-168-185 at 54.160.255.230:2375" 
time="2015-07-16T04:03:36Z" level=info msg="Registered Engine ip-10-101-152-104 at 54.205.93.129:2375" 
time="2015-07-16T08:24:45Z" level=error msg="Unable to update state of container \"ee96d9f43ac6c13b184cdc8da76cdcd30125c24f28772d9a2d6e7748335b3d44\"" id="HCNL:7JUS:WX7D:36JY:BWJS:PIXD:PNAW:6SHM:EZ4P:LR2A:SA3B:SCJS" name=ip-10-101-152-104 
time="2015-07-16T10:02:54Z" level=error msg="Unable to update state of container \"4a438cfeec23d871ffe11b67faa21fec8bc62e0d776d3a3215b92fac35475cc4\"" id="HCNL:7JUS:WX7D:36JY:BWJS:PIXD:PNAW:6SHM:EZ4P:LR2A:SA3B:SCJS" name=ip-10-101-152-104 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x47f81b]

goroutine 66 [running]:
runtime.panic(0x963280, 0xcd5d33)
	/usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/docker/swarm/pkg/store.func·004()
	/go/src/github.com/docker/swarm/pkg/store/etcd.go:204 +0x13b
created by github.com/docker/swarm/pkg/store.(*Etcd).Watch
	/go/src/github.com/docker/swarm/pkg/store/etcd.go:212 +0x294

goroutine 16 [chan receive, 383 minutes]:

**Comment by vieux** [comment]
ping @abronan

**Comment by abronan** [comment]
Thanks for reporting @wrotki! This should be solved in the latest **master**. It happens that etcd might return a nil pointer for values during network hiccups and connectivity issues with the store. This has been fixed in docker/libkv#17.

**Comment by wrotki** [comment]
Super. Thanks - let me try with the latest then.

**Comment by abronan** [comment]
:+1:

**Comment by wrotki** [comment]
My test setup has survived the night under low albeit constant load with swarm built from the recent master without nil pointer panics, so I think the fix mentioned earlier was the right one. Closing - thanks a lot!
