### ISSUE TITLE
Replace references to boot2docker with docker-machine

### ISSUE THREAD

**Issue by moxiegirl** [docker/swarm#1072]
`boot2docker` is replaced with `docker-machine` in 1.8 `boot2docker` is deprecated.

```
./swarm/docs/install-w-machine.md:	This example was run a Mac OSX system with `boot2docker` installed. So, the
./swarm/docs/install-w-machine.md:		`dev` environment in the list represents the `boot2docker` machine.
```

**Comment by moxiegirl** [comment]
ping @vieux @aluzzardi this needs to go into the 1.8 content

**Comment by abronan** [comment]
Just mentioning *Docker Toolbox* is a little bit confusing, this should be more specific and mention `docker-machine` directly (just trying to think as a new user of Docker and Swarm, I would google Docker Toolbox and find unrelated things instead). Or could this be a link to `docker-machine` releases maybe?

**Comment by MHBauer** [comment]
I can say that as a someone new to docker & swarm, and on osx; I do not know what /Docker Toolbox/ is. If there's a plan to completely describe that somewhere, it should be fine.

I did have a very easy time using `docker-machine` to create a swarm and run some workloads on it. So far so good on that front.

**Comment by moxiegirl** [comment]
@abronan @MHBauer  Docker Toolbox is the name of the new installer for Windows and Mac.  It will have an explicit mention in the installer guide where that is appropriate in docker/docker.  For the Swarm material I'll be doing a PR shortly to replace the references to the boot2docker in the install-w-machine.md file.

**Comment by abronan** [comment]
@moxiegirl OK thanks for clarifying :+1:

**Comment by moxiegirl** [comment]
np. Toolbox is moving fast so it is hard to keep up. :-)
