### ISSUE TITLE
REST API equivalent to swarm join

### ISSUE THREAD

**Issue by gdmurali** [docker/swarm#1076]
Hi,

 I would like to add a Docker Host(Register it ) to Swarm Manager like below
./swarm join --advertise=10.192.14.181:2375 token://6fae3c32908e47c9daf43ca6e116747c

Above works fine when I use swarm binary.

I would like to know if REST API exists to do same ? to join a docker host to a cluster ?

Murali G D

**Comment by vieux** [comment]
Hi @gdmurali 

yes, the doc is here: https://github.com/docker/swarm/tree/master/discovery/token#add-new-nodes-to-a-cluster

**Comment by chanwit** [comment]
@gdmurali shall we close this issue?

**Comment by gdmurali** [comment]
Sure.
