### ISSUE TITLE
containers on 'host down' amazon machine

### ISSUE THREAD

**Issue by agsmorodin** [docker/swarm#1083]
When I create a machine on amazon cloud, create a couple of containers on it and then terminate the machine using :
docker-machine rm swarm-01 
I still see containers on swarm-master with remark 'host down':
2a3946288f05        nginx:latest   "nginx -g 'daemon of   17 hours ago        Host Down           443/tcp, 10.10.92.199:32768->80/tcp   swarm-01/dockermachine_worker_2

And it's not possible to stop/remove this unreachable container from the list using docker rm or docker stop. 
docker stop 9576211d7b3f
Error response from daemon: Post https://10.10.92.5:2376/v1.18/containers/9576211d7b3f00b423d8a52698bc23db1829e062a82268d39861d8b329839ede/stop?t=10: dial tcp 10.10.92.5:2376: no route to host
The problem is clear because host is down. But it will not be UP never. 

There is only one solution that is working for me:  if I restart swarm-master machine unreachable containers disappear from the list.  
I stopped the machine manually and I understand that  properly I should stop containers on this machine firstly. But lets' imagine that something accidentally happened with machine and we need to remove the unreachable docker instances from swarm cluster. Is there a the proper way to do it?

**Comment by abronan** [comment]
Hi @agsmorodin, this is a known issue if you are using `docker-machine` paired to swarm `0.2.0` or `0.3.0` using simple discovery methods (file, token, etc.). If you want your machines to be removed from your cluster, for now you have to use *Consul*, *etcd* or *Zookeeper* when provisioning your `docker-machine` cluster.

You can do that by first creating a Consul instance somewhere and the using the discovery flag in docker-machine:

```
docker-machine [...] --swarm-discovery consul://<ip>:8500/nodes
```

This way, Swarm Agents leaving the cluster will be removed from the agent list by the Swarm Manager and you will not see unavailable containers.

**Comment by aluzzardi** [comment]
Hi @agsmorodin, this should work now with the latest swarm.

Please let us know if it doesn't
