### ISSUE TITLE
Create an experimental tag on dockerhub

### ISSUE THREAD

**Issue by aanm** [docker/swarm#1084]
Is it possible to have a new tag called `experimental` so we can use the latest swarm binary? Thanks

**Comment by vieux** [comment]
@aanm it's `dockerswarm/swarm:master` as of right now you cannot combine library images with automated builds /cc @tianon

**Comment by aanm** [comment]
@vieux At least is something for debugging. Thank you :)

**Comment by aluzzardi** [comment]
ping @tianon on library + automated builds

@aanm As @vieux mentioned, we have `dockerswarm/swarm:master` plus release candidates (`swarm:0.4.0-rc1`) and that's pretty much all we can do so far.

**Comment by aanm** [comment]
@aluzzardi I thought I had close this. `dockerswarm/swarm:master` is good enough for me, thanks :-)
