### ISSUE TITLE
How do I remove *all* the docker swarm information?

### ISSUE THREAD

**Issue by mpilant** [docker/swarm#1086]
I'm running an Ubuntu 14.04 LTS VM and I had installed Docker.  In the process of doing swarm testing I have managed to have a lot of old (obsolete) information from previous swarm incarnations.  I would like to remove it so I *know* there is no old information laying around which might cause problems (or confuse me :-)
I thought that by removing docker all the swarm information would be removed as well.  Unfortunately, that is not the case.  After removing and installing Docker all over, when I do a "swarm list" with the "old" token/ID, the old nodes still show up.
So, what do I need to clean up to *completely* remove all the old Docker information?  (It is not all in /var/lib/docker as I found out.)
Thanks in advance.
- Mark

**Comment by MHBauer** [comment]
I'm just learning, but I think I know the answer to this.

The swarm tokens and the associated machines are stored on a server.

See here https://github.com/docker/swarm/tree/master/discovery/token

From what I understand, when using the token discovery service, you cannot do anything but add nodes. Which means you cannot remove nodes, or release the token.

**Comment by aluzzardi** [comment]
@MHBauer: Nodes are going to disappear after a while when you stop `docker join` (after the TTL which by default is 60 seconds I believe)

**Comment by aluzzardi** [comment]
@mpilant Does that solve the issue?
