### ISSUE TITLE
TLS authentication only for client→manager

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/swarm#1089]
#question

Is there a way to set up TLS authentication only for client-to-manager communications and not manager-to-node? I already secured my slave nodes behind a firewall and only managers and peer nodes can talk to them. However I still need to secure client-to-manager auth.

Looking at the docs at http://docs.docker.com/swarm/install-manual/#tls, looks like it's not possible –it's either all or none.

Is there a way to support this? If not, would we be open to a proposal like this to configure TLS only for the manager frontends?

**Comment by aluzzardi** [comment]
Good question. The reason we made that call was to avoid flag *explosion*.

TLS flags are already bad as it is (`--tls --tlscacert --tlscert --tlskey --tlsverify`) and we wanted to avoid duplicating those and ending up with 10 different flags (`--tls-client-cert`, `--tls-server-cert` and so on).

Thoughts?

**Comment by aluzzardi** [comment]
ping @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
@aluzzardi looks like this choice is not bad at all and looks like it's serving fine. However I think for someone who only wants to secure the cluster frontend (i.e. managers), maybe we can have a way to disable the manager&rarr;node TLS communication with a flag like `--disable-nodes-tls`? (I'm pretty sure someone else come up with a better name)

**Comment by ahmetalpbalkan** [comment]
Looks like I might contribute something like this, are maintainers OK with such a feature implementation?

**Comment by amitshukla** [comment]
@ahmetalpbalkan it's been a long time getting back to you. Please do make a proposal!

**Comment by ahmetalpbalkan** [comment]
@amitshukla I no longer need this, I basically did security through SSH tunneling to managers and all nodes are behind a firewall. It's not super secure but it's not too bad either. If someone else is interested in proposing something, please feel free to take up.

**Comment by crewjam** [comment]
So I have the inverse problem ... I want TLS between the manager and docker daemons, but I want the manager to listen on a plaintext unix socket (I plan to use ghostunnel in front of the manager). Would there be an interest in a patch that adds `--disable-nodes-tls` and `--disable-server-tls` ?

Alternately for my use case, a patch that disables TLS for unix sockets would work, but that may not be general enough for others.

**Comment by ahmetalpbalkan** [comment]
No need for this anymore.
