### ISSUE TITLE
Multiple IPs to consul:// silently discarded

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/swarm#1091]
Followup to https://github.com/docker/swarm/pull/1087#issuecomment-125299274: 

`swarm join --help` (v0.3) documents that `consul://<ip>/<path>` is the schema for consul discovery backend; however when multiple IPs are passed, they are silently discarded and `swarm join` keeps running by using the first IP addr and discarding others.

Not giving any error actually is misleading and `join` should fail if multiple IPs are specified. 
cc: @abronan 

```
ahmet@swarm-master-0:~$ docker inspect compose_swarm_1 | head -n 12
[
{
    "Id": "8122b9bb9930e2ca419702d91555bc92c87538bf92c4bf29f438a9af175cbb99",
    "Created": "2015-07-26T02:11:20.3822512Z",
    "Path": "/swarm",
    "Args": [
        "manage",
        "--replication",
        "--advertise",
        "10.0.0.4:2376",
        "consul://10.0.0.4:8500,10.0.0.5:8500,10.0.0.6:8500/nodes"
    ],
```

**Comment by aanm** [comment]
I honestly thought this would only work with 1 IP.

**Comment by aluzzardi** [comment]
ping @abronan
