### ISSUE TITLE
Docker swarm not working on Microsoft Azure

### ISSUE THREAD

**Issue by mpilant** [docker/swarm#1095]
I'm trying to get Docker Swarm running on Azure and it seems to be "half" working.  By this I mean I can create the swarm, join all the nodes to the swarm, manage/start the swarm, and the IP/ports show up correctly with "swarm list".  However when I do an "info" to the swarm manager port, on the system running the swarm manager, the manager reports no nodes.
I'd try to look in the log files, but I can't seem to find them :-(
Thank in advance.
- Mark

**Comment by abronan** [comment]
Hi @mpilant, both issues (with #1096), look like you are not configuring TLS correctly thus the Manager cannot contact the Swarm Agents and get back informations to list those nodes in `docker info`.

**Comment by mpilant** [comment]
Hi @abronan. At the moment, I have Docker configured to use TLS, and I can it to remotely interact with the individual nodes without any problems. So I believe it is configured properly. The problems seem to be with trying to set up a swarm. This is one area where the documentation I have found (from Docker, Microsoft, etc.) is really pretty poor. Almost all is really good at describing the commands to use not not very good at describing what the arguments and options of the command are given and what they are supposed to do.  (Same as #1096.)

**Comment by mpilant** [comment]
Update: I have managed to create a Docker swarm on a bunch of VMs, not on Azure.  I did this mainly to make sure I could in fact deploy a working swarm.  The major difference is my local deployment did not use TLS/certificates for communications where the Azure Docker VM extension does.

Attempting to replicate the deployment, so far, has met with failure.  But, it does appear to be certificate related.  Not with the certificates used to communicate with Docker, but the certificates (or lack thereof) swarm uses.

Still investigating.

**Comment by mpilant** [comment]
Well, some more progress; after a fashion.
I just finished trying to create a swarm on Microsoft Azure using Docker Machine on an Ubuntu 14.04 LTS system.  I created three VMs: a swarm master and two swarm nodes.  (Using the information here: https://github.com/chanezon/azure-linux/blob/master/docker/swarm.md.)  The results were *not* encouraging.
All of the VMs were created successfully, the swarm was created and only one node was joined to the swarm (doing a ps -a on the swarm manager showed only one swarm join done).  Using "swarm list" showed all three VMs as expected, but doing an "info" on the swarm manager VM (as per the web page) did not show any nodes in the swarm.  This is the same thing I had happen trying to set up a swarm using the Azure CLI.
Given my recent Azure / Docker experiences, I'm assuming "something" has been broken, and will probably be fixed "sometime" in the future.  But for now, unless someone can demonstrate otherwise, my testing seems to indicate Docker Swarm is broken on Microsoft Azure.

**Comment by agup006** [comment]
@mpilant when using Docker Machine to spin up the swarm did you open 3376 endpoint in Azure manually? Docker Machine does not configure the endpoint for the swarm master - here is my pull request that enables this to happen automatically: https://github.com/docker/machine/pull/1647

**Comment by mpilant** [comment]
@agup006 Yes, I opened port 3376.
I don't think this exclusively a port problem.  I was getting very similar results when I was trying to manually set up a swarm using just the Azure CLI or the Azure portal (create VMs) and Azure CLI (using Docker).

**Comment by mpilant** [comment]
Given a couple of the subtle (unannounced) changes accompanying the new Docker VM Extension which cause me a great deal of grief, it would not at all surprise me if there are other bugs (sorry, undocumented features :-) as well.  Of course they may be completely unrelated.

**Comment by agup006** [comment]
@mpilant what version of machine are you using, and what Azure Region? I was able to run "docker info" for my Ubuntu 14.04 Docker Swarm with no similar issue

```
docker info
Containers: 5
Images: 6
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 4
 anugup-swarm-01: anugup-swarm-01.cloudapp.net:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.721 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-36-generic, operatingsystem=Ubuntu 14.04.1 LTS, provider=azure, storagedriver=aufs
 anugup-swarm-02: anugup-swarm-02.cloudapp.net:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.721 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-36-generic, operatingsystem=Ubuntu 14.04.1 LTS, provider=azure, storagedriver=aufs
 anugup-swarm-03: anugup-swarm-03.cloudapp.net:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.721 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-36-generic, operatingsystem=Ubuntu 14.04.1 LTS, provider=azure, storagedriver=aufs
 anugup-swarm-04: anugup-swarm-04.cloudapp.net:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.721 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-36-generic, operatingsystem=Ubuntu 14.04.1 LTS, provider=azure, storagedriver=aufs
CPUs: 4
Total Memory: 6.884 GiB

```

**Comment by mpilant** [comment]
@agup006 I am trying to run in the East US region.
Docker-machine was downloaded this morning and is  0.4.0-rc2 (c2b5f06).

**Comment by mpilant** [comment]
My problems could very easily be something I am doing incorrectly.  However, from all of the examples I have seen (Azure CLI or docker-machine) I have not been able to spot what I might be doing wrong.

**Comment by mpilant** [comment]
@agup006 Question: is this swarm one you had previously created or was it recently (say the past several days) created?

**Comment by agup006** [comment]
@mpilant This was a swarm I created yesterday, in the West US Region. I'll give East US Region a try with the version mentioned and see if I can repro.

```
docker ps -a
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                                    NAMES
d4b8cf6548c0        swarm:latest        "/swarm join --addr    16 hours ago        Up 16 hours         2375/tcp                                 anugup-swarm-02/swarm-agent
4bbb36bf7e56        swarm:latest        "/swarm join --addr    16 hours ago        Up 16 hours         2375/tcp                                 anugup-swarm-04/swarm-agent
ca9454ea0ede        swarm:latest        "/swarm join --addr    16 hours ago        Up 16 hours         2375/tcp                                 anugup-swarm-03/swarm-agent
6ba69ebeec82        swarm:latest        "/swarm join --addr    16 hours ago        Up 16 hours         2375/tcp                                 anugup-swarm-01/swarm-agent
8311b5abc7ab        swarm:latest        "/swarm manage --tls   16 hours ago        Up 16 hours         2375/tcp, XXX.XXX.XXX.XXX:3376->3376/tcp   anugup-swarm-01/swarm-agent-master

```

**Comment by mpilant** [comment]
@agup006 Interesting.  If you could put together a list of the commands you used I'll compare it with what I tried to see if I can spot any differences.  I have no problem being proven wrong :-P

**Comment by agup006** [comment]
@mpilant Sure I'll put together a list of steps and send that out later tonight, hopefully can get this resolved :)

**Comment by agup006** [comment]
Hi @mpilant  I put together a blog post over docker swarm. Let me know if you find it useful: http://agup.tech/docker-machine-docker-swarm-azure-walkthrough/

**Comment by abronan** [comment]
Sorry for catching up late on this, thanks for the blog post @agup006! This might help a lot of people running docker on Azure and willing to setup a Swarm.

**Comment by mpilant** [comment]
@agup006 Well, still not working but I did uncover some interesting things.
First, after I cleaned out all the VMs, cloud services, etc. from previous testing (there were no resources listed by the Azure portal for the subscription), when I attempted to create a new VM (using docker-machine), I could not because docker-machine said the name was in use.  So it would appear this information is persisting somewhere other than Azure,  Whether on the local machine or somewhere else on the Internet I do not know.
Second, I created all swarm VMs using the swarm ID from one of my previous tests.  Using "docker-machine ls" reports all of the VMs which have every used that ID.  So it would also appear here this information is persisting somewhere... local or the Internet I don't know.
Third, once all the VMs are part of the swarm, it is a bit (10-15 seconds) before "docker-machine ls" reports the systems as running.
Is the 3376 endpoint still needed?  It isn't mentioned in the blog post.  (I did add it, just in case.)
Because this problem feels like a certificate problem, I recreated the certificate to be uploaded to Azure.  The CN of the certificate was the DNS name of the swarm master.  This didn't seem to help at all.
So I'm going to try and start all over, creating a new swarm to get a new swarm ID, and then try the steps in your post again.  BTW, here are the docker-machine commands I used:
docker-machine create -d azure \
--azure-subscription-id "AZURE_SUBSCRIPTION_ID" \
--azure-subscription-cert "/home/auser/mycert.pem" \
--swarm --swarm-discovery token://SWARM_ID \
--swarm-master lmp-swarm-master-a
docker-machine create -d azure \
--azure-subscription-id "AZURE_SUBSCRIPTION_ID" \
--azure-subscription-cert "/home/auser/mycert.pem" \
--swarm --swarm-discovery token://SWARM_ID \
lmp-swarm-node-b
docker-machine create -d azure \
--azure-subscription-id "AZURE_SUBSCRIPTION_ID" \
--azure-subscription-cert "/home/auser/mycert.pem" \
--swarm --swarm-discovery token://SWARM_ID \
lmp-swarm-node-c

With my Azure subscription ID and swarm ID substituted as appropriate.

**Comment by agup006** [comment]
@mpilant I accidentally made two Swam Masters and found a similar behavior to what you mentioned. Is it possible the Swarm Token is no longer valid? Definitely try regenerating that token and let me know what you get.

Also definitely forgot 3376 part for the blog, thanks

**Comment by agup006** [comment]
@mpilant Also as a double check -- in Azure the service and VM were both removed?

**Comment by mpilant** [comment]
"docker-lachine ls" persisting information answer: On my local system, I found a number of directories in ~/.docker/machine/machines/ containing information for test systems I  had previously created and removed.  I just cleaned out all the directories (as well as the files in ~/.docker/machine/certs/) and started to create the swarm again.

**Comment by agup006** [comment]
Ah, removing hosts with  `docker-machine rm` is really nice as it will remove the service and VM from Azure.

**Comment by mpilant** [comment]
OK.  Still no joy.  Here is what I did:
export SWARM_ID="NEW_SWARM_ID"
export AZURE_ID="AZURE_SUBSCRIPTION_ID"

openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout mycert.pem -out mycert.pem
openssl pkcs12 -export -out mycert.pfx -in mycert.pem -name "My Certificate"
openssl x509 -inform pem -in mycert.pem -outform der -out mycert.cer

docker-machine create -d azure \
--azure-subscription-id $AZURE_ID \
--azure-subscription-cert /home/auser/mycert.pem \
--swarm --swarm-discovery=token://$SWARM_ID \
--swarm-master foo-swarm-master
docker-machine create -d azure \
--azure-subscription-id $AZURE_ID \
--azure-subscription-cert /home/auser/mycert.pem \
--swarm --swarm-discovery=token://$SWARM_ID \
foo-swarm-node-01
docker-machine create -d azure \
--azure-subscription-id $AZURE_ID \
--azure-subscription-cert /home/auser/mycert.pem \
--swarm --swarm-discovery=token://$SWARM_ID \
foo-swarm-node-02
Again, the CN for the cert is foo-swarm-master.cloudapp.net, so I don't *think* the cert is the problem.
Can you spot anything I've screwed up?  (I've been staring at this for so long, I may be missing something obvious.)

**Comment by mpilant** [comment]
This was done after cleaning out everything from Azure.

**Comment by mpilant** [comment]
Curiously, only one of the two swarm nodes appear to have been joined to the swarm.  In other words, a "docker ps -a" to the swarm master system shown only the "swarm manage" container and a single "swarm join" container.  (When I created a swarm locally, there was one for each swarm node.)

**Comment by agup006** [comment]
The CN for my cert is blank, but I'm not sure if having a CN set to something else would cause any of this -- as long as the cert is the same one uploaded in the Azure management portal. The commands look good from my point of view, nothing standing out.

**Comment by mpilant** [comment]
@agup006 OK.  The cert was the same one uploaded to the management certificates.  I'll blow away everything... again :-P and try the same thing with a blank CN.

**Comment by mpilant** [comment]
This is really strange.  Yesterday I cleaned out all of the "old" testing from Azure and my host system and started to create a new swarm using a blank CN in the certificate.  Finishing up this morning, I'm getting the same result as earlier: docker-machine ls originally showed the systems as running and now shows them all as "Timeout", docker ps -a on the swarm master VM only shows one of the two created swarm nodes as having joined the swarm, swarm list shows all the systems as expected, and docker info does not show any cluster information.
I think it may be useful to let this all sit for the weekend and try again Monday.  Maybe it will work because the phase of the moon is different :-P

**Comment by abronan** [comment]
@mpilant We are getting there :ghost: 

I'd really suspect a connectivity issue somehow because it seems now that you are doing it right with certs. Make sure that the remote docker daemons are available over TCP, well set up with certs, and that the correct ports are open. Also check `ufw` or `iptables` rules.

`swarm list` only requests the node list from the Token Service or the backend K/V store. Thus, having it list entries does not mean that the manager can contact remote nodes. If `docker info` does not show any node entry or an incomplete list of nodes: this is very likely that there is a connectivity issue from the Manager to some of the nodes :)

**Comment by mpilant** [comment]
@abronan It is almost certainly a connectivity issue, but where is the big question.  In this case, and others, I can interact directly with the Docker daemon on the VMs.  It is only the swarm manager which appears to be having problems.  In other words, I can do a "docker ps -a" to each of the individual VMs and get back the expected results.  However Docker swarm doesn't work properly.
BTW, this is exactly the same problem I was having when I was creating the swarm manually as opposed to using docker-machine.

**Comment by mpilant** [comment]
Solution: Use a different Azure subscription.  For some reason, it appears my corporate Azure subscription has "limitations".  Using my MSDN Azure subscription I was able to successfully create a swarm using the blog entry from @abronan (thank you very much).

Unfortunately, this is not the first time I have seen this "problem".  So my next task is to find out how to compare the features and capabilities of two different Azure subscriptions.  But that is not for this forum :-)

**Comment by agup006** [comment]
Super Interesting -- I wonder if there is difference in the provisioning return output from that subscription. Might even be an administrator setting set for that account? I'll keep plugged in as I'm interest myself :).
