### ISSUE TITLE
Swarm commands should error out if token flag does not contain "://"

### ISSUE THREAD

**Issue by dockermikeg** [docker/swarm#1097]
The "--swarm-discovery token://<token>" option should error out if the user does not specify "token://".  

I have watched two people complete the Swarm "Getting Started" guide, and both specified "token:flkajdkasdl" instead of "token://flkajdkasdl".

For both cases, the individuals were confused by the documentation, and thought the '//' meant that the token value was a comment.  They didn't realize that :// is required.

To avoid confusion, the command should terminate with an error when 'token://' does not include the double-slashes.

**Comment by MHBauer** [comment]
I think that's a flag for `docker-machine` and not swarm, but swarm also gets passed tokens.

**Comment by nathanleclaire** [comment]
Fixed in : https://github.com/docker/machine/pull/1606 thanks @hairyhenderson!
