### ISSUE TITLE
Container names in description and example don't match

### ISSUE THREAD

**Issue by harishjayakumar** [docker/swarm#1100]
https://docs.docker.com/swarm/scheduler/filter/
Under container affinity  , the description goes " For example, you can start a container called frontend running nginx:" but the shell prompt below creates a container called front. It should be frontend. The rest of the example continues with frontend, so its a bit confusing. The command should be changed from:
$ docker run -d -p 80:80 --name front nginx
to:
$ docker run -d -p 80:80 --name frontend nginx

**Comment by MHBauer** [comment]
This is already fixed by a65766e6862279245ea26ce6a300e96ddbd56446

**Comment by aluzzardi** [comment]
Fixed in #959
