### ISSUE TITLE
swarm list does not see other nodes on one node

### ISSUE THREAD

**Issue by laktak** [docker/swarm#1105]
I've set up a cluster with three nodes, each running consul and swarm.

When I run `docker run --rm swarm -l debug list consul://10.246.246.173:8500/swarm` one node (10.246.246.174) will only see itself:

```
time="2015-07-30T06:30:35Z" level=debug msg="Initializing discovery service" name=consul uri="10.246.246.173:8500/swarm" 
time="2015-07-30T06:30:35Z" level=debug msg="Initializing store service" backend=consul 
time="2015-07-30T06:30:36Z" level=debug msg="Watch triggered with 1 nodes" discovery=consul 
10.246.246.174:2375
```

while the others see all:

```
time="2015-07-30T06:33:07Z" level=debug msg="Initializing discovery service" name=consul uri="10.246.246.173:8500/swarm" 
10.246.246.173:2375
10.246.246.177:2375
10.246.246.174:2375
```

Notice that one says `Initializing store service` while the others do not.

When running `curl http://10.246.246.173:8500/v1/kv/swarm?recurse\&pretty` I see that the node with the problems is registered with a session and a different key:

```
[
    {
        "CreateIndex": 17,
        "ModifyIndex": 61,
        "LockIndex": 0,
        "Key": "swarm/10.246.246.173:2375",
        "Flags": 0,
        "Value": "MTAuMjQ2LjI0Ni4xNzM6MjM3NQ=="
    },
    {
        "CreateIndex": 19,
        "ModifyIndex": 62,
        "LockIndex": 0,
        "Key": "swarm/10.246.246.177:2375",
        "Flags": 0,
        "Value": "MTAuMjQ2LjI0Ni4xNzc6MjM3NQ=="
    },
    {
        "CreateIndex": 14,
        "ModifyIndex": 63,
        "LockIndex": 1,
        "Key": "swarm/docker/swarm/nodes/10.246.246.174:2375",
        "Flags": 0,
        "Value": "MTAuMjQ2LjI0Ni4xNzQ6MjM3NQ==",
        "Session": "bfc810a9-f26b-ec36-ce29-1ed684ffa61d"
    },
    {
        "CreateIndex": 16,
        "ModifyIndex": 27,
        "LockIndex": 0,
        "Key": "swarm/",
        "Flags": 0,
        "Value": null
    }
]
```

I can't find any errors in the logs and `docker exec consul consul members` is the same on all nodes:
```
Node     Address              Status  Type    Build  Protocol  DC
dev-do3  10.246.246.177:8301  alive   server  0.5.2  2         dc1
dev-do1  10.246.246.174:8301  alive   server  0.5.2  2         dc1
dev-do2  10.246.246.173:8301  alive   server  0.5.2  2         dc1
```

All the nodes are the same (IMHO) so I don't understand why the first one behaves differently. I also set this up multiple times and it's always the same node that does not see the others.

**Comment by vieux** [comment]
@laktak are you sure you are using the last version of swarm on all you nodes ? maybe you need to docker pull swarm on node 10.246.246.174

**Comment by abronan** [comment]
Hi @laktak, as @vieux suggested, can you check the version of the swarm image on the first node? It seems that the first node is not `latest` thus it is affected by a bug that has been fixed while other nodes are fine because they use the most recent version. Just a guess but let us know if this is the case :smile:

Same goes about your agents, try to pull the `latest` swarm image or the latest `rc`.

Also you might want to clean your Consul while trying again because the first two nodes must be attached to a session (the session holds the TTL so that nodes can be removed if they don't renew their TTL).

**Comment by laktak** [comment]
@vieux @abronan Sure enough I forgot to pull. Not sure how I missed that, sorry for wasting your time. After doing that and clearing consul, everything is now working. Thanks!

**Comment by abronan** [comment]
@laktak No worries, glad it works now. Let us know if you run into any trouble with the latest `rc` ;)
