### ISSUE TITLE
Failed to build swarm with latest code in master and even release package

### ISSUE THREAD

**Issue by eric-nuaa** [docker/swarm#1108]
Hi,

I tried to build swarm with its latest code in master, but it failed:
```
stack@swarm1:~/gocode/src/github.com/docker$ git clone https://github.com/docker/swarm 
Cloning into 'swarm'...
remote: Counting objects: 10506, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 10506 (delta 8), reused 0 (delta 0), pack-reused 10477
Receiving objects: 100% (10506/10506), 5.62 MiB | 184.00 KiB/s, done.
Resolving deltas: 100% (5827/5827), done.
Checking connectivity... done.
stack@swarm1:~/gocode/src/github.com/docker$ cd swarm/
stack@swarm1:~/gocode/src/github.com/docker/swarm$ godep go install . 
# github.com/docker/libkv/store/etcd
Godeps/_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:83: unknown net.Dialer field 'KeepAlive' in struct literal
Godeps/_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:85: unknown http.Transport field 'TLSHandshakeTimeout' in struct literal
# github.com/mesos/mesos-go/detector
Godeps/_workspace/src/github.com/mesos/mesos-go/detector/standalone.go:73: unknown http.Client field 'Timeout' in struct literal
godep: go exit status 2
```

Then I tried to download v0.4.0-rc1, v0.3.0 and built, but failed too with the same error. So far the only one I can build successfully is v0.2.0. But I want to try the latest features of swarm.

Can anyone help? How can I build latest swarm code?

Thanks!

**Comment by abronan** [comment]
Hi @eric-nuaa, do you still have this error with `godep go install ./...`?

**Comment by FreedomWangLi** [comment]
Hi @eric-nuaa, What is the version of golang you used  to build? I also meet this issue yesterday, and I have fixed this issue in patch https://github.com/docker/swarm/pull/1107, you can refer it to have a try again.

**Comment by jimmyxian** [comment]
@eric-nuaa 
You have to upgrade golang to 1.4 in you environment.

**Comment by eric-nuaa** [comment]
Thanks @FreedomWangLi , the steps in your patch works good for me :+1:
