### ISSUE TITLE
CLI freeze with `-it`

### ISSUE THREAD

**Issue by cpuguy83** [docker/swarm#1121]
I ran into an issue with a 3-node swarm (1 in DO, 2 in Vbox, master was in vbox) setup via docker-machine.
Basically doing a simple `docker run -it --rm debian:jessie` and then trying to exit caused the docker CLI to completely freeze, couldn't ctrl-c or anything.
Had to `kill -9` the docker client from another terminal. Upon doing this that terminal the client was using was fubar'd as well.
Once I got to this state, any time I did the above command I would get a CLI freeze upon exit.

Removing the cluster machines and creating a new cluster resolved the issue.

**Comment by aluzzardi** [comment]
Thanks @cpuguy83 - maybe related to #792 and #767 

What's your setup ? As in, is the CLI running on a different machine than Swarm, is Swarm running on a container, what OS is the CLI running on, etc.

Thanks

**Comment by cpuguy83** [comment]
CLI is running on OSX.

Swarm on all 3 nodes were setup by machine and running in a container.
1 swarm node was in digital ocean, 2 were in virtualbox.
Master was in virtualbox.

**Comment by aluzzardi** [comment]
Thanks for the input, will try to reproduce using the same setup

**Comment by aluzzardi** [comment]
Hey @cpuguy83 - I believe we can close this down?

**Comment by cpuguy83** [comment]
Yep.
