### ISSUE TITLE
Docker Swarm documentation clarification

### ISSUE THREAD

**Issue by ddgnani** [docker/swarm#1125]
https://docs.docker.com/swarm/install-w-machine/

Section: Generate a discovery token using the Docker Swarm image.

I think it will help to point out at this section it uses Docker Hub based service discovery. It took a while to understand where the token generated is stored and how it is referred as part of adding nodes.

Thanks.

**Comment by marcomusso** [comment]
+1

**Comment by abronan** [comment]
Thanks for the feedback @ddgnani :)

/cc @moxiegirl
