### ISSUE TITLE
new nodes are not showing up in cluster but i can see them on https://discovery-stage.hub.docker.com/v1/clusters/<mytoken>

### ISSUE THREAD

**Issue by shashiranjan84** [docker/swarm#1129]
I created a swarm cluster some time back. To scale out I planned add two more nodes to swarm. 

I used following command to add new node 

sudo docker -H tcp://0.0.0.0:2375 run -d swarm join --addr=<node>:2375 token://<token>

I see new nodes on discovery hub with previous created nodes but when i query master node(docker info), it does not show the new nodes.

**Comment by chanwit** [comment]
@shashiranjan84 maybe it's got some delay before showing newly added nodes? 
Decreasing the heartbeat rate to be a small value would help (I think heartbeat's default value is `25s`).

**Comment by abronan** [comment]
Hi @shashiranjan84, this would help if you can show the debug output that is shown on `swarm manage` and `swarm join` (using `--debug`)? Also what is the version of swarm you are using? Thanks!

**Comment by shashiranjan84** [comment]
@abronan  I am running it in production, so I cant stop the swarm and run the swarm in debug mode.
@chanwit  how do we update the heartbeat's?

**Comment by chanwit** [comment]
@shashiranjan84 you need to stop the manager and start it again with `--heartbeat=1s` , for example

**Comment by aluzzardi** [comment]
Hey @shashiranjan84, sorry this fell through the cracks.

This likely means swarm cannot reach the nodes.

If you can't restart it with the debug flag, you could simply start another swarm with the same token AS LONG as you use it in read-only mode (e.g. don't run containers on it).

My guess is ` --addr` in `join` was used wrong.

You could try something like this:

In the manage machine, run:
- `swarm list token://<token>` and look if you see the address of your new machines
- Then run `docker -H <that same address> info` and see if you can reach the engine from that machine

**Comment by abronan** [comment]
@shashiranjan84 You most likely solved the issue by now, sorry for the inconvenience. We're working on adding the connection status on `docker info` to help troubleshoot issues for Node management (in #1486).

Feel free to comment below or reach out on IRC (#docker-swarm) if you still have issues with Swarm. Thanks!
