### ISSUE TITLE
Obtain Swarm node ip address from a container

### ISSUE THREAD

**Issue by damianopezzotti** [docker/swarm#1131]
Is it possible to obtain the Swarm node IP address from a container?
We are building a microservices architecture based on docker and our application needs to publish its address to a centralized registry.
When we are in a cluster environment with containers running on different nodes, it is important for us to understand the node ip or, at least, a node identifier.

Tranks

**Comment by jimmyxian** [comment]
@damianopezzotti 
Use `docker -H <SWARM HOST> ps`, 
In NAMES column, you can find hostname the container run on.
In swarm, `NAMES` = `hostname/containername`
```
[root@localhost ~]# docker -H 127.0.0.1:2222 ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
6dfbf8e6f63f        busybox             "sleep 1000"        3 seconds ago       Up 1 seconds                            host82/stupefied_bell 
```

**Comment by jimmyxian** [comment]
Also,  use `docker -H <SWARM HOST> info`, you can get hostname <-->node ip

**Comment by damianopezzotti** [comment]
Hi Xian,
Thanks for your response.
I don't need to filter containers from node host or obtain information about the node.

What I really need is find the host IP address from an application running inside the container.
For example, if we have a swarm cluster with 3 nodes (master with ip 192.168.99.100, node001 with ip 192.168.99.101, node002 with ip 192.168.99.102) and I create a container, Docker creates the container inside a node.
I need that my application running inside the container can retrieve the node IP for a service registration. The application needs to communicate to other containers or to an external application that it is reacheable on a specific host and port.

**Comment by jimmyxian** [comment]
@damianopezzotti 
Related to https://github.com/docker/swarm/issues/1106

**Comment by damianopezzotti** [comment]
This is exactly what I need.
Thanks

**Comment by chanwit** [comment]
@damianopezzotti I shall close this issue then?

**Comment by damianopezzotti** [comment]
@chanwit ok
