### ISSUE TITLE
Confusion between Docker and Swarm API

### ISSUE THREAD

**Issue by Pensu** [docker/swarm#1142]
Hi, so I am a little confused between APIs being used by swarm and Docker. I have done a development setup of swarm through this: https://docs.docker.com/swarm/install-manual/

Now, I am not using swarm binary. Everything is being done using swarm image. What I want to know when I do "docker info" on my swarm manager, it calls the swarm API(i.e. the one in this repo) or Docker API(i.e. the one in docker repo)? Or is it the case, that the API in this tree is used by swarm binary only? Excuse me if I sound too noob, I am new to this stuff. TIA

**Comment by jimmyxian** [comment]
Hi, @Pensu 
Swarm serves the standard Docker API, you can use docker CLI to run/stop.... in swarm cluster.
```
docker client ----> swarm manager  ---> docker daemon
```

* `docker -H <Swarm Manger IP:PORT> info`: call Swarm API
* `docker -H <Docker Daemon IP:PORT> info`: call Docker API

**Comment by Pensu** [comment]
@jimmyxian Hi, thanks for the reply. I understand now that how can I call two different APIs. I just have a follow up question: when I call swarm manager, the request goes to the manager which is running as a container. Now, that takes the request, analyse it and send it to docker daemon. (Correct?). Now what I want to know is that when I am running swarm manager using swarm image, the code that is being used to generate that image is from this repo (i.e. docker/swarm) or something else?

**Comment by chanwit** [comment]
> Now what I want to know is that when I am running swarm manager using swarm image, the code that is being used to generate that image is from this repo (i.e. docker/swarm) or something else?

@Pensu yes, it is. Each stable version is compiled from a certain tag:
https://github.com/docker/swarm/releases
Now you should get `docker/swarm:0.4.0` when you pulling `docker/swarm:latest`.

**Comment by Pensu** [comment]
@chanwit Thanks a lot. Now all of this makes so much more sense :). Will close it.
