### ISSUE TITLE
How Swarm guarantee container dependencies like volume-from 

### ISSUE THREAD

**Issue by resouer** [docker/swarm#1143]
I noticed swarm can make sure `c1 --volume-from=c2` co-scheduled to the same host: https://github.com/docker/swarm/pull/388

But how Swarm guarntee c2 will be scheduled first on the host?

Otherwise, c1 can not pass the `filter` as it can not find c2 ready host. will c1 wait for a reschedule again?

**Comment by jimmyxian** [comment]
Swarm do not care about container orchestration. You can use Compose(https://github.com/docker/compose) to run multi-container applications.

In Swarm, if you use `--volumes-from=c2` and `c2` is not exist, swarm will return an error, just like this:
```
[root@Host82 ~]# docker -H 127.0.0.1:2222 run -d --volumes-from=c2 busybox
Error response from daemon: Unable to find a node fulfilling all dependencies: --volumes-from=c2
```

**Comment by resouer** [comment]
Fig is clever enough. Issue closed,
