### ISSUE TITLE
"docker tag" not tagging images for an entire cluster

### ISSUE THREAD

**Issue by tchk1228** [docker/swarm#1149]
It looks like only the first registered node in my cluster is executing "docker tag".

Kernel: 3.10.0-229.el7.x86_64
OS: CentOS Linux release 7.1.1503 (Core)

Swarm Manager:

docker -H $CLUSTER_ENDPOINT version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: swarm/0.4.0
Server API version: 1.16
Go version (server): go1.4.2
Git commit (server): HEAD

Node 1:
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): ba1f6c3/1.6.2
OS/Arch (server): linux/amd64

Node 2:
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 8aae715/1.6.0
OS/Arch (server): linux/amd64

swarm daemon command line parameters:
/usr/bin/swarm --debug manage -H tcp://$ENDPOINT file:///$STATIC_FILE

Informational output shows both nodes are registered:
"Registered Engine NODE1 at IP1"
"Registered Engine NODE2 at IP2"

docker -H $ENDPOINT tag -f IMAGE TAG

Swarm debug output shows only the first registered node getting tagged:

"HTTP request received" method=POST uri="/v1.17/images/IMAGE/tag?force=1&repo=TAG&tag="
"Proxy request" method=POST url=http://IP1/v1.17/images/IMAGE/tag?force=1&repo=TAG&tag=

I restarted the daemon so that the node order switched, and the first registered node only is still getting tagged.

Please let me know if you need any more information.

**Comment by vieux** [comment]
Confirmed, `tag` currently uses proxyImageAndForceRefresh so it will only tag one image

**Comment by jimmyxian** [comment]
via https://github.com/docker/swarm/pull/1159
