### ISSUE TITLE
"docker pull" returning 0 on error

### ISSUE THREAD

**Issue by tchk1228** [docker/swarm#1151]
Kernel: 3.10.0-229.el7.x86_64
OS: CentOS Linux release 7.1.1503 (Core)

Swarm Manager:

docker -H $CLUSTER_ENDPOINT version
 Client version: 1.5.0
 Client API version: 1.17
 Go version (client): go1.4.1
 Git commit (client): a8a31ef
 OS/Arch (client): linux/amd64
 Server version: swarm/0.4.0
 Server API version: 1.16
 Go version (server): go1.4.2
 Git commit (server): HEAD

Node 1:
 Server version: 1.6.2
 Server API version: 1.18
 Go version (server): go1.4.2
 Git commit (server): ba1f6c3/1.6.2
 OS/Arch (server): linux/amd64

Node 2:
 Server version: 1.6.0
 Server API version: 1.18
 Go version (server): go1.4.2
 Git commit (server): 8aae715/1.6.0
 OS/Arch (server): linux/amd64

docker -H $ENDPOINT pull $REGISTRY/qwerty; echo $?
NODE1: Pulling REGISTRY_IP/qwerty:latest... : Error: image qwerty:latest not found
NODE2: Pulling REGISTRY_IP/qwerty:latest... : Error: image qwerty:latest not found
0

**Comment by jimmyxian** [comment]
@tchk1228 Thanks for reporting this. I will take a look..

**Comment by jimmyxian** [comment]
Done to confirm. `pull / load / import` all these three cmd always return 0 even errors.

**Comment by chanwit** [comment]
@jimmyxian It seems we need a PR then.

**Comment by jimmyxian** [comment]
@chanwit Yeah. I'm trying to slove this locally. :)

**Comment by vieux** [comment]
@jimmyxian @chanwit any news on this one ?

**Comment by jimmyxian** [comment]
@vieux Yeah, here is my idea:
Once pull/load/import error on some nodes, do not return util all nodes done.
Then collect all the errors in swarm and finally return all the error to client. 

WDYT?

**Comment by jimmyxian** [comment]
Close via #1206 #1213
