### ISSUE TITLE
Proposal: versioning scheme

### ISSUE THREAD

**Issue by chanwit** [docker/swarm#1153]
Currently `swarm` version is changed only when releasing. This is a bit confusing for someone to report issues. (For example, `swarm` version is still marked as 0.4.0 but we started committing 0.5.0 works into master.)

We should follow Docker's versioning scheme to help solve this problem. For example, 

 *  We are now in the new sprint (Sprint 22). At the beginning of a new sprint just after releasing, we should bump the version to `0.${x+1}.0-dev'.
 * After the latest RC, we should strip `-dev` out of the version number, just before tagging a new release.

I think this is a minimal change to help maintaining versions in a bit better way.

WDYT?

**Comment by chanwit** [comment]
ping @abronan @aluzzardi @jimmyxian @vieux

**Comment by thaJeztah** [comment]
:+1: Docker used to have this as well, and it was really confusing

**Comment by jimmyxian** [comment]
:+1:

**Comment by abronan** [comment]
Totally :+1: for this.
