### ISSUE TITLE
Request for "docker rmi" to support -f flag 

### ISSUE THREAD

**Issue by tchk1228** [docker/swarm#1157]
I'm using the -f flag with docker rmi on my swarm endpoint but it doesn't seem to be implemented in 0.4.0.

Kernel: 3.10.0-229.el7.x86_64
OS: CentOS Linux release 7.1.1503 (Core)

Swarm Manager:

swarm -version
swarm version 0.4.0 (HEAD)

docker -H $CLUSTER_ENDPOINT version
 Client version: 1.5.0
 Client API version: 1.17
 Go version (client): go1.4.1
 Git commit (client): a8a31ef
 OS/Arch (client): linux/amd64
 Server version: swarm/0.4.0
 Server API version: 1.16
 Go version (server): go1.4.2
 Git commit (server): HEAD

Node 1:
 Server version: 1.6.2
 Server API version: 1.18
 Go version (server): go1.4.2
 Git commit (server): ba1f6c3/1.6.2
 OS/Arch (server): linux/amd64

Node 2:
 Server version: 1.6.0
 Server API version: 1.18
 Go version (server): go1.4.2
 Git commit (server): 8aae715/1.6.0
 OS/Arch (server): linux/amd64

docker -H $ENDPOINT rmi -f c90d3b3cf2d4
Error response from daemon: NODE1: 409 Conflict: Conflict, cannot delete image c90d3b3cf2d4 because it is tagged in multiple repositories, use -f to force

NODE2: 409 Conflict: Conflict, cannot delete image c90d3b3cf2d4 because it is tagged in multiple repositories, use -f to force
FATA[0000] Error: failed to remove one or more images

**Comment by jimmyxian** [comment]
@tchk1228 Thanks for reporting this.

**Comment by abronan** [comment]
Closed by #1162
