### ISSUE TITLE
swarm:0.2.0 create failed

### ISSUE THREAD

**Issue by cy490761462** [docker/swarm#1158]
Env:
linux kernel version 2.6.32-504.23.4.el6.x86_64
Docker version 1.5.0, build a8a31ef/1.5.0
Issue:
while running "sudo docker run --rm swarm:0.2.0 create", meet error:
time="2015-08-18T02:31:16Z" level=fatal msg="Post https://discovery-stage.hub.docker.com/v1/clusters: dial tcp 162.242.195.83:443: i/o timeout"

**Comment by jimmyxian** [comment]
@cy490761462 
You can see the this issue:
Duplicate https://github.com/docker/swarm/issues/871

**Comment by abronan** [comment]
Closing this one, @cy490761462 feel free to comment on the other issue as this is a duplicate. Thanks!
