### ISSUE TITLE
Integration tests on Windows

### ISSUE THREAD

**Issue by chanwit** [docker/swarm#1161]
Engine is now able to run on Windows Server 2016 TP3. But our testing infrastructure currently supports only Linux.

To ensure that `swarm` works similarly across platforms, we need to port all integration tests to Windows (Cygwin, MinGW, Power Shell are good candidates).

How could we achieve this?

**Comment by abronan** [comment]
There are already integration tests in Docker for Windows support so we could probably do the same for Swarm. Just a random thought, but can we run *bats* on cygwin? This would avoid the entire rewrite of the integration tests.

/cc @jfrazelle

**Comment by chanwit** [comment]
@abronan Yes we can run bats on Cygwin :)

**Comment by nishanttotla** [comment]
Closing because this is not as relevant right now.
