### ISSUE TITLE
"docker images" de-duplication

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/swarm#1164]
Just realized `docker images` swarm returns duplicates of the same images on multiple nodes (b/c image was fetched using `docker pull`). Looks like bad UX and we can probably remove duplicates from the list. Thoughts?

![image](https://cloud.githubusercontent.com/assets/159209/9460577/5e7b2752-4abc-11e5-982c-3d1f6dfefa6a.png)

**Comment by chanwit** [comment]
I'll take care of it.
