### ISSUE TITLE
a node disappear a few minutes later after I add this node in cluster

### ISSUE THREAD

**Issue by dayiguizhen** [docker/swarm#1165]
I add one node in cluster,but after few minutes,it was disappear.
    
    root@ubuntu:~# docker run --rm swarm join --addr=10.0.5.142:2375 token://85be61e8f2301ece240f27dc51aa5c30
    time="2015-08-25T11:01:23Z" level=info msg="Registering on the discovery service every 20s..." addr="10.0.5.142:2375" discovery="token://85be61e8f2301ece240f27dc51aa5c30" 
    time="2015-08-25T11:01:58Z" level=info msg="Registering on the discovery service every 20s..." addr="10.0.5.142:2375" discovery="token://85be61e8f2301ece240f27dc51aa5c30" 
    ^CYou have new mail in /var/mail/root
    root@ubuntu:~# docker run --rm swarm list token://85be61e8f2301ece240f27dc51aa5c30
    10.0.5.142:2375
    root@ubuntu:~# docker run --rm swarm list token://85be61e8f2301ece240f27dc51aa5c30
    root@ubuntu:~#

**Comment by abronan** [comment]
Hi @dayiguizhen, It's the desired behavior. `swarm join` actively heartbeats to signal that the node is alive and working:

```
time="2015-08-25T11:01:58Z" level=info msg="Registering on the discovery service every 20s..." addr="10.0.5.142:2375" discovery="token://85be61e8f2301ece240f27dc51aa5c30"
```


If you stop the `swarm join` program to execute, the node will stop signaling its activity and will thus be removed from the cluster list.

Each node has a TTL associated to their entry in the cluster list, so each time a node stops taking part of the cluster, the store in the background will make sure that this entry is removed. If you add it back with `swarm join` and you leave the program running you will see that the entry will be added back to the cluster list.

**Comment by dayiguizhen** [comment]
So according to my understanding,if I want add the node to cluster  for long time ,I should use option `-d` launch swarm image.

**Comment by jimmyxian** [comment]
@dayiguizhen 
Yes

**Comment by dayiguizhen** [comment]
Thanks!
