### ISSUE TITLE
Client and server don't have same version

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/swarm#1167]
With the release of Docker 1.8, Swarm is now two versions behind in Remote API version and this makes it hard to operate with Swarm clusters. Now I'll be downgrading my Docker client due to this problem. 

```
$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Wed Aug 19 17:05:20 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/0.4.0
 API version:  1.16
 Go version:   go1.4.2
 Git commit:   d647d82
 Built:
 OS/Arch:      linux/amd64
```

```
$ docker run -it debian
client and server don't have same version (client : 1.20, server: 1.18)
                                                                       Error response from daemon: client and server don't have same version (client : 1.20, server: 1.18)
```

Maybe some traction here https://github.com/samalba/dockerclient/issues/122 will help.

Alternatively you can support the movement here that would enable clients to override API version the client is sending through env vars: https://github.com/docker/docker/issues/11486

Also the [`api/README.md`](https://github.com/docker/swarm/blob/67cd9259eb616e6ab49fc0029b8be76449adc22f/api/README.md) should probably document the API version implemented.

**Comment by gianarb** [comment]
Same issue at the moment

**Comment by vieux** [comment]
@ahmetalpbalkan I see 1.16 and 1.18 in your logs, is that correct ?

**Comment by ahmetalpbalkan** [comment]
LOL I can't actually repro this now for some reason... Apparently I was doing some upgrade or hit the wrong docker engine. Closing, sorry for the trouble @vieux.
