### ISSUE TITLE
Does swarm provide high-availability and failover for containers?

### ISSUE THREAD

**Issue by nadgowdas** [docker/swarm#1174]
From the swarm announcement page at:
https://blog.docker.com/2014/12/announcing-docker-machine-swarm-and-compose-for-orchestrating-distributed-apps/

It is mentioned that
"In addition to resource optimization, Docker Swarm provides high-availability and failover.  Docker Swarm continuously health-checks the Docker daemon’s hosts and, should one suffer an outage, automatically rebalances by moving and re-starting the Docker containers from the failed host to a new one."

While i am trying the latest swarm code (swarm:latest from docker hub), it simply reports "Host down" but do not do failover and restart the containers from the failed host to other healthy host?

**Comment by nadgowdas** [comment]
also, how swarm will support "restart=always" policy if docker host goes down?

**Comment by jimmyxian** [comment]
https://github.com/docker/swarm/issues/599

**Comment by nadgowdas** [comment]
Thanks @jimmyxian, in principle i agree with the concerns for enabling this capability.
Is there a plan to overcome those ?
IMO, swarm need to have this capability.

**Comment by jimmyxian** [comment]
@nadgowdas Yeah. Maybe in 0.5. You can see Milestone Page to get what we will do.
https://github.com/docker/swarm/wiki/0.5.0-Milestone-Project-Page

**Comment by nadgowdas** [comment]
Thanks @jimmyxian

**Comment by jimmyxian** [comment]
@nadgowdas I shall close this issue then?

**Comment by nadgowdas** [comment]
Yes, please.

**Comment by mostafa8eltaher** [comment]
I think this should be reopened, or at least the expected version to be updated, since (as per the given link) there is no version 0.5, currently the latest version 1.2.3, and yet no news if this features in or not or when it will be.

**Comment by mostafa8eltaher** [comment]
Just for any one passing by, this feature is now available in version 1.12 Swarm Mode.

**Comment by koreshkumar** [comment]
So, container failover from one docker host to a another is possible on version 1.12 ? ... however i couldn't find such update on the release document.

**Comment by mostafa8eltaher** [comment]
Check https://docs.docker.com/engine/swarm/#feature-highlights for **Desired state reconciliation** feature
