### ISSUE TITLE
Documentation of Swam in a network 

### ISSUE THREAD

**Issue by abdulrahmanazab** [docker/swarm#1175]
I'm trying to install swarm on our test cluster SNabel (16 compute nodes), by setting one as the manager. Have been through this manual (https://docs.docker.com/swarm/install-manual/), but there are issues. when docker is configured to run as ```docker -H tcp://0.0.0.0:2375 -d```
I found that the daemon MUST be called afterwards using ```docker -H tcp://0.0.0.0:2375 <command>```, and NOT ```docker <command>```, so I guess this should be fixed in the manual.
The more important thing, is that I managed to get the swarm manager running together with one node (which is the local node), but things didn't work with the other nodes. What happens is, when I run:
```docker -H tcp://0.0.0.0:2375 run -d swarm join --addr=<node_ip:2375> token://<cluster_id>```
on each node, the container starts ok, but it does not appear in the list of the manager. 

I feel there is something messing here. I don't see, in the steps described in the manual, how the swarm nodes will know the address of the manager. in the join command above, the manager's address is not provided as an argument

**Comment by MHBauer** [comment]
When using the token discovery service, the manager does a lookup using that token at the docker hub. The nodes do not know the address of the manager and do not need to. The manager calls them, not the other way around.
See [here](https://github.com/docker/swarm/blob/master/discovery/token/README.md) for the description of the token service sequence.

**Comment by abdulrahmanazab** [comment]
@MHBauer So the manager should find the nodes (through the discovery service) not the other way around. But now I'm confused again. Where is the discovery service located? and who tells it the IP addresses of the nodes? which step in the documentation is this?
In step 2 in the manual, it is said: "Register the Swarm agents to the discovery service", I ran the command: '''docker -H tcp://0.0.0.0:2375 run -d swarm join --addr=<node_ip:2375> token://<cluster_id>''' on each node, is that correct? or should I run it on the manager node instead?
because so far I didn't get any of the nodes seen

**Comment by MHBauer** [comment]
The discovery service is provided by the Docker hub.

The `swarm join` command has the address used to connect to the node in the `--addr` flag. Make sure to leave `swarm join` running.

**Comment by abdulrahmanazab** [comment]
Ok here is what I have done:
1- Installed docker on 3 machines a, b, and c in a LAN.
2- pulled the swarm image on each.
3- ran 'docker run --rm swarm create' on node (a) and got the cluster_id
4- On a, b, and c I edited the  /etc/sysconfig/docker and added:
other_args="-H tcp://0.0.0.0:2375"
and restarted the docker service
5- On a,b, and c I ran:
docker -H tcp://0.0.0.0:2375 run -d swarm join --addr=<node_ip:2375> token://<cluster_id>
the node_ip is the IP of the node where I'm running the command on
6- on (a) I ran:
docker -H tcp://0.0.0.0:2375 run -d -p 2376:2375 swarm manage token://<cluster_id>
7- Now when I run:
 docker -H tcp://0.0.0.0:2376 info
I get information only about node (a)

What did I do wrong?

**Comment by rhim** [comment]
Maybe you need to point to port 3376.

**Comment by abdulrahmanazab** [comment]
@rhim more specific. which step?

**Comment by rhim** [comment]
step 7.

**Comment by abdulrahmanazab** [comment]
Wait a sec, so all of the nodes must have connection to the docker hub through the internet? This is the issue then, because in my cluster only one node is connected to the internet. Is there a way to set this up to run locally? e.g. setup a local discovery service?

**Comment by abronan** [comment]
You can use your own Consul, Etcd or Zookeeper cluster to set up the discovery. Or just use a plain file with the IPs of the machine that must be reachable in your network :)

For an overview of the possibilities, here is the [doc](https://github.com/docker/swarm/tree/master/discovery) for discovery :)

**Comment by abdulrahmanazab** [comment]
@abronan This solved it, thanks :+1: I think that this part should be added to the manual

**Comment by abronan** [comment]
@MHBauer kindly made this change in #1176

Closing this one but feel free to open a new Issue or contact us on IRC (#docker-swarm) if you have any more questions! :)
