### ISSUE TITLE
How to add a new scheduler?

### ISSUE THREAD

**Issue by Pensu** [docker/swarm#1181]
Hi,

I am trying to add a new scheduler to docker swarm. Writing it from scratch. Is there any documentation available regarding how to do that? Or should I just look at the existing schedulers and implement a new one following their structure? TIA

**Comment by jimmyxian** [comment]
@Pensu Sorry, do not have any documentation about how to implement a new scheduler.
But you can look at the existing schedulers and implement a new one following their structure.
Also, when you implement, any problem you meet,  feel free to ping us.

**Comment by Pensu** [comment]
Thanks @jimmyxian. Yeah, sure, will look into that. :)

**Comment by jimmyxian** [comment]
@Pensu  I shall close this issue then?

**Comment by Pensu** [comment]
@jimmyxian Yeah, sorry, forgot to do that. Will start a new discussion if there is any issue.
