### ISSUE TITLE
Swarm panic when docker-machine is unreachable 

### ISSUE THREAD

**Issue by agsmorodin** [docker/swarm#1191]
Swarm dies if I create/remove docker-machines (EC2) and  send the requests to swarm at the same time (using just docker ps).  I am using default discovery method.

Swarm log:
```
time="2015-09-02T13:50:35Z" level=error msg="Flagging engine as dead. Updated state failed: Get https://10.10.92.234:2376/v1.15/containers/json?all=1&size=0: read tcp 10.10.92.234:2376: no route to host" id="GQLM:75SN:DRQ4:3BGZ:IELF:22NB:3IQA:XKJA:MU5U:2GMC:FZD7:E4HK" name=swarm-agent-blue-sound-70 
time="2015-09-02T13:51:01Z" level=error msg="Flagging engine as dead. Updated state failed: Get https://10.10.92.233:2376/v1.15/containers/json?all=1&size=0: read tcp 10.10.92.233:2376: no route to host" id="XIDS:2UBM:25VT:JTPX:64XP:HGTK:Z3D6:QIRE:2JBN:HFJG:HPU3:VY3Z" name=swarm-agent-blue-sea-52 
time="2015-09-02T13:51:01Z" level=info msg="Removed Engine swarm-agent-test-test-52" 
2015/09/02 13:51:01 http: panic serving 10.10.93.62:64727: runtime error: index out of range
goroutine 1182 [running]:
net/http.func·011()
	/usr/src/go/src/net/http/server.go:1130 +0xbb
github.com/docker/swarm/api.getContainersJSON(0xc2080e9280, 0x7f9a58657168, 0xc2082e8dc0, 0xc2081ec410)
	/go/src/github.com/docker/swarm/api/handlers.go:197 +0x1815
github.com/docker/swarm/api.func·007(0x7f9a58657168, 0xc2082e8dc0, 0xc2081ec410)
	/go/src/github.com/docker/swarm/api/primary.go:118 +0x2de
net/http.HandlerFunc.ServeHTTP(0xc2080dc4a0, 0x7f9a58657168, 0xc2082e8dc0, 0xc2081ec410)
	/usr/src/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080983c0, 0x7f9a58657168, 0xc2082e8dc0, 0xc2081ec410)
	/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x297
github.com/docker/swarm/api.(*dispatcher).ServeHTTP(0xc208033b50, 0x7f9a58657168, 0xc2082e8dc0, 0xc2081ec410)
	/go/src/github.com/docker/swarm/api/server.go:32 +0x9d
net/http.serverHandler.ServeHTTP(0xc208182600, 0x7f9a58657168, 0xc2082e8dc0, 0xc2081ec410)
	/usr/src/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20842cc80)
	/usr/src/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/src/go/src/net/http/server.go:1751 +0x35e
time="2015-09-02T13:51:01Z" level=info msg="Removed Engine swarm-agent-test-test-70" 
```

**Comment by abronan** [comment]
Hi @agsmorodin, thanks for reporting the issue. Can you output these informations for the swarm running with machine:

```
$ docker info
$ docker version
```

**Comment by shihch** [comment]
Got the same issue. After I use 'docker-machine rm <swarm-agent>',  using docker ps or docker info only hangs on the docker-machine host. 

-swarm version 0.4.0 (d647d82)

docker info from my swarm-master
```
Containers: 3
Images: 20
Storage Driver: devicemapper
 Pool Name: docker-253:1-261354-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.009 GB
 Data Space Total: 107.4 GB
 Data Space Available: 17.39 GB
 Metadata Space Used: 2.179 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-123.8.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 490.1 MiB
Name: swarm-master
ID: R2LT:UTYI:ILCM:MJSM:T37I:JJSI:MK7A:H3C4:SIIP:PX4Z:YLI4:GLXZ
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 provider=digitalocean
```

docker version
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:19:43 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:19:43 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by agsmorodin** [comment]
Hi,

my info:

[root@ip-10-10-92-129 centos]# docker info

Containers: 3

Images: 31

Storage Driver: devicemapper

 Pool Name: docker-202:1-67184923-pool

 Pool Blocksize: 65.54 kB

 Backing Filesystem: xfs

 Data file: /dev/loop0

 Metadata file: /dev/loop1

 Data Space Used: 1.519 GB

 Data Space Total: 107.4 GB

 Data Space Available: 18.73 GB

 Metadata Space Used: 2.245 MB

 Metadata Space Total: 2.147 GB

 Metadata Space Available: 2.145 GB

 Udev Sync Supported: true

 Deferred Removal Enabled: false

 Data loop file: /var/lib/docker/devicemapper/devicemapper/data

 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata

 Library Version: 1.02.93-RHEL7 (2015-01-28)

Execution Driver: native-0.2

Logging Driver: json-file

Kernel Version: 3.10.0-229.11.1.el7.x86_64

Operating System: CentOS Linux 7 (Core)

CPUs: 2

Total Memory: 6.897 GiB

Name: ip-10-10-92-129.*****

ID: P5X3:DPRW:IUDZ:MFP4:O3BB:EQEN:J2CU:J3WF:EVBY:V7JX:F4DI:23EG

Labels:

 provider=amazonec2



[root@ip-10-10-92-129 centos]# docker version

Client version: 1.7.0

Client API version: 1.19

Go version (client): go1.4.2

Git commit (client): 0baf609

OS/Arch (client): linux/amd64

Server version: 1.7.0

Server API version: 1.19

Go version (server): go1.4.2

Git commit (server): 0baf609

OS/Arch (server): linux/amd64



On Fri, Sep 4, 2015 at 7:00 AM, shihch <notifications@github.com> wrote:

> Got the same issue. After I use 'docker-machine rm ', using docker ps or
> docker info only hangs on the docker-machine host.
>
> -swarm version 0.4.0 (d647d82
> <https://github.com/docker/swarm/commit/d647d820b71fd5886dbada74a0bcf63c096cd9a6>
> )
>
> docker info from my swarm-master
>
> Containers: 3
> Images: 20
> Storage Driver: devicemapper
>  Pool Name: docker-253:1-261354-pool
>  Pool Blocksize: 65.54 kB
>  Backing Filesystem: extfs
>  Data file: /dev/loop0
>  Metadata file: /dev/loop1
>  Data Space Used: 2.009 GB
>  Data Space Total: 107.4 GB
>  Data Space Available: 17.39 GB
>  Metadata Space Used: 2.179 MB
>  Metadata Space Total: 2.147 GB
>  Metadata Space Available: 2.145 GB
>  Udev Sync Supported: true
>  Deferred Removal Enabled: false
>  Data loop file: /var/lib/docker/devicemapper/devicemapper/data
>  Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
>  Library Version: 1.02.93-RHEL7 (2015-01-28)
> Execution Driver: native-0.2
> Logging Driver: json-file
> Kernel Version: 3.10.0-123.8.1.el7.x86_64
> Operating System: CentOS Linux 7 (Core)
> CPUs: 1
> Total Memory: 490.1 MiB
> Name: swarm-master
> ID: R2LT:UTYI:ILCM:MJSM:T37I:JJSI:MK7A:H3C4:SIIP:PX4Z:YLI4:GLXZ
> WARNING: bridge-nf-call-iptables is disabled
> WARNING: bridge-nf-call-ip6tables is disabled
> Labels:
>  provider=digitalocean
>
> docker version
>
> Client:
>  Version:      1.8.1
>  API version:  1.20
>  Go version:   go1.4.2
>  Git commit:   d12ea79
>  Built:        Thu Aug 13 02:19:43 UTC 2015
>  OS/Arch:      linux/amd64
>
> Server:
>  Version:      1.8.1
>  API version:  1.20
>  Go version:   go1.4.2
>  Git commit:   d12ea79
>  Built:        Thu Aug 13 02:19:43 UTC 2015
>  OS/Arch:      linux/amd64
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/swarm/issues/1191#issuecomment-137649499>.
>



-- 
Sincerely,
  Alex Smorodin

            mailto: agsmorodin@gmail.com

**Comment by abronan** [comment]
@agsmorodin Sorry for the delay coming back to this issue, this should be fixed as of now with the general improvements in the refresh loop and also requests made during an Engine removal. Can you give it another try with master for `swarm` and `docker-machine`? Thanks!

**Comment by agsmorodin** [comment]
I can confirm that now it's working fine without any problem with swarm master.

**Comment by abronan** [comment]
Thanks for checking @agsmorodin! Closing this one.

**Comment by dongluochen** [comment]
In api.getContainersJSON, container.Names[0] is referenced without validating not empty.

**Comment by vieux** [comment]
@cpuguy83 I can't find your previous comment about this. You said it shouldn't happen in the recent version of engine ?

**Comment by cpuguy83** [comment]
Correct. In 1.9 we make sure the list is never nil.

**Comment by dongluochen** [comment]
thank you @cpuguy83 @vieux. I think my test was on < 1.9. Closing this issue.
