### ISSUE TITLE
swarm manage with token discovery hangs after errors

### ISSUE THREAD

**Issue by wayerr** [docker/swarm#1200]
hang at 88 line:

https://github.com/docker/swarm/blob/6678a167fe873a320d00aa99be09945ac5f9ca96/discovery/token/token.go#L88

Trace:
```
goroutine 7 [chan send, 7 minutes]:
github.com/docker/swarm/discovery/token.func·001()
        /root/gocode/src/github.com/docker/swarm/discovery/token/token.go:88 +0x12c
created by github.com/docker/swarm/discovery/token.(*Discovery).Watch
        /root/gocode/src/github.com/docker/swarm/discovery/token/token.go:113 +0x226

```
This problem is appears when we run 'swarm manage' with temporary inaccessible internet, after access is returned the swarm will not retrieve node list, but swarm join work correctly.

**Comment by interair** [comment]
+1

**Comment by abronan** [comment]
Hi @wayerr, thanks for reporting the issue. Can you test with #1201? Should work :smile:

**Comment by abronan** [comment]
@wayerr So the patch was merged but feel free to re-open if you still encounter the issue. Couldn't reproduce despite shutting down my connection and putting it back up a few times (Adding and removing nodes). Thanks again for reporting it.

**Comment by chanwit** [comment]
@abronan sorry for not looking at this issue before merging :(:(:(

@wayerr please feel free to re-open if the problem still persists.

**Comment by abronan** [comment]
@chanwit No worries, it was such a small obvious patch that this needed to be merged :+1: I just want to make sure the issue is indeed fixed from this PR perspective, might be a detail I missed for example.

**Comment by wayerr** [comment]
Thanks, after fix it not reproduced!
