### ISSUE TITLE
Reserved Memory not release 

### ISSUE THREAD

**Issue by kevinsimper** [docker/swarm#1217]
Containers that have exited still take up reserved memory, is that correct?

`Exited (137) 35 minutes ago`

**Comment by kevinsimper** [comment]
I just tried do a `docker restart swarm-master` and that did not make it reload it config. This is pretty bad!

**Comment by abronan** [comment]
Hi @kevinsimper, Yes if you want that chunk of memory to be released you need to explicitly remove the container. The reason why is that a container might have a `restart policy` on exit/failure and you don't want that process to fail restarting because its allocated resource chunk has been given to some other container in the meantime :)

**Comment by kevinsimper** [comment]
Okay, that makes sense, but I can't read that anywhere?
https://docs.docker.com/swarm/api/swarm-api/

I did `memory=512M` because i wanted the container to be limited, not the whole cluster to be limited. I don't want a docker container to be take up all the memory, but I want to be able to put 10 containers on a 2GB machine. How can i do that?

From what i read here, memory is not calculated together either? Or am i wrong? https://docs.docker.com/reference/run/#memory-constraints

**Comment by abronan** [comment]
@kevinsimper I admit that somehow this should be configurable but as of now, resource accounting was conservative regarding the container state. You can put 10 containers on a 2GB machine but just make sure that some containers are not lurking around holding up resources. Usually you would like to clean and remove containers in the `exit` state.

In the meantime I'm migrating the resource accounting to be done by the Swarm Manager directly in #1212 so there might be a window to allow a resource chunk to be released on container `exit` (based on events we receive) and also based on `restart-policies`.

**Comment by kevinsimper** [comment]
Okay that sounds good! However, I was not talking about containers that has `exit` state, when I talked about 10 containers. Most of the time containers does not use that much memory, you just want to control them, that they don't use too much!

For an example, 10 golang web servers could only take up 1 GB, so they could easily fit on a 2 GB server, I just don't one 1 golang server to leak and take up all 2 GB.

**Comment by abronan** [comment]
@kevinsimper You can put soft memory limits on a container, docker allows that (so you put a lower/upper bound memory limit to your container). This might help in this case. Haven't tried on swarm though, this might require a change on the client. Curious to see!

**Comment by kevinsimper** [comment]
I just tried, and docker puts the soft limit on, but does not limit the overall system. So docker swarm needs a option to allow that :)

**Comment by Gladmir** [comment]
+1 for overall limitation config

**Comment by vieux** [comment]
this was documented in https://github.com/docker/swarm/pull/1520

I'm not sure such a flag makes sense in a clustering environment.

**Comment by amitshukla** [comment]
Closing: the question was answered and the docs were updated (https://github.com/docker/swarm/pull/1520)

**Comment by kevinsimper** [comment]
@amitshukla This should be reopened because it was not solved in #1520.

#1520 only talks about how containers are placed but nothing about memory `-m` arguments and how memory occupation is calculated.

How is a server with 1 GB of ram and 2 GB swap used and calculated?
