### ISSUE TITLE
Taking Nodes offline for maintenance

### ISSUE THREAD

**Issue by djl197** [docker/swarm#1230]
We are just starting to experiment with Swarm.
Its not clear from the documentation how we might 'remove' a node from the cluster for maintenance.

We are currently using file based (static list) - to specify the list of nodes.
If I was to restart the swarm manager with a new file list will it update its node list?
The problem with this approach is that I need to restart the manager, is there a better way? (For example does it poll the file for changes so that I can just update the file directly and watch nodes get added/removed?)

If I was to use the Hosted Discovery would that work in a better way?
I could stop the swarm agent on the node I am rebuilding - would that then result in the node no longer being available to the swarm.

In both of these cases, what happens to containers that are already running on the node - do they run to completion?

Hope you can help 
Dan

**Comment by abronan** [comment]
I'm closing this one in favor of #1508. Please feel free to comment on this other issue instead which has more details on possible solutions.

Thanks for opening the issue and putting it under our attention, this is going to be addressed as part of the Proposal in #1486
