### ISSUE TITLE
Docker 1.8.2 can not connect to Swarm 0.5.0-dev

### ISSUE THREAD

**Issue by klaus1982** [docker/swarm#1241]
I'm using Docker 1.8.2 and Swarm 0.5.0 to build a cluster; but it seems the docker can not access Swarm because URL mismatch.

Docker is trying to access `/v1.20/containers/create`, but in Swarm's log, there is only `/containers/create` endpoint.

if I corrected it, it will report the following error:

    root@mesosStagingController:~/swarm_mesos/swarm# docker -H tcp://mesosStagingController:4375 info
    Error response from daemon: 404 page not found

Here is the detail information of Docker & Swarm:

    root@mesosStagingController:~/swarm_mesos/swarm# /usr/local/gocode/bin/swarm -v
    swarm version 0.5.0-dev (HEAD)
    root@mesosStagingController:~/swarm_mesos/swarm# docker version
    Client:
    Version: 1.8.2
    API version: 1.20
    Go version: go1.4.2
    Git commit: 0a8c2e3
    Built: Thu Sep 10 19:19:00 UTC 2015
    OS/Arch: linux/amd64

    Server:
    Version: 1.8.2
    API version: 1.20
    Go version: go1.4.2
    Git commit: 0a8c2e3
    Built: Thu Sep 10 19:19:00 UTC 2015
    OS/Arch: linux/amd64
    root@mesosStagingController:~/swarm_mesos/swarm# docker -H mesosStagingController1:4375         run hello-world
    Post http://mesosStagingController1:4375/v1.20/containers/create: dial tcp: lookup     mesosStagingController1: no such host.
    * Are you trying to connect to a TLS-enabled daemon without TLS?
    * Is your docker daemon up and running?

**Comment by klaus1982** [comment]
If any un-clear about the message, please let me know.

**Comment by klaus1982** [comment]
It's a Swarm + Mesos cluster; after several hours, it keep reporting the following error's in swarm's log:

    2015/09/25 20:34:36 http: Accept error: accept tcp4 10.114.222.251:4375: too many open files; retrying in 1s
    2015/09/25 20:34:37 http: Accept error: accept tcp4 10.114.222.251:4375: too many open files; retrying in 1s
    time="2015-09-25T20:34:37-05:00" level=error msg="Flagging engine as dead. Updated state failed: Get http://mesosStagingCompute3.sl.cloud9.ibm.com:2375/v1.15/containers/json?all=1&size=0: dial tcp: lookup mesosStagingCompute3.sl.cloud9.ibm.com: too many open files. Are you trying to connect to a TLS-enabled daemon without TLS?" id="KWMY:FORD:ENMW:NZIQ:NV64:KZZ5:7TRR:4EH5:35UO:ZQZM:PVC3:F5T4" name=mesosStagingCompute3 
    time="2015-09-25T20:34:37-05:00" level=error msg="Flagging engine as dead. Updated state failed: Get http://mesosStagingCompute2.sl.cloud9.ibm.com:2375/v1.15/containers/json?all=1&size=0: dial tcp: lookup mesosStagingCompute2.sl.cloud9.ibm.com: too many open files. Are you trying to connect to a TLS-enabled daemon without TLS?" id="LL73:JA4O:WH72:KWRR:HZ7M:GNPR:H5JV:HYKM:6EJQ:EEN4:YUKH:BJBJ" name=mesosStagingCompute2 
    2015/09/25 20:34:38 http: Accept error: accept tcp4 10.114.222.251:4375: too many open files; retrying in 1s
    2015/09/25 20:34:39 http: Accept error: accept tcp4 10.114.222.251:4375: too many open files; retrying in 1s
    time="2015-09-25T20:34:39-05:00" level=debug msg="Removing offer" name=mesos offerID="&OfferID{Value:*8c712f23-839b-46d8-8725-69aab35d93b3-O28,XXX_unrecognized:[],}" 
    time="2015-09-25T20:34:39-05:00" level=debug msg="Offer \"8c712f23-839b-46d8-8725-69aab35d93b3-O28\" declined successfully" name=mesos 
    time="2015-09-25T20:34:40-05:00" level=error msg="Flagging engine as dead. Updated state failed: Get http://mesosStagingCompute3.sl.cloud9.ibm.com:2375/v1.15/containers/json?all=1&size=0: dial tcp: lookup mesosStagingCompute3.sl.cloud9.ibm.com: too many open files. Are you trying to connect to a TLS-enabled daemon without TLS?" id="KWMY:FORD:ENMW:NZIQ:NV64:KZZ5:7TRR:4EH5:35UO:ZQZM:PVC3:F5T4" name=mesosStagingCompute3 
    2015/09/25 20:34:40 http: Accept error: accept tcp4 10.114.222.251:4375: too many open files; retrying in 1s
    time="2015-09-25T20:34:40-05:00" level=debug msg="Removing offer" name=mesos offerID="&OfferID{Value:*8c712f23-839b-46d8-8725-69aab35d93b3-O29,XXX_unrecognized:[],}" 
    time="2015-09-25T20:34:40-05:00" level=debug msg="Offer \"8c712f23-839b-46d8-8725-69aab35d93b3-O29\" declined successfully" name=mesos 
    time="2015-09-25T20:34:41-05:00" level=error msg="Flagging engine as dead. Updated state failed: Get http://mesosStagingCompute2.sl.cloud9.ibm.com:2375/v1.15/containers/json?all=1&size=0: dial tcp: lookup mesosStagingCompute2.sl.cloud9.ibm.com: too many open files. Are you trying to connect to a TLS-enabled daemon without TLS?" id="LL73:JA4O:WH72:KWRR:HZ7M:GNPR:H5JV:HYKM:6EJQ:EEN4:YUKH:BJBJ" name=mesosStagingCompute2 
    2015/09/25 20:34:41 http: Accept error: accept tcp4 10.114.222.251:4375: too many open files; retrying in 1s

**Comment by vieux** [comment]
Our CI tests the latest swarm master agains the latest docker engin all the time, so it's not a version issue.

@klaus1982 did you open the port `2375` on your slaves ?

**Comment by klaus1982** [comment]
I start the swarm by following command; it'll connect to mesos cluster.

    /usr/local/gocode/bin/swarm --debug manage -c mesos-experimental --cluster-opt mesos.address=10.114.222.251 --cluster-opt mesos.port=4375 zk://mesosStagingController:2181,mesosStagingCompute0:2181,mesosStagingCompute1:2181/mesos

One more question: according to the log, Docker is trying to access /v1.20/containers/create, but in Swarm's log, there is only /containers/create endpoint. What steps/configuration did I miss?

**Comment by klaus1982** [comment]
Configuration issue, close this issue.

**Comment by riuvshin** [comment]
Hey! @klaus1982  I'm having same issue I have to nodes managed by swarm 0.4.0 and it works perfect. But sometimes it's starting to print exactly the same messages 
`2015/10/16 11:32:27 http: Accept error: accept tcp [::]:2375: too many open files; retrying in 1s`
restart swarm doing the fix but I wanted to know what I've missed in my config. can you please share what you've done with it? Thanks!

**Comment by klaus1982** [comment]
@riuvshin the issue of Accept error is still here, I have to re-start swarm after a few hours; seems no solution for that now :(. But it's enough for my demo.

**Comment by riuvshin** [comment]
@klaus1982 yeah same on my side. So maybe we should reopen issue?

**Comment by klaus1982** [comment]
Yes, seem we'd better to re-open this issue for `Accept error`.

**Comment by aluzzardi** [comment]
Am I right to assume this is a dupe of #1267 ?

**Comment by klaus1982** [comment]
@aluzzardi , I think so.

**Comment by abronan** [comment]
Hi @klaus1982 (/cc @riuvshin), could you give it a try with the latest `swarm:1.0.0-rc3` image? The problem should be solved by now, let us know if you still have issues with this version.

**Comment by klaus1982** [comment]
@abronan I'll try it and keep you posted, thanks for your feedback :).

**Comment by riuvshin** [comment]
@abronan I've updated to rc3 also

**Comment by abronan** [comment]
Hey @klaus1982 and @riuvshin. Any news from the RC testing (and now final `1.0.0`)? Can we close this? Thanks!

**Comment by klaus1982** [comment]
@abronan , I think we can close it. The latest version seems good to me :).
