### ISSUE TITLE
/images/json ignores label filters

### ISSUE THREAD

**Issue by dnephin** [docker/swarm#1244]
Looks like it only works with the `node` filter.  The `docker-compose` test suite needs this.

**Comment by dnephin** [comment]
I'm going to work on a fix for this

**Comment by dnephin** [comment]
This is going to be difficult.

So swarm keeps a list of images from the engine, but it's only the output of this `/images/json` call, which means it doesn't include labels.  When the call to this endpoint happens it only operates on the cached list, so there's no opportunity to add the filters to the API call, and the data needed to filter is not available.

The only options I can see are: 
 1. adding extra output to the engine response
 2. make `RefreshImage()` do a full inspect on every image so labels are stored (which I believe is a much more expensive operation)

Thoughts? Is there an easier way I missed?

Do you think there is any way to make 2 workable, or does this require 1?

**Comment by vieux** [comment]
I think it's possible with 2, but as you said it would be too much expensive.

I think 1 would be the best, the Docker API returns labels in listcontainers, it should be the same for listimages

**Comment by dnephin** [comment]
Good news, it turns out it is actually in the API response!  It's just missing from the docs, and from the go dockerclient.

So I should be able to just fix the client and get it working in swarm.
