### ISSUE TITLE
/images/json ignores repo name filter

### ISSUE THREAD

**Issue by dnephin** [docker/swarm#1257]
Similar to #1244 but for repo name instead of labels

**Comment by dnephin** [comment]
Looks like this param is also missing from the api docs https://docs.docker.com/reference/api/docker_remote_api_v1.20/#list-images

**Comment by dnephin** [comment]
+kind/bug
+area/api (I think)

I'm going to start working on this, since it's one of the last issues blocking the compose test suite from running.

**Comment by chanwit** [comment]
@dnephin Have you got some steps to reproduce? If so, I can help you test it when your PR is ready.

**Comment by dnephin** [comment]
Yup

```
docker tag busybox othername
docker images busybox
```

It will show all the images, but it should only show busybox images

I've got the fix mostly done in https://github.com/docker/swarm/compare/master...dnephin:fix_filter_images_by_repo

I just have to fix the integration test I think
