### ISSUE TITLE
Port 2375 or 2376?

### ISSUE THREAD

**Issue by RustJason** [docker/swarm#1259]
I restart my laptop and restart docker-machine. swarm shows no node conneted cause IP address changed, then I ssh to my one of my node and use:
```bash
#https://docs.docker.com/swarm/install-manual/
docker run -d swarm join --addr=<node_ip:2375> token://<cluster_id>
```
But it won't work.
And then I ssh to my swarm-master to execute ```docker ps```, it shows:
```bash
root@swarm-master:~# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
c8d0401a5874        swarm:latest        "/swarm manage --tlsv"   2 hours ago         Up About a minute   2375/tcp, 0.0.0.0:3376->3376/tcp   swarm-agent-master
```
Will, now let's see the result of ```netstat -natp```
```bash
root@swarm-master:~# sudo netstat -natp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1012/sshd
tcp        0      0 10.0.2.15:22            10.0.2.2:41564          ESTABLISHED 1249/sshd: docker [
tcp        0      0 :::2376                 :::*                    LISTEN      1069/docker
tcp        0      0 :::3376                 :::*                    LISTEN      1819/docker-proxy
tcp        0      0 :::22                   :::*                    LISTEN      1012/sshd
tcp        0      0 ::ffff:192.168.99.100:2376 ::ffff:172.17.0.2:46430 ESTABLISHED 1069/docker
tcp        0      0 ::ffff:192.168.99.100:2376 ::ffff:172.17.0.2:46433 ESTABLISHED 1069/docker
```
There is a 2376 open, But no 2375.
Is this a change?

**Comment by chanwit** [comment]
Hi

Docker port 2375 is the insecured where 2376 is for TLS (secured port).

Anyway when we start a swarm manager, we usually use another secured port number just for swarm, which is 3376.

**Comment by RustJason** [comment]
How do you think about this? @nathanleclaire is 2375 is insecured, then why it is not opend?

**Comment by RustJason** [comment]
Thank you very much @chanwit , This issue seems like blongs swarm, When I add a node in swarm, How did it know the master's IP address? Since I only pass node's address here.https://github.com/docker/swarm/blob/master/cli/join.go#L23

**Comment by chanwit** [comment]
Clients don't know a master. Each client registers itself to a discovery service.

You need to pass either a discovery string which contains IP addresses or `token://`.

A master then read a list of nodes from the discover service you specified.

**Comment by RustJason** [comment]
I passed with token, so token contains master IP in it?

**Comment by chanwit** [comment]
@RustJason no, but the token will  be used by Docker Hub. The Docker Hub will be your discovery service.

When you pass the token to your master, the master will know a list of your nodes.

You don't tell the master IP to the nodes, the master node knows them from the discovery service.

**Comment by RustJason** [comment]
Thanks, That's helps me a lot!
