### ISSUE TITLE
Engine refresh value interval should be tweakable

### ISSUE THREAD

**Issue by abronan** [docker/swarm#1265]
Related to #1263 

We should be able to tweak the values of the refresh in some ways. I don't see any other way than adding flags at the moment (put this in a config file would be convenient though). It goes alongside the flags for the `TTLs`, `heartbeat`, and Lock `TTL` tweakable values.

Maybe:

- `--engine-refresh-low-value 30 --engine-refresh-high-value 60`
- `--refresh-low 30 --refresh-high 60`

/cc @aluzzardi

**Comment by aluzzardi** [comment]
How about `min` / `max` instead of `low` / `high`?

**Comment by abronan** [comment]
:+1:

**Comment by abronan** [comment]
Fixed by #1363
