### ISSUE TITLE
Send authConfig when engine perfoms pull during create container

### ISSUE THREAD

**Issue by ezrasilvera** [docker/swarm#1269]
Is there any special reason why authConfig is passed during /image/create but is not passed during the image pull initiated by swarm engine during the /container/create (see bellow passing nil) 

		// Otherwise, try to pull the image...
		if err = e.Pull(config.Image, nil); err != nil {
			return nil, err
		}

**Comment by vieux** [comment]
Because the docker CLI unfortunately doesn't send us  the config on `/container/create`

**Comment by ezrasilvera** [comment]
I understand but if I use remote API and not the client I could pass X-Registry-Auth in the header and that could have work, right?   Can't we check if X-Registry-Auth exists and pass it if so ?

**Comment by ezrasilvera** [comment]
Probably would need small changes in postContainersCreate to pull the auth as well ..

**Comment by ezrasilvera** [comment]
Just as a test case - we are currently using this change (#1359)  in our local Swarm based cloud service and we already have a customer that is successfully using private registry by passing the X-Registry-Auth header

**Comment by thaJeztah** [comment]
@vieux is this related to https://github.com/docker/swarm/pull/1384?

**Comment by ezrasilvera** [comment]
@thaJeztah I believe that  #1384 has the same code changes as in #1350 (for the Swarm part) so probably #1350  and this issue can be  closed now that it was merged.

**Comment by thaJeztah** [comment]
Thanks @ezrasilvera! I'll close this issue, and will leave a comment on #1350
