### ISSUE TITLE
Unable to find a node fulfilling all dependencies

### ISSUE THREAD

**Issue by agsmorodin** [docker/swarm#1272]
Hi,

I am experiencing the following problem: when I am trying to run the simple compose file via swarm:
```
db:
  image: local_registry_domain/mysql:latest
  ports:
   - "3306:3306"
portal:
  image: local_registry_domain/tomcat:latest
  ports:
   - "8080:8080"
  links:
   - db
```

I receive the error: Unable to find a node fulfilling all dependencies: --link=name-db:db
The problem is that db container exists in swarm cluster.  if I rerun the command - it works perfectly. 
I can reproduce the issue only from time to time.   Most of the times this case works. 

docker info:
 docker -v
Docker version 1.9.0-dev, build 743dc1c

swarm version 0.5.0-dev (76591d2)

**Comment by dzlab** [comment]
Did you managed to find what's causing this? I'm having a similar problem when I try to scale a service:
```
> docker-compose scale server=2
WARNING: The "server" service specifies a port on the host. If multiple containers for this service are created on a single host, the port will clash.
Creating and starting 2 ... error

ERROR: for 2  Unable to find a node fulfilling all dependencies: --link=composedapp_kafka_1:composedapp_kafka_1 --link=composedapp_kafka_1:kafka --link=composedapp_kafka_1:kafka_1
```

**Comment by kirves** [comment]
Same as dzlab.
Is there a solution or at least a workaround?

```yaml
api:
  image: #myimage
  links:
    - memcached
  ports:
    - "8000:8000"

memcached:
  image: memcached
  ports:
    - "11211:11211"
```

This happens when trying to scale:
```
docker-compose scale api=2                                                                                                                                                                                                                kirves@Jenos
WARNING: The "api" service specifies a port on the host. If multiple containers for this service are created on a single host, the port will clash.
Creating and starting 2 ... error

ERROR: for 2  Unable to find a node fulfilling all dependencies: --link=everyride_memcached_1:everyride_memcached_1 --link=everyride_memcached_1:memcached --link=everyride_memcached_1:memcached_1
```

**Comment by abronan** [comment]
@agsmorodin @dzlab @kirves Links are deprecated, please refer to the [Compose documentation](https://docs.docker.com/compose/networking/). Also we don't use links with Swarm, if you want to scale a service using `docker-compose`, you must create an `overlay` network or let Compose create one for you using the flag `--x-networking` (Swarm defaults to `overlay` but you can specify which driver to use: `host/bridge/none/overlay` using `--x-networking --x-network-driver=<driver>`).

Generally you'd want to create an overlay for containers that needs to be linked together and known by their name coupled to constraints and affinities to restrict the scheduling choice to a set of nodes (using `-environment: "-e affinity:container!=memcached"` which will scale this container on another swarm host that does not run a memcached already. If scaling on the same machine leave the port expose unspecified or this will clash and refer to the service from its name in `api`).

**Comment by abronan** [comment]
Closing this one but feel free to comment below if you have any more questions :)

**Comment by dzlab** [comment]
@abronan i've tried to use overlay network as you suggested but end up seen this issue https://github.com/docker/libnetwork/issues/783
