### ISSUE TITLE
Returns EOF when trying to connect to the Swarm Manager with TLS

### ISSUE THREAD

**Issue by jfourment** [docker/swarm#1279]
Hello, 
I have been using Swarm for a while now and all was good until i tried to secure my cluster.
Any connection to my Swarm manager returns an EOF error and there is nothing in the logs:

<code>An error occurred trying to connect: Get https://localhost:50003/v1.20/info: EOF</code>

I'm trying a simple configuration running on one host. 
1. My daemon is TLS enabled and listening on port 2376 and I can succesfully "talk" to it through the secured port
2. If i change the -H option and try to talk to the swarm manager port i get the EOF

The Swarm Manager has been started with the following options: 
<code>docker run --name swarm-manager-tls -d -p 50003:2376 swarm manage --tlsverify --tlscacert=ca.pem --tlscert=swarmCRT.pem --tlskey=swarmKEY.pem --filter dependency --filter affinity token://mytoken </code>

And my client command line is : 
<code> docker --tlsverify --tlscacert=ca.pem --tlscert=localCRT.pem --tlskey=localKEY.pem -H at-at:50003 info </code>

All my certificates have been generated with clientCertAuth and serverCertAuth.

Any idea what's going on here?

There a few strange things in the logs though. When I first start the swarm container, I can see the following line, even if no HTTP is expected here:
<code>time="2015-10-12T00:34:25Z" level=info msg="Listening for HTTP" addr=":2375" proto=tcp </code>
Is that a logging bug or do i misinterpret this line?

Thx!

**Comment by aluzzardi** [comment]
Hey @jfourment - how about the connection between the manager and the nodes?

If it manages to connect, you should see something in the logs.

Do you have the full logs by any chance?

**Comment by jfourment** [comment]
Hey, 
I found the problem but I forgot to come back and update the issue. Sorry about that!
I was mapping my manager exposed port  on the wrong internal port. Swarm Manager internal port in 2375 and not 2376 .. as I was expecting with TLS enabled.
Don't know if it has been done on purpose, but at least the documentation should be clearer on the subject. I think someone else opened an issue on the subject recently.
