### ISSUE TITLE
Node labels only refreshed after Swarm Manager restart 

### ISSUE THREAD

**Issue by nicolaka** [docker/swarm#1281]
If a node's labels are updated or changed, the changes aren't reflected in Swarm manager( even after restarting the engine). The only way to reflect these changes is to restart the Swarm Manager itself. 

Swarm Version: swarm/0.4.0
Node engine version: 1.8.2

Steps to Reproduce:
1. Update the labels on a node ( e.g add DOCKER_OPTS= --label=environment=production to /etc/default/docker)
2. Restart the node's engine 
3. Check the labels of that node on Swarm manager using 'docker info'
4. Restart the Swarm manager container itself.
5. Repeat Step 3 >> now you'll see the new labels

**Comment by aluzzardi** [comment]
Perhaps we should call `refreshSpecs` in the engine refresh loop.

Thoughts? /cc @docker/swarm-maintainers

**Comment by allencloud** [comment]
I think it is reasonable to update refreshLoop. Since docker 1.10 supports labels configuration reload, swarm should have the ability to get new labels of all docker engines.
