### ISSUE TITLE
Image builds using affinity

### ISSUE THREAD

**Issue by pwnall** [docker/swarm#1282]
I want to be able to use Swarm to build images based on other images that I have built, and are not pushed to repositories.

I can run containers based on images that I have built, using affinities. Swarm 0.4+ even attempts to figure out image affinities on its own. I want to be able to specify affinities when building an image (AFAIK, that happens in the `POST /build` API call).

I noticed that API 1.21 adds `buildargs` to `POST /build`. Perhaps Swarm can overload them to allow specifying affinities, just like `POST /containers/create` overloads environment variables?

Asides from solving my use case, having affinities available for image building would open up other optimization opportunities. If this seems like a good idea, I'd be happy to try to implement it, perhaps with a bit of guidance.

**Comment by chanwit** [comment]
+1

This will solve compatiblity problems of the orchestration workflow too.

**Comment by Yam408** [comment]
Good

**Comment by pwnall** [comment]
I put together a patch in PR #1310. I pushed a swarm build that incorporates the patch at  `pwnall/swarm:image_filters`
