### ISSUE TITLE
Why does swarm expose port 2375

### ISSUE THREAD

**Issue by rhim** [docker/swarm#1288]
While going through the dockerfile for swarm, I see the following:

ENV SWARM_HOST :2375
EXPOSE 2375

I want to understand the purpose for it.

For swarm containers that I run on nodes with --join, they seem to have a local port on container open, but I don't understand the need for these containers to listen to anything - since they are just publishing whatever is passed in --advertise to discovery backends. I always pass docker daemon's port (2376) and node's local IP in --advertise.

e873c89e24d9        swarm               "/swarm join --addr=1"   2 hours ago         Up 2 hours          2375/tcp                           focused_bhaskara

For swarm container that I run with manage, I specify a different port anyway, like 3376 which is exposed to the host, so as to serve on hostIP:3376. I see that port listed in docker ps output too:
f465f070fc37        swarm               "/swarm manage --tls "   2 hours ago         Up 2 hours          2375/tcp, 0.0.0.0:3376->3376/tcp   serene_allen

So, what are we gaining by exposing 2375 on the swarm container? What is listening on that port and what's its purpose? It isn't clear from docs on swarm setup.

Thanks and best regards,
Himanshu

**Comment by chanwit** [comment]
it's for backward compatibility when you'd like to start the swarm manager without TLS.
I make use of this port extensively during development.

**Comment by rhim** [comment]
Hmm, let me try to clarify a bit.

The swarm container that runs on worker nodes (with join command) - AFAIK - its sole job is to publish the URI for the docker engine running on that host (let's assume it runs on port 2376). So there would be no inbound connections to this container.

The swarm container that runs on manager (with manage command) - AFAIK - it makes docker remote API calls to endpoints published on a discovery engine. So it will be making outbound connections to worker:2376, e.g. For inbound connectivity, if I specify a specific port with -H option, then I don't need to use the port 2375 either. 

I guess that port is just an artifact from earlier days when swarm didn't have the -H option to specify running server on a specific port. So that port is just there, not being used, IMHO.

Pls correct me if I am wrong.

**Comment by aluzzardi** [comment]
@rhim It's simply because the same image is used for both manage and join.

Manage has to expose the port, join does not, but since it's the same image they both do.

**Comment by thaJeztah** [comment]
It may be worth adding that the `EXPOSE` instruction only *informs/hints* docker which ports a container is listening on, but does not actually make ports reachable; the `EXPOSE` instruction merely makes the image more convenient to use. We recently merged a PR to clarify this in the documentation; https://github.com/docker/docker/pull/16965/files

**Comment by chanwit** [comment]
I think @thaJeztah's is clear enough. Shall we close this then?

**Comment by rhim** [comment]
Yep. Go ahead. 

-Himanshu




On Sun, Oct 25, 2015 at 10:34 PM -0700, "Chanwit Kaewkasi" <notifications@github.com> wrote:












I think @thaJeztah's is clear enough. Shall we close this then?

**Comment by tannerchung** [comment]
May not be the best place to post but it seemed like everyone on this thread had a good understanding of the ports used for docker swarm..

I see that 2375 is used for backwards compatibility. When I look at this https://docs.docker.com/datacenter/ucp/2.2/guides/admin/install/system-requirements/#ports-used

It says that 2376 is for backwards compatibility as well, however, when I'm using docker-machine I see that 2376 is being used as default. I know the guide is for UCP but I couldn't find an exhaustive list of what ports swarm use except for that list. I must be misunderstanding something - can anyone clarify?
