### ISSUE TITLE
runtime error in port filter

### ISSUE THREAD

**Issue by dnephin** [docker/swarm#1289]
I'm running master with 1f66308

```
swarm.master_1 | 2015/10/13 22:02:51 http: panic serving 172.17.42.1:47556: runtime error: invalid memory address or nil pointer dereference
swarm.master_1 | goroutine 567 [running]:
swarm.master_1 | net/http.(*conn).serve.func1(0xc82086d6b0, 0x7fbaf36c0058, 0xc82014ac08)
swarm.master_1 |        /usr/local/go/src/net/http/server.go:1287 +0xb5
swarm.master_1 | github.com/docker/swarm/scheduler/filter.(*PortFilter).portAlreadyInUse(0x11a9ae0, 0xc82025ab40, 0x0, 0x0, 0x0, 0x0, 0x0)
swarm.master_1 |        /go/src/github.com/docker/swarm/scheduler/filter/port.go:92 +0xb2
swarm.master_1 | github.com/docker/swarm/scheduler/filter.(*PortFilter).filterBridge(0x11a9ae0, 0xc820fa6380, 0xc82014ac48, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
swarm.master_1 |        /go/src/github.com/docker/swarm/scheduler/filter/port.go:52 +0x27e
swarm.master_1 | github.com/docker/swarm/scheduler/filter.(*PortFilter).Filter(0x11a9ae0, 0xc820fa6380, 0xc82014ac48, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
swarm.master_1 |        /go/src/github.com/docker/swarm/scheduler/filter/port.go:28 +0x15a
swarm.master_1 | github.com/docker/swarm/scheduler/filter.ApplyFilters(0xc82007e800, 0x5, 0x8, 0xc820fa6380, 0xc82014ac48, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
swarm.master_1 |        /go/src/github.com/docker/swarm/scheduler/filter/filter.go:61 +0x12d
swarm.master_1 | github.com/docker/swarm/scheduler.(*Scheduler).SelectNodesForContainer(0xc820108360, 0xc82014ac38, 0x1, 0x1, 0xc820fa6380, 0x0, 0x0, 0x0, 0x0, 0x0)
swarm.master_1 |        /go/src/github.com/docker/swarm/scheduler/scheduler.go:37 +0xb3
```

This failure is triggered by [this](https://github.com/docker/compose/blob/c06d9ec6723beae80f63f7b251d31f393502536b/tests/integration/cli_test.py#L591) test in the `docker-compose` test suite. It fails when compose tried to create two containers with the same port.  The create container call runs in parallel on the client, so both containers are created at approximately the same time. This failure seems to be easily reproducible (every run causes this failure).

You can reproduce the failure with:

```
parallel docker run -d -p 8888 alpine:edge sleep ::: 2 2
```

**Comment by dnephin** [comment]
Actually, I think any test that use the compose `scale` command causes this failure.

I wasn't seeing it when running against master from about a week ago, so I think it's something that was merged recently.

**Comment by agsmorodin** [comment]
I have the same issue:

2015/10/19 12:39:12 http: panic serving 10.10.92.93:54360: runtime error: invalid memory address or nil pointer dereference
goroutine 22068 [running]:
net/http.(*conn).serve.func1(0xc8211ef3f0, 0x7f6085941f18, 0xc820953080)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/docker/swarm/scheduler/filter.(*PortFilter).portAlreadyInUse(0x11a9b08, 0xc820540780, 0x0, 0x0, 0xc82041f590, 0x4, 0x4)
	/go/src/github.com/docker/swarm/scheduler/filter/port.go:92 +0xb2
github.com/docker/swarm/scheduler/filter.(*PortFilter).filterBridge(0x11a9b08, 0xc8215ea700, 0xc82078bb00, 0xa, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/swarm/scheduler/filter/port.go:52 +0x27e
github.com/docker/swarm/scheduler/filter.(*PortFilter).Filter(0x11a9b08, 0xc8215ea700, 0xc82078bb00, 0xa, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/swarm/scheduler/filter/port.go:28 +0x15a
github.com/docker/swarm/scheduler/filter.ApplyFilters(0xc820123600, 0x5, 0x8, 0xc8215ea700, 0xc82078bb00, 0xa, 0x10, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/swarm/scheduler/filter/filter.go:61 +0x12d
github.com/docker/swarm/scheduler.(*Scheduler).SelectNodesForContainer(0xc820148000, 0xc8204e4280, 0xa, 0xa, 0xc8215ea700, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/swarm/scheduler/scheduler.go:37 +0xb3
github.com/docker/swarm/cluster/swarm.(*Cluster).createContainer(0xc820127b00, 0xc8215ea700, 0xc820530f73, 0x1c, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/swarm/cluster/swarm/cluster.go:143 +0x417
github.com/docker/swarm/cluster/swarm.(*Cluster).CreateContainer(0xc820127b00, 0xc8215ea700, 0xc820530f73, 0x1c, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/swarm/cluster/swarm/cluster.go:112 +0x6e
github.com/docker/swarm/api.postContainersCreate(0xc820134b40, 0x7f6085944010, 0xc8211de160, 0xc8202eae00)
	/go/src/github.com/docker/swarm/api/handlers.go:392 +0x295
github.com/docker/swarm/api.NewPrimary.func1(0x7f6085944010, 0xc8211de160, 0xc8202eae00)
	/go/src/github.com/docker/swarm/api/primary.go:128 +0x300
net/http.HandlerFunc.ServeHTTP(0xc82025c240, 0x7f6085944010, 0xc8211de160, 0xc8202eae00)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820131b30, 0x7f6085944010, 0xc8211de160, 0xc8202eae00)
	/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/swarm/api.(*dispatcher).ServeHTTP(0xc820146300, 0x7f6085944010, 0xc8211de160, 0xc8202eae00)
	/go/src/github.com/docker/swarm/api/server.go:32 +0x9f
net/http.serverHandler.ServeHTTP(0xc820330300, 0x7f6085944010, 0xc8211de160, 0xc8202eae00)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8211ef3f0)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

**Comment by interair** [comment]
+1

**Comment by dnephin** [comment]
Are you hitting this in the 1.0.0rc1?

+kind/bug
+milestone 1.0.0

**Comment by agsmorodin** [comment]
swarm version 1.0.0 (fe88189)

**Comment by chanwit** [comment]
@dnephin @agsmorodin could you elaborate steps to reproduce this?
(It would be great if we can reproduce it without `docker-compose`, anyway)

**Comment by dnephin** [comment]
@chanwit it's easy to reproduce with this:

```
parallel docker run -d -p 8888 alpine:edge sleep ::: 2 2
```

I'll add it to the PR description as well

**Comment by vieux** [comment]
Thanks, we are going to investigate asap

**Comment by vieux** [comment]
ping @aluzzardi

**Comment by aluzzardi** [comment]
@dnephin Can you confirm #1314 fixing the crash?

**Comment by aluzzardi** [comment]
Thanks for spotting @dnephin, this was a really nasty one.

**Comment by interair** [comment]
The error doesn't reproduce anymore
Thanks!
