### ISSUE TITLE
`run -i` requires hitting input to exit

### ISSUE THREAD

**Issue by cpuguy83** [docker/swarm#1297]
When doing `docker run -i` against swarm, when the container exits, it is required to hit enter 2 times to get back to a prompt.
This is true with a  shell in the container `docker run -it busybox` (then type exit), or even just `docker run -i busybox false`.
It always requires hitting enter 2 times to fully exit.

### info
```
Containers: 5
Images: 5
Engine Version:
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 3
 swarm-demo-1: 192.168.99.148:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.10-boot2docker, operatingsystem=Boot2Docker 1.9.0-rc1 (TCL 6.4); master : 4187d2c - Wed Oct 14 14:00:28 UTC 2015, provider=virtualbox, storagedriver=aufs
 swarm-demo-2: 192.168.99.147:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.10-boot2docker, operatingsystem=Boot2Docker 1.9.0-rc1 (TCL 6.4); master : 4187d2c - Wed Oct 14 14:00:28 UTC 2015, provider=virtualbox, storagedriver=aufs
 swarm-demo-3: 192.168.99.149:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.10-boot2docker, operatingsystem=Boot2Docker 1.9.0-rc1 (TCL 6.4); master : 4187d2c - Wed Oct 14 14:00:28 UTC 2015, provider=virtualbox, storagedriver=aufs
CPUs: 3
Total Memory: 3.064 GiB
Name: dd4b830fedda
```

### version
```
Client:
 Version:      1.9.0-rc1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9291a0e
 Built:        Wed Oct 14 03:29:07 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/1.0.0
 API version:  1.16
 Go version:   go1.5.1
 Git commit:   fe88189
 Built:
 OS/Arch:      linux/amd64
```

**Comment by chanwit** [comment]
Duplicated with #1284

**Comment by abronan** [comment]
@vieux can you reproduce? I can't :disappointed:

**Comment by abronan** [comment]
ping @dongluochen I know that you showed me the behavior. Can you provide us with more details of your setup?

**Comment by dongluochen** [comment]
I have a repro on Mac. When I issue ‘docker run hello-world’ it returns to prompt right away. When I issue ‘docker run -i hello-world’, I need 2 returns to get back to prompt. 

info 

Dongluos-MacBook-Pro:~ dongluochen$ docker info
Containers: 17
Images: 6
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 3
 agent-00: 192.168.99.102:2376
  └ Containers: 5
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.022 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.0.9-boot2docker, operatingsystem=Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015, provider=virtualbox, storagedriver=aufs
 agent-01: 192.168.99.103:2376
  └ Containers: 6
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.022 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.0.9-boot2docker, operatingsystem=Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015, provider=virtualbox, storagedriver=aufs
 master-02: 192.168.99.104:2376
  └ Containers: 6
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.022 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.0.9-boot2docker, operatingsystem=Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015, provider=virtualbox, storagedriver=aufs
CPUs: 3
Total Memory: 3.065 GiB
Name: b9223eb476f5

version

Dongluos-MacBook-Pro:~ dongluochen$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/1.0.0
 API version:  1.16
 Go version:   go1.5.1
 Git commit:   fe88189
 Built:        
 OS/Arch:      linux/amd64

swarm 
Dongluos-MacBook-Pro:~ dongluochen$ docker-machine ls
NAME           ACTIVE   DRIVER       STATE     URL                         SWARM
agent-00                virtualbox   Running   tcp://192.168.99.102:2376   swarm-master
agent-01                virtualbox   Running   tcp://192.168.99.103:2376   swarm-master
default                 virtualbox   Stopped                               
local                   virtualbox   Running   tcp://192.168.99.100:2376   
master-02               virtualbox   Running   tcp://192.168.99.104:2376   swarm-master (master)
swarm-master            virtualbox   Stopped                               swarm-master (master)

ps

Dongluos-MacBook-Pro:~ dongluochen$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS                                     NAMES
0a09477cf2f8        hello-world         "/hello"                 2 minutes ago       Exited (0) 5 seconds ago                                              master-02/modest_hypatia
a3f303411db2        hello-world         "/hello"                 4 minutes ago       Exited (0) 2 minutes ago                                              agent-00/tender_sinoussi
1e97d36c7cf4        hello-world         "/hello"                 30 minutes ago      Exited (0) 27 minutes ago                                             master-02/mad_swartz
b473b3ed5b69        hello-world         "/hello"                 30 minutes ago      Exited (0) 27 minutes ago                                             agent-01/grave_galileo
6bd2dc7b2e78        hello-world         "/hello"                 4 hours ago         Exited (0) 4 hours ago                                                agent-00/mad_euclid
4b62ab5ea950        hello-world         "/hello"                 5 hours ago         Exited (0) 5 hours ago                                                agent-01/sad_perlman
228c07ad931a        hello-world         "/hello"                 5 hours ago         Exited (0) 5 hours ago                                                master-02/loving_goodall
64dce8ff846d        hello-world         "/hello"                 5 hours ago         Exited (0) 5 hours ago                                                master-02/trusting_mcclintock
1a921e72a245        hello-world         "/hello"                 5 hours ago         Exited (0) 5 hours ago                                                agent-00/focused_chandrasekhar
791c4bdafaf0        hello-world         "/hello"                 5 hours ago         Exited (0) 5 hours ago                                                agent-01/sick_swartz
9faf480f7d41        hello-world         "/hello"                 16 hours ago        Exited (0) 16 hours ago                                               agent-00/hungry_mcclintock
fc829bc66a58        hello-world         "/hello"                 16 hours ago        Exited (0) 16 hours ago                                               agent-01/insane_lovelace
eb0b8645f79a        hello-world         "/hello"                 16 hours ago        Exited (0) 16 hours ago                                               master-02/modest_kowalevski
21b1e65ad246        hello-world         "/hello"                 16 hours ago        Exited (0) 16 hours ago                                               agent-01/elated_yonath
1858edfafc79        hello-world         "/hello"                 16 hours ago        Exited (0) 16 hours ago                                               agent-00/compassionate_hoover
9d7e633bea8a        swarm:1.0.0-rc1     "/swarm join --advert"   16 hours ago        Up 16 hours                 2375/tcp                                  master-02/swarm-agent
b9223eb476f5        swarm:1.0.0-rc1     "/swarm manage --tlsv"   16 hours ago        Up 16 hours                 2375/tcp, 192.168.99.104:3376->3376/tcp   master-02/swarm-agent-master
9ad7e80c528c        swarm:1.0.0-rc1     "/swarm join --advert"   16 hours ago        Up 16 hours                 2375/tcp                                  agent-01/swarm-agent
75549ea5310b        swarm:1.0.0-rc1     "/swarm join --advert"   16 hours ago        Up 16 hours                 2375/tcp                                  agent-00/swarm-agent


Thanks,
Dong
