### ISSUE TITLE
Couldn't load x509 key pair, no such file or directory

### ISSUE THREAD

**Issue by anweiss** [docker/swarm#1301]
Trying to launch a Swarm manager using the following command:

```sh
docker run -d -p 2375:2375 swarm manage --tlsverify --tlscacert=~/ca.pem --tlscert=~/cert.pem --tlskey=~/key.pem token://<token>
```

For some reason, the container doesn't seem to launch due to the following error:

```sh
level=fatal msg="Couldn't load X509 key pair (/home/<user>/cert.pem, /home/<user>/key.pem): open /home/<user>/cert.pem: no such file or directory. Key encrypted?"
```

I can confirm that all certs were created using the same CA and that the certs are indeed at the root of the user's home directory. Not sure what's missing.

SLES 12
Docker 1.6.2, build 7c8fca2
Image -> Swarm:latest

**Comment by abronan** [comment]
Hey @anweiss, because you are using `docker run` to launch swarm you should mount the host directory containing certs as a data volume for those certs to be available inside the container.

```sh
docker run -d -v <host-directory>:/certs -p 2375:2375 swarm manage --tlsverify --tlscacert=/certs/ca.pem --tlscert=/certs/cert.pem --tlskey=/certs/key.pem token://<token>
```

**Comment by anweiss** [comment]
Thanks @abronan! Can't believe I missed that lol. Closing
