### ISSUE TITLE
Keep track of the missing API endpoints options in swarm

### ISSUE THREAD

**Issue by jimmyxian** [docker/swarm#1312]
I have compared the latest docker API. Our Swarm is missing the following api OPTIONS:
#### push
- [ ] --disable-content-trust

#### build
- [ ] --disable-content-trust
- [ ] --ulimit=[]
- [x] --build-arg

#### pull 
- [ ] --disable-content-trust
- [ ] --all-tags

#### run 
- [ ] --disable-content-trust
- [x] --stop-signal
- [x] --dns-opt=[] 
- [x] --kernel-memory=
- [x] --group-add=[]
- [x] --memory-swappiness=-1
- [x] --memory-reservation

#### ps
- [ ] --size
- [ ] --filter since=XXX
- [ ] --filter ancestor=\<image\>
- [ ] --filter label=\<somelabel\>
- [x] --filter volume=XXXX

#### load
- [ ] --quiet

#### import
- [ ] --message

#### exec
- [ ] --privileged

**Comment by jimmyxian** [comment]
@vieux I just have done some `run` options, not all. :). Anyway, i will continue to work on this.

**Comment by jimmyxian** [comment]
@abronan Closed?

**Comment by vieux** [comment]
@jimmyxian you wrote "Fix #1312" in the PR #1318 so it closed this one automatically, it's not @abronan he just merged #1318.

I usually use "Related to #xxx" when It doesn't fix entirely the issue.

**Comment by jimmyxian** [comment]
@vieux :laughing: Got it.

**Comment by nishanttotla** [comment]
@jimmyxian would you mind updating this issue? :)

It seems like there are newer options that we don't support with newer releases. We should also compile how our API endpoints differ from those in the upcoming Engine release. Ping @dongluochen .

**Comment by jimmyxian** [comment]
@nishanttotla OK, I will compare the newer options and update this ASAP

**Comment by jimmyxian** [comment]
Replaced by https://github.com/docker/swarm/issues/2333
