### ISSUE TITLE
Godep update cmd remove the test file

### ISSUE THREAD

**Issue by jimmyxian** [docker/swarm#1319]
The latest `godep` automatic remove the `_test` file.

I found that use `godep save -t` can save _test file.(https://github.com/tools/godep/commit/87fb5cdc4cbd6f0150f2e58087e235e843065304)
But `godep update` do not have `-t` option to save `_test` file(https://github.com/tools/godep/issues/298).

Now, which way should we go? 
ping @docker/swarm-maintainers

**Comment by vieux** [comment]
I think we should remove the tests

**Comment by jimmyxian** [comment]
@vieux OK, got it!
