### ISSUE TITLE
How to debug swarm source code 

### ISSUE THREAD

**Issue by bhar19** [docker/swarm#1325]
Hi,

I am a newbie, i want to explore more on scheduling strategy. Can any one help me, is there any debug tools available for debugging or, we need to use debug option through swarm ?

BR,
Bhargava

**Comment by chanwit** [comment]
I am not sure how others do. To me, I didn't start with a debugging tool. I read the tests (_test files) to study how the code works.

**Comment by bhar19** [comment]
Thank you !! I will do the same for now.

But if we do some changes in code and I want to ensure whether it is going in right way then in that case it might be useful. As Go language can be debugged through gdb, but i am not sure how can i use in case of swarm.

**Comment by chanwit** [comment]
@bhar19 With that, we cope with those changes using unit and integration tests. See `_test` files and also `.bats` in the `integration` directory for what we did here.

**Comment by bhar19** [comment]
Thanks alot !!

**Comment by chanwit** [comment]
@bhar19 No problem. Have fun!
