### ISSUE TITLE
/images/create returns 201 with swarm, but 200 with docker, no documentation

### ISSUE THREAD

**Issue by ekristen** [docker/swarm#1326]
It seems that when you call /images/create you get a 201 not a 200, but there is no documentation (at least that I could find) to support that the endpoint was modified from the default docker api, which returns a 200.

**Comment by vieux** [comment]
@ekristen thanks for reporting, we are going to fix it.

**Comment by ekristen** [comment]
@vieux no worries! thanks for addressing it so quickly. 

One other question, I've also noticed that it doesn't appear to stream the layer information like the normal docker api, is that intentional?
