### ISSUE TITLE
Swarm locks cluster indefinitely if 'create' hangs on node

### ISSUE THREAD

**Issue by jtwile2** [docker/swarm#1336]
The http client used by swarm to communicate with docker nodes has a Dial Timeout, but not a response timeout.  If a 'create' hangs on the docker daemon, swarm locks the cluster indefinitely.

HTTP Client creation with Dial Timeout only:
https://github.com/samalba/dockerclient/blob/master/utils.go#L11

Mock Docker Daemon with a sleep on 'create' request:
https://github.com/jtwile2/docker/blob/master/mock_docker.py

Version Info:  swarm on HEAD, docker daemon on 1.8.2
twile@twile-dev:~/go-code$ docker -H 127.0.0.1:2375 version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.0.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   HEAD
 Built:
 OS/Arch:      linux/amd64
twile@twile-dev:~/go-code$ docker -H 172.17.42.1:2375 version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
twile@twile-dev:~/go-code$

**Comment by vieux** [comment]
@jtwile2 can you give us the exact version of swarm you are using ? I believe it's fixed in 1.0.0-rc1

**Comment by abronan** [comment]
Looks like a duplicate of #1194

**Comment by jtwile2** [comment]
I built it today using 'go get github.com/docker/swarm'

**Comment by jtwile2** [comment]
I'm going to close this, just tested again and works great, it was fixed with #1194
