### ISSUE TITLE
ARM + PC mix Error response from daemon: client is newer than server

### ISSUE THREAD

**Issue by alexellis** [docker/swarm#1344]
I am running Docker swarm on my Raspberry PIs - with the following listed configuration and I'd like to know whether I can get these to work together.

I have been able to 

* create a swarm token (on PC)
* create a swarm master (on PC)
* run docker daemon on arm
* run docker swarm on arm with statically linked and built swarm binary
* run swarm manage list and see my two 
* run docker ps etc while pointing at the manager

The issue I have is when I try to start a container in the swarm I get this error:
```
docker -H tcp://0.0.0.0:2333 run -ti armv7/armhf-ubuntu_core /bin/bash
client is newer than server (client API version: 1.20, server API version: 1.19)
Error response from daemon: client is newer than server (client API version: 1.20, server API version: 1.19)
```

Please could I get some help?

`swarm version 1.0.0 (HEAD)`

```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/arm
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/arm
```

On my PC I have the following:

```
docker run --rm swarm --version
swarm version 0.4.0 (d647d82)
```

```
sudo docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7-dirty
 Built:        Thu Oct 22 15:30:45 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7-dirty
 Built:        Thu Oct 22 15:30:45 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by chanwit** [comment]
Could you try compiling `swarm` 1.0.0-dev with `docker` 1.9-dev? There would be some fixes on version compatibility lately.

**Comment by alexellis** [comment]
I started up swarm manage on one of the PIs and then I was able to run the cluster and see them reporting as present and I could start a container that way.

But ideally I'd like the PC to be the 'manage' node though and it has the higher API version. Is there a way of making the docker engine on the PC 'play' with nodes at a lower client version? (short of harmonising all the versions)

**Comment by thaJeztah** [comment]
We recently merged a pull request in docker/docker, that allows overriding the API version that the client uses via an environment variable; https://github.com/docker/docker/pull/15964. This feature will be part of docker 1.10.

Note that overriding the API version can still lead to unexpected results, as supporting older API versions in a newer client is on a best-effort base, and we consider that feature a "power user" feature.

**Comment by vieux** [comment]
@alexellis in addition the latest version of swarm supports API 1.21.
