### ISSUE TITLE
json: cannot unmarshal object into Go value of type []string after docker run -it

### ISSUE THREAD

**Issue by vieux** [docker/swarm#1348]
Using docker engine 1.9.0rc3 and swarm master:

```
$ docker run busybox ls
bin
dev
etc
home
proc
root
sys
tmp
usr
var

$ docker run -it busybox ls
bin   dev   etc   home  proc  root  sys   tmp   usr   var
json: cannot unmarshal object into Go value of type []string
```

As you can see, after a docker run with `-it` there is an issue: `json: cannot unmarshal object into Go value of type []string
`

~~In TTY mode, the cli is doing an `inspect` after the run to get the exit code (see https://github.com/docker/docker/blob/b227d19cae34d6d0ce92b72a53f02330b0be5992/api/client/utils.go#L281)~~

~~Since the docker inspect changed recently, we need to reflect the change.~~

I'm not sure where it's coming from.

I diffed inspect from swarm and inspect from engine and here is the difference:

```diff
24a25,38
>     "Node": {
>         "ID": "3KXO:AXAN:Y2SR:O5N5:MVN5:EHKB:G7EO:XJJY:PIDG:CO6N:G3EV:O75W",
>         "IP": "54.218.101.130",
>         "Addr": "node-2:2375",
>         "Name": "node-2",
>         "Cpus": 2,
>         "Memory": 4143755264,
>         "Labels": {
>             "executiondriver": "native-0.2",
>             "kernelversion": "3.16.0-33-generic",
>             "operatingsystem": "Ubuntu 14.04.2 LTS",
>             "storagedriver": "aufs"
>         }
>     },
```

So I don't think it's coming from there

**Comment by vieux** [comment]
@abronan @aluzzardi I updated the issue content.

**Comment by vieux** [comment]
I was using rc1 client...

**Comment by abronan** [comment]
:ghost:
