### ISSUE TITLE
 "No such image"  error   during  swarm push

### ISSUE THREAD

**Issue by linecheng** [docker/swarm#1354]
I‘m using swarm  push my image to my local registry.

This is some information

Registry  :  172.16.150.12:5000
Swarm :      172.16.150.11:8080

I have an image named `172.16.150.12:5000/demo/app_45:tag_45` on  172.16.150.12 .

use the command 
```
curl -H "X-Registry-Auth: ''" -d "" "http://172.16.150.11:8080/images/172.16.150.12:5000/demo/app_45/push?tag=tag_45"
```
It returns
```
No such image: 172.16.150.12:5000/demo/app_45

```
But I can push it  by using this command
```
curl -H "X-Registry-Auth: ''"  -d "" "http://172.16.150.12:2375/images/172.16.150.12:5000/demo/app_45/push?tag=tag_45"
```

How to push it by using swarm ?

Docker Version ：Docker version 1.8.3, build f4bf5c7
Swarm Versin :    0.4.0 (d647d82)
OS : Ubuntu 14.04

Thank you  .

**Comment by jimmyxian** [comment]
@linecheng Thanks for reporting this. 
I will fix this.

**Comment by linecheng** [comment]
It was fixed by  https://github.com/jimmyxian/swarm/commit/5d1fd77aeac5acda7d98cd38dd727cd9802ea9d7.

I will update to add  `workaround` for anyone meet the same question and close this issue.
