### ISSUE TITLE
Swarm 1.0.0-rc2 API 1.21 but Docker Engine API 1.22

### ISSUE THREAD

**Issue by chanwit** [docker/swarm#1364]
Hi
Not sure if we need to have the same API version by the final release of Swarm 1.0.0?

Here's version I got from swarm 1.0.0-rc2.
```
Server:
 Version:      swarm/1.0.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   da1f854
 Built:
 OS/Arch:      linux/amd64
```

Here's version from the master branch (image: `dockerswarm/swarm:master`)
```
Server:
 Version:      swarm/1.0.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   d395fa5
 Built:
 OS/Arch:      linux/amd64
```

Here's what I've got from Docker Engine, the experimental channel.
It seems to be 1.22.
```
Server:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   8d62f24
 Built:        Thu Oct 29 19:55:20 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by chanwit** [comment]
Other things, especially the networking part, is working fine BTW.
I can create, and list the overlay network with client/1.22 -> swarm/1.21 -> engine/1.22.

**Comment by vieux** [comment]
@chanwit it's tricky :)

Although 1.9.0 isn't release yet, it's going to be API 1.21 as you can see here https://github.com/docker/docker/pull/17000

What you are testing diverged from 1.9.0 and should be considered as 1.10.0-dev

**Comment by chanwit** [comment]
@vieux Thank you. I got it.
