### ISSUE TITLE
HTTP  /events stream

### ISSUE THREAD

**Issue by cerias** [docker/swarm#1367]
Currently i try to impliment swarm in our docker farm. But currently i encouter an problem wich i cannot future debug currently. The following demo code works fine with the docker remote api an logs the docker events. Sadly the same code make no output with the swarm api.  

           Client client = ClientBuilder.newClient();

            WebTarget target = client.target("http://docker-app1:2376/"
                    .concat("/events")
            );

            Response resp  =target.request().get();

            log.info(resp.getStatus()+"");
            log.info(resp.getMediaType().getType());
            for(String key :resp.getHeaders().keySet()){
                log.info(key+ ": "+resp.getHeaderString(key));
            }
            log.info("has entity : "+resp.hasEntity());

       
            
            InputStream inputStream = resp.readEntity(InputStream.class);
            String readLine;
            BufferedReader br = new BufferedReader(new InputStreamReader(inputStream));

            while (((readLine = br.readLine()) != null)) {
                log.warn(readLine);
            }

requesting with Chrome or Firefox both API's response.

Could anyone give me a hint whats missing or wrong? 

Version Info:
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/0.4.0
 API version:  1.16
 Go version:   go1.4.2
 Git commit:   d647d82
 Built:        
 OS/Arch:      linux/amd64

**Comment by MHBauer** [comment]
I think this is java, so wouldn't `"http://docker-app1:2376/".concat("/events")` be `http://docker-app1:2376//events`? I think the two `//` might do the wrong thing server side. Just a guess.

**Comment by cerias** [comment]
Jep, sadly it's Java. :) 

You correct with the double slash, but after the change the problem is still there. The connection to the endpoint was sucessfuly established (Http response 200). Also before this change.

**Comment by cerias** [comment]
The problem still exists for me with swarm 1.0 and docker 1.9

Other stream api's like the container/{id}/stats api works fine. except the events api where no line is printed.

**Comment by cerias** [comment]
I think i got the problem. 

If i get char for char, my output is correct. So from my point of view there is an missing line terminator in the events api so readline() would never end. And so its behave a little bit diffrent from the others endpoints.

Could anyone check if i'm right?

**Comment by MHBauer** [comment]
Docker the client reads by decoding json objects. This client is reading by lines.

Docker the server has newlines between json objects. Swarm does not separate the json by newlines.

I would guess that docker the server has newlines to flush the buffer.

**Comment by cerias** [comment]
Yeah, adding an line terminator would make it easier to switch from docker to swarm.

For prototyping i used for me the most basic form with parsing line for line. After this clarification i switched it to jackson and everything works fine. 

     for (Iterator it = new ObjectMapper().readValues(
                    new JsonFactory().createParser(inputStream), SwarmEvent.class);
                 it.hasNext();)

Thanks!
