### ISSUE TITLE
soft affinity and constraints not working properly together (1.0.0-rc3)

### ISSUE THREAD

**Issue by natarajanv** [docker/swarm#1374]
if we launch a docker container with the following soft affinity/constraints, swam throws the following error:  "Error response from daemon: unable to find a node that satisfies mitre.pool==B"

```
-e constraint:mitre.environment==DEV
-e constraint:mitre.pool==B
-e affinity:container==~busybox
```
This occurs when busybox is already running on pool A, and we are trying to start busybox on pool B as well. What should happen here is that even though the soft affinity is being met by r10a-dockersb1, the container should run on r10a-dockersb2 in our environment because the constraints should outweigh the soft affinity.  Here are the details about our env:

```
[bamboo@r10a-dockersb1 ~]$ docker info
Containers: 6
Images: 9
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 r10a-dockersb1.mitre.org: r10a-dockersb1.mitre.org:2376
  â Containers: 4
  â Reserved CPUs: 0 / 2
  â Reserved Memory: 0 B / 3.888 GiB
  â Labels: executiondriver=native-0.2, kernelversion=3.10.0-229.14.1.el7.x86_64, mitre.environment=SND, mitre.f5=B0k103-dltm1.mitre.org, mitre.pool=A, operatingsystem=Red Hat Enterprise Linux Server 7.1 (Maipo), storagedriver=devicemapper
 r10a-dockersb2.mitre.org: r10a-dockersb2.mitre.org:2376
  â Containers: 2
  â Reserved CPUs: 0 / 2
  â Reserved Memory: 0 B / 3.888 GiB
  â Labels: executiondriver=native-0.2, kernelversion=3.10.0-229.14.1.el7.x86_64, mitre.environment=SND, mitre.f5=B0k103-dltm1.mitre.org, mitre.pool=B, operatingsystem=Red Hat Enterprise Linux Server 7.1 (Maipo), storagedriver=devicemapper
CPUs: 6
Total Memory: 11.66 GiB
Name: r10a-dockersb2.mitre.org
```
Here are the versions:
```
[bamboo@r10a-dockersb1 ~]$ docker version
Client:
 Version:      1.9.0-rc4
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   e6f5a3c
 Built:        Sat Oct 31 05:43:43 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.0.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   d395fa5
 Built:
 OS/Arch:      linux/amd64

[bamboo@r10a-dockersb1 ~]$ docker-compose --version
docker-compose version: 1.5.0rc3
```

It seems to us that the soft affinity is being treated more like a "hard" affinity because if we remove the affinity from the equation then it works fine, for example...
```
-e constraint:mitre.environment==DEV
-e constraint:mitre.pool==B
```

**Comment by abronan** [comment]
Thanks for reporting @natarajanv 

ping @jimmyxian @vieux

**Comment by vieux** [comment]
@natarajanv something is not right in your logs.

You use `-e constraint:mitre.environment==DEV` but both of your engines were started with `mitre.environment=SND`

nothing should run at all.

**Comment by vieux** [comment]
also when you use `-e affinity:container==~busybox` you say `don't run on a machine when a container named busybox is running`, it's not using the image, just the container name (or ID).

**Comment by natarajanv** [comment]
Sorry for the typo. These are the parameters:

```
 -e constraint:mitre.environment==SND
 -e constraint:mitre.pool==A
 -e affinity:container==~busybox
```

**Comment by natarajanv** [comment]
according to the documentation:
Then, using -e affinity:container==frontend flag schedule a second container to locate and run next to frontend.

My understanding is, run busybox container on env SND and pool A where the "old version" of busybox is running. If an older vesrion is not running, still go ahead and run the container there.

I used busybox as an example , using a container name there instead.

**Comment by vieux** [comment]
@natarajanv here the test I wrote to try to reproduce your env:

```
@test "docker run - constraint and soft affinities" {
        start_docker_with_busybox 1 --label group=A # node-0
        start_docker_with_busybox 1 --label group=B # node-1
        swarm_manage

        # start	c0 on node-0
        docker_swarm run -d --name c0 -e constraint:node==node-0 busybox sleep 100

        # check container running on node-0
        run docker_swarm ps
        [[ "${output}" == *"node-0/c0"* ]]

        # start	c1 on node-1 using group==A (soft affinity will be discarded)
        docker_swarm run -d --name c1 -e constraint:group==A -e affinity:container==~c0 busybox sleep 100

        # check container running on node-0
        run docker_swarm ps
        [[ "${output}" == *"node-0/c1"* ]]
}
```

Can you tell me if it looks like your env ? because the test pass without issue.

**Comment by keith-** [comment]
I work with @natarajanv. I believe the test needs to be altered as follows to match our situation, which is running a container with the same name on a node in both group A and B. And for subsequent runs use the same nodes in group A and B if the container is already running.

```
"docker run - constraint and soft affinities" {
        start_docker_with_busybox 1 --label group=A # node-0
        start_docker_with_busybox 1 --label group=B # node-1
        swarm_manage

        # start c0 on a node in group=A
        docker_swarm run -d --name c0 -e constraint:group==A -e affinity:container==~c0 busybox sleep 100

        # check container running on node-0
        run docker_swarm ps
        [[ "${output}" == *"node-0/c0"* ]]

        # start c0 on a node in group==B (soft affinity will be discarded)
        docker_swarm run -d --name c0 -e constraint:group==B -e affinity:container==~c0 busybox sleep 100

        # check container running on a node in group=B
        run docker_swarm ps
        [[ "${output}" == *"node-1/c0"* ]]
}
```

**Comment by vieux** [comment]
@keith- you cannot start 2 containers with the same name (c0) I updated the 2nd container to c1 like this:

```
@test "docker run - constraint and soft affinities" {
        start_docker_with_busybox 1 --label group=A # node-0
        start_docker_with_busybox 1 --label group=B # node-1
        swarm_manage

        # start c0 on a node in group=A
        docker_swarm run -d --name c0 -e constraint:group==A -e affinity:container==~c0 busybox sleep 100

        # check container running on node-0
        run docker_swarm ps
        [[ "${output}" == *"node-0/c0"* ]]

        # start c1 on a node in group==B (soft affinity will be discarded)
        docker_swarm run -d --name c1 -e constraint:group==B -e affinity:container==~c0 busybox sleep 100

        # check container running on a node in group=B
        run docker_swarm ps
        [[ "${output}" == *"node-1/c1"* ]]
}
```

The test fails, I'm investigating

**Comment by vieux** [comment]
@keith- @natarajanv I created a place holder https://github.com/docker/swarm/pull/1375 to keep track of the progress

**Comment by keith-** [comment]
@vieux - I really appreciate you looking into this...I am able to start 2 containers with the same name in my swarm cluster by using constraints to make sure they do not end up on the same nodes. It is only when we try to introduce soft affinities that we see problems. For example, here is output from docker ps showing 2 containers with the same name running successfully:

```
[bamboo@r10a-dockersb1 ~]$ docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS               NAMES
e360895ae7a7        bamboo_docker_build:rhel7-5   "./run-agent.sh"         17 seconds ago      Up 14 seconds                           r10a-dockersb1.mitre.org/bamboo_docker_build
ba561eb8d5d9        bamboo_docker_build:rhel7-5   "./run-agent.sh"         43 seconds ago      Up 41 seconds                           r10a-dockersb2.mitre.org/bamboo_docker_build
30056790e415        swarm:SND                     "/swarm manage --tlsv"   23 hours ago        Up 23 hours                             r10a-dockersb1.mitre.org/swarm
b2330c1be9ad        bamboo_docker_deploy:SND      "./run-agent.sh"         23 hours ago        Up 23 hours                             r10a-dockersb2.mitre.org/bamboo_docker_deploy
176370ff5639        bamboo_docker_deploy:SND      "./run-agent.sh"         23 hours ago        Up 23 hours                             r10a-dockersb1.mitre.org/bamboo_docker_deploy
8039a1ffcc4b        swarm:SND                     "/swarm manage --tlsv"   23 hours ago        Up 23 hours                             r10a-dockersb2.mitre.org/swarm

```

We need this capability to support HA deployments in our environment. We are trying to use soft affinities to control where an application re-deployments such that newer builds overwrite older builds. This also ensures we don't leave orphaned instances of older builds running.

**Comment by vieux** [comment]
@keith- are you starting them through the manager or manually on each machine ?

**Comment by keith-** [comment]
@vieux - Doh! You are right, for the containers with the same names shown in my "docker ps" output, they were started by bypassing the manager... So thank you for updating the test case to use unique names as the constraint and soft-affinity issue is captured by that test case.
