### ISSUE TITLE
Dead links in docs

### ISSUE THREAD

**Issue by moxiegirl** [docker/swarm#1380]
@docker I found a typo on https://t.co/pS7bqR17wY  it should be `$ docker network ls` not `$ docker networks ls` under h2::Create a network

**Comment by auzias** [comment]
I'll know what to do next time :wink: :+1:

**Comment by moxiegirl** [comment]
@auzias Yay! We'll look forward to additional contributions.

**Comment by MHBauer** [comment]
@auzias are you interested in making a PR? The doc in question is located [here](https://github.com/docker/swarm/blob/master/docs/networking.md#L22)

**Comment by auzias** [comment]
That's done : https://github.com/docker/swarm/pull/1381
