### ISSUE TITLE
Panic Error: Discovery error: Unexpected watch error

### ISSUE THREAD

**Issue by dsampath** [docker/swarm#1385]
time="2015-11-06T01:13:05Z" level=error msg="Discovery error: Unexpected watch error" 
time="2015-11-06T01:13:25Z" level=info msg="Removed Engine dj-1" 
time="2015-11-06T01:13:25Z" level=info msg="Removed Engine dj-0" 
time="2015-11-06T01:23:48Z" level=info msg="Listening for HTTP" addr="0.0.0.0:3376" proto=tcp 
time="2015-11-06T01:23:49Z" level=info msg="Registered Engine dj-1 at 54.193.124.217:2376" 
time="2015-11-06T01:23:49Z" level=info msg="Registered Engine dj-0 at 54.193.51.73:2376" 
time="2015-11-06T01:28:49Z" level=error msg="Discovery error: Unexpected watch error" 
2015/11/06 01:31:28 http: panic serving 71.198.46.216:59989: runtime error: index out of range
goroutine 107 [running]:
net/http.(*conn).serve.func1(0xc820698000, 0x7f104e6ac198, 0xc8201258c0)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/docker/swarm/api.getContainersJSON(0xc820163a00, 0x7f104e627280, 0xc82019adc0, 0xc8204a6460)
	/go/src/github.com/docker/swarm/api/handlers.go:272 +0x1adc
github.com/docker/swarm/api.NewPrimary.func1(0x7f104e627280, 0xc82019adc0, 0xc8204a6460)
	/go/src/github.com/docker/swarm/api/primary.go:128 +0x300
net/http.HandlerFunc.ServeHTTP(0xc8201be520, 0x7f104e627280, 0xc82019adc0, 0xc8204a6460)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820167220, 0x7f104e627280, 0xc82019adc0, 0xc8204a6460)
	/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/swarm/api.(*dispatcher).ServeHTTP(0xc82016cfa0, 0x7f104e627280, 0xc82019adc0, 0xc8204a6460)
	/go/src/github.com/docker/swarm/api/server.go:32 +0x9f
net/http.serverHandler.ServeHTTP(0xc8203826c0, 0x7f104e627280, 0xc82019adc0, 0xc8204a6460)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820698000)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
2015/11/06 01:41:18 http: panic serving 71.198.46.216:60113: runtime error: index out of range
goroutine 26 [running]:

**Comment by vieux** [comment]
ping @abronan

**Comment by dongluochen** [comment]
@dsampath This should be fixed by #1465. It'd be great if you can confirm.

**Comment by dsampath** [comment]
Let me check that and get back to you. 
Thanks!

**Comment by thaJeztah** [comment]
Thanks @dsampath!

**Comment by dsampath** [comment]
That works ! Please close this ticket out. Thanks for fixing it !

**Comment by thaJeztah** [comment]
Cool! I don't have permissions in this repository, but since you created this ticket, you should be able to close it :+1:
