### ISSUE TITLE
Master can't connect to node

### ISSUE THREAD

**Issue by ThibautGery** [docker/swarm#1386]
Master can't connect to node
=======================

I run one agent, one master and the discovery service on the same host `192.168.56.25`

Environment
-----------------
Port on the host:

 * consul : `8500`
 * docker daemon: `2375`
 * agent port: `2376`
 * master port: `2380`  

docker version:

		Client:
		 Version:      1.9.0
		 API version:  1.21
		 Go version:   go1.4.2
		 Git commit:   76d6bc9
		 Built:        Tue Nov  3 17:43:42 UTC 2015
		 OS/Arch:      linux/amd64

		Server:
		 Version:      1.9.0
		 API version:  1.21
		 Go version:   go1.4.2
		 Git commit:   76d6bc9
		 Built:        Tue Nov  3 17:43:42 UTC 2015
		 OS/Arch:      linux/amd64

docker info:

		Containers: 8
		Images: 119
		Server Version: 1.9.0
		Storage Driver: aufs
		 Root Dir: /var/lib/docker/aufs
		 Backing Filesystem: extfs
		 Dirs: 141
		 Dirperm1 Supported: false
		Execution Driver: native-0.2
		Logging Driver: json-file
		Kernel Version: 3.13.0-24-generic
		Operating System: Ubuntu 14.04 LTS
		CPUs: 1
		Total Memory: 3.861 GiB
		Name: vagrant-ubuntu-trusty
		ID: I6WI:VL4Y:3T43:U2YI:72GE:BIDC:K3CA:GHTV:PHTC:EVPQ:I6HN:ZA4A
		WARNING: No swap limit support

uname -a : `Linux vagrant-ubuntu-trusty 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

vagrant box : `https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/14.04/ubuntu-14.04-amd64.box`

cat /etc/default/docker : `DOCKER_OPTS="--insecure-registry localhost --tls=false -H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock"`

Step to reproduce
-----------------------

 * Run the discovery service : `docker run -p 8500:8500 --name consul --rm=true progrium/consul -server -bootstrap`
 * Run one agent: `docker run -p 2376:2375 --name node1 --rm=true swarm join --advertise=192.168.56.25:2376 consul://192.168.56.25:8500`
 * Run the master: `docker run -p 2380:2375 --name master --rm swarm manage  consul://192.168.56.25:8500 --tlsverify=false  --advertise=192.168.56.25:2380`

Actual Results
------------------
The swarm master can't connect to the swarm agent :

        time="2015-11-06T10:57:01Z" level=error msg="Get http://192.168.56.25:2376/v1.15/info: EOF. Are you trying to connect to a TLS-enabled daemon without TLS?"

Expected Results
----------------------

The master can correct to the agent without TLS

Additionnal Info
--------------------
The discovery service works as expected : 
`docker run swarm list consul://192.168.56.25:8500` : `192.168.56.25:2376`

The cluster is up does'nt have any nodes :
`docker -H 192.168.56.25:2380 info` : 

		Containers: 0
		Images: 0
		Role: primary
		Strategy: spread
		Filters: health, port, dependency, affinity, constraint
		Nodes: 0
		CPUs: 0
		Total Memory: 0 B
		Name: 621469acd104

**Comment by ch3lo** [comment]
In your swarm agent change the adevertise to advertise=192.168.56.25:2375 and in the master remove the advertirse in your master.

Regards

**Comment by ThibautGery** [comment]
Thank you very much, I misunderstood the fact that the master contact directly the docker daemon instead of the swarm agent. I had to change my docker options to : `--tls=false -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock`

The following commands work properly :

		docker run -p 8500:8500 --name consul --rm=true progrium/consul -server -bootstrap
		docker run --rm=true --name node1 swarm join --advertise=<node_ip>:2375 consul://192.168.56.25:8500
		docker run -p 2380:2375 --name master --rm swarm manage  consul://<node_ip>:8500
		docker -H <node_ip>:2380 info

Regards,
