### ISSUE TITLE
Swarm not releasing ports on `docker stop`

### ISSUE THREAD

**Issue by rgardler** [docker/swarm#1387]
I started three containers on a three node cluster:

docker run -d -p 80:80 web

As expected I got one container on each node.

Then I stopped them:

docker stop $(docker ps -q)

Then I tied to restart one of the containers with the same command:

$ docker run -d -p 80:80 web
Error response from daemon: unable to find a node with port 80 available

FYI

$ docker info                                                                                                                          
Containers: 6                                                                                                                          
Images: 9                                                                                                                              
Role: primary                                                                                                                          
Strategy: spread                                                                                                                       
Filters: health, port, dependency, affinity, constraint                                                                                
Nodes: 3                                                                                                                               
 swarmVM0: 10.0.0.4:2375                                                                                                               
  └ Containers: 2                                                                                                                      
  └ Reserved CPUs: 0 / 1                                                                                                               
  └ Reserved Memory: 0 B / 3.53 GiB                                                                                                    
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-43-generic, operatingsystem=Ubuntu 14.04.2 LTS, storagedriver=aufs        
 swarmVM1: 10.0.0.6:2375                                                                                                               
  └ Containers: 2                                                                                                                      
  └ Reserved CPUs: 0 / 1                                                                                                               
  └ Reserved Memory: 0 B / 3.53 GiB                                                                                                    
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-43-generic, operatingsystem=Ubuntu 14.04.2 LTS, storagedriver=aufs        
 swarmVM2: 10.0.0.5:2375                                                                                                               
  └ Containers: 2                                                                                                                      
  └ Reserved CPUs: 0 / 1                                                                                                               
  └ Reserved Memory: 0 B / 3.53 GiB                                                                                                    
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-43-generic, operatingsystem=Ubuntu 14.04.2 LTS, storagedriver=aufs        
CPUs: 3                                                                                                                                
Total Memory: 10.59 GiB                                                                                                                
Name: e2a4bc8622ad

**Comment by rgardler** [comment]
Perhaps this is expected behavior?

$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS               NAMES
2e1c743ab23b        web                 "apache2-foreground"     18 minutes ago      Exited (0) 16 minutes ago                       swarmVM0/insane_euclid
a0d4c8788ccb        web                 "apache2-foreground"     20 minutes ago      Exited (0) 16 minutes ago                       swarmVM2/nostalgic_almeida
3f8b9a284d9e        web                 "apache2-foreground"     26 minutes ago      Exited (0) 16 minutes ago                       swarmVM1/naughty_mietner
5216fc96cb83        swarm               "/swarm join --addr=1"   4 hours ago         Up 4 hours                  2375/tcp            swarmVM2/compose_swarm_1
f8bbaf9d8fdd        swarm               "/swarm join --addr=1"   4 hours ago         Up 4 hours                  2375/tcp            swarmVM0/compose_swarm_1
eb548061371b        swarm               "/swarm join --addr=1"   4 hours ago         Up 4 hours                  2375/tcp            swarmVM1/compose_swarm_1

$ docker rm 2e1
2e1

$ docker run -d -p 80:80 web
c3dc885819f121494e9099e471ca410f9445933601b37c46290a47e1e694633e

**Comment by abronan** [comment]
@rgardler Yes this is the expected behavior :) reason for that is that you may want to restart the container you just stopped and the port will not be available in that case. So we expect users to remove the container entirely if the port needs to be made available to some other container.

**Comment by rgardler** [comment]
Thanks.
