### ISSUE TITLE
Swarm Docker Run Proxy Issue 

### ISSUE THREAD

**Issue by stemau98** [docker/swarm#1390]
Hey!

I'm working behind a company proxy and trying to run a docker swarm cluster. 
I am able to join and manage a cluster but when it comes to starting a container with docker run I get a html response from the proxy server with error code 502.

Proxy settings for docker work fine.

All other commands within the swarm cluster like ps, pull, etc. worked also fine, only the run command failed.

**Comment by dongluochen** [comment]
@stemau98 Can you provide details of your swarm topology, including swarm master, docker client, swarm nodes, and proxy setting on them? What's the output from docker run and docker pull?

**Comment by stemau98** [comment]
I'm running the swarm master on my laptop in our company network, the Swarm Nodes are running on two of our Servers in the same network. 
The entire network is behind our company proxy and on all machines the environment variables like http_proxy are set. I also added the environment variables to the container at startup.

I have to start the Swarm Master like:
docker run -d -e HTTP_PROXY=http://company_proxy -e HTTPS_PROXY=http://company_proxy -p 127.0.0.1:2375:2375 swarm manage token://761adbd84dd762f49392b9cb22ebba5e
I bind the Host Port to 2375 and IP to localhost otherwise I get an error from the proxy. 
 
Swarm Master Docker Version: Docker version 1.8.2, build 0a8c2e3
Swarm Nodes Docker Version: Version: 1.8.2 and Api Version: v1.17

If I run the following command: docker -H tcp://127.0.0.1:2375 run -d ubuntu:14.04 /bin/sh -c "while true; do echo hello world; sleep 1; done"

Error response from daemon: 

Errorcode: 502 Proxyfehler. ISA Server denied URL. (12202)
IP-Adresse: ...
>Datum: 12.11.2015 07:01:22 [GMT]
>Server: ...
>Quelle: Proxy

**Comment by dongluochen** [comment]
@stemau98 HTTP proxy should be applied to external request only. You can use `no_proxy` setting to specify internal addresses. In your case communication to docker agent shouldn't use proxy as it's internal communication.
http://askubuntu.com/questions/11274/setting-up-proxy-to-ignore-all-local-addresses

**Comment by stemau98** [comment]
I have set the no_proxy settings like described here: https://docs.docker.com/engine/articles/systemd/
And docker itself worked fine for me even with the proxy settings.

I only need http_proxy settings inside the swarm agent containers to get the token from the discovery service on Docker Hub.  

The strange thing is that only the docker run command which points to my swarm cluster get an error response. All other commands like info or pull are working. 

So what happend exactly when I want to run a container on a swarm agent. How did the swarm master tell the agent to start that container.? Is this done over IP of the swarm agent or some way else?

**Comment by kunalkushwaha** [comment]
@stemau98 Can you please share the ``docker logs <container-name>`` for failed container.
I am also facing something similar, but with consul based discovery.

Had fixed issue for token based discovery in docker-machine https://github.com/docker/machine/pull/2166

**Comment by kunalkushwaha** [comment]
>The strange thing is that only the docker run command which points to my swarm cluster get an error > response. All other commands like info or pull are working.

docker command on host utilizes the proxy of you docker host settings, while in case of ``docker run `` your container, will utilize the proxy which is set in your environment settings for container i.e. passed as ``-e`` while docker run.

Try ``docker run -d -e "http_proxy=http://example-proxy:port" swarm join --addr=host-IP:swarm-port token://618194207ddfcbf6e13693d08f0dc5fc``

**Comment by stemau98** [comment]
@kunalkushwaha 
The contianer I want to start will only be created on the swarm agent and dokcer logs fot that container is:  <code> invalid character '<' looking for beginning of value </code>
i think this is also a bug because i get this message for every single container even for continaers i started direct on the swarm node.

**Comment by stemau98** [comment]
I already use the -e "http_proxy=http://example-proxy:port" for my swarm agent contianers and the connection between master and agent is correctly setup. 

Only the run command give ma an error message

**Comment by kunalkushwaha** [comment]
I think u misunderstood with ``docker logs <container-name>``  command, your error message ``invalid character '<' looking for beginning of value `` suggest you typed ``<`` before container name.

It is simply ``docker logs container-name``

**Comment by stemau98** [comment]
I know but this is the message I get when I run: <code>docker -H tcp://127.0.0.1:2375 logs 0bd383e60036 </code>

**Comment by kunalkushwaha** [comment]
humm that is strange, If possible, please ssh or login to that node and try these commands. Also, you may check ``/var/log/docker.log`` or docker log as per your host OS distribution.

**Comment by stemau98** [comment]
I did this already and there are no logs for the contianer because the container is only created but never started. So my continaer have no logs.

**Comment by kunalkushwaha** [comment]
You may try with docker machine.
For proper proxy support for swarm in, use latest code from github and build it.

**Comment by dongluochen** [comment]
@stemau98 Replying your previous question,  
```
How did the swarm master tell the agent to start that container.? Is this done over IP of the swarm agent or some way else?
```
When you issue a docker run command to swarm, it selects an agent to start a container. The request goes thru the REST API on an agent's docker daemon. You can issue command `docker -H agent_i:port_i run <your app>` against each agent to validate the output. It may help you identify the source of proxy error. In your case node discovery and image pull may go thru proxy.

**Comment by stemau98** [comment]
@dongluochen Thanks for the information!

I have another question in matter of the proxy settings. 
Does Docker take locally set environment variables like http_proxy or no_proxy? Or have they set up within the config files http-proxy.conf in /etc/systemd/system/docker.service.d/ ?
And is there any difference between no_proxy and NO_PROXY?

**Comment by stemau98** [comment]
@dongluochen  I run the command <code>docker -H agent_i:port_i run <your app> </code> like you suggest from the same machine where the swarm master is running. And I got no error and the Container started normally on the swarm node.

But when I run the same command pointing to my swarm master I get a proxy error and the container will only be created on the swarm agent but not be started.   

I tested some docker commands some of them worked but most of them didn't work.
Commands that work: <code>ps, images, verison, info</code>
Commands with proxy error code 502: <code> run, search, exec, stats, top </code>

For the <code> logs </code> and <code>inspect </code> I get following error message: </br> 
<code> invalid character '<' looking for beginning of value </code>

**Comment by dongluochen** [comment]
@stemau98 Please provide your command and output for `info, version, ps -a, images, run, logs, inspect`. And `env | grep -i proxy`.

**Comment by stemau98** [comment]
@dongluochen Output: <code> env | grep -i proxy </code>
HTTPS_PROXY=http://xxx.xxx.de:3128/
no_proxy=localhost,127.0.0.0/8,::1
HTTP_PROXY=http://xxx.xxx.de:3128/

Start Swarm Master
docker run -d -e HTTP_PROXY=http://xxx.xxx.de:3128/ -e HTTPS_PROXY=http://xxx.xxx.de:3128/ -p 127.0.0.1:2375:2375 swarm manage token://xxxxxxxxxxxxxxxxxxxxxxxxx

<code> docker -H tcp://127.0.0.1:2375 info </code>
Containers: 13
Images: 74
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 1
 imbpl4bui07: XX.XX.XX.XX:2375
  └ Containers: 13
  └ Reserved CPUs: 0 / 58
  └ Reserved Memory: 0 B / 264.4 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.10.0-229.14.1.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
CPUs: 58
Total Memory: 264.4 GiB
Name: 11edca842b83

<code> docker -H tcp://127.0.0.1:2375 -v</code>
--> Docker version 1.8.2, build 0a8c2e3

<code> docker -H tcp://127.0.0.1:2375 ps -a </code> and <code> docker -H tcp://127.0.0.1:2375 images </code>
--> displays the running container and images like expected

For the <code> logs </code> and <code>inspect </code> comamnd I get following error message: </br> 
<code> invalid character '<' looking for beginning of value </code>

<code> docker -H tcp://127.0.0.1:2375 run -d ubuntu:14.04 /bin/sh -c "while true; do echo hello world; sleep 1; done" </code>

<ul>Error response from daemon:

Errorcode: 502 Proxyfehler. ISA Server denied URL. (12202)
IP-Address: xx.xx.xx.xx

Date: 18.11.2015 07:01:22 [GMT]
Server: xxx
Source: Proxy
</ul>
The Container  will only be created on the swarm node but not started.

hope this is helpfull for you!

**Comment by dongluochen** [comment]
@stemau98 Do you have update for this issue?

**Comment by dongluochen** [comment]
@stemau98 I'll close this issue as we don't see update. Feel free to re-open if you have more info.
