### ISSUE TITLE
Typo error in Docker Swarm Networking

### ISSUE THREAD

**Issue by aruneli** [docker/swarm#1391]
![image](https://cloud.githubusercontent.com/assets/7720752/11048231/75b294da-86eb-11e5-80ff-7e56620bbe18.png)

It has to be "docker network ls"

**Comment by MHBauer** [comment]
Was this already fixed by #1381?
@moxiegirl 
Are we waiting for a cherry-pick to the displayed docs?

**Comment by MHBauer** [comment]
I think so, because I have no instance of the string `docker networks` present in my repository.

```
λ ag 'docker networks'
λ
```

**Comment by moxiegirl** [comment]
@MHBauer I have not done a cherry-pick yet.  Next release is Thursday.

**Comment by abronan** [comment]
Docs are updated now, thanks for the report :+1:
