### ISSUE TITLE
Can't get memory limit (docker run -m) to work with Swarm

### ISSUE THREAD

**Issue by nathanleclaire** [docker/swarm#1399]
I've got a four-node Swarm cluster running in DigitalOcean (Debian 8) using Consul as the KV store in a setup very similar to what's described in the overlay networking quickstart in the docs (https://docs.docker.com/engine/userguide/networking/get-started-overlay/).  Each server has about 500m of memory.

It seems that the memory limit flag isn't working as I expected?  Historically I thought that `docker run -m` were treated as "reservations" of memory for what Swarm's reporting, but when pointed at a Swarm cluster I get:

```console
$ docker run -d -m 450m rethinkdb
66861bb71085a25808f259a4bc61332056d67f688cd9216da554c3c3e45e7025
$ docker inspect -f '{{.HostConfig.Memory}}' $(docker ps -lq)
0
```

It doesn't show up in `docker info` either:

```console
Containers: 15
Images: 32
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 4
 queenbee-nathanleclaire-11-09-2015:
  └ Containers: 5
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 519.2 MiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-4-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), provider=digitalocean, storagedriver=aufs
 workerbee-1-nathanleclaire-11-09-2015:
  └ Containers: 3
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 519.2 MiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-4-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), provider=digitalocean, storagedriver=aufs
 workerbee-2-nathanleclaire-11-09-2015:
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 519.2 MiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-4-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), provider=digitalocean, storagedriver=aufs
 workerbee-3-nathanleclaire-11-09-2015:
  └ Containers: 5
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 519.2 MiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-4-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), provider=digitalocean, storagedriver=aufs
CPUs: 4
Total Memory: 2.028 GiB
Name: 7ec9f0a9b1d3
```

So, I'm slightly perplexed.  As a result of this behavior, Swarm is happily scheduling `docker run -d -m 450m rethinkdb` many many times past the 4 that I would expect it to stop me at.

cc @aluzzardi @vieux @abronan I might be misunderstanding -- let me know if it's a bug and you can reproduce.  My cluster is still up ATM so let me know if you'd like to poke at it.

**Comment by nathanleclaire** [comment]
I should note that it's the latest of everything: `swarm:latest`, Docker Machine 0.5.0, Docker client and daemon 1.9, etc.

**Comment by vieux** [comment]
@nathanleclaire you are using the flag correctly, I don't understand what's wrong with you setup:

```
vieux@macbook /Users/victorvieux  $ docker info
Containers: 0
Images: 12
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 3
 node-1: node-1:2375
  └ Containers: 0
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.052 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-33-generic, operatingsystem=Ubuntu 14.04.2 LTS, storagedriver=aufs
 node-2: node-2:2375
  └ Containers: 0
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.052 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-33-generic, operatingsystem=Ubuntu 14.04.2 LTS, storagedriver=aufs
 node-3: node-3:2375
  └ Containers: 0
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.052 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-33-generic, operatingsystem=Ubuntu 14.04.2 LTS, storagedriver=aufs
CPUs: 6
Total Memory: 12.16 GiB
Name: macbook.local

vieux@macbook /Users/victorvieux  $ docker run -d -m 450m redis
e20ad90236916d7f491d0e793f485d24c42fd1cea3d6c45512ab07919adfcb53

vieux@macbook /Users/victorvieux  $ docker info
Containers: 1
Images: 12
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 3
 node-1: node-1:2375
  └ Containers: 0
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.052 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-33-generic, operatingsystem=Ubuntu 14.04.2 LTS, storagedriver=aufs
 node-2: node-2:2375
  └ Containers: 0
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.052 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-33-generic, operatingsystem=Ubuntu 14.04.2 LTS, storagedriver=aufs
 node-3: node-3:2375
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 450 MiB / 4.052 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-33-generic, operatingsystem=Ubuntu 14.04.2 LTS, storagedriver=aufs
CPUs: 6
Total Memory: 12.16 GiB
Name: macbook.local

vieux@macbook /Users/victorvieux  $ docker inspect -f '{{.HostConfig.Memory}}' e20ad90236916d7f491d0e793f485d24c42fd1cea3d6c45512ab07919adfcb53
471859200

vieux@macbook /Users/victorvieux  $ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/1.0.0
 API version:  1.21
 Go version:   devel +9ef10fde754f Thu Dec 11 16:32:25 2014 +1100
 Git commit:   HEAD
 Built:
 OS/Arch:      darwin/amd64
```

I'll be happy to take a look tomorrow.

**Comment by nathanleclaire** [comment]
Thanks Victor... I'll leave the Swarm cluster running and post some more logs etc. if I come across them.

**Comment by nathanleclaire** [comment]
Don't see anything interesting in the Swarm master logs so far.

**Comment by abronan** [comment]
@nathanleclaire Can't reproduce with swarm `1.0.0` and docker master :confused: not sure what is the issue and why it isn't reported correctly. This is the kind of things that the CI would catch if not working. What version of the engine are you using?

If you restart the docker engines and swarm from scratch, can you still reproduce this issue?

**Comment by nathanleclaire** [comment]
@abronan and I sat and took a look at this.  We found the problem :\

![screen shot 2015-11-11 at 11 58 46 am](https://cloud.githubusercontent.com/assets/1476820/11101408/9a2b3106-886b-11e5-9578-dbdd4a1f3264.png)

Naturally there isn't an issue with Swarm but it probably could be better documented to ensure that Swarm needs memory limit support enabled to support this feature (I know it should be obvious but it caught me off guard).  Also `docker info` on a regular daemon will report this information but not pointed at Swarm.  Things to consider!  Thanks all.

**Comment by anentropic** [comment]
can someone clarify for me... `-m` flag is a memory _limit_, or indicates to the swarm how much memory to _reserve_ for the container... or both?

**Comment by nathanleclaire** [comment]
> can someone clarify for me... -m flag is a memory limit, or indicates to the swarm how much memory to reserve for the container... or both?

It's both: `-m` to indicate the memory limit to Docker, which Swarm also uses to reserve the corresponding amount of space.

> my concern is the container scheduling... will swarm distribute containers across hosts based on -m as if it 'reserved' that amount of memory, or by how much memory they're actually using (likely little on startup)?

Based on how much they reserve.  If you schedule through Swarm it will refuse to schedule containers which reserve more memory than the system currently has available.
