### ISSUE TITLE
swarm manage always print error: ID duplicate , when 2 node register to it

### ISSUE THREAD

**Issue by xuxilei** [docker/swarm#1406]
create a swarm cluster: 1 manage , 2 node 
swarm manage always print error: ID duplicate , when 2 node register to it

both docker discovery and static local file , have this probelem

**Comment by chanwit** [comment]
You seems to clone your machines (or VMs).
Stop `docker` service, delete `/etc/docker/key.json` (or finding then delete it).
Then restart `docker` service again.

Your machines will be good to go.

**Comment by xuxilei** [comment]
solved !  thank you very much!

**Comment by lilewis** [comment]
@chanwit  thanks very good!
