### ISSUE TITLE
windows docker client can connect to  swarm manage, but linux can't 

### ISSUE THREAD

**Issue by xuxilei** [docker/swarm#1407]
create a swarm cluster:  1 manage , 2 node
the manage print error: ID duplicate 。 （I already commit as another issue）
then, a  windows docker client can connect to the swarm manage ,  get image/contain info about one node ( only one , because the error of  ID duplicate )
but linux, the docker client even can't connect to swarm manage .

**Comment by vieux** [comment]
@xuxilei we need much more logs and debug information that this.

I and most of our team as running linux, so I can assure you something is wrong with your configuration.

**Comment by xuxilei** [comment]
in linux, i do:   docker -H tcp://x.x.x.x:yy   info   ,    want to connect to swarm manage .
then, no output , wait a very long time , the terminal print:  error occur , get: EOF

**Comment by xuxilei** [comment]
i have resolved this problem:  http proxy  cause this problem .   because my no_proxy is wrong set .
but i think docker is not friendly enough.  when i test with WGET, it can give some hint on terminal: conneting to proxy .     etc 
so i suggest add a  feature: print some info on terminal when docker client's  http request was redirect to proxy.

**Comment by amitshukla** [comment]
Per Xuxilei the issue was due to his http proxy.. closing
