### ISSUE TITLE
Docker Swarm Master disappearing

### ISSUE THREAD

**Issue by miguelpuyol** [docker/swarm#1408]
I have created a docker swarm cluster with this setup:
- 1 Master Node (named swarm-master)
- 3 Nodes for Kafka contaienrs (named swarm-kafka-1, 2 and 3)
- 3 Nodes for Clients of Kafka (named swarm-client-1, 2 and 3)

The creation works fine. But when I try to run the cluster, executing containers, some of the nodes disappear, including the swarm master

```bash
eval $(docker-machine env --swarm swarm-master)
docker info
```
And the output is: (I have removed the real ips for obvious reasons)
```
Containers: 6
Images: 6
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 6
 swarm-kafka-1:ip1:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 7.67 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 14.04.2 LTS, provider=amazonec2, storagedriver=aufs
 swarm-kafka-2: ip:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 7.67 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 14.04.2 LTS, provider=amazonec2, storagedriver=aufs
 swarm-kafka-3:ip:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 7.67 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 
14.04.2 LTS, provider=amazonec2, storagedriver=aufs
 swarm-client-1: ip:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 7.67 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 14.04.2 LTS, provider=amazonec2, storagedriver=aufs
 swarm-client-2: ip:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 7.67 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 14.04.2 LTS, provider=amazonec2, storagedriver=aufs
 swarm-client-3: ip:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 7.67 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 14.04.2 LTS, provider=amazonec2, storagedriver=aufs
CPUs: 12
Total Memory: 46.02 GiB
Name: name
```

I could understand that other nodes are not visible to the master, but how can it even the master not be visible to itself?

After some time, when I run the same command and not chaning anything, the swarm-master comes back to life.

I am not using consul or any other discovery service. I see this behaviour since swarm 1.0.0

**Comment by dongluochen** [comment]
@miguelpuyol I need some info about your swarm cluster. What command do you use to start swarm? What are the logs from swarm? Output from docker version?

**Comment by abronan** [comment]
@miguelpuyol it's because it's using the `token` discovery service by default. Since very recently we saw a huge spike in Swarm token usage and requests are timing out from time to time. Thus the nodes are going to be unregistered when failing to renew their TTL in the Hub. We advise you to use Consul or Zookeeper with docker-machine in the meantime so we can investigate (and probably throw some more resources to sustain the load).

Mostly the token was designed as a way to easily get started with Swarm but we advise using `Consul`, `etcd` or `zookeeper` for sustainable production clusters.

**Comment by miguelpuyol** [comment]
Thanks for your response @abronan 

We will use our own discovery service then.
