### ISSUE TITLE
docker node not registered to swarm

### ISSUE THREAD

**Issue by raghuvirkamath** [docker/swarm#1417]
I created two machines RHEL7.1 and docker on it.
a. created a cluster on machine2 (swarm machine) and got cluster id (token)
b. registered the node to the cluster using the below command on machine1 (node) 
 sudo docker -H tcp://0.0.0.0:2375 run -d swarm join --addr=:2375 token://<token id>
c. on machine2 , i ran following command
 docker run -d -p 2374:2375 swarm manage token://<token id> --heartbeat=1s

but now when i run the list command on machine2 , it is not listing the node
 docker run --rm  swarm list token://<token id>

any idea why ? is this a bug ?

**Comment by raghuvirkamath** [comment]
the following command returns nothing 
 curl -s https://discovery-stage.hub.docker.com/v1/clusters/<token id>
[]

**Comment by dongluochen** [comment]
@raghuvirkamath Advertise address should be in the form of `--addr=<node_ip:2375>`. If you remove `-d` in step b you can see the error. 
```
time="2015-11-15T19:11:29Z" level=fatal msg="--advertise should be of the form ip:port or hostname:port" 
```

**Comment by raghuvirkamath** [comment]
thanks Dongluo Chen , I tried as you suggested but the same result .

1. create a new swarm using command in machine1 -> docker run swarm create
2. machine2 has docker and here i ran the command -> docker run -d swarm join --addr=<ip of machine2>:2375 token://<my cluster token id>
3. came back to machine1 (swarm machine) and ran the command --> 
 docker run -d -p 2374:2375 swarm manage token://<my cluster token id> --heartbeat=1s
4. tried to list the node but it is not listing .
 docker run --rm swarm list token://<my cluster token id> 
returned nothing :(
5. tried one more command 
curl -s https://discovery-stage.hub.docker.com/v1/clusters/<my cluster token id>
returned me  []

**Comment by raghuvirkamath** [comment]
thanks dongluochen i tried as you suggested

1. create a new swarm using command in machine1 -> docker run swarm create
2. machine2 has docker and here i ran the command -> docker run -d swarm join --addr=<ip of machine2 > :2375 token://
3. came back to machine1 (swarm machine) and ran the command --> docker run -d -p 2374:2375 swarm manage token:// --heartbeat=1s
4. tried to list the node but it is not listing . docker run --rm swarm list token:// returned nothing :(
5. tried one more command curl -s https://discovery-stage.hub.docker.com/v1/clusters/ returned me []

**Comment by raghuvirkamath** [comment]
thanks dongluochen i tried as you suggested

create a new swarm using command in machine1 -> docker run swarm create
machine2 has docker and here i ran the command -> 

docker run --rm -d swarm join --addr=ip of machine 2 :2375 token:// my cluster token id  


came back to machine1 (swarm machine) and ran the command --> docker run -d -p 2374:2375 swarm manage token:// --heartbeat=1s
tried to list the node but it is not listing . docker run --rm swarm list token:// returned nothing :(
tried one more command curl -s https://discovery-stage.hub.docker.com/v1/clusters/ returned me []

**Comment by dongluochen** [comment]
@raghuvirkamath After you set up swarm manager, you should run `docker -H <manager_ip:2374> info` because you set 2374 as service port. If you still see problem, please run your commands without `-d` and provide the output of each command.

**Comment by raghuvirkamath** [comment]
thanks a lot dongluochen . it worked fine now.
