### ISSUE TITLE
Prevent removal of the Swarm containers

### ISSUE THREAD

**Issue by everett-toews** [docker/swarm#1422]
Naturally it's critical to have the Swarm agent and manager containers running on the cluster. However it's very common that users are used to running `docker rm -f $(docker ps -aq)` for a quick clean up of their environment. Doing this in a Swarm causes nothing but problems for those users. 

It would be a great enhancement to Swarm usability if you could prevent the removal of the Swarm containers. A more general issue for this over in the Docker Engine project at https://github.com/docker/docker/issues/9878. 

I wanted to see what the Swarm team thinks of this and what they're currently doing to mitigate it.

**Comment by abronan** [comment]
Hi @everett-toews, I think this all falls under the `ACL` effort in Swarm and Engine (see #1366). This way an admin user can create all the Swarm containers and regular users are not able to list or manipulate those containers.

Once we get this in, we allow multiple users to manipulate their own containers or the ones they have an access to. WDYT about this approach?

**Comment by everett-toews** [comment]
Certainly seems like it would cover this case. Thanks for the info!

I'll subscribe and watch the fun over in #1366.
