### ISSUE TITLE
No Resources from Mesos

### ISSUE THREAD

**Issue by stevenpall** [docker/swarm#1423]
Hi there,

I'm currently attempting to get the Swarm Mesos driver working against a 3 node cluster. `docker engine` version is 1.9.0. `docker swarm` version is 1.0.0. I followed this doc: https://github.com/docker/swarm/blob/master/cluster/mesos/README.md and was successfully able to start the swarm manager connecting to my zookeeper nodes. The command I ran was: `docker run -d --name=swarm --restart=always -p 2375:2375 -p 3375:3375 swarm --debug manage -c mesos-experimental --cluster-opt mesos.address=10.101.5.175 --cluster-opt mesos.port=3375 zk://10.101.5.175:2181,10.101.5.173:2181,10.101.5.171:2181/mesos`. This container seems to start properly and `docker logs` does not report any connection errors. However, running `docker -H tcp://10.101.5.175:2376 info` returns
```
Containers: 0
Images: 0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Offers: 0
CPUs: 0
Total Memory: 0 B
Name: df52e006e73b
```
It appears that Mesos is not offering resources to the Swarm framework. The other reason I suspect that this is the case is that, going to the Mesos master web interface, I do not see Swarm listed as an active framework. As you might suspect, attempting to run a container against the Swarm manager also fails, presumably because it has nowhere to run the container. Is there a step that I'm missing in the setup process or is there possibly a bug in this version of docker-engine and/or swarm?

Thanks!

**Comment by rgardler** [comment]
See #1372

**Comment by stevenpall** [comment]
Hum, I built a test image from #1372, but I'm still seeing the same issue. Perhaps @vieux's fix isn't related to my issue...

**Comment by dileban** [comment]
Observing the same issue: Docker 1.9.0, Swarm 1.0.0, Mesos 0.25.0. Any workarounds?

**Comment by Spritekin** [comment]
Do not use Zookeeper, connect to the mesos master straight away. That worked fine for me.
For some reason Swarm won't accept my ZK.

Also veryfy you have started the docker daemon in the slaves listening to the shared port (2375) make sure the port is active in each slave before even trying to start the swarm manager. Check from a remote computer. The slave should report ok. If it says it is not active you have a problem.
docker -H tcp://my.slave.ip.here:2375 ps

Finally, check if the slaves are properly connected to the mesos master. Do this just by navigating to the mesos master and clicking into each slave hostname. Maybe there is a DNS problem. 

Those are the problems I have found up now regard connections.
Luck!

**Comment by bruwozniak** [comment]
We're experiencing the same issue with zk.
Unfortunately pointing swarm to the current leading mesos master in a high availability setup is a no-go as the master may change at any point.
Any leads about what is causing this and whether it will be fixed at some point?

**Comment by stevenpall** [comment]
@vieux Any idea when #1372 might get merged?

**Comment by ahmetalpbalkan** [comment]
@stevenpall @bruwozniak I have an interim fix https://hub.docker.com/r/ahmet/swarm/ `ahmet/swarm:1.0.0-zk-hotfix` we have been using for a while.

**Comment by stevenpall** [comment]
@ahmetalpbalkan Cool, thanks. I'll try that out.

**Comment by vieux** [comment]
@stevenpall it should be fixed in master, we expect to do a new release soon

**Comment by stevenpall** [comment]
@vieux Awesome, thank you.

**Comment by asdfsx** [comment]
it seems I met the same problem~~~I'm using docker 1.9.1, swarm 1.0.1, mesos 0.24.1~~
