### ISSUE TITLE
[Question] Can not create a container when the registry needs auth

### ISSUE THREAD

**Issue by panli889** [docker/swarm#1424]
We have a private registry needing auth and a self written docker cli using swarm. When we want to create a container using swarm, it can not download the image from registry since the api can not receive the 'X-Registry-Auth' header so it has no auth message.

I notice there has been some issues talking about this, maybe there are two solutions for us:

1. Use image/pull method to first download image to each node of the docker cluster, then use container/create method

1.  Change the swarm api like #1350 

which one do you recommend? Is there a plan to solve this kind of situation?

**Comment by amitshukla** [comment]
@panli889 Swarm 1.1.0 supports registries with Auth
docker pull swarm:1.1.0-rc2
Closing this question.
