### ISSUE TITLE
manage tls cert: can't recognize home directory char:~

### ISSUE THREAD

**Issue by xuxilei** [docker/swarm#1427]
it can't recognize character  ~    .    but docker daemon can .

**Comment by nishanttotla** [comment]
@xuxilei how are you running the manage command, and are you using bash? In general, your shell should expand relative paths to absolute paths, although there are some limitations. Can you try skipping the `=` sign? For instance, try running your command as follows:

```
./swarm manage -H <ip>:<port> --tlsverify --tlscacert=<CACERT> --tlscert ~/testcert --tlskey ~/testkey token://<token>
```
as opposed to
```
./swarm manage -H <ip>:<port> --tlsverify --tlscacert=<CACERT> --tlscert=~/testcert --tlskey=~/testkey token://<token>
```
The former works for me, latter doesn't, can you try and report back? Meanwhile I will check if we want to deal with this in the Swarm codebase.

cc @vieux

**Comment by nishanttotla** [comment]
Closing this issue since it's not really a Swarm issue, but a command line quirk. If more people have issues with it later, we can consider manipulating relative paths in Swarm.
