### ISSUE TITLE
stdin close event is not transferred to a docker node on TLS

### ISSUE THREAD

**Issue by yoshiokatsuneo** [docker/swarm#1430]
Swarm does not transfer "stdin close" event as TCP half close to docker node daemon when TLS is enabled.
The reason is what "crypto/tls" does not have CloseWrite() method to send half close.
"docker" package solved the issue by implementing their own CloseWrite method(and "tlsDial", "dial")
   https://github.com/docker/docker/blob/master/api/client/hijack.go
How about using the same way to handle the issue ?

```
$ eval $(docker-machine env master)
$ echo aaa | docker run -i ubuntu cat |grep aaa
aaa
$ eval $(docker-machine env --swarm master)
$ echo aaa | docker run -i ubuntu cat |grep aaa
aaa
^C^C^C^C
^C^C^C^C
^C^C^C
Connection to docker.paiza.io closed.
```

**Comment by yoshiokatsuneo** [comment]
docker version:
Client:
Version: 1.9.0
API version: 1.21
Go version: go1.4.2
Git commit: 76d6bc9
Built: Tue Nov 3 17:43:42 UTC 2015
OS/Arch: linux/amd64

Server:
Version: swarm/1.0.0
API version: 1.21
Go version: go1.5.1
Git commit: 087e245
Built:

OS/Arch: linux/amd64

docker info:
$ docker info
Containers: 22
Images: 3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 1
master: 52.68.106.74:2376
└ Containers: 22
└ Reserved CPUs: 0 / 1
└ Reserved Memory: 0 B / 1.018 GiB
└ Labels: executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 14.04.2 LTS, provider=amazonec2, storagedriver=aufs
CPUs: 1
Total Memory: 1.018 GiB
Name: 873b02fada2d

uname -a:
$ uname -a
Linux ip-172-30-1-65 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):
AWS

List the steps to reproduce the issue:
1. "docker run" to normal node, and it exit as expected.
$ echo aaa | docker run -i ubuntu cat |grep aaa
aaa

"docker run" to swarm cluster, and it never exit. $ echo aaa | docker run -i ubuntu cat |grep aaa aaa ^C^C^C^C ^C^C^C^C ^C^C^C Connection to docker.paiza.io closed.
Describe the results you received:
"docker run" never exit when stdin is closed.

Describe the results you expected:
"docker run" exit when stdin is closed.

**Comment by yoshiokatsuneo** [comment]
I also tested on the very latest docker and swarm commit.

**Comment by yoshiokatsuneo** [comment]
Related: https://github.com/docker/docker/issues/18035

**Comment by yoshiokatsuneo** [comment]
Note: the above commit does not fix this issue.

**Comment by aluzzardi** [comment]
Thanks @yoshiokatsuneo 

@cpuguy83 Would you mind taking a look into this? /cc @docker/swarm-maintainers

**Comment by cpuguy83** [comment]
Sure #1463
