### ISSUE TITLE
why is mesos-go instead  of mesos http API

### ISSUE THREAD

**Issue by kendiyqx** [docker/swarm#1435]
mesos-go is experimental and mesos Scheduler HTTP API is experimental too

**Comment by tnachen** [comment]
mesos http API is a very recent finished API and mesos-go will be supporting the HTTP api as the current development progresses. So eventually swarm will be using mesos http API with latest mesos-go.

**Comment by abronan** [comment]
@kendiyqx Feel free to comment below if you have any more questions :) hope you had the details you wanted from the answer above. Closing.
