### ISSUE TITLE
Return EOF when ps -a

### ISSUE THREAD

**Issue by c2j** [docker/swarm#1436]
"docker ps" and "docker ps -a" will be OK, "docker -H swarm-manager:2376 ps" is OK also, but if input "docker -H swarm-manager:2376 ps -a", it will report an error:
An error occurred trying to connect; Get http://swarm-manager:2376/v1.21/containers/json?all=1; EOF

**Comment by abronan** [comment]
Hi @c2j. This seems related to docker/docker#18009 somehow but I fail to reproduce the issue. Are you using `docker-machine` to setup the swarm cluster?

Also, can you give us some more information about your setup? Mostly the output of:

- `docker info`
- `docker version`
- `uname -a`

Thanks!

**Comment by c2j** [comment]
Thanks, A lot of dead containers exist in some node, When I remove them manually, then execute "docker -H swarm-manager:2376 ps -a" show me OK.
So I consider it's related with DEAD containers.

**Comment by schmunk42** [comment]
Possibly related: https://github.com/docker/swarm/issues/1421
