### ISSUE TITLE
Readme of swarm discovery - broken links

### ISSUE THREAD

**Issue by herau** [docker/swarm#1437]
All the links are broken in the `Docker Swarm documentation index` part in the readme file

**Comment by MHBauer** [comment]
On github, or on docs.docker.com ?

**Comment by herau** [comment]
@MHBauer on [github](https://github.com/docker/swarm/blob/master/discovery/README.md)

**Comment by chanwit** [comment]
@herau It's normally broken when you're viewing on Github. I've heard someone's going to fix it. Please use docs.docker.com in the mean time.

**Comment by abronan** [comment]
Thanks for reporting the issue @herau, seems like it's all good now :) Closing.
