### ISSUE TITLE
Network error when deploying compose app on digitalocean swarm

### ISSUE THREAD

**Issue by lucj** [docker/swarm#1440]
Hi,

When I run the following compose file against a fresly created swarm (consul, 1 master, 1 agent) on DigitalOcean:
 
    interlock:
      image: ehazlett/interlock
      ports:
        - "80:80"
      volumes:
        - /etc/docker:/etc/docker
      command: "--swarm-url tcp://xxx.xxx.xxx.xxx:2376 --swarm-tls-ca-cert=/etc/docker/ca.pem --swarm-tls-cert=/etc/docker/server.pem --swarm-tls-key=/etc/docker/server-key.pem --plugin haproxy start"
    db:
      image: mongo:3.0
      command: "--storageEngine wiredTiger"
      environment:
        - "constraint:node==demo0"
    api:
      image: lucj/message-app:v3
      environment:
        - INTERLOCK_DATA={"hostname":"api","domain":"message-app.com"}
 
I got the following error:
 
    $ docker-compose -f docker-compose-do.yml --x-networking --x-network-driver=overlay up
    Pulling api (lucj/message-app:v3)...
    h0: Pulling lucj/message-app:v3... : downloaded
    h1: Pulling lucj/message-app:v3... : downloaded
    Creating testscale_api_1
    ERROR: Cannot start container 1fbf030de329c6620dec3b5207bec8342a35f7f77531324941b24efae685bb6c: subnet sandbox join failed for "10.0.0.0/24": vxlan interface creation failed for subnet "10.0.0.0/24": failed in prefunc: failed to set namespace on link "vxlane8ab84a": invalid argument

Is there something special to use for the multihost network on a swarm with compose ?

**Comment by chanwit** [comment]
@lucj  Could you please confirm that your VM's running Debian Jessie (or Linux with Kernel 3.16)?

**Comment by lucj** [comment]
@chanwit I was running 14.04 (default DigitalOcean image) with kernel 3.13.
I've just tested to create the swarm (consul + master + agent) with several other ubuntu images (14.10, 15.04 or 15.10) but each time the creation fails (https://github.com/docker/machine/issues/2366)

**Comment by lucj** [comment]
@chanwit I've tested with Debian Jessie and its 3.16 kernel, the swarm is created correctly.
Thanks a lot for your help !
