### ISSUE TITLE
new demand

### ISSUE THREAD

**Issue by woshihaoren** [docker/swarm#1441]
Hi:
   I have a new demand. 
   Docker doesn't support update time, But My test envirment's application needs update time. So I run some kvm. I wish I could run only one container at KVM, through swarm scheduling filter.

Like this:
   docker  -H 10.255.33.102:2376 run -d -P -e constraint:machine==kvm -e constraint:containers==0  tomcat

But, Now docker info's Containers is not a Standard Constraints.

I just  use  docker  -H 10.255.33.102:2376 run -d -P -e constraint:machine==kvm -e constraint:node==server-10-255-6-130.com tomcat
If I wrap docker command, I can get node of kvm node containers is 0. It's OK, But docker-compose doesn't support this.

docker  -H 10.255.33.102:2376 info
Containers: 33
Images: 17
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 server-10-255-6-130.com: 10.255.6.130:2375
  └ Containers: 0
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 1.005 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.10.0-229.el7.x86_64, machine=kvm, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
 server-10-255-33-102.com: 10.255.33.102:2375
  └ Containers: 4
  └ Reserved CPUs: 0 / 25
  └ Reserved Memory: 2 GiB / 132.2 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.18.24, machine=nokvm, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
CPUs: 27
Total Memory: 133.2 GiB
Name: server-10-255-33-102.com

Would you plan support docker info's Containers be a Standard Constraints, or add a dynamic label. 
                                                                                                                

Thanks

**Comment by aluzzardi** [comment]
Hey @woshihaoren, you can achieve that by using *affinities*.

Example:

```
docker run --label foo=bar -e affinity:foo!=bar tomcat
```

What that does is:
1. Create a tomcat container
2. Label that container `foo=bar` (with `--label`)
3. Tell Swarm to **never** run that container on the same machine where another container labeled `foo=bar` is already running (`-e affinity:foo!=bar`)

This will effectively guarantee that you only have one container running per machine.

Let me know if it makes sense!

**Comment by woshihaoren** [comment]
Hi:
   Thank for you help. It's can resolve my demand .

**Comment by aluzzardi** [comment]
Awesome!

Please re-open the issue if it doesn't work out for you.
