### ISSUE TITLE
Swarm HTTP API and CORS not working for other verbs than GET

### ISSUE THREAD

**Issue by Bahaika** [docker/swarm#1442]
Hi,

It seems there is a bug in the implementation of the --cors option. I'm currently working on a web interface to manage a swarm cluster, and I consume the HTTP API using AngularJS.
I started the swarm manager with the `--cors` option, and I can use it for all the GET requests. But when it comes to the POST requests, nothing works anymore :

```
XMLHttpRequest cannot load http://172.31.8.142:3375/networks/create.
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:9000' is therefore not allowed access. The response had HTTP status code 404.
```

The thing is, it didn't do a POST request, but an OPTIONS request.
So, I started digging a little. When in a CORS case, if you try to request with something else than GET, the browser will always asks the server if it can do the request using a OPTIONS request. The server is supposed to respond with headers to allow the browser to emit the real request :

```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, PUT, DELETE, PATCH
```

It would be nice to implement this in the swam manager.

**Comment by MHBauer** [comment]
I'm going to guess this line, https://github.com/docker/swarm/blob/master/api/primary.go#L93 needs to be `"/"` or `"/*"`. I am going to try to write a test.
