### ISSUE TITLE
Proposal for changes to the "filters" docs

### ISSUE THREAD

**Issue by dnephin** [docker/swarm#1444]
I'd like to propose some changes to https://docs.docker.com/swarm/scheduler/filter/, which I'm happy to write up if there is some agreement.

1. Rename this section to something like "Scheduling Constraints and Affinities" instead of filters. I understand the implementation of this is basically "filter nodes", but as a user, I don't really see these as filters. Maybe it's just me, I don't feel that strongly about this point. Other naming suggestions are also welcome.
2. Change the section titles to include the thing they filter by, either Node or Container (ex: "Node constraint", "Container affinity", "Node health", "Node ports")
3. Move "Expression Syntax" and "Soft Affinities" sections out from  "Affinity filter" section, and into a new section about "Applying constraints and affinities", and link to it from the introduction.
4. ~~Organize the filters by "user defined" filters (constraint, affinity) and "automatic" filters (port, dependency, health) that get applied without any custom settings.~~ Also mention this in the docs explicitly.
5. Mention that all of these constraints and affinities consider stopped containers, not just running containers, when filtering. I think this might fit into the new "Applying constraints and affinities" section, or maybe in the intro.

+kind/docs

**Comment by dnephin** [comment]
cc @moxiegirl

**Comment by aluzzardi** [comment]
:+1: 

I'd love to see those changes.

**Comment by dnephin** [comment]
Cool, I submitted a first draft in #1445
