### ISSUE TITLE
Without `discovery.hub.docker.com`,could i create a swarm cluster?

### ISSUE THREAD

**Issue by cnsinger** [docker/swarm#1455]
Hi, 
I am in an internal network,and i can't connect `discovery.hub.docker.com`.

When i install swarm by this [install-manual](http://docs.docker.com/swarm/install-manual/), i get some errors.

```
level=error msg="Post https://discovery.hub.docker.com/v1/clusters/6856663cdefdec325839a4b7e1de38e9?ttl=60: dial tcp: i/o timeout"
```

PS: this token is created by myself.

Without `discovery.hub.docker.com`, could i create a swarm cluster?

Wish your help,
Thanks.

Thanksgiving wishes for you and your family, at last.

**Comment by auzias** [comment]
Yes you can! I suggest you to use static file (the easiest, safest and fastest mean to create a swarm IMHO).
[Docker doc](https://docs.docker.com/swarm/discovery/https://docs.docker.com/swarm/discovery/#using-a-static-file-describing-the-cluster), [step-by-step tutorial using it](https://www.auzias.net/en/docker-network-multihost/#static-file-start-the-swarm-manager-while-joining-swarm-members:b286545a85a53658f9118404059fc18b).

You can also use etcd or consul.

**Comment by aluzzardi** [comment]
ping @vieux

**Comment by cnsinger** [comment]
@auzias  Thanks,it's useful.

**Comment by auzias** [comment]
My pleasure. Happy to be helpful !

**Comment by aluzzardi** [comment]
@cnsinger Yes you can as @auzias explained.

Sorry for the inconvenience - the token discovery is back and the issue is tracked by #1455.
