### ISSUE TITLE
Docker Inspect for images from Swarm Manager prints  HTTP error:No such container hello-world:latest  status=404.

### ISSUE THREAD

**Issue by ankitsnlq** [docker/swarm#1456]
I have installed swarm manager on one of virtual machine and replica for swarm manager as well using consul discovery. Added two swarm node using swarm join docker container described on official swarm DOCS. I have compiled swarm manager from Github Repo instead of using Docker container for swarm manager.

On one of Swarm manager  either Primary or Replica when i give command docker inspect for image name on first line swarm return ERRO[5241] HTTP error: No such container imagename           status=404 just below that error it prints all detail about same image for which it returned error message.

For example when i give command docker inspect swarm  it  will return output as follow.

ERRO[5241] HTTP error: No such container swarm           status=404
[
{
    "Id": "6b40fe7724bd29107f6182ca2befec011cdf524b23ebc4c9a33591d6b7aea4ee",
    "RepoTags": [
        "swarm:latest"
    ],
    "RepoDigests": [],
    "Parent": "2b4c55187a27a43f6c5aebab707e75cffee14f7c3cc02e4f74429992bd5f7db2",
    "Comment": "",
    "Created": "2015-11-03T20:07:32.218088604Z",
    "Container": "f6d1a64a408c5c1a696712ddbaf2722718fe4fe4828d16f234e876fb21dbc7fe",
    "ContainerConfig": {
        "Hostname": "a9b6c6521f07",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "2375/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "SWARM_HOST=:2375"
        ],
        "Cmd": [
            "/bin/sh",
            "-c",
            "#(nop) CMD [\"--help\"]"
        ],
        "Image": "26b910067c5f19b5ec691e85b486cf508739ad60158d61f295c12e29d062dbaa",
        "Volumes": {
            "/.swarm": {}
        },
        "WorkingDir": "",
        "Entrypoint": [
            "/swarm"
        ],
        "OnBuild": null,
        "Labels": null
    },
    "DockerVersion": "1.8.2",
    "Author": "",
    "Config": {
        "Hostname": "a9b6c6521f07",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "2375/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "SWARM_HOST=:2375"
        ],
        "Cmd": [
            "--help"
        ],
        "Image": "26b910067c5f19b5ec691e85b486cf508739ad60158d61f295c12e29d062dbaa",
        "Volumes": {
            "/.swarm": {}
        },
        "WorkingDir": "",
        "Entrypoint": [
            "/swarm"
        ],
        "OnBuild": null,
        "Labels": null
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Size": 0,
    "VirtualSize": 15602184,
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    }
}
]

Docker Version Output on Nodes : 

Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Docker Version Output on Swarm Manager : 

Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.0.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   HEAD
 Built:        
 OS/Arch:      linux/amd64

Docker Info output on Swarm Manager : 

Containers: 81
Images: 22
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 arun-Latitude-3550: 172.16.0.247:2375
  └ Containers: 42
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 8.099 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-68-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
 raw1-VirtualBox: 172.16.0.255:2375
  └ Containers: 39
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.019 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-32-generic, operatingsystem=Ubuntu 14.04.1 LTS, storagedriver=aufs
CPUs: 5
Total Memory: 9.118 GiB
Name: swarm-master

Docker Info Output on one of Node : 
Containers: 42
Images: 159
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 243
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.713 GiB
Name: arun-Latitude-3550
ID: JAST:ALW6:7WPH:7QZZ:QXQQ:2AZJ:SGA6:MG2O:NC7I:X7CT:EGSF:MY5C
WARNING: No swap limit support

uname -a on Node : 

Linux arun-Latitude-3550 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Uname -a on Swarm Manager : 

Linux swarm-master 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jimmyxian** [comment]
@ankitsnlq 
Can you provide the cmd you setup swarm cluster?
I guess you run swarm manager with `&`, and you run `docker inspect` in the same console.

**Comment by ankitsnlq** [comment]
Yes @jimmyxian you are right have started docker swarm manager  with & and running inspect command on same terminal. Is it expected behaviour ?

**Comment by jimmyxian** [comment]
@ankitsnlq Yeah, it's OK. :)
