### ISSUE TITLE
IPsec capabilities?

### ISSUE THREAD

**Issue by pierreozoux** [docker/swarm#1458]
I just saw the new nice feature of cross host linking. This is nice, but if you want to do a cross IaaS provider setup (like in this [video](https://youtu.be/3I6hWb24_qE), I don't see the point without a VPN.
My question is is there any plan to support this kind of feature? (Or even, is it already the case?)

I tried to look around, and didn't find any answers. Tell me if it is the right place to discuss that matter?

**Comment by cpuguy83** [comment]
Yes, it's planned and I _believe_ scheduled for docker 1.10.
Note that this really belongs in https://github.com/docker/libnetwork

**Comment by pierreozoux** [comment]
Thanks @cpuguy83 !
