### ISSUE TITLE
Dockerfile ENTRYPOINT

### ISSUE THREAD

**Issue by pixeleet** [docker/swarm#1462]
Having a default entrypoint set on the binary is usually great, because the developer doesn't need to know where the binary was copied in.

However in AWS ECS I found the need to use an environment variable to inject the docker host address.

https://github.com/aws/amazon-ecs-agent/issues/3

However, you can't change the entrypoint to `/bin/sh` manually in the task defintion because you'll get.
```
exec: "/bin/sh": stat /bin/sh: no such file or directory
```

To enable the Swarm-Agent in ECS to connect to consul and advertise with the right host ip I've ended up with this `ecs-task-definition`. 
```
[
  {
    "volumesFrom": [],
    "memory": 256,
    "extraHosts": null,
    "dnsServers": [
      "172.17.42.1"
    ],
    "disableNetworking": null,
    "dnsSearchDomains": [
      "consul"
    ],
    "hostname": null,
    "essential": true,
    "name": "Swarm-Agent",
    "ulimits": null,
    "dockerSecurityOptions": null,
    "links": [],
    "workingDirectory": null,
    "readonlyRootFilesystem": null,
    "image": "pixeleet/swarm:latest",
    "command": [
      "/bin/bash",
      "-c",
      "swarm join --advertise=$(curl -s 169.254.169.254/latest/meta-data/local-ipv4):2375 consul://consul.service.consul:8500/nodes"
    ],
    "user": null,
    "dockerLabels": null,
    "logConfiguration": null,
    "cpu": 256,
    "privileged": null
  }
]
```

Had to create my own image without the explicit `ENTRYPOINT` in it and use that in order to be able to get the host ip from the Metadata Service. A consul agent is running with port 53 mapped to host, hence the docker gateway being set as the dns for the containers all around.

Am I missing something here and being extremely ignorant and stupid at the same time?

**Comment by cpuguy83** [comment]
The swarm image doesn't have anything except statically compiled swarm in it.
So there is no sh, bash, or anything.

**Comment by pixeleet** [comment]
That's what I thought.
So I removed the `ENTRYPOINT` and voila!
The default go shell kicks in and I can just have my variable replaced
before starting swarm.

It's more of an ECS Issue than Swarm as I've mentioned before but If
someone has the idea to run Swarm on ECS this is how you can run it.


2015-11-29 15:42 GMT+01:00 Brian Goff <notifications@github.com>:

**Comment by abronan** [comment]
@pixeleet This is blog post worthy :) not sure if much users have tried to run swarm on ECS.

Closing as this one is solved, but let us know if you run into any trouble running Swarm on ECS in the future.
