### ISSUE TITLE
Can't load image into Swarm cluster

### ISSUE THREAD

**Issue by nazar-pc** [docker/swarm#1464]
#### docker version
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64
```
#### docker info (under swarm)
```
Containers: 5
Images: 7
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 4
 master: 192.168.99.114:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 517.6 MiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.13-boot2docker, operatingsystem=Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015, provider=virtualbox, storagedriver=aufs
 slave-1: 192.168.99.115:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 517.6 MiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.13-boot2docker, operatingsystem=Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015, provider=virtualbox, storagedriver=aufs
 slave-2: 192.168.99.116:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 517.6 MiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.13-boot2docker, operatingsystem=Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015, provider=virtualbox, storagedriver=aufs
 slave-3: 192.168.99.117:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 517.6 MiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.13-boot2docker, operatingsystem=Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015, provider=virtualbox, storagedriver=aufs
CPUs: 4
Total Memory: 2.022 GiB
Name: 3d4377d2a3d9
```

#### uname -a
```
Linux nazar-pc 4.3.0-haswell #1 SMP Mon Nov 2 06:42:33 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
```

#### How to reproduce
Bad:
```
$ eval $(docker-machine --swarm master)
$ docker load < /media/Data/mariadb.tar 
An error occurred trying to connect: Post https://192.168.99.114:3376/v1.21/images/load: write tcp 192.168.99.114:3376: connection reset by peer
```
Good:
```
$ eval $(docker-machine master)
$ docker load < /media/Data/mariadb.tar
```

#### Additional info
`/media/Data/mariadb.tar` is 436 MiB

**Comment by dongluochen** [comment]
@nazar-pc Can you enable swarm debug logs? Command is like `./swarm -l "debug" manage -H 0.0.0.0:2372 consul://192.168.56.204:8500/swarm`. You should be able to see logs on your load command like 
```
DEBU[7267] HTTP request received                         method=POST uri=/v1.21/images/load
```

**Comment by nazar-pc** [comment]
As you may know it is not trivial to put anything before `manage` with Docker Machine and I'm too lazy to do that manually.
However, some more info:
* error doesn't happen with 1 node (which is master by coincidence in Docker Machine-created Swarm)
* I see nice long stacktrace in logs of master container (it is too long to place it here): http://pastebin.com/a7gQri6y

**Comment by dongluochen** [comment]
@nazar-pc I think your suspicion of memory allocation failure is right. The swarm load operation creates multiple writers and copies content from reader to writers. The master with both reader and a writer may run out of memory when the image size is close to node's memory. I can trigger **cmalloc** failure by controlling memory limit on master node. (Docker `load` is implemented differently from swarm.)

Also it's recommended not to put agent on swarm master node to avoid resource contention.

**Comment by nazar-pc** [comment]
Thanks for confirmation.
I'd be happy to separate them, but it is not currently possible just that easily with Docker Machine (https://github.com/docker/machine/issues/2302) and this is just my laptop for experiments, not production setup.
In any case it would be nice if Swarm can detect this issue and handle it somehow without being crashed.

**Comment by jimmyxian** [comment]
Related: https://github.com/docker/swarm/issues/1163
Maybe using the registry is a good workaround

**Comment by nazar-pc** [comment]
Yes, according to description looks like this is a duplicate of mentioned issue.
I'm closing this, hopefully issue will be resolved soon.
