### ISSUE TITLE
docker -H tcp://<swarm-ip>:<swarm-port> info only sees 1 node  whereas swarm list sees whole cluster

### ISSUE THREAD

**Issue by barbarello** [docker/swarm#1467]
I've setup a 3 node cluster each running docker, swarm and consul.   All nodes are identical in that they run the same version for the docker,swarm, consul stack,  including same base ubuntu image:

1.  Here are the join cmds on each node:
$<b>docker run</b> -d --name swarm-node-0 swarm join --addr=<b>10.128.1.65:2375</b> consul://10.128.1.65:8500/swarm
$<b>docker run</b> -d --name swarm-node-1 swarm join --addr=<b>10.128.2.104:2375</b> consul://10.128.2.104:8500/swarm
$<b>docker run</b> -d --name swarm-node-2 swarm join --addr=<b>10.128.3.174:2375</b> consul://10.128.3.174:8500/swarm

2.  Here is the swarm manager cmd with no replicas:
$docker run -d -p 8333:2375 --name swarm-manager swarm manage consul://10.128.1.65:8500/swarm

3.  Here is docker/swarm/go stack version (same for all 3 nodes)
$docker -H tcp://10.128.1.65:2375 version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/ad64

4. Cluster members as reported with swarm list:
$<b>docker -H tcp://10.128.1.65:8333 run --rm swarm -l debug list consul://10.128.1.65:8500/swarm</b>
time="2015-11-30T17:01:06Z" level=debug msg="Initializing discovery service" name=consul uri="10.128.1.65:8500/swarm" 
time="2015-11-30T17:01:06Z" level=debug msg="Initializing discovery without TLS" 
time="2015-11-30T17:01:06Z" level=debug msg="Watch triggered with 3 nodes" discovery=consul
<b>10.128.1.65:2375
10.128.2.104:2375
10.128.3.174:2375</b>
<b>docker -H tcp://10.128.2.104:2375 run --rm swarm -l debug list consul://10.128.2.104:8500/swarm</b>
time="2015-11-30T17:02:45Z" level=debug msg="Initializing discovery service" name=consul uri="10.128.2.104:8500/swarm" 
time="2015-11-30T17:02:45Z" level=debug msg="Initializing discovery without TLS" 
time="2015-11-30T17:02:45Z" level=debug msg="Watch triggered with 3 nodes" discovery=consul 
<b>10.128.1.65:2375
10.128.2.104:2375
10.128.3.174:2375</b>
$<b>docker -H tcp://10.128.3.174:2375 run --rm swarm -l debug list consul://10.128.3.174:8500/swarm</b>
time="2015-11-30T17:03:37Z" level=debug msg="Initializing discovery service" name=consul uri="10.128.3.174:8500/swarm" 
time="2015-11-30T17:03:37Z" level=debug msg="Initializing discovery without TLS" 
time="2015-11-30T17:03:37Z" level=debug msg="Watch triggered with 3 nodes" discovery=consul 
<b>10.128.1.65:2375
10.128.2.104:2375
10.128.3.174:2375</b>

5. Consul cluster is also a 3 node cluster:
consul members
Node                   Address                  Status  Type     Build  Protocol  DC
ip-10-128-1-65   10.128.1.65:8301     alive     server  0.5.2  2             lab
ip-10-128-2-104  10.128.2.104:8301  alive     server  0.5.2  2             lab
ip-10-128-3-174  10.128.3.174:8301  alive     server  0.5.2  2             lab

6.  Consul leader query
curl http://10.128.1.65:8500/v1/kv/swarm?recurse | python -m json.tool
[
    {
        "CreateIndex": 11,
        "Flags": 0,
        "Key": <b>"swarm/docker/swarm/nodes/10.128.1.65:2375"</b>,
        "LockIndex": 1,
        "ModifyIndex": 241,
        "Session": "749058b0-2167-0173-61cb-21c87b23a768",
        "Value": "MTAuMTI4LjEuNjU6MjM3NQ=="
    },
    {
        "CreateIndex": 18,
        "Flags": 0,
        "Key": <b>"swarm/docker/swarm/nodes/10.128.2.104:2375"</b>,
        "LockIndex": 1,
        "ModifyIndex": 242,
        "Session": "4990f682-3bb5-491b-f564-46f1a301d765",
        "Value": "MTAuMTI4LjIuMTA0OjIzNzU="
    },
    {
        "CreateIndex": 14,
        "Flags": 0,
        "Key": <b>"swarm/docker/swarm/nodes/10.128.3.174:2375"</b>,
        "LockIndex": 1,
        "ModifyIndex": 240,
        "Session": "5f36ae30-ecf5-3dc9-b714-e19062289fea",
        "Value": "MTAuMTI4LjMuMTc0OjIzNzU="
    },
    {
        "CreateIndex": 20,
        "Flags": 0,
        "Key": "swarm/docker/swarm/nodes",
        "LockIndex": 0,
        "ModifyIndex": 20,
        "Value": null
    }
]

7.  The swarm manager can contact docker on other nodes and itself at port 2375 as shown below:

$<b>docker -H tcp://10.128.1.65:2375 info</b>
Containers: 4
Images: 15
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: EXT's
 Dirs: 23
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 992.5 MiB

$<b>docker -H tcp://10.128.2.104:2375 info</b>
Containers: 3
Images: 15
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 992.5 MiB

$<b>docker -H tcp://10.128.3.174:2375 info</b>
Containers: 3
Images: 15
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 992.5 MiB

------------------------------------------------------------------------------------------

Issue:
**However ,  when querying the swarm manager with docker -H tcp://<swam-manager-ip>:<swarm-port> info, i get the following:

<b>docker -H tcp://10.128.1.65:8333 info</b>
Containers: 3
Images: 3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
<b><color>Nodes: 1</color=red></b>
 ip-10-128-2-104: 10.128.2.104:2375
  └ Containers: 3
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.018 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-68-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
CPUs: 1
Total Memory: 1.018 GiB
Name: 163af7e872a2

I have tried this countless times but the swarm manager ALWAYS ONLY list the same node (10.128.2.104).     it fails to to list itself(10.128.1.65) , and node 10.128.3.174.

Any insight appreciated.

**Comment by abronan** [comment]
Hi @barbarello, are you cloning your VMs to setup your nodes? My first guess is that your docker daemons have the same unique IDs because of the cloning, thus the Manager will only see one Agent as it will assume that this is the same underlying docker Engine.

**Comment by barbarello** [comment]
@abronan   thanx for your prompt reply.

I'm using the same packer ubuntu ami for all 3 nodes.  docker is pre-installed in the ami.

**Comment by barbarello** [comment]
@abronan 

docker -H tcp://10.128.1.65:2375 info   |  grep ID
docker -H tcp://10.128.2.104:2375 info |  grep ID
docker -H tcp://10.128.3.174:2375 info |  grep ID

all return the same   <b>ID: DSPS:LTON:S4ZH:5VJY:PU6A:MUMO:5KQT:LPMU:VN7G:PZVE:Q6ZX:E3QF </b>

If this is what ye're referring to,  then 
I will remove the docker from the base image, and do a manual install of docker on each node so that the deamon have their own unique IDs.

Will report back here after that.

**Comment by MHBauer** [comment]
Wait for someone else to confirm, but I think you can achieve the same thing by finding `key.json`, deleting the file and restarting docker daemon service.

**Comment by Farjad** [comment]
Yes what @MHBauer said should fix your issue.

**Comment by barbarello** [comment]
@abronan 
removing docker from the base ami , and doing a docker manual install on each node, + reboot did NOT solve the issue.    ID is still the same.

Now trying @MHBauer 's suggestion.

**Comment by Farjad** [comment]
@barbarello 

It will continue to use the ID specified in key.json until it is deleted. I don't think reinstalling changes it.

**Comment by abronan** [comment]
@barbelio Yes because it will keep the same `key.json` file. The file with the ID should be explicitly removed before attempting a reinstall. Sorry for the confusion. This should work fine with @MHBauer 's suggestion.

Tagging as a `docs` issue, we should emphasize more on this aspect and properly warn users.

**Comment by barbarello** [comment]
Hi @MHBauer ,    your fix worked.

@abronan ,   thank you for updating the public facing docs.

**Comment by aluzzardi** [comment]
Thanks for reporting the issue, @barbarello.

We are going to fix this ASAP in the docs (#1472) but longer term we are going to make the problem more obvious by reporting it in `docker info`, as explained in #1486.
