### ISSUE TITLE
undefined parsers.ParseRepositoryTag on Windows 10

### ISSUE THREAD

**Issue by alexandrev** [docker/swarm#1469]
I'm trying to compile swarm on Windows and I'm getting all the time the following error: 

```# github.com/docker/swarm/cluster
cluster\image.go:27: undefined: parsers.ParseRepositoryTag
cluster\image.go:31: undefined: parsers.ParseRepositoryTag
cluster\image.go:43: undefined: parsers.ParseRepositoryTag
cluster\image.go:88: undefined: parsers.ParseRepositoryTag```

I've installed go and godep but no luck in this time. It seems like the parsers pkg (github.com/docker/docker/pkg/parsers) have been downloaded, but no luck.

The same problems is still happening. Any help to go through this problem?

Thanks!

**Comment by lmfmkos** [comment]
I have the same with Ubuntu 14.04, docker version 1.9.1

**Comment by jayunit100** [comment]
I think actually you'll be seeing this error when trying to build anything that relies on a certain version of the docker parsers pkg.  i see it with some kube images.

**Comment by noelyahan** [comment]
According to swarm Docker file https://github.com/docker/swarm/blob/master/Dockerfile before it builds the swarm it excuites the git rev-parse --short HEAD command. So I was able to fix this issue by folliwing https://github.com/docker/swarm/ build steps with above git command 

$ mkdir -p $GOPATH/src/github.com/docker/
$ cd $GOPATH/src/github.com/docker/
$ git clone https://github.com/docker/swarm
$ cd swarm
$ git rev-parse --short HEAD
$ $GOPATH/bin/godep go install .

$ export PATH=$PATH:~/go/bin
$ swarm

**Comment by vieux** [comment]
This can happen when our dependencies changes (in this case, docker/docker removed the `ParseRepositoryTag` function)

You need to use `godeps` when compiling to use the dependencies that are saved in this repository instead.

See https://github.com/docker/swarm/pull/1645
