### ISSUE TITLE
libnetwork: syncing network list based on events

### ISSUE THREAD

**Issue by abronan** [docker/swarm#1470]
As of now, creating and deleting a network works well if done exclusively through Swarm or a single docker engine. But as there are no events generated on the libnetwork side, swarm can end up with stale informations if a network is removed directly from a docker node.

Those informations are going to be synced on the next `refresh` loop but swarm does not append the right node information to the network, thus the network is unusable from Swarm.

Also this might result in cases where Swarm is listing the same network multiple times if we create it through Swarm but remove it directly through the Engine. There are also cases where a network name can be made forever unavailable through Swarm.

We can mitigate those issues on `Refresh_Network` on the Swarm side to append the right informations to the network but the experience is still inconsistent on adding/removing networks if done often as it is bound to the refresh time interval (for Compose users for example), so the right way is to do it through events.

This is an enhancements to be made both in `libnetwork` (to generate those events) and `swarm` (to listen and take appropriate actions based on those events).

/cc @mavenugo

**Comment by vieux** [comment]
@abronan now that libnetwork emit events, should we close this one ?

**Comment by abronan** [comment]
@vieux I need to try to reproduce first, I think this may still be an issue in some cases.

**Comment by abronan** [comment]
Closed by #2400 and #2255
