### ISSUE TITLE
timeout when docker run swarm create

### ISSUE THREAD

**Issue by gotcha** [docker/swarm#1482]
When I do `docker run swarm --debug create` with `swarm version 1.0.0 (087e245)`, I get 
   
    dial tcp 50.16.209.231:5452: getsockopt: connection timed out

FYI,  when doing

    curl -X POST https://discovery.hub.docker.com/v1/clusters

from various hosts in various networks, I get the exact same timeout error message.
This makes me believe that the service itself is broken.

This issue might be related to #664.

**Comment by bencolon** [comment]
Same for me for one hour.
Everything was working well this morning ..

**Comment by JackKar** [comment]
+1

Same here

**Comment by johnjelinek** [comment]
I think the discovery service is down at the moment. It'd be nice if there was a status page for that.

**Comment by ssebbass** [comment]
same error here, running on local vbox (trusty), and in AWS (jessie)

# docker run --rm swarm create
dial tcp 50.16.209.231:5452: connection timed out

**Comment by raimille1** [comment]
Same here!

**Comment by remonlam** [comment]
Ah so it isn't just me ;-) same thing over here:

$ docker run --rm swarm create
  dial tcp 50.16.209.231:5452: getsockopt: connection timed out

$ docker run --rm swarm list token://...
  2015/12/02 20:12:09 Timed out

**Comment by remonlam** [comment]
yeah they fixed it, it's working again!

**Comment by gotcha** [comment]
@johnjelinek I agree. A status page would be useful.

**Comment by bencolon** [comment]
Down again ?
`$ docker run swarm create
dial tcp 54.197.250.94:5892: connection refused
`
Same for you guys ?

**Comment by mbentley** [comment]
It is working fine for me here:

# docker run --rm swarm create
ea6556bd86adb7391ab3dbfee7827c8c

**Comment by bencolon** [comment]
It's working fine for me too now.
Thanks @mbentley

**Comment by remonlam** [comment]
Well it's kinda unstable at the moment, it's working for now but sometimes it gives a timeout/500 response.

Does anyone know if there's a status page for the discovery service?

**Comment by aluzzardi** [comment]
@johnjelinek @gotcha @remonlam Thanks for the feedback - we just added the status of the discovery service to  http://status.docker.com/

**Comment by johnjelinek** [comment]
@aluzzardi: thanks :+1:

**Comment by remonlam** [comment]
@aluzzardi that's great, thanks!

**Comment by abronan** [comment]
We can close, *thanks everyone for your patience*. We have updated the service and it's back to normal.

Please make sure to use the **kv discovery** for production usage [see the consul/etcd/zookeeper sections on the [discovery docs](https://github.com/docker/swarm/tree/master/discovery)].

The token discovery is only a mean for new users to get started with Swarm before moving on to the other node discovery alternatives. Thanks for your understanding.

**Comment by gotcha** [comment]
@abronan Thanks for adding swarm discovery to the status page.

It is very clear this should not be used in production but as a way of getting started.
