### ISSUE TITLE
Markup error in the swarm discovery docs

### ISSUE THREAD

**Issue by petarmaric** [docker/swarm#1483]
"User guide" should be a link on https://docs.docker.com/swarm/discovery/#docker-swarm-documentation-index

**Comment by vieux** [comment]
ping @moxiegirl

**Comment by moxiegirl** [comment]
@petarmaric  Thank you for the issue.  @vieux user guide is a misnomer, this is the introduction to Swarm. I'm going to change the files accordingly.
