### ISSUE TITLE
Revisit default discovery TTL/heartbeat values

### ISSUE THREAD

**Issue by abronan** [docker/swarm#1485]
Current default discovery TTL values are pretty low and the load is heavy on the kv discovery/token service.

Those values are configurable anyway so we can consider increasing to a higher default value. To be defined.

/cc @docker/swarm-maintainers

**Comment by MHBauer** [comment]
Thoughts:
 1. Scale the values based on number of connected nodes, or node/master ratio.
  - simple, yet dynamic over time.
 2. Scale automatically based on timeouts.
  - dynamic, but very complicated

**Comment by aluzzardi** [comment]
Also - keep in mind that Swarm already does active health checking and flags nodes as dead when they are dead.

Discovery TTL doesn't impact health checking - the only downside in high discovery TTLs if when you retire a node (as in, stop swarm join), then it'll stick around until the TTL expires - which is not a huge deal.
