### ISSUE TITLE
Proposal: Improved Node Management

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#1486]
When Swarm fails to connect to a node for the first time, it gives up and never retries.

This was designed to avoid continuously retrying to connect to invalid nodes.

This causes multiple problems (#1185 #1331) such as:
- If the manager is started before a node then it will never see the node
- It's very hard to debug for the user

## Proposal

To fix those problems we could redesign the way Swarm does node management.

This is a possible approach I think we could explore:

- **Always**  add discovered nodes to the cluster

- Do not attempt to synchronously connect to *engines* from *discovery* at all (this will make the discovery code much simpler since we won't need the goroutine anymore)

- Let the Engine *refresh loop*, which currently handles retrying on failure, handle initial connection as well. This means that if an engine is not reachable at start, the refresh loop will try to reconnect after a random delay within range.

- Make sure the rest of the code base can handle unhealthy nodes. Until we make first connection, we do not know the `ID` of the Engine which will be a problem since we index Engines by ID.

- Perhaps we could do something more fancy than the random delay retry such as exponential back-off.

### Reporting

Debugging node registration issues is really difficult for users and requires fiddling with logs. A proposal was already made (#1136) and I think it could be built on top of the improved node management.

Since we'd have a list of **all** nodes (even if we failed to connect to them), we could report all of them in `docker info`, along with their status and error message if any:

```
$ docker info
Nodes: 1
 dev: 10.0.0.123:4242
  └ Status: Down
  └ Error: 10.0.0.123: No route to host
```

This could include extra information such as:
- Last seen (last successful heartbeat)
- Number of retries
- Scheduled next retry

Reporting must also take care of **duplicate IDs**: the problem confuses users very often (#1467). At the very least we should report it in `docker info`.

### Existing Attempts

There have been a couple of attempts to fix this issue (#1044 #1195), however both approaches try to solve the problem at the discovery level rather than the engine level.

The downsides are:
- It duplicates the reconnection problem in both engine and discovery. For instance, now that `Engine` retries to reconnect at a random interval we would have to reimplement that for discovery as well
- It makes the discovery code path more complicated. It's already a beast. If we implement this proposal however, we would actually make it simpler since we don't need to connect to engines in goroutines anymore
- It doesn't provide a way to report the status to the user, since the `Cluster` is not aware of those nodes.

/cc @docker/swarm-maintainers @MHBauer @lokikiller @ahmetalpbalkan @riuvshin

**Comment by lokikiller** [comment]
Treat it as an unhealthy node maybe a good idea~

**Comment by dongluochen** [comment]
Great proposal! We may extend Node Management to cover node removal #1341, node maintenance #1230, etc. I think a node's life cycle can be modeled by a state machine. Corresponding actions can be triggered based on state, event and timer. It'd require persistent storage to store node states which is not available today.

**Comment by jimmyxian** [comment]
Cool! Totally agreed
I have tried to implement `Expose un-healthy nodes in info` and meet the same problem(When Swarm fails to connect to a node for the first time, it gives up and never retries. Then we can not get the un-health info of this node).
Should always add discovered nodes to the cluster and reconnect at engine level, so that we can expose un-healthy nodes in `docker info`. :+1:

**Comment by ahmetalpbalkan** [comment]
Great proposal, sounds good to me. Unhealthy node addresses definitely should be listed on /info and extra info such as last heartbeat, connection error, next retry would be useful as well. I'm not sure “number of retries” is going to be relevant.

**Comment by MHBauer** [comment]
Agree with concept. Agree with suggestion of state machine for managing node condition. Agree that unhealthy nodes should be kept aware of. I can see the details of implementing this will be considerable.

**Comment by dongluochen** [comment]
Here is an initial plan on node management. Feedbacks are welcome.

A 'maintenance' state is added for node upgrade/maintenance/node remove. We may add commands for node management like set node to 'maintenance' state. A node in maintenance will not be selected to run container unless constraint is 'node==#thisnode#'. This state is used to do maintenance/debug work, or to put it in inactive state to drain/migrate running containers, collect data before deleting it. 

```
    add node
      |     
      |    
      v                              
+-----------+    refresh            +-----------+      
|           |+--------------------->|           |      
| unhealthy |                       |  healthy  |      
|           |<---------------------+|           |      
+-----------+  connection failure   +-----------+      
    ^    |                                   |         
    |    |                                   | 
    |    | maintain                 maintain | 
    |    |           +-------------+         |         
    |    +---------->|             |         |         
    |                | maintenance |<--------+         
    +---------------+|             |                  
maintenance done     +-------------+                  
                            +
                            |
                            |
                            v
                      remove node
```

Several attributes will be added for node state. Next refresh time is calculated from current state and number of failed retries. A node fails recently can be probed frequently so it can recover fast (for example, VM reboot case). Retry interval takes a back-off  strategy to reduce resource waste until it reaches a limit like 8 hours. (User can jumpstart it, maybe thru moving it in and out of maintenance state.)  
- Last seen (last successful heartbeat)
- Last error
- Number of failed retries
- Next refresh time 

A node may have 2 indexes, one is IP address, the other is ID. When a node is added to swarm, only IP index is created and the node is set to unhealthy state. When refresh loop reaches the node, it retrieves its ID and add the second index. Removing a node will remove both indexes. 

If a node joins with a different IP, there are 2 cases. The first case is same node comes back with a different IP (DHCP renew). The second case is conflict ID from VM clone. Swarm should detect this issue, update IP, and issue a warning.

**Comment by abronan** [comment]
@dongluochen Do you think we can close this one or should we should keep it open because of the maintenance state?

**Comment by dongluochen** [comment]
Thanks @abronan. I'd like to keep it for the maintenance state. I think we may come to it soon.

**Comment by dongluochen** [comment]
The majority of this proposal is completed. State `maintenance` will be added later when we have swarm API that can control nodes.

**Comment by ghostsquad** [comment]
how do you remove a node from a swarm? (as part of testing and development of node management automation)

**Comment by abronan** [comment]
Hi @ghostsquad, If using Consul, etcd or zookeeper for the node discovery: just stop the docker daemon on the node you want to remove and the node will be left out immediately of any scheduling decisions and removed from the list on `info` after some time (after `discoveryTTL` value expires). I admit that this is kind of hard for automation if you want an imperative way to remove and confirm the removal.

Alternatively, you can take a look at [swarmkit](https://github.com/docker/swarmkit) and [docker swarm mode](https://docs.docker.com/engine/swarm/) (docker engine 1.12 RC3) which are including node management and are allowing you to add and remove nodes explicitly which is much easier for automation. Hope this helps!

**Comment by ghostsquad** [comment]
@abronan awesome. I'll upgrade and try it out.

**Comment by jeffbaier** [comment]
Where does swarmkit fit in? Is swarm being replaced by swarmkit or do they fit different niches?
