### ISSUE TITLE
swarm with secure consul (TLS+ACL)

### ISSUE THREAD

**Issue by gdiazlo** [docker/swarm#1487]
Hello

Using the latest swarm docker image, as per documentation:

    $ docker images
    REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
    swarm               latest              6b40fe7724bd        4 weeks ago         15.6 MB

Swarm join can't use consul with TLS.  without TLS works as expected:

    docker create --name swarm-agent swarm join \ 
    --addr=swarm1:2376 \
     consul://swarm:8500/swarm

I expected that something like this would work:

    docker create -v /home/pki/:/tmp/pki --name swarm-agent swarm join --tlsverify \
     --tlscacert=/tmp/pki/swarmca.pem \
     --tlscert=/tmp/pki/swarm-cert.pem \
     --tlskey=/tmp/pki/swarm-key.pem \ 
    --addr=swarm:2376 \
    consul://swarm:8501/swarm

given that consul uses the very same certificate, generated with  clientAuth and serverAuth enabled, but there is no tls options in join command, while there are in manage command, to communicate with docker, but not with consul.

Communication between docker and swarm using TLS works as expected.

Also, i cannot specify a consul token so docker only have access to its own tree in the consul key/value store.

The same happens with docker daemon and its --cluster-store parameter

    $  docker version
    Client:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   a34a1d5
     Built:        Fri Nov 20 13:25:01 UTC 2015
     OS/Arch:      linux/amd64

    Server:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   a34a1d5
     Built:        Fri Nov 20 13:25:01 UTC 2015
     OS/Arch:      linux/amd64
 
regards,
gabi

**Comment by abronan** [comment]
Hi @gdiazlo,

You must use `--discovery-opt kv.cacertfile=mycacert.pem --discovery-opt kv.certfile=mycert.pem --discovery-opt kv.keyfile=mykey.pem` flags that are specific to the discovery for setting up TLS.

ACL is making its way through #1434.

This is cumbersome for now (if the same certs than swarm you still have to point using the same files to setup TLS for the discovery) and not well documented, tagging as docs. Thanks for the report!

**Comment by gdiazlo** [comment]
Gooood! thanks a lot for pointing this out.

**Comment by abronan** [comment]
Closed by #1510
