### ISSUE TITLE
Performance issues with mesos - due to Global lock in Mesos scheduleTask() ?

### ISSUE THREAD

**Issue by ezrasilvera** [docker/swarm#1495]
When using native Swarm cluster we can increase the create_container bandwidth (how many containers/sec the cluster can handle) by adding more engines.
However when using Mesos cluster no matter how many concurrent requests we use the bandwidth when using N engines is the same as using a single engine which mean such cluster can't scale at all !!

I believe the issue is coming from the global lock on scheduleTask(). For some reason it seems as if incoming tasks are waiting on this lock until previous task is completed/in RUNNING state ...

func (c *Cluster) scheduleTask(t *task) bool {
	c.scheduler.Lock()
	defer c.scheduler.Unlock()

To reproduce - just use a cluster of N engines and sent N create() or run() requests in parallel . The N requests will be completed as if there is only single engine.

**Comment by ezrasilvera** [comment]
I think the problem is coming from  "finished, data, err := t.monitor()"  which waits till change in status sent by Mesos.

**Comment by ezrasilvera** [comment]
I have changed the scheduler lock and this indeed solve the issue. Hopefully it's not causing other issues. 
You can see in the graph bellow that now multiple concurrent requests can be handled
![throughput_graph_mesos](https://cloud.githubusercontent.com/assets/13567561/11874203/2c8a7f2e-a4e7-11e5-9fcf-0edd30db401c.png)

**Comment by abronan** [comment]
ping @vieux @jimenez

**Comment by jimenez** [comment]
closed by https://github.com/docker/swarm/pull/1554
