### ISSUE TITLE
Discovery documentation: some links not working 

### ISSUE THREAD

**Issue by full-of-foo** [docker/swarm#1502]
Not a big deal at all, but some of the links on the swarm/discovery Readme are no longer working.
```
$ curl https://github.com/docker/swarm/blob/master/discovery/API.md
{"error":"Not Found"}
```

The four links involved are here: https://github.com/docker/swarm/blob/f78c8054b7d660b2467063cb9ec42bce74f057de/discovery/README.md#docker-swarm-documentation-index

**Comment by thaJeztah** [comment]
Created a pull request to fix them, thanks!
