### ISSUE TITLE
swarm create fails with "remaining connection slots are reserved..."

### ISSUE THREAD

**Issue by ahaurw01** [docker/swarm#1503]
Following the beginner's docs for OSX:

```sh
# Terminal started via Docker Quickstart Terminal app.
$ docker-machine create -d virtualbox local
$ eval "$(docker-machine env local)"
$ docker run swarm create
```

Results in `pq: remaining connection slots are reserved for non-replication superuser connections`.

```sh
$ docker --version
# Docker version 1.9.1, build a34a1d5
$ docker run swarm --version
# swarm version 1.0.0 (087e245)

# Virtualbox version 5.0.10 r104061
# OSX 10.11.1 (15B42)
```

Any ideas what I'm doing wrong or how the docs need to be updated?

**Comment by ChristSent** [comment]
Same issue here with Ubuntu 14.04 LTS. This was totally working for me the night before last. Using whatever version of docker is available in the Ubuntu's default repos. Can provide more detail if need be.

**Comment by AlexOugh** [comment]
I also had "pq: sorry, too many clients already" error. After restarting docker, now I have the same error, "pq: remaining connection slots are reserved for non-replication superuser connections"

**Comment by stewartpark** [comment]
I'm having this error, too. I think node discovery with a token ID can be faulty in cases like this. Having a private discovery system should be strongly recommended. i.e. consul, etc. My nodes are all missing now and I have no means to access containers at the moment other than accessing each docker swarm host.

**Comment by remonlam** [comment]
If you're using Docker Swarm Discovery, it's down since Friday check http://status.docker.com
also check issue https://github.com/docker/swarm/issues/1482 it's recommended to use a private discovery tool.

**Comment by rhinoceros** [comment]
I have the same problem.
root@xxxx:~# docker run --rm swarm create
pq: sorry, too many clients already

root@xxxx:~# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
root@xxxx:~# docker run --rm swarm -v
swarm version 1.0.0 (087e245)

root@xxxx:~# cat /etc/issue
Ubuntu 14.04 LTS \n \l

**Comment by cpuguy83** [comment]
It looks like this is because the hosted discovery service is having issues.
Please try with either a static node list or with a supporter k/v store (etcd, zk, consul).

**Comment by ahaurw01** [comment]
I created a PR to add a documentation note with this advice. Thanks all for chiming in. I haven't yet tried setting up an alternate backend. I'll try to confirm that this works.

**Comment by amitshukla** [comment]
Thanks @ahaurw01 - closing this question
