### ISSUE TITLE
Docker events using since not functioning as expected

### ISSUE THREAD

**Issue by doronl** [docker/swarm#1504]
Docker events using since not functioning as expected, I expected to get events since the given time but I get only new events (that occurred after the command execution) in most cases

I tested both Swarm and working directly with the Engine via CLI or remote API, I am using v1.8.

Cases:

Docker Engine via CLI
Command: docker events --since '1449411846' 
Result: Got events as expected since the given time.

Docker Engine via Remote API: 
Command: wget http://MyDockerEngineIP:2375/events?since=1449411846
Result: No older events, just new ones.

Docker Swarm via CLI: 
Command: docker -H tcp://MySwarmManagerIP:8333 events --since '1449411846'
Result: No older events, just new ones.

Docker Swarm via Remote API: 
Command: wget http://MySwarmManagerIP:8333/events?since=1449411846
Result: No older events, just new ones.

am I doing anything wrong?

Thanks,
 Doron

**Comment by dongluochen** [comment]
@doronl Docker CLI and Remote API (case 1 & 2) should be correct. In your case 2 `Docker Engine via Remote API`, if you add `-qO-` to your wget command, like `wget -qO- http://MyDockerEngineIP:2375/events?since=1449411846`, you should see the history events. 

For swarm events, adding support for `--since` is under investigation. See #1203.

**Comment by doronl** [comment]
Thanks @dongluochen 

1. I will rellate to #1203... 
2. Adding -qO- didnt fix the issue... before adding it I had echo:
--2015-12-08 21:19:57--  http://MyDockerEngineIP:2375/events?since=1449411846
Connecting to MyDockerEngineIP:2375... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘events?since=1449411846.3’

    [<=>                                                                                              ] 0           --.-K/s

and the output file was empty.... with the flag I dont get any echo or output file... any thoughts?

**Comment by dongluochen** [comment]
@doronl `wget -qO-` redirects output to STDOUT so you don't see saved file. Can you show the output from the follow 3 commands towards a docker agent? They should get same result. Make sure the docker TCP port is correct.   
```
docker events --since '1449411846' 
docker -H MyDockerEngineIP:2375 events --since '1449411846' 
wget -qO- http://MyDockerEngineIP:2375/events?since=1449411846
```

**Comment by vieux** [comment]
Can you please follow up in #1203 this one is a duplicate.
