### ISSUE TITLE
Unable to configure `swarm manage -H unix://` socket group permissions

### ISSUE THREAD

**Issue by SpComb** [docker/swarm#1507]
I would like to run the swarm manager as a system daemon with access controlled via an unix group (matching the default setup for docker: `/var/run/docker.sock` is `chown root:docker` `chmod 0660`).

`swarm manage --host=unix:///run/swarm/swarm.sock` works, but the permissions on the socket are hardcoded in the code (https://github.com/docker/swarm/blob/master/api/server_unix.go#L30):

	// only usable by the user who started swarm
	if err := os.Chmod(addr, 0600); err != nil {
		return nil, err
	}

I currently hack around this with something like the following systemd service unit, which is certainly not ideal (the swarm user has swarm as its primary group, so it ends up with the desired permissions):

	[Service]
	User=swarm
	RuntimeDirectory=swarm
	ExecStart=/opt/.../swarm manage \
	    --host=unix:///run/swarm/swarm.sock \
	    ...
	ExecStartPost=/bin/sleep 2
	ExecStartPost=/bin/chmod g+rw /run/swarm/swarm.sock

Docker has a `docker daemon --group=docker` flag; should `swarm manage` have something similar?

Systemd socket activation support (`docker daemon -H fd://`) would also be nice, since it would take care of this same issue even more cleanly :)

**Comment by dongluochen** [comment]
@SpComb I think swarm doesn't implement full support for unix group because this is not its major usage scenario. In production environment swarm manager have replica for high availability. Using unix group is inconvenient as master can change. This is different from single box docker. IMHO adding TLS for access control is more appropriate.

**Comment by dongluochen** [comment]
@SpComb I'll close this issue. Feel free to add comments.
