### ISSUE TITLE
How to configure a docker with credentials

### ISSUE THREAD

**Issue by bluishpe** [docker/swarm#1511]
Hello,
      Do you know how to configure docker with credentials? Please note its not SSL, it should be accessible using username and password.

Regards
Baltazar Luis

**Comment by bluishpe** [comment]
any help?

**Comment by nishanttotla** [comment]
@bluishpe We support authentication using TLS, as mentioned here: https://docs.docker.com/engine/articles/https/

Username/password isn't supported, also since it would have to be done in Docker Engine. You can try creating an issue there.

**Comment by amitshukla** [comment]
@bluishpe please reopen if you have further questions
