### ISSUE TITLE
swarm never tries to reconnect when it gets a dial tcp i/o timeout error

### ISSUE THREAD

**Issue by ekristen** [docker/swarm#1527]
It appears that if a swarm master gets a `dial tcp 10.10.xxx.xxx:2376: i/o timeout` it never attempts to reconnect.

**Comment by ekristen** [comment]
You have to restart the swarm master to get it to try again, I believe it should retry automatically with a backoff.

**Comment by dongluochen** [comment]
@ekristen Thanks for reporting issue. It's a duplicate of #1185. Work item #1486 plans to fix this issue.
