### ISSUE TITLE
Leader Election Recovery with Consul fails sometimes

### ISSUE THREAD

**Issue by abronan** [docker/swarm#1545]
There are cases where the Swarm Leader Election process cannot recover from the store failure using Consul.

It does not affect *etcd* and *zookeeper* though.

As the leader election process relies on a Distributed Lock and Watch events, this might be related to #1413 (race and missed event on new leader key which would prevent the switch from replica to primary role).

Primary sees itself as the Leader with its own IP, it's just the switch from the Replica role back to Primary/leader that does not happen (related to the **candidate** goroutine).

**Comment by fugr** [comment]
go func () {
for {
// By consul / etcd / zookeeper distributed locking mechanism, swarm manage set be primary when acquired the locker, and set the server Handlers to primary.
// When the lock failure (TTL) re-election (and possibly other swarm manage to obtain the lock).
// When the swarm manage to replica role, the server's replica set Handlers

run (candidate, server, primary, replica)


time.Sleep (defaultRecoverTime)
// Note: swarm manage when primary and will not unlock the lock, under circumstances still valid session, still holding the lock,
// While others swarm manage's Locker or NewLocker be unsuccessful, and the original primary is set to replica.
// This resulted is no primary, but the watcher saw  the original primary's IP, until the original session of TTL failure will release the lock。
}
} ()

so,it is indeed to unlock before swarm manage re-election.

**Comment by abronan** [comment]
I managed to narrow down the issue on the `Lock` implementation on libkv's side (which is basically only calling Consul's implementation of Lock).

The issue lies in using a `Lock` with a custom Session (forcing `--replication-ttl "0s"` to escape the Lock TTL code path does not lead to this issue).

Scenario is:
- Everyone is a candidate and a follower
- One node is elected
- Everyone is notified of the new Leader
- Store goes down
- Everyone's Lock exits (Leader with `Lock already Held` and others with `getsockopt error`)
- Everyone retries to be a candidate and a follower
- Everyone stays locked in the candidate state (Wait case in the `Lock`) even though this should fail and trigger the retry loop because the store is down.
- The retry loop to follow the leader is still active but the candidate loop is stuck

What's mind boggling is that this issue seems to be due to the fact we're using a custom session for the Lock. Everything works fine with the default session. No luck in cleaning the session at lock failure either. Still investigating but I suspect a blocked channel or stuck retry loop on the Lock due to some check on the Session.
