### ISSUE TITLE
Proposal: Refactor HTTP client used by swarm

### ISSUE THREAD

**Issue by dongluochen** [docker/swarm#1549]
Swarm manager has 3 different ways to send a request to a node, dockerclient, httpclient, and `proxy` mode thru httpclient (see cluster/engine.go and api/handlers.go). The connection between swarm manger and node is important for functionality as well as performance. It's hard to maintain or improve 3 connection methods. For example, if we want to change TCP settings for client it'll be in different places. PR #1517 has difficulty to monitor connection failure from swarm manager to node. We want to merge the clients to one, and implement connection setting/monitoring in this data structure.

This can be associated with improvement on node management #1486.

**Comment by nishanttotla** [comment]
@dongluochen did you make progress on this?

**Comment by dongluochen** [comment]
@nishanttotla I haven't got time to work on it yet.
