### ISSUE TITLE
go get github.com/docker/swarm is not working

### ISSUE THREAD

**Issue by jmccormick2001** [docker/swarm#1550]
I get the following error when doing a build today of swarm:

tater jeffmc~/swarmproject]: go get github.com/docker/swarm
package github.com/docker/swarm
	imports github.com/Sirupsen/logrus
	imports github.com/codegangsta/cli
	imports github.com/docker/docker/pkg/ioutils
	imports golang.org/x/net/context
	imports github.com/docker/docker/pkg/parsers
	imports github.com/docker/docker/pkg/parsers/filters
	imports github.com/docker/docker/pkg/parsers/filters
	imports github.com/docker/docker/pkg/parsers/filters: cannot find package "github.com/docker/docker/pkg/parsers/filters" in any of:
	/usr/lib/golang/src/github.com/docker/docker/pkg/parsers/filters (from $GOROOT)
	/home/jeffmc/swarmproject/src/github.com/docker/docker/pkg/parsers/filters (from $GOPATH)

my environment is centos 7.2.1511, docker Version:      1.8.2-el7.centos

**Comment by jmccormick2001** [comment]
I also get this error when I try to build with v1.0.1:

tater jeffmc~/swarmproject/src/github.com/docker/swarm]: git checkout v1.0.1
Note: checking out 'v1.0.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 744e3a3... Merge pull request #1522 from dongluochen/bump-1.0.1
tater jeffmc~/swarmproject/src/github.com/docker/swarm]: godep go install
# github.com/docker/swarm/api
api/primary.go:108: undefined: "net/http/pprof".Trace
godep: go exit status 2

**Comment by jmccormick2001** [comment]
it builds if I switch to the v1.0.0 branch

**Comment by dongluochen** [comment]
@jmccormick2001 Could be a go version issue. See https://github.com/revel/revel/issues/937. Please check.

**Comment by jmccormick2001** [comment]
I'm using the stock centos 7.2 version
of golang

go version go1.4.2 linux/amd64

**Comment by dongluochen** [comment]
@jmccormick2001 `Trace` is added to Golang net/http/pprof in 1.5.2. See https://github.com/golang/go/commit/690db9c89fef427f44a921250421dd2d5fa1a03f.

**Comment by vieux** [comment]
@jmccormick2001, 2 things: 

1) swarm is using godep to manage dependencies, so you will have to clone the repository and do a godep go build to compile swarm.

2) swarm 1.0.1 requires go1.5+

**Comment by jmccormick2001** [comment]
ah, thanks!  I was unaware of the golang version requirement.

**Comment by MHBauer** [comment]
We do need to list the 1.5.2 hard requirement now that we have the pprof trace. I'll make a PR to start this where I see it.

**Comment by poliveira89** [comment]
Even with version go1.5.2 this still happens on Ubuntu 14.04.

```bash
$ printenv
...
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin
GOPATH=/home/user/work
...
# $GOROOT not set

$ go version
go version go1.5.2 linux/amd64


$ go get -u github.com/docker/swarm
package github.com/docker/docker/api/types/filters: cannot find package "github.com/docker/docker/api/types/filters" in any of:
	/usr/local/go/src/github.com/docker/docker/api/types/filters (from $GOROOT)
	/home/user/work/src/github.com/docker/docker/api/types/filters (from $GOPATH)
```

I have installed go following the Digital Ocean guide: [How To Install Go 1.5.1 on Ubuntu 14.04](https://www.digitalocean.com/community/tutorials/how-to-install-go-1-5-1-on-ubuntu-14-04)

**Comment by vieux** [comment]
@poliveira89 docker/docker kept moving it's code around (for example github.com/docker/docker/api/types/filters was moved to github.com/docker/engine-api/types)

This PR: https://github.com/docker/swarm/pull/1601 update the dependencies to the newest version so after it's merge you will be able to go get.

In the meantime you can probably do:

```
go get -d github.com/docker/swarm
go get github.com/tools/godep
cd <where_swarm_is>
godep go install
```

**Comment by mattgiles** [comment]
`go get -d github.com/docker/swarm` also fails with:

```
package github.com/docker/docker/api/types/filters: cannot find package "github.com/docker/docker/api/types/filters" in any of:
	/usr/local/go/src/github.com/docker/docker/api/types/filters (from $GOROOT)
	/usr/local/src/github.com/docker/docker/api/types/filters (from $GOPATH)
```

**Comment by ryzasss** [comment]
Vieux > worked fine for me

**Comment by poliveira89** [comment]
@vieux and @mattgiles I have installed manually like explained on `README.md`:

```bash
$ mkdir -p $GOPATH/src/github.com/docker/
$ cd $GOPATH/src/github.com/docker/
$ git clone https://github.com/docker/swarm
$ cd swarm
$ $GOPATH/bin/godep go install .
```

As we can see next, installed successfully:
```bash
$ go list
github.com/docker/swarm

$ $GOPATH/bin/swarm --version
swarm version 1.0.1 (HEAD)
```

@vieux , about what you told, if it's that the case, that they are changing the code. IMO, that's somehow normal or at least understandable. Only looks strange for not seeing that warning anywhere even on this issue (until you mention it). Let's wait if some contributor read you comment and update the `README.md` or maybe it's best someone submit a PR for that part of the documentation.

**Comment by vieux** [comment]
@poliveira89 I agree, we try to do our best to keep our dependencies up to date but things like this can happen.

That's why we recommend to use the docker image we package.

You should know that when you `go get` a project, you will end up with the current master branch.
Although our policy is the have master working at all time, it's not considered `stable`, only our releases are: https://github.com/docker/swarm/releases

**Comment by poliveira89** [comment]
@vieux not understand me wrong, I was not demand or point fingers at anyone, it was not my intention.
I was just stating that this problem appeared sometimes, but without the insight you gave.
Regarding the releases topics, I understand why you do that. For me it was not "working" thought that with this installation could get a better understanding on Swarm.
And for "keep up dependencies" I just "got into" Go now... and read about it.
To finish, thanks for the time you took to answer my questions. :+1:
