### ISSUE TITLE
docker-compose 'up' does not work compared to 'start'

### ISSUE THREAD

**Issue by mrapczynski** [docker/swarm#1567]
Starting a Compose application with Swarm constraints using the 'up' command to take advantage of container auto re-creation does not work. However, using the 'start' command works fine.

```
[docker@dockertest2 Compose]$ docker-compose -f docker-registry.yml up -d
Recreating 2d0a0476c3_2d0a0476c3_compose_registry_1
ERROR: unable to find a node that satisfies container==2d0a0476c34ea3458e2ee1ddbe52834c62d0aed5025f2d29fce5403d7970353d

[docker@dockertest2 Compose]$ docker-compose -f docker-registry.yml start
Starting 2d0a0476c3_2d0a0476c3_2d0a0476c3_compose_registry_1
```

*Update:* Running Compose 'up' on the Swarm primary has no added benefit. Same error output.

**Comment by dongluochen** [comment]
@mrapczynski compose `start` is to start existing containers, while `up` is trying to (re)create the container. It looks like the container is already created, so start would work while recreate fails. Can you share the yml and swarm `info` before your command? 

```
start
Starts existing containers for a service.
up
Builds, (re)creates, starts, and attaches to containers for a service.
```

**Comment by mrapczynski** [comment]
@dongluochen  OK here you go - I got a fresh example that just occurred this morning.

Output:
```
[docker@dockertest2 Compose]$ docker-compose -f atlassian-bamboo-nolb.yml up -d
Creating compose_atlassian_bamboo_nolb_1
ERROR: unable to find a node that satisfies node==dockertest2.ad.fhda.edu
```
YML:
```yaml
atlassian_bamboo_nolb:
    environment:
        - constraint:node==dockertest2.ad.fhda.edu

    hostname: bamboo

    image: dockermgmt.ad.fhda.edu:5000/atlassian-bamboo:5.9.7f

    ports:
        - 9000:8085

    restart: always

    volumes:
        - /docker/atlassian-bamboo-lb:/data
        - /var/run/docker.sock:/var/run/docker.sock
```
Docker Info:
```
[docker@dockertest2 Compose]$ docker info
Containers: 15
Images: 36
Role: replica
Primary: dockertest.ad.fhda.edu:3376
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 4
 dockermgmt.ad.fhda.edu: dockermgmt.ad.fhda.edu:2376
  └ Status: Healthy
  └ Containers: 3
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 3.888 GiB
  └ Labels: environment=management, executiondriver=native-0.2, kernelversion=3.10.0-327.3.1.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
 dockern1.ad.fhda.edu: dockern1.ad.fhda.edu:2376
  └ Status: Healthy
  └ Containers: 3
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 8.022 GiB
  └ Labels: environment=production, executiondriver=native-0.2, kernelversion=3.10.0-327.3.1.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
 dockertest2.ad.fhda.edu: dockertest2.ad.fhda.edu:2376
  └ Status: Healthy
  └ Containers: 7
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 8.022 GiB
  └ Labels: environment=test, executiondriver=native-0.2, kernelversion=3.10.0-327.3.1.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
 dockertest.ad.fhda.edu: dockertest.ad.fhda.edu:2376
  └ Status: Healthy
  └ Containers: 2
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 8.022 GiB
  └ Labels: environment=test, executiondriver=native-0.2, kernelversion=3.10.0-327.3.1.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
CPUs: 28
Total Memory: 27.95 GiB
Name: 42e8197a6f20
```

**Comment by mrapczynski** [comment]
Here's an update - I may have found my issue. I gave up trying to launch this dev container using Swarm so I logged in as `root` just so I can create my container directly on the host. I commented out the constraint, and then attempted another compose run which led to this error:

```
[root@dockertest2 Compose]# docker-compose -f atlassian-bamboo-nolb.yml up -d
Creating compose_atlassian_bamboo_nolb_1
ERROR: Cannot start container 8c2e2d837bf9701e3c2e23dc34ec463b850dde1f364cc44e809aafb728e17309: failed to create endpoint compose_atlassian_bamboo_nolb_1 on network bridge: Bind for 0.0.0.0:9000 failed: port is already allocated
```

Duh! I was trying to use a port already in use. So I altered my YAML file with a different port, and then I thought OK I'll try Swarm one more time. And bingo! That was it.

So my original issue about the error message of about node not found is actually misleading. Is it possible to have Swarm report more meaningful error messages when failing to deploy? In my particular example, I think it would be useful if Swarm could tell me that I'm being thick headed and need to change my port for the constraint to work.

**Comment by dongluochen** [comment]
@mrapczynski Thanks for the update! The problem of returning more meaningful message has some difficulty because each node has its specific reason why it cannot create the container. Putting all these messages together may be overwhelming for a big cluster. User can try to run the container on each machine like what you did. You don't need to log in each host to do that. You can use DOCKER_HOST env variable. 
```
$ export DOCKER_HOST=tcp://1.2.3.4:5678
$ docker-compose up 
```

**Comment by dongluochen** [comment]
@mrapczynski Any comment on this issue?

**Comment by mrapczynski** [comment]
@dongluochen Sorry for the long delay! I ended out of the office ill unexpectedly last week.

There is one other kind of error message that I get, but it is hard to reproduce. Often something like 'Cannot find host suitable for container == ......' - that seems to only occur when performing a Compose operation such as `'up` on a service where the container(s) already exist.

Any idea what might cause that or if it is related? I had an example from my shell last week but forgot to save it amidst other work going on.

**Comment by dongluochen** [comment]
@mrapczynski I do not get enough info to reproduce your problem. You may do some search on [docker-compose](https://github.com/docker/compose). If we do not get extra info, I may close this issue.

**Comment by mrapczynski** [comment]
@dongluochen Thank you for the reminder. You know what the issue for now seems to mitigated for us. Not fixed per se, but just worked around.

In our CI, I have the build script run:

```
docker-compose -f ... stop
docker-compose -f ... rm
docker-compose -f ... up -d
```

All has been well since then. It could very well be that Swarm 1.1 will get rid of any underlying issues. I'll close this request. Thank you for your assistance in the past weeks.

**Comment by dongluochen** [comment]
Thanks @mrapczynski . Feel free to reopen if you have reproduce.

**Comment by navinSing** [comment]
Getting similar issue : 
 ```
docker info
Containers: 215
 Running: 4
 Paused: 0
 Stopped: 211
Images: 49
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 4
 vva: 192.168.1.37:2376
  └ Status: Healthy
  └ Containers: 28
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 3.534 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-25-generic, machine.env=prod, machine.name=v37, machine.storage=disk, machine.type=s, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-02-09T16:15:33Z
 vvd: 192.168.1.36:2376
  └ Status: Healthy
  └ Containers: 27
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 3.534 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-25-generic, machine.env=prod, machine.name=v36, machine.storage=disk, machine.type=s, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-02-09T16:15:13Z

... 

```




snippet from compose 
```
czabc:
 image: aa:3.0
 ports:
   - 2015:2015
 command: " --ne e"
 environment:
   -  "constraint:machine.name==v37"


```


ERROR:
```
docker-compose -f docker-compose-core.yml up -d
Recreating 414fee4571_uj_czabc_1
ERROR: unable to find a node that satisfies machine.name==v37
```

**Comment by dongluochen** [comment]
@mrapczynski I think node affinity should be `"constraint:node==v37"` where `v37` is the node name shown in swarm info, like `vva`.

**Comment by mrapczynski** [comment]
@dongluochen Sorry wasn't me. Tagging @navinSing as he added to the comment above.

**Comment by dongluochen** [comment]
@mrapczynski My mistake here.

**Comment by nanounanue** [comment]
I am having the same problem.

And I believe it has to do with the fact that I recreate (`docker-compose build`) the container. 

Any solution?

**Comment by bvandewalle** [comment]
I have the same issue.
It seems it only occurs when docker-compose needs to build one of the images.

```
[...]
Step 4 : EXPOSE 8888
 ---> Running in 400116772b63
 ---> 095ce3f54d03
Removing intermediate container 400116772b63
Successfully built 095ce3f54d03
Creating myapp_web_1
ERROR: unable to find a node that satisfies image==yewno_web
```
