### ISSUE TITLE
'swarm create' fails with "getsockopt: no route to host"

### ISSUE THREAD

**Issue by ssuvasanth** [docker/swarm#1570]
######################
$ docker run swarm create
2015/12/30 23:12:18 Post https://discovery.hub.docker.com/v1/clusters: dial tcp 54.175.197.208:443: getsockopt: no route to host
######################

-- My system have access to internet through a proxy.
-- wget in the docker host is able to access the internet
-- docker daemon is able to access the internet and pull images

Is it that swarm running inside the docker do not have proxy settings and that it couldn't access the internet?

**Comment by abronan** [comment]
Hi @ssuvasanth,

Yes, if running Swarm in a container you need to configure docker to use your proxy settings. See the following link: https://docs.docker.com/engine/articles/systemd/#http-proxy

Otherwise just use the binary directly for `swarm create`/`swarm join`/`swarm manage`.

**Comment by ssuvasanth** [comment]
Hello @abronan ,

I have already configured proxy for docker and images are pulled from registry without an issue.
The only failing command is 'swarm create' inside docker.

Other swarm commands run without an issue:
#####################################
$ docker run --rm swarm --version
swarm version 1.0.1 (744e3a3)
#####################################

Could you please tell me why does 'swarm create' access https://discovery.hub.docker.com/v1/clusters ? 

When I try to access "https://discovery.hub.docker.com/v1/clusters" directly, it gives me a 404 error (Page not found).

Thank you,
Vasanth

**Comment by abronan** [comment]
@ssuvasanth Not really sure, a `curl -X POST https://discovery.hub.docker.com/v1/clusters` works fine on my end and returns the token as expected.

Would really bet something is wrong with your proxy settings that makes the URL inaccessible from inside the container. Do you have the same problem if you use the binary directly?

**Comment by ssuvasanth** [comment]
@abronan , swarm binary runs without an issue with the proxy set for the docker host machine.

######################
# /gopath/bin/swarm create
1f8bfdb28a5b111e49e211b66df9945a
######################

So, it looks like the container is not taking the proxy setting from docker daemon.
I am wondering if I could get a shell to swarm container and set proxies.

I think swarm image should have feature to set proxy.

++ Is there any other way to get token than accessing https://discovery.hub.docker.com/v1/clusters? 
What runs at https://discovery.hub.docker.com/v1/clusters? Can I host it internally (something similar to internal registry)?

**Comment by ssuvasanth** [comment]
I want to emphasize again that only "swarm create" fails when run inside the container. 

swarm manage succeeds.
#####################
$ docker run -d -P swarm manage token://cb64ebe93bf1d66212b6b5b91f1032eb
45d4c02616fd1d5c89307c65f36f2e1ee5e7a3c9a3200f46f45107c71b13552c
#####################

**Comment by ssuvasanth** [comment]
@abronan I understand that the hosted discover provided by docker is for testing and development purpose, but I really want to request passing proxy settings to swarm container / swarm container inheriting proxy from docker daemon as an enhancement. That would make our swarm image contain more features to support more setups.

**Comment by ssuvasanth** [comment]
Hello,

I was not aware that we can pass environment variables to docker-run.(Sorry I am new to docker).

swarm create with docker hosted discovery was successful when passed https_proxy to docker-run:

$ docker run --rm -e "https_proxy=<proxy>" swarm create
xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Thank you,
Vasanth
