### ISSUE TITLE
Overlay network problem when swarm nodes have non-unique hostnames

### ISSUE THREAD

**Issue by mgoelzer** [docker/swarm#1573]
Summary:  I have a Swarm cluster with a master and two nodes.  All three hosts have the same hostname "vagrant-ubuntu-trusty-64".  I cannot ping one container's overlay IP from a container running on the other node.  However, if I manually give each node and the master unique hostnames, then the overlay networking will work normally.

Is this the intended behavior?

---

Here's a concrete example.  Master is at 192.168.33.11:3375.  I start and nginx container and a /bin/sh container and shown below:

```
$ docker -H=tcp://192.168.33.11:3375 run -d --name web --net myStack1 nginx
7bef07de1ba1fb403b1f469face7867f57e07b300d81c855fc8abe099c25555e
$ docker -H=tcp://192.168.33.11:3375 run -itd --name shell1 --net myStack1 alpine /bin/sh
536cbea76ad18a56a8d1f7b25437c26f915792d7e7025102a684d649111d6014
$ docker -H=tcp://192.168.33.11:3375 ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
276979ed81a3        alpine              "/bin/sh"                11 seconds ago      Up 10 seconds                           vagrant-ubuntu-trusty-64/shell1
4b32eba5d660        nginx               "nginx -g 'daemon off"   17 seconds ago      Up 16 seconds       80/tcp, 443/tcp     vagrant-ubuntu-trusty-64/web
```

(By sshing into each node and doing a local `docker ps`, I can tell that nginx is running on one node and /bin/sh container on the other node.)

Now I attach to the shell container (10.0.0.3) and try to ping the web container's IP (10.0.0.2):

```
$ docker -H=tcp://192.168.33.11:3375 attach shell1

/ # ping web
PING web (10.0.0.2): 56 data bytes
[...wait a minute seconds here...]
^C
--- web ping statistics ---
12 packets transmitted, 0 packets received, 100% packet loss
```

Other network communication like curl, nc and traceroute also fail.  However, networking is fine if the same procedure as above is followed but with master and the two nodes all having unique hostnames.

**Comment by dongluochen** [comment]
This looks like a routing problem. /cc @sanimej .

**Comment by dongluochen** [comment]
Confirmed with Santhosh that server name needs to be unique in libnetwork. libnetwork uses Serf in underlayer where hostname is used to identify a node.

**Comment by mgoelzer** [comment]
@dongluochen Thanks for investigating.  I'm going to close this issue and open one on libnetwork instead.

**Comment by dongluochen** [comment]
Just
