### ISSUE TITLE
Error response from daemon: client is newer than server (client API version: 1.21, server API version: 1.20)

### ISSUE THREAD

**Issue by ssuvasanth** [docker/swarm#1574]
When I try to 'docker run' an image on a docker client connected to a swarm manager, I get the below error, even though all the server and client APIs in all 2 nodes managed by swarm are at version 1.21:

     Error response from daemon: client is newer than server (client API version: 1.21, server API version: 1.20)

Docker version displays API versions as 1.21.

However, I do not get the above error when I directly 'docker run' on the nodes instead of running through swarm manager.

The error is always reproducible with swarm manager.

**Comment by ssuvasanth** [comment]
Sorry, not a bug. There was really a conflict in API versions.

**Comment by jannikweichert** [comment]
How did you resolve it @ssuvasanth? I'm struggling with the same issue on OSX. docker-machine and docker are both updated to newest versions.

**Comment by ssuvasanth** [comment]
Hello Jannik,

I had one of the docker host in the swarm run a lower version..
Please check the docker version on each of the host in swarm.
You might face this issue when you install docker-engine from docker repos
in some hosts and OS vendor provided docker-engine on few hosts.

Hope that helps..

Thank you,
Vasanth
