### ISSUE TITLE
Forward swarm replica tcp to primary

### ISSUE THREAD

**Issue by dustinblackman** [docker/swarm#1576]
I currently have a 4 server setup, all of which set to be potential masters. When connecting to a replica, currently `docker ps -a` will only give containers on the current host, instead of the entire swarm like when connected to the `primary`. 

Is there currently configuration that will forward commands from the replica to the primary so I'll always be returned information from the `primary`? Or is this something missing?

**Comment by dongluochen** [comment]
@dustinblackman In swarm high availability setup, you should use `docker -H swarm_manager:manager_port ps -a` to access a master or a replica. Be aware that on a manager, there are different ports open, one is for docker, another one for manager. If your request is sent to replica manage_port, it'll be forwarded to master.

**Comment by dustinblackman** [comment]
@dongluochen So forwarding does exist? Currently docker-machine will setup the swarm manage port on `3376`, however connecting to a replica swarm listening on 3376 only gives information about that server, and doesn't forward the configuration.

This is the command I had run when setting up an instance. Is there something I had forgotten?

```
docker-machine --debug create NEWNAME -d generic \
--generic-ip-address SERVERIP \
--generic-ssh-key KEYPATH \
--generic-ssh-user core \
--engine-label public=false \
--swarm \
--swarm-master \
--swarm-opt replication \
--swarm-discovery=etcd:/URL:PORT/swarm \
--engine-opt "cluster-store=etcd://URL:PORT/store" \
--engine-opt "cluster-advertise=eth0:2376"
```

**Comment by dongluochen** [comment]
@dustinblackman Yes forwarding is the default behavior for replica. The [high availability](https://docs.docker.com/swarm/multi-manager-setup/) doc describes the setup using swarm binary. You may check if the replica is aware of master first. Look for the line `Role` and `Primary` from `docker -H replica_IP:manager_port info` output. 
```
user@my-machine $ export DOCKER_HOST=192.168.42.201:4000 # Points to manager-2
user@my-machine $ docker info
Containers: 0
Images: 25
Storage Driver:
Role: Replica  <--------- manager-2 is a Replica
Primary: 192.168.42.200
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 3
...
```

**Comment by dustinblackman** [comment]
@dongluochen Confirmed, it shows `Role: Replica` on the replica.

**Comment by abronan** [comment]
@dustinblackman Just checking but did you use `$ eval $(docker-machine env --swarm swarm-master)` when setting up Swarm with *docker-machine* to point to the Swarm instance?

**Comment by dustinblackman** [comment]
That's the trick, that's what I don't want.

I'm currently using [jwilders nginx proxy](https://github.com/jwilder/nginx-proxy) and connecting it in to docker swarm instead of dockers `2376`. When connected to the swarm primary, everything works, routes to all the different servers depending on where the container is running. However if I reboot primary and it became a replica, this no longer works. I have to instead find which server has taken the primary and change my environment variables to point there instead.

If swarm is supposed to do forwarding, then I shouldn't have to be changing things manually if the primary gets switched to a replica..

**Comment by abronan** [comment]
@dustinblackman When you shut down the Primary and the Node comes back up as a Replica, it takes some time for the Replica to see the new Leader. Re-election needs to happen first.

I suspect this issue to be related to: docker/machine#2650 and [docker/machine#1518](https://github.com/docker/machine/issues/1518#issuecomment-164609068) which makes the cluster inconsistent after a Swarm `Primary` node restart or failure.

So my bet is that this is more of an integration issue with Machine. If you use Swarm directly and setup your cluster with the Image or the Binary, this should work just fine and the request will be proxied to the current Leader.

**Comment by nathanleclaire** [comment]
We aren't currently support replicas directly today.  Machine's model of Swarm is a bit behind the times and leaves some things to be desired.  It (naively) assumes that the original master will stay the master, and access will happen at that `hostname:port`.  We welcome proposals in the Machine repo for how you feel this should be handled in the UX or code.

**Comment by dustinblackman** [comment]
@nathanleclaire @abronan Thanks for all the help so far. Is it really something Machine is doing? After taking a look at `docker inspect` on all 4 hosts running `swarm manage`, these are the arguments it's running with. It looks pretty dead on to what the [high availability docs](https://docs.docker.com/swarm/multi-manager-setup/) mentions to do. Am I missing something?

```json
{
  "Path": "/swarm",
  "Args": [
      "manage",
      "--tlsverify",
      "--tlscacert=/etc/docker/ca.pem",
      "--tlscert=/etc/docker/server.pem",
      "--tlskey=/etc/docker/server-key.pem",
      "-H",
      "tcp://0.0.0.0:3376",
      "--strategy",
      "spread",
      "--advertise",
      "PUBLICIP:2376",
      "--replication",
      "etcd://ectd.host:2379/swarm"
    ]
}```

**Comment by MHBauer** [comment]
@dustinblackman Did you clone a vm or otherwise only install docker once before making copies of the images?

**Comment by dustinblackman** [comment]
So, I went ahead and created a new swarm by hand. Docker machine was used to start up the systems and install docker, but was not used to set up swarm, that I had done by hand. Still remains the same issue where the swarm is connected, both primary and replica's show all hosts in `docker info`, but `docker ps -a` does not show all containers when connected to the replica, only the ones running on that system.

This is command used to boot up swarm manage.

```bash
docker run \
  -v /etc/docker:/etc/docker \
  -p 3376:3376 \
  swarm manage \
  --tlsverify \
  --tlscacert=/etc/docker/ca.pem \
  --tlscert=/etc/docker/server.pem \
  --tlskey=/etc/docker/server-key.pem \
  -H tcp://0.0.0.0:3376 \
  --strategy spread
  --advertise PUBLICIP:2376 \
  --replication \
  etcd://ETCD.HOST:2379/swarm
```

**Comment by dongluochen** [comment]
@dustinblackman I think `--advertise` is not right in your setting. Your swarm managers are listening on 3376 but `--advertise` is set to port 2376. So a replica thinks the master is at <master_IP>:2376. It would forward requests to <master_IP>:2376. It might happen to be your docker port on your manager node so you see docker result, not swarm result. Can you change `--advertise` to `PUBLICIP:3376` to see if it solves your problem?

**Comment by dustinblackman** [comment]
@dongluochen That's the one buddy, great find! I got the initial configuration from [docker-machine config](https://github.com/docker/swarm/issues/1576#issuecomment-169038930) which confused me on the port. I'll throw up a PR to fix the advertising flag. Thanks again!

**Comment by MHBauer** [comment]
@dustinblackman thanks for working through it with us! I look forward to the PR!
