### ISSUE TITLE
Inconsistencies in commands between manual setup and HA setup guides

### ISSUE THREAD

**Issue by lowescott** [docker/swarm#1580]
Hi all, I recently walked through the process of establishing a multi-manager Docker Swarm cluster and noticed some inconsistencies in the Docker commands between the multi-manager setup guide (1) and the manual Swarm setup guide (2). For example, the manual setup guide uses commands like `docker run -d swarm manage...` whereas the HA setup guide just says `swarm manage...`. I'm not clear why the `docker run` part of these commands was omitted in the HA setup guide.

I'm happy to submit a PR (this will be my first time contributing) to resolve these inconsistencies, assuming these inconsistencies aren't intentional. Am I missing a reason why the commands are different (aside from the flags, of course)?

(1): https://docs.docker.com/swarm/multi-manager-setup/
(2): https://docs.docker.com/swarm/install-manual/

**Comment by abronan** [comment]
Thanks for bringing this up @lowescott.

I think we need to settle between using the Image or the binary in the docs. There was kind of a consensus around using the binary instead of the Image because it was confusing for the most part like having to mount volumes for certs, etc. (so using only `swarm manage`).

/cc @moxiegirl @mgoelzer

**Comment by lowescott** [comment]
@abronan, thanks for the clarification. I freely admit that I wasn't even aware of a binary for Swarm, only the container (perhaps the docs should be updated to clarify that as well?). A pointer to where I could get the Swarm binary would be appreciated (I only saw source code links). Thanks!

**Comment by moxiegirl** [comment]
@lowescott thanks for the feedback. This is on the docs roadmap to fix in the 1.10 release. @abronan I'm writing the scoping document this week, will ping when it is up.

**Comment by amitshukla** [comment]
@moxiegirl @rolfedh any update on whether this will make 1.10?

**Comment by moxiegirl** [comment]
@amitshukla I made a PR for this work.
