### ISSUE TITLE
Restarted mesos slaves wont make offers to swarm

### ISSUE THREAD

**Issue by Spritekin** [docker/swarm#1583]
Hi, just write down this issue.

First, I'm using CoreOS.
I have a mesos master with two nodes. All working fine.
Docker engine in the slaves. Its an essential part of CoreOS.
Mesos slaves running as containers in the slave servers.
Swarm manager in the same machine as the mesos master

All connected and working like a charm. Swarm works perfectly.

Recently I got a registration problem in mesos. I had to add a parameter to the slaves and restart the slave services. They restarted fine and mesos updated the slaves and reported the 2 nodes and its resources. All fine. 

Marathon accepted the nodes and restarted its jobs, even those in docker containers (not using swarm). The docker engine in the nodes was not restarted so all was working as usual, in fact the mesos slaves run in containers so docker in the slaves is a requisite. 

But then, swarm no longer takes the offers from the slaves. Its like by restarting the slaves the swam manager is cut from the cluster. I restarted the swarm manager service and it started accepting offers again.

I guess this is a bug.

Luck!
Guimo

**Comment by vieux** [comment]
ping @jimenez

**Comment by jimenez** [comment]
Closing this as this behavior seems to be solved with 1.1. Thanks @Spritekin !
