### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by savioursoul** [docker/swarm#1584]
After running
<code>$ go get github.com/docker/swarm</code>

I am getting the following error messages:

# github.com/samalba/dockerclient
Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:283: syntax error: unexpected range, expecting {
Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:283: missing statement after label
Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:286: syntax error: unexpected case, expecting semicolon or newline or }
Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:292: syntax error: argument to go/defer must be function call
Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:295: syntax error: unexpected }
Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:297: non-declaration statement outside function body
Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:298: syntax error: unexpected }
# github.com/mesos/mesos-go/messenger
Godeps/_workspace/src/github.com/mesos/mesos-go/messenger/http_transporter.go:51: unknown net.Dialer field 'KeepAlive' in struct literal
Godeps/_workspace/src/github.com/mesos/mesos-go/messenger/http_transporter.go:53: unknown http.Transport field 'TLSHandshakeTimeout' in struct literal
Godeps/_workspace/src/github.com/mesos/mesos-go/messenger/http_transporter.go:57: unknown http.Client field 'Timeout' in struct literal
# github.com/mesos/mesos-go/detector
Godeps/_workspace/src/github.com/mesos/mesos-go/detector/standalone.go:73: unknown http.Client field 'Timeout' in struct literal
# github.com/ugorji/go/codec
Godeps/_workspace/src/github.com/ugorji/go/codec/encode.go:533: undefined: sync.Pool
Godeps/_workspace/src/github.com/ugorji/go/codec/encode.go:1219: undefined: sync.Pool
godep: go exit status 2

Does anyone else have similar?

**Comment by savioursoul** [comment]
Looks like I am using an old version of GO (1.2), will upgrade to 1.4

**Comment by savioursoul** [comment]
Updating to Go 1.5 fixed this. Please close the issue

**Comment by MHBauer** [comment]
1.2 is definitely too old. I would like to get #1190 or similar in to update the instructions from 1.4 to 1.5.
