### ISSUE TITLE
Swarm build instructions inconsistent in README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by nishanttotla** [docker/swarm#1597]
If you check the two files https://github.com/docker/swarm/blob/master/README.md and https://github.com/docker/swarm/blob/master/CONTRIBUTING.md, both have instructions to build Swarm. They have slight differences, such as:

1. CONTRIBUTING.md doesn't specify Golang version requirement
2. Build instructions look different, README.md doesn't have section on adding dependencies
3. CONTRIBUTING .md describes non-standard GOPATH settings

Ideally, the information in these two places should be consistent, or probably just in a single place.

cc @abronan (following up from discussion)

Thanks,

**Comment by MHBauer** [comment]
Agreed, please review #1190. I can make `CONTRIBUTING.md` similar if my change looks good.

**Comment by nishanttotla** [comment]
This is currently being worked on at #1645, consistent with the latest versions/releases.

**Comment by nishanttotla** [comment]
Closing this issue since it was fixed by #1645.
