### ISSUE TITLE
Swarm get started (network pro)

### ISSUE THREAD

**Issue by rolfedh** [docker/swarm#1606]
Manually set up a swarm in an AWS cluster; no docker-machine

Explain Specific discussion of difference between ports 2375, 2376 and 3375/6

Consider introducing a high availability step

**Comment by dvenza** [comment]
Yes, please consider also people deploying Swarm on bare metal, they do exist and they do not use docker-machine.
The documentation available right now contains "how to set up Swarm with machine" and "set up a development environment -- not for production", but it is not clear why the latter is not good for production.

**Comment by rolfedh** [comment]
Excellent. Thanks for your comments. I'll address those questions in this topic.

**Comment by rolfedh** [comment]
Created this topic and am closing this issue:
https://docs.docker.com/swarm/install-manual/
