### ISSUE TITLE
New topic: Plan for Swarm in production

### ISSUE THREAD

**Issue by rolfedh** [docker/swarm#1616]
What users should think about when architecting a Swarm installation.
* master/nodes ratios
* failover considerations
* multiple clusters
* testing infrastructure
* container networks
* hardware/os selection
* Compose or something else?
* When to consider a commercial solution such as UCP

**Comment by CooCooCaCha** [comment]
Discovery?

**Comment by dvenza** [comment]
Also networks and discovery, but from the outside.
Meaning, how the services run in containers can be accessed from outside the Swarm network? Do you need a public subnet? If they have any experience with Amazon they will quickly start to wonder if there is something like floating IP addresses.
They will ask if they can use DNS names to access the web services running in the Swarm.

At least, those are the questions I am trying to answer while setting up Swarm.

**Comment by rolfedh** [comment]
Excellent. Thanks for you comments. We'll cover this in our doc.

**Comment by rolfedh** [comment]
https://docs.docker.com/swarm/plan-for-production/
https://docs.docker.com/swarm/install-manual/
