### ISSUE TITLE
New topic: Example Swarm at scale

### ISSUE THREAD

**Issue by rolfedh** [docker/swarm#1617]
Mike G has an idea of creating an application that is more real world. The application would be based on the voting app out from Compose.

Allow users to standup an application that is more real world

Result of this work will be a working application and a Compose file

The piece should include a section at the end that suggests ways a user could extend.  Included in the suggestion should be some guidance but not actual steps.

* Add Jenkins
* Shard Postgres
* Add Interlock

**Comment by nishanttotla** [comment]
The initial code and description for this is here: https://github.com/mgoelzer/swarm-demo-voting-app

I'm working on writing a compose file, and demonstrating it at scale on AWS.

**Comment by nigelpoulton** [comment]
Cool @nishanttotla 

I'm part way through an initial draft of the doc -  install guide (without compose files) plus considerations around HA and design etc.

Keep me in the loop re what you do/plan to do to demo scale on AWS.

Cheers.

**Comment by nishanttotla** [comment]
I'll do that @nigelpoulton. Please feel free to report issues you face, or suggestions for improvement :)

**Comment by rolfedh** [comment]
https://docs.docker.com/swarm/swarm_at_scale/
