### ISSUE TITLE
Proposal: Swarm use unreserved/reserved resources from Mesos

### ISSUE THREAD

**Issue by ghost** [docker/swarm#1618]
When launch tasks, Swarm only use unreserved resource; and if Mesos offer reserved resources, the role info are also ignored which is rejected by Mesos master.

This proposal is to let Swarm use both un-reserved/reserved resources Mesos.

**Comment by klaus1982** [comment]
@jimenez any comments on this requirement?

**Comment by gradywang** [comment]
Append the PR #1890 , In that PR, Swarm is enabled to use both reserved and unreserved resources to create container. 

**The design proposal is** : swarm will use reserved resources firstly, if reserved resources are not enough for the creating container, then the unreserved resources will be used for the gap. This behaviour is hardcode, it does not support to change to use the unreserved resources firstly by a configuration.

**Comment by nishanttotla** [comment]
Closing due to https://github.com/docker/swarm/pull/2853
