### ISSUE TITLE
Proposal: Swarm use revocable resources from Mesos

### ISSUE THREAD

**Issue by ghost** [docker/swarm#1619]
After [MESOS-1607](https://issues.apache.org/jira/browse/MESOS-1607) and [MESOS-354](https://issues.apache.org/jira/browse/MESOS-354), the revocable resources will offer to Swarm; it'll improve the resources utilisation if Swarm used revocable resources.

I'm also working on [MESOS-4303](https://issues.apache.org/jira/browse/MESOS-4303) to clarify the protocol between Swarm & Mesos; if any suggestion, please let me know.

**Comment by jimenez** [comment]
@klaus1982 +1 on this, thanks for contributing!

**Comment by qianzhangxa** [comment]
I has submitted the design proposal in #1900.

**Comment by nishanttotla** [comment]
Closing due to https://github.com/docker/swarm/pull/2853
