### ISSUE TITLE
Proposal: Using S3 as backend for Swarm

### ISSUE THREAD

**Issue by wido-gg** [docker/swarm#1631]
# Disclaimer

I'm new in the docker and swarm comunnity. I have searched for this proposel but did not find it, so I apologize in advance if this has already been discused.
# Problem

Swarm failover is still hacking around exported data volumes. 
# Proposal

Having a backend such as ceph, gfs or S3 would help swarm to delegate the data in volumes. Flocker is a solution that does this, it could be integrated as a backend as well. Backends could be plugins, which could extend functionality.
# Why?

We have a cluster that cannot reacomodate running containers on demand. With the volumes located in an external source, we can include the values in the kv backend allowing that, in a multi-tenant environment, when a docker engine dies, the master can allocate the conainer in a new engine without worrying the data.

Currently, this is the behaviour in a stateless container, so such feature could be replicated using volumes-from, but there is always a critical single-point-of-failure. using volumes from an external storage could allow for reallocation without conditions

**Comment by nishanttotla** [comment]
Closing because new proposals aren't being built into Swarm anymore.
