### ISSUE TITLE
docker client cant connect to swarm SSL

### ISSUE THREAD

**Issue by bluishpe** [docker/swarm#1634]
Hi,
   Followed the below link to create docker and swarm in SSL:
http://www.blackfinsecurity.com/docker-swarm-with-tls-authentication/

I started swarm with the following options:

docker run -d -v /opt/swarm/setup/certs/:/opt/swarm/setup/certs/ swarm manage --tlsverify --tlscacert=/opt/swarm/setup/certs/ca_public.pem --tlscert=/opt/swarm/setup/certs/server_cert.pem --tlskey=/opt/swarm/setup/certs/server_private.pem -H tcp://0.0.0.0:2376 token://11d27820fe3a27f954981f06d3a902fe

the swarm is running fine in TLS:

[root@iwfvm07195 ~]# ps -ef | grep swarm
root     20674 20551  0 00:20 pts/0    00:00:00 grep --color=auto swarm
root     59446 59240  0 Jan13 ?        00:00:22 /swarm join --addr=iwxxxxx88.hpxxwlxb.net:2376 token://ff5a8fc30c0b4e5ebf097ae8cdc5e9b8
root     59524 59240  0 Jan13 ?        00:00:22 /swarm join --addr=iwfxxxx85.hpexxxxab.net:2376 token://ff5a8fc30c0b4e5ebf097ae8cdc5e9b8
root     60326 59240  0 Jan13 ?        00:00:18 /swarm manage --tlsverify --tlscacert=/opt/certs/ca.pem --tlscert=/opt/certs/swarmCRT.pem --tlskey=/opt/certs/swarmKEY.pem -H tcp://0.0.0.0:2376 token://ff5a8fc30c0b4e5ebf097ae8cdc5e9b8

But when I try to access thro windows docker client I get:

C:\docker\cert>docker --tlsverify --tlscacert=ca.pem --tlscert=localCRT.pem --tl
skey=localKEY.pem -H=iwxxxxx95.hpxxxxxb.net:2376 version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get https://iwxxxxx95.hpxxxxxb.net:2376/v1
.21/version: dial tcp 16.999.99.999:2376: ConnectEx tcp: No connection could be
made because the target machine actively refused it.

What would be the exact command to connect to SWARM SSL?

The connection to DOCKER SSL with the above command is working perfect.

**Comment by bluishpe** [comment]
Any help on the above query?

**Comment by bluishpe** [comment]
Hello Team,
      Now I am able to run swarm in SSL:

docker run -d -v /opt/certs/:/opt/certs/ -p 2374:2375 swarm manage --tlsverify --tlscacert=/opt/certs/ca.pem --tlscert=/opt/certs/swarmCRT.pem --tlskey=/opt/certs/swarmKEY.pem token://538090ef551832330937303d3d465661

But from the docker client it cant identify any dockers added to it:

C:\docker\cert>docker --tlsverify --tlscacert=ca.pem --tlscert=localCRT.pem --tlskey=localKEY.pem -H=iwfvm07195.hpeswlab.net:2374 info
Containers: 0
Images: 0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 0
CPUs: 0
Total Memory: 0 B
Name: 4d6ddfb56372

The number of nodes is zero. Is there anyway to debug this?

**Comment by bluishpe** [comment]
Hi,

I am able to run the swarm in SSL:

docker run -d -v /opt/certs/:/opt/certs/ -p 2374:2375 swarm manage --tlsverify --tlscacert=/opt/certs/ca.pem --tlscert=/opt/certs/swarmCRT.pem --tlskey=/opt/certs/swarmKEY.pem token://538090ef551832330937303d3d465661

but it still cant it identify the docker nodes added to it:

C:\docker\cert>docker --tlsverify --tlscacert=ca.pem --tlscert=localCRT.pem --tlskey=localKEY.pem -H=ixxxxxxx5.hpeswlab.net:2374 info
Containers: 0
Images: 0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 0
CPUs: 0
Total Memory: 0 B
Name: 4d6ddfb56372

The number of nodes is zero. Is there any way to debug this?

Thanks

**Comment by vieux** [comment]
When you start manage with TLS certs, if mean that you need to use TLS in the docker cli to connect to swarm, you did that.

but it also mean swarm will use TLS to connect to the nodes themselves

Did you setup TLS on you nodes ?

**Comment by bluishpe** [comment]
Hello Vieux,
      Thank you very much for the response.

Yes the nodes are also configured in TLS.

However when I remove TLS from SWARM, I can get the node info even though the nodes are still running in TLS.

The command I use when swarm is not in TLS is: (from docker client on my laptop)

docker -H=ixxxxxxx5.hpeswlab.net:2374 info

This gives me the node info correctly. To repeat, here the nodes are in TLS but swarm is not in TLS (still port 2374).

Any suggestions appreciated.

Regards

**Comment by bluishpe** [comment]
Hello,
     I re-created certificates with a common CA cert. Now swarm is able to pull docker info in TLS. 

Please consider this thread closed.

**Comment by vieux** [comment]
@bluishpe thanks for the update.
