### ISSUE TITLE
How to create swarm cluster with Consul Tokens 

### ISSUE THREAD

**Issue by vandita31** [docker/swarm#1643]
I have a question around creating a docker swarm cluster using Consul as a backend service. I currently have a Consul set up with ACL's enabled and the K/V pairs are protected by a master token. The documentation currently indicates steps for creating a swarm cluster using certs with Consul. Could someone shed some light on how to achieve the same ( swarm cluster) using ACL tokens for auth with Consul? 

My template file (consul.json.erb) looks something like this leveraging the use of master tokens.

```
{
  "server": <%=@server%>,
  "disable_remote_exec": true,
  "disable_update_check": true,
  "data_dir": "/var/lib/consul/data",
  "log_level": "INFO",
  "ui_dir": "/var/lib/consul/webui",
  "acl_datacenter": "<%=@datacenter%>",
  "datacenter": "<%=@datacenter%>",
  "client_addr": "0.0.0.0",
  "encrypt": "<%=@encrypt_key%>",
<%if @server -%>
  "acl_master_token": "<%=@acl_master_token%>",
<% if @bootstrap -%>
  "bootstrap_expect": <%= @consul_servers.length %>,
<%else%>
  "bootstrap_expect": 1,
<%end-%>
<% end -%>
<% local_servers = @consul_servers.delete(@fqdn) -%>
  "retry_join": <%=@consul_servers%>
}
```

Thanks in advance!

**Comment by vandita31** [comment]
Anyone have any input on the above issue? Would love some guidance. TIA!

**Comment by abronan** [comment]
Hey @vandita31, did you try to set up `CONSUL_HTTP_TOKEN` instead of putting the token in the config file? (answered on IRC but not sure you saw it :smile:). I'm not familiar with consul tokens but I think the client is using the environment variable for the ACL master token.

**Comment by amitshukla** [comment]
@vandita31 was your question answered?

**Comment by vandita31** [comment]
@amitshukla Nope. I haven't seen any examples of setting up swarm cluster + consul + auth tokens as an example. We are using the Consul UI and ACL's are enabled via the Auth token , so keep in mind we are not using any certs for Consul security. I'm going to circle back on this and attempt again in my sprint this week , please keep this open for now and I can paste you the logs and issues I faced. Thanks for the follow up!

**Comment by chenqing** [comment]
I have the same problem. @vandita31  have you fix this ?

**Comment by soletan** [comment]
I am having issues with using consul cluster for registration either. There is a consul cluster consisting of three nodes and I'm trying to join docker swarm using a command like this:

```
docker run swarm join --advertise=1.2.3.4:2375 consul://c1.myregistry.com/docker/swarm
```

@abronan How would provide this environment variable? Like this?

```
CONSUL_HTTP_TOKEN=cbe5aba7-879b-999a-07cc-2efd9ad993bb docker run swarm join --advertise=1.2.3.4:2375 consul://c1.myregistry.com/docker/swarm
```

In my case this didn't work. Either command results in this:

```
time="2016-03-06T13:12:54Z" level=info msg="Initializing discovery without TLS"
time="2016-03-06T13:12:54Z" level=info msg="Registering on the discovery service every 1m0s..." addr="1.2.3.4:2375" discovery="consul://c1.myregistry.com/docker/swarm"
time="2016-03-06T13:12:55Z" level=error msg="cannot set or renew session for ttl, unable to operate on sessions"
time="2016-03-06T13:13:55Z" level=info msg="Registering on the discovery service every 1m0s..." addr="1.2.3.4:2375" discovery="consul://c1.myregistry.com/docker/swarm"
```

**Comment by soletan** [comment]
Okay, found a basically working soluttion:

1. In my case I had to explicitly choose port number to use on selected consul node.
2. Of course, environment variable wasn't passed and before that attempt above I simply missed the fact that `-e` behaves differently according to where it is given in command line to docker.

Fixing port on its own resulting in

```
time="2016-03-06T14:55:06Z" level=error msg="Unexpected response code: 403 (rpc error: Permission denied)"
```

But by properly providing environment option the swarm was registered in consul properly:

```
docker run -e CONSUL_HTTP_TOKEN=cbe5aba7-879b-999a-07cc-2efd9ad993bb swarm join --advertise=1.2.3.4:2375 consul://c1.myregistry.com:8500
```

The prefix `/docker/swarm` vanished for consul implicitly limiting scope to prefix defined in ACL of used token.

**Comment by soletan** [comment]
Just to qualify my anser to include some basic security concerns (as providing token on command line isn't quite save): I switched using environment file for providing token, e.g. in */etc/docker/token*:

```
CONSUL_HTTP_TOKEN=cbe5aba7-879b-999a-07cc-2efd9ad993bb
```

This file is then used like this:

```
docker run --env-file /etc/docker/token swarm join --advertise=1.2.3.4:2375 consul://c1.myregistry.com:8500
```

**Comment by abronan** [comment]
Thank you for the explanation @soletan, much appreciated. And apologies for having missed the evolution on this issue. Seems like an answer has been found so I'll be closing this one. Feel free to comment or create a new issue if this is still a problem. Thanks.
