### ISSUE TITLE
Enhance the scheduler with knowledge about Disk space and inode usage

### ISSUE THREAD

**Issue by abronan** [docker/swarm#1678]
The scheduler has knowledge about CPU and Memory reservations. It is necessary though to take Disk space usage into account and/or rank nodes based on _Inode_ usage for data intensive containers or just for simple build schedules.

Indeed it makes no sense to schedule a data intensive container or a build on a Node whose available inodes are near exhaustion after we pick a subset of nodes and the strategy is applied. Especially with device drivers sometimes leaking inodes, this can lead to cluster wide problems when scheduling new tasks.

Not sure the API returns any information based on inodes usage for a given Node/Engine, so this potentially requires enhancements on the docker API side.

**Comment by vieux** [comment]
I agree, it would be a nice enhancement. 
As you said, we need to update docker info in the engine first to return the information.

**Comment by dongluochen** [comment]
Thanks @abronan. I would like to put disk space and inode exhaustion as `error` instead of scheduler preference. The reason is they are not a performance measure. They will cause errors and not performance penalty. It's also hard to fit them with strategy like `binpack`.

**Comment by dtepeneu** [comment]
Any update about this? We are looking forward to a swarm cluster that is disk-aware... 

Would it also be possible to have a reservation policy for disk space similar with the memory allocation? Of course, this information should be surfaced via "docker info" and ideally via a dedicated API (there was a discussion about enhancing the REST API to allow us to directly get the node information without parsing the output from GET /info, is there any update in that?)

Thanks,
   Dorin
