### ISSUE TITLE
Consul and log error

### ISSUE THREAD

**Issue by auzias** [docker/swarm#1680]
Hi everyone.

Docker runs on a cluster on a few machines. The command for the daemon is as follow:
`docker daemon -H tcp://0.0.0.0:2375 --cluster-advertise eth0:2375 --cluster-store consul://127.0.0.1:8500`

About every 20 seconds the daemon, **whether or not consul is running**, appends in the logs:
> Jan 13 09:50:04 bugs20 docker[29356]: time="2016-01-13T09:50:04.203417359+01:00" level=error msg="Registering as \"192.168.196.20:2375\" in discovery failed: cannot set or renew session for ttl, unable to operate on sessions"
> Jan 13 09:50:19 bugs20 docker[29356]: time="2016-01-13T09:50:19.056980231+01:00" 
level=error msg="discovery error: Unexpected watch error"

I can't get rid of these errors than generate log all days long while no accident are experienced during Swarm usage (consul is used for Swarm).

---
#### Environment details
**`docker version`**
````
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64
````
**`docker info`**
````
Containers: 68
Images: 12
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 148
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 12
Total Memory: 47.25 GiB
Name: bugs20
ID: DVQZ:XBAT:IN4R:VLTP:2B4H:J4LX:4TDT:HXL7:U6QT:O3IQ:MB6E:XSRP
WARNING: No memory limit support
WARNING: No swap limit support
Cluster store: consul://127.0.0.1:8500
Cluster advertise: 192.168.196.20:2375
````
**`uname -a`**
````
Linux bugs20 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
````
---

I opened this issue. I should have opened it on Swarm, my bad.
Should I copy paste the whole content or just give the link ? https://github.com/docker/docker/issues/19589

**Comment by vieux** [comment]
@auzias it look like a docker issue, let's keep only docker/docker#19589 open
