### ISSUE TITLE
events api not streaming events

### ISSUE THREAD

**Issue by nicolaka** [docker/swarm#1686]
Version : swarm:1.0.1

Setup: 3 Swarm Managers with 2 Swarm nodes

Issue: Sometimes issuing `docker events` against a Swarm manager will not stream any events that the docker engines are reporting. Restarting the Swarm managers fixed the issue. Could not reproduce.

Example:

Here i'm creating containers as I listen for swarm events. But no events are showing.

$ sudo docker -H tcp://127.0.0.1:2376  events

$

After restarting swarm manager , it works as expected.

**Comment by MHBauer** [comment]
Was this a freshly set up swarm, or were you listening for events for a while? I know we have integration tests so listen for events, but I'm not sure how we'd test a problem that requires a swarm to sit around for a while.

**Comment by nicolaka** [comment]
Nop, and not sure exactly what caused it but it did happen to me before with a single manager. I'll try to reproduce.

**Comment by dongluochen** [comment]
@nicolaka Did the command exit by itself? Or did you send a Ctrl^C? What's swarm version?

**Comment by nicolaka** [comment]
@dongluochen nop, it just stays silent. Swarm version is 1.0.1.

**Comment by vieux** [comment]
@nicolaka I think I found a workaround https://github.com/docker/swarm/pull/1728
