### ISSUE TITLE
Multicast and overlay network

### ISSUE THREAD

**Issue by auzias** [docker/swarm#1691]
I am testing a application using multicast for the discovery. I created a Swarm cluster and a `network create -d overlay swarm-net` so the containers share the same LAN across the several Swarm agents hosts.

The discovery seemed to not be working, so I installed `tshark`.  `tshark` shows the IP address node within which `tshark` is running and the multicast address for the packet being _sent_ though `tshark` **does not** show any incoming multicast packet.

Note that, as I don't know a better way to do so, the container is run with `--privileged` to enable `tshark`.

Is the multicast blocked because of Docker iptable?
How to enable multicast in an overlay network?

Any help would be welcome. I don't know if it is a bug or just an obvious issue I can't debbug myself, this is also post on [SO](http://stackoverflow.com/questions/35039612/multicast-with-docker-swarm-and-overlay-network).

---
#### Environment details
**`docker version`**
````
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64
````
**`docker info`**
````
Containers: 68
Images: 12
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 148
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 12
Total Memory: 47.25 GiB
Name: bugs20
ID: DVQZ:XBAT:IN4R:VLTP:2B4H:J4LX:4TDT:HXL7:U6QT:O3IQ:MB6E:XSRP
WARNING: No memory limit support
WARNING: No swap limit support
Cluster store: consul://127.0.0.1:8500
Cluster advertise: 192.168.196.20:2375
````
**`uname -a`**
````
Linux bugs20 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
````
**`docker -H tcp://0.0.0.0:5732 -v #swarm-docker -v `**
````
Docker version 1.9.1, build a34a1d5
````
**`consul -v`**
````
Consul v0.5.2
Consul Protocol: 2 (Understands back to: 1)
````

**Comment by chanwit** [comment]
Hi @auzias 
I do not think an overlay network supports multicast.

cc @vieux @mavenugo

**Comment by auzias** [comment]
Really ?!  :fearful:

Does the doc give details about it? I can't find anything about that. I really did not expect such drawback. Where can I find info about it without getting lost in the source code?

**Comment by chanwit** [comment]
@auzias maybe I'm wrong. 

Please wait for @mavenugo or other `libnetwork` guys to answer this.
We still have some hope.

**Comment by chanwit** [comment]
@auzias  Oh this is a bad news for you.
Libnetwork uses `vxlan` unicast.
docker/libnetwork#522.

But I think multicast will be implemented soon enough or maybe you can try some third-party plugins.

**Comment by auzias** [comment]
Any suggestion for third-party plugins?

I don't get the link between the  docker/libnetwork#522 and mine.

**Comment by chanwit** [comment]
@auzias  Sorry for my typo it's docker/libnetwork#552.

**Comment by mavenugo** [comment]
@auzias @chanwit, atm overlay driver doesn't support multicast. contributions welcome.

**Comment by auzias** [comment]
@mavenugo  where should I start to contribute ?

**Comment by mavenugo** [comment]
@auzias https://github.com/docker/libnetwork/issues/552

**Comment by nishanttotla** [comment]
Closing this issue since it's a `libnetwork` issue being discussed at https://github.com/docker/libnetwork/issues/552.
