### ISSUE TITLE
 docker-compose pull with constraint on swarm cluster?

### ISSUE THREAD

**Issue by winggundamth** [docker/swarm#1692]
Does docker-compose pull command support pull with constraint on swarm cluster?
I created issue on docker-compose but I'm not sure docker-compose or docker-swarm that responsibility for this.
https://github.com/docker/compose/issues/2764

For example

``` bash
$ docker info
Containers: 29
Images: 56
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 3
 pre-01: pre-01:2376
  └ Status: Healthy
  └ Containers: 4
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 2.044 GiB
  └ Labels: preproduction=true, executiondriver=native-0.2, kernelversion=3.19.0-47-generic, operatingsystem=Ubuntu 14.04.3 LTS, provider=generic, storagedriver=overlay
 prd-01: prd-01:2376
  └ Status: Healthy
  └ Containers: 5
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 8.179 GiB
  └ Labels: production=true, executiondriver=native-0.2, kernelversion=3.19.0-47-generic, operatingsystem=Ubuntu 14.04.3 LTS, provider=generic, storagedriver=overlay
 prd-02: prd-02:2376
  └ Status: Healthy
  └ Containers: 4
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 8.179 GiB
  └ Labels: production=true, executiondriver=native-0.2, kernelversion=3.19.0-47-generic, operatingsystem=Ubuntu 14.04.3 LTS, provider=generic, storagedriver=overlay

$ cat docker-compose.yml
nginx:
    image: nginx
    environment:
        - "constraint:label==production=true"
```

But when I did docker-compose pull it still pull to whole swarm cluster.

``` bash
$ docker-compose pull
Pulling nginx (nginx:latest)...
pre-01: Pulling nginx:latest... : downloaded
prd-01: Pulling nginx:latest... : downloaded
prd-02: Pulling nginx:latest... : downloaded
```

**Comment by chanwit** [comment]
@winggundamth Sorry no. It's always pulling the whole cluster.

Please note that `constraints` and `affinities` apply only when you're doing `docker run`.

**Comment by winggundamth** [comment]
Can I ask this as a feature request?

**Comment by chanwit** [comment]
@winggundamth it's a limitation of the docker client. You'd better request for this at the Engine repo.

It is known that there were similar requests like this for `docker build` with environment variables.
I personally think that it's a cool feature if we can selectively pull images to a zone of cluster.
@vieux @aluzzardi @thaJeztah WDYT about this?

cc @docker/swarm-maintainers

**Comment by chanwit** [comment]
A side note.

Maybe `docker build --build-arg="constraint:node==node-1"` can be a workaround for pulling to a specific node. Compose also supports this feature.

**Comment by winggundamth** [comment]
I created issue on docker engine here https://github.com/docker/docker/issues/19785

@chanwit I'll try that but I'm not sure that it will support constraint by label or not.

**Comment by heycalmdown** [comment]
Same problem here.

@chanwit, should I build an empty image from the image what I actually want for a workaround?

**Comment by chanwit** [comment]
@heycalmdown Yep I think you can do that. At least it will pull your base image to the correct node.

**Comment by kyhavlov** [comment]
I submitted a PR for this at #2302, that covers swarm but it'll need another PR in docker engine to add it to the CLI.

**Comment by schmunk42** [comment]
Any progress on this? Especially in combination with `docker-compose`. We've some small proxy-nodes which actually only need a few images.

We have to constantly delete images, which then get pulled again, and so on...
