### ISSUE TITLE
Run container to every nodes in Swarm Cluster

### ISSUE THREAD

**Issue by winggundamth** [docker/swarm#1705]
Now I'm using this script to clean unused Docker Images in my whole Swarm Cluster

```bash
eval $(docker-machine env --swarm swarm-master)
docker pull spotify/docker-gc
for machine in $(docker-machine ls | tail -n +2 | awk '{ print $1 }'); do
  eval $(docker-machine env $machine)
  docker run --rm=true -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc
done
```

Any way to remove the for loop and use only one line command with docker run to run spotify/docker-gc to every nodes in Swarm Cluster?

I'm not sure sure this has to be done by Docker Engine or Docker Swarm?

**Comment by chanwit** [comment]
relates to #601

**Comment by winggundamth** [comment]
Ok so I'll close this and follow #601 instead
