### ISSUE TITLE
Per-server TLS certificates

### ISSUE THREAD

**Issue by avaer** [docker/swarm#172]
#148/#160 work fine for the frontend connection, but this change seems to assume all of the TLS backend servers use the same TLS config as the swarm manage listener... This is not always the desired behavior, especially with heterogeneous backends that don't all use the same certificate set (in which case you basically can't use swarm?).

There seems to be no way to override this behavior; correct me if I'm wrong.

This problem is solved if there was a way specify the TLS key/cert/ca for docker daemons on a per-server basis, but it's not completely straightforward how that would work with the various discovery APIs...

**Comment by SvenDowideit** [comment]
So swarm can't talk to a group of pre-existing Docker daemons - for example, a set of boot2docker base servers, where each will have its own CA (and other certs).

I was hoping to add a very simple `docker-swarm join` to my boot2docker boot scripts, and instantly have a swarm.

**Comment by SvenDowideit** [comment]
I'll do some work on the userguide docs to tell users what they need to know.

**Comment by SvenDowideit** [comment]
@vieux @aluzzardi looking at the `docker-swarm manage` commandline - does that mean you also can't have a TLS swarm socket and non-TLS Docker daemons, or non-TLS swarm daemon with a TLS Docker daemon? or a mix of TLS and non-TLS Docker daemons?

**Comment by SvenDowideit** [comment]
mm, also, can I use https://github.com/SvenDowideit/generate_cert ? that will generate the certs without requiring user input.

**Comment by cpuguy83** [comment]
@SvenDowideit I was messing with machine last night.
I think, or at least what I suggested, is to have machine generate a single CA (or allow one to be specified) and a single set of client keys, and then each new host gets a new set of server keys signed by that single CA.
This CA can then in turn be used to sign server keys for swarm.

**Comment by vieux** [comment]
@SvenDowideit at the moment, is all TLS or no TLS, no mix. We don't want to introduce 8 flags for TLS in swarm, 4 is already enough :D 

You have to generate the certs with `extendedKeyUsage = clientAuth,serverAuth`

@ehazlett can you confirm for machine ?

**Comment by ehazlett** [comment]
Yeah after thinking about @cpuguy83 suggestion, I think this is the right way (single CA, single client, new hosts get new server certs).

I am working on this for Machine.

**Comment by vieux** [comment]
:+1:

**Comment by aluzzardi** [comment]
:+1: 

If you have a mix of CAs, you can still use TLS with no `--tls-verify`.

However, as soon as you want to verify the certs, we simply assume that a proper PKI is in place.
