### ISSUE TITLE
godep: Unable to parse Godeps/Godeps.json: invalid character ':' after array element

### ISSUE THREAD

**Issue by gradywang** [docker/swarm#1720]
Hi,

I want to build swarm with the latest released source files on Ubuntu 14.04, but I meet the following errors:

root@gradyhost1:/opt/tmp# godep restore -v
godep: Unable to parse Godeps/Godeps.json: invalid character ':' after array element

My detailed steps as below:
1. Prepare the environment as below:
root@gradyhost1:/opt/tmp# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.1 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

root@gradyhost1:/opt/tmp# go version
go version go1.5.3 linux/amd64

root@gradyhost1:/opt/tmp# godep version
godep v51 (linux/amd64/go1.5.3)
2. Detailed steps as below:
root@gradyhost1:/opt/tmp# wget https://github.com/docker/swarm/archive/v1.0.1.tar.gz
root@gradyhost1:/opt/tmp# mkdir -p $PWD/src/github.com/docker
root@gradyhost1:/opt/tmp# tar -C src/github.com/docker -xzf v1.0.1.tar.gz
root@gradyhost1:/opt/tmp# mv src/github.com/docker/swarm-1.0.1 src/github.com/docker/swarm
root@gradyhost1:/opt/tmp# export GOPATH=$PWD
root@gradyhost1:/opt/tmp# cd src/github.com/docker/swarm/
root@gradyhost1:/opt/tmp/src/github.com/docker/swarm# godep restore
godep: Unable to parse Godeps/Godeps.json: invalid character ':' after array element

Can someone help me on this issue?

**Comment by nishanttotla** [comment]
@gradywang thanks for reporting this, I can see that there's a `{` missing above line 43 in https://github.com/docker/swarm/blob/v1.0.1/Godeps/Godeps.json

Ping @vieux @abronan @dongluochen I'm not sure why our 1.0.1 release code has that, but can we fix it?

Check image below:
<img width="704" alt="screen shot 2016-02-01 at 1 06 20 am" src="https://cloud.githubusercontent.com/assets/1872537/12712832/0fdbdd34-c880-11e5-97c3-d444214e6571.png">

**Comment by vieux** [comment]
I would wait 1.1.0 in a few days.

**Comment by gradywang** [comment]
@nishanttotla thanks for your reply. How to submit a pull request to a stable release to fix this issue?

**Comment by vieux** [comment]
@gradywang this is already fixed in master, you can build 1.1.0-rc2 today without this issue.

**Comment by nishanttotla** [comment]
@gradywang please build 1.1.0-rc2 instead, as mentioned above, where you shouldn't have this problem: https://github.com/docker/swarm/releases/tag/v1.1.0-rc2

Closing the issue.
