### ISSUE TITLE
Abnormal swarm behavior while querying port

### ISSUE THREAD

**Issue by Yogesh9692** [docker/swarm#1731]
I am running swarm as a separate container, using docker 1.9.1 version. Swarm is listening on http://192.168.56.101:2376, When I view containers json I get 2 records, cdn_lr001_m2_fkt and cdn_lr001_m1_fkt, But when I do docker -H tcp://192.168.56.101:2376 port cdn_lr001_m1_fkt, I see abnormal behavior. It works for cdn_lr001_m2_fkt and doesn't work for cdn_lr001_m1_fkt.
Am I missing something? or is it a bug?

**_This is the trace- _** (If I am not clear enough)

user@lr1:~$ curl -v http://192.168.56.101:2376/containers/json
* Hostname was NOT found in DNS cache
*   Trying 192.168.56.101...
* Connected to 192.168.56.101 (192.168.56.101) port 2376 (#0)
> GET /containers/json HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 192.168.56.101:2376
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Mon, 01 Feb 2016 12:55:33 GMT
< Content-Length: 828
<
[
 {"Id":"c5e5730fd5f3f624a6d04910fd56ee1bd31db3973acc7e5ca70ae6caf0de122d",
  _"Names":["/lr2/**cdn_lr001_m2_fkt**"],_
  "Image":"alef-cdnv2-child:latest",
  "Command":"childapp -parent=192.168.56.105:80 -cust-id=fkt -db-dir=/db-dir -content-dir=/content-dir",
  "Created":1454329736,
  "Status":"Up 26 minutes",
  "Ports":[{"IP":"192.168.56.102","PrivatePort":3001,"PublicPort":32768,"Type":"tcp"}],
  "SizeRw":0,
  "SizeRootFs":0,
  "Labels":{}},

 {"Id":"fae5a3ad3625e76f9ec3eb26c768721cc0faa472f37f2e01ecb224a185a66212",
  "Names":["/lr1/**_cdn_lr001_m1_fkt_**"],
  "Image":"alef-cdnv2-child:latest",
  "Command":"childapp -parent=192.168.56.105:80 -cust-id=fkt -db-dir=/db-dir -content-dir=/content-dir",
  "Created":1454329731,
  "Status":"Up 26 minutes",
  "Ports":[{"IP":"192.168.56.101","PrivatePort":3001,"PublicPort":32768,"Type":"tcp"}],
  "SizeRw":0,
  "SizeRootFs":0,
  "Labels":{}}
]
* Connection #0 to host 192.168.56.101 left intact

user@lr1:~$ docker -H tcp://192.168.56.101:2376 port **_cdn_lr001_m1_fkt_**
Error response from daemon: No such container cdn_lr001_m1_fkt

user@lr1:~$ docker -H tcp://192.168.56.101:2376 port **_cdn_lr001_m2_fkt_**
3001/tcp -> 192.168.56.101

**Comment by dongluochen** [comment]
@Yogesh9692 Is the Docker daemon where cdn_lr001_m1_fkt runs reachable or not? What's the output from `docker -H tcp://192.168.56.101:2376 ps -a`? I vaguely remember an issue like that. 
cc @vieux.

**Comment by amitshukla** [comment]
@Yogesh9692 any update based on Dongluo's comment above?

**Comment by Yogesh9692** [comment]
@dongluochen @amitshukla Yes cdn_lr001_m1_fkt is reachable. And when I do <ps -a> it shows me all running containers. Actually when I do <ps -a> swarm is also listed, so <ps> works fine.

**Comment by dongluochen** [comment]
@Yogesh9692 What's the output from `docker -H tcp://192.168.56.101:2376 ps -a | grep -i cdn_lr001_m1_fkt`? Do you see one record or more than one? Swarm gets confused when there are more than containers with same name.

**Comment by Yogesh9692** [comment]
@dongluochen I see only one record, the one which I grep. I am not running containers with same names, they are similar though but not same does that matters? I think it should not.

**Comment by dongluochen** [comment]
@Yogesh9692 What do you get from `docker -H tcp://192.168.56.101:2376 inspect cdn_lr001_m1_fkt`?

**Comment by Yogesh9692** [comment]
I am not facing this issue now. Don't know why! I am using same docker version. I am trying to reproduce the bug will update you soon. Closing it for now.
