### ISSUE TITLE
Additional Remote API endpoints?

### ISSUE THREAD

**Issue by avaer** [docker/swarm#177]
Currently many endpoints have a ```notImplementedHandler``` with a message that the endpoint is not supported in clustering mode. Found this out trying to do a swarmed image ```pull```, which would have been much nicer than ```pull``` in a loop.

Is this a case of "not implemented *yet*" or "swarm will not implement these APIs"?

If the latter, is the intended way to (for example) update images across the cluster to manually hit all the daemons?

**Comment by aluzzardi** [comment]
Thanks @vincentwoo 

We are getting there, endpoint by endpoint!

The overall progress is tracked by #602
