### ISSUE TITLE
Restarting Consul leader leaves redundant Swarm cluster without a primary manager

### ISSUE THREAD

**Issue by jpetazzo** [docker/swarm#1782]
## What I have

- 5 nodes cluster
- each node runs Consul 0.6.3
- each node runs Swarm 1.1.0
- Swarm is setup to use `consul://localhost:8500` for discovery and redundancy

## What I do

- I'm rebooting random nodes, but between reboots, I let the cluster settle (i.e. I wait until all nodes are shown healthy, both by Consul and Swarm with `docker info`)

## What I expect to see

- everything is fine

## What I see instead

- when rebooting the Consul leader (which is NOT the Swarm primary at that time), the Swarm primary loses the cluster leadership, and never recovers

## Possibly related (but unsure)

#1088 #1025 #1491 #982 

## Details

Here are a bunch of logs from Consul + Swarm managers + output of `docker info`.

Towards the end of the logs:
- Swarm primary is node 3
- Consul leader is node 5
- after rebooting node 2, everything was OK
- after rebooting node 5, we're dead

Note: after collecting those logs, I restarted node 3, and eventually a leader election happened and my cluster works again.

[consul-1.log.txt](https://github.com/docker/swarm/files/123262/consul-1.log.txt)
[consul-2.log.txt](https://github.com/docker/swarm/files/123263/consul-2.log.txt)
[consul-3.log.txt](https://github.com/docker/swarm/files/123264/consul-3.log.txt)
[consul-4.log.txt](https://github.com/docker/swarm/files/123265/consul-4.log.txt)
[consul-5.log.txt](https://github.com/docker/swarm/files/123266/consul-5.log.txt)
[swarm-agent-master-1.log.txt](https://github.com/docker/swarm/files/123267/swarm-agent-master-1.log.txt)
[swarm-agent-master-2.log.txt](https://github.com/docker/swarm/files/123268/swarm-agent-master-2.log.txt)
[swarm-agent-master-3.log.txt](https://github.com/docker/swarm/files/123269/swarm-agent-master-3.log.txt)
[swarm-agent-master-4.log.txt](https://github.com/docker/swarm/files/123270/swarm-agent-master-4.log.txt)
[swarm-agent-master-5.log.txt](https://github.com/docker/swarm/files/123271/swarm-agent-master-5.log.txt)
[swarm-info-1.log.txt](https://github.com/docker/swarm/files/123273/swarm-info-1.log.txt)
[swarm-info-2.log.txt](https://github.com/docker/swarm/files/123272/swarm-info-2.log.txt)
[swarm-info-3.log.txt](https://github.com/docker/swarm/files/123275/swarm-info-3.log.txt)
[swarm-info-4.log.txt](https://github.com/docker/swarm/files/123274/swarm-info-4.log.txt)
[swarm-info-5.log.txt](https://github.com/docker/swarm/files/123276/swarm-info-5.log.txt)

**Comment by jpetazzo** [comment]
Extra details to reproduce:

- my 5 nodes are on EC2
- each node runs a Consul server, with `-advertise=172.31.X.X -client=0.0.0.0`
- first Consul node was started with `-bootstrap`, other nodes with `-join 172.31.X.X`
- each node runs a Swarm manager listening on :3376, with `--advertise 52.29.X.X:3376 --replication --consul://localhost:8500`

Then:
- `docker info | grep ^Primary` to check Swarm's primary node
- `curl localhost:8500/v1/status/leader` to check Consul's leader
- if the same nodes are leaders, just kill the Swarm manager on that node (warning, there is a catch, since I'm using two different addressing plans)
- once the cluster is stable again (i.e. Swarm primary is different from Consul leader), I execute "sudo reboot" on the Consul leader
- once the Consul leader comes back (shows all green in Consul UI) Swarm still has no leader :panda_face:

**Comment by abronan** [comment]
I think it's definitely related to the way the Consul cluster is setup (pointing to a local instance rather than a single Consul server), which is totally valid by the way. Will investigate using the same setup. Thanks for the report!

**Comment by abronan** [comment]
@jpetazzo I found some time to spend on this issue and I found the culprit. I'm have a working fix (which is quite non trivial), need to spend some time testing with other stores and implement the tests. Thanks again for reporting!
