### ISSUE TITLE
broken link in docs

### ISSUE THREAD

**Issue by jmccormick2001** [docker/swarm#1788]
https://docs.docker.com/swarm/machine-provisioning/provision-w-machine/

appears to be broken at the moment

**Comment by vieux** [comment]
@jmccormick2001 the correct link seems to be https://docs.docker.com/swarm/provision-with-machine/

where did you get your link ?

**Comment by vieux** [comment]
ping @moxiegirl

**Comment by jmccormick2001** [comment]
I found that broken link at the bottom of this page:

https://docs.docker.com/machine/overview/

**Comment by nathanleclaire** [comment]
https://github.com/docker/machine/issues/3030

**Comment by nishanttotla** [comment]
Closing this issue since it's not a Swarm issue.
