### ISSUE TITLE
Can't access rescheduled container using its name after failed node recovers

### ISSUE THREAD

**Issue by jpetazzo** [docker/swarm#1810]
This is about the experimental rescheduling support (#1488).

## What I do

- start a resilient container:
  ```
  docker run -d --name highlander -e reschedule:on-node-failure redis
  ```

- reboot the node of this container:
  ```
  NODE=$(docker inspect --format '{{.Node.Name}}' highlander)
  ssh $NODE sudo reboot
  ```

- wait until the node is done rebooting...

- try to access the container using its name, `highlander`:
  ```
  docker inspect highlander
  ```

## What I expect

Information about the container

## What I see instead

```
docker inspect highlander
[]
Error: No such image or container: highlander
```

## Discussion

Of course, when the node comes back, we end up with two `highlander` containers, and this results into a name clash. Possible workarounds:
- Swarm could just return *all* matching containers
- Swarm could return an error indicating the conflict
- When the node rejoins, Swarm could rename the clashing containers (e.g. `highlander` would become `highlander_conflicts_with_329bcf928295219e9f9cbe...`)

One word of warning about the last option: this could cause problems with the `swarm-manager` containers (i.e. they could end up clashing too, and just doing a special case with the name of the container (e.g. "name starts with swarm") wouldn't be enough since that could be a problem for people using custom Swarm images...)

**Comment by dongluochen** [comment]
I think there are 2 problems here. 

For container rescheduling, I believe the existing design is to *delete* the container on the *failed* node when it comes back. The new one should stay. Swarm manager should take care of this if it has not been interrupted. 

The other problem is how to deal with duplicate container names in Swarm. I think we may report *conflict* information instead of `Error: No such image or container: highlander`.

**Comment by dongluochen** [comment]
cc @vieux.

**Comment by vieux** [comment]
@jpetazzo @dongluochen regarding the error, it's printed by the CLI, nothing much we can do

as @dongluochen said, the 1st container should be removed, @jpetazzo do you have logs ? (in --debug)

**Comment by amitshukla** [comment]
@jpetazzo ping on logs ^^

**Comment by vieux** [comment]
@jpetazzo can you retry with `1.1.3-rc1` we fixed a bunch of issues.

Also, are you setting TTLs to a small values like `--engine-refresh-min-interval=1s --engine-refresh-max-interval=1s --engine-failure-retry=1` ? otherwise swarm takes some time to detect node failure.

**Comment by jpetazzo** [comment]
I couldn't reproduce with 1.1.3-rc1 and `--debug` so I thought we were good, but then when I did a dry run fro my meetup tonight, the problem appeared again. Here the logs (without `--debug`). I'll try to reproduce again over the week-end. Also, I had a crash when trying to scale a service to 100 containers; I'll open a separate ticket.



[node3.log.txt](https://github.com/docker/swarm/files/148483/node3.log.txt)
[node2.log.txt](https://github.com/docker/swarm/files/148484/node2.log.txt)
[node1.log.txt](https://github.com/docker/swarm/files/148485/node1.log.txt)
[node5.log.txt](https://github.com/docker/swarm/files/148486/node5.log.txt)

**Comment by jpetazzo** [comment]
(To answer @vieux's question: no, I didn't change the TTL, but I waited a looooong time)

**Comment by jpetazzo** [comment]
This is still the case with 1.1.3-rc2.

- start highlander container with reschedule policy
- reboot the node on which the container was scheduled

Result: the container gets rescheduled two times but both instances fail to start.

```
docker@node1 /tmp: docker ps -a
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                 NAMES
f78917f3e041        redis                                         "/entrypoint.sh redis"   5 seconds ago                                                                 node4/highlander
cb0ea9976e06        redis                                         "/entrypoint.sh redis"   5 seconds ago                                                                 node1/highlander
```

After the node reboots and reintegrates the cluster:

```
docker@node1 /tmp: docker ps -a
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS                     PORTS                                 NAMES
f78917f3e041        redis                                         "/entrypoint.sh redis"   3 minutes ago                                                                        node4/highlander
cb0ea9976e06        redis                                         "/entrypoint.sh redis"   3 minutes ago                                                                        node1/highlander
4a234dfde04c        redis                                         "/entrypoint.sh redis"   3 minutes ago       Exited (0) 3 minutes ago                                         node3/highlander
```

```
Server:
 Version:      swarm/1.1.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   7e9c6bd
 Built:        Wed Mar  2 00:15:12 UTC 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

Log is attached.

[node1-swarm-agent-master.log.txt](https://github.com/docker/swarm/files/154455/node1-swarm-agent-master.log.txt)

**Comment by jpetazzo** [comment]
@vieux pointed out to me that since I issue a `reboot`, the Engine does a proper shutdown, and my `highlander` container is stopped normally. When the rescheduling logic kicks in, the container is created on another node, but it's not started -- this is the normal behavior.

However, it doesn't explain why I have *two* containers. I reproduced the same tests, but by disconnecting the node from the network. After disconnecting the node, I get *two* new containers, running on two different hosts, both named `highlander`.

**Comment by jpetazzo** [comment]
Confirmed, #2025 fixes it. Thanks!
