### ISSUE TITLE
"No route to host" on Docker Swarm cluster (overlay networking)

### ISSUE THREAD

**Issue by jacobmarshall** [docker/swarm#1814]
I've been trying to figure out why my containers, on a newly setup swarm cluster, are unable to reach each other using their container names as hostnames.

I have the following setup;
- master (consul & swarm manager)
- agent1 (swarm agent)
- agent2 (swarm agent)

The agents have been setup with the `cluster-store` and `cluster-advertise` engine opts - equal to `consul://192.168.33.172:8500` (which is the private IP of the master server), and `eth0:2376` respectively.

The swarm agents are all running...
```
docker run -d --restart=unless-stopped --name=swarm swarm join --advertise=$(docker-machine ip agent$N):2376 consul://192.168.33.172:8500
```

Doing a `docker info` comes back with all nodes healthy and no errors.

If I launch a container using the nginx image, running in a "test" overlay network (with the following command)...
```
docker run --rm -it -e "constraint:node==agent1" --name=test_nginx --net=test nginx
```

And then run a busybox container, running in the same "test" overlay network, on another agent, to `wget` the page at `http://test_nginx` (with the following command)...
```
docker run --rm -it -e "constraint:node==agent2" --net=test busybox wget -qO- http://test_nginx
```

I get the following...
```
wget: can't connect to remote host (10.0.2.2): No route to host
```

If I do a `docker network inspect test` I get the following...
```
[
    {
        "Name": "test",
        "Id": "c7d427a9e7674787cff15faa446aaae6c22bb3728084f5c7b4a593e8c281bb48",
        "Scope": "global",
        "Driver": "overlay",
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.2.0/24",
                    "Gateway": "10.0.2.1/24"
                }
            ]
        },
        "Containers": {
            "3ccbf1780dab4c25797d8e85df35fb70f609ee8ec0958a700964be88a2b00242": {
                "Name": "test_nginx",
                "EndpointID": "fe81ff15f9541151e5954113f16f44bd9b31d55abf53707a08d9641fb3eaee51",
                "MacAddress": "02:42:0a:00:02:02",
                "IPv4Address": "10.0.2.2/24",
                "IPv6Address": ""
            }
        },
        "Options": {}
    }
]
```

I know for a fact that I've done this kind of thing in the past (in a test environment), and I cannot for the life of me seem to figure out why it doesn't work anymore. The only thing I can think of is that maybe the `cluster-advertise eth0:2376` engine opt is not working correctly (does it work the same way it used to? does it accept `eth0` as a valid option anymore?).

Sorry if this is the wrong place to put this issue, I wasn't too sure where to put it.

**Comment by jacobmarshall** [comment]
I've put the script I used to setup the swarm, [here](https://gist.github.com/jacobmarshall/f8641081fd0c2caa179b).

**Comment by dongluochen** [comment]
@jacobmarshall Have you validated your ACL setting on your subnet? The following ports need to be open. 
```
Protocol	Port	Description
udp	4789	Data plane (VXLAN)
tcp/udp	7946	Control plane
```

**Comment by jacobmarshall** [comment]
I've not touched them. I assume the defaults are correct? This is a newly setup VPC.

<img width="770" alt="screenshot 2016-02-14 20 12 39" src="https://cloud.githubusercontent.com/assets/4710291/13032433/85473906-d357-11e5-9f13-641b446940eb.png">

**Comment by dongluochen** [comment]
Can you run some tests? From machine 1 `telnet $(machine 2 IP) 7946`. If port is accessible it should be able to connect, otherwise you see "no route to host".

**Comment by jacobmarshall** [comment]
Yep, absolutely no problem. I originally opened up all ports when I noticed the issue, incase that was the issue.

<img width="407" alt="screenshot 2016-02-14 20 31 17" src="https://cloud.githubusercontent.com/assets/4710291/13032522/9f3d4f78-d35a-11e5-9b0b-a8dc43043185.png">

**Comment by dongluochen** [comment]
Can you login to the agent machine and check the daemon process with `ps -ef | grep -i docker` to see if it's running with the right options? I'm also not sure if `cluster-advertise eth0:2376` is translated correctly. The daemon process should show the right IP. From (https://docs.docker.com/engine/userguide/networking/get-started-overlay/) it uses the different syntax. 

```
    --swarm-discovery="consul://$(docker-machine ip mh-keystore):8500" \
    --engine-opt="cluster-store=consul://$(docker-machine ip mh-keystore):8500" \
    --engine-opt="cluster-advertise=eth1:2376" \
```

You may also restart docker daemon manually on the agent machines with debug option `docker daemon -D ...`. The 2 agent nodes should discovery each other in the debug logs.

**Comment by jacobmarshall** [comment]
> The daemon process should show the right IP

Should that IP be the public or private IP for that node? Right now it's not translated to anything. But setting it to be the public IP for that node yields the following error in the daemon debug logs...

```
ERRO[0000] Multi-Host overlay networking requires cluster-advertise([REDACTED]) to be configured with a local ip-address that is reachable within the cluster
ERRO[0000] initializing serf instance failed: failed to create cluster node: Failed to start TCP listener. Err: listen tcp [REDACTED]:7946: bind: cannot assign requested address
```

**Comment by dongluochen** [comment]
It should be the private IP of the node. The public IP is not a logical IP on the node's interfaces.

**Comment by jacobmarshall** [comment]
Interestingly, it would seem that deploying the same cluster on DigitalOcean works. If all ports are open for all nodes in the VPC, what else could this mean?

My test was...

```
$ docker network create test
$ docker run -itd --env "constraint:node==mnc-a1" --name test_nginx --net test nginx
$ docker run -it --rm --env "constraint:node==mnc-a2" --net test busybox wget -qO- http://test_nginx

<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

The setup script I used was...

```
docker-machine create -d digitalocean \
  --digitalocean-access-token "$DO_TOKEN" \
  --digitalocean-image "ubuntu-15-10-x64" \
  --digitalocean-region "nyc3" \
  --digitalocean-size "512mb" \
    mnc

master_ip=$(docker-machine ip mnc)

eval $(docker-machine env mnc)

docker network create swarm

docker run -d -p 8500:8500 --net=swarm --restart=unless-stopped --name=consul \
  progrium/consul -server -bootstrap

docker run -d -p 3376:3376 --net=swarm --restart=unless-stopped --name=swarm -t -v /etc/docker:/etc/docker:ro \
  swarm manage -H 0.0.0.0:3376 --tlsverify --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server.pem --tlskey=/etc/docker/server-key.pem consul://consul:8500

docker-machine create -d digitalocean \
  --digitalocean-access-token "$DO_TOKEN" \
  --digitalocean-image "ubuntu-15-10-x64" \
  --digitalocean-region "nyc3" \
  --digitalocean-size "1gb" \
  --engine-opt "cluster-store consul://$master_ip:8500" \
  --engine-opt "cluster-advertise eth0:2376" \
    mnc-a1

docker $(docker-machine config mnc-a1) run -d --restart=unless-stopped --name=swarm \
  swarm join --advertise=$(docker-machine ip mnc-a1):2376 consul://$master_ip:8500

docker-machine create -d digitalocean \
  --digitalocean-access-token "$DO_TOKEN" \
  --digitalocean-image "ubuntu-15-10-x64" \
  --digitalocean-region "sfo1" \
  --digitalocean-size "1gb" \
  --engine-opt "cluster-store consul://$master_ip:8500" \
  --engine-opt "cluster-advertise eth0:2376" \
    mnc-a2
```

The only difference being the fact the agents connect to the consul server using the master node's public IP. I wouldn't suspect that would have anything to do with it though.

**Comment by mavenugo** [comment]
@jacobmarshall which distro are you trying the scenario in AWS ? If it is with a kernel < 3.16 (such as ubuntu 14.04), then it could be the overlapping/conflicting route (to 10.x.x.x/y subnet) between the overlay network and the network managed by AWS. If that is the case, then pls use the `--subnet` option in `docker network create` command and use a subnet that doesn't overlap with the underlying platform.
`docker network create --subnet=40.1.0.0/16 swarm`.

**Comment by jacobmarshall** [comment]
Hey @mavenugo, I'm using the default EC2 AMI for docker, which as according to https://docs.docker.com/machine/drivers/aws/#default-amis is Ubuntu 15.10 LTS (ami-26d5af4c).

The subnet for the VPC is 192.168.33.0/x, I originally tried with 10.0.0.0/x but changed it when I ran into this issue originally, as I had the same thought.

I don't have access to the computer I set this all up with right now, so I'll try that and see if it makes a difference anyway, later on today.

**Comment by jacobmarshall** [comment]
Hey @mavenugo, sorry about the delay. That did not work either.

<img width="1022" alt="screenshot 2016-02-16 20 58 59" src="https://cloud.githubusercontent.com/assets/4710291/13070283/347bde10-d4f0-11e5-9328-bd8e8804e9b9.png">

I will rebuild the cluster, again, for the 4th (ish) time, and see whether or not everything is working. I'll make sure that all ports are open right from the get-go, as far as I can tell, that's the only difference (minus the fact the VM image on DO & AWS is obviously different).

**Comment by jacobmarshall** [comment]
So I did some testing. I rebuilt the cluster with all ports exposed for all nodes.

Everything worked.

See here...

```
$ docker run -itd --name=nginx --net=test nginx
ea902d5cb1992b0b2fc6efcaf0012549f5a17fa9327d6615e90c3c07a5538354
$ docker run --rm --net=test busybox wget -qO- http://nginx
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
(etc...)
```

So then I only allowed 2376, 22 for all nodes, and an additional 3376, 8500 for the master (swarm & consul).

I got the following error...

```
$ docker run --rm --net=test busybox wget -qO- http://nginx
docker: Error response from daemon: Post https://[agent3-public-ip]:2376/v1.15/containers/create: read tcp 172.18.0.3:56516->[agent3-public-ip]:2376: read: connection timed out.
```

Anyways, so then I tried adding the additional ports (vxlan etc...) as mentioned by @dongluochen in https://github.com/docker/swarm/issues/1814#issuecomment-183839143.

But I got the following error...

```
$ docker run --rm --net=test busybox wget -qO- http://nginx
docker: Error response from daemon: Post https://[agent3-public-ip]:2376/v1.15/containers/create: read tcp 172.18.0.3:56516->[agent3-public-ip]:2376: read: connection timed out.
```

I really don't want to be exposing all ports if they're not necessary, as you can probably understand. But I just can't see why this would be happening. As far as I can tell I'm exposing all the necessary ports for docker + multi-host networking.

**Comment by jacobmarshall** [comment]
Just as a side note, `nginx` was running on agent1, I assume swarm was attempting to run the busybox container on agent3.

**Comment by mavenugo** [comment]
@jacobmarshall can you pls confirm all the ports (& corresponding protocols) thats currently opened ?
Pls refer to https://docs.docker.com/engine/userguide/networking/dockernetworks/#an-overlay-network and confirm if protocol UDP is opened for 4789 & 7946.

**Comment by jacobmarshall** [comment]
My bad, I didn't realise that the VXLAN & Control plane were intended to be exposed on the master node as well. That was the issue. Thanks a bunch for your help @mavenugo.

**Comment by pilgrim2go** [comment]
I have the same issue.
I see all the ports are opening (4789 & 7986) in agent hosts.
but only 7986 open in master.

Is it an issue?
If yes, how to open port 4789 in master ( i see port 4789 is open only if we start container).

Besides, I find port 4789 is not reachable ( I might be wrong)
```
[ec2-user@node1 ~]$ nc -z -v  10.x.x.x 4789-4789
nc: connect to 10.x.x.x port 4789 (tcp) failed: Connection refused
[ec2-user@node1 ~]$ nc -z -v  10.x.x.x 7946-7946
Connection to 10.x.x.x 7946 port [tcp/*] succeeded!
```
Is there any way to check both ports are reachable?

**Comment by pilgrim2go** [comment]
Hi @mavenugo : I have the same issue but can't make it work
Here my test
Make sure ports are  open
```
[ec2-user@ip-192-168-0-87 ~]$ nc -z -v -u 192.168.1.246 4789
Connection to 192.168.1.246 4789 port [udp/*] succeeded!
[ec2-user@ip-192-168-0-87 ~]$ nc -z -v -u 192.168.1.246 7946
Connection to 192.168.1.246 7946 port [udp/*] succeeded!
```
and
```
[ec2-user@ip-192-168-1-246 ~]$ nc -z -v -u 192.168.0.87 4789
Connection to 192.168.0.87 4789 port [udp/*] succeeded!
[ec2-user@ip-192-168-1-246 ~]$ nc -z -v -u 192.168.0.87 7946
Connection to 192.168.0.87 7946 port [udp/*] succeeded!
```
ip-192-168-0-87 and ip-192-168-1-246 are my agent nodes.

Create overlay network
```
 docker network create --driver overlay --subnet=40.0.9.0/24 my-net2
```
add nginx 
```
docker run -itd --name=web --net=my-net2 --env="constraint:node==ip-192-168-0-87" nginx
```
but not able to ping web
```
 docker run -it --rm --net=my-net2 --env="constraint:node==ip-192-168-1-246" busybox wget -O- http://web
Connecting to web (40.0.9.2:80)
wget: can't connect to remote host (40.0.9.2): No route to host
```

Docker version
```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:13:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/1.2.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   eaa53c7
 Built:        Fri May 27 17:25:03 UTC 2016
 OS/Arch:      linux/amd64
```

**Comment by nicolaka** [comment]
@pilgrim2go I replied to your other comment on #2161 . Please ensure ports udp/4789 and udp+tcp/7946 are open in both directions. Also ensure that cluster-advertise / cluster-store setting is configured correctly ( check `docker info`).

**Comment by pilgrim2go** [comment]
@nicolaka : 
See my results to see both ports are reachable in both directions.
cluster-advertisse/cluster-store are propertly configured because I can create overlay network , right?
Docker info shows agent connected.
Fyi, I'm using https://github.com/andypowe11/AWS-Docker-Swarm-with-Consul to setup my cluster.
With some more actions:
+ Add cluster-advertisse/cluster-store in /etc/sysconfig/docker
```
            "myip=`curl http://169.254.169.254/latest/meta-data/local-ipv4`\n",

            "echo \"OPTIONS=\\\"-D -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 --cluster-advertise ${myip}:2375 --cluster-store consul://consul0:8500 \\\"\" > /etc/sysconfig/docker\n",

```
+ Allow all traffic within cluster.

I have one example working in AWS but using Centos.
I'm doubting if  Amazon Linux has some issues ( + Ubuntu also)

**Comment by mkingbe** [comment]
Did you reach a conclusion as I think I have same issue?
2 nodes in aws, one master and one worker.
if I put 2 services on worker it can reach each other, if I move one of the to the manager, it cannot be reached from the worker.

I have all traffic open on worker and manager (in and out).
