### ISSUE TITLE
swarm manage can's TLS handshake with docker 

### ISSUE THREAD

**Issue by woshihaoren** [docker/swarm#1815]
Hi:
   I run docker with -H tcp://0.0.0.0:2376 --tlsverify --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server-cert.pem --tlskey=/etc/docker/server-key.pem,then run swarm manage and agent,But /var/log/message has error: 

###
Feb 14 17:07:29 docker-33-107 docker: 2016/02/14 17:07:29 http: TLS handshake error from 172.17.0.4:38609: remote error: bad certificate

And docker -H ip:3376 --tlsverify info , All nodes is unknown.

How to configure swarm mangae certificate with docker communication

I use --debug run swarm manage, see this log
time="2016-02-14T09:35:35Z" level=debug msg="Failed to validate pending node: Get https://10.255.33.102:2376/v1.15/info: x509: cannot validate certificate for 10.255.33.102 because it doesn't contain any IP SANs" Addr="10.255.33.102:2376

I create server-cert.pem common name is test-docker.aaa.com,and I try common name is *, but useless,must specify domain

**Comment by rain1024** [comment]
@woshihaoren, how do you pass this issue, I meet this issue too

**Comment by danielbjornadal** [comment]
Me to. 
`http: TLS handshake error from 172.17.0.4:45653: remote error: bad certificate`

Certificate is valid if I use CURL to talk to the api.
(/etc/hosts contain the valid FQDN of the certificate)

Something wrong with the --tlsvalidate flag when running the `run swarm manage` 
Could this be that the swarm manage cant validate the FQDN set when generating the certificate request ? 

To make it work, run the swarm manage with --tls and not --tlsverify
(this will make it vulnerable to man-in-the-middle attack)

**Comment by woshihaoren** [comment]
@rain1024  @danielbjornadal 
Yeah, I pass it.
first, you should use hostname 
then, make a certificate, CN=*.xxx.com

example:
hostname: docker01.xxx.com

openssl req -subj '/CN=*.xxx.com' -new -key server.key -out server-req.csr -days 3650

swarm-agent use hostname register
docker run -d --name swarm-agent swarm:1.1.2 join --addr=$(hostname-f):2376

**Comment by rain1024** [comment]
thank you @woshihaoren
