### ISSUE TITLE
Swarm fails to find an image that is present using docker 1.10

### ISSUE THREAD

**Issue by hackndoes** [docker/swarm#1816]
I am using docker 1.10 and latest swarm release (14/02/2016) with docker-machine.
building an image on swarm (pointing to the swarm manager) successfully creates an  image.
docker images | grep <image_id> 
shows the image in the list but:

docker tag <image_id> <tag_name> fails with error:
Error response from daemon: No such image: <image_id>

to recreate simply start a swarm on docker-machine (node and manager on same machine)
build a simple container on the swarm (pointing to the manager)
that try to tag the created image.

**Comment by jimmyxian** [comment]
@hackndoes Thanks for reporting this. But I can't reproduce. Can you provide the command you use.

**Comment by auzias** [comment]
What outcome are you expecting from a `swarm build` ?

Swarm build should actually not build anything, and IMHO, should even refuse to do so. [Here is an explanation why -- scroll up for another explanation](https://github.com/docker/swarm/issues/1783#issuecomment-184600268).

**Comment by hackndoes** [comment]
nothing like swarm build was mentioned. 
what I meant was running docker build against the swarm manager.
it seems like everything is working in 1.10.2 so problem solved somehow. 
thanks.
