### ISSUE TITLE
Request: Quarantine a node

### ISSUE THREAD

**Issue by Spritekin** [docker/swarm#1818]
Hi,

I'm using Swarm 1.1.0 with binpack scheduler on a mesos cluster 0.26. 

We are running lots and lots of jobs so the 20 nodes we have are full. Now I would like to isolate a node so the current running jobs finish but no more offers are accepted from (and no more jobs are sent to) this node. The objective is to shutdown the node and start a new node with a new setup.

I would like to have a quarantine command so I can do "docker quarantine IP" and swarm will stop receiving offers from that node.

Is that acceptable?

Luck!
Guimo

**Comment by gradywang** [comment]
@Spritekin, I think if you do not want Swarm to receive some offers from some specified node, you can try the dynamic reservation feature on Mesos. Currently, Swarm only support to register Mesos with the default role (*), so you can dynamic reserve all resources (cpus and mems) on that specified node to some other Mesos role, then Swarm will no get offers from that node.

**Comment by dongluochen** [comment]
A hack from @aluzzardi is documented in #1508.

**Comment by nishanttotla** [comment]
Closing due to https://github.com/docker/swarm/pull/2853
