### ISSUE TITLE
Reserved resources show incorrect in docker info command

### ISSUE THREAD

**Issue by gradywang** [docker/swarm#1819]
I build the swarm binary with the latest code to create my swarm cluster, and I find that the reserved resources alway show 0 in docker info command when I create container without `-m` and `--cup-shares` flag.

Steps to reproduce:

Step1: Create container without `-m` and `--cup-shares` flag.
$ docker -H gradyhost2.eng.platformlab.ibm.com:2375 run -d  ubuntu:14.04 sleep 2000

Step1: Check the reserved resources with docker info command:
$ docker -H gradyhost1.eng.platformlab.ibm.com:2375 info
Containers: 1
Images: 13
Server Version: swarm/1.1.0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 gradyhost2.eng.platformlab.ibm.com: gradyhost2.eng.platformlab.ibm.com:2375
  └ Status: Healthy
  └ Containers: **1**
  └ Reserved CPUs: **0 / 2**
  └ Reserved Memory: **0 B / 4.044 GiB**
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-32-generic, operatingsystem=Ubuntu 14.04.1 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-02-16T09:42:37Z
 gradyhost3.eng.platformlab.ibm.com: gradyhost3.eng.platformlab.ibm.com:2375
  └ Status: Healthy
  └ Containers: 0
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.044 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-32-generic, operatingsystem=Ubuntu 14.04.1 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-02-16T09:42:06Z
Kernel Version: 3.13.0-32-generic
Operating System: linux
CPUs: 4
Total Memory: 8.088 GiB
Name: gradyhost1.eng.platformlab.ibm.com

My environment information as below:
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

$ docker -H gradyhost1.eng.platformlab.ibm.com:2375 info
Containers: 2
Images: 13
Server Version: swarm/1.1.0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 gradyhost2.eng.platformlab.ibm.com: gradyhost2.eng.platformlab.ibm.com:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.044 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-32-generic, operatingsystem=Ubuntu 14.04.1 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-02-16T09:42:37Z
 gradyhost3.eng.platformlab.ibm.com: gradyhost3.eng.platformlab.ibm.com:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.044 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-32-generic, operatingsystem=Ubuntu 14.04.1 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-02-16T09:42:06Z
Kernel Version: 3.13.0-32-generic
Operating System: linux
CPUs: 4
Total Memory: 8.088 GiB
Name: gradyhost1.eng.platformlab.ibm.com

**Comment by gradywang** [comment]
In addition, can some guys tell me how to assign a swarm bug to myself.

**Comment by dongluochen** [comment]
@gradywang Today swarm uses `Reserved` CPU/Memory to estimate the load on each node. The reserved CPU/memory is specified by configuration from `-m` and `--cpu-shares`, etc. They are not the real consumption of CPU/memory on the node. That's the reason you see 0 in reserved CPU/memory. If users do not specify reserved resource, node resource reservation are all 0s. (Swarm does a trick to use container count to break tie between nodes.)

An alternative to this is to use `real` CPU/memory consumption as metrics to schedule containers. And keep reserved CPU/memory as constraints to prevent overcommit. It'd require utilization data collection from daemons. 

I don't know history of this problem so I'd wait for others' comments.

**Comment by dvenza** [comment]
This issue is interesting also because not all of the memory installed on the system is actually available to docker/swarm.

There are (at least) operating system processes running along docker, they use up some memory and need some headroom, so when docker says that I have the full amount of RAM available for reservation, it is telling a lie, because if I try to reserve and use all that memory something will break somewhere.

**Comment by dongluochen** [comment]
@dvenza Swarm gets node CPU/memory information from docker daemon running on each node. Docker daemon doesn't limit its resource, i.e., it considers all resources can be used.  

Swarm allows `overcommit` on resource, that is, you can reserve more or less memory/CPU from docker daemon. By default swarm has overcommit = 0.05 which means it can reserve 1.05GB memory if the daemon has 1GB memory. You can change it to negative, e.g. `--cluster-opt swarm.overcommit=-0.2`, then swarm would only allow reservation up to 0.8GB. This works when you use reservation consistently. 
```
[ec2-user@ip-172-19-182-118 ~]$ ./swarm manage --help | grep -i overcommit -B 1
   --cluster-opt [--cluster-opt option --cluster-opt option]		cluster driver options
   									 * swarm.overcommit=0.05		overcommit to apply on resources
```

**Comment by gradywang** [comment]
In addition, I find docker/swarm changed the semantics of `--cpu-shares` parameter of docker run. For docker only, it is a relative weight, but in swarm, it uses it as the real cpu numbers.  

@dongluochen, I think we need to document it for this change, do you think so?

**Comment by dongluochen** [comment]
@gradywang I missed your message last month. It's tracked by #475.

**Comment by dongluochen** [comment]
@gradywang @dvenza I think we can close this issue.
