### ISSUE TITLE
[1.1.1 Regression] Containers are not attached to networks with Compose

### ISSUE THREAD

**Issue by oiavorskyi** [docker/swarm#1840]
I have first opened this issue against Docker Compose but after the investigation it looks like the problem was caused by changes in Swarm 1.1.1. Please take a look at the [original issue](https://github.com/docker/compose/issues/2949) for the details on how to reproduce.

**Comment by nathanleclaire** [comment]
Using Swarm master I see in the logs:

```
Feb 18 18:51:38 ip-10-0-1-151 sh[1354]: time="2016-02-18T18:51:38Z" level=error msg="HTTP error: No such network: 2949_another_network" status=404
Feb 18 18:51:38 ip-10-0-1-151 sh[1354]: time="2016-02-18T18:51:38Z" level=error msg="HTTP error: No such network: 2949_test_network" status=404
```

**Comment by nishanttotla** [comment]
@oiavorskyi We just released 1.1.2 which should fix the breaking change. Can you try that please?

**Comment by oiavorskyi** [comment]
@nishanttotla I have tried with 1.1.2 and could confirm that behavior is back to normal. Thank you for the prompt response.

**Comment by oiavorskyi** [comment]
Closing the defect as fixed.
