### ISSUE TITLE
Proposal: Swarm support the rescind offer operation from Mesos

### ISSUE THREAD

**Issue by gradywang** [docker/swarm#1860]
Currently, Swarm does not implement the interface of `OfferRescinded` in scheduler, propose to implement it to avoid to schedule the create container request to the invalid offer to improve the performance of swarm+mesos.

**Comment by gradywang** [comment]
@nishanttotla ， cloud you help to assign this enhancement to me? or can you tell me how to assign an existing issue to myself?

**Comment by gradywang** [comment]
#dibs

**Comment by gradywang** [comment]
#1866

**Comment by nishanttotla** [comment]
Closing due to https://github.com/docker/swarm/pull/2853
