### ISSUE TITLE
Proposal: DOCKER INFO should show nodes information in Swarm + Mesos

### ISSUE THREAD

**Issue by gradywang** [docker/swarm#1884]
Currently, when Swarm run on Mesos, `docker info` command shows as below:

```
# docker -H swarmmanager.wyq.com:2375 info
Containers: 0
Images: 14
Server Version: swarm/1.1.2
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Offers: 2
  Offer: 577c74a2-c422-4a66-8c35-76a077b96090-O2
   └ cpus: 2
   └ mem: 2.851 GiB
   └ disk: 29.79 GiB
   └ ports: 31000-32000
  Offer: 577c74a2-c422-4a66-8c35-76a077b96090-O3
   └ cpus: 2
   └ mem: 2.851 GiB
   └ disk: 29.79 GiB
   └ ports: 31000-32000
Kernel Version: 3.13.0-32-generic
Operating System: linux
CPUs: 4
Total Memory: 5.701 GiB
Name: swarmmanager.wyq.com
```

I think we should show nodes information rather than offer information, because the filter and strategy of swarm are worked on nodes information. actually, end user does not care about the resources information in each offer, s/he only care about the total resources on each node, because a container can be created with multiple offers on a node.

In addition, the labels of engine can also be easily show when show nodes information in docker info, then end user can use those labels for Swarm strategy and filters.

**Comment by gradywang** [comment]
According to the proposal, the output of DOCKER INFO will be enhanced to:

```
# docker -H gradyhost1.eng.platformlab.ibm.com:2375 info
Containers: 3
Images: 9
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 gradyhost3.eng.platformlab.ibm.com: gradyhost3.eng.platformlab.ibm.com:2375
  └ Status: Healthy
  └ Containers: 2
  └ Offers: 2
  └ Used CPUs: 2 / 2  
  └ Used Memory: 2.0 GiB / 4.044 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-32-generic, operatingsystem=Ubuntu 14.04.1 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-01-23T03:55:04Z
 gradyhost4.eng.platformlab.ibm.com: gradyhost4.eng.platformlab.ibm.com:2375
  └ Status: Healthy
  └ Containers: 1
  └ Offers: 1
  └ Used CPUs: 1 / 2
  └ Used Memory: 1.0 GiB / 4.044 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-32-generic, operatingsystem=Ubuntu 14.04.1 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-01-23T03:55:22Z
CPUs: 4
Total Memory: 8.088 GiB
Name: gradyhost1.eng.platformlab.ibm.com
```
Note: In above output,  the used resources are using for the current contains on that node, total resources = used + free (plus all offers on that node.)

@jimenez , cloud you help to review this proposal, if you have some comments, let me know, Thanks!

**Comment by nishanttotla** [comment]
Closing due to https://github.com/docker/swarm/pull/2853
