### ISSUE TITLE
Proposal: Support revive offer to improve Swarm + Mesos performance

### ISSUE THREAD

**Issue by gradywang** [docker/swarm#1888]
Currently, in Swarm + Mesos, if there are no sufficient resources in Swarm to create container, then Swarm will save this task in a pending tasks queue to wait receive offers from Mesos. In order to improve the performance for creating container in Swarm + Mesos, I propose to revive offers from Mesos if resources are not enough to create a container.

**Comment by nishanttotla** [comment]
Closing due to https://github.com/docker/swarm/pull/2853
