### ISSUE TITLE
Proposal: Swarm support to register Mesos with a specified Mesos role

### ISSUE THREAD

**Issue by gradywang** [docker/swarm#1889]
Currently, Swarm register Mesos with the default Mesos role "*", proposal to introduce a new cluster option and a new environment variable for Swarm on Mesos to specify a Mesos role to register. Then it can use Mesos static/dynamic reservation, create volume, quota features to reserve some resources to Swarm framework.

**Comment by gradywang** [comment]
#1890

**Comment by gradywang** [comment]
@jimenez , cloud you help to review this proposal and patch, if you have some comments, let me know. Thanks!

**Comment by akamalov** [comment]
Does Swarm currently support framework authentication against Mesos (i.e., MESOS_AUTHENTICATION_PRINCIPAL, MESOS_AUTHENTICATION_SECRET_FILE, etc) ?

Thanks,

Alex

**Comment by gradywang** [comment]
@akamalov , It does not support now.

**Comment by akamalov** [comment]
@gradywang Bummer...Can we propose/request for enhancement ?

**Comment by gradywang** [comment]
@akamalov, yes, I have logged a new issue for this proposal.

**Comment by nishanttotla** [comment]
Closing due to https://github.com/docker/swarm/pull/2853
