### ISSUE TITLE
swarm join with IPv6 not supported?

### ISSUE THREAD

**Issue by joes** [docker/swarm#1906]
Hi,

It seems I am not able to to set the advertise option to the docker host's IPv6 address:

```
docker run --name swarm_agent -d swarm join --advertise=[2001:db8:85a3::8a2e:370:7334]:2375 consul://[2001:db8:85a3:d0c:1::2]:8500
docker logs swarm_agent
time="2016-02-29T13:22:15Z" level=fatal msg="--advertise should be of the form ip:port or hostname:port"
```

However, the discovery backend's URI is accepted if I use an IPv6 address.

**Comment by dongluochen** [comment]
There are some issues with IPv6 address handling in swarm. I'll look into it.

**Comment by joes** [comment]
Thank you for the great work! Is there an upcoming release that includes this fix?

**Comment by nishanttotla** [comment]
@joes I think the 1.2 release will include the fix that supports IPv6. This should happen in about a month's time. If you're interested in using it now, you can build from the master branch.
