### ISSUE TITLE
./test/integration/run.sh does not show the tests results.

### ISSUE THREAD

**Issue by gradywang** [docker/swarm#1911]
When I following the steps in CONTRIBUTING.md to run the integration tests with command `./test/integration/run.sh` after changing some source code, the results show as following:

```
# ./test/integration/run.sh
Using default tag: latest
latest: Pulling from dockerswarm/swarm-test-env
Digest: sha256:2ad61a065f185853d6c3e5ec98a8fc42f7cd4fab8f1ef575753fc874c184d2f0
Status: Image is up to date for dockerswarm/swarm-test-env:latest
++ time curl -L --silent https://github.com/docker/compose/releases/download/1.6.2/docker-compose-Linux-x86_64
```

Actually some tests execution failed，but it does not show the results and the detailed stacks. I will to enhance this doc to make it clearly. If some guys have some good suggestions, you can append them here.

**Comment by nishanttotla** [comment]
To show results, print statements can be added to the failing tests.

For example
`echo "PRINTING $output"`
