### ISSUE TITLE
Force pull of base image on build doesn't work with swarm

### ISSUE THREAD

**Issue by garagatyi** [docker/swarm#1912]
I tried to set pull parameter of POST /build.
It works with plain docker, but it doesn't over swarm. 
Here example that shows how to reproduce (take a look at logs - swarm doesn't pull):
$ ps ax | grep docker
 6856 ?        Sl     0:59 /usr/local/docker-distribution/bin/registry /usr/local/docker-distribution/config.yml
16718 ?        Ssl   25:30 /usr/bin/docker daemon --selinux-enabled=false -g /var/lib/docker --insecure-registry dev.box.com:5000 --storage-opt dm.basesize=10G -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock
29042 pts/1    S+     0:00 grep --color=auto docker
$ ps ax | grep swarm
16888 ?        Sl     3:21 /usr/local/swarm/bin/swarm manage -H 0.0.0.0:23750 file:///usr/local/swarm/node_list
29044 pts/1    S+     0:00 grep --color=auto swarm
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Package Version: docker-1.8.2-7.el7.centos.x86_64
 Go version:   go1.4.2
 Git commit:   bb472f0/1.8.2
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Package Version:
 Go version:   go1.4.2
 Git commit:   bb472f0/1.8.2
 Built:
 OS/Arch:      linux/amd64
$ /usr/local/swarm/bin/swarm --version
swarm version 1.1.0 (a0fd82b)
$ docker -H tcp://127.0.0.1:2375 build --pull=true https://gist.githubusercontent.com/garagatyi/3832875bcdd4e6d12595/raw/fd56243b219d9a45541038d74f8c8092543aa128/Dockerfile
Downloading build context from remote url: https://gist.githubusercontent.com/garagatyi/3832875bcdd4e6d12595/raw/fd56243b219d9a45541038d74f8c8092543aa128/Dockerfile [==================================================>]     26 B/26 B^MDownloading build context from remote url: https://gist.githubusercontent.com/garagatyi/3832875bcdd4e6d12595/raw/fd56243b219d9a45541038d74f8c8092543aa128/Dockerfile [==================================================>]     26 B/26 B^MDownloading build context from remote url: https://gist.githubusercontent.com/garagatyi/3832875bcdd4e6d12595/raw/fd56243b219d9a45541038d74f8c8092543aa128/Dockerfile [==================================================>]     26 B/26 B^M
Sending build context to Docker daemon 2.048 kB^MSending build context to Docker daemon 2.048 kB^M
Step 0 : FROM codenvy/ubuntu_jdk8
Trying to pull repository docker.io/codenvy/ubuntu_jdk8 ... latest: Pulling from codenvy/ubuntu_jdk8
8aa2fc7185e2: Already exists
13a8e55f2d20: Already exists
1b1999356dda: Already exists
1997914a7c23: Already exists
daaae9518bd5: Already exists
2373d93f42cf: Already exists
1d46850458bb: Already exists
3afbdd3c3613: Already exists
bb34f2071a58: Already exists
185a08c3afc8: Already exists
f4ed149c6eb0: Already exists
a85a48824758: Already exists
e1b8eed1cb6a: Already exists
65f487a6ecdb: Already exists
f1f386ca0771: Already exists
36530d292ed5: Already exists
be861a783da1: Already exists
9dc2888179a5: Already exists
a2a0e9bc7c8b: Already exists
3857c6ef0926: Already exists
7ed0ef1952ca: Already exists
6a3af614386b: Already exists
60f6a4243648: Already exists
Digest: sha256:db6503947c5c8d074f0deb723b19b7a7399ccf5b0e37b92a312110d58cbba031
Status: Image is up to date for docker.io/codenvy/ubuntu_jdk8:latest

 ---> 60f6a4243648
Successfully built 60f6a4243648
$ docker -H tcp://127.0.0.1:23750 build --pull=true https://gist.githubusercontent.com/garagatyi/3832875bcdd4e6d12595/raw/fd56243b219d9a45541038d74f8c8092543aa128/Dockerfile
Downloading build context from remote url: https://gist.githubusercontent.com/garagatyi/3832875bcdd4e6d12595/raw/fd56243b219d9a45541038d74f8c8092543aa128/Dockerfile [==================================================>]     26 B/26 B^MDownloading build context from remote url: https://gist.githubusercontent.com/garagatyi/3832875bcdd4e6d12595/raw/fd56243b219d9a45541038d74f8c8092543aa128/Dockerfile [==================================================>]     26 B/26 B^MDownloading build context from remote url: https://gist.githubusercontent.com/garagatyi/3832875bcdd4e6d12595/raw/fd56243b219d9a45541038d74f8c8092543aa128/Dockerfile [==================================================>]     26 B/26 B^M
Sending build context to Docker daemon 2.048 kB^MSending build context to Docker daemon 2.048 kB^M
Step 0 : FROM codenvy/ubuntu_jdk8
 ---> 60f6a4243648
Successfully built 60f6a4243648

**Comment by garagatyi** [comment]
I don't know if this is useful but command that uses plain docker is logged as
`Mar 01 18:18:39 dev.box.com docker[16718]: time="2016-03-01T18:18:39.045324355Z" level=info msg="POST /v1.20/build?cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&pull=1&rm=1&t=&ulimits=null"`
whereas command through swarm is logged as
`Mar 01 18:19:43 dev.box.com docker[16718]: time="2016-03-01T18:19:43.275131098Z" level=info msg="POST /v1.15/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&pull=1&rm=1"`

So version of APIs differ.

**Comment by garagatyi** [comment]
Ok in accordance with [build in Docker API v1.15](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.15/#build-an-image-from-dockerfile-via-stdin) there is no such parameter as pull.
Looks like swarm uses v1.15 client of docker https://github.com/docker/swarm/blob/master/Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go#L20
Is it possible to upgrade docker client in swarm instead of building swarm manually?

**Comment by garagatyi** [comment]
@vieux @aluzzardi WDYT?

**Comment by garagatyi** [comment]
@thaJeztah Hi! Can you review this issue and ping vieux and aluzzardi

**Comment by riuvshin** [comment]
Hi @vieux I wonder does that change in latest 1.2.0 version 
- Select apiClient version according to node docker version

should fix that issue?

**Comment by garagatyi** [comment]
We have updated swarm and now everything is OK
