### ISSUE TITLE
Race condition when allocating a port on all nodes of the cluster

### ISSUE THREAD

**Issue by jpetazzo** [docker/swarm#1914]
**What I do:**

5 nodes cluster running Swarm 1.1.2 (f947993) and Engine 1.10.2.

I reproduce the bug with Compose 1.6.2 and the following `docker-compose.yml`:

```yaml
www:
  image: nginx
  ports:
    - 8888:80
```

I do `docker-compose up -d` then `docker-compose scale www=5`.

(It has to match exactly the size of my cluster: 5 nodes → 5 containers.)

**What I expect:**

Each node starts one container, binding to port 8888.

**What I see instead:**

One container fails to start:

```
$ docker-compose scale www=5
WARNING: The "www" service specifies a port on the host. If multiple containers for this service are created on a single host, the port will clash.
Creating and starting 2 ... done
Creating and starting 3 ... error
Creating and starting 4 ... done
Creating and starting 5 ... done

ERROR: for 3  500 Internal Server Error: failed to create endpoint bug_www_3 on network bridge: Bind for 0.0.0.0:8888 failed: port is already allocated 
```

**Notes:**

- If I scale from 1 to 5, on my test cluster, the bugs appears all the time.
- If I scale directly from 0 to 5, the bugs appears *less often*.
- If I scale from anything to 4, *then* to 5, the bug doesn't appear.
- If I scale from anything to 1, 2, or 3, and then to 5, the bug appears.

**Comment by vieux** [comment]
@jpetazzo can you try with 1.1.3-rc1 (or -rc2 in a couple of hours?) we touched something that might help

**Comment by jpetazzo** [comment]
@vieux got exactly the same problem with 1.1.3-rc1:

```
Server:
 Version:      swarm/1.1.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   da37fb5
 Built:        Thu Feb 25 00:04:25 UTC 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by jpetazzo** [comment]
And for what it's worth, the Swarm manager logs have this:

```
time="2016-03-02T00:22:17Z" level=error msg="HTTP error: 500 Internal Server Error: failed to create endpoint bug_www_5 on network bridge: Bind for 0.0.0.0:8888 failed: port is already allocated\n" status=500 
```

And `docker ps -a` confirms that two containers were scheduled on the same node:

```
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                 NAMES
74c96a05dd28        nginx                         "nginx -g 'daemon off"   3 seconds ago                                                                 node3/bug_www_5
43a765b48ce8        nginx                         "nginx -g 'daemon off"   3 seconds ago       Up 2 seconds        443/tcp, 52.29.186.146:8888->80/tcp   node3/bug_www_2
47846efd42ce        nginx                         "nginx -g 'daemon off"   3 seconds ago       Up 2 seconds        443/tcp, 52.58.43.95:8888->80/tcp     node2/bug_www_1
b9f2167d3ea9        nginx                         "nginx -g 'daemon off"   3 seconds ago       Up 2 seconds        443/tcp, 52.58.50.15:8888->80/tcp     node1/bug_www_3
af63fccacadb        nginx                         "nginx -g 'daemon off"   3 seconds ago       Up 2 seconds        443/tcp, 52.58.38.206:8888->80/tcp    node4/bug_www_4
```

**Comment by jpetazzo** [comment]
Note: this is way harder to reproduce in debug mode, but after many tries, it happened again. Here is the log of the primary manager.

[node1-swarm-agent-master.log.txt](https://github.com/docker/swarm/files/154419/node1-swarm-agent-master.log.txt)

```
Server:
 Version:      swarm/1.1.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   da37fb5
 Built:        Thu Feb 25 00:04:25 UTC 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by jpetazzo** [comment]
And I reproduced it with 1.1.3-rc2.

[node1-swarm-agent-master.log.txt](https://github.com/docker/swarm/files/154443/node1-swarm-agent-master.log.txt)

```
Server:
 Version:      swarm/1.1.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   7e9c6bd
 Built:        Wed Mar  2 00:15:12 UTC 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by jpetazzo** [comment]
This seems to be gone in master: I can't reproduce it reliably. I'll close, and re-open if I see it again.
