### ISSUE TITLE
Cloudinit example

### ISSUE THREAD

**Issue by kevinsimper** [docker/swarm#192]
It could be cool to have a cloudinit example in the readme, as that would help to understand on how to use Swarm.

**Comment by vieux** [comment]
I'll add @jpetazzo in the loop

**Comment by bfirsh** [comment]
Yes! [Cloudinit is going to be used for Machine](https://github.com/docker/machine/issues/124), so this would be a great way to set up Machines with Swarm installed.

**Comment by vieux** [comment]
We know that swarm will be distributed as an official docker image, should we close this ?
