### ISSUE TITLE
Pull with @ to specify node location

### ISSUE THREAD

**Issue by chanwit** [docker/swarm#1922]
This may be a pre-proposal document trying to collect ideas in open of how should we abuse a syntax of `pull` :-)

Finding we can do `docker pull nginx@sha256:abcdef` makes me think that it's possible to adopt this syntax for pulling image to a specific node in the cluster, a lengthy discussed feature.

With the `@` tag we will be able to do something like:

`docker pull nginx@node-1`

or maybe even a bit complex constraint like:

`docker pull nginx@constraint:node==node-*`

What do you think?

/cc @docker/core-swarm-maintainers

**Comment by nishanttotla** [comment]
Quick question about the use case - if we allow this, then presumably you'd want your container to also run on the same node. Sometimes it may not be possible to do that given other constraints, does that reduce the utility of such a feature?

**Comment by thaJeztah** [comment]
Note that there's a similar proposal in docker/docker https://github.com/docker/docker/issues/19785

Can't we use the same syntax for `docker pull` as for `docker run`?

**Comment by chanwit** [comment]
@nishanttotla I think eagerly pulling a large amount of images onto a production cluster would outweigh this.

@thaJeztah yes, it will be really great if `docker pull` can adopt `-e` from `docker run`.

**Comment by thaJeztah** [comment]
@chanwit perhaps you can comment on the docker issue I linked to, and briefly describe what you think is needed for this?

No guarantees, but it would help the maintainers making a decision

**Comment by mattgiles** [comment]
One idea might be for the docker pull cli/api to support something like node constraint arguments. Swarm could then evaluate which nodes are eligible etc.

In compose, for example, it may well make sense for docker-compose up to pull all images to all eligible nodes, but it doesn't make as much sense for that pull to offend node constraints defined in the docker-compose.yml.

Believe this would also solve the more specific problem of "how to ask swarm to pull to a specific node". And would be nice to know that images are sitting ready on alternate nodes should a container need to be rescheduled etc.

**Comment by mbentley** [comment]
I agree with @mattgiles.  From a consistency standpoint with scheduling, I would think that I would like to be able to perform `docker pull` via swarm with the same constraint filters (node, labels, etc) as I can use to schedule containers.  I am not completely sure how these could be used from the standpoint of docker-compose but I imagine being able to consume constraints would be able to be passed via the `docker-compose pull` command as well.

**Comment by nishanttotla** [comment]
Ping @chanwit did you make progress with this issue?

**Comment by OferE** [comment]
+1 sounds really good

**Comment by longkt90** [comment]
:+1: to follow

**Comment by bklau** [comment]
This also very useful when one wants to  pass in AWS ECR authentication info thru the  docker.PullImage()  so that an image stored in ECR can be pulled into a specified node before a container is created:
`ecrAuth, err := getECRAuth(registryURI, registryID, stsClient, ecrClient)
	if err != nil {
		return err
	}

	repositoryURI := ecrAuth.Registry + "/" + repository

	dockerAuth := docker.AuthConfiguration{
		Username:      ecrAuth.Username,
		Password:      ecrAuth.Password,
		ServerAddress: ecrAuth.ProxyEndpoint,
	}

	// Pull Image
	if err := dockerClient.PullImage(repositoryURI, tag, dockerAuth); err != nil {
		return err
	}`


Note: Currently, Swarm doesn't  do much to alleviate this pain...
See https://github.com/awslabs/amazon-ecr-credential-helper/issues/37

**Comment by schmunk42** [comment]
Will this ever happen? 
Otherwise please close it as **wontfix** so we can think about alternatives. CC: @handcode
