### ISSUE TITLE
API: How to build an image with affinities or constraints

### ISSUE THREAD

**Issue by eric-basley** [docker/swarm#1928]
I'm using api to automatically deploy applications. Since swarm migration, frequently after the build of an image, I cannot run it because docker can't find it.

It seems that the build can be launched on any node, whereas I express constraints to run the container.

How to express constrains during the build to be sure that image will be available where I want to  run container ?

Note: 

1/ I don't want to reverse the pb and run container where on the node where image was created
2/ I dont want to push image on a repository

**Comment by chanwit** [comment]
You can use:
`docker build --build-arg constraint:node==node-2`
to basically build on `node-2` of the cluster.

**Comment by eric-basley** [comment]
Yes but how to express or reproduce  this constraint via API ?
I cannot find such attribute in API documentation !
