### ISSUE TITLE
API: Some Swarm response status codes are different from Docker response status codes

### ISSUE THREAD

**Issue by allencloud** [docker/swarm#1929]
Hi, All:

Recently I found that swarm response status codes are not completely the same as docker native api response status code. For example:

When I do a request  `POST /volumes/create`,  swarm returns a response of 200, while docker will return 201. This kind of incompatible issue exists in lots of Swarm APIs.

I think it's not so good for swarm which aims at supporting totally compatible APIs with docker.

WDYT, my friend.  I will do something to change this case.

**Comment by nishanttotla** [comment]
@allencloud thanks for reporting. It would be great if you could briefly list down all such endpoints, so that we can address them individually.

Also, we're moving to a new client for Swarm (#1879) which will also likely address some of these issues.

**Comment by allencloud** [comment]
@nishanttotla  
Actually, I am on the listing work. :）

During the list process, I found that we could better some api response status code in github.com/docker/docker as well, such as `DELETE networks` should return 204 instead of 200 in docker/docker.

[https://github.com/docker/docker/issues/20976](https://github.com/docker/docker/issues/20976)

Wish to discuss more here, as in this part swarm and docker have some difference.

**Comment by allencloud** [comment]
https://github.com/docker/docker/pull/20977
this pr has been merged into docker-master.
So delete network return a status code of 204.
