### ISSUE TITLE
Shutting down mesos nodes destabilizes the swarm manager.

### ISSUE THREAD

**Issue by Spritekin** [docker/swarm#1935]
Using: Swarm most recent code at Wed 9 March (Sydney time)
Mesos 0.27
CoreOS 899.9
Marathon 0.15.3

I was testing swarm on a 5 node mesos cluster in AWS. Swarm running under marathon scaled to two services, each service running on  its own node.

The only things running on swarm were the periodic health checks. Every minute the health check forced a hello-world command on each of the 2 swarm services.

It run flawlessly for 20 hours.

Then I decided to shutdown 3 of the nodes, leaving the 2 nodes where swarm was running up.

Then swarm became unstable, health checks failing to run, marathon was restarting again and again.  This continued for around 10 minutes, each service was restarted maybe 3 or 4 times. Than it stabilised and started running fine again.

Not sure what happened. I will retry the experiment again.

**Comment by Spritekin** [comment]
Ok so I retried the experiment. Increased 5 nodes, left it running for a while, then shut them down.
I got this messages. Seems like something is stuck trying to resolve an IP that is no longer there.
```
time="2016-03-09T02:08:57Z" level=error msg="Error monitoring events: Get http://172.31.34.228:2375/v1.15/events: read tcp 172.31.35.213:49260->172.31.34.228:2375: read: connection reset by peer" id="2YYK:DTEE:6UGO:XM57:WAW3:YN5I:T5IL:ITZY:IKRT:S2WU:SOWM:BSCQ" name=ip-172-31-34-228.aws.cmcrc.com 
time="2016-03-09T02:08:57Z" level=error msg="Error monitoring events: Get http://172.31.34.225:2375/v1.15/events: read tcp 172.31.35.213:35860->172.31.34.225:2375: read: connection reset by peer" id="5J3Q:7GL7:B6E4:6ILO:TY3X:HF3V:BKZD:6SKR:NJFX:P7O5:4HMO:CDUK" name=ip-172-31-34-225.aws.cmcrc.com 
time="2016-03-09T02:08:57Z" level=error msg="Error monitoring events: Get http://172.31.34.227:2375/v1.15/events: read tcp 172.31.35.213:34842->172.31.34.227:2375: read: connection reset by peer" id="U7P3:GC3R:LNEG:3EBG:B6D6:QRK6:PCW3:BCAC:ZGIL:W2OB:JJG4:2HJ6" name=ip-172-31-34-227.aws.cmcrc.com 
time="2016-03-09T02:09:01Z" level=error msg="Flagging engine as unhealthy. Connect failed 3 times" id="CYXQ:5B6H:EEMX:DO4U:PFAW:HFLH:TMUZ:RMGV:DOHW:JMYH:YG24:SAK2" name=ip-172-31-34-226.aws.cmcrc.com 
time="2016-03-09T02:09:01Z" level=error msg="Error monitoring events: Get http://172.31.34.226:2375/v1.15/events: read tcp 172.31.35.213:47588->172.31.34.226:2375: read: connection reset by peer" id="CYXQ:5B6H:EEMX:DO4U:PFAW:HFLH:TMUZ:RMGV:DOHW:JMYH:YG24:SAK2" name=ip-172-31-34-226.aws.cmcrc.com 
time="2016-03-09T02:09:21Z" level=error msg="Update engine specs failed: Get http://172.31.34.226:2375/v1.15/info: dial tcp 172.31.34.226:2375: i/o timeout. Are you trying to connect to a TLS-enabled daemon without TLS?" id="CYXQ:5B6H:EEMX:DO4U:PFAW:HFLH:TMUZ:RMGV:DOHW:JMYH:YG24:SAK2" name=ip-172-31-34-226.aws.cmcrc.com 
time="2016-03-09T02:10:14Z" level=error msg="Update engine specs failed: Get http://172.31.34.226:2375/v1.15/info: dial tcp 172.31.34.226:2375: getsockopt: no route to host. Are you trying to connect to a TLS-enabled daemon without TLS?" id="CYXQ:5B6H:EEMX:DO4U:PFAW:HFLH:TMUZ:RMGV:DOHW:JMYH:YG24:SAK2" name=ip-172-31-34-226.aws.cmcrc.com 
time="2016-03-09T02:11:04Z" level=error msg="Update engine specs failed: Get http://172.31.34.226:2375/v1.15/info: dial tcp 172.31.34.226:2375: getsockopt: no route to host. Are you trying to connect to a TLS-enabled daemon without TLS?" id="CYXQ:5B6H:EEMX:DO4U:PFAW:HFLH:TMUZ:RMGV:DOHW:JMYH:YG24:SAK2" name=ip-172-31-34-226.aws.cmcrc.com 
time="2016-03-09T02:11:37Z" level=error msg="Update engine specs failed: Get http://172.31.34.226:2375/v1.15/info: dial tcp 172.31.34.226:2375: getsockopt: no route to host. Are you trying to connect to a TLS-enabled daemon without TLS?" id="CYXQ:5B6H:EEMX:DO4U:PFAW:HFLH:TMUZ:RMGV:DOHW:JMYH:YG24:SAK2" name=ip-172-31-34-226.aws.cmcrc.com 
time="2016-03-09T02:12:23Z" level=error msg="Update engine specs failed: Get http://172.31.34.226:2375/v1.15/info: dial tcp 172.31.34.226:2375: getsockopt: no route to host. Are you trying to connect to a TLS-enabled daemon without TLS?" id="CYXQ:5B6H:EEMX:DO4U:PFAW:HFLH:TMUZ:RMGV:DOHW:JMYH:YG24:SAK2" name=ip-172-31-34-226.aws.cmcrc.com 
time="2016-03-09T02:13:13Z" level=error msg="Update engine specs failed: Get http://172.31.34.226:2375/v1.15/info: dial tcp 172.31.34.226:2375: getsockopt: no route to host. Are you trying to connect to a TLS-enabled daemon without TLS?" id="CYXQ:5B6H:EEMX:DO4U:PFAW:HFLH:TMUZ:RMGV:DOHW:JMYH:YG24:SAK2" name=ip-172-31-34-226.aws.cmcrc.com 
time="2016-03-09T02:13:53Z" level=error msg="Update engine specs failed: Get http://172.31.34.226:2375/v1.15/info: dial tcp 172.31.34.226:2375: getsockopt: no route to host. Are you trying to connect to a TLS-enabled daemon without TLS?" id="CYXQ:5B6H:EEMX:DO4U:PFAW:HFLH:TMUZ:RMGV:DOHW:JMYH:YG24:SAK2" name=ip-172-31-34-226.aws.cmcrc.com 
```

**Comment by Spritekin** [comment]
Marathon is a framework to manage services. Marathon will keep the tasks running in case of failure, if a node crashes, all running services are relocated to other node.

So one feature in marathon is the ability to define health checks. It is possible to do simple health checks (i.e. http:/swarm.marathon.mesos:2376/info) and Marathon will request that url in a periodic basis (i.e. every minute). If that fails a number of times then it flags the service as bad and restarts it, probably in other node.

Other type of health checks is the command checks. In this case a command is requested from the running container (swarm). In that case you can execute any command the OS supports. For me it is a curl command (I already asked to add curl as part of the distribution image here https://github.com/docker/swarm/issues/1862, its just one line and adds 2MB to the final image). In my case I run a curl command that starts hello-world. If the command takes too long to respond then its considered a strike, 3 strikes and the service will be restarted.

**Comment by Spritekin** [comment]
Ok so to answer what I see as unstable.
a. After stopping a node, swarm (that was running just doing hello-world tasks all night) started to fail all health checks forcing marathon to restart the services a few times until it got stable again. 

b. A swarm that is doing nothing suddenly starts crashing. Thats unstable.

c. When I request a container information or logs and one in 10 times it says "container does not exist" and the next time you ask it responds properly.

d. When network connections are not released finally making the server unresponsive and unreachable.

e. When it can't recover from a node being disconnected from the cluster and keeps trying to reach it.

f. If swarm restarts because mesos-master is restarted. Chronos and Marathon just keep working, cant issue jobs but they won't crash.

So I know the mesos driver is experimental, but honestly I couldn't imagine being that underdeveloped.

**Comment by nishanttotla** [comment]
Closing due to https://github.com/docker/swarm/pull/2853
