### ISSUE TITLE
Short container ID format cannot be used in affinity filter

### ISSUE THREAD

**Issue by marcosnils** [docker/swarm#1936]
When using the container ID affinity filter the full container ID needs to be specified. In contrast, when using other swarm commands, this is not required. 

It seems a bit odd to expect different behaviors when using container IDs. Per @mgoelzer this might be an issue but wanted @vieux to confirm. If this is the case I'd like to craft a fix so I can start diving into the swarm source code.

**Comment by marcosnils** [comment]
per  @mgoelzer using regex support in filters did the trick, so issuing `docker run -e affinity:container==2ab62c2*` worked. 

Same applies for image IDs. Is this the correct way to proceed?.

**Comment by mgoelzer** [comment]
Yes, it's the recommended way to proceed.  (Incidentally, it will also work for container names.)
