### ISSUE TITLE
Request: Resync jobs when mesos-master restarts

### ISSUE THREAD

**Issue by Spritekin** [docker/swarm#1939]
Hi,

When the mesos-master crashes then restarts, I can see the jobs run by marathon being resync'd with the master. They are not restarted, they are still running fine, they are just updated in the mesos list. For example, if I had an http server running for 20 hours when the master crashes, when the master restarts marathon will resync the info with the master and I will see it appear in the running jobs list. Note this jobs can be running in docker containers.

However, Swarm does not do this resync. I know the docker jobs started by swarm are still running, in fact if I do a ps, swarm will show me the running jobs. However this jobs no longer appear on the mesos master lists. For the mesos master they are not running at all.

This is highly problematic. Imagine I have a slave with 8 jobs started by swarm consuming all the resources of that slave. Previous to the crash, the mesos-master would know there are 8 jobs running in that slave so it would not accept jobs of make resource offers for that node. Suddenly the mesos master is restarted and wipes out the job list. Then it thinks in that slave there are no jobs running when in fact there are still 8 jobs running. So it starts sending offers and accepting jobs for that node which will definitely overload the node.

I leave this here, hopefully it gets done sometime.

Luck!

**Comment by nishanttotla** [comment]
Closing due to https://github.com/docker/swarm/pull/2853
