### ISSUE TITLE
memory and cpu hot-plugging support

### ISSUE THREAD

**Issue by wmark** [docker/swarm#1949]
I've started *Docker*, *etcd2*, and *Swarm* on a *amd64* machine able to receive more CPUs and memory on-the-fly (aka hot-plugging), running Linux 4.4.0. It's a swarm of one machine only.

```bash
$ lscpu | head -n 5
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23

$ docker -H 127.0.0.1:2377 info | tail -n 6
Kernel Version: 4.4.0-4-generic
Operating System: linux
Architecture: amd64
CPUs: 25
Total Memory: 16.32 GiB
Name: 562ec85caa9b
```

The »CPU«-count is obviously off by one when displaying through *swarm*, fine with *docker*.

Anyway, I've plugged in one more CPU and more memory. Both get detected and are made available by Linux correctly.

**expected**
```docker info``` (using swarm) displays more »(reservable) CPUs« and more »(reservable) memory«, and higher totals.

**currently happening**
The counters don't change.

**Comment by dongluochen** [comment]
@wmark Thanks for reporting this problem! Currently Swarm manager updates node specification when the node first join the cluster, or when the node comes back from unhealthy state. Periodic node spec update might be a little inefficient. Can you run `docker events` towards the node and check if there is specific `event` when you add/remove CPU/Mem? If there are such events, we can update spec when we detect them.

**Comment by dongluochen** [comment]
@wmark Just check docker code, it doesn't emit events. It just collects `runtime.NumCPU()` when user issues `docker info`. Swarm as an aggregator has to refresh engine spec to get the update.

**Comment by wmark** [comment]
@dongluochen Thank you for looking into this! If I understood that completely we need *Swarm* to poll periodically, and *Docker* or the *Agent* to refresh its stats. (I didn't look into it on this side.)

It will be enough if we re-read total memory and core count on signal ```syscall.SIGPWR``` on the target machine(s).

```go
signal.Notify(signalChannel, os.Interrupt, syscall.SIGPWR)
…
case syscall.SIGPWR:
    // this could be a power-loss event, or hotplugging
    runtime.NumCPU()
    …
```

**Comment by dongluochen** [comment]
@wmark Docker doesn't store CPU/Mem information. It queries them on-the-fly. Swarm doesn't get event notification from the nodes. A simple fix is to refresh node spec periodically. To reduce resource requirement, we may select a refresh interval of several minutes.

**Comment by wmark** [comment]
Or just generate an event on syscall.SIGPWR?

**Comment by dongluochen** [comment]
> Or just generate an event on syscall.SIGPWR?

I doubt Docker maintainers would agree to that.

**Comment by jimmyxian** [comment]
Fixed by: https://github.com/docker/swarm/pull/1992
