### ISSUE TITLE
How to guarantee that container is redeployed to the same machine after image update?

### ISSUE THREAD

**Issue by rjsteinert** [docker/swarm#1951]
Hi folks - I use volumes to persist data between image updates for containers. How do I guarantee that when I update a container with a new image tag that the container is deployed back to the same machine where its own data lives?
```
docker stop container-a
docker rm container-a
docker pull image-a
docker start --volume /container-a:/data --name container-a image-a:new-release
```
The above example could result in the container being deployed to a different machine thus the `/container-a` folder that the new container is using would no longer have its data from the last time it was stopped.

**Comment by dongluochen** [comment]
@rjsteinert Swarm has support for [volume dependency](https://github.com/docker/swarm/blob/master/docs/scheduler/filter.md#use-a-dependency-filter). Use `--volumes-from` to specify a volume container that you want to mount. In case you don't want to mount volume directly you can use container affinity `-e affinity:container==xxx`.

**Comment by rjsteinert** [comment]
Thanks @dongluochen. It looks like that will do the trick.
