### ISSUE TITLE
Error response from daemon: No healthy node available in the cluster.

### ISSUE THREAD

**Issue by vimalprakashts** [docker/swarm#1956]
Hi,

I followed this documentation 

https://docs.docker.com/swarm/install-manual/

I am in Step 6. Communicate with the Swarm

I try to execute this command 

docker -H :4000 run hello-world

and ti gives me this result,

docker: Error response from daemon: No healthy node available in the cluster.
See 'docker run --help'.

But my docker info says 

> docker -H :4000 info

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: swarm/1.1.3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 (unknown): xxxxx:2375
  └ Status: Pending
  └ Containers: 0
  └ Reserved CPUs: 0 / 0
  └ Reserved Memory: 0 B / 0 B
  └ Labels: 
  └ Error: Cannot connect to the docker engine endpoint
  └ UpdatedAt: 2016-03-12T22:27:32Z
 (unknown): yyyyy:2375
  └ Status: Pending
  └ Containers: 0
  └ Reserved CPUs: 0 / 0
  └ Reserved Memory: 0 B / 0 B
  └ Labels: 
  └ Error: Cannot connect to the docker engine endpoint
  └ UpdatedAt: 2016-03-12T22:25:12Z
Plugins: 
 Volume: 
 Network: 
Kernel Version: 3.13.0-74-generic
Operating System: linux
Architecture: amd64
CPUs: 0
Total Memory: 0 B
Name: bad6fbd0573b

Any suggestion , how to fix this issue?

**Comment by gittycat** [comment]
Have a look at this similar issue https://github.com/docker/swarm/issues/511
Also check that the Consul server is running fine using `docker logs consul`.

If you're on OSX/Windows, using `docker-machine create` makes this a lot simpler.

**Comment by dongluochen** [comment]
@vimalprakashts Your nodes are unreachable, as shown in
```
(unknown): xxxxx:2375
Error: Cannot connect to the docker engine endpoint
```
You need to check if `docker -H xxxxx:2375 info` is up from your manager. It could be you are not opening port 2375 on your nodes, or the port is blocked by network firewall.

**Comment by vimalprakashts** [comment]
@dongluochen , Yes that was the issue , thank you :+1:

**Comment by gkgt80** [comment]
One of the reason this error come if you are using 
swarm version 1.2.0 , 1.2.1, 1.2.2
