### ISSUE TITLE
Unable to remove a node from the cluster

### ISSUE THREAD

**Issue by mountkin** [docker/swarm#197]
The ```Watch``` method of the discovery backend calls ```cluster.UpdateNodes``` method to update the  node list according the return value of the ```Fetch``` method of the discovery service.
But it only inserts the nodes that aren't exist in the node list and doesn't touch the nodes that are "removed" from the discovery service.

If a node is removed from the discovery service, the ```swarm list``` command returns the correct result because it calls the ```Fetch``` method of the discovery service directly. But in fact the removed node is still in the node list of the cluster.

**Comment by vincentwoo** [comment]
:+1: for node removal being a priority. If you have long running jobs, you need some way of signaling that a node is going to be removed but is still present while it is finishing its outstanding jobs.

**Comment by bryantidd** [comment]
what is the priority and timeline on node removal - housekeeping? It seems that this is integral to using Swarm. Otherwise it presents only a half solution for Docker cluster management. Would be happy to help test.

**Comment by mountkin** [comment]
The node list is synced from discovery services periodically. 
If we simply remove it from swarm's cached node list, it'll be added again when the next ```UpdateNodes``` is triggered by discovery service.

I think the problem can be solved in two ways:

1. Add a new member to the ```Cluster``` struct to keep all the nodes that had been "removed". And modify the ```UpdateNodes``` function to exclude the nodes that are in the removed list. 
The list of removed nodes should be stored persistently. 
This will introduce two new APIs to swarm:
  - DELETE /nodes/:node_id  which is responsible for add an entry to the removed list and delete the node from cluster.nodes.
  - POST /nodes/:node_id  which is responsible for remove the node from the ```removed list```.

2. The user removed the node from discovery service first, then call swarm's API to delete it from the cache.
But this may not work for the discovery services that haven't exposed a ```DELETE``` API, such as ```nodes``` and ```token```.

@vieux @aluzzardi  What do you think?

**Comment by vincentwoo** [comment]
@vieux saw from your comments in linked issues that this was going to be addressed soon - can you give us any updates on how this is coming together?

**Comment by aluzzardi** [comment]
@vincentwoo We have a few PRs cooking for this - should be completed for 0.3.0.

**Comment by vincentwoo** [comment]
@aluzzardi I see that this was marked resolved in https://github.com/docker/swarm/pull/811, but I don't see the topic addressed in the official docs or changelog. Can you describe the procedure required to remove a node from the cluster? Does it depend on the discovery service?

**Comment by abronan** [comment]
Hi @vincentwoo, Yes it depends on the discovery service. If using the `kv` discovery or the `token` discovery, there is a `TTL` field attached to the node entry. If the node does not heartbeat to notify of its presence in the cluster (ie. stopping the `swarm join` or the node crashes), the `TTL` will expire and the Manager will be notified to remove the node entry.

**Comment by vincentwoo** [comment]
So if I understand you correctly, the way to remove a node is to explicitly kill whatever background process `swarm join` is running in, and wait for the TTL to expire? Are there plans to encapsulate or document this?

**Comment by abronan** [comment]
Yes exactly. The documentation mentions the `heartbeat` flag but I agree that this should be explained better.. Especially about the whole process off tagging a node as dead to evict it from any scheduling decision and then removing it from the cluster, the process of heartbeating and watch notifications, etc. 

You can maybe open an issue to track this. I'll look into enhancing the docs for this aspect.
