### ISSUE TITLE
how to use swarm manager to rmi image

### ISSUE THREAD

**Issue by woshihaoren** [docker/swarm#1974]
swarm version:1.1.2
docker version:1.10.3

###### [root@zw-docker-2 ~]# docker -H swarm-manager:3376 images
REPOSITORY                                  TAG                 IMAGE ID            CREATED             SIZE
background   532d8cc             645c73d6b195        About an hour ago   788.9 MB
swarm                                       latest              d1c2b663d66a        3 weeks ago         18.11 MB
###### [root@zw-docker-2 ~]# docker -H swarm-manager:3376 rmi 645c73d6b195
Failed to remove image (645c73d6b195): Error response from daemon: No such image 645c73d6b195

**Comment by dongluochen** [comment]
Confirm the error is also on Swarm 1.1.3. 
```
ubuntu@manager:~$ docker -H manager:3375 images | grep -i hello
hello-world                            latest              690ed74de00f        5 months ago        960 B
ubuntu@manager:~$ docker -H manager:3375 rmi 690ed74de00f
Failed to remove image (690ed74de00f): Error response from daemon: No such image 690ed74de00f
ubuntu@manager:~$ docker -H manager:3375 rmi hello-world
Untagged: hello-world:latest
Deleted: sha256:690ed74de00f99a7d00a98a5ad855ac4febd66412be132438f9b8dbd300a937d
Deleted: sha256:32ada9ef4cd3ccd536337fbcd8cdb6e026237f59db80498f83f3175176561ffb
Deleted: sha256:b652ec3a27e758f30de4742156b5d096bb19c82f2dc836e96e430323ba166ffe
```

**Comment by vieux** [comment]
@woshihaoren thanks for the report, I opened a fix in https://github.com/docker/swarm/pull/1979
