### ISSUE TITLE
'--tmpfs' support ?

### ISSUE THREAD

**Issue by DarkFranX** [docker/swarm#2001]
I set up Docker Swarm according to this [article](http://blog.scottlowe.org/2015/03/06/running-own-docker-swarm-cluster/) and I am using docker-py to control it. 

The problem is that even if I add the --tmpfs option to the container creation parameters, the swarm ignores it (no errors). So the desired temporary volume is not created inside the container. 

However, if I use my local docker deamon or a swarm node directly, everything works fine.

Any idea?

Thanks in advance!

edit: I can see the tmpfs value in the creation POST request when sniffing the connection, so I think it's sending correctly

**Comment by jimmyxian** [comment]
@DarkFranX 
It has already supported in swarm master. Can you try swarm master?

**Comment by DarkFranX** [comment]
What do you mean by trying swarm master? I am using the swarm image from docker registry already. Or maybe there is something else?

BTW I just saw that "SwarmMaster" build is failing since four days, could it be related?

**Comment by DarkFranX** [comment]
Problem solved with image **swarm:1.2.0rc1**

Closing.
