### ISSUE TITLE
Integration tests failing on master

### ISSUE THREAD

**Issue by nishanttotla** [docker/swarm#2002]
Most integration tests started failing around Friday (as pointed out by @dongluochen), and the error seems to be
```
# Command "docker -H 127.0.0.1:5249 info" failed 15 times. Output: Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
It's possible that #1997 introduced new `engine-api` behavior that is causing this, because the text corresponds with `ErrConnectionFailed`. It's not clear though, since tests passed on #1997. Good news is that the client is working with manual testing, so it's likely only the integration tests need to be fixed.

Another possible culprit might be https://github.com/docker/docker/pull/20662 (as pointed out by @vieux), leading to `dind` not working.

**Comment by vieux** [comment]
Depends on https://github.com/docker/docker/pull/21341

**Comment by MHBauer** [comment]
docker/docker#21341 is merged. What is next to do?

**Comment by dongluochen** [comment]
#2089 may have fixed it.
