### ISSUE TITLE
"docker run -i -t" hangs on Ctrl-p + Ctrl-q detach.

### ISSUE THREAD

**Issue by yoshiokatsuneo** [docker/swarm#2003]
"docker run -i -t" with docker swarm hangs on ctrl-p ctrl-q sequence to detach.
 https://docs.docker.com/engine/quickstart/#running-an-interactive-shell

**Comment by jimmyxian** [comment]
@yoshiokatsuneo Thanks for reporting this.
Tested locally and can reproduce.

**Comment by jimmyxian** [comment]
@yoshiokatsuneo 
Can you provide swarm version and docker version?

**Comment by yoshiokatsuneo** [comment]
@jimmyxian 
Strangely, I cannot reproduce the issue, now...
I close this case for now...
