### ISSUE TITLE
How to set up a private registry for docker swarm ???

### ISSUE THREAD

**Issue by venki93** [docker/swarm#2005]
I've configured docker swarm cluster with 2 nodes (v.m's) and a master(v.m) in our organization.  I've followed the token method for setting up the swarm cluster. I want to set up a private registry for that swarm cluster. For single host insecure registry flag works and for swarm cluster i don't have any info on it. So, please help me out with this.

**Comment by dongluochen** [comment]
Have you try [registry](https://docs.docker.com/registry/deploying/)? There are also some blogposts on this topic.

**Comment by venki93** [comment]
I tried to deploy registry 2.0 in one of the machines running swarm cluster and i tried --insecurity-registry flag on all nodes and i tried to pull the image through docker -H :4000 pull <ip_of_host>:5000/img_name but of no use.

**Comment by venki93** [comment]
thanks @dongluochen finally i resolved and i am able to access the private registry now

**Comment by hekaldama** [comment]
@venki93 how did you resolve?

**Comment by liorsbg** [comment]
@venki93 Can you please give a hint as to how you solved this?
