### ISSUE TITLE
command `docker events` has no options of --since and --filter?

### ISSUE THREAD

**Issue by allencloud** [docker/swarm#2036]
Like the topic:

In swarm, `docker events` only supports the option of `--until`.
While in docker engine, it supports `--since` and `--filter`.

**Comment by jimmyxian** [comment]
Same as https://github.com/docker/swarm/issues/1203

**Comment by allencloud** [comment]
@jimmyxian 
OK, Thanks for your remind.
Then should I close this issue report?

**Comment by jimmyxian** [comment]
@allencloud Yeah.
