### ISSUE TITLE
API "/images/create" is available, and the document swarm-api is out of date

### ISSUE THREAD

**Issue by CodeJuan** [docker/swarm#2039]
The document [swarm-api](https://github.com/docker/swarm/blob/master/docs/swarm-api.md#missing-endpoints) said the API "/images/create" is not available, but I found that the API "/images/create" is OK, I tried 
```
curl -X POST http://192.168.1.245:4000/images/create?fromImage=busybox
```
And the response is 
```
{"id":"i3","status":"Pulling busybox...","progressDetail":{}}
{"id":"g540","status":"Pulling busybox...","progressDetail":{}}
{"id":"i3","status":"Pulling busybox... : downloaded","progressDetail":{}}
{"id":"g540","status":"Pulling busybox... : downloaded","progressDetail":{}}
```
After that, I checked the images on the nodes by cli `docker images`, and found the image busybox.

So I think the  document [swarm-api](https://github.com/docker/swarm/blob/master/docs/swarm-api.md#missing-endpoints) is out of date.

**Comment by nishanttotla** [comment]
cc @thaJeztah
