### ISSUE TITLE
consistent addressing

### ISSUE THREAD

**Issue by phemmer** [docker/swarm#204]
The addressing of servers is rather inconsistent, especially between docker & swarm.

* The Docker documentation says to use the format `tcp://1.2.3.4:2375` ([here](https://github.com/docker/docker/blob/master/docs/sources/reference/commandline/cli.md#daemon-socket-option))
* The swarm documentation says to use the format `1.2.3.4:2375` ([here](https://github.com/docker/swarm)).
* The `swarm list` and `docker info` commands output the format `http://1.2.3.4:2375
* The docker client does not accept `http://`protocol prefixes, only `tcp://`.
* The format `tcp://1.2.3.4:2375` (and `http://...`) is not a host (is named as such in `$SWARM_HOST` and `$DOCKER_HOST`). The format `1.2.3.4:2375` is not a host either. A host, or hostname, does not include protocol or port.
* The `swarm join` command uses `--addr` for specifying the IP & PORT
* The `swarm manage` command uses `--host` for specifying the IP & PORT

As you can see, the naming is all over the place (and this is just from a brief look as well). Half these are URLs & URIs, the other half might be considered addresses, and none of them are hosts, but most are labeled as such.
While I personally would prefer we not call things 'hosts' that aren't hosts, it's a little late to fix this naming issue. However I do think all this needs to be made consistent. The documentation can be fixed at any time, and the swarm code can be fixed before it is labeled as 'stable'.

**Comment by vieux** [comment]
see #237

**Comment by vieux** [comment]
I believe we solved most of the issues ?

We can't change `-H` as we use it to match docker's flags

**Comment by phemmer** [comment]
Well in it's current state, it's now broken for me:

```
# cat .swarm_discovery 
172.17.0.81:2375
172.17.0.82:2375
172.17.0.83:2375

# docker info
Containers: 0
Nodes: 0
```

And the swarm daemon logs are spitting out:

```
2015-01-19 20:18:10 swarm: time="2015-01-19T20:18:10-05:00" level=error msg="Get 172.17.0.25:2375/v1.15/info: unsupported protocol scheme \"\". Are you trying to connect to a TLS-enabled daemon without TLS?" 
2015-01-19 20:18:10 swarm: time="2015-01-19T20:18:10-05:00" level=error msg="Get 172.17.0.26:2375/v1.15/info: unsupported protocol scheme \"\". Are you trying to connect to a TLS-enabled daemon without TLS?" 
2015-01-19 20:18:10 swarm: time="2015-01-19T20:18:10-05:00" level=error msg="Get 172.17.0.27:2375/v1.15/info: unsupported protocol scheme \"\". Are you trying to connect to a TLS-enabled daemon without TLS?" 
```

**Comment by vieux** [comment]
@phemmer you need to update dockerclient (`go get -u`)
Can you do this and try again ?

**Comment by phemmer** [comment]
ahha, sorry about that :-)

Then yes, I think all is well enough. Though in response to #237, `docker -H 1.2.3.4:2375` works fine for me. No `tcp://` prefix needed.

**Comment by technolo-g** [comment]
Everything seems to be working for me as well.

**Comment by aluzzardi** [comment]
Can we close this down?
