### ISSUE TITLE
How to setup a docker swarm cluster with AWS ubuntu machine

### ISSUE THREAD

**Issue by vimalprakashts** [docker/swarm#2047]
I am getting the bellow error. while creating and running container in swarm cluster.

 

      Creating network "ubuntu_default" with the default driver
            ERROR: 500 Internal Server Error: failed to parse pool request 
        for address space "GlobalDefault" pool "" subpool "": 
        cannot find address space GlobalDefault 
        (most likely the backing datastore is not configured)

The steps I followed.

1. Created a One VPC and added a security group with allowing all the port numbers.

2. Created a 3 ubuntu machine in AWS (manager, slave1,slave2)

3. First started the Consul node with the below command

    docker run --restart=unless-stopped -d -p 8500:8500 -h consul1 progrium/consul -server -bootstrap

4. Then started a swarm manger on the same machine

    docker run --restart=unless-stopped -d -p 3375:2375 swarm manage consul://172.31.17.163:8500

5. Then added the 2 slaves to it

    docker -H=tcp://slave1ip:2375 --restart=unless-stopped run -d swarm join --advertise=slave1ip:2375 consul://172.31.17.163:8500
    
    docker -H=tcp://slave2ip:2375 --restart=unless-stopped run -d swarm join --advertise=slave2ip:2375 consul://172.31.17.163:8500

6. Added consul store in swarm manger machine

    DOCKER_OPTS="--cluster-store=consul://172.31.17.163:8500 --cluster-advertise=eth0:2375 -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"

> docker info

    Containers: 8
     Running: 2
     Paused: 0
     Stopped: 6
    Images: 4
    Server Version: swarm/1.1.3
    Role: primary
    Strategy: spread
    Filters: health, port, dependency, affinity, constraint
    Nodes: 2
     ip-172-31-19-203: slave1ip:2375
      └ Status: Healthy
      └ Containers: 4
      └ Reserved CPUs: 0 / 1
      └ Reserved Memory: 0 B / 1.018 GiB
      └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-74-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
      └ Error: (none)
      └ UpdatedAt: 2016-03-29T11:32:39Z
     ip-172-31-42-220: slave2ip:2375
      └ Status: Healthy
      └ Containers: 4
      └ Reserved CPUs: 0 / 1
      └ Reserved Memory: 0 B / 1.018 GiB
      └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-74-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
      └ Error: (none)
      └ UpdatedAt: 2016-03-29T11:32:21Z
    Plugins: 
     Volume: 
     Network: 
    Kernel Version: 3.13.0-74-generic
    Operating System: linux
    Architecture: amd64
    CPUs: 2
    Total Memory: 2.035 GiB
    Name: 257d542e5b26

> export DOCKER_HOST=tcp://172.31.17.163:3375

> docker run hello-world

it was excuting perfectly. and I can see the containers creating slaves with spread strategy 

Now I just try to create 

docker-compose.yml

    version: "2"
    services:
           web:
                image: busybox

> docker-compose up

this says the following error. 

   

     Creating network "ubuntu_default" with the default driver
        ERROR: 500 Internal Server Error: failed to parse pool request 
    for address space "GlobalDefault" pool "" subpool "": 
    cannot find address space GlobalDefault 
    (most likely the backing datastore is not configured)

It giving the same error for

> docker network create -d overlay myapp

so the problem is , this is not creating overlay network , with my current configuration.

How to resolve this error?

**Comment by dongluochen** [comment]
To enable overlay network, you need to set `cluster-store` and `cluster-advertise` on **all** the Docker `daemons` that want to participate the overlay networking. Make sure you open corresponding network ports for VXLAN. See https://docs.docker.com/engine/userguide/networking/dockernetworks/ .

```
To create an overlay network, you configure options on the daemon on each Docker Engine for use with overlay network. There are three options to set:

Option	Description
--cluster-store=PROVIDER://URL   Describes the location of the KV service.
--cluster-advertise=HOST_IP|HOST_IFACE:PORT  The IP address or interface of the HOST used for clustering.
--cluster-store-opt=KEY-VALUE OPTIONS   Options such as TLS certificate or tuning discovery Timers
```

**Comment by zet809** [comment]
@vimalprakashts I have followed you steps to create a small swarm cluster. But for step5, even though there is docker created and running on slave host, the master can not get info about them. 
The only slave added successfully into the swarm cluster is the docker host which have swarm master running on.
And the log for the container running on slave docker host output the following msg, do you have any idea about the error for my scenario? 
time="2016-03-30T09:35:44Z" level=info msg="Initializing discovery without TLS"
time="2016-03-30T09:35:44Z" level=info msg="Registering on the discovery service every 1m0s..." addr="<host_ip>:2375" discovery="consul://<consul_ip>:8500/ui"
time="2016-03-30T09:38:14Z" level=error msg="cannot set or renew session for ttl, unable to operate on sessions"
time="2016-03-30T09:39:14Z" level=info msg="Registering on the discovery service every 1m0s..." addr="<host_ip>:2375" discovery="consul://<consul_ip>:8500/ui"

**Comment by dongluochen** [comment]
When running Docker in cloud platform, some network ports need to open. 
Docker port (your choice, 2375, 2376, etc)
Discovery: 8500 for Consul
Overlay network: tcp 7946, udp 4789, 7946.
SSH: 22

**Comment by zet809** [comment]
The port scan from slave node shows 8500, 22 are opened on the master node. And use tcpdump show that the slave node doesn't send out any request to master node at all. Really strange.
nmap <master IP>

Starting Nmap 6.40 ( http://nmap.org ) at 2016-03-30 21:44 EDT
Nmap scan report for master (master IP)
Host is up (0.00012s latency).
Not shown: 996 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
111/tcp  open  rpcbind
4000/tcp open  remoteanything
8500/tcp open  fmtp
MAC Address: 02:42:A8:F7:2C:6A (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 1.74 seconds

**Comment by zet809** [comment]
My guess is correct that after I assign 10.0.0.x IP for the slave docker container, it can register to the swarm master. But the problem is there will be another IP needed beside the docker host, which means how many slave docker host there, 2 times IP address are needed within the same subnet.
Another problem is that the swarm master only know there is a new slave docker host, but the docker host information is empty.

**Comment by dongluochen** [comment]
@zet809 Ubuntu has default docker configuration file at /etc/default/docker. Can you show the process info of your docker daemon like this? 

```
ubuntu@manager:~$ ps -ef | grep -i "docker daemon"
root       666     1  0 Mar14 ?        00:50:56 /usr/bin/docker daemon -H xxx:2377 -H unix:///var/run/docker.sock --cluster-store=consul://yyy:8500/swarm --cluster-advertise=xxx:2377
```

**Comment by zet809** [comment]
@dongluochen Thanks very much for you responding. I have found the reason in my environment that I have configure bridge manually for the nic that docker host need to use to contact outside.
The current question is, is it possible to assign IP address for the containers running in the swarm cluster and then I can ping it outside of the swarm cluster? It seems the overlay network only works inside the cluster.

**Comment by dongluochen** [comment]
> is it possible to assign IP address for the containers running in the swarm cluster and then I can ping it outside of the swarm cluster?

@zet809 It's possible but you have to manage the IP assignment and routing. Docker allows you to create a subnet with public IP `--net`, and it allows you to specify an IP for a container `--ip`. But you'll have to handle routing. 

If you just want your container accessible from outside, you can use port mapping `-p` to map host port to your container port, or use host network where container uses the host's network `--net=host`. They have different implication, choose accordingly.
