### ISSUE TITLE
Slave dockerhost can not be added into swarm cluster

### ISSUE THREAD

**Issue by zet809** [docker/swarm#2052]
I have followed the doc https://docs.docker.com/swarm/install-manual/ to setup a small swarm cluster.
But swarm master can not add slave docker host which is not the host the master running on.
My scenario:
dockerhost1(10.4.0.1):     the consul node, swarm master and swarm slave
dockerhost2(10.4.0.2):    swarm slave

The steps to reproduce the issue:
1. create consul
docker run -d -p 8500:8500 --name=consul progrium/consul -server -bootstrap
2. start swam master
docker run -d -p 4000:2375 --name master swarm manage consul://10.4.0.1:8500
3. add dockerhost1 as slave(running on dockerhost 1)
docker run -d --name=slave swarm join --advertise 10.4.0.1:2375 consul://10.4.0.1:8500
4. add dockerhost2 as slave (running on dockerhost 2)
docker run -d --name=slave swarm join --advertise 10.4.0.2:2375 consul://10.4.0.1:8500
5: check docker info
    # docker -H 10.4.0.1:4000 info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 5
Server Version: swarm/1.1.3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 1           ============> Only the dockerhost1 is added into the swarm cluster
 dockerhost1: 10.4.0.1:2375
  └ Status: Healthy
  └ Containers: 3
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.053 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-56-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-03-30T09:53:17Z
Plugins:
 Volume:
 Network:
Kernel Version: 3.19.0-56-generic
Operating System: linux
Architecture: amd64
CPUs: 2
Total Memory: 4.053 GiB
Name: 24132efe8214

**Comment by dongluochen** [comment]
@zet809 Is your question covered in #2047?

**Comment by zet809** [comment]
Yes, I will close this one.
