### ISSUE TITLE
how to fix : unable to find a node that satisfies error?

### ISSUE THREAD

**Issue by vimalprakashts** [docker/swarm#2079]
I am in a small cluster, with one master and 2 slave.

My docker info Says
>
```
Containers: 11
 Running: 8
 Paused: 0
 Stopped: 3
Images: 22
Server Version: swarm/1.1.3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 ip-172-31-19-203: xxxx:2375
  └ Status: Healthy
  └ Containers: 4
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.018 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-74-generic, node=node1, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-05T02:00:51Z
 ip-172-31-42-220: yyyy:2375
  └ Status: Healthy
  └ Containers: 7
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.018 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-74-generic, node=node2, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-05T02:01:10Z
Plugins: 
 Volume: 
 Network: 
Kernel Version: 3.13.0-74-generic
Operating System: linux
Architecture: amd64
CPUs: 2
Total Memory: 2.035 GiB
Name: 4c436f6afe07
```

above I can see the labels are set as node=node1,node=node2 for the slaves.

but If I try to execute ,

> docker run -e constraint:node==node1 -d nginx

I am getting this error.

docker: Error response from daemon: unable to find a node that satisfies node==node1.
See 'docker run --help'.

**Comment by allencloud** [comment]
Oh, Great. I think constraints of "node" and labels of "node" went conflict in swarm manager.
"Node" in "constraint:node==node1" in swarm is a key word, swarm will search node whose name is node1, while in your cluster no node is named after node1.
Although you have a node with label node1, it does not work.
And in your case, you use "node" as a label name.
So, conflict happens.

**Comment by vimalprakashts** [comment]
Wow, It works, I just change that label to awsinstance=node1 on slave1 and  awsinstance=node2 on slave2. 

Thankyou @allencloud
