### ISSUE TITLE
launching a "self destroying" container (aka --rm=true) through swarm -- hangs

### ISSUE THREAD

**Issue by andrea-spoldi** [docker/swarm#2082]
Hi,
 can't tell if this topic was already discussed, did a bit of research in issues without significant results.

Also, my question might be silly, so again sorry in advance

I'm running a test swarm cluster, 1 manger plus 2 nodes

sudo docker run --rm=true -it swarm --version
swarm version 1.1.3 (7e9c6bd)

sudo docker version 
Client:
 Version:      1.9.1
....

using consul as key service (don't think is relevant for the issue, but anyway)

everything goes smooth normally, but if I try to run whichever container with "--rm=true" (and of course no "-d" flag), the container goes on node with "Created" status, but never really starts up till the CMD goes timeout, and eventually (I tested with "nginx" image for instance) starts in detached mode, kinda ignoring the --rm=true command

I'm doing this because I'm working on an application which will batch process some jobs from a sidekiq queue within containers, and I wish to use that --rm flag in order to get rid of the container once the processing is completed and the CMD exits '0'

Any thoughts ? 

Thanks for your help

A

**Comment by dongluochen** [comment]
@andrea-spoldi Can you provide the command you start swarm, and the command/output of your `docker run`? `--rm=true` shouldn't block container from starting.

**Comment by andrea-spoldi** [comment]
@dongluochen thanks for replying

this is how I lunch the swarm manage container 

sudo docker run -d --dns 172.17.42.1 -p 8333:2375 swarm --experimental manage consul://consul.service.consul:8500/swarm

and this is what I try running a simple container with "--rm=true"

sudo docker -H tcp://10.0.0.11:8333 run --rm=true debian date

no outputs here, but on one node I have

sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
db450c7f4e93        debian              "date"                   24 seconds ago      Created                                 backstabbing_austin
334bd6b466c2        swarm               "/swarm --experimenta"   4 days ago          Up 4 days           2375/tcp            lonely_swirles

Created, not started

**Comment by dongluochen** [comment]
@andrea-spoldi You may enable debugging on Swarm `swarm -l debug manage ...` and Daemon `docker daemon -D ...`. The logs may give you reason on the failure. You can also try the same command on the corresponding daemon to compare the result, and with or without `--rm=true`. It may give you better idea on the problem.

**Comment by andrea-spoldi** [comment]
Hi, this is what happens on the swarm node, from docker daemon debug log
http://pastebin.com/xvshnsFY

This line here I think is the more relevant

```
DEBU[0996] Calling POST /v1.21/containers/7880ff1219872f677b83c9fda25fe21c06e034f13e84056a3b63398c10ca4f2b/attach

INFO[0996] POST /v1.21/containers/7880ff1219872f677b83c9fda25fe21c06e034f13e84056a3b63398c10ca4f2b/attach?stderr=1&stdout=1&stream=1

DEBU[0996] attach: stdout: begin      
                  
DEBU[0996] attach: stderr: begin   
                     
<<...more than 1 minute here doing nothing ...>>     
   
DEBU[1116] Calling POST /v1.15/containers/7880ff1219872f677b83c9fda25fe21c06e034f13e84056a3b63398c10ca4f2b/start

INFO[1116] POST /v1.15/containers/7880ff1219872f677b83c9fda25fe21c06e034f13e84056a3b63398c10ca4f2b/start

DEBU[1116] Assigning addresses for endpoint fervent_leakey's interface on network bridge

DEBU[1116] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])

DEBU[1116] Assigning addresses for endpoint fervent_leakey's interface on network bridge

ERRO[1116] attach: **stdout: write unix @: broken pipe**    

DEBU[1116] attach: stdout: end
```


I think somehow it cannot redirect/attaching-to the tty console from the container running in the remote node back to the swarm manager

I can't see anything interesting in swarm manager logs

similar thing happens without --rm=true, but lunching the container with "-it" flag, or without any flag, but this time the error is different 


```
DEBU[3320] Calling POST /v1.21/containers/8ff5e96eb12b656b3ec1ef613567cf741e82a9a77384c73e5296077fb88ecc0e/attach 

INFO[3320] POST /v1.21/containers/8ff5e96eb12b656b3ec1ef613567cf741e82a9a77384c73e5296077fb88ecc0e/attach?stderr=1&stdin=1&stdout=1&stream=1           
            
DEBU[3440] Calling POST /v1.15/containers/8ff5e96eb12b656b3ec1ef613567cf741e82a9a77384c73e5296077fb88ecc0e/start 

INFO[3440] POST /v1.15/containers/8ff5e96eb12b656b3ec1ef613567cf741e82a9a77384c73e5296077fb88ecc0e/start 

DEBU[3440] Assigning addresses for endpoint modest_mahavira's interface on network bridge 

DEBU[3440] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 

DEBU[3440] Assigning addresses for endpoint modest_mahavira's interface on network bridge 

DEBU[3440] Calling GET /v1.15/containers/json           

INFO[3440] GET /v1.15/containers/json?all=1&size=0&filters={"id":["8ff5e96eb12b656b3ec1ef613567cf741e82a9a77384c73e5296077fb88ecc0e"]} 

DEBU[3440] Releasing addresses for endpoint modest_mahavira's interface on network bridge 

DEBU[3440] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.3) 

DEBU[3440] Calling GET /v1.15/containers/8ff5e96eb12b656b3ec1ef613567cf741e82a9a77384c73e5296077fb88ecc0e/json 

INFO[3440] GET /v1.15/containers/8ff5e96eb12b656b3ec1ef613567cf741e82a9a77384c73e5296077fb88ecc0e/json 

DEBU[3440] Calling POST /v1.21/containers/8ff5e96eb12b656b3ec1ef613567cf741e82a9a77384c73e5296077fb88ecc0e/resize 

INFO[3440] POST /v1.21/containers/8ff5e96eb12b656b3ec1ef613567cf741e82a9a77384c73e5296077fb88ecc0e/resize?
h=41&w=131 

ERRO[3440] Handler for POST /v1.21/containers/8ff5e96eb12b656b3ec1ef613567cf741e82a9a77384c73e5296077fb88ecc0e/resize returned error: Container 8ff5e96eb12b656b3ec1ef613567cf741e82a9a77384c73e5296077fb88ecc0e is not running 

ERRO[3440] HTTP Error                                    err=Container 8ff5e96eb12b656b3ec1ef613567cf741e82a9a77384c73e5296077fb88ecc0e is not running statusCode=500
```

**Comment by dongluochen** [comment]
Do you see the same failure when you run it directly towards docker daemon, not swarm? 

Also Docker engine version 1.9.1 is a bit old. Do you have reason to keep it? Otherwise would you upgrade it to current stable version [1.10.3](https://github.com/docker/docker/releases/tag/v1.10.3) and rerun the test?

**Comment by andrea-spoldi** [comment]
@dongluochen running the container on the node itself (so not from the swarm master) just works

I also tried to upgrade docker to 1.10.3, same result

**Comment by andrea-spoldi** [comment]
Still running into this issue, has anybody using swarm ever tried to run a container through swarm with --rm=true option successfully ? 

ty

**Comment by dongluochen** [comment]
I tried it on 2 different swarm clusters and both were successful. The first one is Swarm 1.1.3 with Engine 1.9.1, the second one is Swarm 1.2.0 with Engine 1.11.0. In both case `docker -H manager:port run --rm=true debian date` finished and containers were removed.

**Comment by andrea-spoldi** [comment]
@dongluochen I tried again, new cluster, Swarm 1.2.0 with Engine 1.11.0, no consul this time (testing with token://<token-id>) and no experimental mode..

actually the lunch of a non-persistent-self-destroying container works, but it just takes 2minutes before actually starting the container ...this is the test I made

from the swarm manager : 

ubuntu@swarm-test-node-mg:~$ time sudo docker -H tcp://10.0.2.222:8333 run --rm=true debian date

this comes on debug logs of the selected swarm node 

```
DEBU[0098] Calling POST /v1.15/containers/create        
DEBU[0098] form data: {"AttachStderr":true,"AttachStdin":false,"AttachStdout":true,"Cmd":["date"],"CpuShares":0,"Cpuset":"","Domainname":"","Entrypoint":null,"Env":null,"ExposedPorts":null,"HostConfig":{"Binds":null,"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"BlkioWeight":0,"BlkioWeightDevice":null,"CapAdd":null,"CapDrop":null,"CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuPeriod":0,"CpuQuota":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","DNSOptions":[],"Devices":[],"Dns":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IpcMode":"","KernelMemory":0,"Links":null,"LogConfig":{"config":{},"type":""},"LxcConf":null,"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NetworkMode":"default","OomKillDisable":false,"OomScoreAdj":0,"PidMode":"","PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SecurityOpt":null,"ShmSize":0,"Tmpfs":null,"UTSMode":"","Ulimits":null,"VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"debian","Labels":{"com.docker.swarm.id":"2e1290151071263aad406344d1ab71c4a9d5a385830893f18e6fb23230796ce2"},"MacAddress":"","Memory":0,"MemorySwap":0,"NetworkDisabled":false,"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":false,"PortSpecs":null,"StdinOnce":false,"StopSignal":"","Tty":false,"User":"","VolumeDriver":"","Volumes":{},"WorkingDir":""} 

DEBU[0098] container mounted via layerStore: /var/lib/docker/aufs/mnt/32e87cd140c5d8cb454b5ba04272f5ca490d19f236599c76b4111ce560184291 

DEBU[0098] Calling GET /v1.15/containers/json?all=1&size=0&filters={"id":["426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005"]} 

DEBU[0098] Calling GET /v1.15/containers/426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005/json 
DEBU[0098] Calling GET /v1.23/volumes    
               
DEBU[0098] Calling GET /v1.23/networks   
               
DEBU[0098] Calling POST /v1.23/containers/426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005/attach?stderr=1&stdout=1&stream=1 

DEBU[0098] attach: stdout: begin        
                
DEBU[0098] attach: stderr: begin 
```

and after 2mins, when I got this on the swarm manager console 

```
real	2m0.245s
user	0m0.020s
sys	0m0.005s
```

the swarm node logs this : 

```
DEBU[0218] Client disconnected, stop sending events   
  
DEBU[0218] Calling GET /v1.15/events         
           
DEBU[0218] Calling POST /v1.15/containers/426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005/start 
DEBU[0218] form data: null       
                       
DEBU[0218] container mounted via layerStore: /var/lib/docker/aufs/mnt/32e87cd140c5d8cb454b5ba04272f5ca490d19f236599c76b4111ce560184291 

DEBU[0218] Assigning addresses for endpoint sleepy_bassi's interface on network bridge 

DEBU[0218] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 

DEBU[0218] Assigning addresses for endpoint sleepy_bassi's interface on network bridge 

DEBU[0218] Programming external connectivity on endpoint sleepy_bassi (01c17e5501d8ab5925e5c95dd20dca992e977feafa9934147dfe2d861ee947e9) 

DEBU[0218] sandbox set key processing took 18.716205ms for container 426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005 

DEBU[0218] received containerd event: &types.Event{Type:"start-container", Id:"426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005", Status:0x0, Pid:"", Timestamp:0x571fda30} 

DEBU[0218] event unhandled: type:"start-container" id:"426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005" timestamp:1461705264  

DEBU[0218] Calling GET /v1.15/containers/json?all=1&size=0&filters={"id":["426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005"]} 

DEBU[0218] Calling GET /v1.15/containers/426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005/json 

ERRO[0218] attach: stdout: write unix /var/run/docker.sock->@: write: broken pipe 

DEBU[0218] attach: stdout: end     
                     
DEBU[0218] Calling POST /v1.23/containers/426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005/wait 

DEBU[0218] containerd: process exited                    id=426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005 pid=init status=0 systemPid=4473

DEBU[0218] received containerd event: &types.Event{Type:"exit", Id:"426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005", Status:0x0, Pid:"init", Timestamp:0x571fda30} 

DEBU[0218] attach: stderr: end    
                      
DEBU[0218] Revoking external connectivity on endpoint sleepy_bassi (01c17e5501d8ab5925e5c95dd20dca992e977feafa9934147dfe2d861ee947e9) 

DEBU[0218] Releasing addresses for endpoint sleepy_bassi's interface on network bridge 

DEBU[0218] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.3) 

DEBU[0218] Calling GET /v1.15/containers/json?all=1&size=0&filters={"id":["426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005"]} 


DEBU[0218] Calling GET /v1.15/containers/426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005/json 

DEBU[0218] Calling GET /containers/426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005/json 

DEBU[0218] Calling DELETE /v1.15/containers/426858d2c674076752db98250338685d93a5c26a727aff67a4a7380bd0b3c005?force=0&v=1 
```

so it all seems like from either the swarm manager or the node there is something waiting for "something else" to connect, or to be forwarded (maybe the tty ??) up to 2 mins, after that it times out and the container is actually started, and terminated after its finishes its processing 

I did a further testing, I made the "date" command output to a file within a folder mounted from the host within the container, and actually it writes in 2mins after I lunch the command from the swarm manager

**Comment by andrea-spoldi** [comment]
@dongluochen okay, I discovered what the bogus was

I use nginx to reverse proxy the tcp socket of the docker engine and expose (internally) the tcp port 2375, rather than having the docker daemon working on port 2375...this is something I use since docker 0.something, and actually never changed

If I cut off nginx from the scenario and lunch docker daemon like this : 

sudo docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock

the lunch of a non-persistent container just works, instantly and beautifully

sorry for the waste of time, if any, and thanks for the support


A

**Comment by dongluochen** [comment]
Glad you get the root cause.
