### ISSUE TITLE
nopclient does not implement client interface

### ISSUE THREAD

**Issue by ascotan** [docker/swarm#2083]
Basically this change: https://github.com/docker/engine-api/commit/c3e35722bad23e13366c1186fd073ba60450e9ec  added a new interface method to the docker engine Client struct.  This file: https://github.com/docker/swarm/blob/master/api/nopclient/nop.go does not implement that interface so:

[vagrant@node ~]$ go get github.com/docker/swarm
\# github.com/docker/swarm/cluster
/opt/golang/src/github.com/docker/swarm/cluster/engine.go:134: cannot use "github.com/docker/swarm/api/nopclient".NewNopClient() (type *"github.com/docker/swarm/api/nopclient".NopClient) as type client.APIClient in field value:
	*"github.com/docker/swarm/api/nopclient".NopClient does not implement client.APIClient (missing UpdateClientVersion method)
/opt/golang/src/github.com/docker/swarm/cluster/engine.go:252: cannot use "github.com/docker/swarm/api/nopclient".NewNopClient() (type *"github.com/docker/swarm/api/nopclient".NopClient) as type client.APIClient in assignment:
	*"github.com/docker/swarm/api/nopclient".NopClient does not implement client.APIClient (missing UpdateClientVersion method)
/opt/golang/src/github.com/docker/swarm/cluster/engine.go:268: impossible type assertion:
	*"github.com/doc

This is because in cluster/engine.go, the Engine.apiClient field is of type engineapi.APIClient
which is an interface defined here: https://github.com/docker/engine-api/blob/5b9e86c11862e755be8871b64aada2a65ded4b8b/client/interface.go#L16 

which as you can see has the method:
UpdateClientVersion(v string)

:shipit: 

environment:
[vagrant@node ~]$ go version
go version go1.6 linux/amd64

[vagrant@node ~]$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

**Comment by nishanttotla** [comment]
@ascotan This will be fixed in #2077. Meanwhile, you should build swarm using `godep go install`, so that it uses the `engine-api` code in Godeps and builds successfully.

**Comment by ascotan** [comment]
Hey nishanttotla,

Thanks for the info. FYI I'm not setting up a development environment for swarm. In my case I'm installing swarm onto a production system without the use of the container. 

/soapbox
With most golang repos the expectation is to be able to go get from HEAD to get a binary distribution.  I understand the vendoring issues that golang brings but HEAD *is* the release version of the product.  If HEAD is broken the product is broken.

Features can/should be worked in a branch until stable and then merged into master when they are for release.
/soapbox

In my case I have production scripts which 'go get github.com/docker/swarm' to get swarm. However, if HEAD will be unstable, I have to setup a dev environment on my production boxes by doing a git clone with a godep install.

Anyway, data point to take into consideration. :)

**Comment by nishanttotla** [comment]
@ascotan I understand your problem, sorry that you have issues. This should be fixed today.

The fast moving nature of independent Docker repos and dependencies between them is the reason we use Godeps, so that we can fully control the Swarm `master` branch.

**Comment by ascotan** [comment]
:+1:  Thanks nishanttotla. nps.

**Comment by nishanttotla** [comment]
@ascotan the PR was merged, this issue should be fixed now. Feel free to point out more issues!
