### ISSUE TITLE
Does it necessary to show engine ID in `docker info` in swarm?

### ISSUE THREAD

**Issue by allencloud** [docker/swarm#2104]
Hi, All,

In a docker cluster with many docker engines managed by Swarm, there may be several engine with the same name, even all the same.

When managing docker engines, we usually run into some error from specific engine, in the error message, Output just shows engine name without engine ID.

In this case, users have no idea error is happening on which engine.

How about:
* 1. showing ID in `docker info` in Swarm
* 2. reporting message with both Engine Name and Engine ID

So we can have a map of Engine Name and Engine ID. Engine Name will help us get the exact engine fast if it is unique. If it is not unique, we can still use Engine ID.

**Comment by dongluochen** [comment]
I think having duplicate node name is a bad practice for Swarm. Swarm follows Docker CLI in name handling. Docker don't allow container name duplication although IDs are different. For the same reason we don't want duplicate node name, although it's not an error. Generally speaking users prefer names to access nodes, which is often built-in with DNS records. I think adding Engine ID is unnecessary.

**Comment by allencloud** [comment]
Although duplicate node name is bad practice, actually when we use docker machine or some IaaS to provision a bunch of VMs, there definitely will be a scene that all the vm has the same hostname.
In this case, if in swarm log we find some error message just showing the hostname(node name), it will be not readable for user. A user can do nothing according duplicate name. 
If we show node ID, it is the identity for user to find the exact one.

**Comment by allencloud** [comment]
merged in #2169
