### ISSUE TITLE
how does swarm have a sprint  meeting?

### ISSUE THREAD

**Issue by bruceauyeung** [docker/swarm#2109]
using an irc channel ? a docker meetup ? or something else ?

**Comment by dongluochen** [comment]
We don't have a sprint meeting at this time. There were quite a few Docker (online) meetups on Swarm in past 2 months. We are close to Docker 1.11 release. There would be some meetups on that.

**Comment by redhatlinux10** [comment]
@dongluochen https://github.com/docker/swarm/wiki/Open-Source-Planning-Process says 

> Major decisions affecting the Roadmap are discussed during fortnightly Sprint Meetings

do you mean the roadmap for Swarm 1.3.0 will not be discussed during a sprint meeting but during a meetup ? 
but which way for swarm 1.4.0, 1.5.0 ?  what is the conventional way ?
and it's a sprint meeting, which way is it ? an irc channel ? a docker meetup ? or something else ?

**Comment by nishanttotla** [comment]
We are in the process of redefining the future of Swarm, and will update the wiki with process and roadmap details. Stay tuned for that. Closing this issue until then, please reopen if you wish to discuss further.
