### ISSUE TITLE
docker info: display number of running containers per node

### ISSUE THREAD

**Issue by schmunk42** [docker/swarm#2141]
When running `docker info`:

```
# docker info
docker info
Containers: 124
 Running: 124
 Paused: 0
 Stopped: 0
Images: 248
Server Version: swarm/1.1.3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 4
 node-122: 1.2.3.4:2376
  └ Status: Healthy
  └ Containers: 58
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.053 GiB
  └ Labels: app=1, executiondriver=native-0.2, kernelversion=4.2.0-30-generic, operatingsystem=Ubuntu 15.10, provider=generic, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-19T10:17:35Z
[...]
```

... the output contains the count of all containers, including i.e. exited ones. I'd propose to add the number of runnings containers also, like

```
  └ Containers: 58 (40 running)
```

Related: https://github.com/docker/swarm/issues/2096

**Comment by allencloud** [comment]
I am afraid I did not get your point. Your suggested format is like 
```
Containers: 124
 Running: 124
```
So, what is the differences?

**Comment by schmunk42** [comment]
Sorry, I wasn't clear enough :)

I meant **per node**; I updated the issue title.

Usage example:
We have a swarm with master, proxy and application (worker) nodes. On master(s) and proxies there should be only 2-3 containers *running*, but the output per node includes also *stopped* and *exited* containers, which is kinda confusing IMHO.

**Comment by allencloud** [comment]
@schmunk42 
Reasonable, more specific details about containers on each node.

**Comment by allencloud** [comment]
When the node is `unhealthy` status, show nothing about container status?

**Comment by schmunk42** [comment]
> When the node is unhealthy status, show nothing about container status?

Hmmm, I'd assume that you can't get any information then. 
But actually, I don't have an opinion on that.
