### ISSUE TITLE
DockerSwarm UI

### ISSUE THREAD

**Issue by mlabouardy** [docker/swarm#2145]
I have built a web interface to manage DockerSwarm cluster (nodes, containers, images ..)
https://github.com/mlabouardy/dockerswarm-ui

**Comment by thaJeztah** [comment]
Nice! (You may want to add a license to that repo though)

**Comment by EamonZhang** [comment]
mark

**Comment by mlabouardy** [comment]
@thaJeztah i added :)

**Comment by thaJeztah** [comment]
@mlabouardy great! 👍

**Comment by rogerwelin** [comment]
Nice! I'm using [shipyards](https://github.com/shipyard/shipyard) ui which I think works great

**Comment by abronan** [comment]
We should look into adding this to the list of useful tools in the Swarm ecosystem. This is a really cool contribution!

**Comment by mlabouardy** [comment]
@abronan  yeah that would be awesome :+1:

**Comment by nishanttotla** [comment]
Closing this issue since a UI isn't part of the roadmap anymore.
