### ISSUE TITLE
Expose API Version for compatibility with Ansible

### ISSUE THREAD

**Issue by technolo-g** [docker/swarm#219]
Ansible is a very effective tool for orchestration with Docker containers. Unfortunately, it does not work with Swarm as it checks for the API version in use [1] which is not exposed by Swarm [2]. I think that the Swarm server should respond with it's minimum API compatibility level in a similar manner to the Docker daemon.

[1] https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker.py#L535
[2] https://gist.github.com/technolo-g/cf82abbb4eda212f26ce

**Comment by vieux** [comment]
Thanks for the report, I'll make a PR

**Comment by technolo-g** [comment]
@vieux, I was working on one now though I can't guarantee it will be what we need :)

**Comment by vieux** [comment]
@technolo-g ah sorry, please see #219 <- would this work for you ?

**Comment by technolo-g** [comment]
Never a problem with being too fast :) Confirming the fix w/ Ansible now...

**Comment by technolo-g** [comment]
The fix has been tested and confirmed working. Thanks!
