### ISSUE TITLE
Swarm fails to find packages when running unit testing with `go test -race ./...`!

### ISSUE THREAD

**Issue by allencloud** [docker/swarm#2221]
Hi, All,

When running unit tests locally on my own machine, it always reports error like these:
```
root@ubuntu:~/gocode/src/github.com/docker/swarm# go test -race ./...
vendor/github.com/Sirupsen/logrus/examples/hook/hook.go:5:2: cannot find package "gopkg.in/gemnasium/logrus-airbrake-hook.v2" in any of:
	/root/gocode/src/github.com/docker/swarm/vendor/gopkg.in/gemnasium/logrus-airbrake-hook.v2 (vendor tree)
	/usr/local/go/src/gopkg.in/gemnasium/logrus-airbrake-hook.v2 (from $GOROOT)
	/root/gocode/src/gopkg.in/gemnasium/logrus-airbrake-hook.v2 (from $GOPATH)
```

missing packages in vendor, GOROOT and GOPATH.

Maybe we need to add it in the /vendor, but now /vendor dir misses vendor.json, thus still broken.
https://github.com/docker/swarm/pull/2220 has tried to make vendor complete.

**Comment by allencloud** [comment]
It seems we need to update the CONTRIBUTING.md.

tp abandon `go test -race ./...`, while use 
```
go test -v -race `go list ./... | grep -v /vendor/`
```
instead.

**Comment by dongluochen** [comment]
Yes we should exclude `/vendor` from unit test.

**Comment by pfrayer** [comment]
+1 Thanks @allencloud. Build was broken with `./...`, works well with your command.
