### ISSUE TITLE
Swarm nodes with TLS on Consul

### ISSUE THREAD

**Issue by Nurza** [docker/swarm#2225]
Hello, I am building a Swarm cluster on a public network (so i MUST use TLS, I don't want a VPN).

I succeed to build this cluster, but when I capture internet packets with tcpdump, the swarm nodes are trying to connect to the Consul server in clear HTTP (but didn't succeed because of the TLS authentication).

However, the cluster is functional and can run containers.

How I run my Swarm manager:

```bash
docker run -d -p 4000:4000 -v /root/.certs:/certs:ro \
--add-host consul:192.168.0.56 \
--add-host node-1:192.168.0.49 \
--add-host node-2:192.168.0.51 \
--add-host node-2:192.168.0.54 \
swarm --debug manage --tlsverify \
--tlscacert /certs/ca.pem \
--tlscert /certs/swarm-cert.pem \
--tlskey /certs/swarm-priv-key.pem \
--discovery-opt kv.cacertfile=/certs/ca.pem \
--discovery-opt kv.certfile=/certs/swarm-cert.pem \
--discovery-opt kv.keyfile=/certs/swarm-priv-key.pem \
-H :4000 --replication --advertise 192.168.0.55:4000 consul://consul:8080
```

How I run my swarm's nodes:

```bash
docker run  -v /root/.certs:/certs:ro --add-host consul:192.168.0.56 swarm --debug join \
--discovery-opt kv.cacertfile=/certs/ca.pem \
--discovery-opt kv.certfile=/certs/cert.pem \
--discovery-opt kv.keyfile=/certs/key.pem --advertise=node-1:2375 consul://consul:8080
```

Some requests of a swarm node:

```
GET /v1/kv/docker/network/v1.0/endpoint/7d4e38bcdd69b66e65a830a464920ae6e0199b474b9a1ee05781ac7f2f633bf4/?consistent=
GET /v1/kv/docker/network/v1.0/endpoint/2f3906e0921b64f65d1f47c1634bf39f489873afcfeb1d6a37a93c3bcb0ffa79/35a91cc6185dd8a9e53e46c60981ef47c2dda1f2ce4cc936814eb21d5e8d6d42/?consistent=
GET /v1/kv/docker/network/v1.0/network/?consistent=
```

Any explications please? Thank you !

**Comment by Stretch96** [comment]
Have you started the consul server with the TLS options?

It's not well documented in the docker consul image, but I managed to get it configured using the guides at https://www.consul.io

First create a server.json file for consul, with the relevant TLS options. The main ones being

 - `encrypt` (a 16 byte base64 encoded string) which enables `Gossip Encrypt`
 - `https` (Self explanatory)
 - `verify_incoming` (requires that all incoming connections make use of TLS and that the client provides a certificate signed by the Certificate Authority from the ca_file)
 - `verify_outgoing` (requires that all outgoing connections make use of TLS and that the server provides a certificate that is signed by the Certificate Authority from the ca_file)

Like so:
```
{
  "data_dir": "/data",
  "log_level": "INFO",
  "node_name": "consul",
  "encrypt": "16byte-base64",
  "server": true,
  "addresses": {
    "https": "0.0.0.0"
  },
  "ports": {
    "https": 8501
  },
  "verify_incoming": true,
  "verify_outgoing": true,
  "key_file": "/certs/priv.pem",
  "cert_file": "/certs/cert.pem",
  "ca_file": "/certs/ca.pem"
}
```
Note: There's a full list of options at https://www.consul.io/docs/agent/options.htm
Then run it mounting the required files and specifying the config dir:
```
docker run -d -v /path/to/server.json:/config/server.json \
  -v /mycerts/ca.pem:/certs/ca.pem \
  -v /mycerts/cert.pem:/certs/cert.pem \
  -v /mycerts/priv.pem:/certs/priv.pem \
  -p 8501:8501 \
  --name=consul progrium/consul \
  -config-dir=/config
```
Then confirm it by running `docker logs <container_id>`:
```
[...]
Gossip encrypt: true, RPC-TLS: true, TLS-Incoming: true
[...]
```
Would like to know if there's any improvements that could be made to this 👍

**Comment by Nurza** [comment]
Well, I am using swarmkit now, so no need to install a key value store like Consul anymore, but thank you for your response. I can't test the solution so the issue is closed I guess ?

**Comment by Stretch96** [comment]
Yeah that'd be cool. I'm just on my way to building a swarm using Consul, I'll use the configuration you have mentioned and report back
I'm also planning to have it on a public network, so I have the same requirements 👍
