### ISSUE TITLE
Cannot remove overlay network when one of the Engines is down

### ISSUE THREAD

**Issue by doronp** [docker/swarm#2247]
$ docker -H localhost:4000 network create someNet

af0544ed6c58d1fca0a41695733735bbb15205aafdea0a1eb38084bc7a1aeb52

$ docker -H localhost:4000 run -tdi -e --net=someNet busybox
855195e6ecd81c450886f921ac3eed0447b41c68c9928f5b000e982ebf8df969

$ docker -H localhost:4000 ps -a

CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
855195e6ecd8        busybox             "sh"                5 seconds ago       Up 4 seconds                            docker2/sharp_poincare

$ docker -H localhost:4000 network ls
NETWORK ID          NAME                      DRIVER
f368d31e4f1b        docker1/host              host                
88796a8d8422        docker1/bridge            bridge              
af0544ed6c58        someNet                   overlay             
0f79475d3fff        docker2/bridge            bridge              
88ceb09718b7        docker2/host              host                
7830bbe345fc        docker2/docker_gwbridge   bridge              
2da78b8447da        docker1/none              null                
d62982382f49        docker2/none              null                
1f549a1b7b40        docker1/docker_gwbridge   bridge   
           
$ docker -H localhost:4000 network rm someNet
Error response from daemon: Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Swarm log part:

RRO[4398] Flagging engine as unhealthy. Connect failed 3 times  id=44H6:2M7F:CS63:AJ7A:RBA5:EASL:ND23:2IB6:436P:3LNS:R7HJ:7XS3 name=docker2
ERRO[4398] Update engine specs failed: Cannot connect to the Docker daemon. Is the docker daemon running on this host?  id=44H6:2M7F:CS63:AJ7A:RBA5:EASL:ND23:2IB6:436P:3LNS:R7HJ:7XS3 name=docker2
DEBU[4398] Node 44H6:2M7F:CS63:AJ7A:RBA5:EASL:ND23:2IB6:436P:3LNS:R7HJ:7XS3 failed - rescheduling containers 
DEBU[4398] Skipping rescheduling of 855195e6ecd81c450886f921ac3eed0447b41c68c9928f5b000e982ebf8df969 based on rescheduling policies 
DEBU[4424] HTTP request received                         method=DELETE uri=/v1.22/networks/someNet
DEBU[4425] Engine update succeeded                       id=D73Y:E56L:YVF4:4EWO:AQ7X:KNEY:WLXC:Z7CO:UWOP:TQHN:B4VT:PGML name=docker1
ERRO[4434] HTTP error: Cannot connect to the Docker daemon. Is the docker daemon running on this host?  status=500
ERRO[4442] Update engine specs failed: An error occurred trying to connect: Get http://10.0.15.22:4243/v1.23/info: dial tcp 10.0.15.22:4243: connect: host is down  id=44H6:2M7F:CS63:AJ7A:RBA5:EASL:ND23:2IB6:436P:3LNS:R7HJ:7XS3 name=docker2

Latest Swarm docker
Used consul on in a container on ubuntu 14 VM and two more VMs each running docker engine to serve as the swarm nodes.
Swarm runs as binary from the host (Mac)

**Comment by dongluochen** [comment]
Ping @mavenugo.

**Comment by mavenugo** [comment]
@dongluochen this seems like a swarm specific behavior : ` Error response from daemon: Cannot connect to the Docker daemon. Is the docker daemon running on this host?` where it tries to connect to a daemon that is down.

**Comment by dongluochen** [comment]
@doronp Is this same issue of #2149?

**Comment by doronp** [comment]
@dongluochen No. This has nothing to do with rescheduling. 
This issue state that:
You have Docker1 and Docker2 and you have created an overlay network and ran a container.
One of the engines now fails.
You are now unable to delete the overlay network.

**Comment by doronp** [comment]
PR #2251

**Comment by doronp** [comment]
Can this be closed?

**Comment by allencloud** [comment]
Yes, I think we should close this, since the related pr is merged.
