### ISSUE TITLE
Update engine-api version in /vendor

### ISSUE THREAD

**Issue by nishanttotla** [docker/swarm#2253]
After https://github.com/docker/engine-api/pull/162, lot of function signatures changed in `engine-api`. We should bump up to master soon.

This will have to be done all at once and will touch the following things:
- `engine-api` function calls
- mock and nop clients in Swarm
- unit tests

**Comment by allencloud** [comment]
@nishanttotla 
In the new version of docker/engine-api, I think PR https://github.com/docker/engine-api/pull/162 is merged.
Maybe we should reconsider https://github.com/docker/swarm/blob/master/cluster/engine.go#L962.
