### ISSUE TITLE
Build with private repo fails

### ISSUE THREAD

**Issue by garagatyi** [docker/swarm#2256]
Docker image build fails if base image is private image on dockerhub
Output:
```
Step 0 : FROM garagatyi/privatetest
Trying to pull repository docker.io/garagatyi/privatetest ...
not found 
Error: image garagatyi/privatetest:latest not found
```
I recorded headers using proxy and found that my client send X-Registry-Config header with credentials, but swarm sends this header to docker without credentials.
Swarm receives next JSON but base64 encoded 
```
{
  "configs": {
    "https://index.docker.io/v1/": {
      "serveraddress": "https://index.docker.io/v1/",
      "username": "***",
      "password": "***",
      "email": "***"
    }
  }
}
```
Docker receives
```
{
  "configs": {}
}
```

Swarm 1.2.2
Docker 1.8.2
OS CentOS

**Comment by nishanttotla** [comment]
@garagatyi can you please look at #2235? We'll review that and do whatever is necessary to fix this issue.

**Comment by garagatyi** [comment]
@nishanttotla Looks like function `buildImagePullOptions` is not used in build handling. So this fix won't help.

**Comment by nishanttotla** [comment]
@garagatyi can you please try now that #2272 was merged? I suspect this issue is basically same as #2217 because your problem seems to be that the base layer isn't pulled, which in turns causes the build to fail.

**Comment by garagatyi** [comment]
Sorry guys, looks like authentication failed because we are using old format of X-Registry-Config header. We started using docker since v0.6. Then we implemented private registry auth (not sure in which version). Later we start using swarm and didn't use private images. And only now we need private images with swarm and found that docker can pull on build but swarm can't.
From what I understand docker supports an old format for backward compatibility and swarm doesn't.
I tried to check with new format and curl instead of our client and everything is working on v 1.2.1, 1.2.2, 1.2.3. So we will update our client to new auth format usage.
Again sorry that I misinformed you. If you confirm that it is supposed that swarm doesn't support old conf format I'll close this issue.

**Comment by nishanttotla** [comment]
@garagatyi I would advise you to use the new format, since we're not planning on adding support for the old format at this point unless it's a blocker for a user. Sorry that this changed without notice, but it was part of a large change replacing the underlying client and was missed (hence a bug).
