### ISSUE TITLE
Builds fail randomly on test "28 leader election - store failure"

### ISSUE THREAD

**Issue by ezrasilvera** [docker/swarm#2266]
The build fails randomly on test "28 leader election - store failure"
on one of the targets ( engine-1.10  engine-1.10  engine-1.10  engine-1.10 engine-master)

The fail is random: E.g:  only engine-1.10  fails , and then on the next build (exactly the same code !) engine-1.10 will pass and engine-master will fail . On the same test!

**Comment by abronan** [comment]
Indeed this test is really flaky because of the waits and sleeps, the retries are aggressive but on a slow CI this can fail. Will try to give it some love soon enough :)
