### ISSUE TITLE
Compose UP in Docker Swarm Node Added Problem

### ISSUE THREAD

**Issue by yank1** [docker/swarm#2273]
When I use a one node. 
I can use `compose up` to up a image like `jenkins`.
And then I `compose down`

But when I add a node to swarm, And `compose up`  again.
There would be a error `can not find image`.

**Comment by yank1** [comment]
@allencloud is there any way to fix it

**Comment by allencloud** [comment]
I will try to reproduce this, and find the root cause of this issue.
@yank1

**Comment by allencloud** [comment]
@yank1 
If you solved this issue, please close this issue.
