### ISSUE TITLE
swarm loses events if docker engine restarts!

### ISSUE THREAD

**Issue by allencloud** [docker/swarm#2309]
Hi, All, 

This issue presents two parts:
- How to reproduce **Swarm loses control of docker's event**;
- How to locate the Swarm's code to identify code BUG;

First, Let me describe the issue:**Swarm will miss docker's events if we restart docker engine**.

The test environment has two parts: **One Swarm Binary**,**One Docker Engin**:

<h2>Steps to reproduce the issue:</h2>
1. Start Swarm Manager using `$GOPATH/bin/swarm --debug -l debug manage nodes://10.1.0.108:2376`;
2. Use `docker events` to listen Swarm Events;
3. Use `docker run` to create and start a container on  10.1.0.108, we can find `docker events` returns serveral events as wished;
4. On node 10.1.0.108, we run **service docker restart**;
5. Still on node 10.1.0.108, we `docker run` a container, `docker events` returns nothing.

**Version Details**:

```
~ $  docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/1.2.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   HEAD
 Built:        <unknown>
 OS/Arch:      darwin/amd64
```

<h2>Locate the bug code</h2>

I found that Swarm uses **StartMonitorEvents** to listen on docker's event, if error happened restart listening via a recursive.

```

// StartMonitorEvents monitors events from the engine
func (e *Engine) StartMonitorEvents() {
    log.WithFields(log.Fields{"name": e.Name, "id": e.ID}).Debug("Start monitoring events")
    ec := make(chan error)
    e.eventsMonitor.Start(ec)

    go func() {
        if err := <-ec; err != nil {
            if !strings.Contains(err.Error(), "EOF") {
                // failing node reconnect should use back-off strategy
                <-e.refreshDelayer.Wait(e.getFailureCount())
            }
            e.StartMonitorEvents()
        }
        close(ec)
    }()
}
```

While I add more log in func StartMonitorEvents and func e.eventsMonitor.Start:

```
// StartMonitorEvents monitors events from the engine
func (e *Engine) StartMonitorEvents() {
    log.WithFields(log.Fields{"name": e.Name, "id": e.ID}).Debug("Start monitoring events")
    ec := make(chan error)
    e.eventsMonitor.Start(ec)

    go func() {
        if err := <-ec; err != nil {
            log.Infof("----------------------------------- %v", err)
            if !strings.Contains(err.Error(), "EOF") {
                // failing node reconnect should use back-off strategy
                <-e.refreshDelayer.Wait(e.getFailureCount())
            }
            e.StartMonitorEvents()
        }
        close(ec)
    }()
}
```

AND

```
// Start starts the EventsMonitor
func (em *EventsMonitor) Start(ec chan error) {
    em.stopChan = make(chan struct{})

    responseBody, err := em.cli.Events(context.Background(), types.EventsOptions{})
    if err != nil {
        fmt.Println(err.Error())
        ec <- err
        return
    }
        ...
}
```

Then save the files, compile a new binary and do the steps as Part 1. This time we will get log like this

```
INFO[0000] Registered Engine ubuntu at 10.1.0.108:2376
INFO[0013] ----------------------------------- unexpected EOF
DEBU[0013] Start monitoring events                       id=HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG name=ubuntu
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
DEBU[0056] Engine update succeeded                       id=HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG name=ubuntu
```

We found that StartMonitorEvents did not restart monitoring docker's event as we wish. Swarm just restarts monitoring once like the log showed us.

**Why does this start monitoring fail?**
For Swarm it almost takes no time to start one monitoring event, while for docker engine, it needs much more time to initialize itself. As a result, one start monitoring fails before docker engine start completely. **So, Swarm loses this engine's all events since then.**

I think it is a severe bug for Swarm. Hope one can try this, and then reproduce it. If this issue solved, Swarm will not lose some important events so that inconsistency state of container between Swarm and Docker Engine will disappear a lot.

related issue #2237 

cc @docker/core-swarm-maintainers ?

**Comment by dongluochen** [comment]
Nice catch @allencloud!

**Comment by allencloud** [comment]
I think https://github.com/docker/swarm/pull/2547 fixed this, closing this
