### ISSUE TITLE
Find out the minimum docker engine version Swarm supports?

### ISSUE THREAD

**Issue by allencloud** [docker/swarm#2330]
Hi, All, 

Using Swarm we are all very concerned about what is the minimum docker engine version Swarm supports.

In https://github.com/docker/swarm/blob/master/cluster/engine.go#L37, Swarm implies that 
```
// Minimum docker engine version supported by swarm.
minSupportedVersion = version.Version("1.6.0")
```

While I tried with Swarm 1.2.3 and Docker 1.6.0, unfortunately there is some incompatibility  in the API. Swarm uses engine-api to connect with docker's API, while docker 1.6.0's API version is too old to support engine-api, such as /info API. Related issue #2150 

And I tried docker 1.7.0, although the /info API will be OK, there is something wrong for engine-api to support docker 1.7.0's event API. Therefore, failed again.

docker 1.7.1 failed as well.

And I tried docker 1.8.0, it works fine with Swarm 1.2.3.

So, I think we should update minSupportedVersion in Swarm.

In addition we see that in CI, Swarm supports docker 1.9.0.

My environment:
```
~ $  docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/1.2.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   HEAD
 Built:        <unknown>
 OS/Arch:      darwin/amd64


~ $  docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: swarm/1.2.3
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 1
 dao: 192.168.0.10:2376
  └ ID: CZYK:SOH2:6LGU:NXZU:MLOA:RGP2:LAP4:G3JE:SXPB:SMO5:DMBL:L7RU
  └ Status: Pending
  └ Containers: 0
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 2.053 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-24-generic, operatingsystem=Ubuntu 14.04 LTS, storagedriver=aufs
  └ UpdatedAt: 2016-06-05T11:51:01Z
  └ ServerVersion: 1.7.1
Plugins:
 Volume:
 Network:
Kernel Version: <unknown>
Operating System: darwin
Architecture: amd64
CPUs: 0
Total Memory: 0 B
Name: sunhongliangdeMacBook-Pro.local
Docker Root Dir:
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support
```

**Comment by nishanttotla** [comment]
I think support for 1.6 should be dropped at the very least. 1.7 might stay for a while, depending on usage.

**Comment by allencloud** [comment]
@nishanttotla 
Yes, swarm should have ability to support wide versions of docker engine. 
With docker 1.7.x, code below never returns.https://github.com/docker/swarm/blob/master/cluster/event_monitor.go#L37:
```
responseBody, err := em.cli.Events(context.Background(), types.EventsOptions{})
```

**Comment by xiaods** [comment]
1.9 prefered
