### ISSUE TITLE
[Documentation] Install for production is confusing

### ISSUE THREAD

**Issue by dangoncalves** [docker/swarm#2336]
In install-manual.md, "set up for a discovery backend" step (step 4) tells to connect to manager0 and consul0 but connection to manager0 is not needed at this step. This is confusing because it can be interpreted as running the same command on consul0 and manager0.

"Create swarm cluster" step (step 5) mentions that manager0 and consul0 is on the same host and the examples given use the same IP address for consul0 and manager0 but the "create your instances" step tells to create five different instances. This is really confusing and there is no other mention about using the consul0 and the manager0 on the same host.

Using different instances for consul0 and manager0 is simpler and works well. Documentation should not mention that consul0 and manager0 are on the same host, or it should at least explain, as an introduction, what you get by putting them on the same host.

**Comment by allencloud** [comment]
@dangoncalves 
Thanks for your feedback.
Totally welcome your contribution via PR. Let us make the docs more usable.

**Comment by dangoncalves** [comment]
I created a PR #2337 
Please let me know if it is something is wrong
