### ISSUE TITLE
Swarm Manager does not see new Swarm members while using etcd 

### ISSUE THREAD

**Issue by akomakom** [docker/swarm#2339]
This is a consistent problem, **etcd** has **correct** member information but swarm manager does not notice **changes** unless I **restart** the swarm manager.

## Setup:

* Versions
  * CentOS 7.2.1511 (64 bit) 
  * docker-engine-1.11.1-1.el7.centos.x86_64
  * etcd-2.2.5-1.el7.x86_64
  * all configuration is done via standard puppet modules
* Swarm host runs "swarm" image (SwarmManager) with the following parameters (ps output): 
  *   /usr/bin/docker run --net host -m 0b --name SwarmManager swarm manage -H tcp://0.0.0.0:2375 etcd://127.0.0.1:2379
* Swarm members run "swarm" image with the following parameters (ps output):
  *   /usr/bin/docker run --net bridge -m 0b --name SwarmAgent swarm join --advertise=MEMBER-XX.HOST.NAME:4243 etcd://SWARMMANAGER.HOST.NAME:2379

## Problem

The swarm manager will not see the newly joined member (-02 in this example) until I restart the SwarmManager service (swarm image).   ~~Same with node removals - I have to restart, then it disappears.~~ Correction, removals work, but not via etcd expiration (removed because connection refused)

## Contents of etcd
Notice that there **are two** members.  Checking docker logs on the swarm image on the member machines shows that it's successfully registering every minute.  (**etcdctl watch** confirms this)
```
# etcdctl  ls  /docker/swarm/nodes                                                                                   
/docker/swarm/nodes/MEMBER-01.HOST.NAME:4243
/docker/swarm/nodes/MEMBER-02.HOST.NAME:4243
```

## etcd config

```
ETCD_NAME=default
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380"
ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"
ETCD_ADVERTISE_CLIENT_URLS="http://SWARMMANAGER.HOST.NAME:2379"
ETCD_DEBUG="false"
```

## Docker info 
(this is using the swarm port)
Notice that there is **only one** member

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 1
 MEMBER-01.HOST.NAME: MEMBER-01.HOST.NAME:4243
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 1.033 TiB
  └ Labels: executiondriver=, kernelversion=3.10.0-327.13.1.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
Plugins: 
 Volume: 
 Network: 
CPUs: 33
Total Memory: 1.033 TiB
Name: SWARMMANAGER.HOST.NAME
Docker Root Dir: 
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
```

## Docker Info after restarting SwarmManager

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 0
Images: 5
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 MEMBER-01.HOST.NAME: MEMBER-01.HOST.NAME:4243
  └ Status: Healthy
  └ Containers: 4
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 1.033 TiB
  └ Labels: executiondriver=, kernelversion=3.10.0-327.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
 MEMBER-02.HOST.NAME: MEMBER-02.HOST.NAME:4243
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 1.033 TiB
  └ Labels: executiondriver=, kernelversion=3.10.0-327.13.1.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
Plugins: 
 Volume: 
 Network: 
CPUs: 66
Total Memory: 2.067 TiB
Name: SWARMMANAGER.HOST.NAME
Docker Root Dir: 
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
```

**Comment by dongluochen** [comment]
Can you take a look at Swarm logs to see if there are discovery errors like `time="2016-06-07T14:36:11Z" level=error msg="Discovery error: Unexpected watch error"`? If you are running swarm in a container, it's `docker logs #container`. 

You can also enable swarm debug (-l debug) to get discovery debug info. When a node is added to etcd, there should be debug logs about discovery. 
https://github.com/docker/swarm/blob/master/vendor/github.com/docker/docker/pkg/discovery/kv/kv.go#L115

It could be interoperability problem between etcd and libkv.

**Comment by akomakom** [comment]
I did check it already, it wasn't there, that's why I didn't include it.  Here is what's in there (I first started with both members, then killed 01, then brought it back up a few minutes later - that was yesterday, it still hasn't noticed it)

```
time="2016-06-08T14:22:29Z" level=info msg="Listening for HTTP" addr="0.0.0.0:2375" proto=tcp 
time="2016-06-08T14:22:30Z" level=info msg="Registered Engine MEMBER-02.HOST.NAME at MEMBER-02.HOST.NAME:4243" 
time="2016-06-08T14:22:30Z" level=info msg="Registered Engine MEMBER-01.HOST.NAME at MEMBER-01.HOST.NAME:4243" 
time="2016-06-08T14:53:18Z" level=error msg="Flagging engine as dead. Updated state failed 3 times: Get http://MEMBER-01.HOST.NAME:4243/v1.15/containers/json?all=1&size=0: dial tcp 10.130.240.32:4243: getsockopt: connection refused" id="VYUG:YPCP:ITTF:O7KV:HSWT:HDXU:TNUR:FA6V:CXAZ:NCFR:45FB:PLTG" name=MEMBER-01.HOST.NAME 
time="2016-06-08T14:54:11Z" level=info msg="Removed Engine MEMBER-01.HOST.NAME" 

```

**Comment by akomakom** [comment]
I think that this is my fault - I was restarting the docker service on the members, but not the Swarm Agent service (puppet creates separate systemd entries).  In other words, stopping stops both, but starting only starts docker but not the swarm container.

The reason I saw the inconsistent state is probably due to long etcd expire timeout (it was still in etcd, but Swarm Manager already knew it was down due to connect failures).  Sorry, my bad.  

Thanks for the **-l debug**, that was helpful.
