### ISSUE TITLE
invalid dependency on removed docker/pkg/version

### ISSUE THREAD

**Issue by czankel** [docker/swarm#2351]
go get -u github.com/docker/swarm fails for me with a dependency error on docker/pkg/version:
```
	imports github.com/docker/docker/pkg/version: cannot find package "github.com/docker/docker/pkg/version" in any of:
	/usr/lib/go/src/pkg/github.com/docker/docker/pkg/version (from $GOROOT)
	/root/go/src/github.com/docker/docker/pkg/version (from $GOPATH)
```

which was removed with this commit:

```
commit 49f7b4dafb2fc3d702304ae1bfe5834764692e1d
Author: Vincent Demeester <vincent@sbr.pm>
Date:   Tue Apr 19 16:57:02 2016 +0200

    Remove pkg/version

    Signed-off-by: Vincent Demeester <vincent@sbr.pm>
```

**Comment by xiaods** [comment]
hi @czankel don't found the commit, are u sure the commit is in swarm upstream branch?

**Comment by czankel** [comment]
@xiaods , thanks for the quick reply. The commit is actually in the docker package, which is used by swarm. If you just use the 'go get...' command, does it work for you? Thanks.

**Comment by xiaods** [comment]
go get -u github.com/docker/swarm is works like a charm in my env.

**Comment by ishah-12** [comment]
It didn't work for me. 

If I follow: https://github.com/docker/swarm/blob/master/CONTRIBUTING.md and run the below steps:

cd $GOPATH/src/github.com/docker/swarm
go install .

It gives me the below error:

`api/handlers.go:19:2: cannot find package "github.com/docker/docker/pkg/version" in any of:
        /usr/lib/golang/src/github.com/docker/docker/pkg/version (from $GOROOT)
        /opt/go/src/github.com/docker/docker/pkg/version (from $GOPATH)
../../coreos/etcd/client/auth_role.go:23:2: cannot find package "golang.org/x/net/context" in any of:
        /usr/lib/golang/src/golang.org/x/net/context (from $GOROOT)
        /opt/go/src/golang.org/x/net/context (from $GOPATH)
../go-connections/sockets/proxy.go:9:2: cannot find package "golang.org/x/net/proxy" in any of:
        /usr/lib/golang/src/golang.org/x/net/proxy (from $GOROOT)
        /opt/go/src/golang.org/x/net/proxy (from $GOPATH)`

**Comment by dongluochen** [comment]
@ishah-12 What's your go version?

**Comment by ishah-12** [comment]
1.4.2

**Comment by ishah-12** [comment]
@dongluochen  It did work in the end when using go version 1.6.3 and then running `go get -u github.com/docker/swarm`. 

Can this be part of simple installation instructions in the README ?

The current README points to Swarm documentation and that page seems to go nowhere. As stated below:  
========================================================================
Installation for Swarm Users

For instructions on using Swarm in your dev, test or production environment, refer to the Docker Swarm documentation on docs.docker.com.
========================================================================

**Comment by dongluochen** [comment]
@ishah-12 Thanks for the suggestion. 

> Can this be part of simple installation instructions in the README ?

Go version may change when new Go features are used in Swarm. I feel it better to keep just in the contribution doc. 

The installation should contains link to http://docs.docker.com/swarm/, isn't it? That's the docker doc manual for how to use Swarm. 

Here is the markup. 
```
## Installation for Swarm Users

For instructions on using Swarm in your dev, test or production environment, 
refer to the Docker Swarm documentation on 
[docs.docker.com](http://docs.docker.com/swarm/).
```

**Comment by ishah-12** [comment]
@dongluochen Thanks!
