### ISSUE TITLE
What is the relationship between the swarm and swarmkit?

### ISSUE THREAD

**Issue by maguowei** [docker/swarm#2353]
swarmkit will replace swarm❓

**Comment by xiaods** [comment]
swarmkit will replace kuberenets.

**Comment by conicalflask** [comment]
@xiaods I don't think that answer is clear enough.

Will swarm continue to be maintained now?

**Comment by sampsonhuo** [comment]
I also want to know the question.

**Comment by deviantony** [comment]
I'd even like to know the relation between docker-swarm in 1.12 and Swarmkit. Does 1.12 uses Swarmkit?

**Comment by dongluochen** [comment]
We updated [README](https://github.com/docker/swarm/blob/master/README.md) to clarify the 2 projects. See changes in #2403. 

Let's merge this discussion with #2379.
