### ISSUE TITLE
Swarm docs has same Wrongs

### ISSUE THREAD

**Issue by clhlc** [docker/swarm#2356]
HI ,i find same wrongs in swarm docs "High availability in Docker Swarm"
[https://docs.docker.com/swarm/multi-manager-setup/](url)

In the final ,'Test the failover mechanism',manager-2’s logs  is "Cluster leadership acquired";so manager-2 is **Primary Manager**.

But in "Switch the primary", the docs is "**Role: Replica  <--------- manager-2 is a Replica**".is wrong

**Comment by allencloud** [comment]
@clhlc 
Thanks for your work very much. And welcome your contribution.

**Comment by nishanttotla** [comment]
@clhlc it would be great if you could submit a PR to fix this :). This is where you'd need to look: https://github.com/docker/swarm/blob/master/docs/multi-manager-setup.md
