### ISSUE TITLE
Container name with more than 49 characters causes cryptic error at container start

### ISSUE THREAD

**Issue by michaelzangerle** [docker/swarm#2359]
I have a swarm with ETCD running on two EC2 instances on AWS. Everything works fine until I try to start a container with a name that has more than 49 characters. I can create the container but as soon as I try to start it I get the following cryptic message: 

```
Error response from daemon: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: invalid argument"
Error: failed to start containers: test123-f49e38e8c7b87d7d50f46e30bad.test1234.cloud
```

I did not find any documentation of such a limit and it also works when I run the container directly via the daemon and not the swarm. It's not a real problem but it would be nice to get a meaning full error message if the length of the container name is the real problem here.

**`docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64
```

**`docker info`:**

```
Containers: 15
 Running: 12
 Paused: 0
 Stopped: 3
Images: 7
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 64
 Dirperm1 Supported: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host overlay bridge null
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: ip-172-31-1-144
ID: BB5J:E5CD:OA7C:URTZ:SW4T:NJJK:FEGM:FFAO:L7WI:MOA4:RARO:3K4T
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: ***
Registry: https://index.docker.io/v1/
Labels:
 cloud.test.swarm.type=master
Cluster store: etcd://172.31.1.144:4001
Cluster advertise: 172.31.1.144:0
```

**`uname -a`:**

```
Linux ip-172-31-1-144 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**`cat /etc/lsb-release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
```

**Comment by allencloud** [comment]
Thanks for your feedback.
Your container's name is `test123-f49e38e8c7b87d7d50f46e30bad.test1234.cloud`?

**Comment by michaelzangerle** [comment]
Yes.

**Comment by xiaods** [comment]
interest the limited. do you can provide your step to let me evaluate the bug?

**Comment by michaelzangerle** [comment]
What additional information do you need?

**Comment by xiaods** [comment]
@michaelzangerle i need your run container's script to invest the root cause.

**Comment by michaelzangerle** [comment]
I'm sorry but I have no run script. I'm using docker-php (https://github.com/docker-php/docker-php) to do all the "magic". Maybe the issue is solved with the new docker version anyway. I'm going to close the issue and reopen it if the issue still exists.
