### ISSUE TITLE
Feature: Swarm rolling update w/healthcheck

### ISSUE THREAD

**Issue by jhmartin** [docker/swarm#2366]
The existing swarm functionality provides for --update-parallelism and --update-delay, but if a bad image is deployed there is nothing to stop it from being rolled out entirely.

Instead, leverage the HEALTHCHECK dockerfile entry (if present) and do not consider the current container instance to be 'done' until it passes the healthcheck. 

This also protects against some outside influence causing the application to start slower than normal, combining with the update delay to bring the entire application down.

So when HEALTHCHECK is used, rollouts will go faster as swarm is not waiting needlessly (in the general case), and in the exceptional case it will not proceed until the application is happy.  If the application is fundamentally unhappy then the deployment will not proceed and won't take down all of the healthy containers.

So, if I have a 10 node cluster and set --update-parallelism 2, the first two containers would be restarted under the new image, fail their healthcheck within a defined time period (--update-maxtime perhaps), and cause the rollout to halt -- or even automatically roll back.

Fundamentally, timer-based to rollouts are doomed to trip over themselves at some point.  They will also generally take much longer than needed as the delay will be set to the 99.9th percentile to avoid too much of the application coming down at the same time in the general case.

**Comment by composer22** [comment]
Where is --update-parallelism and --update-delay documented? Where are you referencing HEALTHCHECK???

**Comment by dongluochen** [comment]
@jhamrick The issue you mentioned should go to swarmkit repo and link to https://github.com/docker/swarmkit/issues/641. It's not your fault. There is some confusion on which repo to report Docker-1.12 swarm mode issues and we are working to clarify it.

**Comment by jhmartin** [comment]
Will-do, thank you.

**Comment by jhmartin** [comment]
@composer22 https://docs.docker.com/engine/reference/builder/ for the 1.12 docs references HEALTHCHECK.
