### ISSUE TITLE
Feature: Rolling update percent-parallelism

### ISSUE THREAD

**Issue by jhmartin** [docker/swarm#2367]
With a 10 container environment, an --update-parallelism of 2 is reasonable.  If the application is scaled up to 500 nodes it becomes too short.  Instead allow --update-percent that defines how much of the application can be taken down at a given time on a relative basis.

So, --update-percent 10% would take approximately the same amount of time to deploy regardless if the application is scaled to 10 or 500 nodes, without administratively having to adjust it as the application scales.

**Comment by dperny** [comment]
I think you may want github.com/docker/swarmkit, which is the repository for everything related to the new Docker 1.12 Swarm Mode.

**Comment by nishanttotla** [comment]
@jhmartin as @dperny suggested, do you mind opening this issue on https://www.github.com/docker/swarmkit?

**Comment by jhmartin** [comment]
Yes -- as https://github.com/docker/swarmkit/issues/1085

**Comment by nishanttotla** [comment]
Thanks @jhmartin!
