### ISSUE TITLE
Incorrect case in api fields. 

### ISSUE THREAD

**Issue by suryagaddipati** [docker/swarm#2378]
hi Looks like [docs](https://docs.docker.com/swarm/swarm-api/) have incorrect casing . 

```json
"Node": {
    "Id": "ODAI:IC6Q:MSBL:TPB5:HIEE:6IKC:VCAM:QRNH:PRGX:ERZT:OK46:PMFX",
    "Ip": "0.0.0.0"
```
`Id` should be `ID` and `Ip` should be `IP`. 

Looks like [this commit](https://github.com/docker/swarm/commit/1297a4cef2813839da91bf962beda2e3a35cf77e#diff-a28a4b7a97d2368507318a8565e27ff2L41) changed the case of those fields.

Would this have broken any backward compatibility?

**Comment by allencloud** [comment]
Doc is fixed in PR #2218

**Comment by mstanleyjones** [comment]
#2218 is a huge PR and I'm going to just fix this issue in a new PR, https://github.com/docker/swarm/pull/2491. I'll carry the other PR as well.

**Comment by KostyaSha** [comment]
https://docs.docker.com/swarm/swarm-api/ Still has old info
