### ISSUE TITLE
Router Mesh Session Stickiness

### ISSUE THREAD

**Issue by adamjk-dev** [docker/swarm#2382]
Apologies if this isn't the appropriate place. I asked a few employees at dockercon16 about session stickiness in the built-in router mesh that comes with docker 1.12. Are there any plans to provide capabilities for session stickiness (cookie-based etc.) in this router mesh? As awesome as it would be, not all apps are stateless, and we need to route users to the proper container in certain cases. 

I need to dig more into alternatives, as I heard mention of Interlock and nginx etc., but our use case would be to somehow detect the "events" for all containers to get IP addresses and ports, and update a pool in F5 devices. 

But, it might be nice if session stickiness was provided by the routing mesh, and we could just send traffic to the mesh to be handled.

**Comment by dperny** [comment]
Issues with the new Docker 1.12 Swarm Mode are filed under [docker/swarmkit](github.com/docker/swarmkit). Can you repost this issue there and close this one?

**Comment by adamjk-dev** [comment]
Sure thing, I kind of figured this wasn't the right place.
