### ISSUE TITLE
Should only enforce co-scheduling if container is using old-style links

### ISSUE THREAD

**Issue by tiborvass** [docker/swarm#2384]
From https://github.com/docker/docker/issues/23885#issuecomment-228905441:

> Old-style links are only used when containers are created with "NetworkMode": "default", which Compose only does for v1 files (to preserve backwards compatibility). For v2 files, every container (by default) joins a network created especially for the Compose app.

> I believe the issue is with Swarm. It should only enforce co-scheduling if the container is using old-style links (i.e. if it's created with "NetworkMode": "default"), but it currently always enforces it, regardless of network mode, if the Links key is set.

Ping @nishanttotla

**Comment by aanand** [comment]
Actually, there's already an issue for this - see #1811.

**Comment by tiborvass** [comment]
Haha! Closing as dupe of #1811 :)

**Comment by tiborvass** [comment]
@nishanttotla please verify the milestone this one was put at 1.2.4 but 1811 is put at 1.3.0

**Comment by nishanttotla** [comment]
@tiborvass 1.3.0 is only a tentative milestone for issues to be fixed in the long-term. If we decide to not fix it now, I'll move 1811 back to 1.3.0.
