### ISSUE TITLE
Continuous Delivery Hangs via Swarm since `/networks` API has a long delay in engine.

### ISSUE THREAD

**Issue by allencloud** [docker/swarm#2388]
Hi, All,

Yesterday, one of my friends seek help from me that all delivery jobs hangs in their production environment. 

Here is his environment details:
1.docker engine version: 1.9.1
2.swarm version 1.2.0
3.has a consul for swarm
4.has the same consul for every docker engine.

The problem:
1. Once deliver a container via Swarm, it needs almost 3 minutes. As a result, delivering many containers of production needs much longer time.
2.We do nothing about swarm, directly interact with docker engine, `docker run -d ubuntu:14.04 sleep 1000` hangs for about 1 minute. After that `docker kill containerXXX` will consume 1-3 minutes, too.
3.we stop swarm agent, and repeat step2, no delay happens.

First conclusion, 
Something was related to Swarm.

Start swarm,  then the issue occurs again.

Explore deeper, we found when we stop Swarm, `docker network ls` command has a long delay. At the  situation of stopped Swarm, in the delay duration of `docker network ls`, `docker run` command still hangs for 1-3 minutes. When `docker network ls` finishes, everything is OK.

Then Start Swarm, no `docker network ls` command, but when `docker run`, still hangs. While in the log of Docker Engine, we found someone called `/networks` api. It must be that swarm's RefreshNetworks triggered this API.

In refreshLoop and network event and `docker network create`, swarm will all send a RefreshNetwork request. As a request, hangs happens. If several jobs concurrent dealed, longer time will be delayed.

Why `docker network ls` hangs?
Docker Engine relies on a k/v store to store all network information. If long delay happens when engine communicates with consul, then no network create and no network rm will succeed. Delay happens indeed.

One of the solution:
I think in event of network, refresh all network on the engine is redundant, and in this case almost hangs everything.

#2255 **Refresh single network when network event emitted** will ease this issue.

cc @docker/core-swarm-maintainers

**Comment by dongluochen** [comment]
Thanks Allen for your analysis. It's an interesting issue. It'd be great if we can measure the delay from overlay network and from swarm. Overlay network itself doesn't rely on Swarm. If you still have the environment, can you try to run overlay network without swarm and time the operations? You can follow the instruction at https://docs.docker.com/engine/userguide/networking/dockernetworks/.

**Comment by allencloud** [comment]
Actually, It is in my friend's production environment. When we determine the root cause, I lose the control of that. While network checking is still needed. Thanks a lot @dongluochen

**Comment by allencloud** [comment]
I think the merged PR will ease the issue.
So I close this.
