### ISSUE TITLE
Inconsistent Swarm inspect for a single node manager

### ISSUE THREAD

**Issue by arun-gupta** [docker/swarm#2398]
Using `1.12 RC3` with Docker for Mac

Initialized Swarm mode as `docker swarm init` and that showed the message:

`Swarm initialized: current node (aa3763o02gqqwyagq9on0yc23) is now a manager.`

`docker swarm inspect` shows:

```
docker swarm inspect
[
    {
        "ID": "6ii5sfqk2v5ycf37kb4tnujt8",
        "Version": {
            "Index": 11
        },
        "CreatedAt": "2016-07-06T00:13:08.520785296Z",
        "UpdatedAt": "2016-07-06T00:13:08.642364689Z",
        "Spec": {
            "Name": "default",
            "AcceptancePolicy": {
                "Policies": [
                    {
                        "Role": "worker",
                        "Autoaccept": true
                    },
                    {
                        "Role": "manager",
                        "Autoaccept": false
                    }
                ]
            },
            "Orchestration": {
                "TaskHistoryRetentionLimit": 10
            },
            "Raft": {
                "SnapshotInterval": 10000,
                "LogEntriesForSlowFollowers": 500,
                "HeartbeatTick": 1,
                "ElectionTick": 3
            },
            "Dispatcher": {
                "HeartbeatPeriod": 5000000000
            },
            "CAConfig": {
                "NodeCertExpiry": 7776000000000000
            }
        }
    }
]
```

The output message indicate that the node is server. Shouldn't `Autoaccept` value be `true` for the `manager` role?

**Comment by aaronlehmann** [comment]
> Shouldn't `Autoaccept` value be `true` for the manager role?

No. When you run `docker swarm inspect`, you are inspecting the swarm cluster you created. The default settings are to automatically accept new workers into the cluster, but require approval for managers.

Note that this GitHub repo is for the `swarm` product. For issues related to Docker 1.12's Swarm mode, you should file issues under https://github.com/docker/docker.

**Comment by arun-gupta** [comment]
Reading through the docs clarified the purpose of `AcceptancePolicy` and so closing the bug.
