### ISSUE TITLE
Swarm create container very slow when using overlay network

### ISSUE THREAD

**Issue by xianlubird** [docker/swarm#2401]
When I use swarm in overlay network, I found it create container more slowly with increasing number of containers, I found the reason is that swarm refresh network when a container is created, it will cost much time for waiting response.

**Comment by nishanttotla** [comment]
@xianlubird can you provide more details about your setup and how you start the swarm?

**Comment by xianlubird** [comment]
I use swarm in overlay network, using etcd as kv store. For getting network info , engine will visit etcd through network. So it will become more and more slowly to refresh network. And swarm shouldn't refresh network when container created, at this time, container hasn't `network endpointID` and `ip`, it's useless.

I have raised a issued and PR for docker engine, [engine network list issue](https://github.com/docker/docker/issues/24364) , there's more detail info about `docker info` and `docker version`

Thank you.  @nishanttotla

**Comment by xianlubird** [comment]
Already merged in docker. Done
