### ISSUE TITLE
Please update for engine-api v0.3.3

### ISSUE THREAD

**Issue by onlyjob** [docker/swarm#2404]

**Comment by allencloud** [comment]
@onlyjob 
Could you share more details about of engine-api v0.3.3?
What is the best benefit of this version?

**Comment by onlyjob** [comment]
This would be helpful for consistency as Docker depends on 0.3.3 while Swarm FTBFS with that version. Because of this incompatibility I'm unable to update Swarm in [Debian](http://debian.org)...

**Comment by allencloud** [comment]
ping @nishanttotla @dongluochen @abronan

**Comment by nishanttotla** [comment]
`engine-api` has several new functions in the client interface. It won't be complicated to update it, but will take a little bit of work. We'll do it soon.

**Comment by onlyjob** [comment]
Thanks! :)
