### ISSUE TITLE
Expose health check details in container list

### ISSUE THREAD

**Issue by dhiltgen** [docker/swarm#2415]
In 1.12, engine adds support for container level health checks.  When querying `/containers/json` directly on the engine, this health status is bubbled up as a string appended to the Status field.  If you send this same query to swarm running on the same engine, the health information is missing.  Swarm shouldn't discard this information.

Engine example:
```
"Status": "Up 42 minutes (healthy)"
```

Swarm example for the same container:
```
"Status": "Up 42 minutes"
```

**Comment by allencloud** [comment]
Yes, I think it is needed for 1.2.4

**Comment by allencloud** [comment]
I am afraid in engine-api v0.3.3, there is no Health field in ContainerState. Engine-api update needed and `FullStateString` needs modified.

**Comment by dongluochen** [comment]
@allencloud Yes I have the code ready. It depends on engine-api merge where @nishanttotla is working on it.

**Comment by allencloud** [comment]
@dongluochen 
Could not be better.
