### ISSUE TITLE
Container rescheduling on leader node failure

### ISSUE THREAD

**Issue by dustinblackman** [docker/swarm#2432]
## Overview

I've been going deep in to testing in what network scenarios Docker Swarm will declare a host dead and start rescheduling containers. I've discovered that containers don't reschedule if the leader is the one to fail.

## Systems

- 5 systems, all on the same network.
- Each system is a swarm manager.
- Each system has other containers running along side it (web applications, redis, ect)
- One of these is of course the swarm manager leader

## Issue

If you were to shutdown the swarm manager leader system (easiest way to reproduce), leader reelection happens, but the containers that were on that machine are not rescheduled, even though they were configured to. If you were to shutdown a swarm manager follower, it works as expected where containers are moved to another appropriate system.

From what I understand, the swarms state is saved in the discovery service (in my case Consul), shouldn't Swarm verify what containers were lost on the swarm manager leader after reelection? 

Is the system scenario I've laid out the wrong way to accomplish Swarm with rescheduling? The idea is running a Swarm with the least amount of systems/money spent.

**Comment by dongluochen** [comment]
Thanks for providing detail information. I think this is a case that currently Swarm doesn't handle. 

> the swarms state is saved in the discovery service (in my case Consul), shouldn't Swarm verify what containers were lost on the swarm manager leader after reelection? 

Swarm uses `Consul` for node discovery only. It doesn't store container information. 

Swarm master has a **cache** of current running containers in every node. When a node fails, it reschedules containers from that cache. When master fails, the newly elected master doesn't have that cache so it cannot reschedule those containers.

**Comment by dustinblackman** [comment]
Thanks for the reply, @dongluochen! Would this be something that would be supported in the future storing the cache elsewhere then the swarm master?

**Comment by dongluochen** [comment]
@dustinblackman It'd come down to a distributed data storage to keep running configuration. This and related functionalities are implemented in [Swarmkit](https://github.com/docker/swarmkit) and integrated into Docker 1.12. You may want to take a look.

**Comment by dustinblackman** [comment]
Brilliant. If it's done there, I suppose it won't be completed here. I'll close this, thanks a lot!
