### ISSUE TITLE
Docs for rescheduling typo

### ISSUE THREAD

**Issue by amouat** [docker/swarm#2438]
The docs on swarm rescheduling at https://docs.docker.com/swarm/scheduler/rescheduling/ currently say:

> To set the on-node-failure policy with a reschedule environment variable:
> 
> $ docker run -d -e reschedule:on-node-failure redis

I'm pretty sure it should actually say`-e reschdule=on-node-failure` with an `=` sign, unless there is a syntax I'm unaware of. At any rate with Docker 1.12:

```
amouat@marvin proj$ docker run --env="reschedule:on-node-failure" debian env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=5109c5e59dca
HOME=/root
amouat@marvin proj$ docker run --env="reschedule=on-node-failure" debian env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=1ee10bbd48f2
reschedule=on-node-failure
HOME=/root
```

**Comment by nishanttotla** [comment]
@amouat I think you're right. Would you mind sending out a PR to fix this? We can discuss more there.

**Comment by amouat** [comment]
I see someone has got this. Thanks!

**Comment by nishanttotla** [comment]
Fixed in https://github.com/docker/docker.github.io/pull/236
