### ISSUE TITLE
Incorrect content type in header

### ISSUE THREAD

**Issue by alktlr** [docker/swarm#244]
The [Jenkins Docker plugin] (https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin) is unable to read the output from swarm because the content type is "text/plain". The correct content type should be "application/json".

How to reproduce:

wget --server-response http://&lt;docker_host&gt;:&lt;port&gt;/version
  HTTP/1.1 200 OK
  Content-Type: application/json
  Job-Name: version
  Date: Wed, 14 Jan 2015 14:18:32 GMT
  Content-Length: 163
Length: 163 [application/json]

wget --server-response http://&lt;swarm_ip&gt;:&lt;port&gt;/version
  HTTP/1.1 200 OK
  Date: Wed, 14 Jan 2015 14:19:22 GMT
  Content-Length: 114
  Content-Type: text/plain; charset=utf-8
Length: 114 [text/plain]

**Comment by vieux** [comment]
Fixed in 32c135314dd9573d54f5ec104537f9b51eb772f2

**Comment by alktlr** [comment]
Thanks. The fix has been verified.
