### ISSUE TITLE
Does 1.12 require key-value store for a swarm cluster?

### ISSUE THREAD

**Issue by alfredcs** [docker/swarm#2446]
Set up a 1.12 swarm cluster and it can deploy services just fine. However when created a new network mesos with subnet 10.200.0/24 on the manager node, it failed to be propagated to the clients. The question is does the cluster need a separated key-value store? Also noticed all services were deployed to the bridge subnet, instead of he default overly subnet ingress. Is that normal? 

==== On the manager node all seem to be there including default ingress and the newly created network mesos ==============

[root@dcos3 etc]# docker node ls
ID                           HOSTNAME           STATUS  AVAILABILITY  MANAGER STATUS
0sa3mgu3mnfk0eyetxezohw3e    dcosa05.novalocal  Ready   Active        
16k4jlnrb89bwiqgacsnpwbbc *  dcos3.novalocal    Ready   Active        Leader
2mn00dsu17zpz6v8pzvuzxpwh    dcosa13            Ready   Active        
3mhev76f7cv66r80jqp3fqt5u    dcosa11            Ready   Active        
57x09tjzp78xo5zole97gzv9o    dcosa04.novalocal  Ready   Active        
6dpw63mg4n6tpoh49h5rqcmqz    dcosa01.novalocal  Ready   Active        
6gnnuc73d40we0q6wygq0q68m    dcosa12            Ready   Active        
7qbqmjz10edj1conwss0aztd0    dcos2.novalocal    Down    Active        
93muxpsb5rn9tp5gtpyks0dzc    dcosa14            Ready   Active        
9rfl1sx05ula1aivwdl7xnmbk    dcosa03.novalocal  Ready   Active        
9ryqg642s008o1d8namysnz97    dcosa02            Ready   Active        
9ygj0dm5nk09papeubjhkoth0    dcosa08            Ready   Active        
a5dnfyu2q4oy2gqqyxz60gz2f    dcosa17            Ready   Active        
afjicz2a6n61fa9nxkzh9bcn1    dcosa15            Ready   Active        
bkc6l8e0eh569z9tx2y2i9w2c    dcosa07            Ready   Active        
cz5oj42fwd6srer4lzk5xhhjz    dcosa06            Ready   Active        
d8m7hfdbjnrnba22nnf6gifuz    dcosa09            Ready   Active        
dtswmtrm053osenehm4irwnoa    dcosa10            Ready   Active  

[root@dcos3 etc]# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
3d7a1ab933ad        bridge              bridge              local               
8acecd158b7f        docker_gwbridge     bridge              local               
3943f71b4384        host                host                local               
9zct0s5ha0rb        ingress             overlay             swarm               
ewwhwqqgqm7e        mesos               overlay             swarm               
2a9b4d560ad3        none                null                local  

[root@dcos3 etc]# docker network inspect mesos
[
    {
        "Name": "mesos",
        "Id": "ewwhwqqgqm7ewk8p0xbjy799e",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.200.0.1/24",
                    "Gateway": "10.200.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": null,
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "257"
        },
        "Labels": null
    }
]

==== On the client side, the newly created network mesos is missing but default ingress is there =======

[root@dcosa05 ~]# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
133a6f767d90        bridge              bridge              local               
d82e93d0e4db        docker_gwbridge     bridge              local               
088afbf5e22b        host                host                local               
9zct0s5ha0rb        ingress             overlay             swarm               
cc00a2fa70f8        none                null                local

**Comment by fideloper** [comment]
I've run into a bunch of this playing with docker-swarm today:

1. Overlay networks don't appear on the worker nodes until you create a service with them
2. If you get that far and the overlay network appears to not work, [ensure you have opened all the ports (tcp and udp) necessary](https://docs.docker.com/swarm/plan-for-production/). On AWS, I finally got everything working when opening all TCP/UDP traffic to the servers (just to test it out).

**Comment by mimousewu** [comment]
The new docker swarm do not need a key-value store, or it use official online key-value store? You know that docker official service is not that easy to access in some place in this world. And this will driven unstable.

**Comment by dongluochen** [comment]
There is some confusion in this thread between Swarm project and the new Swarm mode in Docker 1.12. Please read the difference at https://github.com/docker/swarm#swarm-disambiguation. Please distinguish documents between the 2 projects. If you are just starting on orchestration, you may try Docker swarm mode from Docker 1.12. And open issues at https://github.com/docker/swarmkit for Swarmkit project. 

@mimousewu Docker 1.12 Swarm mode has a built-in key value store in the nodes. It doesn't rely on external key-value store. https://github.com/docker/swarmkit is the right repository for that.

**Comment by dongluochen** [comment]
@alfredcs You are Docker 1.12 swarm mode, please use https://github.com/docker/swarmkit for issues. Closing this thread.
