### ISSUE TITLE
docker for batch jobs/small jobs 

### ISSUE THREAD

**Issue by kartikjoshi07** [docker/swarm#2449]
Is there any use case where docker is used for batch jobs/small jobs, and that requires a scheduler queue to schedule them ??  In swarm if we don't have enough resources, it rejects the request, and doesn't queue it. If we want to schedule batch jobs and services together, we will need a scheduler queue then. is there any support for such use cases in swarm. I'm new to swarm. Please help :)

**Comment by dongluochen** [comment]
I see you have opened issue on https://github.com/docker/swarmkit/issues/1388 which is the right place for this question.
