### ISSUE TITLE
How to update Swarm 1.2.3 to Swarm 1.2.5?

### ISSUE THREAD

**Issue by vingrad** [docker/swarm#2461]
How to update Swarm 1.2.3 to Swarm 1.2.5?

**Comment by dongluochen** [comment]
Swarm is stateless besides node discovery. You can just start Swarm 1.2.5 the same way you start Swarm 1.2.3. (The funny thing is you can run both swarm clusters at the same time.)

**Comment by allencloud** [comment]
I think dongluo has provided the easiest way. Closing this.
feel free to reopen this if more help needed.
