### ISSUE TITLE
Docker Swarm ignores container constraints when performing the pull operation

### ISSUE THREAD

**Issue by groyee** [docker/swarm#2467]
My Swarm is cluster is getting bigger and bigger.

Every time I change one of my images, docker swarm will pull the image to all nodes in my cluster. Obviously this operation is very time consuming.

Let's say that in my docker-compose.yml I added a constraint: **_"constraint:node==*categorization*"_**

docker swarm will still pull the image to all my nodes even though it will never run there because of my constraint.

**Comment by nishanttotla** [comment]
@groyee as of now, it is not possible to specify node constraints for pulling operations. Currently, constraints and affinities only work when doing `docker run`. I'll close this issue, and let's do any follow-up discussion on #1692
