### ISSUE TITLE
How replication control and load balancing being taken care of?

### ISSUE THREAD

**Issue by sourav82** [docker/swarm#247]
I wanted to create multiple replicas of same docker containers which should be replicated amongst the swarm nodes and a load balancer in place to balance the request to those replicas. Something similar to kubernetes pods, replicationControllers and services.

How can we do this using docker swarm?

**Comment by vieux** [comment]
For the load balancer part you need something like this:http://jasonwilder.com/blog/2014/03/25/automated-nginx-reverse-proxy-for-docker/
Listen to the swarm events api and rewrite your configuration accordingly.

For the rest, we are waiting for docker compose to add those features, you'll need to do it manually for now.

**Comment by sourav82** [comment]
Thanks @vieux. I noticed if one swarm node goes down, then the container scheduled on it marked as pending but not rescheduled to other available swarm nodes. From the manager node, I'm getting below logs -

ERRO[3121] [3FLV:RF2L:CXDR:PF3Y:QC7S:Y7SY:JLZF:TJH5:HEXA:FH52:YUCP:ASSB/etp-ProLiant-DL180-G6-3] Flagging node as dead. Updated state failed: Get http://10.227.125.3:2375/v1.15/containers/json?all=1&size=0: dial tcp 10.227.125.3:2375: connection refused

What is expected here? Should it wait forever for the down node to come up or it will try to reschedule the containers to other available nodes?

One more question, may be silly though, I noticed in your demo you were not providing -H switch with docker cli to connect to swarm node and port. Where do I need to configure this for docker so that I do not have to specify -H with swarm ip and port? I tried in /etc/init/docker.conf with DOCKER_OPTS but it is not able to connect while starting the daemon. But with cli, it is able to connect.

**Comment by david-guenault** [comment]
@sourav82 for your -H problem the right syntax is DOCKER_OPTS="-H tcp://0.0.0.0:2375" where 0.0.0.0 will answer on every network interfaces. Since it is an http api just issue a curl http://localhost:2375 from your server and check that it answer 404 Not found.

**Comment by sourav82** [comment]
Thanks @david-guenault. Will try with it.
