### ISSUE TITLE
Create Service Bug

### ISSUE THREAD

**Issue by brainqi1991** [docker/swarm#2473]
I have installed the latest version docker:
```
[root@docker-manager01 ~]# docker --version
Docker version 1.12.1, build 23cf638
```

There are 2 managers and 3 workers in the cluster.
I'd like to create a service with 5 replicas named `hello-node` and using an image called `reg1.jzez.com/hello-node:1.0`.
```
docker service create --replicas 5 --name hello-node --update-delay 10s -p 3000:3000 reg1.jzez.com/hello-node:1.0
```

However, there is no image called `reg1.jzez.com/hello-node:1.0`.
So,it'll not be successful.

After that, i pull `reg1.jzez.com/hello-node:1.0` from my own private regirstry server at one node in the cluster.

Then the bug appered, about half an hour later, execute:
```
[root@docker-manager01 ~]# docker service ls
ID             NAME        REPLICAS             IMAGE               COMMAND
9rbcpg4qi712  hello-node    18/5      reg1.jzez.com/hello-node:1.0  
```
![image](https://cloud.githubusercontent.com/assets/10718925/18193846/ff5003d6-7113-11e6-86b6-07363a6b9fe7.png)
you can see that  the `REPLICAS` was `18/5`.

That's a bug.   :(

**Comment by allencloud** [comment]
@brainqi1991 
Thanks for your feedback about Swarm Mode in docker. 
Actually It is a SwarmKit issue, not Swarm issue.
I think your had better to report this issue in https://github.com/docker/swarmkit/issues or https://github.com/docker/docker/issues.

Or you can get some reference about Swarm and Swarmkit project here: https://github.com/docker/swarm/blob/master/README.md#swarm-disambiguation

I am closing this. Good luck.

**Comment by brainqi1991** [comment]
Thanks. I'll take a look the swarmkit project.
