### ISSUE TITLE
Assigning service published ports to IP

### ISSUE THREAD

**Issue by quentinsch** [docker/swarm#2478]
Missing the option to assign a published port to a specified IP instead of all host IPs.
When you create a service with a published port, this port is assigned to all host IPs. You cannot create a new service on the same port because this is already in use.

**Comment by michelvocks** [comment]
Hello @quentinsch 
First of all you are using the term "service". I'm correct that you are using docker 1.12 with the internal swarm mode? If yes, please keep in mind that those issues should be created in the [docker/docker](https://github.com/docker/docker) repository. 

To answer your question. This is actually possible like described [here.](https://docs.docker.com/engine/reference/run/#/expose-incoming-ports)

> -p=[]      : Publish a container᾿s port or a range of ports to the host
               format: ip:hostPort:containerPort | ip::containerPort | hostPort:containerPort | containerPort

**Comment by rtuk** [comment]
Hello @michelvocks 
Running the docker service create command with the suggested syntax results in an error.

Command:
`docker service create --name test -p 192.169.2.8:80:80 nginx`

Result:
`invalid argument "192.169.2.8:80:80" for p: HostIP is not supported by a service.
See 'docker service create --help'.`

We will raise this issue again in the [docker/docker](https://github.com/docker/docker) repository.

**Comment by michelvocks** [comment]
@rtuk 
Please have a look at my first post. You are using Docker Swarm Mode which uses the [Docker Swarmkit](https://github.com/docker/swarmkit). This is completely different from the docker swarm orchestration platform here. You can also find more information about the difference here: https://github.com/docker/swarm#swarm-disambiguation

Within the docker swarm orchestration platform this is possible like shown below:
```
root@c69e67650791:/go/src/github.com/docker/docker# docker -H :4000 run -p 172.18.0.1:8080:80 -d nginx
800823cde4cee567b7260c75ff6a532db8e1b66cef5ce64e45f63f966d820732
root@c69e67650791:/go/src/github.com/docker/docker# docker -H :4000 run -p 172.17.0.2:8080:80 -d nginx
7debc63af9c3830a0078607cc506b755dcfa00734c8fea48331e13ecdc9c0e3e
root@c69e67650791:/go/src/github.com/docker/docker# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
800823cde4ce        nginx               "nginx -g 'daemon ..."   3 seconds ago       Up 2 seconds        443/tcp, 172.18.0.1:8080->80/tcp   elated_shaw
7debc63af9c3        nginx               "nginx -g 'daemon ..."   58 seconds ago      Up 57 seconds       443/tcp, 172.17.0.2:8080->80/tcp 
```

**Comment by nishanttotla** [comment]
@quentinsch as @michelvocks pointed out, this issue does not belong on https://www.github.com/docker/swarm, since it's related to the new Swarm Mode features. See "Swarm Disambiguation" (https://github.com/docker/swarm/blob/master/README.md).

I'm closing this issue, please open on https://www.github.com/docker/docker.
