### ISSUE TITLE
Allowing `addr` to be hostname

### ISSUE THREAD

**Issue by krallin** [docker/swarm#248]
What would be the blockers (if any) that need to be resolved to allow `addr` to be a hostname (in `swarm join`)? 

When using SSL, forcing the advertised address (which I understand `swarm manage` will collect to) to be a hostname makes things a little bit more complicated than they should (i.e. you need a certificate with an IP SAN, and generating one with OpenSSL isn't exactly the most intuitive thing either).

Or maybe i'm missing something entirely?!

Happy to help if possible,

Thanks!

**Comment by vieux** [comment]
@krallin nothing!
I agree we should have it, I'll make a PR

**Comment by vieux** [comment]
@krallin please take a look at #250

**Comment by krallin** [comment]
Thanks! I'll close this issue and comment in the PR.

Cheers,
