### ISSUE TITLE
Privileged containers on swarm with mesos?

### ISSUE THREAD

**Issue by Spritekin** [docker/swarm#2480]
Hi,
Is it possible to launch privileged containers using swarm? I need to run an image that mounts an s3 bucket using fuse-s3. 
Locally I can do it.
If I send the run command straight to a node in the cluster it works fine.
But if I send it to swarm, it loses the privileged flag.

Is it supported? Any plans to support it?

**Comment by michelvocks** [comment]
Hello @Spritekin 
I tried it out and it works quite well for me:

```
root@67cf0a75e6e3:/go/src/github.com/docker/docker# docker -H :4000 run -d --privileged nginx
7788e30bd08b772796faa35afe77b63256512074e96e381619e38c15d6779510
root@67cf0a75e6e3:/go/src/github.com/docker/docker# docker -H :4000 inspect --format='{{.HostConfig.Privileged}}' 7788e30bd
true
```

The output of `docker info` as well as the used docker swarm version would help here.

**Comment by Spritekin** [comment]
@michelvocks 
Sorry for not answering before. I'm trying to resolve other problems with swarm (i.e. receives offers from mesos for a few seconds then stops receiving them). Will come back later as this has lower priority.

**Comment by Spritekin** [comment]
Hi @michelvocks,
Unfortunately it doesn't work for me. 
Maybe I should specify I run swarm on mesos. This is my command:
docker -H tcp://172.31.33.146:2376 run --privileged -e TEST=123 --name test -c 1 hello-world

But mesos says:
```
I1006 02:37:42.074637  4424 docker.cpp:809] Running docker -H unix:///var/run/docker.sock run --cpu-shares 10 -e MESOS_SANDBOX=/mnt/mesos/sandbox -e MESOS_CONTAINER_NAME=mesos-22467ff6-50c5-4e71-bf75-d13ecba128ec-S4.89baa3e7-4f54-49d5-8837-1451916d3d07 -v /var/lib/mesos/slave/slaves/22467ff6-50c5-4e71-bf75-d13ecba128ec-S4/frameworks/a2853a78-7cba-455a-99c7-d73bb5cbda95-0022/executors/test.466bc3e8bc7b/runs/89baa3e7-4f54-49d5-8837-1451916d3d07:/mnt/mesos/sandbox --net bridge --label=com.docker.swarm.mesos.task=test.466bc3e8bc7b --label=com.docker.swarm.mesos.name=test --env=TEST=123 --name mesos-22467ff6-50c5-4e71-bf75-d13ecba128ec-S4.89baa3e7-4f54-49d5-8837-1451916d3d07 hello-world
```
So my env variable passed to the command, but the privileged flag did not.

**Comment by Spritekin** [comment]
In order to test mesos can pass the privileged flag, I started a marathon service with privileges, this is the startup command:
```
I1006 03:22:04.837775  2328 docker.cpp:809] Running docker -H unix:///var/run/docker.sock run --privileged --cpu-shares 1024 --memory 134217728 -e MARATHON_APP_VERSION=2016-10-06T03:21:34.594Z -e HOST=172.31.33.146 -e MARATHON_APP_RESOURCE_CPUS=1.0 -e MARATHON_APP_RESOURCE_GPUS=0 -e MARATHON_APP_DOCKER_IMAGE=hello-world -e PORT_10000=25193 -e MESOS_TASK_ID=testprivileged.0df2290e-8b74-11e6-87ce-3632c2042977 -e PORT=25193 -e MARATHON_APP_RESOURCE_MEM=128.0 -e PORTS=25193 -e MARATHON_APP_RESOURCE_DISK=0.0 -e MARATHON_APP_LABELS= -e MARATHON_APP_ID=/testprivileged -e PORT0=25193 -e MESOS_SANDBOX=/mnt/mesos/sandbox -e MESOS_CONTAINER_NAME=mesos-22467ff6-50c5-4e71-bf75-d13ecba128ec-S2.1a80e033-baf8-4fc7-9534-704ccfc6ae0c -v /var/lib/mesos/slave/slaves/22467ff6-50c5-4e71-bf75-d13ecba128ec-S2/frameworks/22467ff6-50c5-4e71-bf75-d13ecba128ec-0000/executors/testprivileged.0df2290e-8b74-11e6-87ce-3632c2042977/runs/1a80e033-baf8-4fc7-9534-704ccfc6ae0c:/mnt/mesos/sandbox --net host --name mesos-22467ff6-50c5-4e71-bf75-d13ecba128ec-S2.1a80e033-baf8-4fc7-9534-704ccfc6ae0c hello-world
```

You can see the privileged flag there. So the problem is not mesos.

**Comment by Spritekin** [comment]
Also tried the REST API, which should be the same but just in case:
```
curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d '{"Image":"hello-world","HostConfig":{"CpuShares":1,"Privileged":true}}' http://172.31.33.146:2376/containers/create?name=Test1
```

But again the privileged flag never reached the agent.

**Comment by Spritekin** [comment]
@michelvocks 
The problem is in cluster/mesos/task/task.go
The build method should be:
```
	t.Container = &mesosproto.ContainerInfo{
		Type: mesosproto.ContainerInfo_DOCKER.Enum(),
		Docker: &mesosproto.ContainerInfo_DockerInfo{
			Image: &t.config.Image,
			Privileged: &t.config.HostConfig.Privileged,  <<<<<<<<<< ADD THIS!!!!
		},
	}
```

However, I won't make a patch until my other pending PRs are accepted and committed into the code. Every time I send a patch the build system rejects it even when they have been checked and there is nothing wrong and I have them in use for months.

If anyone wants to make a patch using this feel free to do so.

Luck!
Guimo

**Comment by nishanttotla** [comment]
Closing due to https://github.com/docker/swarm/pull/2853
