### ISSUE TITLE
can't schedule a container that binds a port on a machine that has a stopped contianer binding the same port

### ISSUE THREAD

**Issue by vikstrous** [docker/swarm#2483]
With swarm you can't schedule a container that binds a port on a machine that has a stopped contianer binding the same port. This is a problem because, for example, if you want to turn off your web server temporarily and run a standalone let's encrypt server on that port on the same machine, you can't do it through swarm.

**Comment by michelvocks** [comment]
This seems to be intended. I'm not quite sure why:

`swarm/scheduler/filter/port.go`
```
// 2/ If the port was bound (e.g. -p 80:80) but the container is stopped,
//    NetworkSettings.Port will be null and we have to check
//    HostConfig.PortBindings to find out the mapping.
```

**Comment by dongluochen** [comment]
This is to avoid port conflicts in several scenarios. `docker run` is `docker create` followed by `docker start`. If only running containers are checked, 2 `docker run` commands may result in 1 successful, the other one would finish `docker create` but fail at `docker start`. A dead container is left behind. 

There is another approach in deployment that users may create all the containers first, then start them. Allowing port reuse would fail this approach.

**Comment by vikstrous** [comment]
This makes it impossible to replace a container safely. Normally the way to replace a container safely is to create a new one, stop the old one, rename it, rename the new one over the old one, start the new one and remove the old one. However, this restriction makes this approach impossible. Is there some other way of replacing container safely? How do others do it?

We are using this renaming approach to replace all containers that don't have bound ports. Is there any other restriction we should be aware of that will make replacing a container via renaming impossible through swarm?
