### ISSUE TITLE
Swarm not declining mesos offers correctly

### ISSUE THREAD

**Issue by Spritekin** [docker/swarm#2498]
As the title says, swarm gets the offers and some are declined but others are not. At the end it gets all offers and doesn't release them

Here is an example log. I have removed lines not relevant to this problem. My swarm is configured to release offers after 5 seconds which is why there is a delay of 5 seconds between the time the offers are received and the time it starts removing offers.

```
time="2016-09-28T10:35:43Z" level=debug msg="Offers received" name=mesos offers=108 
time="2016-09-28T10:35:44Z" level=debug msg="Removing offer" name=mesos offerID="&OfferID{Value:*dec69f38-3edf-45e9-aca1-164c49e6bbb1-O441231,XXX_unrecognized:[],}" 
time="2016-09-28T10:35:48Z" level=debug msg="Removing offer" name=mesos offerID="&OfferID{Value:*dec69f38-3edf-45e9-aca1-164c49e6bbb1-O441231,XXX_unrecognized:[],}" 
time="2016-09-28T10:35:49Z" level=debug msg="Removing offer" name=mesos offerID="&OfferID{Value:*dec69f38-3edf-45e9-aca1-164c49e6bbb1-O441232,XXX_unrecognized:[],}" 
time="2016-09-28T10:35:49Z" level=debug msg="Offer \"dec69f38-3edf-45e9-aca1-164c49e6bbb1-O441232\" declined successfully" name=mesos 
time="2016-09-28T10:35:49Z" level=debug msg="Removing offer" name=mesos offerID="&OfferID{Value:*dec69f38-3edf-45e9-aca1-164c49e6bbb1-O441233,XXX_unrecognized:[],}" 
time="2016-09-28T10:35:49Z" level=debug msg="Offer \"dec69f38-3edf-45e9-aca1-164c49e6bbb1-O441233\" declined successfully" name=mesos 
time="2016-09-28T10:35:49Z" level=debug msg="Removing offer" name=mesos offerID="&OfferID{Value:*dec69f38-3edf-45e9-aca1-164c49e6bbb1-O441234,XXX_unrecognized:[],}" 
time="2016-09-28T10:35:49Z" level=debug msg="Offer \"dec69f38-3edf-45e9-aca1-164c49e6bbb1-O441234\" declined successfully" name=mesos 
```

Now this is the problem. Look at offers O441232, O441233 and O441234. They are all removed and the next line tells us the offer was removed successfully.

But look at O441231... there are two removing offer messages but no success message. And I'm quite sure I have searched the log and there are no success messages for that offer. In fact the code makes it impossible to get that message twice.

This code is from mesos/cluster.go. There are no loops in there, each offer is registered then set to sleep for the time of the offerTimeout then it calls removeOffer (which prints the Removing offer message), and if the remove is successful it should print the "Offer declined successfully" or should print an error message. It is not possible not to print something.

```
func (c *Cluster) addOffer(offer *mesosproto.Offer) {
    s, ok := c.agents[offer.SlaveId.GetValue()]
    if !ok {
        return
    }
    s.addOffer(offer)
    go func(offer *mesosproto.Offer) {
        time.Sleep(c.offerTimeout)
        // declining Mesos offers to make them available to other Mesos services
        if c.removeOffer(offer) {
            if _, err := c.scheduler.driver.DeclineOffer(offer.Id, &mesosproto.Filters{}); err != nil {
                log.WithFields(log.Fields{"name": "mesos"}).Errorf("Error while declining offer %q: %v", offer.Id.GetValue(), err)
            } else {
                log.WithFields(log.Fields{"name": "mesos"}).Debugf("Offer %q declined successfully", offer.Id.GetValue())
            }
        }
    }(offer)
}

func (c *Cluster) removeOffer(offer *mesosproto.Offer) bool {
    log.WithFields(log.Fields{"name": "mesos", "offerID": offer.Id.String()}).Debug("Removing offer")
    s, ok := c.agents[offer.SlaveId.GetValue()]
    if !ok {
        return false
    }
    found := s.removeOffer(offer.Id.GetValue())
    if s.empty() {
        // Disconnect from engine
        s.engine.Disconnect()
        delete(c.agents, offer.SlaveId.GetValue())
    }
    return found
}
```

So two problems here:
a. The Scheduler is registering an offer twice or mesos is sending an offer twice (unlikely).

b. When the offer is removed, the process is suffering a code lock. This I suspect because the offers are really removed in the mesos/agent.go, and there are locks involved. This is the code:

```
func (s *agent) removeOffer(offerID string) bool {
    s.Lock()
    defer s.Unlock()
    found := false
    _, found = s.offers[offerID]
    if found {
        delete(s.offers, offerID)
    }
    return found
}
```

In theory it should work perfectly, but it doesn't.

c. Other suspicion is that on mesos/cluster.go in the addOffer code, specifically here:

```
    s, ok := c.agents[offer.SlaveId.GetValue()]
    if !ok {
        return
    }
```

It should probably decline the offer if there is an error (!ok) as:
   c.scheduler.driver.DeclineOffer(offer.Id, &mesosproto.Filters{});

I really need to add a lot of debug code here but something is definitely fishy.

Luck!

**Comment by Spritekin** [comment]
Just noticed the code can fail removing the offer and not inform it has failed. It will fail silently.
Worse yet, if it fails silently, the offer is never declined.
The fact that the program fails to remove the offer from a list should not prevent from calling the decline offer.

**Comment by nishanttotla** [comment]
Closing due to https://github.com/docker/swarm/pull/2853
