### ISSUE TITLE
swarm mode container published port can't be curled from another container

### ISSUE THREAD

**Issue by hmdhasani** [docker/swarm#2501]
My scenario:
I created a service that publish sth on port 8080 host (host ip is 172.10.10.10)
running 
curl http://172.10.10.10:8080/
on host gave me what I expected
but calling this from another container result in timed out
curling another port that is mapped by a non swarm container works fine

**Comment by slawekgh** [comment]
What OS ? What docker version ? If Centos there are many issuea about firewalld, if Ubuntu there are issues with 14.04 , on 16.04 works fine

**Comment by hmdhasani** [comment]
Containers: 16
 Running: 9
 Paused: 0
 Stopped: 7
Images: 198
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 473
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: active
 NodeID: et9w8rc33fdzhi9hm4edbxlgv
 Is Manager: true
 ClusterID: anoyn17cbeogyvwawtezzhurb
 Managers: 2
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.16.111.85
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-69-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 15
Total Memory: 29.45 GiB
Name: yusef
ID: UVTY:3N6S:NJ4J:IU2J:VIJ7:JPZS:GDQT:CYYN:V6WN:WDE7:VJRY:6J52
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Comment by slawekgh** [comment]
There are many problems with 14.04. Test your environment on 16.04.  For me (mamy times)  it aways worked

**Comment by hmdhasani** [comment]
generally, which distribution and version of linux do you think fits best with docker and swarm mode?

**Comment by slawekgh** [comment]
Ubuntu 16.04

**Comment by dongluochen** [comment]
@hmdhasani Thanks for reporting issue. Swarm mode related questions should be reported at [docker/docker](https://github.com/docker/docker/issues). See https://github.com/docker/swarm#swarm-disambiguation. 

Thank @slawekgh for answering.
