### ISSUE TITLE
Deploy an app on multiple nodes with a single command.

### ISSUE THREAD

**Issue by neddogg** [docker/swarm#2506]
Hi Everyone,

I have setup a docker swarm of three agents (agent1, agent2, agent3), one master and I using zookeeper as my scheduler. I was able to deploy my logstash app on swarm with the following commands:

    docker -H <ip_of_master>:4000 run -it --rm logstash -e 'input { stdin { } } output { stdout { } }'

I did that 6 times and swarm deployed logstash on the agents in the following order. First on agent2,  agent2 again, then agent2 again, followed by agent1, agent2 again and finally agent3.

Now what I want to do is combine all these 6 times deploys on a single command. That is I was wondering if there is a mean to tell swarm that I want a deployment of 6 instances of logstash ( **this should done on a single command.**) and swarm just does that for me.

Any clues please?
Thanks.

**Comment by dongluochen** [comment]
Swarm doesn't support this directly because it complies with Docker API. You may use Docker-compose `scale` command for your problem. See https://docs.docker.com/compose/swarm/.

**Comment by neddogg** [comment]
@dongluochen Thanks for the quick reponse. I will give a try on that.

**Comment by neddogg** [comment]
@dongluochen Thanks once more, I was able to get it working by pulling the logstash image from my docker hub on swarm, write a docker-compose.yml file and deploying it with docker-compose.
In short I did was

    docker -H <master_ip>:4000 pull myrepo/mylogstash:v1

docker-compose.yml
    web:
      image: myrepo/mylogstash:v1

Finally

    docker-compose -H <master_ip>:4000 scale web=6
