### ISSUE TITLE
How to deal with --link --volume_from network container etc.

### ISSUE THREAD

**Issue by resouer** [docker/swarm#251]
In a word, most of the cases in real world requires relationship between Docker containers like --link --volume-from --net=container, that means, at least, swarm should be able to schedule those containers to one host.

But I did not see this kind of strategy in swarm currently, is it under developing or swarm has other approach?

**Comment by Tebro** [comment]
+1 for this, at least until there is a solution that allows containers to communicate when on different hosts (some kind of VPN setup?) it would be really useful if swarm put containers with link relations on the same host. I assume this should account for the future when docker compose starts to become more stable.

**Comment by vieux** [comment]
Those issues will be resolved in docker itself, when overlay network support will land in the engine.

@resouer We might add theses strategies in swarm (using #243), but it'll be far from perfect.
Let's say one host has 2g of RAM, you schedule a container with 1g, it's going to this host, then if you schedule a `linked` or `--volumes-from` container asking for 2g, it's a dead end, the `--volumes-from` says you need to schedule next to container1 but there is not enough resource available on this host.

As @Tebro we will rely on docker compose to be able to schedule a "group" of containers

**Comment by resouer** [comment]
@vieux Yes, can't agree more with you. If we want to make swarm really works, we need import concepts like Groups in Docker (as Pods n k8s). That really need Compose's help in this case. But I think Fig is not ready for that, group labels, group resource sharing ... are all lack from the project. Did you guys know about the direction of Swarm&Compose is going to?

**Comment by aanand** [comment]
@resouer The networking effort - still ongoing - will most probably result in a top-level "network" concept that's essentially a multi-host group of containers which can intercommunicate. As and when that makes it into Docker master, Compose will use it.

**Comment by analytically** [comment]
+1

**Comment by aanand** [comment]
Is co-scheduling based on links/volumes-from/net an easy fix to sneak in for 0.1.0? It'd be really cool from Compose's point of view.

**Comment by Tebro** [comment]
@aanand +1

**Comment by aluzzardi** [comment]
@aanand Technically we are in a code freeze so no.

In reality, I might try to sneak it in :)

But no guarantees.

**Comment by aanand** [comment]
![mgs_3_sub_12-sneakingmissioncopy](https://cloud.githubusercontent.com/assets/1062/6088815/88665e28-ae28-11e4-8224-c3ede5aa429e.jpg)
