### ISSUE TITLE
docker swarm init --advertise-addr (ip:port)   

### ISSUE THREAD

**Issue by upsunjian** [docker/swarm#2510]
cmd: "docker swarm init --advertise-addr (ip:port) "  to  create a manage node
It prompt error：must  sprcify a listening address to advertise is not recognized as a system address.
and when use cmd: docker swarm init --listen-addr (ip:port)  occurs error : " --live-restore daemon configuration is incompatible with swarm mode"

**Comment by michelvocks** [comment]
Hello @upsunjian 
It seems like you want to use docker swarm mode. This one differs from the docker swarm standalone platform. [See the differences here](https://github.com/docker/swarm#swarm-disambiguation).

All issues/bugs related to docker swarm mode should be opened in the [docker/docker repo](https://github.com/docker/docker).

**Comment by upsunjian** [comment]
@michelvocks ok, thanks!
