### ISSUE TITLE
Request: Add binaries to GitHub releases

### ISSUE THREAD

**Issue by vincentwoo** [docker/swarm#2518]
Currently, when swarm cuts a release, the source code gets uploaded as a tarball to github releases, and a new version is pushed out to https://github.com/docker/swarm-library-image in binary form.

If you want to download a specific version of the swarm binary, it's not too easy: you have to look for the appropriate commit in the library image repo. I propose that releases that get cut here also bundle binaries, too, since it seems like you are already making them as part of your release workflow.

**Comment by dongluochen** [comment]
@vincentwoo We do not provide download link because we want users to run swarm inside a container, `docker run ... swarm`? Do you prefer to run the binary?

**Comment by vincentwoo** [comment]
Yes, because I wish to reduce the attack surface of my application, it's actually very important to me to *not* be running the docker daemon on the node that is running the swarm manager.

**Comment by dongluochen** [comment]
That makes sense. Let me look into how to add a download link.

**Comment by vincentwoo** [comment]
In the UI for creating a github release, there's an area where you can drag and drop binaries in, if that helps: https://help.github.com/articles/creating-releases/

**Comment by dongluochen** [comment]
Thanks for the info. 

I just do some validation and put swarm-1.2.5 at the [release page](https://github.com/docker/swarm/releases/tag/v1.2.5)

**Comment by vincentwoo** [comment]
I appreciate it! Another convention you might want to use is to name the binary after the architecture (amd64 or whatever) in case you eventually ever do multiple builds.

**Comment by vincentwoo** [comment]
Oh, also, you might want to update the release checklist in the repo root.

**Comment by dongluochen** [comment]
PR added https://github.com/docker/swarm/pull/2525.

**Comment by vincentwoo** [comment]
@dongluochen hey fyi in the 1.2.6 release you added a "v" to the URL:

`https://github.com/docker/swarm/releases/download/v1.2.5/swarm-1.2.5-linux-x86_64.tgz`
`https://github.com/docker/swarm/releases/download/v1.2.6/swarm-v1.2.6-linux-x86_64.tgz`

**Comment by dongluochen** [comment]
@vincentwoo Thanks for reporting the problem. I have updated the binary name for `1.2.6` and RCs.
