### ISSUE TITLE
Creating a simple Debian image as service

### ISSUE THREAD

**Issue by wyxgit** [docker/swarm#2527]
Hi,

```
# docker service create   --name debian --replicas=3 debian:latest

# docker service ls

ID            NAME                    REPLICAS  IMAGE                                                                                     COMMAND
5xhmeocv5rf4  XXX-appconsul1s  3/3       XXX/app:build-305                                                    -Dconfig.file=conf/application.conf
67mq5gruelnx  debian           0/3       debian:latest                                                             
```

I wanna create a simple native debian image under swarm, but does not run. 0/3, as you can see.
Tries to start but not.
Another app is running fine, as you can see.

What is the reason? How can I create a simple Debian images what swarm can use and start?

**Comment by wyxgit** [comment]
I found the solution in the meantime, should declare an "entry point", like a bash script to run.

**Comment by allencloud** [comment]
Oh, that is great. @wyxgit 
Enjoy the swarm mode docker engine provides. Since you solved your way, I am thinking to close this one. While feel free to open it for more we could help.

Thanks.
