### ISSUE TITLE
docker: Error response from daemon: json: cannot unmarshal object into Go value of type [2]int.

### ISSUE THREAD

**Issue by jinuxstyle** [docker/swarm#2530]
Hi

I am using following command to create a container on a swarm cluster:

docker -H localhost:3375 create busybox top

but met following error:

docker: Error response from daemon: json: cannot unmarshal object into Go value of type [2]int.

My docker version is:

Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   fcd035e
 Built:        Tue Sep 20 09:58:04 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   fcd035e
 Built:        Tue Sep 20 09:58:04 2016
 OS/Arch:      linux/amd64

My swarm image is pulled from docker public hub with version 942fd5fd357e.

Any idea on what's going on?

**Comment by allencloud** [comment]
Hi , @jinuxstyle 

can you provide more details of your environment? Such as the steps how to reproduce you issue?

In addition, can you show us more log about swarm? I think maybe that would be helpful.

**Comment by jinuxstyle** [comment]
Hi @allencloud,

Thanks for looking into this issue.

It looks a versioning problem. I am using the docker and swarm built based on latest code on master branch, but they doesn't keep in line with the data structures like container's config. After revendoring the dependent engine-api package to latest, the problem disappeared.

By the way, when checking the version of engine-api in docker repo, I found it's deprecated. Maybe swarm needs update to keep compatibility with latest docker.

**Comment by git-jiby-me** [comment]
@allencloud , @jinuxstyle i also noticed this when trying to run swarm container on 1.13.0 (dev) of docker, the api seems to have deviated, that swarm doesnt support the new api.

@jinuxstyle can you describe how you fixed, and compiled swarm to work with 1.13.0. @allencloud when would swarm have support for docker v1.13.0-rc1 ?

**Comment by jinuxstyle** [comment]
@git-jiby-me I fixed the problem with following steps:

First, get the latest engine-api package
      
    $ go get -v github.com/docker/engine-api

Then, update the godep file and swarm repository

    $ godep update github.com/docker/engine-api/...

Next, build swarm,
      
    $ go build

Apply following patch if build complains info.ExecutionDriver undefined.

```
diff --git a/cluster/engine.go b/cluster/engine.go
index 1d3124b..5c69a84 100644
--- a/cluster/engine.go
+++ b/cluster/engine.go
@@ -538,9 +538,6 @@ func (e *Engine) updateSpecs() error {
        if info.Driver != "" {
                e.Labels["storagedriver"] = info.Driver
        }
-       if info.ExecutionDriver != "" {
-               e.Labels["executiondriver"] = info.ExecutionDriver
-       }
        if info.KernelVersion != "" {
                e.Labels["kernelversion"] = info.KernelVersion
        }
```
Then, continue build until succeed.

Hope it helps.

**Comment by dongluochen** [comment]
#2492 should fix this issue.
