### ISSUE TITLE
Dockerfile build fail

### ISSUE THREAD

**Issue by jinuxstyle** [docker/swarm#2531]
Docker build failed with following error log:

github.com/docker/swarm
# github.com/docker/swarm
/usr/local/go/pkg/tool/linux_amd64/link: -X flag requires argument of the form importpath.name=value
The command '/bin/sh -c set -ex         && apk add --no-cache --virtual .build-deps     git   && GOOS=$GOOS CGO_ENABLED=0 go install -v -a -tags netgo -installsuffix netgo -ldflags "-w -X github.com/docker/swarm/version.GITCOMMIT `git rev-parse --short HEAD` -X github.com/docker/swarm/version.BUILDTIME \"`date -u`\""       && apk del .build-deps' returned a non-zero code: 2

**Comment by allencloud** [comment]
Thanks @jinuxstyle 
I tried as well. Failed with the same error, too.
We will solve it soon.
ping @dongluochen, is it related to PR https://github.com/docker/swarm/pull/2521?
