### ISSUE TITLE
Swarm component could not be started. Docker daemon stops

### ISSUE THREAD

**Issue by megastef** [docker/swarm#2542]
Hi, 

the IP address of my Swarm master changed (Scaleway, stopped node and started a day later). Where can I change the listen-address configured during "swarm init"? 

Logs: 
```
> docker --version
Docker version 1.12.2, build bb80604
> docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
> docker daemon
INFO[0000] libcontainerd: new containerd process, pid: 4974 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=65536
INFO[0001] [graphdriver] using prior storage driver "aufs" 
INFO[0001] Graph migration to content-addressability took 0.00 seconds 
INFO[0001] Loading containers: start.                   
...INFO[0001] Firewalld running: false                     
INFO[0001] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 

INFO[0001] Loading containers: done.                    
ERRO[0001] cluster exited with error: listen tcp 10.6.3.79:2377: bind: cannot assign requested address 
FATA[0001] Error creating cluster component: swarm component could not be started: listen tcp 10.6.3.79:2377: bind: cannot assign requested address 
```

**Comment by michelvocks** [comment]
Hello @megastef 
Please be aware that this question is related to docker swarm mode integrated into the docker engine since  docker 1.12. Therefore, this question should be asked at [docker/docker repo](https://github.com/docker/docker).

To answer your question. You can use `docker swarm leave` to leave a swarm cluster and then re-initiate it with `docker swarm init`.

**Comment by allencloud** [comment]
Yes, like @michelvocks mentioned. This is an issue about Swarm Mode in docker docker.
@megastef we can discuss more at project docker/docker.
And I am closing this, please feel free to let us know if there is still something confusing.

**Comment by megastef** [comment]
Thx. ```docker swarm leave``` means I have to create a new cluster, because the swarm master got this problem.
