### ISSUE TITLE
Swarm adds prerouting iptables rule which hides existing rules

### ISSUE THREAD

**Issue by zk101** [docker/swarm#2545]
By default, swarm has a very open rule that looks like:
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER-INGRESS

This in effect takes all traffic from anywhere and sticks in in the DOCKER-INGRESS chain, where the rules to route traffic for running services are dyanically added.  If you attempt to limit the globalness of this rule to:
-A PREROUTING -s 192.168.0.0/16 -m addrtype --dst-type LOCAL -j DOCKER-INGRESS
-A PREROUTING -s 172.16.0.0/12 -m addrtype --dst-type LOCAL -j DOCKER-INGRESS
-A PREROUTING -s 10.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER-INGRESS

When a container is started on a host by swarm, it re-adds its default rule to position 1 in the chain.
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    DOCKER-INGRESS  all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
2    DOCKER-INGRESS  all  --  192.168.0.0/16       0.0.0.0/0            ADDRTYPE match dst-type LOCAL
3    DOCKER-INGRESS  all  --  172.16.0.0/12        0.0.0.0/0            ADDRTYPE match dst-type LOCAL
4    DOCKER-INGRESS  all  --  10.0.0.0/8           0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Which then allows traffic from all sources, hiding the limited rules.  Deleting that rule returns the host to its desired behaviour.

This is very easy to replicate, start with a swarm host that has two interfaces, start a service with a simple web container, and then attempt to curl the container over both interfaces, should work.  Replace the default rule with the source limited rules, and filtering works as expected, traffic on the non-filtered interface works, on the filtered interface it does not.  Stop the container running on the host, swarm will start a new instance on that host and re-adds the global rule to position 1.

The behaviour of this could be modified, so swarm tests with there is already a -j DOCKER-INGRESS rule in play within PREROUTING, and if so, respects that rule is accurate.

I attempted to re-create the docker swarm network overlay using the --internal option, this doesn't appear to have any effect.  However, if it did, it only partly corrects the issue as we want to be able to limit interactions with the swarm to private and select public subnets.  Maybe there is some other way to achieve?

**Comment by allencloud** [comment]
Hi @zk101  Thanks for your feedback.

I am afraid that your issue is related to Swarm Mode of docker engine, maybe it is more proper to post issue here https://github.com/docker/docker/issues/new . This project is about Swarm which is different from swarm mode in docker engine.

Here are more details about the difference https://github.com/docker/swarm#swarm-disambiguation

I am closing this. If you need more help, feel free to let us know. Thanks again for your contribution.
