### ISSUE TITLE
Swarm info logging is sent to stderr

### ISSUE THREAD

**Issue by jotunskij** [docker/swarm#2546]
**Issue**

Logging from Swarm node in etcd backed cluster with level=info is sent to stderr

**Versions**
```
Swarm 1.2.5
etcd 3.0.9
```

**Run command**
```
docker --host 10.28.20.133:2376 run --detach  --restart=always --name=swarm-join --label=availset=worker --label=type=swarm.node --env SERVICE_IGNORE=true --volume /etc/docker:/etc/docker swarm:1.2.5 join --advertise 10.28.20.133:2376 etcd://10.28.20.133:2379/swarm
```

**Log being sent to stderr**
```
time="2016-11-17T09:33:42Z" level=info msg="Registering on the discovery service every 1m0s..." addr="10.28.20.133:2376" discovery="etcd://10.28.20.133:2379/swarm"
```

**To verify**
```
docker logs swarm-node > stdout.log 2>stderr.log
```
Stderr.log contains all the messages of the type given above

This causes our logging tool to register this message as an error, which obviously is not something we want.

**Comment by dongluochen** [comment]
Not sure why it was set to `stderr` for log output. @aluzzardi ?

https://github.com/docker/swarm/blame/master/cli/cli.go#L48
```
		log.SetOutput(os.Stderr)
```
