### ISSUE TITLE
Port filtering in the Host mode

### ISSUE THREAD

**Issue by chanwit** [docker/swarm#255]
Correct me if I am wrong.

Does the current port filter work only with port mapping in the -net=bridge mode?
If so, is there any information we could obtain from a Docker instance to filter it with the host's port?

**Comment by vieux** [comment]
Not at the moment, like memory and CPU, we rely on docker to know what's used and what's not.

Maybe we could use `exposed` ports when `-net=host`.

@chanwit that's assuming you are using `-net=host` ?

**Comment by chanwit** [comment]
yes we're using -net=host to avoid NAT to maximize our cluster's performance  :)

**Comment by chanwit** [comment]
@vieux to make this happen, does it require any change to `docker`?

**Comment by vieux** [comment]
@chanwit I don't think so, if you can use `--expose` with `--net=host` we will just need to use it.

**Comment by chanwit** [comment]
I see. Thank you @vieux
