### ISSUE TITLE
Update CI for integration tests

### ISSUE THREAD

**Issue by nishanttotla** [docker/swarm#2558]
The CI is running behind Docker versions, and must have 1.12 and 1.13 on the integration tests. It is possibly time to also remove some older versions.

**Comment by dongluochen** [comment]
Ping @vieux.

**Comment by nishanttotla** [comment]
This works for 1.12 now, all PR updates should now have a field for 1.12. Thanks to @mikedougherty.

**Comment by nishanttotla** [comment]
CI updated for 1.13 also. Closing this issue now.

cc @dongluochen @allencloud
