### ISSUE TITLE
Redistribute/rebalance containers on nodes

### ISSUE THREAD

**Issue by FarhadF** [docker/swarm#2559]
Hi guys,

I was wondering if there is a feature for redistributing better to say rebalancing containers on swarm nodes.
The scenario is: my containers are all on a single node after other nodes failed, now they are back online and I need to redistribute/rebalance them across the nodes. I can drain the node but it will cause an empty node.

Regards,
Farhad

**Comment by michelvocks** [comment]
Hello @FarhadF. I think this question is related to the new docker swarm mode introduced within docker 1.12? If so, please open a new issue in the corresponding tracker [docker/docker](https://github.com/docker/docker). 

You can also find here more information about the old docker swarm standalone platform and the new docker swarm mode: https://github.com/docker/swarm#swarm-disambiguation

**Comment by FarhadF** [comment]
Yes, Thanks for the info.

**Comment by nishanttotla** [comment]
Closing this issue, thanks for the clarification @michelvocks
