### ISSUE TITLE
On-Failure move of an image breaks network alias

### ISSUE THREAD

**Issue by nishanttotla** [docker/swarm#2562]
Reported on Swarm version 1.2.5, Engine version 1.12.1

Making a network alias with a bridge (and possibly overlay) network isn't preserved when the container gets rescheduled to a different node.

cc @dongluochen @wsong

**Comment by clemenko** [comment]
Do we have an update on this?

**Comment by nishanttotla** [comment]
I was able to reproduce this issue for Docker version 1.12.3 and latest Swarm release (1.2.5)

cc @dongluochen @wsong @mavenugo

**Comment by mavenugo** [comment]
@nishanttotla thanks. I guess this is specific to swarm and not swarm-mode. correct ?

**Comment by nishanttotla** [comment]
@mavenugo that's correct. I reproduced this issue without enabling swarm
mode.

**Comment by nishanttotla** [comment]
@mavenugo @clemenko I've submitted a PR: https://github.com/docker/swarm/pull/2565
