### ISSUE TITLE
Container logs file remains open

### ISSUE THREAD

**Issue by evoevodin** [docker/swarm#2567]
Hi there :hand:

When i make the following request:

```bash
curl "http://0.0.0.0:23750/containers/<container-id>/logs?stdout=1&stderr=1&follow=1" --max-time 5
```
0.0.0.0:23750 <- swarm

container logs file on node is opened 1 more time, but when timeout is reached
and connection becomes closed - the file remains open.
I tried different request configurations and got the following results:

- :no_entry_sign: - file remains open
- :ok_hand: - file is closed after some period of time

| curl params                        | follow=    | swarm           | direct daemon request |
| ------------------:                |-----------:| ---------------:|----------------------:|
| --max-time=5                       | true       | :no_entry_sign: |   :ok_hand:           |
| --max-time=5                       | false      | :ok_hand:       |   :ok_hand:           |
|                                    | false      | :ok_hand:       |   :ok_hand:           |
| --no-keepalive --max-time=5        | true       | :no_entry_sign: |   :ok_hand:           |

I used the following command to check open files:

```bash
lsof -p $(cat /run/docker.pid) | awk '{print $9 $10}' | sort | uniq -c | sort -n | grep ".*containers.*log"
```

it produces something like this:
```
1   /var/lib/docker/containers/94e48934b97db014dd9e0b89cca84e4bb332c5101e239644ba5aa19f276ea13e/94e48934b97db014dd9e0b89cca84e4bb332c5101e239644ba5aa19f276ea13e-json.log
885 /var/lib/docker/containers/eacc357e0724eb1f64781e9fb5ce202e282db4e875b10a4479d3c3bf103f8934/eacc357e0724eb1f64781e9fb5ce202e282db4e875b10a4479d3c3bf103f8934-json.log
```
where the first column is a number of openings for a certain file.

##### Versions:

```
# docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
```

```
#swarm --version
swarm version 1.2.3 (eaa53c7)
```

```
#cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core) 
```

**Comment by dongluochen** [comment]
@evoevodin Thanks for reporting the problem. We will look into it.

**Comment by dongluochen** [comment]
@evoevodin In my test, when curl finishes, the extra file handle on the target node log file remains open for 15 seconds. After 15 seconds the handle closes. Can you confirm if this is the case? 

```
curl "http://0.0.0.0:23750/containers/<container-id>/logs?stdout=1&stderr=1&follow=1" --max-time 5
```

**Comment by dongluochen** [comment]
Swarm manager acts as a proxy for these requests. The problem is it doesn't react to incoming connection disconnect signal. I have a patch to fix this. But this `proxy` method is shared by many requests. So it'd require better testing. 

On the other hand, I'll need confirmation from @evoevodin on the impact data, see above.

**Comment by evoevodin** [comment]
Hi @dongluochen,

> @evoevodin In my test, when curl finishes, the extra file handle on the target node log file remains open for 15 seconds. After 15 seconds the handle closes. Can you confirm if this is the case?

I checked it again, when i use swarm - logs file remains open even after ~2h.
When i use node docker daemon directly file is closed immediately or after small amount of time.

**Comment by dongluochen** [comment]
Thanks @evoevodin. I tested https://github.com/docker/swarm/pull/2578 and it should solve this problem. I'm trying to figure out if there are side effects from this change. It'd be great if you get a chance to test #2578.

**Comment by evoevodin** [comment]
I'v tested #2578, logs file is closed immediately after timeout.
Thank you @dongluochen.

**Comment by dongluochen** [comment]
Thanks @evoevodin!
