### ISSUE TITLE
Container rescheduling does not work when a container uses an image from a private repository because of authentication

### ISSUE THREAD

**Issue by dang3r** [docker/swarm#2569]
# Issue

When a node failure occurs and containers have to be rescheduled, the rescheduling fails if the image the container uses is NOT on its new node AND requires a private registry. The image is not being successfully pulled because of authentication issues. In some cases, the private image may be on the new node the container is scheduled to run on, but this shouldn't be relied upon.

` if (isPrivate(container.Image) && !imageOnNode(container.Image, new_node) -> rescheduling fails`

# Versions

Using a Swarm binary wrapped in a container from the commit `fecbcff2385984157c6bcf71c7fbdf6c948b9c7e` (latest commit at the time of this posting)

Docker
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64
```

# Logs

- container logs when rescheduling fails

`Dec 14 23:04:40 ip-X-X-X-X [swarm][swarm_manager][d1cd08b016ad][708]: time="2016-12-14T23:04:40Z" level=error msg="Failed to reschedule container 89b73e09f1ebfc46ac3fe28ac0b77111011b07696abf2f66f193ca4a0645b063: unauthorized: authentication required"`

# Notes
When using a private registry for images, you must ensure the correct authentication header is passed when making requests to the Swarm [Swarm Authentication](http://docs.master.dockerproject.org/swarm/swarm-api/#/registry-authentication). 

This header is correctly used when making requests against the exposed Swarm API on a Manager. An example can be seen when creating a container [here](https://github.com/docker/swarm/blob/5a254ec1a1bc424676596101de32e775d64d4ffa/api/handlers.go#L583). It correctly extracts and forwards the header so the Node/Swarm_Agent that will run the container, can actually pull the image.

However, when a container is deemed fit to reschedule because of a node failure, this authentication token for private registries is not stored or retrieved. The top-level call where you can see this is at [Link](https://github.com/docker/swarm/blob/214a4dc36f6fab0c11d73e1c8f167b5a46cc4a89/cluster/watchdog.go#L124) This **nil**  auth config pervades all the way down until the engine the scheduler deems fit for the container, tries to create it. Seen [here](https://github.com/docker/swarm/blob/master/cluster/engine.go#L973). 

The authConfig being passed around is nil, and is never populated in the rescheduling case. However, there is support to use one, but its not being leveraged. This is largely because the only existing method to retrieve said authentication token has been from incoming requests, and not from a local file. The Docker-CLI seeks credentials from `$HOME/.docker/config.json` as seen [here](https://github.com/docker/docker/blob/c34efaeca0806e6fd92cc951b85420f0f300b74e/man/docker-login.1.md)

# Workarounds

* For an image you want to run on the Swarm, ensure it exists on all Swarm-Agent nodes
  * This would require extra work to ensure all private images that can be run on node, will be. For Swarms that run different versions of images, or whose required images change rapidly, this requires custom work (but not impossible)
  * For simple cases, you can perform this before deployment and it works. However, in case you want to automate this, it still requires rolling your own solution.

# Potential Solutions

- Read authentication credentials when needed. Essentially, emulate how the Docker CLI does it (with the one of the solutions reading from `~/.docker/config.json`). When using the Swarm Docker image, just mount said folder structure into the container so it has access. 
  - There is only one spot I believe this is necessary mentioned before: [here](https://github.com/docker/swarm/blob/214a4dc36f6fab0c11d73e1c8f167b5a46cc4a89/cluster/watchdog.go#L124)
  - Rereading the file each time may not be the most performant, but the authentication tokens for specific private registries expire (AWS-ECR tokens have 12 hour expiration). Reading each time prevents having update logic to reread the token at a specific frequency
- Same solution as above but caching the authentication credentials that live somewhere (maybe at the cluster or engine level) and periodically updating them atomically
- Enable the Swarm-Agents that receive commands from the Managers to look for local authentication credentials.
  - When receiving requests from the Swarm API, if no token is present in the header, check locally. If no token locally, same behaviour as before.
  - Modify certain handlers like [ContainersCreate](https://github.com/docker/swarm/blob/5a254ec1a1bc424676596101de32e775d64d4ffa/api/handlers.go#L583) to perform this local lookup step
  - This goes against the architecture of the Swarm, but might be the simplest option

**Comment by dang3r** [comment]
My quick solution can be seen at the fork here : https://github.com/dang3r/swarm

**Comment by nishanttotla** [comment]
@dang3r thanks for the report. This seems reasonable and should be considered a bug that must be fixed soon. We might need to think a little more to agree upon the right way to retrieve the auth config, but in the meantime please feel free to submit a PR.

**Comment by ambrons** [comment]
I would also like to through out there during the consideration of this fix AWS and the recent release of Docker for AWS.  If the private repo is ECR the credentials are only good for 12 hours.  So Docker Swarm would need to implicitly authenticate via the aws docker-login command or some other means.

**Comment by destebanm** [comment]
So, do you guys plan to fix that in future versions? Are you going to apply one of solutions proposed by @dang3r ?
Thanks!

**Comment by friism** [comment]
I think this might be a dupe. See:

 * https://github.com/docker/swarm/issues/1484
 * https://github.com/docker/for-aws/issues/5#issuecomment-315865628
