### ISSUE TITLE
How to configure Swarm Mode on Mesos

### ISSUE THREAD

**Issue by vimalprakashts** [docker/swarm#2570]
hi,

Is there are any to run Swarm mode on mesos ? 

My google search always shows the old way of doing , (running swarm image with mesos experimental ) 

I just like to know is there any way to run swarm mode on mesos ?

**Comment by dongluochen** [comment]
@vimalprakashts Swarm mode issue should be discussed at https://github.com/docker/swarmkit/. And you may want to present your use-case.
