### ISSUE TITLE
Containers not re-scheduled to available nodes from dead nodes

### ISSUE THREAD

**Issue by sourav82** [docker/swarm#259]
I noticed if one swarm node goes down, then the container scheduled on it marked as pending but not re-scheduled to other available swarm nodes. From the manager node, I'm getting below logs -

ERRO[3121] [3FLV:RF2L:CXDR:PF3Y:QC7S:Y7SY:JLZF:TJH5:HEXA:FH52:YUCP:ASSB/etp-ProLiant-DL180-G6-3] Flagging node as dead. Updated state failed: Get http://10.227.125.3:2375/v1.15/containers/json?all=1&size=0: dial tcp 10.227.125.3:2375: connection refused

What is expected here? Should it wait forever for the down node to come up or it will try to reschedule the containers to other available nodes?

**Comment by phemmer** [comment]
Currently it will not try and start it on another node. While it might be nice to try and do so, this would be rather dangerous territory.
Lets say it does does restart the container on another node, then that missing node comes back up and the container is still running on it, what happens? Should swarm stop one of them? If so, which one? Then what if the container is running an application where corruption can occur if it's running multiple times in parallel?

I'm not saying swarm shouldn't do this, as I think service availability is critical, and other clustering engines are capable of handling this scenario, but it's not a simple task.

**Comment by aluzzardi** [comment]
@sourav82: This is planned but not currently implemented. As @phemmer said, it's dangerous and complex. What we are going to do is give you an option when scheduling containers in order to set the rebalancing policy, in the same way Docker has a restart policy so you will be able to decide by yourself which containers are safe to reschedule.

**Comment by sourav82** [comment]
Thanks @phemmer and @aluzzardi for the information.
