### ISSUE TITLE
Feature request: Being able to retrieve swarm node name / host's hostname

### ISSUE THREAD

**Issue by mostolog** [docker/swarm#2628]
As requested in https://forums.docker.com/t/how-to-specify-our-own-unique-node-id-or-node-name-to-docker-swarm-nodes/28109 it could be interesting to be able to make node names more friendly, having a **PlaceHolder {{.Node.Name}}** with the host's hostname in https://docs.docker.com/engine/reference/commandline/service_create/#/create-services-using-templates

Regards

**Comment by allencloud** [comment]
Hi @mostolog , thanks for your feedback.

I am afraid that your issue is related to Swarm Mode of docker engine, maybe it is more proper to post issue here https://github.com/docker/docker/issues/new . This project is about Swarm which is different from swarm mode in docker engine.

Here are more details about the difference https://github.com/docker/swarm#swarm-disambiguation

I am closing this. If you need more help, feel free to let us know. Thanks again for your contribution.

**Comment by mostolog** [comment]
You really SHOULD remove all legacy swarm references...Thanks!

**Comment by nishanttotla** [comment]
@mostolog can you point out which legacy Swarm reference confused you? We're trying to keep documentation clean, but perhaps something was missed. Thanks!

**Comment by mostolog** [comment]
Starting from https://www.docker.com/products/docker-swarm ? :stuck_out_tongue_closed_eyes:

**Comment by nishanttotla** [comment]
That page is technically talking about Docker Swarm, which is `github.com/docker/swarm`, but I can see that one might get confused.

cc @mstanleyjones do you think we should make changes there?

**Comment by mostolog** [comment]
Although I understand legacy swarm could still be used, I would suggest removing all the information form docs, not indexing it on search engines or adding a bigger LEGACY disclaimer everywhere.

For sure I'm not the first neither the last to ask on the wrong place ;)

**Comment by mstanleyjones** [comment]
I believe there are still some recommended use cases for legacy swarm mode. @aaronlehmann @stevooe might have some more info about why we have not deprecated the legacy swarm mode docs.

**Comment by artisticcheese** [comment]
Where do I need to create a feature request to add .Node.Name to list of environment variables passed to individual containers in swarm mode? Documentation for existing ones are available here (https://docs.docker.com/engine/swarm/services/#create-services-using-templates), it's missing `Name`.

**Comment by nishanttotla** [comment]
@artisticcheese please do that at https://github.com/moby/moby/issues

**Comment by mostolog** [comment]
@artisticcheese already: https://github.com/moby/moby/issues/30966
