### ISSUE TITLE
Vendoring dependencies

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#264]
Right now we just assume developers will `go get` dependencies.

However this doesn't work well as my build of `swarm` might be different from, say, @vieux's build.

We need to find a way to properly vendor dependencies in a lightweight way.

**Comment by vieux** [comment]
I always wanted to give http://labix.org/gopkg.in a try in docker but it's way to big, we could try it in swarm.

**Comment by phemmer** [comment]
Git submodules would seem better than gopkg.in to me. gopkg.in is restricted to github, and requires the deps to use the specified versioning scheme. But neither would handle deps from mercurial (though it is rare to need it).

**Comment by rgbkrk** [comment]
Any opposition to Godeps and not checking in the `_workspace`?

/me ducks

**Comment by aluzzardi** [comment]
@vieux I think you have some experience with Godeps?

**Comment by vieux** [comment]
not at all, I have experience with [vendor.sh](https://github.com/docker/docker/blob/master/project/vendor.sh) :)

@rgbkrk can you explain what you mean by `checking in the _workspace` ?

**Comment by aluzzardi** [comment]
@vieux http://stackoverflow.com/questions/26334220/should-i-commit-godeps-workspace-or-is-godeps-json-enough

**Comment by daniel-garcia** [comment]
It's worth noting that godeps deprecated only saving the Godeps.json file.

http://goo.gl/RpYs8e

godep now saves all dependencies in the Godeps/_workspace directory by
default.

**Comment by vieux** [comment]
I think we should give it a try with git submodules.

@aluzzardi can you give it a try ?

**Comment by stevvooe** [comment]
@vieux @aluzzardi docker/distribution has adopted godep and its working pretty well. Note that I've filed tools/godep#172 to request that `godep` be updated to directly manage the ./vendor directory. That proposal would combine the best of vendor.sh and `godep save -r` (import rewriting). Please comment on that issue so it can get some visibility.

**Comment by rgbkrk** [comment]
> @rgbkrk can you explain what you mean by checking in the _workspace ?

Egads. I think I used old VCS language there. I'm talking about not including the `_workspace` in git (explicitly part of the gitignore)

The nice benefit of dodeps is that users can get going without it. If someone wants the exact version being used on development, they can rely on godep and it will pull in the `_workspace`.

**Comment by rgbkrk** [comment]
The reason why I *don't* want to see `_workspace` under version control is that it makes working through a PR **miserable**.

**Comment by vieux** [comment]
if you don't version `_workspace` you can't go get / go build the project, right ?

**Comment by rgbkrk** [comment]
Admittedly, I'm realizing that restoring locally in a development environment requires:

```console
~/go/src/github.com/docker/swarm $ GOPATH=`godep path` godep restore
```

What we've been doing in a Dockerfile that adheres to what is in the Godeps.json is:

```Dockerfile
FROM golang:1.4
RUN go get github.com/tools/godep

# Add the Godeps directory (note that it doesn't have _workspace locally)
ADD ./Godeps /go/src/github.com/cloudpipe/cloudpipe/Godeps
WORKDIR /go/src/github.com/cloudpipe/cloudpipe/

# godep restore sets up the GOPATH (/go here) to get the exact version of libraries from Godeps
RUN godep restore

ADD . /go/src/github.com/cloudpipe/cloudpipe/
RUN go install github.com/cloudpipe/cloudpipe

CMD ["/go/bin/cloudpipe"]
```

This does make me feel a little bit terrible in bike shedding and suggesting bucking the current practice from Godeps. Hopefully I'll still be welcome after this. :tongue: 

/cc @smashwilson

**Comment by aluzzardi** [comment]
1/ Do not rewrite import statements.

This means that you can continue doing things the same way, in development go will pick up your local dependencies and you don't even need to be aware of godep.

To make sure dependencies are updated when needed, we would change `travis.yml` to run the tests using godep so that PRs introducing breaking changes will be stopped.

The only difference will be during releases as we would mint binaries using `godep go build`.

Now comes the question of including `_workspace` or not: Since it will only be used for travis and releases we can probably get away without it.

2/ Rewrite import statements (`godep save -r`)

All the code will explicitly import packages from godep's workspace.
The nice thing about this is that it guarantees that we all run the same code (including travis) and you don't need to `go get -u` after `git pull`.

If we do this, we have to include the workspace since otherwise it will get the getting started process more complicated for new comers (`git clone` then `godep restore`).

Thoughts?

/cc @rgbkrk @dmp42

**Comment by stevvooe** [comment]
@aluzzardi Before, I was in the 1 camp before. After consideration, 2 is a much better option as it doesn't require casual users to pickup godep and makes the project trivially `go get`-able. Builds are faster and with rewrites, incantations of the godep tool are not required to manage builds.

@rgbkrk These benefits outweigh a little extra fat in code review that update dependencies. A little review of code dependencies can't hurt, as we need to somewhat careful about what is pulled in.

This is the conclusion we made for the other project and is just my 2 cents. I hope this helps.

**Comment by aluzzardi** [comment]
@stevvooe I'm still in between 1 and 2. 1 doesn't require users to know about godep at all - it's the regular Go workflow (`go get -u`, etc), so it seems much more lightweight, especially if we don't commit `_workspace`.

I could lean either way.

@vieux: Thoughts?

**Comment by vieux** [comment]
I like 1 + commiting `_workspace`,  because I don't want to use godep :P

**Comment by rgbkrk** [comment]
I would find 2 beyond awkward. 

> I like 1 + commiting _workspace, because I don't want to use godep :P

The `_workspace` bit is tangential to choice of 1 or 2. You're using `godep` if you're using the `_workspace`. This is still your repo and I'm just a user at this point.

**Comment by tianon** [comment]
FWIW, I hate Godeps personally, but if you go that route, I'm 100% +1 on checking in `_workspace` since I don't want to use `godeps` at all, like @vieux (but also don't want to `go get`, so Godeps is a nice compromise IMO if you guys aren't turned off by the way it manages the deps for you). :smile:

**Comment by bfirsh** [comment]
Godeps has worked really well for us on Machine. Also our really lightweight Docker-based build and release scripts:

https://github.com/docker/machine/blob/master/script/build
https://github.com/docker/machine/blob/master/script/release

**Comment by aluzzardi** [comment]
@tianon @bfirsh How about the rewriting the import statements?

Basically,
1/ If you let godep rewrite the import statements, all the imports will look like `github.com/docker/swarm/Godep/_workspace/github.com/...`.

This mean that your import statements look disgusting, BUT you, the users and other automated tools don't need to change `GOPATH` at all (and you don't need to do `godep go <command>`).

2/ If you don't, then you can use the project as usual.

If you don't change your `GOPATH`, use `godep go` or run `godep restore`, it will use your local dependencies instead. This means that if you are not careful, you will end up not using the vendored dependencies. This is fine as long as the releases are always built with godep and the CI runs with the godep environment.

Thoughts?

**Comment by tianon** [comment]
I'm +1 on not rewriting imports, especially since it makes testing new versions as easy as updating your personal `GOPATH` and not worrying about Godeps until/unless necessary (but of course this makes Travis testing using the Godeps even more important because less developers are likely to be doing so).
