### ISSUE TITLE
swarm and swarmkit

### ISSUE THREAD

**Issue by timchenxiaoyu** [docker/swarm#2644]
difference of swarm and swarmkit, why swarm hasn't 'create service' api?

**Comment by timchenxiaoyu** [comment]
if we have swarmkit  why we need swarm?

**Comment by fanux** [comment]
swarmkit not support host network mod

**Comment by dongluochen** [comment]
Swarm is imperative reusing Docker API. Swarmkit is declarative with new APIs. IMHO declarative system is what users want. It may take some time for Swarmkit to cover Swarm functionalities. For example, host network is under development (https://github.com/docker/docker/pull/27266). We also want to support existing Swarm users.

**Comment by nishanttotla** [comment]
Closing this issue since question seems answered. Feel free to reopen if this is not the case.

**Comment by renewooller** [comment]
Hi @dongluochen, I read the swarmkit features and examples at https://github.com/docker/swarmkit, but it does not seem to be declarative. . Can you please provide a link to provide evidence it is declarative?

I can see that it contains a (private) desired state that it compares against the actual state. This sounds declarative except for the fact that this state is only editable via imperative commands. IE there doesn't seem to be any way to maintain the 'desired state' in a version controlled repository. 

Thanks!

**Comment by nishanttotla** [comment]
@renewooller can you give more info about what you mean by 'desired state' maintained in a version controlled repository?

**Comment by renewooller** [comment]
@nishanttotla - sure thing. 

Currently it is possible to make ad hoc changes to components of the cluster state. EG 'swarmctl update redis ... '. This is imperative, as you are providing the instruction. 

It is not possible to say 'this config pertains to my entire cluster state, go and figure out a way to make it happen'. This is declarative - you provide the goal, rather than the instruction. 

Terraform, for example, is declarative - you declare a config, and it will plan out all the steps that are required to make that config into a reality and then execute them.

**Comment by dongluochen** [comment]
@renewooller It's declarative. `swarmctl update redis ...` updates service `redis`'s configuration. For example, service redis has 100 replicas with image redis:3.0. Now you use `update` command to change image to redis:3.2, it updates the service's configuration. Swarmkit will gradually update each replica from 3.0 to 3.2. There may be container failure, machine failure during this update. The system will handle them. When update completes, the service has 100 instances of container running redis:3.2.

**Comment by renewooller** [comment]
It's a fair point, and I understand. Just that it might be worth noting a caveat that is only declarative at the level of a single service, not the entire cluster. I also haven't seen anything that can factor in the dependencies between services and plan changes accordingly. People from the Infrastructure As Code (IAC) world may appreciate being made aware of these limits.

**Comment by dongluochen** [comment]
@renewooller Thanks for the feedback. Docker compose is evolving into describing multi-service bundle https://docs.docker.com/compose/bundles/. It handles service/network/storage dependencies. The philosophy of Docker toolset is to make small tools interoperable with each other. You can pick the right tools to build your system.
