### ISSUE TITLE
Docker Swarm Cannot Binding Port 80 

### ISSUE THREAD

**Issue by auzty** [docker/swarm#2658]
this is my situation : 
i have 3 server that has docker installed
i'm using docker server / client using this version
```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:57:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:57:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

for standalone swarm, i  set it like this : 

### Server1 : as a swarm master & consul only
**/etc/default/docker**
```
DOCKER_OPTS="-H tcp://172.16.1.1:8000 -H unix:///var/run/docker.sock --storage-driver=aufs"
```
and running consul with : 
```bash
docker run -d --name=consul -p 172.16.1.1:8300:8300 -p 172.16.1.1:8400:8400 -p 172.16.1.1:8500:8500 -p 172.16.1.1:8301:8301 -p 172.16.1.1:8302:8302 progrium/consul -server -node swarm-master -bootstrap-expect 1 -advertise 172.16.1.1
```

running swarm with:
```bash
docker run -d --name=swarm -p 172.16.1.1:2375:2375 swarm:1.1.0 manage --replication --advertise 172.16.1.1:2375 --discovery-opt kv.path=docker/nodes consul://172.16.1.1:8500
```

### Server2 : as node 

**/etc/default/docker**
```
DOCKER_OPTS=" --label nama=main -H unix:///var/run/docker.sock -H 0.0.0.0:2375 --cluster-store=consul://172.16.1.1:8500 --cluster-advertise=172.16.1.200:2375"
```

### Server3 : as node 

**/etc/default/docker**
```
DOCKER_OPTS="--label nama=anak -H unix:///var/run/docker.sock -H 0.0.0.0:2375 --cluster-store=consul://172.16.1.1:8500 --cluster-advertise=172.16.1.201:2375
```

-----

**docker info** from **Server 1**

```
Containers: 26
 Running: 0
 Paused: 0
 Stopped: 26
Images: 55
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 master: 172.16.1.200:2375
  └ Status: Healthy
  └ Containers: 18
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 440 MiB / 1.019 GiB
  └ Labels: executiondriver=<not supported>, kernelversion=3.13.0-98-generic, nama=main, operatingsystem=Ubuntu 14.04.5 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2017-03-22T11:09:06Z
 minion1: 172.16.1.201:2375
  └ Status: Healthy
  └ Containers: 8
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.019 GiB
  └ Labels: executiondriver=<not supported>, kernelversion=3.13.0-98-generic, nama=anak, operatingsystem=Ubuntu 14.04.5 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2017-03-22T11:09:00Z
Plugins: 
 Volume: 
 Network: 
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Kernel Version: 3.13.0-100-generic
Operating System: linux
Architecture: amd64
CPUs: 2
Total Memory: 2.038 GiB
Name: 861240efb93f
Docker Root Dir: 
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support
Experimental: false
Live Restore Enabled: false
```

now the problem is : i can't binding port 80 on my **server 2 (172.16.1.200)** form my swarm master
this is the error that i get when i run the container
```bash
#Swarm master (172.16.1.1)
docker run -d -p 80:8000 -e "constraint:nama==main" jwilder/whoami
```
```
docker: Error response from daemon: unable to find a node that satisfies nama==main.
See 'docker run --help'.
```

if the port i set to 801 for example, the container can run, idk why the port 80 are used.
and if i change the "constraint:nama==anak" , it can be run without problem (the container will run to **Server 3 (172.16.1.201)**

i already check using **netstat** command that i didn't find any process that using port 80.

why i post this issues, because if i run it manually from **Server 2(172.16.1.200)** using

```bash
#Server 2 (172.16.1.200)
docker run -d -p 80:8000 -e "constraint:nama==main" jwilder/whoami
```
it's works, so i didn't know why it's cannot be run from **swarm master**

(i already rebooted all of them, restarting all of them, and recreate container for swarm and consul but it didn't help)

thanks,

**Comment by dongluochen** [comment]
@auzty Is there any container already use port 80 on Server2? Note that Swarm considers a port be used by a container even the container is in `stopped` state. You may remove all the stopped containers from Server2 with `docker rm $(docker ps -aq)`. Then retry the swarm command with constraint.

**Comment by auzty** [comment]
wow , thanks  @dongluochen , i wil close this issues, after i remove my stopped container on **Server 2** it's works, i assume if i didn't see it on **netstat** so the port are free,
