### ISSUE TITLE
Help test 0.1.0

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#267]
Dear community,

We've put together a release candidate for 0.1.0.

Even though this will be a beta release (given that it's the very first one) and not meant for production use, we'd like your help to test it out and report your feedback, whether it's bugs or even small cosmetic issues.

Thank you!

**Comment by rgbkrk** [comment]
@jhamrick is totally using it in production with JupyterHub (with IPython notebooks) already for her class for compmodels at Berkeley, hopefully we'll have something meaningful to report back soon. :smile:

I'll try it out with tmpnb.org soon too!

**Comment by jhamrick** [comment]
I'm actually running a very slightly modified version until #227 is merged, but yes, what @rgbkrk said :smile:

**Comment by aluzzardi** [comment]
Awesome! Thanks.

Ping @abronan @chanwit @ibuildthecloud @JeffChien @lukemarsden @metcalfc @mota @phemmer @thaJeztah @tnachen

**Comment by thaJeztah** [comment]
Thanks for the ping, not a lot of time tomorrow, but will give it a spin this weekend

**Comment by aluzzardi** [comment]
Sure! We are actually giving ourselves about 2 weeks to test it out, so there's plenty of time left.

Thank you

**Comment by thaJeztah** [comment]
<--- topping up my DigitalOcean credits to run a huge cluster :sweat_smile:

**Comment by mota** [comment]
Count on me!

**Comment by abronan** [comment]
:whale: :whale: :+1: :whale: :whale:

@thaJeztah I guess I'll do the same. If there is a global outage, we'll know why :smile:

**Comment by thaJeztah** [comment]
@abronan just steer away from AMS3 and you should be fine :smile:

**Comment by technolo-g** [comment]
I'll be giving it a go for sure :bomb:

**Comment by david-guenault** [comment]
curently testing swarm, the only drawback i see at the moment is giving a logical name to swarm joined members (instead of hostname). That say it work quite well on a 3 hosts cluster (sorry i have no more computers available). Thinking off boostraping a docker cluster with an etcd discovery backend (physical hosts). Got a handfull Makefile (yeah i know old school way) to do it. Btw i started testing the whole docker stack 2 weeks ago so not sure to do it well.

**Comment by vieux** [comment]
Thanks everybody for testing the beta!
It was released on 26/02/2015, see http://blog.docker.com/2015/02/scaling-docker-with-swarm/

**Comment by bacongobbler** [comment]
:tada:
