### ISSUE TITLE
Docker run swarm create does not work

### ISSUE THREAD

**Issue by SergioMendes93** [docker/swarm#2675]
Hello, is there any problem with docker swarm or hub because suddenly when I run the command 
"docker run swarm create" it does not work. 
It downloads the image successfully but then gets stuck on  "Status: Downloaded newer image for swarm:latest" and after a while this is displayed:

<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
and other times I get 
<html><body><h1>502  Bad Gateway</h1>
The server didn't respond in time.
</body></html>

Any ideia what could cause this? other docker run swarm commands run fine just create does not work.

Thanks!

**Comment by zaxfenfeiyu** [comment]
metoo,what happened

**Comment by allencloud** [comment]
ping @dongluochen @nishanttotla 
any ideas?

**Comment by nishanttotla** [comment]
I think this is because the token service on hub is deprecated/failing. We've removed tests for it: https://github.com/docker/swarm/pull/2679 and will deprecate the option of using tokens altogether soon.

**Comment by dongluochen** [comment]
Token discovery service on Docker hub is under migration from one cloud provider to another. Unfortunately the migration didn't go well and brought down the service. We are working to restore it in the new cloud provider. 

In long run we are considering to deprecate this discovery feature. Normally there are 2 Docker release cycles from announcement to deprecation. We will follow such practice.

**Comment by s3ni0r** [comment]
@dongluochen Ok, for those who are new and lost (like me) regarding how to handle service discovery, please read this stackoverflow post it will answer many of your question.[http://stackoverflow.com/questions/40786414/need-for-service-discovery-for-docker-engine-swarm-mode](url)

**Comment by dongluochen** [comment]
Token service has migrated to its new cloud infrastructure. You can run `swarm create` to reinitialize your hub based service discovery.

**Comment by nishanttotla** [comment]
Closing since token service was fixed.
