### ISSUE TITLE
TestRegister fail 

### ISSUE THREAD

**Issue by fugr** [docker/swarm#2676]
➜  swarm git:(master)# cd discovery/token
➜  token git:(master)# go test -v -run TestRegister
=== RUN   TestRegister
--- FAIL: TestRegister (8.54s)
	token_test.go:44: Timed out
FAIL
exit status 1
FAIL	github.com/docker/swarm/discovery/token	8.549s

what's happen in https://discovery.hub.docker.com/v1?

503 Service Unavailable

No server is available to handle this request.

**Comment by dongluochen** [comment]
The hub discovery is down. This is not a recommended setup now so the priority may be low to fix it. 

@fugr Are you using the hub discovery. 

cc @vieux.

**Comment by fugr** [comment]
expect TestRegister failed,no effect my program.

**Comment by dongluochen** [comment]
I disabled this tests on token to fix CI. We will discuss this with token service owner to decide next steps.

**Comment by dongluochen** [comment]
Token discovery service hosted on docker hub is down due to service migration. We are working to restore it. It may take a few days.
