### ISSUE TITLE
Deprecate Docker Hub token based discovery

### ISSUE THREAD

**Issue by nishanttotla** [docker/swarm#2688]
It isn't recommended, nor a reliable way to do service discovery. We should start to deprecate it with the goal of completely removing it two releases from now.

cc @docker/core-swarm-maintainers 

Related:
https://github.com/docker/swarm/issues/2675
https://github.com/docker/swarm/pull/2679

**Comment by nishanttotla** [comment]
We should start by printing a warning during `swarm create` and add a line to the release saying that token based discovery will be deprecated after two releases.

**Comment by nishanttotla** [comment]
@dongluochen @aluzzardi any suggestions on how to add this deprecation? The most obvious place to do it would have been to print a warning message when creating a cluster using token discovery, but that might break use cases for people who rely on only a token being printed out on cluster create.

**Comment by aluzzardi** [comment]
Print the warning to stderr
