### ISSUE TITLE
Question: If I was to mount volumes on Swarm/Mesos, how to do it

### ISSUE THREAD

**Issue by Spritekin** [docker/swarm#2691]
First, let me start by saying my Swarm is a hacked one, it allows for privileged containers, fractional CPU allocations and more resilient Mesos service. 

Now, I need to mount volumes which is not supported in the Mesos version. Mesos can mount volumes in docker containers. Its just Swarm that can't.

So, just for the academic discussion. If I were to mount volumes, where should I do it?

**Comment by Spritekin** [comment]
Ok so I went into the cluster.go and printed the task info (t.TaskInfo). There is no volume information (which I sent) so it has been stripped already. Need to search more.

**Comment by Spritekin** [comment]
Ok, in case someone is interested. In cluster/mesos/task/task.go, in the build function add:
```
	// Handle mounting volumes
	for _, volumebind := range t.config.HostConfig.Binds {
		// Values come as hostpath:containerpath[:mode]
		// example /host/path:/container/path:rw
		bindinfo := strings.Split(volumebind,":")
		hostpath := bindinfo[0]
		containerpath := bindinfo[1]
		bindmode := mesosproto.Volume_RW.Enum()
		if len(bindinfo) > 2 && bindinfo[2]=="ro" {
			bindmode = mesosproto.Volume_RO.Enum()
		}

		t.Container.Volumes = append(t.Container.Volumes, &mesosproto.Volume{
					Mode:      	   bindmode,
					HostPath:      &hostpath,
					ContainerPath: &containerpath,
				})
	}
```

Works fine for me :)

Luck!

**Comment by nishanttotla** [comment]
Closing due to https://github.com/docker/swarm/pull/2853
