### ISSUE TITLE
Can´t connect 2 Stacks

### ISSUE THREAD

**Issue by Goram** [docker/swarm#2696]
I have 2 stacks where one container from the first stack has the same overlay as 3 container in the second stack. The three in the second can ping each other just fine, but can´t reach the one in the other stack. This is a haproxy container which can´t start because it doesn´t reach the other 3:

[ALERT] 124/135641 (7) : parsing [/usr/local/etc/haproxy/haproxy.cfg:33] : 'server slave1' : could not resolve address 'slave1'.
.
.
.

I created the network in composer-stack and tried it in cmd with docker network create, same results.

All containers are on different hosts, newest version of docker and docker-compose, any idea?

**Comment by nishanttotla** [comment]
@Goram this is a Swarm mode issue. Please open it on https://github.com/moby/moby.
