### ISSUE TITLE
The IP address of the host in ports is dropped when services are created

### ISSUE THREAD

**Issue by waterelder** [docker/swarm#2706]
Docker version: 17.05.0-ce, build 89658be
OS: 16.04.1-Ubuntu 4.8.0-51-generic x86_64

Steps to Reproduce:

1. Set Ports with IP in the Catalog's `docker-compose.yml`, like below:

        

     > ports: "127.0.0.1:8081:80"

2. Create a Stack StackA from this Catalog.

Results:
The StackA's generated `docker-compose.yml` has wrong Ports config, like below:

>  ServiceA:
>    PORTS:
>    *:8081->80/tcp
> 

Expected:
The StackA's generated `docker-compose.yml` should have the same IP & ports with the Catalog's docker-compose.yml:

> ServiceA:
> PORTS:
>  "127.0.0.1:8081->80/tcp"

**Comment by nishanttotla** [comment]
@waterelder this issue seems related to Docker Swarm Mode. This repo is about Docker Swarm, which is a different project. Check the README here: https://github.com/docker/swarm

Please open this issue at https://github.com/moby/moby.
