### ISSUE TITLE
swarm creates more service replicas than desired

### ISSUE THREAD

**Issue by Spectrik** [docker/swarm#2707]
Hello,

We have got 3 physical nodes.

We face problem when creating service with option --mode global. Swarm creates more replicas than desired. In our case four. So in docker service overview (docker service ls command) we can see number of replicas **4/4 instead of 3/3**

This problem actually **does not** occur very often. We have seen it only ~ three times. For example it happened after rebooting all physical nodes at the same time but it happens.

**Removing / Recreating** service resolves this problem.
**Updating** service also resolves this problem.

But imagine situation when datacenter gets into blackout (it should not happen of course but shit happens) and all nodes gets restarted. Swarm creates wrong number of replicas for example with galera service and it actually gets broken because of it. And this is wrong.

===========
 
root@test0:~# docker info
Containers: 13
 Running: 11
 Paused: 0
 Stopped: 2
Images: 182
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 179
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: lu1jofpbvaqonv7dekdhhjgsp
 Is Manager: true
 ClusterID: elw0a88zz0ytz79erse7ye8ky
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.0.20
 Manager Addresses:
  172.31.0.20:2377
  172.31.0.22:2377
  172.31.0.23:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.769 GiB
Name: test0
ID: RLQV:DBLV:U3BY:CC3V:TJEK:6KYC:SYBW:D4QU:FXHU:EJM6:A43T:ONB7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by allencloud** [comment]
Hi, @Spectrik. Thanks for your feedback.

I am afraid that your issue is related to Swarm Mode of docker engine, maybe it is more proper to post issue here https://github.com/docker/docker/issues/new . This project is about Swarm which is different from swarm mode in docker engine.

Here are more details about the difference https://github.com/docker/swarm#swarm-disambiguation

I am closing this. If you need more help, feel free to let us know. Thanks again for your contribution.
