### ISSUE TITLE
docker service update does not respect UpdateConfig

### ISSUE THREAD

**Issue by HashBanana** [docker/swarm#2715]
_This might not be an issue but a problem in my understanding._

I have the following service running, which has been deployed via `docker stack deploy -c docker-compose.yml docker-demo`:
```
ID:             lqoc3esxg9euuiirtbkgm7pa2
Name:           docker-demo_uuid-generator
Labels:
 com.docker.stack.namespace=docker-demo
Service Mode:   Replicated
 Replicas:      8
Placement:
UpdateConfig:
 Parallelism:   1
 Delay:         1m0s
 On failure:    pause
 Max failure ratio: 0
ContainerSpec:
 Image:         bravo.lab:5000/uuid-generator:latest@sha256:a914b09411986f0c32ab0a254e696821916b446d2247d8ff9f53b4383a34e184
Resources:
 Limits:
  CPU:          1
  Memory:       500 MiB
Networks: kifjbrlmm3zk8qn1e8i0h37i2
Endpoint Mode:  vip
Ports:
 PublishedPort 80
  Protocol = tcp
  TargetPort = 8080
```
This is my Docker version:
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
When i update the service, e.g. change the number of replicas, the changes get applied instantly without respecting the configured update-delay. Is this is a bug in Docker or am i missing something in my understanding about how this should work?

**Comment by HashBanana** [comment]
I finally got it to work; contrary to what the [docs](https://docs.docker.com/engine/swarm/swarm-tutorial/rolling-update/) say the update-parallelism was instantiated with 0. Im not sure if this is a bug in the docs or if i somehow manually set parallelism to 0.

**Comment by BaliStarDUT** [comment]
how does it work?I use delay with 50s，but it update within 2s.I find the  update-Delay doesn't take effect on **service update** .but between the Parallelism when Parallelism>=2. 
`UpdateConfig:
 Parallelism:	1
 Delay:		50s
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      start-first`

blow the update happend in 2seconds:
`
$ docker service ps ac_18_0_0_yztest_V0
ID                  NAME                        IMAGE                        NODE                DESIRED STATE       CURRENT STATE            ERROR               PORTS
mc7prezfg4wc        ac_18_0_0_yztest_V0.1       ab:ubuntu14.10-jdk8   wr-ac-dev02.wr      Running             Running 4 seconds ago                        *:35688->14129/tcp
limezsthsu59         \_ ac_18_0_0_yztest_V0.1   ab:ubuntu14.10-jdk8   wr-ac-dev02.wr      Shutdown            Shutdown 2 seconds ago
`
