### ISSUE TITLE
Use swarmkits node api for cluster membership management

### ISSUE THREAD

**Issue by fbuecklers** [docker/swarm#2716]
Hi,

since swarm (this) and swarm mode (swarmkit) solve different problems, is there any plan, that the swarm manager does use the native node API for cluster membership? 
Then it will be possible to use the new cluster management features from swarmkit to setup a swarm cluster (no external key value store needed and the overlay network works without any modifications on the deamon opts) but you still have the ability to run docker containers independently. 
So you still have the power of the entire docker API and you are not restricted to just use services (as swarmkit force it)

Or exists already a solution where you can combine the swarm manager and the swarmkit cluster management?

**Comment by nishanttotla** [comment]
@fbuecklers this is part of the plan for 1.3.0. I will open a separate issue/PR with the details of that, so closing this one.

**Comment by fbuecklers** [comment]
Awesome, I have seen it in the planned roadmap. Are there any ideas how it can be avoided to expose each docker deamon port manually ? 
If so it would be really easy to setup swarm on top of swarm mode.
I'm really exciting to see those improvements in the next release.

**Comment by nishanttotla** [comment]
@fbuecklers the main idea is for Swarm to use the docker API using either the docker socket or the node IP address/port. I suppose that using the socket will make things much easier.
