### ISSUE TITLE
Swarm with Compose

### ISSUE THREAD

**Issue by akdj** [docker/swarm#2725]
Hello, 

Is it possible to use swarm with docker compose?
How can I use it?   I don't use docker-machine. I found some doc which explain with docker-machine.. Is it mandatory?

**Comment by nishanttotla** [comment]
Hi @akdj. You can use Swarm with Docker compose, and using docker-machine is not necessary. You just need a way to set up multiple host machines with Docker installed on them, to use Swarm. Then you use Compose just like you use it with a Docker Engine.
