### ISSUE TITLE
docker swarm in aws is unreachable after reboot

### ISSUE THREAD

**Issue by tk0485** [docker/swarm#2733]
I have a Docker swarm, consists of a master and two worker nodes, running in AWS and every night I stop all the instances that the swarm cluster running on and boot them again next morning. The problem is every day I notice that couple services failed to start and the swarm has to recreate them (this is happening always on worker 1 only for some reason) and I can't ssh to any of the services running on worker1 or worker2 (I'm not scheduling any services on the master). when the services fail I get this error:

> task: non-zero exit (0): No such container: containerName

**P.S the ec2-instance has only a root ebs that I'm running the swarm on it.**

Also, when I stop worker1 the swarm schedule all the services in worker2 but still I wont be able to ssh to them from outside the cluster. after I start worker1 again and redistribute the services manually between worker1 and worker2 everything works fine after ( I can ssh to the containers but only the new ones created through the update command old ones still wont be accessible). the command I use for redistribution is:

> docker service update --force containerName

**RESULT**

> unable to pin image registry:myImage to digest: Get https://registry:5000/v2/: dial tcp: lookup registry: no such host myContainer

despite the error message above the service on worker2 will stop and will run on worker1 as expected.I 

I opened this issue also in [stackoverflow](https://stackoverflow.com/questions/44571366/docker-swarm-in-aws-is-unreachable-after-reboot)

**Comment by nishanttotla** [comment]
@tk0485 this is a Swarm mode issue. Please open your issue on https://github.com/moby/moby.
