### ISSUE TITLE
Refresh loop doesn't get full network information anymore

### ISSUE THREAD

**Issue by nishanttotla** [docker/swarm#2750]
At some point, the Docker API changes stopped returning the list of containers connected to a network in `NetworkList`. This causes the network info to not contain containers associated with a network each time the refresh loop runs.

Affected PR: https://github.com/docker/swarm/pull/2690

This is a release blocker.

**Comment by bklau** [comment]
@nishanttotla : What release version of Docker CE was impacted by this? Is it specific to Swarm Mode or not?. I still use Swarm Classic with standalone swarm binary installed.

**Comment by nishanttotla** [comment]
@bklau this is an issue that affects Swarm classic, and is unrelated to Swarm Mode. I think Docker version around 17.03/17.03.1 was impacted by this (though I'm not 100% certain).

**Comment by nishanttotla** [comment]
@bklau I've included a fix for this issue in #2690.

**Comment by nishanttotla** [comment]
Fixed by https://github.com/docker/swarm/pull/2690
