### ISSUE TITLE
http: no cipher suite supported by both client and server when container contacting  ingress-endpoint (ingress-sbox)

### ISSUE THREAD

**Issue by AchuthSankar** [docker/swarm#2779]
### What did you do?
We are hosting traefik in a docker swarm containing 3 managers. Things are working fine but after a week or so we start getting either of these errors continuously:
 http: TLS handshake error from 10.255.0.2:56437: tls: no cipher suite supported by both client and server
2017/07/28 06:18:17 server.go:2753: http: TLS handshake error from 10.255.0.2:44674: tls: unsupported SSLv2 handshake received
2017/07/28 06:18:26 server.go:2753: http: TLS handshake error from 10.255.0.2:48083: tls: client using inappropriate protocol fallback
2017/07/28 06:11:12 server.go:2753: http: TLS handshake error from 10.255.0.2:54382: tls: client offered an unsupported, maximum protocol version of 300

### What did you expect to see?
Once I hit the service endpoint, I should see our application JSON response.

### What did you see instead?
Once this error starts showing, our service front end starting giving 502 bad gateway. But not always, 3 in 10 times 502 bad gateway occurs.

### Output of `traefik version`: (_What version of Traefik are you using?_)
Traefik Version:
Version:      v1.3.4
Codename:     raclette
Go version:   go1.8.3
Built:        2017-07-27_03:52:53PM
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Docker version:
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

traefik.toml:
# traefik.toml
accessLogsFile = "log/access.log"
traefikLogsFile = "log/traefik.log"
logLevel = "INFO"

defaultEntryPoints = ["https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/traefik/traefik.cert"
      KeyFile = "/etc/traefik/traefik.key"

[web]
address = ":8080"
ReadOnly = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = true
swarmmode = true

I can see 10.255.0.2 as ingress-endpoint from ingress. Copying the detail of ingress:
The Strange thing is, it was working. Without any change suddenly fails followed by this error.

docker network inspect ingress.
[
    {
        "Name": "ingress",
        "Id": "g91vlveu6s2u9c4tvzqdn2e8y",
        "Created": "2017-07-27T10:01:09.111025266Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.255.0.0/16",
                    "Gateway": "10.255.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": true,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "bfdee6bece2b0750796d39533793286f599ad3f38855f4518ac545cf02048473": {
                "Name": "traefik.qml805v1p6e35ewm3e6f1qko8.zbyxdt4vawobelqp8pz7lxdp5",
                "EndpointID": "6e0e5f3d4c6bede800d6948aaa6da6f6b4df0e51d4e9b43c3fc9be88385e966e",
                "MacAddress": "02:42:0a:ff:00:07",
                "IPv4Address": "10.255.0.7/16",
                "IPv6Address": ""
            },
            "ingress-sbox": {
                "Name": "ingress-endpoint",
                "EndpointID": "10adf1878e093da50c7bfe7dcda2c0c1cdb5271db9b31c49553e4a031b20244b",
                "MacAddress": "02:42:0a:ff:00:02",
                "IPv4Address": "10.255.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4096"
        },
        "Labels": {}
    }
]

**Comment by AchuthSankar** [comment]
This issues is making us to reinstall docker environment every now and then.

**Comment by nishanttotla** [comment]
@AchuthSankar This looks like an issue on Docker Swarm Mode. This repo is for the older project "Standalone Docker Swarm". Please open the issue on https://www.github.com/moby/moby.
