### ISSUE TITLE
Access to simple string functions in (hostname) template

### ISSUE THREAD

**Issue by sbrattla** [docker/swarm#2790]
When creating a new Swarm service, I usually set hostname to a combination of {{ Service.Name }} and {{ Task.ID }}. However, depending on the length of the service name this can cause hostnames that are more than the 64 character limit and consequently break the container.

Could simple string functions be made available in the hostname templates so that I could do some simple modifications to {{ Service.Name }} ensuring that the total hostname does not grow too large?

**Comment by nishanttotla** [comment]
@sbrattla this is a Docker Swarm mode issue, not related to this repo. Could you please open it on github.com/docker/docker?
