### ISSUE TITLE
Docker Service Scale command doesn't support --timeout 

### ISSUE THREAD

**Issue by PunChaFeng** [docker/swarm#2791]
Based on my test, when I scale down a service, the container is stopped in 1 seconds after SIGTERM is sent to container. But I'd like to give it more timeout to gracefully shutting down my app. I see `docker compose` has the `--timeout` parameter to control the timeout but docker swarm not.

**Comment by nishanttotla** [comment]
@PunChaFeng this is a Docker Swarm mode issue, not related to this repo. Could you please open it on github.com/docker/docker?
