### ISSUE TITLE
its possible to run more than one Docker daemon on a single host

### ISSUE THREAD

**Issue by SvenDowideit** [docker/swarm#281]
but you don't seem to be able to `docker-swarm join` the second.

**Comment by tnachen** [comment]
out of curiousity, why would one run more than one daemon per host?

**Comment by phemmer** [comment]
I do this all the time using docker-in-docker, but I use a static discovery file, not `swarm join` (just because it's simpler).

**Comment by david-guenault** [comment]
@phemmer simple but not secure at all, say you loose a docker host, from a scheduling point of view  swarm will certainly try to schedule a container on the failed host ....

**Comment by phemmer** [comment]
@david-guenault actually it won't. Swarm detects when nodes are down.

**Comment by david-guenault** [comment]
@phemmer realy ? last time i used this backend it was not working this way... gona give it a try. May be i missed something around there.

**Comment by david-guenault** [comment]
@phemmer you were right (and i was wrong) swarm with this backend do alive checking for the members. Good ! So yeah it's a good use case. Great i learned another thing today ;-)

**Comment by aluzzardi** [comment]
@SvenDowideit You should be able to do two joins by specifying two different `--addr`

**Comment by aluzzardi** [comment]
@SvenDowideit: Can you verify if that works, and if so, close this issue?

Thanks!

**Comment by aluzzardi** [comment]
Closing for now - please re-open if needed.
