### ISSUE TITLE
Direct docker command to a worker based on manager or other node resource utilisation

### ISSUE THREAD

**Issue by ganeshmuralidhar** [docker/swarm#2810]
Hi,

I am using swarm setup for internal load testing purpose where I spin custom containers on need basis and execute tests on them before the results are published and container is killed.

To make sure that a number of parallel containers can run for executing tests, I deployed swarm and have 1 manager with 2 workers now. A shell script sitting on the manager calls for a 'docker run' to spin a container. However, as there might be a case of the manager or one of the workers exhausted in resources, I want the run command for spinning container to be directed to one of the nodes based on their current resource utilisation. The requirement would be:

- Direct the request on manager initially to Node 1 as First priority
- If Node 1 CPU is > 75% - redirect the request to Node 2
- If Node 2 CPU is also > 75% - (which is exceptional) redirect the request to Manager or fail creating a container.

Thanks in advance for the assistance,
Ganesh

**Comment by nishanttotla** [comment]
@ganeshmuralidhar please open this issue on https://www.github.com/docker/swarmkit. Sorry for the trouble.
