### ISSUE TITLE
The swarm node disappeared after  node successfully has joined a few minutes

### ISSUE THREAD

**Issue by nighteblis** [docker/swarm#2824]
The node disappeared after  node successfully has joined a few minutes.

$ sudo docker --version
Docker version 17.09.0-ce, build afdb6d4

At the worker node ,  sudo docker swarm join .   I could see the node ready at the manager node  with the command "sudo docker node ls ".  But after one minute,  the node disappeared.  BTW,   The manager and the worker node are not in the same Ethernet Subnet, They could be connected with each other.  

Steps:
master:  sudo docker swarm init  (172.16.2.x)
slave: sudo docker swarm join  ...  (10.10.x.x)   

master and slave are not in same subnet , but could ping each other.   Both node have no iptables rules. 

The error logs on slave node. 

 level=error msg="agent: session failed" error="rpc error: code = 7 desc = Permission denied: unauthorized peer role: rpc error: code = PermissionDenied desc = Permission denied: node 44whub2gp4vhkmf5vyuuh571y was removed from swarm" module="node/agent"

**Comment by lh83mail** [comment]
i got the same problem, any idea? 
-------
tail /var/log/syslog

 Dec  5 14:15:08 gcsvr03 dockerd[32193]: time="2017-12-05T14:15:08.068140152+08:00" level=error msg="agent: session failed" error="rpc error: code = 7 desc = Permission denied: unauthorized peer role: rpc error: code = PermissionDenied desc = Permission denied: node 44whub2gp4vhkmf5vyuuh571y was removed from swarm" module="node/agent"
Dec  5 14:15:14 gcsvr03 dockerd[32193]: time="2017-12-05T14:15:14.375344762+08:00" level=error msg="agent: session failed" error="rpc error: code = 7 desc = Permission denied: unauthorized peer role: rpc error: code = PermissionDenied desc = Permission denied: node 44whub2gp4vhkmf5vyuuh571y was removed from swarm" module="node/agent"
Dec  5 14:15:16 gcsvr03 dockerd[32193]: time="2017-12-05T14:15:16.939711544+08:00" level=error msg="agent: session failed" error="rpc error: code = 7 desc = Permission denied: unauthorized peer role: rpc error: code = PermissionDenied desc = Permission denied: node 44whub2gp4vhkmf5vyuuh571y was removed from swarm" module="node/agent"

**Comment by nighteblis** [comment]
@lh83mail   Refered to your logs ,  this may be a permission problems.  However I don't know why    docker engine told me "already joined" when I try to re-join swarm node.  That means the node was not removed actually ?

**Comment by nishanttotla** [comment]
@lh83mail please open this issue on https://www.github.com/docker/swarmkit. Sorry for the trouble.
