### ISSUE TITLE
[QUESTION] swarm node naming

### ISSUE THREAD

**Issue by david-guenault** [docker/swarm#284]
When joining nodes in a swarm cluster will it be possible (or already possible) to specify a node name different from the hostname ? so when you ps on a swarm manage instance it display the nodename/containername and not hostname/containername.

**Comment by aluzzardi** [comment]
Unfortunately, no. The node name is sourced from the docker daemon (`docker info`), and it currently outputs the hostname.

Changing that would require patching Docker itself.
