### ISSUE TITLE
Docker swarm not distributing services when host is down 

### ISSUE THREAD

**Issue by tiwarishrijan** [docker/swarm#2841]
I have docker 17.12 installed with the cluster of 4 nodes , when one of my nodes are going down services are not auto redeploying to another servers.
![image](https://user-images.githubusercontent.com/6523607/35991186-638e1b02-0d2c-11e8-8256-94c20bce970d.png)

--> docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:10:14 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:46 2017
  OS/Arch:      linux/amd64
  Experimental: false

**Comment by nishanttotla** [comment]
This issue should be opened on github.com/moby/moby.
