### ISSUE TITLE
a compose/service configuration directory

### ISSUE THREAD

**Issue by xenoterracide** [docker/swarm#2844]
I'd like for their to be a directory that would look for valid docker compose / service files and then bring them up that way if possible instead of running docker service. maybe `/etc/docker/services.d/*.yml` it's fairly easy to script this myself, but if it were built in to docker swarm in a way that you could be sure it wasn't run too soon... That'd be nice. if it really must have have the flexibility of the cli, then maybe just have a directory that docker runs of shell scripts. I personally will be using terraform to template my compose files so they are dropped into place complete.

**Comment by nishanttotla** [comment]
@xenoterracide please open this issue on https://www.github.com/moby/moby. Sorry for the trouble.
