### ISSUE TITLE
init with --force-new-cluster results in closed communication socket

### ISSUE THREAD

**Issue by sebastianbauer** [docker/swarm#2847]
Testing docker swarm on VMs with only one master. Re-init the master with "--force-new-cluster" closes the tcp/udp ports 7946. Have to restart docker to get it working again.

Test is for working with only two masters. I know it's not recommended, but it should work since "init --force-new-cluster". This should make the cluster working with one master again, when one master goes down.

**Comment by nishanttotla** [comment]
@sebastianbauer  please open this issue on https://www.github.com/docker/swarmkit. Sorry for the trouble.
