### ISSUE TITLE
Updating --restart-condition restarts service

### ISSUE THREAD

**Issue by TruthSpinner** [docker/swarm#2848]
When I perform a service update setting **restart-condition** to none, the involved service is restarted immediately. This restart seems unnecessary, and hinders me considerably when trying to **update my website without downtime** as described in the following: 

I have a web-site composed from an _edge-nginx_ swarm service backed by a number of in-swarm _site_ services. For each new version of the site, a new set of matching _edge-nginx_ and _site_ images are produced and deployed.

In order to allow the source IPs of users to find their way to logs etc. I have had to publish the listening ports of the _edge-nginx_ hostmode, and a further binding on a failover ip means that only a single host in the swarm can run an _edge-nginx_ at any time.

In order to make the smoothest possible transition from version A to v. B of the site, I do the following:
1. Version A is running.
2. I deploy v. B. The _site_ services start up, but _edge-nginx_ v. B must wait for v. A to release the host.
3. I enter _edge-nginx_ v. A and manually change nginx config to point to v. B. In practice the site is now updated to v. B.
4. I set **restart-condition** of _edge-nginx_ v. A to none. Now, if _edge-nginx_ v. A fails, _edge-nginx_ v. B will take over.
5. I remove v. A of _site_ services

**Comment by nishanttotla** [comment]
@TruthSpinner please open this issue on https://www.github.com/docker/swarmkit. Sorry for the trouble.
