### ISSUE TITLE
[ENH] etcd discovery backend

### ISSUE THREAD

**Issue by david-guenault** [docker/swarm#285]
I'm curently testing swarm with an etcd discovery backend. etcd is a three nodes cluster. Joining the cluster is a bit random because we do not know how many etcd hosts are available when starting the join command (production problem for example). It should be valuable to add the capabilitie to specify more than one etcd uri at startup so if i have a 4 nodes etcd cluster, swarm will try to join each specified node until he found one available. Like the zookeeper discovery backend does. Correct me if i'm wrong

**Comment by vieux** [comment]
Hi @david-guenault,

You should be able to do `etcd://192.168.0.1,192.168.0.2,192.168.0.3/path` same as zookeeper.
Did you encounter an issue ?

**Comment by vieux** [comment]
@david-guenault I'll close this one, comment if you still have an issue.

**Comment by david-guenault** [comment]
sorry was out ;-)
i gona test soon and give you feedback asap
