### ISSUE TITLE
restoring a swarm

### ISSUE THREAD

**Issue by rbucker** [docker/swarm#2852]
Sorry but ```swarm-disambiguation``` did nothing to disambiguate my confusion. 

My swarm was constructed of 3 leaders and 2 workers. Each of the nodes are constructed from RancherOS 1.3 running the latest docker:

```
$ docker version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:13:43 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:20:43 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

I'm running gitlab on another system... and pushing my staging and production containers via ```docker stack deploy``` commands using TLS params with values stored in CI/CD variables.

Suddenly I lost my leader. The swarm elected a new leader from the remaining 2 leaders... and while I reconfigured my CI/CD to point to one of the remaining leaders I set upon trying to restore the damaged former leader.

FIRST - it would have been nice to know why it disconnected from the swarm

SECOND - as I was cleaning up.... ```docker node demote``` and ```docker swarm leave```; I tried running these commands on the zombie and the surviving leaders because the DOCs do not specify which and frankly they all need to be cleaned up. When that failed I was left with no choice but to delete the contents of ```/var/lib/docker``` but since docker was running and attached to the plugins I could not delete everything without stopping the docker daemon.... but since this is RancherOS there is a system docker instance and a user docker instance. Just smashing docker was ill advised.

THIRD - I tried to force a new cluster and that failed. ```docker swarm init --force-new-cluster```. 

FOURTH - after deleting the ```/var/lib/docker``` folder, in the original leader,  About this time I started re-checking the health of the rest of the cluster and suddenly the leader's stopped functioning... so I performed a ```docker swarm init``` on the original leader.  Then a demote and node rm on the other leaders that were now dead and then rejoined all nodes to the NEW old leader.

I still have no idea what happened. And while it's a good thing that this cluster was only running 2 stacks I'm not happy that it's not stable enough to do real work.

**Comment by nishanttotla** [comment]
@rbucker please open this issue on https://www.github.com/docker/swarmkit. Sorry for the trouble.
