### ISSUE TITLE
Docker swarm join-token empty

### ISSUE THREAD

**Issue by myfriend12** [docker/swarm#2865]
I ran into a really weird issue last night with our docker swarm instance. One of our servers filled its disk space with logs which caused one of our servers to fully fill up (this caused the issue). Once that happened, our entire docker swarm system stopped responding, all workers and managers to a point they would not communicate with each other and I kept getting the error not enough managers online. I checked to make sure the managers were all online and could communicate and they could. At that point I figured it would probably be good to just reset the quorum, so I ran the command `docker swarm init --force-new-cluster --advertise-addr node01:2377` (with the proper credentials). It said it was successful and to promote other workers to managers, but it would not let me. When I ran the command `docker swarm join-token worker`, nothing was returned. It is like the key used to connect all the servers to the swarm just disappeared. In the end I had to clear our the swarm completely and re-build every single service. Has anyone experienced this before? I still have a few servers from the old swarm if more info is needed to help debug this.

**Comment by nishanttotla** [comment]
@myfriend12 can you open this issue on https://www.github.com/docker/swarmkit? This is the wrong repo for it. Thanks.
