### ISSUE TITLE
Ubuntu Trusty swarm installation  script

### ISSUE THREAD

**Issue by ssoto** [docker/swarm#293]
Hi guys,
I'm making an installation shellscript for Ubuntu Trusty to install docker + go + swarm:
https://github.com/ssoto/iso_scripts/blob/master/install-docker.sh

It is an alpha version but I am working to solve some issues.
I hope it is useful for you.

**Comment by david-guenault** [comment]
seems nice except one thing, why don't running swarm inside a container ?

**Comment by ssoto** [comment]
First of all, thanks for your feedback.

I tested swarm outside a cointainer, must it be runed inside?

**Comment by david-guenault** [comment]
must ? no, but it's better to do it this way, so you can boostrap your docker hosts remotely. Use the Dockerfile provided in github repo. My philosophy is if it can run as a containe do it ! :-)

**Comment by ssoto** [comment]
First time I tested swarm I thought, why don't dockerice that? But then I think about c_groups privileges and other system security. Some special cofinguration to run swarm inside docker is need?

**Comment by david-guenault** [comment]
nop swarm does not need to access cgroup (as far as i know), just have to connect to docker daemon through tcp.

**Comment by aluzzardi** [comment]
We are actually working on making swarm an official docker image: https://github.com/docker-library/official-images/pull/440

This is the way we are planning to distribute it: `docker run swarm`.

Thanks for the contribution, @ssoto, however we'd really like to containerize swarm.

**Comment by ssoto** [comment]
Then I will use it! Thank you so much!
