### ISSUE TITLE
[Feature] "docker system prune" for Swarm nodes

### ISSUE THREAD

**Issue by Dzhuneyt** [docker/swarm#2940]
The introduction of the "docker system prune" command was a good addition to the original Docker daemon. However, I think a similar approach is needed to maintain Swarm nodes clean and tidy (remove junk images, stopped containers, etc).

Two possible solutions:
1. `docker system prune` works on Swarm nodes by default in the future.
2. A new command `docker swarm prune` is introduced for Managers, that just propagates the `docker system prune` command across all nodes.

Thoughts?

**Comment by justincormack** [comment]
This issue is for https://github.com/docker/swarmkit not the old standalone Swarm.
