### ISSUE TITLE
How to balance containers on newly added node with same elastic IP?

### ISSUE THREAD

**Issue by sandipdivekar1** [docker/swarm#2945]
I am running docker swarm mode on docker version - 18.09.5. I am using AWS autoscaling for creating 3 masters and 4 workers. For high availability, if one of the workers goes down, all the containers from that worker node will be balanced on other workers. When autoscaling brings new node up, I am adding that worker node to the current docker swarm setup using some automation. But docker swarm is not balancing containers on that worker node. Even I tried to deploy the docker stack again, still swarm is not balancing the containers. Is it because of different node id?  How can I customize it? I am using docker compose file deploying stack. 
**Command = docker stack deploy -c dockerstack.yml NAME**

**Comment by justincormack** [comment]
This issue is for https://github.com/docker/swarmkit not the old standalone Swarm.
