### ISSUE TITLE
Canary deployment Rolling deployment and Blue-green deployment in docker swarm

### ISSUE THREAD

**Issue by itratel** [docker/swarm#2946]
**Hei,guys,How to implement canary deployment Rolling deployment and Blue-green deployment in docker swarm, you known, it can be done simply  with kubernates, But  I have no idea how to make it via swarm, could you please tell me your ideas and some advice? thanks**

**Comment by DoomTaper** [comment]
I am looking for the same

**Comment by justincormack** [comment]
This issue is for https://github.com/docker/swarmkit not the old standalone Swarm.
