### ISSUE TITLE
Should Consul discovery use the service discovery port at consul:8500?

### ISSUE THREAD

**Issue by technolo-g** [docker/swarm#295]
When using the Consul discovery mechanism it is required to run the Swarm daemon on the Docker hosts to connect to Consul, but it only puts the entry in once; nothing ever expires out of the list. Since we are running the daemon already, would it make more sense to use the services interface on Consul's port 8500 to dynamically maintain the list of servers? Or if not perhaps some expiration mechanism built into Swarm's healthcheck?

**Comment by vieux** [comment]
@technolo-g I'm not familiar with consul enough, can you try to reword your question ?

Thanks.

**Comment by technolo-g** [comment]
I'll close this until I have a more solid suggestion on how to handle it.

**Comment by cultureulterior** [comment]
I'd like to bring this up again. In general, docker swarm is a service in consul parlance-
- When it goes away, it should be dropped from the list
- When the node it is hosted on goes away, it should be dropped from the list
- You generally want a list of nodes with a single service.
