### ISSUE TITLE
discovery.hub.docker.com no longer accessible?

### ISSUE THREAD

**Issue by suihkulokki** [docker/swarm#2953]
Attempting to create a discovery token with classic swarm fails with:

docker run -it --rm swarm create
Unable to find image 'swarm:latest' locally
latest: Pulling from library/swarm
d85c18077b82: Pull complete 
1e6bb16f8cb1: Pull complete 
85bac13497d7: Pull complete 
Digest: sha256:b866583a3b8791bcd705b7bc0fd94c66b695a1a2dbaeb5f59ed29940e5015dc8
Status: Downloaded newer image for swarm:latest
2019/07/04 20:09:06 Post https://discovery.hub.docker.com/v1/clusters: dial tcp: lookup discovery.hub.docker.com on 192.168.1.1:53: no such host

**Comment by icedme666** [comment]
I have the same problem as you

**Comment by GENGSHUANGs** [comment]
I have the same problem as you

**Comment by thaJeztah** [comment]
I think that service was shut down; it was deprecated in 2017 (see https://github.com/docker/swarm/issues/2688 and https://github.com/docker/swarm/pull/2743), and the docs:

https://docs.docker.com/swarm/discovery/#docker-hub-as-a-hosted-discovery-service

<img width="926" alt="Screenshot 2019-07-17 at 22 30 52" src="https://user-images.githubusercontent.com/1804568/61409448-8e995700-a8e2-11e9-9bef-80b5eb7ae5d7.png">

**Comment by thaJeztah** [comment]
Closing, per the above
