### ISSUE TITLE
docker-swarm deployed containers not started.

### ISSUE THREAD

**Issue by ranjantomtom** [docker/swarm#2955]
Hi,

I have initiated docker swarm master/worker on the same machine and deployed  Blackduck { docker-swarm]# docker stack deploy -c docker-compose.yml hub} however all the services are replicated and not started. Do I need to update any docker file?

Any help will be appreciated.

{code}`[root@tlvzephyr01 docker-swarm]# docker stack ls
NAME                SERVICES            ORCHESTRATOR
hub                 12                  Swarm

[root@tlvzephyr01 docker-swarm]# docker service ls
ID                  NAME                 MODE                REPLICAS            IMAGE                                                 PORTS
it766zoxo9fn        hub_authentication   replicated          0/1                 blackducksoftware/blackduck-authentication:2019.6.0
ovam5hna5vg1        hub_cfssl            replicated          1/1                 blackducksoftware/blackduck-cfssl:1.0.0
j5qc448k7ooz        hub_documentation    replicated          1/1                 blackducksoftware/blackduck-documentation:2019.6.0
liomdkbvziti        hub_jobrunner        replicated          0/1                 blackducksoftware/blackduck-jobrunner:2019.6.0
hgj2sr0jzcm0        hub_logstash         replicated          1/1                 blackducksoftware/blackduck-logstash:1.0.4
pnc92g7cmtgx        hub_postgres         replicated          0/1                 blackducksoftware/blackduck-postgres:1.0.7            *:55436->5432/tcp
6kqizhc4fbmo        hub_registration     replicated          1/1                 blackducksoftware/blackduck-registration:2019.6.0
khtjdy8vkux5        hub_scan             replicated          0/1                 blackducksoftware/blackduck-scan:2019.6.0
gpm3eg9ekdb1        hub_uploadcache      replicated          1/1                 blackducksoftware/blackduck-upload-cache:1.0.8
e8u0tc0mujor        hub_webapp           replicated          0/1                 blackducksoftware/blackduck-webapp:2019.6.0
d5sovlldp1gd        hub_webserver        replicated          0/1                 blackducksoftware/blackduck-nginx:1.0.7               *:443->8443/tcp
br2735hsjlwi        hub_zookeeper        replicated          1/1                 blackducksoftware/blackduck-zookeeper:1.0.0

[root@tlvzephyr01 docker-swarm]# docker ps
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                             PORTS                          NAMES
f18e879bf1e2        blackducksoftware/blackduck-registration:2019.6.0     "docker-entrypoint.sh"   7 minutes ago       Up 7 minutes (healthy)                                            hub_registration.1.bxg6op5rerbjgow66a9ya545z
f750c664e9f9        blackducksoftware/blackduck-logstash:1.0.4            "/usr/local/bin/dock…"   10 minutes ago      Up 10 minutes (healthy)            4560/tcp, 5044/tcp, 9600/tcp   hub_logstash.1.wc1hfygfypifba9rym72r5opx
dcd782da78d0        blackducksoftware/blackduck-zookeeper:1.0.0           "docker-entrypoint.s…"   16 minutes ago      Up 16 minutes (healthy)            2181/tcp, 2888/tcp, 3888/tcp   hub_zookeeper.1.6y12hcmwb5nphjkdxgh0aw02l
61c19bed306c        blackducksoftware/blackduck-documentation:2019.6.0    "docker-entrypoint.s…"   25 minutes ago      Up 24 minutes (healthy)            8080/tcp                       hub_documentation.1.mqmrplmteg2r366c306a46i0n
a7cb2fd10a62        blackducksoftware/blackduck-authentication:2019.6.0   "docker-entrypoint.sh"   28 minutes ago      Up 28 minutes (health: starting)                                  hub_authentication.1.pyybu8ucpd9620ot39glssxep
23d0a1afab78        blackducksoftware/blackduck-cfssl:1.0.0               "docker-entrypoint.sh"   28 minutes ago      Up 28 minutes (healthy)            8888/tcp                       hub_cfssl.1.vdluu7nmdpoyr6ipiejmlppat
4418ada468db        blackducksoftware/blackduck-upload-cache:1.0.8        "/opt/blackduck/hub/…"   28 minutes ago      Up 28 minutes (healthy)            8086/tcp, 9443/tcp             hub_uploadcache.1.2n6zaj3kvrut4hlm1fzsgm0dq
3a3b2634d989        blackducksoftware/blackduck-scan:2019.6.0             "docker-entrypoint.sh"   28 minutes ago      Up 28 minutes (health: starting)                                  hub_scan.1.0ua7mj29n8m6pfqghtsu8jss0
`

**Comment by ranjantomtom** [comment]
Just to know you...I am migrating containers from docker-compose to docker swarm.

**Comment by justincormack** [comment]
This issue is for https://github.com/docker/swarmkit not the old standalone Swarm.
