### ISSUE TITLE
Application breaks when deployed to Swarm (works on Compose)

### ISSUE THREAD

**Issue by AymDev** [docker/swarm#2956]
I'm working on *Docker Compose* locally and everything is fine. However, when I deploy it to the development server (the *Swarm cluster*), the app breaks (StackOverflow question [here](https://stackoverflow.com/questions/57143819/symfony-4-app-works-with-docker-compose-but-breaks-with-docker-swarm-no-login)).

I would like to understand what could change from Compose to Swarm ?

 - Docker version: `19.03.1`
 - API version: `1.40`

**Comment by justincormack** [comment]
This issue is for https://github.com/docker/swarmkit not the old standalone Swarm.
