### ISSUE TITLE
TLS issue between Swarm and Docker nodes

### ISSUE THREAD

**Issue by ankushagarwal** [docker/swarm#296]
I am running boot2docker on OSX for testing swarm.

Ran the following on my OSX Terminal

1) swarm create

2) swarm join --hb 1 --addr=192.168.59.103:2376 token://TOKEN-ID-HERE

3) swarm manage -H tcp://0.0.0.0:4243 token://TOKEN-ID-HERE

I get this error :
```
INFO[0000] Listening for HTTP on tcp (0.0.0.0:4243)
ERRO[0000] Get http://192.168.59.103:2376/v1.15/info: malformed HTTP response "\x15\x03\x01\x00\x02\x02". Are you trying to connect to a TLS-enabled daemon without TLS?
```

I then add --tls option to swarm manage and I get : 
```
$ swarm manage --tls -H tcp://0.0.0.0:4243 token://TOKEN-ID-HERE                                                                                                                                                       
FATA[0000] Couldn't load X509 key pair (, ): open : no such file or directory. Key encrypted?
```

My docker server inside boot2docker is running with the following options 
```
/usr/local/bin/docker -d -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --tlsverify --tlscacert=/var/lib/boot2docker/tls/ca.pem --tlscert=/var/lib/boot2docker/tls/server.pem --tlskey=/var/lib/boot2docker/tls/serverkey.pem
```

I am on swarm master and docker version is 1.4.1

**Comment by cpuguy83** [comment]
@ankushagarwal This is because your boot2docker daemon is doing tls with client authentication.
This means that swarm needs to be started with with a tls client cert signed by the same CA as the boot2docker daemon's cert.

Work is being done on docker/machine to make this integration simpler.

**Comment by aluzzardi** [comment]
@ankushagarwal As @cpuguy83 says, it's because boot2docker is using TLS.

You either have to enable TLS in Swarm (which requires using `--tlscert` and `--tlskey`), or you have to disable TLS in boot2docker.

**Comment by ankushagarwal** [comment]
@aluzzardi : 
I tried this
``` 
$ swarm manage -H tcp://0.0.0.0:4243 --tlscert /Users/ankushagarwal/.boot2docker/certs/boot2docker-vm/cert.pem --tlskey /Users/ankushagarwal/.boot2docker/certs/boot2docker-vm/key.pem token://TOKEN-ID-HERE
```

and I get the output

```
INFO[0000] Listening for HTTP on tcp (0.0.0.0:4243)
ERRO[0000] Get http://192.168.59.103:2376/v1.15/info: malformed HTTP response "\x15\x03\x01\x00\x02\x02". Are you trying to connect to a TLS-enabled daemon without TLS?
ERRO[0025] Get http://192.168.59.103:2376/v1.15/info: malformed HTTP response "\x15\x03\x01\x00\x02\x02". Are you trying to connect to a TLS-enabled daemon without TLS?
ERRO[0050] Get http://192.168.59.103:2376/v1.15/info: malformed HTTP response "\x15\x03\x01\x00\x02\x02". Are you trying to connect to a TLS-enabled daemon without TLS?
ERRO[0075] Get http://192.168.59.103:2376/v1.15/info: malformed HTTP response "\x15\x03\x01\x00\x02\x02". Are you trying to connect to a TLS-enabled daemon without TLS?
```

I downloaded the latest swarm just before testing this. Commit id : ffe2800

**Comment by aluzzardi** [comment]
You need to provide either `--tls` or `--tlsverify` in addition to the other flags.

The above commit will make swarm abort if you don't, thanks for catching this.

**Comment by ddysher** [comment]
Is this working now?  I got another tls error here.

1) create two machines using docker-machine
```
$ docker-machine create -d virtualbox dev1
$ docker-machine create -d virtualbox dev2
```

2) Created cluster and registered the two machines.
```
swarm create
swarm join --addr=192.168.99.100:2376 token://TOKEN
swarm join --addr=192.168.99.101:2376 token://TOKEN
```

3) Start swarm manage:
```
swarm manage -H tcp://0.0.0.0:4243 --tls --tlsverify --tlscacert=~/.docker/machines/.client/ca.pem --tlscert=~/.docker/machines/.client/cert.pem --tlskey=~/.docker/machines/.client/key.pem token://TOKEN
```

No error from this command, but when I try to run a container, I got the following error from docker cli:
```
$ docker -H 0.0.0.0:4243 run busybox echo Hello
FATA[0000] Post http://0.0.0.0:4243/v1.16/containers/create: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16". Are you trying to connect to a TLS-enabled daemon without TLS? 
```
and the following error from swarm manage console.
```
2015/01/31 20:42:50 http: TLS handshake error from 127.0.0.1:38330: tls: oversized record received with length 21536
```

**Comment by ankushagarwal** [comment]
What are your DOCKER_* environment variables?
ᐧ

On Sat, Jan 31, 2015 at 6:02 PM, Deyuan Deng <notifications@github.com>
wrote:

> Is this working now? I got another tls error here.
>
> 1) create two machines using docker-machine
>
> $ docker-machine create -d virtualbox dev1
> $ docker-machine create -d virtualbox dev2
>
> 2) Created cluster and registered the two machines.
>
> swarm create
> swarm join --addr=192.168.99.100:2376 token://TOKEN
> swarm join --addr=192.168.99.101:2376 token://TOKEN
>
> 3) Start swarm manage:
>
> swarm manage -H tcp://0.0.0.0:4243 --tls --tlsverify --tlscacert=~/.docker/machines/.client/ca.pem --tlscert=~/.docker/machines/.client/cert.pem --tlskey=~/.docker/machines/.client/key.pem token://TOKEN
>
> No error from this command, but when I try to run a container, I got the
> following error from docker cli:
>
> $ docker -H 0.0.0.0:4243 run busybox echo Hello
> FATA[0000] Post http://0.0.0.0:4243/v1.16/containers/create: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16". Are you trying to connect to a TLS-enabled daemon without TLS?
>
> and the following error from swarm manage console.
>
> 2015/01/31 20:42:50 http: TLS handshake error from 127.0.0.1:38330: tls: oversized record received with length 21536
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/swarm/issues/296#issuecomment-72347287>.
>



-- 
Ankush Agarwal
http://ankush.io
@ankushio <https://twitter.com/ankushio>

*There are 10 types of people in this world. Those who understand binary
and those who don't.*

**Comment by ddysher** [comment]
You mean local machine?  I don't have any DOCKER_* environment var.

**Comment by ankushagarwal** [comment]
1) Yes on the machine on which you ran the docker run command. Make sure that you have nothing when you run `env | grep DOCKER`
2) Also, in the error message, why does it say port 38330?

**Comment by ddysher** [comment]
oops, I should connect to swarm manager using tls too.. 
```
docker -H 0.0.0.0:4243 --tls --tlscacert=~/.docker/machines/.client/ca.pem --tlscert=~/.docker/machines/.client/cert.pem --tlskey=~/.docker/machines/.client/key.pem run busybox echo Hello
```
That explains 38330, it's just a random port opened by docker cli to connect to swarm.

Thanks @ankushagarwal
