### ISSUE TITLE
Rollback to image of the same tag

### ISSUE THREAD

**Issue by braunsonm** [docker/swarm#2960]
Is it possible to have `docker service rollback` rollback to the previous cached image? For instance, imagine an upstream change to the image tagged `latest` causes a service to break. Is it possible for the rollback to use the previous image even if it has the same tag?

Would be cool if this usecase was explained in the docs. I can see in the service inspect that the hash is saved with the image, so I thought it could be possible.

Thanks.

**Comment by justincormack** [comment]
This issue is for https://github.com/docker/swarmkit not the old standalone Swarm.
