### ISSUE TITLE
wrong ip to node

### ISSUE THREAD

**Issue by catataw** [docker/swarm#2963]
When I'm adding a new node swarm is assigning the wrong ip to node

docker info
 Swarm: active
  NodeID: m4fm7zodif7vwmogm3drejzjg
  Is Manager: false
  Node Address: 198.50.170.172
  Manager Addresses:
   149.56.234.130:2377

docker node inspect --format '{{.Status.Addr}}' m4fm7zodif7vwmogm3drejzjg
158.69.54.40

**Comment by justincormack** [comment]
This issue is for https://github.com/docker/swarmkit not the old standalone Swarm.
