### ISSUE TITLE
How to set the unique environments for tasks on every node in docker swarm?

### ISSUE THREAD

**Issue by arvitaly** [docker/swarm#2964]
Hello!
Some arguments of **docker service create** allow to use template like **{{.Node.ID}}**. But unfortunately node labels are not supported. What is the right way for a decision of this problem: I need to set the environment variables for every task.

For example:

`docker service create --env SOME_ENV="{{.Node.Labels.SOME_NODE_LABEL_VALUE}}"`

In this way, I need to configure docker service's task especially for every swarm's node.

**Comment by justincormack** [comment]
This issue is for https://github.com/docker/swarmkit not the old standalone Swarm.
