### ISSUE TITLE
Concerns about future

### ISSUE THREAD

**Issue by vpotseluyko** [docker/swarm#2965]
Hi

What are the plans for swarm future?
Wiki is outdated, there are no public roadmaps. Is it a good technology for using in production right now/in next years?

**Comment by quangnguyen** [comment]
Future does not look so bright after reading this news:  https://thenewstack.io/mirantis-acquires-docker-enterprise/ 
Latest release is over one year ago. Four tickets were closed this year. Imho i do not expect that swarm will stay long.

**Comment by soletan** [comment]
Swarm was impressive but after announcing the sale we've stopped considering it for upcoming installations quite instantly. There is no benefit from setting up things today when there is high probability of lacking any further support in two years. 

AFAIC the brand "docker" has been damaged severely by this sale by means of trust in it and I personally assume it is now on a declining path. I don't see what Docker Inc. will provide in the future. From a developer's point of view Docker Hub is least required these days (mostly due to using registry which is included with on-premise GitLab CE) and Docker Desktop works sufficiently well today and it has been PITA for some years as well always replacing one issue with a new one. I consider the sale to be at the perfect time for getting most out of a dying horse.

If you disagree reading this statement might help: https://www.docker.com/press-release/docker-new-direction ... Docker is going to provide apps for Kubernetes endpoints. It's like Apple selling its device manufacturing department to start developing super fascinating apps for Android.

**Comment by vpotseluyko** [comment]
> Swarm was impressive but after announcing the sale we've stopped considering it for upcoming installations quite instantly. There is no benefit from setting up things today when there is high probability of lacking any further support in two years.
> 
> AFAIC the brand "docker" has been damaged severely by this sale by means of trust in it and I personally assume it is now on a declining path. I don't see what Docker Inc. will provide in the future. From a developer's point of view Docker Hub is least required these days (mostly due to using registry which is included with on-premise GitLab CE) and Docker Desktop works sufficiently well today and it has been PITA for some years as well always replacing one issue with a new one. I consider the sale to be at the perfect time for getting most out of a dying horse.
> 
> If you disagree reading this statement might help: https://www.docker.com/press-release/docker-new-direction ... Docker is going to provide apps for Kubernetes endpoints. It's like Apple selling its device manufacturing department to start developing super fascinating apps for Android.

I love swarm. It is quit easy for use, doesn't require much of setup and has enough features for production use. I can't say so about Kubernetes. So I'll miss swarm. 
Docker guys - I just wanna say you big thanks for developing such a technology.

**Comment by ithinco** [comment]
> Going forward, in partnership with the community and ecosystem, we will expand Docker Desktop and Docker Hub’s roles in the developer workflow for modern apps. Specifically, we are investing in expanding our cloud services to enable developers to quickly discover technologies for use when building applications, to easily share these apps with teammates and the community, and to run apps frictionlessly on any Kubernetes endpoint.

I'm willing to pay for a NoOps Kubernetes Service, which I only need to write code and define services and don't need to provision machines via terraform etc, hope docker can bring such a service for us.

**Comment by kkbruce** [comment]
I love swarm too. my environment is pure Windows-based, implement Kubernetes service is difficult. I know, Kubernetes is the future. So I'll miss Swarm too.

**Comment by italomaia-bk** [comment]
Is there an official response?

**Comment by mvandermade** [comment]
https://jenkins.dockerproject.org is down as well... so it seems that no pull requests can ever be approved.
I hope at least that swarm will keep working for future docker versions, but I highly doubt it now too...

**Comment by AlbertoDePena** [comment]
It would be nice if we get an official statement that swarm is dead. If not, I'm sure lots of people will continue to use it and contribute in any form. I for one love docker swarm and how simple it is to work with...

**Comment by mvandermade** [comment]
I did a little bit more background reading. It seems that this repository: https://github.com/docker/swarmkit is included in the current Docker releases. And is maintained.
And a quick look at the release notes shows swarm still is worked on.
https://docs.docker.com/engine/release-notes/

Maybe a better idea to archive this repo? To avoid confusion.

I agree, simplicity is very big plus. Easy to work with, but above all easy to set-up. No need to adjust any server settings (like swap on/off) for example, it just works with standardized install.

**Comment by mleonhard** [comment]
I tried using Kubernetes but gave up after realizing that [Kubernetes has no documentation for even basic things](https://github.com/kubernetes/website/issues/38478).  So I set up Docker on cloud VMs and it's working ok.  Now I need to pass secrets to the containers, but the only supported way is to run Docker in "swarm mode."  I'm thinking about running single-node swarms.  Before doing that, I need to know: Is Docker Swarm still maintained?

**Comment by mlin** [comment]
ICYMI, good news: https://www.mirantis.com/blog/mirantis-will-continue-to-support-and-develop-docker-swarm/

**Comment by soletan** [comment]
Gosh, I'd like to embrace all the Docker Enterprise customers for keeping addicted to this simple and just-works style of a cluster. I guess they've been committed to using Docker Swarm instead of a k8s cluster for reason in the first place.

**Comment by tgeens** [comment]
@mlin that's somewhat comforting news, yet that does not change the fact that the last commit on this project will be 6 months ago tomorrow

**Comment by thaJeztah** [comment]
This repository is for "classic" / "legacy" swarm; "swarmkit" (which drives the `docker service xx` commands, and commands such as `docker swarm init` , `docker swarm join`) is maintained in the https://github.com/docker/swarmkit repository (and a build-time dependency of the docker engine, which vendors the dependency; https://github.com/moby/moby/blob/501f103a0eb498e920dff6bf3508fcc57cf65d13/vendor.conf#L130)

**Comment by justincormack** [comment]
This issue is for https://github.com/docker/swarmkit not the old standalone Swarm.

**Comment by clintmod** [comment]
`swarm mode != docker swarm` ya'll need to read this: http://dockerlabs.collabnix.com/intermediate/swarm/difference-between-docker-swarm-vs-swarm-mode-vs-swarmkit.html
