### ISSUE TITLE
Feature Suggestion: docker swarm <stack-name> logs should provide aggregated logs from all services

### ISSUE THREAD

**Issue by KathrynN** [docker/swarm#2968]
I did check that this didn't exist in open issues / couldn't find a roadmap which mentioned this.

I am using swarm to create a small (<20 containers, <10 service) backend, and would like to be able to view the logs as the service starts in a similar way to docker-compose up.  e.g. a collated or aggregated view of all the logs.

(If I'm not in the right place, or it's already been discussed and dismissed, please let me know :) )

**Comment by justincormack** [comment]
This issue is for https://github.com/docker/swarmkit not the old standalone Swarm.
