### ISSUE TITLE
Swarm over ssl not working?

### ISSUE THREAD

**Issue by pdericson** [docker/swarm#311]
I am having trouble getting swarm working and I'm wondering if I'm doing something obviously wrong.

My error message is:

> Error response from daemon: No healthy node available in the cluster

My steps to reproduce are:

1. Use docker-machine RC1 to create a docker host on digitalocean (docker-1)
2. as `machine ssh docker-1`:

    ```swarm join --addr xx.yy.zz.252:2376 --discovery token://<token>```
    
3. as `machine ssh docker-1` (same host as step 2):

    ```swarm manage --tlsverify --tlscacert=/etc/docker/ca.pem --tlskey=/etc/docker/server-key.pem --tlscert=/etc/docker/server.pem -H tcp://xx.yy.zz.252:10000 --discovery token://<token>```

Now from the host that I did the initial `machine create docker-1` on:

docker ps

    docker --tls --tlscacert=/home/pdericson/.docker/machines/docker-1/ca.pem --tlscert=/home/pdericson/.docker/machines/docker-1/cert.pem --tlskey=/home/pdericson/.docker/machines/docker-1/key.pem -H tcp://xx.yy.zz.252:10000 ps

OK:

    CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

docker run

    docker --tls --tlscacert=/home/pdericson/.docker/machines/docker-1/ca.pem --tlscert=/home/pdericson/.docker/machines/docker-1/cert.pem --tlskey=/home/pdericson/.docker/machines/docker-1/key.pem -H tcp://xx.yy.zz.252:10000 run ubuntu:trusty /bin/bash

NG:

    FATA[0001] Error response from daemon: No healthy node available in the cluster

Notes:

- swarm manage is reporting

    Get https://xx.yy.zz.252:2376/v1.15/info: remote error: handshake failure

Any ideas?  I think it's interesting that I'm able to do a "docker ps" against xx.yy.zz.252:10000 - that makes me think I'm almost there, just not sure if I'm doing something obviously wrong so wanted to check here before I dig any deeper.

Cheers

**Comment by SvenDowideit** [comment]
As far as i understand it, swarm's TLS support requires all host's certificates to be signed using the same `ca.cert`, which is not how boot2docker (and i'm not sure about the DO machine implementation) works.

**Comment by cpuguy83** [comment]
Yes, the way docker-machine is creating certs (up to and including the RC) is not compatible with what swarm needs (for --tlsverify)
docker-machine master has changed how it generates TLS certs so that you can (more) easily add any machine created by docker-machine to a swarm cluster (assuming swarmd was started with a keypair signed by that CA as well)

On the docker-machine RC, each new machine gets a new CA key pair, a new server key pair, and a new client key pair. This is problematic because when doing tls verification (of either client and/or server), the keys you are using need to be signed by the same CA.
On docker-machine master, only 1 CA and client key pair are created (for all machines), and each machine gets its own server key pair signed by the 1 CA.

Still some work to do on the machine side to make this more seamless, but it's coming along!

**Comment by aluzzardi** [comment]
Yes, what @cpuguy83 said.

@pdericson There should be a few self explaining messages in the swarm logs about not being able to communicate with the nodes.

Can you confirm?

**Comment by pdericson** [comment]
Hmmm

Using docker-machine built from c209704

machine create -d digitalocean docker-1

machine ssh docker-1

```
root@docker-1:~# swarm join --addr ...:2376 --discovery token://...
```

machine ssh docker-1

```
root@docker-1:~# swarm manage --tlsverify --tlscacert=/etc/docker/ca.pem --tlskey=/etc/docker/server-key.pem --tlscert=/etc/docker/server.pem -H tcp://...:1000
0 --discovery token://...
INFO[0000] Listening for HTTP on tcp (...:10000)
ERRO[0000] Get https://...:2376/v1.15/info: remote error: handshake failure
ERRO[0025] Get https://...:2376/v1.15/info: remote error: handshake failure
```

Do I need to to build swarm master as well?

Really appreciate the help everyone

**Comment by ehazlett** [comment]
This is because currently machine does not generate the proper extended usage in the certificate.  I have a branch "swarm" on my fork that does this and will be merged soon.

**Comment by aluzzardi** [comment]
Thanks @ehazlett. I'm closing this down since it's not swarm related.

@pdericson: Please re-open if the problem is not fixed once @ehazlett's branch gets merged into machine.

**Comment by ehazlett** [comment]
yw

**Comment by pdericson** [comment]
Working in https://github.com/ehazlett/machine/tree/swarm :)  thanks
