### ISSUE TITLE
Swarm with tls

### ISSUE THREAD

**Issue by david-guenault** [docker/swarm#341]
May be i'm doing things wrong but here is my problem

I have built 3 docker nodes with tls client auth. I can remotly access each node. Now i want to manage the nodes trough swarm (with tls). Here is my problem

say i'm on node3 and i remotely execute docker command on node1 it work fine 

```
docker -H node1:2375 version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

But when i want to use swarm everything goes wrong for me

```
./swarm manage --tlsverify --tlscacert tlscerts/ca.pem --tlscert tlscerts/cert.pem --tlskey tlscerts/key.pem --discovery file://cluster -H 0.0.0.0:2376
INFO[0000] Listening for HTTP on tcp (0.0.0.0:2376)     
ERRO[0000] Get https://10.10.0.22:2375/v1.15/info: x509: cannot validate certificate for 10.10.0.22 because it doesn't contain any IP SANs 
ERRO[0000] Get https://10.10.0.5:2375/v1.15/info: x509: cannot validate certificate for 10.10.0.5 because it doesn't contain any IP SANs 
ERRO[0000] Get https://10.20.0.21:2375/v1.15/info: x509: cannot validate certificate for 10.20.0.21 because it doesn't contain any IP SANs 
```

the discovery file is :

```
node1:2375
node2:2375
node3:2375
```

Note that swarm certificates are generated with extendedKeyUsage = clientAuth,serverAuth according to the documentation with the same CA as for the docker servers and clients certificates.

**Comment by jhamrick** [comment]
I ran into this same issue a while back. Swarm wants to connect via the ip address, but the certificates you've generated are only for the domain. You'll need to regenerate the certificates so that they have the IP address in the subjAltName. See this guide for how to do this: http://apetec.com/support/GenerateSAN-CSR.htm

**Comment by david-guenault** [comment]
oh thx ! if it work, you save my day !

**Comment by david-guenault** [comment]
well it's a little bit more complicated than i thought ... need to rewrite everything in my procedure. What i don't get is why docker client => docker daemon work like a charm and not swarm manage => docker daemon don't. Seems that swarm is not doing client/server communication the same way that docker client does ... @vieux what do you think ?

**Comment by EmileVauge** [comment]
Same here. Unfortunately, it prevents from using swarm with docker machine :(

**Comment by david-guenault** [comment]
if you follow the documentation (strict) it work between docker client and docker daemon, but if you follow the swarm documentation, it does not work at all. This is a major issue for those who want to use docker clusters in production (in the future). I'm curently digging in the openssl documentation about using SAN certificates but i'm a real noob on this subject so help will be really apreciated

**Comment by vieux** [comment]
@david-guenault swarm act as client AND deamon, so the tls certs need to be configured to work in both ways.

It is definitely an issue with the documentation because it working ok on our side.

@EmileVauge docker machine should work with swarm, @ehazlett can you tell us more?

**Comment by ehazlett** [comment]
In machine (not yet merged; see https://github.com/docker/machine/pull/464) we use `ExtKeyUsageClientAuth` and `ExtKeyUsageServerAuth` when generating the certs.  We also pass the IPAddress of the machine as an IP SAN.

**Comment by david-guenault** [comment]
@vieux yeah i know about the client AND daemon this is why the certificate is generated with  extendedKeyUsage = clientAuth,serverAuth

- testing the swarm cert against server cert with openssl s_client / s_server give a good result. 
- testing the client cert against the swarm cert (remember both client/server) with openssl s_client / s_server give also a good result. 
- testing client cert against server cert with both docker daemon and client work well to

**Comment by jhamrick** [comment]
If it helps, here's a bash script and corresponding ssl config file you can use to create the certificates with an IP SAN: https://gist.github.com/jhamrick/ac0404839b5c7dab24b5

**Comment by david-guenault** [comment]
@jhamrick thx i'll give it a try but seems to work the same way i do it already here

**Comment by david-guenault** [comment]
@jhamrick work well but (there is always a but) you use the same certificate for all of the usages (server, client, swarm) ? what i tried was to use specialized certificates. Anyway it's a good place to start. 

btw i replaced random by urandom in the script

**Comment by jhamrick** [comment]
I had one certificate authority, but created separate certificates for each machine. The docker instance on the machine that has swarm doesn't actually use TLS, but swarm does use TLS with its own certificate, and then each of the nodes in the cluster have their own certificates as well.

Probably fine to use /dev/urandom for testing, but you should probably use /dev/random for deployment because then you're using actual randomness rather than pseudorandomness.

**Comment by EmileVauge** [comment]
Thanks @ehazlett! It would be great to be able to test it in the next rc :)

**Comment by david-guenault** [comment]
@jhamrick yup /dev/random is better but for my testing purpose it is fastest with urandom

**Comment by rgbkrk** [comment]
It's faster because `/dev/random` blocks waiting for its entropy pool to fill. `/dev/urandom` gives out random like AOL gave out CDs in the 90s.

**Comment by david-guenault** [comment]
@rgbkrk yes i totaly agree with that. The fact is that it is only for test purpose so no need to worry about entropy ;-)

**Comment by ehazlett** [comment]
@jhamrick +1 for the certgen

**Comment by david-guenault** [comment]
@vieux may be it would be valuable to add @jhamrick script to the official documentation (or at least a reference to it)

**Comment by rgbkrk** [comment]
We've actually been talking about wrapping that same script (at least the origination of it) in a Docker container in https://github.com/cloudpipe/cloudpipe/issues/50. Would you all be interested in something like that, under docker or... somewhere?

**Comment by jhamrick** [comment]
@rgbkrk That would be awesome! Definite :+1: from me.

**Comment by smashwilson** [comment]
:metal:

I've been meaning to extract that to its own repo and auto-build a container from it. We already need it in two places in the cloudpipe org, so having it as a standalone container that can be used independently would be helpful for us, too.

Somewhat ironically, it was written more or less directly from the instructions in the [Docker docs](https://docs.docker.com/articles/https/).

@jhamrick: Nicely done adding SAN support, by the way! Once I set up an independent repo, think you'd care to submit a PR to add support there, too? (I could also just adapt from your gist's version, but this way you'd get contributor credit :grinning:)

**Comment by jhamrick** [comment]
@smashwilson Sure thing, thanks!

**Comment by david-guenault** [comment]
Ok, tested with specialized certificates (server, client and client/servber) and everything is working like a charm. I close this one

**Comment by smashwilson** [comment]
The independent repo is here: https://github.com/cloudpipe/keymaster

And the container is built here: https://registry.hub.docker.com/u/cloudpipe/keymaster/

Interestingly, reading from `/dev/random` inside a container blocks indefinitely, as far as I can tell -- even when I mapped it with `--device`. Maybe it's still mapping the device from the boot2docker VM, which is also low on entropy? For keymaster, I just moved password generation outside the container, but still.

**Comment by aluzzardi** [comment]
@jhamrick This should fix the issue of IPs and TLS you mentioned.

**Comment by jhamrick** [comment]
@aluzzardi Sweet, thanks!

**Comment by blackrosezy** [comment]
@aluzzardi So with the new fix, we no longer have to generate certificate with IP SANs? I am a bit confuse here.

**Comment by ctarwater** [comment]
@blackrosezy - correct. We no longer need to use IP SANs if we generate the certificates with hostnames instead. I just wrote up step-by-step instructions for anyone curious: http://www.blackfinsecurity.com/docker-swarm-with-tls-authentication/

**Comment by SvenDowideit** [comment]
@ctarwater will you be adding that to the swarm documentation, or should I ? :)

**Comment by SvenDowideit** [comment]
this is also what https://github.com/SvenDowideit/generate_cert was created to do - its go, so we could just import the code...
