### ISSUE TITLE
[Question] How do I use or configure `swarm manage` in multi-region? 

### ISSUE THREAD

**Issue by anarcher** [docker/swarm#346]
According to the README.md, if I were right, `swarm manage` should be able to be used in other networks which is not the same as the network of `swarm join`.

    # on each of your nodes, start the swarm agent
    # <node_ip> doesn't have to be public (eg. 192.168.0.X),
    #  as long as the other nodes can reach it, it is fine.
    $ swarm join --addr=<node_ip:2375> token://<cluster_id>

    # start the manager on any machine or your laptop
    $ swarm manage -H tcp://<swarm_ip:swarm_port> token://<cluster_id>

But, after some testing, I realized that `swarm manage`(the manager) needs to be able to reach it. If I want to join via private networks(192.168.0.X) and also I want to multi region(us-east-1,us-wast-2 ...) too, how do I use and configure `swarm manage`(the manager)?

Thanks for reading. :-)

**Comment by ssoto** [comment]
I have the same question related with the `swarm manage`and its requirements.

**Comment by vieux** [comment]
@anarcher @ssoto you are both right, we updated it in the `userguide`, but we forgot in the `README.mds`

You should read

```diff
diff --git a/README.md b/README.md
index a2ababb..5d8c900 100644
--- a/README.md
+++ b/README.md
@@ -44,7 +44,7 @@ $ swarm create

 # on each of your nodes, start the swarm agent
 #  <node_ip> doesn't have to be public (eg. 192.168.0.X),
-#  as long as the other nodes can reach it, it is fine.
+#  as long as the manager and the docker cli can reach it, it is fine.
 $ swarm join --addr=<node_ip:2375> --discovery=token://<cluster_id>

 # start the manager on any machine or your laptop
```

I'll make a PR asap.
