### ISSUE TITLE
"discovery service not supported" swarm join --discovery=token://

### ISSUE THREAD

**Issue by ctarwater** [docker/swarm#351]
Trying to join a swarm by using token discovery doesn't seem to work. I have generated a swarm cluster id with `swarm generate` but when attempting to run `swarm join discovery=<cluster_id>` I always get the error that "discovery service not supported".

Also, running discovery according to the docs doesn't work if you run `--discovery=` - you have to just run `discovery=` without the `--`

**Comment by aluzzardi** [comment]
Thanks for reporting this - it's actually just a bug in the documentation.

Please use `token://<cluster_id>` instead of `--discovery`

**Comment by ctarwater** [comment]
That did it - thanks for the quick update.
