### ISSUE TITLE
etcd discovery backend SSLTLS client

### ISSUE THREAD

**Issue by david-guenault** [docker/swarm#360]
Hi, just a little question, is it planned to make etcd discovery backend compatible with SSL/TLS ? Curently only simple http client is supported on etcd discovery backend but go-etcd provide both Client and TLSClient clients. I'm not a go developer so seems to be hard to do it by myself, but if you are all overloaded it's a good way to start learning a new language :-)

**Comment by vieux** [comment]
It is not currently in our roadmap, but it would be a nice feature to have.

**Comment by david-guenault** [comment]
@vieux, @aluzzardi  The #404 make this issue redondant. I think we can close it.
