### ISSUE TITLE
 ID duplicated - Node was already added to the cluster

### ISSUE THREAD

**Issue by ctarwater** [docker/swarm#362]
Trying to launch a container into my swarm gives me the following error:

`ID duplicated. HAAX:6AZ2:5ISX:5XRJ:WDUL:LXXO:OUXD:2WJF:NBAG:ONYR:6SY4:47QP shared by xxx.30.1.xx2 and xxx.30.1.xx1`

I have my Swarm Host and two separate ec2 instances as my swarm nodes. I create my swarm, add each node to the swarm, and then start `swarm -debug manage token://<cluster_id> --host=0.0.0.0:2375` on my host.

I continue to see the "ID duplicated ..." error on my Swarm Host and trying to run new containers only seem to hit one of my nodes.  What am I missing here?

**Comment by aluzzardi** [comment]
Did you clone the instances by any chance?

That ID is generated the first time the Docker daemon is launched.

The fix is to remove `~/.docker/key.json` and let Docker re-generate the ID.

**Comment by ctarwater** [comment]
That was the issue, thanks for the clarification.

**Comment by krystism** [comment]
In ubuntu14.04, I find only 'key.json' in `/etc/docker/key.json', BUT if I delete it, docker daemon can'nt start anymore! How to solve it ?

**Comment by heartpandora** [comment]
for centos： to remove /etc/docker/key.json

**Comment by marfago** [comment]
@heartpandora :+1:

**Comment by jayantbh** [comment]
For Ubuntu 14.04, remove /etc/docker/key.json

Tested on an Ubuntu EC2 instance.

**Comment by int32bit** [comment]
Yes, this solve my problem, thx @jayantbh
