### ISSUE TITLE
Constraint filter - unable to find a node that satisfies storage==ssd

### ISSUE THREAD

**Issue by ctarwater** [docker/swarm#363]
Playing with filters and I keep getting the error that `Error response from daemon: unable to find a node that satisfies storage==ssd`

If I'm reading it right, it's adding the second '=' sign when trying to match. The actual tag shows up correctly in `docker info` as storage=ssd.

**Comment by vieux** [comment]
The `==` is expected. In `docker info` there is only one `=` because is it the format `key=value`.

In the contraints it's an expression `==` or `!=`

Can you paste us what docker run you are using ?

**Comment by ctarwater** [comment]
Sure.

`docker -H <ip>:2375 run -d -P -e constraint:storage==ssd blackfinsecurity/tha-kali`

**Comment by vieux** [comment]
What's your docker versions, locally and on your nodes ?

**Comment by ctarwater** [comment]
Version 1.4.1 on everything

**Comment by ctarwater** [comment]
Ok, nevermind. 

I was using different tags and they all work unless you try to assign a tag `node=foo`. Sorry for the bother.
