### ISSUE TITLE
Please use `uname -s`-`uname -m` as suffix for the binary releases

### ISSUE THREAD

**Issue by noodlehaus** [docker/swarm#371]
This would make it easier to embed the download links in provisioning scripts.

Example:
```
curl -s -L https://github.com/docker/swarm/releases/download/0.1.0-rc2/docker-swarm-`uname -s`-`uname -m` > /usr/local/bin/docker-swarm
```

**Comment by aluzzardi** [comment]
Hey @noodlehaus, we are actually planning to stop distributing binaries and instead rely on the docker image (docker run swarm).

Thoughts on that?

**Comment by noodlehaus** [comment]
hi @aluzzardi. i see. will swarm be made part of the docker executable as another action? `docker swarm ...`? we're hoping for the same thing with `docker machine` and `docker compose`.

**Comment by mota** [comment]
Hi @noodlehaus. I don't have the definitive answer but I think it is unlikely since tools such as swarm or machine are proposed as "batteries included but removable". They are meant to interact with the Docker API instead of being part of it.

**Comment by noodlehaus** [comment]
I see. Ok, thanks for the response :) Closing this.
