### ISSUE TITLE
[DEPRECATION WARNING] consul discovery 

### ISSUE THREAD

**Issue by david-guenault** [docker/swarm#373]
consul-discovery is deprecated since Jan 7, 2015 in favor of the api package

- https://github.com/armon/consul-api/blob/master/README.md
- https://github.com/hashicorp/consul/tree/master/api

**Comment by vieux** [comment]
@JeffChien as you wrote the 1st version of the consul discovery backend, do you have time to take care of this ? 

Thanks

**Comment by david-guenault** [comment]
@vieux @JeffChien tried with the official repo (by changing import) and everything seems to work ( building the binary by hand work but not with the Dockerfile).

**Comment by JeffChien** [comment]
@vieux @david-guenault thanks, I'll look into it

**Comment by JeffChien** [comment]
@vieux I'm a little confuse about godeps, should my PR need to update 'Godeps/_workspace' ?

**Comment by david-guenault** [comment]
@JeffChien @vieux correct me if i'm wrong but according to coding rules yes you have to make dependencies part of the PR.

**Comment by aluzzardi** [comment]
```bash
godep restore
go get -u <dependency you want to update>
godep save
```

That will update `Godeps/` and then you just need to send a PR.
