### ISSUE TITLE
Swarm needs integration tests

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#376]
Right now, we only rely on unit tests to ensure everything is working properly but that's not enough.

For instance, TLS was recently broken (https://github.com/docker/swarm/issues/341) and we didn't notice until a user reported the issue.

Integrations test should set up a real cluster of engines and daemons and test things such as:
- TLS/PKI (`swarm<->node` and `cli<->swarm`)
- End-to-end features (affinity, constraints, ...)
- API endpoints (especially the proxied one)
- Run against different versions of the engine and make sure we are compliant (both older versions and new versions).

This would also help validate that upcoming Docker releases are Swarm compatible.

**Comment by chanwit** [comment]
> Run against different versions of the engine and make sure we are compliant (both older versions and new versions).

Boot2docker does not seem to be a choice then.

**Comment by chanwit** [comment]
@aluzzardi here's a quick and dirty framework to test cluster on my own. 

https://github.com/chanwit/marine

Just in case if you're interested.

**Comment by chanwit** [comment]
As framework in #448 is working great now, scheduling strategies need an addition set of integration tests too.
  * Spread in #458 
  * Binpack tweaks in #451

**Comment by aluzzardi** [comment]
Replaced by specific integration test issues (such as #492).
