### ISSUE TITLE
Architectural question regarding high availability with swarm manager 

### ISSUE THREAD

**Issue by jmmills** [docker/swarm#377]
Just got done watching the keynote from Dockercon 2014, and started playing with swarm. I'm already finding it helpful for experimenting with multi-node environments (maybe vm's created with docker-machine should have the ability to run the swarm agent as well?), but I have a few questions about how it works behind the scenes.

If there is a one to one relationship with a docker service (node) and the swarm agent, then where does the manager fall into this? In a permanent environment would I need to elect a host to run the manager on and thus to point my clients at, or can I run multiple manager nodes (locally or otherwise) and everything would DWIM? Obviously if the manager is responsible for all of the resource balancing magic and scheduling then we wouldn't want a single instance of it running, the fact that it's managing a distributed system not-with-standing? 

Perhaps I'm jumping the gun in my line of questioning as it's alpha software, or simply ignorant of how clustering is being accomplished with swarm.

**Comment by abronan** [comment]
Hey @jmmills!

>  Obviously if the manager is responsible for all of the resource balancing magic and scheduling then we wouldn't want a single instance of it running

You are right! This falls under the failure recovery and availability of the Swarm Manager service.

As you may already know, the Swarm Manager just proxies API requests to Swarm Agents after taking scheduling decisions and **keeps local informations** about the cluster in a persistent Key/Value store. This persistent Key/Value store acts as the minimum required feature for the failure recovery of a single Swarm Manager (to keep a persistent view of the cluster after reboot). As of now, you can indeed launch multiple managers but they will have their **own - non shared - view** of the Cluster.

To have better resilience to machine failures in a cluster backed by Swarm but also allow for a better service availability under the failure of a Manager instance, we need support for the **Raft Backend** (for Master election and log replication). This way if a Manager instance dies, we can always ask for another one which will have a **consistent view of the cluster** thanks to the shared state. Hopefully, we will see this happen in a near future and this will be transparent to the users.

If the feature hits Swarm, Managers could be elected amongst a set of Swarm Agents or externally if we want to keep the entry-points to the cluster separated from actual Swarm Agents/Nodes.

I don't know if this answers all of your questions :smile:

**Comment by david-guenault** [comment]
@abronan are you sure that it is working like you said ? 
```the Swarm Manager just proxies API requests to Swarm Agents``` 
I thought that the Manager proxies API requests to docker daemons taking cluster membership from the discovery backend and does a health check of each of the docker nodes.

**Comment by abronan** [comment]
@david-guenault You said it better than I did, I just took a huge shortcut in my explanation to go straight to the shared state part :)

**Comment by david-guenault** [comment]
@abronan ok ;-).

**Comment by filosganga** [comment]
Is the fact that, every manager instance has a non shared view of the cluster,  true also in case of an external discovery system? Eg: etcd?

**Comment by abronan** [comment]
@filosganga Yes, because the discovery part (and informations about peers and their metadata replicated amongst etcd instances) is separated from the cluster management part (containers running on nodes, images pulled, resources available, etc..).

**Comment by david-guenault** [comment]
I would like to know what you mean by "cluster". I do not like the term in the swarm context. What i see is that we have three parts. Membership, node availability and scheduling (discovery backend deal it for membership, manager for availability and scheduler ... for scheduling). But availability is only from a scheduling point of view (as far as i know). The scheduling part just prevent to schedule a container on an unavailable node. The key point is that there is no rescheduling at all when a node fail (and all of the containers within this node). But swarm is on early stage and there is a lot of work to be done.

**Comment by filosganga** [comment]
Oh I see, so etcd only store the cluster topology (the nodes state), but not the docker specific informations. It seems very similar to the hdfs namenode.

**Comment by david-guenault** [comment]
@filosganga no the discovery backend store the membership. Node state is checked by swarm manage.

**Comment by filosganga** [comment]
@david-guenault thanks. Wondering why not using etcd (or consul.io) to keep the node status, in this way the information is replicated out of the box.

**Comment by abronan** [comment]
@filosganga Yes Swarm could totally use *etcd* or any kind of distributed Key/Value store and benefit from log replication. The thing is, this is quite a strong dependency just to have a shared state. Including this directly into Swarm and plugging the existing lightweight Key/Value store to a Raft backend sounds like a good idea to avoid dealing with an external service (even if it means using the etcd/raft library directly into swarm). Using an external service like etcd to deal with nodes infos will make the setup process harder. As the goal of Swarm is to be a simple solution to manage a set of docker Nodes, this seems counter-productive.

Also there are quite a few alternatives like CockroachDB's *Multiraft* (built on top of etcd/raft) which is better suited for multi-datacenter scenarios (by allowing the use of overlapping raft clusters, which makes it harder to break a quorum even if an entire region hosting Swarm Nodes goes down for some reasons).  This is still an open question :)

**Comment by abronan** [comment]
@david-guenault I think it is totally fair to call the congregation of Nodes running docker daemons as well as Swarm Agents a "cluster". They are used to host containers in a larger context and will eventually see the support for cross-container linking so I think it is fine. Or you mean it is unfair to call it a cluster because Swarm Nodes running Agents are not directly connected to each other but just accessed by the Manager? I'm confused :ghost:

**Comment by filosganga** [comment]
@abronan It makes perfect sense to me. I think swarm could abstract this part, that could be implemented as a simple solution natively, but also using some pluggable implementation.

**Comment by abronan** [comment]
Agreed :+1:. I guess that we can allow both in the long run, a default internal store with shared state that works out of the box (to keep the setup part easy for most users) but the possibility to plug additional Key/Value stores :smile: Even though we should only allow *strongly consistent* Key/Value stores to be pluggable for obvious reasons.

:bow: *performs incantation to summon the good will of repository masters*

**Comment by david-guenault** [comment]
@abronan reading (again) the roadmap it become clear that we do not have yet a "real" cluster with all of the needed features (but you are right, it's a cluster as a congregation of nodes). But it's planed => https://github.com/docker/swarm/blob/master/ROADMAP.md

**Comment by jmmills** [comment]
On the topic nomenclature, if one is wanting to avoid the term of "cluster" I vote to call it a "Pod"... because you know, there's a whale in the logo.

**Comment by aluzzardi** [comment]
Thanks @jmmills !

This will be addressed by #598 in the next release.

**Comment by aluzzardi** [comment]
So, this has been implemented in #819 #835. It's still a highly experimental feature, feel free to share your feedback.
