### ISSUE TITLE
Would people find a Hiera discovery backend useful?

### ISSUE THREAD

**Issue by jmmills** [docker/swarm#378]
My employer will be rolling puppet for managing all of various systems in the near future, so we will be deploying Hiera, rather than adding yet another service in to the environment I was thinking that it might be useful to use it as a discovery backend for swarm.
Anyone else think this would be useful?

I'm a go beginner, but I'd be willing to give it a shot.

**Comment by chanwit** [comment]
@jmmills I am doing a PR (#347) to propose a plugin system for Swarm.
With this kind of architecture, we can have a discovery service as a separated module.

**Comment by vieux** [comment]
@jmmills would you be around to support it after it's merged ?

**Comment by jmmills** [comment]
@chanwit sounds good, I'll keep an eye on it as evolves.
@vieux In theory yes, all of my contributions are tied to GitHub... even more so if my day job buys into it.

**Comment by vieux** [comment]
@jmmills any news on this ?
