### ISSUE TITLE
Proposal: move the Discovery system to an external library

### ISSUE THREAD

**Issue by inercia** [docker/swarm#387]
I propose to move the Discovery system to an external library. The code seems to be in very good shape for this, with no external dependencies and a simple API.

With this change, the same discovery mechanism could be used by external services, so they could synchronize with the current cluster managed by Swarm. For example, [Weave](https://github.com/zettio/weave) could use the same library and, when pointed to the same discovery backend, it could connect the containers in this way:

```
# create a cluster
$ swarm create
6856663cdefdec325839a4b7e1de38e8 # <- this is your unique <cluster_id>

# on each of your nodes, start the swarm and the weave agent
$ swarm join --addr=<node_ip:2375>      token://6856663cdefdec325839a4b7e1de38e8
$ weave join --addr=<node_ip:some_port> token://6856663cdefdec325839a4b7e1de38e8

# start the manager on any machine or your laptop
$ swarm manage -H tcp://<swarm_ip:swarm_port> token://<cluster_id>
```

As an external library, it could also be used as a general framework for cluster peers discovery. It could also be used for some particular cases like local area discovery, where the discovery system must consider multiple interfaces (see zettio/weave#224)

**Comment by vieux** [comment]
@inercia that's the ultimate goal, how would you implement `an external library` in go, knowing where is no shared library `(.so)` in go.

**Comment by chanwit** [comment]
@inercia I am crafting a plugin system in #347 and it can adopt to implement Swarm discovery too.

**Comment by errordeveloper** [comment]
I think the point is to make sure the code is reusable and lives in it's
own repo, I cannot see particular need for shared objects on the host it
will run on.

**Comment by inercia** [comment]
As @errordeveloper said, the point would be to move the code to its own repo so it could evolve independently from Swarm.

**Comment by vieux** [comment]
for now, we are still in beta and we don't want to vendor a bunch of code because it can change, let's revisit the issue when we will be out of beta.
