### ISSUE TITLE
Couldn't get swarm running with docker 1.4.0 and greater 

### ISSUE THREAD

**Issue by smothiki** [docker/swarm#390]
tried running swarm binary from the releases with docker version > 1.4, couldn't succeed  on both Coreos( docker version 1.4.1) and Ubuntu ( docker version 1.5.0 ) . help needed to debug the issue let me know if I'm going wrong any where .

coreos
```
swarm manage -H tcp://172.17.8.100:2375 etcd://172.17.8.100:4001/swarmpath
INFO[0000] Listening for HTTP addr=172.17.8.100:2375 proto=tcp
ERRO[0000] Get http://172.17.8.101:2375/v1.15/info: dial tcp 172.17.8.101:2375: connection refused
ERRO[0000] Get http://172.17.8.102:2375/v1.15/info: dial tcp 172.17.8.102:2375: connection refused
INFO[0000] HTTP request received method=GET uri=/v1.15/info
ERRO[0000] Node 172.17.8.100:2375 is running an unsupported version of Docker Engine. Please upgrade.
INFO[0002] HTTP request received method=GET uri=/v1.15/info
ERRO[0002] Node 172.17.8.100:2375 is running an unsupported version of Docker Engine. Please upgrade.
ERRO[0002] Get http://172.17.8.101:2375/v1.15/info: dial tcp 172.17.8.101:2375: connection refused
ERRO[0002] Get http://172.17.8.102:2375/v1.15/info: dial tcp 172.17.8.102:2375: connection refused
^[[INFO[0011] HTTP request received method=GET uri=/v1.15/info
 
 
docker -v
Docker version 1.4.1, build 5bc2ff8-dirty 
```
ubuntu
```
docker run -t -p 2375:2375 -t swarm manage token://3c9d4be38bf438b75105de9e7d923534
INFO[0000] Listening for HTTP                            addr=:2375 proto=tcp
INFO[0000] HTTP request received                         method=GET uri=/v1.15/info
ERRO[0000] Node 172.17.8.102:2375 is running an unsupported version of Docker Engine. Please upgrade. 
ERRO[0000] Get http://172.17.8.100:2375/v1.15/info: dial tcp 172.17.8.100:2375: connection refused 
ERRO[0000] Get http://172.17.8.101:2375/v1.15/info: dial tcp 172.17.8.101:2375: connection refused 
^Cvagrant@deis-03:~$ docker version
Client version: 1.5.0
```

**Comment by vieux** [comment]
Can you paste us:

```
docker -H 172.17.8.100:2375 version
#and
docker -H 172.17.8.102:2375 version
```

thanks

**Comment by smothiki** [comment]
for host 172.17.8.102 which is running swarm manager

```
docker -H 172.17.8.102:2375 version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: swarm/0.1.0
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): e87c276
```
docker info 
 ```
Containers: 2
Images: 8
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 1
Total Memory: 1.955 GiB
Name: deis-03
ID: 4X6T:WJLY:H4N3:JDCA:H5TX:FWOH:WFX2:PMNA:Z2IO:FAOQ:JIFO:4EKU
```

for host  172.17.8.100 its not runnign swarm manager 
```
docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```
I think only docker version 1.5.0 support info command .
guessing ,might be a problem at this line 
https://github.com/docker/swarm/blob/e87c276c1e3b492e30d1f8340096a77fc15a713f/cluster/node.go#L125

**Comment by vieux** [comment]
so `172.17.8.102 ` is running the manager, it shouldn't be part of the discovery. you shouldn't do the swarm join on this machine.

for `172.17.8.100` this line https://github.com/docker/swarm/blob/e87c276c1e3b492e30d1f8340096a77fc15a713f/cluster/node.go#L125 is perfectly fine.

If you do `docker -H 172.17.8.100:2375 info` you should see the ID

**Comment by smothiki** [comment]
I think the issue is  docker swarm container is not binding to the host IP and port while doing swarm join  .
got through the version error but not able to connect to peers from the swarm manager machine 
```
docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
f40e1273445d        swarm:latest        "/swarm join --addr=   16 minutes ago      Up 16 minutes       2375/tcp            jovial_sammet   
```

**Comment by vieux** [comment]
@smothiki join doesn't need to bind anything, but it needs to advertise the host ip.
Here in your command `--addr` should be the host IP.

join add the `addr` in a key/values store that's it.
then, the manager get the list from the key/values store and connect to them.

To debug, instead of the token, you could use a static list of nodes. (so you don't need to do any join)

```
$ swarm --debug manage nodes://<ip:port1>,<ip:port2>,<ip:port3>...
```

**Comment by smothiki** [comment]
This is my understanding 
- manager is trying to talk to <ip:port> on each node .
- on each node when we do a swarm join its starts a container and exposes port 2375.
So if manager has to talk to those swarm containers created while doing a swarm join , manager should know the container IP and port . giving host IP and port works only if the container port is bind to the host port .
below gist has the results for ```swarm --debug manage nodes://172.17.8.100:2375```
https://gist.github.com/smothiki/e954c6eef56a28dc6e9b

**Comment by smothiki** [comment]
Apologies 
 accidentally closed the issue

**Comment by vieux** [comment]
@smothiki this means on `172.17.8.100` you don't have docker listening on port `2375`

You need to listen on this port on docker, with `docker -d -H 0.0.0.0:2375`

**Comment by smothiki** [comment]
Thanks for the help  . swarm is running after restarting the docker engine to listen on 2375 .

```
 docker run --rm myswarm list token://5aa6fdf294eaacb7fe832d4155f75c7c
172.17.8.102:2375
172.17.8.101:2375
172.17.8.100:2375
```
But when I run  ```docker run -d -m 1g redis ``` for  3 times . The third container is starting on the same machine . each  VM I tried has 2GB of ram . Isn't it suppose to schedule the third one on a different VM  .

**Comment by smothiki** [comment]
Sorry My bad I'm not trying to launch the containers through swarm manager . 
Closing the issue . thanks for the help
