### ISSUE TITLE
Enable logging for #docker-swarm on botbot.me

### ISSUE THREAD

**Issue by thaJeztah** [docker/swarm#399]
I noticed that the #docker-swarm IRC channel currently isn't logged. Would it be possible to enable logging for this channel on https://botbot.me?

**Comment by vieux** [comment]
Yes, I asked at the beginning, but they came to the chan to verify in the middle of the night and no OP was online at that time.

I will request again

**Comment by vieux** [comment]
![screen shot 2015-02-14 at 14 05 36](https://cloud.githubusercontent.com/assets/1032519/6201231/a83469d6-b452-11e4-83f8-684a7ab52616.png)

I will contact the support.

**Comment by thaJeztah** [comment]
Great, I'll see when it is solved then, thanks!

**Comment by vieux** [comment]
Done.

**Comment by thaJeztah** [comment]
Thanks!
