### ISSUE TITLE
connection refused on swarm manage

### ISSUE THREAD

**Issue by kevinsimper** [docker/swarm#401]
I spun up some machines with `docker-machine` and then joined them in a swarm cluster, but i get a connection refused.

That is because docker on the nodes does not accept connection from outside, unless you go in a change so they listen on 0.0.0.0

That is not very clear and is not in the tutorial on the readme.

How is that done correctly?

**Comment by ehazlett** [comment]
@kevinsimper can you list what `docker-machine ls` reports?

**Comment by kevinsimper** [comment]
```
$ docker-machine ls
NAME           ACTIVE   DRIVER         STATE   URL
node01                  digitalocean   Error   tcp://104.131.178.98:2376
node02                  digitalocean   Error   tcp://104.131.39.40:2376
swarm-master   *        digitalocean   Error   tcp://104.131.6.53:2376
```

**Comment by kevinsimper** [comment]
```
ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 04:01:3f:ea:8c:01 brd ff:ff:ff:ff:ff:ff
    inet 178.62.226.213/18 brd 178.62.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::601:3fff:feea:8c01/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
root@swarm-master:~# docker run -t -p 178.62.226.213:2375 -t swarm manage token://fb826a9cb3d6f15961645e629cbe021d
docker: Invalid hostPort: 178.62.226.213. See 'docker run --help'.
root@swarm-master:~# docker run -t -p 178.62.226.213::2375 -t swarm manage token://fb826a9cb3d6f15961645e629cbe021d
Unable to find image 'swarm:latest' locally
511136ea3c5a: Pull complete
a8bbe4db330c: Pull complete
9dfb95669acc: Pull complete
0b3950daf974: Pull complete
633f3d9a9685: Pull complete
bba5f98a0414: Pull complete
defbc1ab4462: Pull complete
92d78d321ff2: Pull complete
swarm:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Status: Downloaded newer image for swarm:latest
INFO[0000] Listening for HTTP                            addr=:2375 proto=tcp
ERRO[0000] Get http://128.199.36.14:2375/v1.15/info: dial tcp 128.199.36.14:2375: connection refused
ERRO[0000] Get http://104.131.6.53:2375/v1.15/info: dial tcp 104.131.6.53:2375: connection refused
```

**Comment by kevinsimper** [comment]
```
docker run -d swarm join --addr=128.199.36.14:2375 token://fb826a9cb3d6f15961645e629cbe021d
Unable to find image 'swarm:latest' locally
511136ea3c5a: Pull complete
a8bbe4db330c: Pull complete
9dfb95669acc: Pull complete
0b3950daf974: Pull complete
633f3d9a9685: Pull complete
bba5f98a0414: Pull complete
defbc1ab4462: Pull complete
92d78d321ff2: Pull complete
swarm:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Status: Downloaded newer image for swarm:latest
7989ccfdc10885f3118a3504758739742d9b39b4371f71812cfa2a594544cc49
root@node02:~# docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
7989ccfdc108        swarm:latest        "/swarm join --addr=   3 seconds ago       Up 2 seconds        2375/tcp            kickass_ptolemy
```

**Comment by ehazlett** [comment]
Thanks.  A couple of things.  First, the machines are in the `Error` state so you will need to check DigitalOcean to make sure those instances still exist / are available.  Second, Machine will only create hosts that are TLS secured and use the Docker port 2376 (not 2375).  In order to use TLS with the swarm-master, you will need to get the certs on that host, bind mount the host dir when launching the swarm container and finally pass the cert options (`--tlsverify`, `--tlscacert`, `--tlscert` and `--tlskey`) to swarm (also when launching the container).  This will enable Swarm to communicate securely to the machines.

As an alternative,  you can use my branch from the Swarm provisioning PR for Machine (https://github.com/docker/machine/pull/464) to create secure Swarm clusters (instructions are in the readme in that branch).

**Comment by kevinsimper** [comment]
@ehazlett Thanks a lot for your help! Seems that i miss a some vital things! I thought that machine and swarm were made together, but as i can see from your branch it is very close :)

The Error state was because i had close the nodes as you guess, but then decided to do it the exact same to show what I did.

I looked at the code from your branch and can't seem to understand how i will get my certificate out on to the `swarm-master` since i create the `docker-machine`s from my personal computer.

But i would have to copy the tls certificates to my swarm master, so when i create the swarm manage container is has the same, but my swarm master was also created with the same certificates, so don't it have it already?

I hope i really can get this up and running, will try some more :)

**Comment by kevinsimper** [comment]
I shared the folder with swarm and pointed swarm to the same certificates, those that came when i created them with docker-machine:
```
docker run -t -p 5000:2375 -v /etc/docker:/etc/docker swarm manage --tlsverify --tlscacert=/etc/docker/ca.pem --tlskey=/etc/docker/server-key.pem --tlscert=/etc/docker/server.pem token://fb826a9cb3d6f15961645e629cbe0xxx
```

I also swiched the nodes to listen on 2376
```
docker run -d swarm join --addr=104.131.6.53:2376 token://fb826a9cb3d6f15961645e629cbe0xxx
```

But now i get a handshake failure
```
ERRO[0126] Get https://104.131.6.53:2376/v1.15/info: remote error: handshake failure
```

**Comment by kevinsimper** [comment]
Can read in https://github.com/docker/swarm/issues/311 that it is not the right way still.

**Comment by ehazlett** [comment]
@kevinsimper swarm provisioning is now merged into machine :)  please note: *this is experimental and the ux and commands will most likely change*.  that out of the way, here are the instructions :)

https://github.com/docker/machine#swarm

**Comment by ehazlett** [comment]
@kevinsimper were you able to get swarm with the latest beta?

**Comment by vieux** [comment]
@kevinsimper please tell us if it's still an issue.
