### ISSUE TITLE
Unable to delete a cluster using the hosted discovery service

### ISSUE THREAD

**Issue by sonchang** [docker/swarm#402]
Sending a DELETE HTTP request to:
https://discovery-stage.hub.docker.com/v1/clusters/0ac4cd6c658661d5d80bfbd0215309a0

Produces the following:
pq: update or delete on table "clusters" violates foreign key constraint "nodes_cluster_id_fkey" on table "nodes"

**Comment by aluzzardi** [comment]
Thanks @sonchang 

Will be addressed by #580
