### ISSUE TITLE
Add ssl/tls support in discovery backends

### ISSUE THREAD

**Issue by david-guenault** [docker/swarm#404]
Since all the docker tools support SSL/TLS (docker, swarm, compose ...) should it be possible in the future to add the same for discovery backends. For exemple etcd and consul does support ssl/tls but it is not possible to enable it in swarm discovery backends. 

As a reference you can see #360

**Comment by vieux** [comment]
I agree

**Comment by david-guenault** [comment]
@vieux, thinking about that i do not see how it should be implemented. The only parameter that it is curently possible is the discovery uri in the form [backend]://ip:port, ip:port,.../path. How should it be implemented ? With environment variables ?

**Comment by vieux** [comment]
@david-guenault what about etcds:// and consuls:// ? and we use the same tls certs we already have

**Comment by thaJeztah** [comment]
or  something like `etcd+https://`, `consul+https://`?

**Comment by bacongobbler** [comment]
I'm :+1: for `etcds`. I could see `etcd+https` being interpreted as two connections (etcd and https) rather than a single connection through a tls-secured etcd backend. /my2c

**Comment by david-guenault** [comment]
sorry i've been out for a while. Well etcds seems fine for me.

**Comment by abronan** [comment]
Fixed by #1254. Swarm now supports TLS for consul and etcd through `libkv` and the `--discovery-opt` flag. Closing this one.
