### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by kevinsimper** [docker/swarm#405]
You need to specify the run swarm manage needs to be with double colon when double colon.

```
$ docker run -t -p <swarm_port>:2375 -t swarm manage token://<cluster_id>
```

If you run that you get
```
docker: Invalid hostPort: <swarm_port>. See 'docker run --help'.
```

The example needs to be:
```
$ docker run -t -p <swarm_port>::2375 -t swarm manage token://<cluster_id>
```
or 
```
$ docker run -t -p <swarm_port>:2375:2375 -t swarm manage token://<cluster_id>
```

**Comment by vieux** [comment]
@kevinsimper you need to replace `<swarm_port>` by the port you want to use.

Let's say you choose swarm_port to be 4242 and cluster_id to be XXXXXXX

`$ docker run -t -p <swarm_port>:2375 -t swarm manage token://<cluster_id>`
becomes
`$ docker run -t -p 4242:2375 -t swarm manage token://XXXXXXX`
