### ISSUE TITLE
FATA[0000] discovery service not supported on manager

### ISSUE THREAD

**Issue by 128keaton** [docker/swarm#412]
Hey, I have two Nodes, Nimbus and Cringle. I initiate the nodes with:
Cringle:``` docker run -d swarm join --addr=192.168.1.139 ticket://d33760e5a31990475eef578df2955e4c ```
Nimbus: ```docker run -d swarm join --addr=192.168.1.124 ticket://d33760e5a31990475eef578df2955e4c ```

and then try to manage them on Nimbus (or Cringle) 
``` docker run -t -p 2375 -t swarm manage ticket://d33760e5a31990475eef578df2955e4c ```
and I get this:
``` FATA[0000] discovery service not supported ```

**Comment by bacongobbler** [comment]
the correct protocol is `token://` rather than `ticket://`. See https://github.com/docker/swarm/#example-usage

**Comment by 128keaton** [comment]
@bacongobbler you are right *head-desk* thats what I get for rushing. Now I have another error when starting manage.
