### ISSUE TITLE
swarm not load balancing to other node

### ISSUE THREAD

**Issue by 128keaton** [docker/swarm#414]
I have a process running in my swarm's IP, that causes the CPU to jump to 100%, shouldn't swarm be load balancing? The other node never goes about 0.3%. Is swarm not configured correctly?

**Comment by bacongobbler** [comment]
swarm's default [scheduling strategy](https://github.com/docker/swarm/tree/master/scheduler/strategy) is bin-packing, so it will always try to load up the most packed node to avoid fragmentation. There are other strategies in discussion such as #227, though.

**Comment by 128keaton** [comment]
@bacongobbler now I'm wondering if I am just running one node, because I should be going over the threshold. My 'start' command is "docker -H tcp://192.168.1.139:2375 run cadvisor" where 192.168.1.139 is a node

**Comment by aluzzardi** [comment]
@128keaton: `docker -H` should point to swarm, not a node.
