### ISSUE TITLE
Not fully understanding, help would be appreciated.

### ISSUE THREAD

**Issue by 128keaton** [docker/swarm#415]
Hi. Its me, again. I have two machines, both running docker and have swarm. The way I undertstand it is that these are nodes, so I join them together.

 Lets say **192.168.1.139 is Nimbus** and **192.168.1.124 is Cringle**. Nimbus already has a working container that I'd like balanced over itself and Cringle, so my understanding is to run ``` docker run -d swarm join --addr=192.168.1.124:2375 token://d33760e5a31990475eef578df2955e4c ``` on Nimbus and ```  docker run -d swarm join --addr=192.168.1.139:2375 token://d33760e5a31990475eef578df2955e4c ``` on Cringle, that way they are both on the node list.

 **Side note: both of their docker instances are started with the ``` -H 0.0.0.0:2375 ``` OPTION.**. 

This is where I get confused, if I want to manage the swarm, which ip do I choose (**192.168.1.124 or 192.168.1.139**) is there a 'group' swarm IP that interfaces with both of them (i.e ``` docker -H tcp://swarm_ip:2376 start mcs ```)?

**Comment by bacongobbler** [comment]
When you join a node to a cluster, it is made discoverable by the [discovery backend](https://github.com/docker/swarm/tree/master/discovery). In your case, the host addr is published to your unique token at http://discovery.hub.docker.com. When you start a manager, it uses the discovery backend to discover where the nodes are located and communicates with them.

> This is where I get confused, if I want to manage the swarm, which ip do I choose (192.168.1.124 or 192.168.1.139) is there a 'group' swarm IP that interfaces with both of them (i.e docker -H tcp://swarm_ip:2376 start mcs)?

Again, the docs demonstrate how you manage a swarm cluster by using `swarm manage token://myuniquetoken`: https://github.com/docker/swarm#example-usage

**Comment by 128keaton** [comment]
@bacongobbler ok, so how would I get the swarm IP from that url. Also, running manager from any node results in: FATA[0000] Error response from daemon: Cannot start container 35fba79b32cc037d8aa16c942714e4c6b02998f46b74c45deefc50671725d58a: Error starting userland proxy: listen tcp 0.0.0.0:2375: bind: address already in use.

**Comment by bacongobbler** [comment]
start the swarm manager on some other port: `docker run -t -p 2376:2375 -t swarm manage token://<cluster_id>`

Your swarm IP is the host running the swarm manager, and you can get more information on the swarm nodes using `docker info`. In your case:

```
docker run -t -p 2376:2375 -t swarm manage token://d33760e5a31990475eef578df2955e4c
DOCKER_HOST=tcp://localhost:2376 docker info
```

**Comment by 128keaton** [comment]
@bacongobbler alright! That got manager working fine, aside from both nodes are refusing connection. Hmm,

**Comment by 128keaton** [comment]
@bacongobbler ok, so I redid everything (fresh slate, new ID, creation, etc) and manager still spits out:
``` ERRO[0000] Get http://192.168.1.139:2375/v1.15/info: dial tcp 192.168.1.139:2375: connection refused
ERRO[0003] Get http://192.168.1.124:2375/v1.15/info: dial tcp 192.168.1.124:2375: network is unreachable. Are you trying to connect to a TLS-enabled daemon without TLS? ```

**Comment by 128keaton** [comment]
@bacongobbler got the manager working fine, now getting the IP address for the swarm is what I'm stuck on.

**Comment by vieux** [comment]
@128keaton let's restart from the beginning, create a new token.

192.168.1.139 is *Nimbus* and 192.168.1.124 is *Cringle*
on both machines, docker is listening on 0.0.0.0:2375.

Nimbus needs to join youd cluster, you do
`docker run -d swarm join --addr=192.168.1.139:2375 token://<cluster_id>`

Now Cringle need to join your cluster, you do
`docker run -d swarm join --addr=192.168.1.124:2375 token://<cluster_id>`

You cluster is now setup, you need to start the manager, on any machine, event your *laptop*.
`docker run -t -p 2376:2375 -t swarm manage token://<cluster_id>`

Now that your manager is running, you can use the CLI as follow
`docker -H <ip_laptop>:2376 info`

**Comment by 128keaton** [comment]
@vieux thanks, that got me totally up and running. Last question, is there anyway for a single container to be balanced over the two machines?

**Comment by vieux** [comment]
@128keaton what do you mean, having a single computer on 2 machines ? no you will have to run it twice.

**Comment by thaJeztah** [comment]
> Last question, is there anyway for a single container to be balanced over the two machines?

As @vieux mentioned, no, that isn't possible, Docker Swarm doesn't work at such a "low level"; it doesn't form a single "computer/CPU"; all nodes in the cluster are still separate servers, but you're able to manage them through a single tool.

A single container can *never* have more processing-power or memory than the node it's running on, but you *can* "scale" by deploying *more* containers, distributed over multiple nodes and (for example) put a load-balancer in front of that.

**Comment by vieux** [comment]
@128keaton can we close this ?
