### ISSUE TITLE
Docker Daemon ID conflict when using ubuntu deployed by IaaS image already has docker

### ISSUE THREAD

**Issue by allencloud** [docker/swarm#422]
Hi, all
when I use swarm to manage docker node, issue happens reporting docker register fails, as the docker daemon id is already taken.

I analyzed the issue and found the reason. My docker daemon was  already deployed in the IaaS image, so when I duplicated the vms with IaaS image, each docker daemon in vm has the same docker daemon id.

As a result, I have to delete the file in ~/.docker/key.json and restart docker daemon to avoid docker daemon id conflict in swarm. 

I think making docker in IaaS image is a reasonable way when deploying. Then how to make the bad influence it brings, for example docker daemon id conflict in swarm?

Best Regards.
Allen Sun

**Comment by vieux** [comment]
In my opinion, you need to remove `~/.docker/key.json ` before duplicating your VM

**Comment by allencloud** [comment]
Oh, my god, this is the easiest way to solve this issue. Thank you very much.
