### ISSUE TITLE
Container output doesn't show up without `-i` flag

### ISSUE THREAD

**Issue by jpetazzo** [docker/swarm#425]
**What I do:** `docker run busybox echo ohai`

**What I expect:** `ohai`

**What I see instead:** nothing

What I tried:

- `docker run -i busybox echo ohai` → `ohai`
- `docker run busybox sh -c "sleep 3; echo ohai"` → nothing

```
$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: swarm/0.1.0
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 2acbea1
```

**Comment by vieux** [comment]
I don't get it,

1st: I cannot reproduce, can you ?
2nd: You said in What I do/What I expect/What I see instead that you see nothing and a line after you said ` docker run -i busybox echo ohai → ohai `, so did you see ohai or not ?

**Comment by jpetazzo** [comment]
With "docker run -i" I see "ohai" but without "-i" I see nothing.

On Tue, Mar 10, 2015 at 2:42 PM, Victor Vieux <notifications@github.com>
wrote:

> I don't get it,
>
> 1st: I cannot reproduce, can you ?
> 2nd: You said in What I do/What I expect/What I see instead that you see
> nothing and a line after you said docker run -i busybox echo ohai → ohai,
> so did you see ohai or not ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/swarm/issues/425#issuecomment-78154682>.
>



-- 
@jpetazzo <https://twitter.com/jpetazzo>
"Is it safe to run applications into containers?"
http://www.slideshare.net/jpetazzo/docker-linux-containers-lxc-and-security

**Comment by vieux** [comment]
@jpetazzo can you reproduce with the last version ? (I can't)

**Comment by vieux** [comment]
ping @abronan

**Comment by jpetazzo** [comment]
I don't know if I'll be able to test before end of April :/

Are you able to reproduce with 0.1? If you can repro with 0.1 but not with
master, you probably fixed it :-)

**Comment by abronan** [comment]
@jpetazzo I managed to reproduce the issue on a vagrant setup with:

```
$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

Will look into it..

**Comment by abronan** [comment]
I cannot pinpoint to the location of the issue.

@jpetazzo What was your setup at the time of the test?

@vieux cannot reproduce it with 3 distant agents and a local manager while I can reproduce with 4 local VMs (Agents and Manager directly accessible to each other). Seems to be latency related but not sure.

**Comment by jpetazzo** [comment]
I've reproduced with:

- local manager + nodes on EC2 (with various latencies; i.e. SF-to-Oregon, Paris-to-Ireland, and a few others)
- manager and nodes all on EC2

**Comment by abronan** [comment]
@jpetazzo thanks for the followup. Ok this eliminates an hypothesis :)

**Comment by abronan** [comment]
@jpetazzo Just an FYI but I cannot reproduce anymore with `master`. Would be cool if you can confirm that the issue vanished or still persists on your setup :smile:

**Comment by aluzzardi** [comment]
Assuming this is fixed
