### ISSUE TITLE
No healthy node available in the cluster

### ISSUE THREAD

**Issue by aanm** [docker/swarm#429]
I've followed this example https://github.com/docker/swarm#example-usage

I'm running 4 VMs (192.168.3.{1,4}), they ping each other.
The .1 is the manager and the rest are nodes.
The manager was started with the following command:
`sudo docker run -d -p 2375:2375 swarm manage token://<token-id>`
I can't start any containers on the manager since I get this:
`FATA[0000] Error response from daemon: No healthy node available in the cluster`
If I see the log from manager I get this:
```
ERRO[0858] Get http://192.168.3.3:2375/v1.15/info: dial tcp 192.168.3.3:2375: connection refused 
ERRO[0858] Get http://192.168.3.2:2375/v1.15/info: dial tcp 192.168.3.2:2375: connection refused 
ERRO[0858] Get http://192.168.3.4:2375/v1.15/info: dial tcp 192.168.3.4:2375: connection refused 
```
If I try to run `nc -l 2376` on one VM and `nc 192.168.3.1 2376` on another they speak with each other.
Any ideas?

**Comment by bacongobbler** [comment]
you have the swarm cluster binding on port 2375 yet you're targeting 2376 with `nc`. When you joined the nodes to the token via `docker run -d swarm join --addr=<node_ip:2375> token://<cluster_id>`, try using 2376 instead of 2375.

**Comment by aanm** [comment]
the `nc -l 2376` part was only to test if the VMs could speak with each other via TCP

**Comment by olc** [comment]
You should use a different port for 'swarm_port', for exemple:
`sudo docker run -d -p 1234:2375 swarm manage token://<token-id>`

After that, you will be able to use the regular CLI in order to send docker commands through swarm:
`docker -H tcp://<swarm_ip>:1234 info`

HTH

**Comment by aanm** [comment]
```
sudo docker run -d -p 2376:2375 swarm manage token://<token-id>
 sudo docker -H tcp://127.0.0.1:2376 info
Containers: 0
Nodes: 0
```

**Comment by aanm** [comment]
I was using Vagrant for the nodes, I tried to use one physical machine in one of the nodes and I got it working as expected.
Thanks for the support guys.
Should I close it or leave it open so other people with the same problem can reach it?

**Comment by vieux** [comment]
I think closing it is better, thanks for the update @aanm

**Comment by Odravison** [comment]
Hello guys, i got the same problem. 
I'm using VM on AWS with only one node on the swarm. The swarm, also, it's a VM on AWS. The security politic groups is enabled to comunicate with HTTP on PORT 80 in wich nodes (SWARM and NODE0).

I'm brazilian guy, sorry about the english.

**Comment by gkgt80** [comment]
One of the reason this error come if you are using 
swarm version 1.2.0 , 1.2.1, 1.2.2
