### ISSUE TITLE
broken links for swarm documentation

### ISSUE THREAD

**Issue by scollier** [docker/swarm#436]
All of the links at the bottom of the page:

https://github.com/docker/swarm/tree/master/scheduler/strategy

are broken.  Specifically, the ones under this section:

"Docker Swarm documentation index"

**Comment by vieux** [comment]
ping @SvenDowideit

**Comment by vieux** [comment]
ping @SvenDowideit

**Comment by SvenDowideit** [comment]
yeah - those links are written for the published docs: http://docs.docker.com/swarm/scheduler/strategy/

If people are reading them here, I guess we'll have to rename the files in this repo to match how they're published.

**Comment by vieux** [comment]
I believe every issue is fixed.
