### ISSUE TITLE
Question: Relationship between docker endpoints and swarm endpoints

### ISSUE THREAD

**Issue by squillace** [docker/swarm#437]
Sort of a followup from [https://github.com/docker/swarm/issues/415](https://github.com/docker/swarm/issues/415). 

> Edit: I'm not using docker-machine to create the VMs; this is about what I must do with the VMs such that swarm works as it should with docker in cloud VMs.

I am hosting the $master and $node1 and $node2 in the cloud, all three in completely separate VMs. Because I'm using Microsoft Azure, the default docker port -- secured by default, also -- is port 4243 on all machines. I'm operating all this from an Ubuntu laptop sitting... on my lap.

I can create the cluster id no problem with:
> `docker --tls -H tcp://$master:4243 run swarm create`

and I get back a lovely $clusterid. Great. So then I go to $node1 and request the join, like so, specifying NOT 2375 but the docker endpoint, 4243. NO doc has this, but on the other hand, what should I be doing here? BECAUSE... when I do:

> `docker --tls -H tcp://$node1:4243 run -d swarm join --addr:$node1:4243 token://$clusterid`

it returns fine but look at the port I get back from ps -a:

> **2375/tcp**

which implies that I must ALWAYS set the addr port to 2375 no matter what, because it's hard coded. OK, I can do that.... 

Can someone confirm that I MUST use 2375 as the --addr port and then answer whether I must then open port 2375 on the VM and map it to the swarm container's port?

> [Update]: If I use 2375 as specified, and open up a VM port mapped to it, nothing changes in the $master node when swarm list is called.

If I do it the way I'm doing it, I end up with my master doing a swarm list on docker port 4243 that returns the two node endpoints, but if I do my $master's swarm port (2375:2375) I get back a report that the swarm has no healthy nodes....

I really want to understand what the 2375 port represents:

- relative to the existing docker ports on those VMs
- relative to the swarm $master VM port/swarm $master container port
- whether any thing tries to connect to the $node swarm VM ports on 2375 (requiring me to open them up at the VM level and map those to the containers)

Hope I'm being clear. Thanks in advance. I've been on the IRC channel for the past two days, but it's of course been the weekend....

**Comment by vieux** [comment]
>it returns fine but look at the port I get back from ps -a:

>>    2375/tcp

No that's because the port 2375 is exposed in the swarm image.
As you can see the port is not used (otherwise you would have something like `0.0.0.0:2375->2375/tcp` in ps)

So your `docker --tls -H tcp://$node1:4243 run -d swarm join --addr:$node1:4243 token://$clusterid` seems totally fine.

If you do a `docker --tls -H tcp://$node1:4243 run -d swarm list token://$clusterid` you should see your node1 with the port 4243


We are going to update the docs to say that 2375 is just an example.

**Comment by squillace** [comment]
Thanks, so in theory, when I get the proper listing at the end, that seems correct, then? What is the best next steps to demonstrate that the management is working? Should I spawn three port 80 nginx'es to produce a failure? What's the simplest you can think of?

I'm happy to submit the doc fix as a PR so that you can focus on other things. :-)

**Comment by vieux** [comment]
@squillace `docker info` should print you CPUs/Memory and addr of all your nodes.

please submit the PR :D

**Comment by squillace** [comment]
I'm repro'ing my world, and then I'll be happy to submit the PR.

**Comment by squillace** [comment]
one final confirmation: I apologize, but want to be sure:

I should be able to start manage by saying 

> docker --tls -H tcp://$master:4243 run -d -p 2375:4243 swarm manage token://$clusterid

correct? that is, I connect to the master's docker port, then pass some random open port (2375), and then my docker port (4243)? this is the master's docker host starting `swarm manage`. 

if so, then I can connect to the manager on $master by which of the following calls?:

1. docker --tls -H tcp://$master:4243 run swarm list token://$clusterid
2. docker <no --tls> -H tcp://$master:2375 run swarm list token://$clusterid

?? the first one asks docker to create a container with swarm running and have it list the nodes, whereas the second one would connect to the SWARM container running on $master and ask THAT manager to list its cluster's nodes. 

I think, but want to be crystal clear before I teach others the wrong thing. Thanks for your patience.

**Comment by vieux** [comment]
No, you cannot do `docker -H tcp://$master:4243 run -d -p 2375:4243 swarm manage token://$clusterid`

`-p 2375:4243` will redirect the port 4243 inside the container to the host. but inside the container, swarm isn't listening on 4243, but 2375, so you would need to do

`docker -H tcp://$master:4243 run -d -p 2375:2375 swarm manage token://$clusterid`

If you do that, docker listen on 4243 and swarm listen on 2375

**Comment by vieux** [comment]
@squillace can we close this ?

**Comment by squillace** [comment]
My apologies. You bet!

**Comment by aluzzardi** [comment]
Re-opening. We have a docs issue.

**Comment by aluzzardi** [comment]
ping @moxiegirl

**Comment by amitshukla** [comment]
Closing as this is pretty old
