### ISSUE TITLE
Swarms created on Hub discovery service should be linked to Hub accounts

### ISSUE THREAD

**Issue by bfirsh** [docker/swarm#438]
At some point, we may have some kind of UI for managing Swarms created with the Hub discovery service. To be able to do this, we should connect Swarms that have been created to Hub accounts.

When running `swarm create`, it should first ask you to provide user/pass to log in with, then the Swarm will be attached to this user.

In the future when we allow you to use custom token servers, this could also work in a similar way with them, like you can provide auth details to a third-party image registry. Perhaps there could be some way of making it optional for third party token servers?

**Comment by vieux** [comment]
This is being worked on #695

**Comment by nishanttotla** [comment]
Closing this issue since Hub discovery service is now deprecated: https://github.com/docker/swarm/pull/2743

**Comment by bfirsh** [comment]
Oh wow! I remember this. So pleasing to see that after all these years the intent behind this has now actually been implemented in Cloud and D4M. 🎉

**Comment by bfirsh** [comment]
(Congrats!)

**Comment by nishanttotla** [comment]
@bfirsh much has changed too 😸
