### ISSUE TITLE
Proposal: Soft Affinities

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#447]
Currently, affinities are **hard** enforced, that is, if an affinity cannot be met the container won't be scheduled.

We'd like to introduce **soft affinities**. Soft affinities would provide the behavior as regular affinities, except that if the conditions aren't met the scheduler would simply discard them.

## Use Cases

Here are a few examples showcasing how soft affinities are useful.

### Faster container start time

It is currently possible to use affinities to force a container to be scheduled on a machine that already has a particular image through `affinity:image==foo`. However, if no machine has the image already pulled, the container won't schedule.

With soft affinities however, containers would be scheduled on machines with said image **if possible**, resulting in speedy start up time. If no machine is found, the container would end up on any other machine resulting in a pull.

### High Availability

Container anti-affinities (`affinity:container!=foo`) are a great way to provide high availability: Ensure that a *redis* master doesn't end up on the same machine as the slave, make sure that my web front-ends are running on different machines, etc.

However, the side effect is that one cannot run more containers of the same type as there are machines in the cluster.

For instance, `container:name!=webapp_*` will schedule all `webapp_*` containers on different machines, but once said container is running on every single node in the cluster, no more `webapp_*` containers can be scheduled.

Using soft-affinities, *webapp* containers will be scheduled on different machines (just like with hard-affinities), but once *webapp* is running on every machine, the scheduler will ignore the affinity and use bin packing as usual, thus achieve high availability and cluster resource optimization at the same time.

## Syntax

This is up for debate. There are (at least) a couple of ways to express soft affinities.

With a different *keyword*, such as `soft-affinity:container!=foo` or `preference:container!=foo` or with a slightly altered *affinity* syntax, such as `affinity:container!=~foo` (`~` representing a soft affinity).

**Comment by vieux** [comment]
I am in favor of using `~` because we could event support "soft constraint" like, try to put my container on a fedora machine, but if there no fedora availalble, put it anywhere else:

`-e constraint:operatingsystem==~fedora`

**Comment by gabrtv** [comment]
+1. This is also a hard requirement for us to adopt to Swarm in a production setting. :racehorse:

In my opinion, soft affinity is the best way to achieve HA placement of homogenous containers distributed via the bin packing strategy.  As an example, if I scale web=5, I'm likely to wind up with 5 containers on the same host.  If I lose that host I suffer an outage of all 5 containers.  With soft affinity, I can achieve an even spread regardless of cluster size.  We would still benefit from the efficiency of bin packing for heterogenous containers.

With regard to syntax, I think the likelihood of adding "soft constraints" is high.  I prefer standardizing on a special operator like `~` as @vieux suggested.

**Comment by vieux** [comment]
Closed by #478
