### ISSUE TITLE
Cannot create node

### ISSUE THREAD

**Issue by apexskier** [docker/swarm#449]
I've created a swarm on a single machine.
```
$ docker run --rm swarm create
<token>
```
Then I started a node on that same machine.
`$ docker run -d swarm join --addr=<ip of this machine>:2375 token://<token from last command>`

I don't see any nodes available when managing.
```
$ docker run -d -p 1234:2375 swarm manage token://<token>
...
$ docker -H tcp://0.0.0.0:1234 info
Containers: 0
Nodes: 0
```

Am I not allowed to use the creation machine as a node? Am I doing something else wrong?

**Comment by vieux** [comment]
Is docker listening on 2375 on your machine ?

Can you do `docker -H <ip of this machine>:2375 info` ?

**Comment by apexskier** [comment]
No, that's not working.

```
$ docker -H <ip>:2375 info
FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 
$ docker -H localhost:2375 info
FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 
$ docker -H localhost:1234 info 
Containers: 0
Nodes: 0
$ docker -H <ip>:2375 info
Containers: 0
Nodes: 0
```

Ah, after some research, is my problem that I'm not making docker available over tcp?

https://docs.docker.com/articles/basics/#bind-docker-to-another-hostport-or-a-unix-socket

**Comment by vieux** [comment]
@apexskier yes exactly, docker needs to listen en tcp

**Comment by apexskier** [comment]
Starting the docker daemon with the -H flag solved this.
