### ISSUE TITLE
Docker Labels and Constraint Filter

### ISSUE THREAD

**Issue by k2xl** [docker/swarm#450]
I have a file "deploy.txt" with 
```
[node1]:2375
[node2]:2375
[node3]:2375
```
On node 1:
```
docker -H tcp://0.0.0.0:2375 -d --label blah=123
```
On node 2:
```
docker -H tcp://0.0.0.0:2375 -d --label blah=321
```
On node 3:
```
docker -H tcp://0.0.0.0:2375 -d --label blah=999
```
I run
```
swarm manage file://$PWD/deploy.txt 
```
on my linux machine which has access to all the nodes (BTW, is there a way to run swarm manage as daemon? Right now I have to launch another process to do the next few commands...)

(Note that the reason I'm using swarm executable is because when I use the swarm docker container the file is unable to be found since it looks for the file inside the docker container instead of my file system... something i advice the docs make clearer)

I see log output happen on all the nodes as soon as I run swarm manage command and things appear good. Here is where the weird thing happens.

I then run on my linux machine running swarm manage:
```
docker -H 0.0.0.0:2375 run -P -e constraint:blah==321 ubuntu:14.04 echo 'hi'
```
I see 
```
FATA[0000] Error response from daemon: unable to find a node that satisfies blah==321
```
This also happens when doing blah==123.
HOWEVER, for blah==999
```
docker -H 0.0.0.0:2375 run -P e constraint:blah==321 ubuntu:14.04 echo 'hi'
hi
```
... it works as expected! (I can see node 3 getting the containers and 'hi' outputs on console)

Each time I try this, it is almost as if only one of the nodes will work. Am I doing something wrong here?

**Comment by vieux** [comment]
in `deploy.txt` you have
```
<ip_node1>:2375
<ip_node2>:2375
<ip_node3>:2375
```

right ?

--- 

`swarm manage -H 9999:2375 file://$PWD/deploy.txt ` what is this `9999` here ???

**Comment by k2xl** [comment]
@vieux  - My fault. I copied and pasted the wrong command from my history. I updated the top. I simply ran 
```
swarm manage file://$PWD/deploy.txt

**Comment by vieux** [comment]
@k2xl so I guess the last example in the pr is also wrong ?

**Comment by vieux** [comment]
```
docker -H 0.0.0.0:2375 run -P -e blah=999 -e constraint:blah==999 ubuntu:14.04 echo 'hi'
hi
```

???

**Comment by k2xl** [comment]
What is wrong about it? Are you referring to passing in blah as an env variable as well as a constraint? Even if I don't and only have the constraint I still have the same issue.

**Comment by k2xl** [comment]
What should the command be?

**Comment by k2xl** [comment]
I updated the example above to remove the -e blah=999. It still has the same issue in not finding the node...

**Comment by k2xl** [comment]
I figured it out. It was related to this: https://github.com/docker/swarm/issues/380

I was seeing "duplicate IDs" but wasn't sure what was going on. When the nodes were provisioned they were cloned so the key.json was the same.

Removing /etc/docker/key.json on each node then restarting the service worked!
