### ISSUE TITLE
How to integrate swarm with mesos

### ISSUE THREAD

**Issue by kakazuo** [docker/swarm#462]
Hi, I have several questions on integration between swarm and mesos:

First one. how to configure the swarm and mesos to implement the integration? I have a mesos cluster with three master nodes,  and I installed swarm on all master nodes using go get. then I tried to run command:

./swarm manage --cluster mesos zk://192.168.140.134,192.168.140.135,192.168.140.136/mesos

it responses:

INFO[0000] Listening for HTTP                            addr=127.0.0.1:2375 proto=tcp
FATA[0000] missing port in address info_0000000025

how can I fix this problem?

Second one, as you know, it also can manage the docker cluster using mesos integrated with marathon/chronos, so what are the advantages of integration swarm with mesos, why do I need to do like this?

hope can get answers quickly, thanks very much >_<

**Comment by vieux** [comment]
The mesos and swarm integration is in process, it is not merged so `./swarm manage --cluster mesos zk://192.168.140.134,192.168.140.135,192.168.140.136/mesos` won't work as `--cluster` doesn't exists in swarm yet.

Regarding the "why?" Swarm uses the same API as docker, this means if you are used to the docker cli and if you have tools that works today on top of docker (like fig) they will work on your mesos cluster thanks to swarm.

**Comment by aluzzardi** [comment]
It's in master
