### ISSUE TITLE
Permission denied on swarm create

### ISSUE THREAD

**Issue by gideonairex** [docker/swarm#469]
I run __docker run --rm swarm create__. It returns
```
pq: permission denied for relation clusters
```
Am i missing something? I dont know where this error comes from.

**Comment by vieux** [comment]
Sorry, it was an error on our side. Fixed.

**Comment by gideonairex** [comment]
Where can I pull the fixed swarm?

**Comment by vieux** [comment]
@gideonairex sorry, It broke again, I'm working on a fix

**Comment by gideonairex** [comment]
Okay thanks

**Comment by pchaussalet** [comment]
@vieux Is the problem related to swarm or to the docker image ? (i.e. : do I have a chance to be able to build a usable version from sources ?)

**Comment by vieux** [comment]
@pchaussalet it's an issue with the hosted service

**Comment by pchaussalet** [comment]
@vieux ok, no chance, then... thx

**Comment by vieux** [comment]
@pchaussalet @gideonairex I fixed the issue for now, we are going to migrate to a new DB in a few days.

**Comment by gideonairex** [comment]
Thanks man!

**Comment by conradkleinespel** [comment]
I'm getting this error too, now. @vieux or @gideonairex , any idea if this is a problem on my end ? Thanks for any help / tip you can give :+1:

**Comment by sandric** [comment]
so what, is it fixed, should I take it from git master?

**Comment by vanzhiganov** [comment]
Try to execute command with `sudo`
