### ISSUE TITLE
Proposal: Swarm should have the MAINTAINERs file

### ISSUE THREAD

**Issue by chanwit** [docker/swarm#484]
The project grows and I'd like to know who should I talk to for code reviews.
The MAINTAINERS file is a good place for new comers to know about this.
As an outside contributor, I have my guess as following:

```
[core]
vieux
aluzzardi
abronan

[documentation]
SvenDowideit

```

/cc @vieux

**Comment by vieux** [comment]
@chanwit let's keep something simpler for now like https://github.com/docker/distribution/blob/master/MAINTAINERS or https://github.com/docker/machine/blob/master/MAINTAINERS

**Comment by chanwit** [comment]
+1
