### ISSUE TITLE
Minor typos in "Filter" documentation

### ISSUE THREAD

**Issue by Nickology** [docker/swarm#488]
Though the content appears to be identical, there are two small typos on [docs.docker.com](http://docs.docker.com/swarm/scheduler/filter/) and one in the [README.md](https://github.com/docker/swarm/blob/master/scheduler/filter/README.md).

On [docs.docker.com](http://docs.docker.com/swarm/scheduler/filter/):
* _You can schedule a container only on nodes where the images **are** already pulled._
* _So 'NoDe1' or 'NODE1' will also **match**._

In [swarm/scheduler/filter/README.md](https://github.com/docker/swarm/blob/master/scheduler/filter/README.md):
* _So 'NoDe1' or 'NODE1' will also **match**._

**Comment by abronan** [comment]
Hey @Nickology, thank you for reporting the typos! Would you like to submit a Pull Request for this? We would be happy to merge :)

**Comment by Nickology** [comment]
Hi @abronan. I'll submit one right away. :)
