### ISSUE TITLE
swarm doesnt work with private repositories 

### ISSUE THREAD

**Issue by oba11** [docker/swarm#490]
Hi,

Currently playing around with swarm.
I tried `docker run -d -p 80:80 --name app private/app`
I get this error `FATA[0001] Error response from daemon: Error: image private/app: not found`
Note: I already have my .dockercfg in the home directory which works

I manually pulled the image on one of the swarm-hosts but didnt work either

I got it working only by using image affinity `docker run -d -p 80:80 --name app -e affinity:image==private/app private/app`.

Would be great if there is no need to manually pull the private image and setting affinity filter to use a private image in docker registry.
Thank you

**Comment by vieux** [comment]
This is expected for now, as explained in https://github.com/docker/swarm/pull/349

**Comment by aluzzardi** [comment]
Please see #374
