### ISSUE TITLE
Integration tests for API

### ISSUE THREAD

**Issue by jfrazelle** [docker/swarm#492]
Right now, the API is not being covered by unit tests since it's hard to properly test. Integration tests could be written covering every supported CLI command.

Currently, we are missing the following tests:
- [x] docker attach
- [x] docker build
- [x] docker commit
- [x] docker cp
- [x] docker create
- [x] docker diff
- [x] docker events
- [x] docker exec
- [x] docker export
- [x] docker history
- [x] docker images
- [ ] docker import
- [x] docker info
- [x] docker inspect
- [x] docker kill
- [x] docker load
- [ ] docker login
- [ ] docker logout
- [x] docker logs
- [x] docker port
- [x] docker pause
- [x] docker ps
- [x] docker pull
- [ ] docker push
- [x] docker rename
- [x] docker restart
- [x] docker rm
- [x] docker rmi
- [x] docker run
- [x] docker save
- [x] docker search
- [x] docker start
- [x] docker stats
- [x] docker stop
- [x] docker tag
- [x] docker top
- [x] docker unpause
- [x] docker version
- [x] docker wait

Help very appreciated as it's a colossal amount of work!

**Comment by dpwspoon** [comment]
https://zapier.com/engineering/continuous-integration-jenkins-docker-github/

**Comment by aluzzardi** [comment]
We are missing the following integration tests (defined in `api.bats`):

```
ocker attach
docker build
docker commit
docker cp
docker create
docker diff
docker events
docker exec
docker export
docker history
docker images
docker import
docker inspect
docker kill
docker load
docker login
docker logout
docker logs
docker port
docker pause
docker pull
docker push
docker rename
docker restart
docker rm
docker rmi
docker run
docker save
docker search
docker start
docker stats
docker stop
docker tag
docker top
docker unpause
docker version
docker wait
```

Help very appreciated as it's a colossal amount of work!

**Comment by chanwit** [comment]
:)

**Comment by chanwit** [comment]
Could we have a proper checklist? So works can be done individually and randomly.

**Comment by aluzzardi** [comment]
Sure, @chanwit, sounds like a good idea!

**Comment by jimmyxian** [comment]
@jfrazelle  @aluzzardi 
I will be working on it.

**Comment by aluzzardi** [comment]
Thanks @jimmyxian 

Do you want to work on all of them or just a few ones? I can check the boxes on the ones you'd like to tackle to mark them as assigned

**Comment by jimmyxian** [comment]
@aluzzardi Yeah, i will work all of them. The following tests are not done, others are already done locally. 
+ diff
+ events
+ wait
+ import (not support in Swarm)
+ login (do not have a good idea)
+ logout (do not have a good idea)

**Comment by aluzzardi** [comment]
I think we have covered everything we have on the API side.

@jimmyxian can we close this?

**Comment by jimmyxian** [comment]
@aluzzardi Yeah..

**Comment by aluzzardi** [comment]
:fireworks: :fireworks: :fireworks:
