### ISSUE TITLE
Support tls in the etcd discovery backend

### ISSUE THREAD

**Issue by crosbymichael** [docker/swarm#496]
**Problem**

Support tls in the etcd discovery backend

**Solution**

All the docker tools supports SSL/TLS, it should be possible to enable TLS to talk to the discovery service. Let's use `etcds://` and use the tlsconfig already provided

**Comment by david-guenault** [comment]
isn't this a duplicate of #404 ?

**Comment by timfallmk** [comment]
:+1:

**Comment by packetcollision** [comment]
#dibs

**Comment by timfallmk** [comment]
Hi @packetcollision, you mind if I take this one? I already fixed it at the party but haven't double checked my work.

**Comment by packetcollision** [comment]
@timfallmk go for it!

**Comment by aluzzardi** [comment]
Duplicate of #404
