### ISSUE TITLE
Integration tests for the file discovery backend

### ISSUE THREAD

**Issue by crosbymichael** [docker/swarm#498]
**Problem**

Integration tests for the file discovery backend

**Solution**

Write integration tests to verify the file discovery backend is working correctly

**Comment by rot26** [comment]
#dibs

**Comment by groob** [comment]
#dibs

**Comment by chanwit** [comment]
@groob any progess about this? If not, would you mind if I take over this one?

**Comment by groob** [comment]
@chanwit go ahead, I ran out of steam.

**Comment by chanwit** [comment]
Thanks @groob ! Review is very welcome.

**Comment by chanwit** [comment]
@abronan @aluzzardi This issue can be closed for now.
