### ISSUE TITLE
Add integration tests to the zookeeper discovery backend

### ISSUE THREAD

**Issue by crosbymichael** [docker/swarm#504]
**Problem**

Add integration tests to the zookeeper discovery backend

**Solution**

Add integration tests to the zookeeper discovery backend

**Comment by chanwit** [comment]
@crosbymichael maybe I could help for this issue.

**Comment by vieux** [comment]
@chanwit go for it :D

**Comment by chanwit** [comment]
@crosbymichael @vieux done. This issue can be now closed :)

**Comment by abronan** [comment]
@chanwit :+1:
