### ISSUE TITLE
Docker run needs to show more status when pulling images

### ISSUE THREAD

**Issue by anderssv** [docker/swarm#508]
Might be a result of me running on DigitalOcean/ams2 . But when I do a: '''docker run -ti ubuntu /bin/bash''' it pulls the image correctly, but shows no progress whatsoever. As this is a slow operation it is quite hard to know if there is a problem or not. Please print progress when doing this. :)

**Comment by bacongobbler** [comment]
dupe of https://github.com/docker/swarm/issues/336

**Comment by abronan** [comment]
@anderssv feel free to comment on the original issue about it :)
