### ISSUE TITLE
No healthy node available in the cluster

### ISSUE THREAD

**Issue by nadgowdas** [docker/swarm#511]
Hi,

I just started using swarm and i am having issue starting a new container.
I created a swarm cluster and joined from 3 docker hosts.

started swarm from image on node1
node1> docker run -d -p 8090:2375 swarm manage token:0754366c8d2b3d09e8fffd300337aa33

joined cluster from 3 different nodes
node1> docker run -d swarm join --addr=x.x.y.1:2375 token://0754366c8d2b3d09e8fffd300337aa33
node2> docker run -d swarm join --addr=x.x.y.2:2375 token://0754366c8d2b3d09e8fffd300337aa33
node3> docker run -d swarm join --addr=x.x.y.3:2375 token://0754366c8d2b3d09e8fffd300337aa33

I can list these nodes with swarm list
node1> #  docker run --rm swarm list token://0754366c8d2b3d09e8fffd300337aa33
x.x.x.1:2375
x.x.x.2:2375
x.x.x.3:2375

But, when i tried to start a new container, i get error that "No healthy node available in the cluster"
node1> # docker -H tcp://<swamip>:8090 run -t -i --name contA ubuntu:14.04 /bin/bash
FATA[0000] Error response from daemon: No healthy node available in the cluster

Is there anything i am missing here?

Also, few questions:
1) I started one container on node1 using docker run command directly. But, when i do swarm ps, i do not see that container 
> docker -H tcp://x.x.x.1:8090 ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
>

I would expect since swarm client monitor/manage local docker deamon, regardless of whether i create container through swarm client or directly, it should still list all container?

**Comment by abronan** [comment]
Hi @nadgowdas,

Prior to running `swarm join` on your Agents, you need to make sure that docker daemons on those agents are available on TCP.

You can launch the docker daemon on those Agents with: `docker -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -d`

(It's actually on the doc but needs an highlight at the top of the node configuration part. Seems to be a common pitfall when first running a swarm cluster)

**Comment by nadgowdas** [comment]
Thanks abronan. 
It work for me now, after starting the docker daemon to listen on TCP port.

**Comment by abronan** [comment]
@nadgowdas Cool! :+1:

**Comment by sinderrellar** [comment]
hello, I met the same question, but I'm sure I add -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -d, so, any other possible???

**Comment by zhanghuanzhong** [comment]
I met the same question too. I added -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -d, but it doesn't work for me.

**Comment by dongluochen** [comment]
@zhanghuanzhong @sinderrellar What's the output from `docker -H swarm_manager:manager_port info`? Can you reach each daemon with `docker -H node:2375 info`?

**Comment by zhanghuanzhong** [comment]
@dongluochen, I disabled the firewalld service on my docker host and the question has gone:)

**Comment by dongluochen** [comment]
@zhanghuanzhong thanks for your update! We can keep this issue closed.

**Comment by gkgt80** [comment]
One of the reason this error come if you are using 
swarm version 1.2.0 , 1.2.1, 1.2.2

**Comment by mrmarcsmith** [comment]
@gkgt80 I am receiving this error on 1.2.2 do you have a temporary work around?

**Comment by dongluochen** [comment]
@gkgt80 @mrmarcsmith From your manager node, can you access docker daemon on your worker nodes, i.e., does `docker -H node:port info` return correct info?

**Comment by gkgt80** [comment]
@mrmarcsmith : No work around 
@dongluochen  : Yes. Here you are running docker command on remote docker

**Comment by Homie20006** [comment]
Got a similar error.
And `docker -H node:port info` prompts the expected output :|

root@master:~$ docker -H node_ip:2375 info
Containers: 23
 Running: 4
 Paused: 0
 Stopped: 19
Images: 82
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 144
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-86-generic
Operating System: Ubuntu 14.04.4 LTS
... and so on

`swarm manage` container logs:
`time="2016-05-24T09:31:59Z" level=debug msg="Failed to validate pending node: Cannot connect to the Docker daemon. Is the docker daemon running on this host?" Addr="node_ip:2375"`

**Comment by mrmarcsmith** [comment]
$ docker-machine ls
NAME          ACTIVE   DRIVER         STATE     URL                         SWARM   DOCKER    ERRORS
MM0003-node   -        digitalocean   Running   tcp://104.236.145.96:2376           v1.11.1   
$ docker -H 104.236.145.96:2376 info
Get http://104.236.145.96:2376/v1.23/info: malformed HTTP response "\x15\x03\x01\x00\x02\x02".
* Are you trying to connect to a TLS-enabled daemon without TLS?
$ sudo !!
sudo docker -H 104.236.145.96:2376 info
[sudo] password for username: 
Get http://104.236.145.96:2376/v1.23/info: malformed HTTP response "\x15\x03\x01\x00\x02\x02".
* Are you trying to connect to a TLS-enabled daemon without TLS?

@dongluochen it's a TLS Problem!... now what? i used docker-machine to create the node with this code

docker-machine create \
--driver digitalocean \
--digitalocean-access-token <Nice try dirty gypsies you won't get my keys today> \
--digitalocean-region sfo1 \
--digitalocean-size=512mb \
--digitalocean-ipv6 \
--digitalocean-private-networking \
--digitalocean-backups=false \
--swarm \
--swarm-discovery token://<Nor will you get my discovery token!> \
MM0003-node

**Comment by Rockyjee** [comment]
I was getting the same issue until I redeployed the swarm and increased number of agents to "2" and it worked for me !!!
