### ISSUE TITLE
Failover in swarm/machine

### ISSUE THREAD

**Issue by robwithhair** [docker/swarm#523]
Hi there,

I have read multiple articles mentioning failover in docker swarm but I can't find anything in the docs.  Is this feature still in development?  If not can you point me in the right direction to where to find out about it?  

Sorry to put this in the issue queue as it's kind of a question but also I suppose a documentation/communication issue.

**Comment by janeczku** [comment]
Haha, i just wondered about this too and Google pointed me here.

**Comment by aluzzardi** [comment]
Please see #599 and #598
