### ISSUE TITLE
not able to install swarm from source

### ISSUE THREAD

**Issue by nadgowdas** [docker/swarm#524]
Hi,

I am trying to install swarm code from source, and i am getting bunch of import errors:
> echo $GOPATH
/home/shripad/repository/gocode/

>  pwd
/home/shripad/repository/swarm

> godep go install .
manage.go:12:2: cannot find package "github.com/docker/swarm/api" in any of:
        /usr/local/go/src/github.com/docker/swarm/api (from $GOROOT)
        /home/shripad/repository/swarm/Godeps/_workspace/src/github.com/docker/swarm/api (from $GOPATH)
        /home/shripad/repository/gocode/src/github.com/docker/swarm/api
manage.go:13:2: cannot find package "github.com/docker/swarm/cluster" in any of:
        /usr/local/go/src/github.com/docker/swarm/cluster (from $GOROOT)
        /home/shripad/repository/swarm/Godeps/_workspace/src/github.com/docker/swarm/cluster (from $GOPATH)
        /home/shripad/repository/gocode/src/github.com/docker/swarm/cluster
....

I see api, cluster packages are available in the same folder, so I changed the "manage.go" import from
"github.com/docker/swarm/api" to
"api"

and i could get rid of import error for "api".

Is there something i missed in my environment setting? or i need to change the import for all?

**Comment by pratapchand** [comment]
The instruction in the readme file is incomplete. Before the git clone step for swarm, you need to change directory to $GOPATH/arc/github.com/docker.

This is similar to the issue #520

**Comment by nadgowdas** [comment]
Thanks. After changing the swarm clone location, i am able to build it.
It would also help, if we could change the documentation.

**Comment by pratapchand** [comment]
There is a PR that is waiting to be reviewed. 
https://github.com/docker/swarm/pull/521

**Comment by vieux** [comment]
#521 was merged.
