### ISSUE TITLE
How to build Swarm

### ISSUE THREAD

**Issue by TrumanLing** [docker/swarm#527]
I tried to use ```go build``` and got swarm executable binary file, but my modification can't be compiled into the binary file.

So I tried to modify ```Dockerfile``` and make a new build script file, which are made by referring Docker Machine, but size of output binary file is different, and I am worrying that.

How do you compile swarm, very much hope to get response from you?

**Comment by abronan** [comment]
Hi @TrumanLing,

What kind of modification have you made? `go build` seems enough if you got the binary in the first place but if you added a package related to the changes you made, `go get` the package first and then `godep save`/`godep go build`. If you can provide us with more details about the nature of those changes, we can probably help troubleshoot the issue and find out why you can't build the binary :)

**Comment by TrumanLing** [comment]
@abronan thanks for your response!

My case is very simple, I just added some log code in file discovery/token/token.go to check its implementation flow. But there is no any compilation with this file's modification, moreover the executable binary file ```swarm``` I got is downloaded from somewhere, and it's version is 0.1.0, however, I cloned the latest source code, it should be 0.2.0 at least.

So I do some modification with Dockerfile by referring ```docker machine```'s Dockerfile and create a ```build``` script, they look like as following:
Dockerfile
'''console```
FROM golang:1.3

ENV http_proxy http://xxx:yyy@zzz.aaa.bbb:111
ENV https_proxy https://xxx:yyy@zzz.aaa.bbb:111
RUN apt-get update && apt-get install -y --no-install-recommends openssh-client

# TODO: Vendor these `go get` commands using Godep.
RUN go get github.com/mitchellh/gox
RUN go get github.com/aktau/github-release
ENV GIT_SSL_NO_VERIFY 1
RUN go get github.com/tools/godep
RUN go get code.google.com/p/go.tools/cmd/cover

#COPY . /go/src/github.com/docker/swarm

ENV GOPATH /go/src/github.com/docker/swarm/Godeps/_workspace:$GOPATH
WORKDIR /go/src/github.com/docker/swarm
ADD . /go/src/github.com/docker/swarm
RUN CGO_ENABLED=0 go install -v -a -tags netgo -ldflags "-w -X github.com/docker/swarm/version.GITCOMMIT `git rev-parse --short HEAD`"

ENV SWARM_HOST :2375
EXPOSE 2375

VOLUME $HOME/.swarm

#ENTRYPOINT ["swarm"]
CMD ["--help"]
```
build script:
```console```
#!/bin/bash
set -e
docker build -t docker-swarm .
rm -f docker-swarm*
exec docker run --rm -v `pwd`:/go/src/github.com/docker/swarm docker-swarm gox  -output="swarm" -ldflags="-w -X github.com/docker/swarm/version.GITCOMMIT `git rev-parse --short HEAD`"
```

**Comment by aluzzardi** [comment]
All you need to do is:

```
go get github.com/tools/godep
godep go build
```
