### ISSUE TITLE
Swarm state monitor

### ISSUE THREAD

**Issue by Fangfenghua** [docker/swarm#529]
Did swarm has any plan to implement function monitor swarm status?

**Comment by jimmyxian** [comment]
@Fangfenghua You can see following issues, maybe help you:
https://github.com/docker/swarm/issues/507
https://github.com/docker/swarm/issues/377

**Comment by aluzzardi** [comment]
Yes - See our roadmap https://github.com/docker/swarm/wiki/0.3.0-Milestone-Project-Page

And issue #598 for the details.
