### ISSUE TITLE
The idea of the implementation of 'docker commit' in swarm

### ISSUE THREAD

**Issue by jimmyxian** [docker/swarm#533]
I want to implement the 'docker commit' api in swarm, the following steps is my idea to do this:
(1) find the node that CONTAINER is running on
(2) send commit request to this node

is it OK?

**Comment by vieux** [comment]
@jimmyxian yes it seems good.

**Comment by jimmyxian** [comment]
@vieux OK. I will do it

**Comment by vieux** [comment]
Closed by #538
