### ISSUE TITLE
Enable cpu filter

### ISSUE THREAD

**Issue by Fangfenghua** [docker/swarm#535]
In  NFV case, some application need high perfermance, the end-user want the application  exclusive the cpu core.So we want add a cpu filter.The main idea is:
1 if the host has run contariner,that not specify cpuset,then the node  will past;
2 if all container had spectfiy cpuset,but didn't has enough cpuset the node  will pass;

**Comment by vieux** [comment]
I don't get it, what's the difference with `-c 1` ? to have one cpu

**Comment by Fangfenghua** [comment]
That's mean let -c 1 is exclusive!Other container can't use it!The container  you assign the core can use it 100%!

**Comment by Fangfenghua** [comment]
@vieux   Use  -c 1,  We can let container bind to cpu-set 1, but  can't restriction other container use cpu-set 1 in the same node . In high-perfermance use case, We want the cpu-set can just use by one container in a node,it's exclusive. 
     If we run container A  in node-1 use cpu-set 1-2，We didn't wish any container didn't specify cpu-set or specify cpu-set 1-2 can run in node-1,Only container  specify cpu-set 3-4 can't run in node A.The cpu-set 1-2 can just use by container A exclusive.

**Comment by vieux** [comment]
@aluzzardi @abronan any comment on this ?

**Comment by affo** [comment]
@vieux I think this is not a bad idea even out of the field of high performances.  
If we think of swarm as a manager for a cluster that offers a IaaS, we could have users that run _flavor-based_ (as for VMs in OpenStack) docker containers.  
Say we have small (2 cores, 2GB of RAM), medium (4 cores, 4GB) and large (8 core, 8GB); a user should be able to run, for instance, a medium-flavored redis container.  
The system admin -- for SLA purposes -- should guarantee that container to have the desired properties and so he/she should prevent other containers to use the first's resources (leaving overcommitting stuff).

I think it could be a nice idea.

Correct me if I am wrong, but, is the number_of_cores/cpu_shares conversion a good idea?  
Why not converting directly the number of cores specified in `-c` into a defined cpuset?  
Wouldn't it be much more sensed?

**Comment by abronan** [comment]
Closing in favor of #1702 so that this enhancement can be considered.

I think this is a good idea to have such knowledge included into the scheduler. Thanks a lot for opening @Fangfenghua and also @affo for the valuable feedback.
