### ISSUE TITLE
Use of Health Filter

### ISSUE THREAD

**Issue by snrism** [docker/swarm#544]
I am trying to understand the need for health filter in scheduler. The doc mentions that the health filter "will prevent scheduling containers on unhealthy nodes". I believe this is the expected default behavior even without the filter right? If yes, then why have the health filter option? If no, some clarification on this will help..thanks

**Comment by vieux** [comment]
Right now, the nodes are never removed of the cluster, they are marked as unhealthy.

As soon as we properly remove nodes from the cluster, we won't need the health filter anymore.

**Comment by aluzzardi** [comment]
@snrism: Yes, this is the expected behavior. The filter is the implementation of that behavior. Filters are the way we add filtering to the scheduler, not just options.

**Comment by snrism** [comment]
Got it..thanks
