### ISSUE TITLE
Not able to run containers in the cluster. 

### ISSUE THREAD

**Issue by ashish235** [docker/swarm#557]
I started with swarm today using a docker image but I 'm unable to run any containers from the cluster. 

The swarm version on my machine is:
[root@localhost ~]# docker version
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): fc0329b/1.5.0
OS/Arch (client): linux/amd64
Server version: swarm/0.1.0
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 2acbea1
OS/Arch (server): linux/amd64

The docker version is:
[root@localhost ~]# docker version
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): fc0329b/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): fc0329b/1.5.0
OS/Arch (server): linux/amd64

I 've 2 nodes in the cluster. 
[root@localhost ~]#  docker run --rm swarm list token://786c17c88ab9840d389213e9d549fc57
172.16.131.252:2375
172.16.131.253:2375

My swarm manager is running on port 6000 on of these 2 nodes. 
b4adcddbf57d        swarm:latest        "/swarm manage token   16 hours ago        Up 16 hours         0.0.0.0:6000->2375/tcp   romantic_sinoussi

Now when I try to run a container from the swarm CLI (by exporting dockerhost to 6000 port), nothing happens. 
docker run -d --name web1 -m 1g nginx

Even from docker CLI if I try to run a container nothing happens. 
docker -H tcp://172.16.131.252:6000 run -d --name web1 -m 1g nginx

I have waited for more than an hour, after that I had to press ctrl+c to exit. 

Kindly suggest if I 'm missing something.

**Comment by abronan** [comment]
Hi @ashish235,

Have you tried using `docker -H tcp://0.0.0.0:6000 info` instead?

**Comment by ashish235** [comment]
I think the issue was because swarm was trying to pull the images from github repo hence it was taking a longer time even though I had those images on all my docker nodes. However when I tried to pull an image from a local repo, it worked. Not sure but maybe this is a possible reason. 

@abronan, yes my info command was working.

**Comment by abronan** [comment]
@ashish235 Do you still encounter issues running commands on Swarm? This is probably related to the registry you were trying to pull an image from as the `docker run` on swarm will not show you the progress of `docker pull`. Hence it appears to be blocked while it can be due to a very slow download speed instead (even if an hour seems to tell that it couldn't contact the registry somehow).

**Comment by chanwit** [comment]
@ashish235, like @abronan mentioned, `docker run` via Swarm will not show any progress.

With the current version of Swarm you better do:
`docker -H tcp://172.16.131.252:6000 pull nginx` first before `docker run`.

**Comment by ashish235** [comment]
@abronan and @chanwit thanks for the reply. Yes, it was the pull which was taking ages actually and since there was no progress shown, I was clueless what's happening. So to confirm this I created a local private repository and tried to the run the image from there it started within seconds. 
I think a progress bar would be helpful here.

**Comment by chanwit** [comment]
@ashish235 It's been reported in #336 since 0.1.0 :) and @vieux has been finding a proper way to accomplish it.

**Comment by abronan** [comment]
@ashish235 Yes it would be really useful to have at least a progress bar and help diagnose network issues during the pull operation. But you can still fire the `pull` prior to `run` for now and it will show the actual progress of downloading the image. Feel free to comment on the issue reported by @chanwit :) I'm closing this one.
