### ISSUE TITLE
Make heartbeat type as unsigned int

### ISSUE THREAD

**Issue by snrism** [docker/swarm#558]
Current heartbeat type is integer and can accept negative values or single digit interval time. This can lead to frequent registration with the manager and can be flaky. To improve this, I believe we can make two changes:

- Make heartbeat type as unsigned
- Define a minimal heartbeat interval (say 10sec). However this can be optional.

Any thoughts if this will be useful?

Thanks,
Sriram

**Comment by mgoelzer** [comment]
Hi @snrism, I agree with you on making it an unsigned int.  It might also be a good idea to require it to be strictly >0, because currently 0 is allowed and I'm not sure if that's a bug or a real use case.

**Comment by snrism** [comment]
@mgoelzer Indeed. I will open a pull request and see what folks think about it.

**Comment by vieux** [comment]
@snrism I agree with @mgoelzer unsigned + > 0

**Comment by snrism** [comment]
@vieux: thanks, I am working on it, will open a PR soon...
