### ISSUE TITLE
Docker swarm not connecting with "unsupported version"

### ISSUE THREAD

**Issue by qkslvrwolf** [docker/swarm#562]
I have two machines, .137 and .138.  Both are ubuntu 14.04

Both have docker 1.5.0 Build a8a31ef

I used docker pull swarm, like the docs said.

On 137, I ran 
docker run --rm swarm:0.2.0-rc1 create
which returned: af88de735316ff60e61db70e5d8c5e0f

Then on 137, I ran docker run -d -p 2375:2375 swarm:0.2.0-rc1 manage token://af88de735316ff60e61db70e5d8c5e0f

And on 138 I ran docker run -d swarm:0.2.0-rc1 join --addr=xxx.xxx.xxx.137:2375 token://af88de735316ff60e61db70e5d8c5e0f

docker logs tail on the first returns 
time="2015-04-02T19:10:57Z" level=info msg="HTTP request received" method=GET uri="/v1.15/info" 
time="2015-04-02T19:10:57Z" level=error msg="node xxx.xxx.xxx.137:2375 is running an unsupported version of Docker Engine. Please upgrade."

And I never see any messages from 138.

I have DOCKER_OPTS="-H tcp://0.0.0.0:2375" in /etc/default/docker (first on neither, then on one, then on both).

I can telnet to 2375 from 138 and from 137.
Not sure what other troubleshooting steps to take here, but it's not working as advertised.

docker info on 137 shows:  
docker -H tcp://198.18.65.137:2375 info
Containers: 0
Nodes: 0

docker run --rm swarm list token://af88de735316ff60e61db70e5d8c5e0f
xxx.xxx.xxx.137:2375

**Comment by vieux** [comment]
the --addr in join should be docker addr, not the manager and each machine is supposed to do it's own join:

Assuming docker listen on *2375*:
On **137** I ran docker run -d swarm:0.2.0-rc1 join --addr=xxx.xxx.xxx.**137**:2375 token://af88de735316ff60e61db70e5d8c5e0f

And on **138** I ran docker run -d swarm:0.2.0-rc1 join --addr=xxx.xxx.xxx.**138**:2375 token://af88de735316ff60e61db70e5d8c5e0f

Then you can start the manager with : `docker run -d -p 9999:2375 swarm:0.2.0-rc1 manage token://af88de735316ff60e61db70e5d8c5e0f` on any machine 

then `export DOCKER_HOST=x.x.x.x:9999` and you should be good

**Comment by qkslvrwolf** [comment]
That did it, thank you.
