### ISSUE TITLE
Docker Swarm:  Race condition in etcd discovery

### ISSUE THREAD

**Issue by mgoelzer** [docker/swarm#564]
In the etcd discovery provider, when you use a short heartbeat interval, a race occurs between the TTL and the heartbeat update causing nodes to briefly disappear from the cluster (due to etcd key expiration) and then reappear.

How to reproduce:

1.  Start swarm join with a short heartbeat interval, e.g., 1 second:

```
swarm join --addr=10.0.1.101:2375 --hb 1 etcd://10.0.1.101:4001/myswarm
```

2.  Note that this will cause ttl to be 1 because of this line:  ```s.ttl = uint64(heartbeat * 3 / 2)``` (in discovery/etcd.go)

3.  Now start an etcdctl watcher:

```etcdctl watch /myswarm --recursive --forever```

About 1/1000 of the time you'll see a blank line because ttl won the race and node disappeared.

Suggested fix:  guarantee TTL will always be substantially longer than heartbeat interval, e.g., s.ttl = max(uint64(heartbeat * 3 / 2), 30).  I can open a PR if maintainers think this is appropriate.

**Comment by abronan** [comment]
@mgoelzer Good catch!

Of course feel free to submit a PR, we'll be there to test and review :)

**Comment by aluzzardi** [comment]
Fixed by https://github.com/docker/swarm/pull/567
