### ISSUE TITLE
Help incorrectly shows ability to specify multiple consul IPs

### ISSUE THREAD

**Issue by MrMMorris** [docker/swarm#576]
The help message for Swarm shows that you can specify multiple consul IPs (which would be nice): https://github.com/docker/swarm/blob/master/help.go#L21

However, it doesn't actually (yet): 

`swarm version 0.2.0 (HEAD)`

```
$ /usr/local/bin/swarm manage -H tcp://0.0.0.0:2375 --strategy spread consul://10.0.0.5,10.0.1.5/swarm
INFO[0000] Listening for HTTP                            addr=0.0.0.0:2375 proto=tcp
FATA[0000] Put http://10.0.0.5,10.0.1.5/v1/kv/swarm/: dial tcp: lookup 10.0.0.5,10.0.1.5: no such host
```

Trying the command with each IP on it's own works.

Not sure if it was put there in anticipation of the feature, but it's a bit confusing that it's there but doesn't work.

I saw this PR: https://github.com/docker/swarm/pull/386. Not sure if it is being implemented from someone else.

**Comment by abronan** [comment]
@MrMMorris Yes this was mostly the doc being copied from etcd I guess but consul is not taking multiple IPs when initializing the client. An example of consul taking multiple IPs is in #583.

**Comment by aluzzardi** [comment]
ping @abronan

**Comment by abronan** [comment]
Help is now correct for consul and shows a single IP :)
