### ISSUE TITLE
pq: permission denied for relation clusters

### ISSUE THREAD

**Issue by lyndaoleary** [docker/swarm#577]
Hi, I am getting the following error when attempting to create a discovery token.
```
$ docker run swarm create
pq: permission denied for relation clusters
```
I've seen that this issue was raised before (#469), but it appears to be closed.

**Comment by tombee** [comment]
Same issue here.

**Comment by vanzhiganov** [comment]
I have this error message too in CentOS 6.6 x86_64

**Comment by vanzhiganov** [comment]
Try execute command with `sudo`

**Comment by vanzhiganov** [comment]
Try to execute command with `sudo`

**Comment by tombee** [comment]
Looks like it's working again -- no need for `sudo`.

```
docker run swarm create
5f4b4b2bcf52bbea13b7553f26232da3
```

**Comment by mgoelzer** [comment]
I am getting this error intermittently as well.  By the way, I don't think it's related to sudo or lack thereof:

````
mike@docker1:~$ sudo docker run --rm swarm create
pq: permission denied for relation clusters

mike@docker1:~$ docker run --rm swarm create
pq: permission denied for relation clusters
````

**Comment by vieux** [comment]
Hi guys, it's fixed (again) sorry about that.
It was a server side issue.
