### ISSUE TITLE
Couldn't get swarm manager connect with swarm agents

### ISSUE THREAD

**Issue by phagunbaya** [docker/swarm#578]
I'm running 2 nodes (centOS 7):

1. dev-swarm-01 (swarm manager)
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): fc0329b/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): fc0329b/1.5.0
OS/Arch (server): linux/amd64

2. dev-agent-01 (swarm agent)
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): fc0329b/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): fc0329b/1.5.0
OS/Arch (server): linux/amd64

Swarm version : latest and even tried with 0.1.0

When I add agent to cluster and start the manager the debug logs says :
INFO[0000] Listening for HTTP                            addr=:2375 proto=tcp
ERRO[0100] Get http://10.240.138.8:2375/v1.15/info: dial tcp 10.240.138.8:2375: connection refused 

The API points to v1.15 ? Probably it's version mis-match. Need help !

**Comment by abronan** [comment]
Hi @phagunbaya,

Did you run `docker -H tcp://0.0.0.0:2375 -d` on your agents as the documentation says? Just to make sure that the docker daemons running on agents are reachable over tcp.

**Comment by phagunbaya** [comment]
@abronan : Thanks for the quick response. It's resolved now, there was some firewall issue. I just got confused with the API version in the log.
