### ISSUE TITLE
Idea of "docker load" api implementation

### ISSUE THREAD

**Issue by jimmyxian** [docker/swarm#585]
I want to implement the 'docker load' api in swarm, the following steps is my idea to do this:

* (1) swarm cache the load-file(save in a temp file)\[api/api.go\]
* (2) call cluster.Load(temp_file_path)
	* Need to add a "func Load(file_path string)" interface in cluster[cluster/cluster.go]
* (3) In swarm cluster,  implement Load interface, send load request to every node[cluster/swarm/cluster.go]
    * call node.load(temp_file_path)
* (4) In node.load function, call n.client.LoadImage(temp_file_path)[cluster/swarm/node.go]
    * Need to add and implement LoadImage interface in dockerclient
	
Well, first i will submit a PR(add and implement LoadImage interface) in dockerclient, then implement "docker load" api in swarm.

Is my idea right ?

**Comment by vieux** [comment]
I think so, as we decided that `docker pull` pulls on every node, I think it's a good idea to have `docker load` load on every machine.

**Comment by jimmyxian** [comment]
@vieux OK. I will do it

**Comment by aluzzardi** [comment]
Fixed by @jimmyxian
