### ISSUE TITLE
Regexp filtering limitation

### ISSUE THREAD

**Issue by frntn** [docker/swarm#589]
# What I do

I have 5 docker server in the pool of my swarm manager.
Two servers are started with the following label : 
  * server1 : ̀`type=app`
  * server2 : `type=db`
 
I then want to start a container on any nodes with types `app` **or** `db` : 

```bash
docker run -d -e constraint:type==/app\|db/ nginx
```

# What I get

I get an the following error on client side : 
```bash
FATA[0000] Error response from daemon: Value '/app|db/' is invalid
```

And this one on proxy side : 
```bash
time="2015-04-08T11:15:38+02:00" level=info msg="HTTP request received" method=POST uri="/v1.16/containers/create" 
time="2015-04-08T11:15:38+02:00" level=error msg="HTTP error: Value '/app|db/' is invalid" status=500 
```

# What I expected

The [scheduler README](https://github.com/docker/swarm/blob/master/scheduler/filter/README.md) says [Go regexp are supported](https://github.com/docker/swarm/blame/master/scheduler/filter/README.md#L174), so I was expecting the container to be created on any of these nodes.

I can see this is because of the constraint value [validation here](https://github.com/docker/swarm/blob/cdc9c7a47b0267dac77a170fed72a5bd26a752a4/scheduler/filter/expr.go#L55)

Swarm should not limit us when building complex filtering strategies, **the full golang regexp behaviour should be available**

**Comment by aluzzardi** [comment]
ping @chanwit

**Comment by chanwit** [comment]
Ack. I'm fixing it.
