### ISSUE TITLE
Documentation home page should point at GitHub, IRC, etc

### ISSUE THREAD

**Issue by bfirsh** [docker/swarm#590]
http://docs.docker.com/swarm/ is currently the landing page for Swarm. A few cases this page doesn't cater for:

- Somebody wants some help using Swarm, in which case we should point them at the mailing list or IRC channel
- Somebody wants to suggest features, report bugs or contribute code, in which case we should point them at GitHub

I think we should have links off to those things somewhere. @aluzzardi @vieux @fredlf - WDYT?

**Comment by garagatyi** [comment]
For IRC nice button can be provided (replace image)
[![Visit Swarm IRC channel](https://kiwiirc.com/buttons/irc.freenode.net/kiwiirc.png)](https://kiwiirc.com/client/irc.freenode.net/#swarm)

**Comment by fredlf** [comment]
Closed by #604
