### ISSUE TITLE
Golint panic in travis build

### ISSUE THREAD

**Issue by abronan** [docker/swarm#591]
Trying to build #583 again and golint panics. (golint checks are passing locally using an older version of the tool)

See: https://travis-ci.org/docker/swarm/builds/57624740

**Comment by snrism** [comment]
Yup, same issue in https://github.com/docker/swarm/pull/587 and https://github.com/docker/swarm/pull/588

**Comment by abronan** [comment]
This should be due to the latest version of golint (there was breaking changes 12 hours ago) as we do a `go get` and put the package in the `Godeps/_workspace` folder in the travis environment.

cc @aluzzardi @vieux

**Comment by abronan** [comment]
We should probably manage **golint** with Godeps and update manually when we need to.

Thoughts?

**Comment by vieux** [comment]
Fixed by https://github.com/golang/lint/commit/3b3fdebcde972819016da7b8377e79651998f5fc :D
