### ISSUE TITLE
late-bound constraints

### ISSUE THREAD

**Issue by wallnerryan** [docker/swarm#592]
Reading the docs, https://docs.docker.com/swarm/scheduler/filter/ constraints are added when the docker daemon is started.

Is there a way to add constraints after the engine in started? E.g. today I can do this by starting a container with a name that would be my constraint and then use affinity with the container name equal-to that name.

A use case for this may be if a a service is deployed to a set of nodes, you could add a constraint to those docker engines running such a service possibly via an UPDATE or or POST method the engine API.

**Comment by abronan** [comment]
Hi @wallnerryan. No, you need to restart the engine in that case.

I you need a service to run on a specified set of nodes, why not using node constraints? (you don't need late-binding in that case)

**Comment by wallnerryan** [comment]
@abronan I guess I could.. the thing is if I deploy a service after my initial docker engine is started up that say "gives a groups of nodes a specific roll in a cluster" as in node1-4 have a specific configuration to them, I would need something like a service discovery tool to let me know that those 4 nodes are now running such a service and are used for that role now, so reference them with node[1234], which in an orchestration systems could be a fair assumption.

Instead, it could be simpler if I give those nodes a unique constraint name like "foo-config" after I deploy my service foo successfully, I could then just use one constraint instead of finding the nodes. This is why container affinity kind-of works but if that containers used to deploy the service are removed once the service is deployed or if that container doesn't have a unique name it can be harder to accomplish. It would be nice to be able to assign/un-assign a role to an engine after it is started.

**Comment by abronan** [comment]
@wallnerryan I understand the use-case but unfortunately it belongs to the docker engine to support late-binding of labels (because we use the docker API and `docker info` to retrieve those labels). Feel free to open an issue on docker :) I'll close the issue for now but we might reconsider this in the future if the feature hits the engine.
