### ISSUE TITLE
Usecase for State.store in swarm

### ISSUE THREAD

**Issue by smothiki** [docker/swarm#597]
I'm trying to implement handling  node fail-overs in swarm and figured out that A state of a container is stored in ```.swarm``` file as a key value pair {container : container state}. But swarm is not storing the state of a Node . it would be helpful to store a key value map of {Node : containerList} along with the {container : container state} and keep updating containerList . This helps for a faster lookup of a Node snapshot in case of a node failure and rerun the scheduling logic for the containers in the failed node.

Also any thoughts on how to extend store interface to a distributed store ? (etcd,consul)

**Comment by vieux** [comment]
@abronan @aluzzardi

**Comment by aluzzardi** [comment]
Hey @smothiki - we are working on it (specifically @abronan)

See #507
