### ISSUE TITLE
Multi-tenancy: Leader Election

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#598]
Currently, only a single Swarm manager is allowed per cluster. This means that if it goes down, it becomes temporarily impossible to schedule new containers on the cluster. Existing containers will continue to operate as usual.

In order to get multi-tenancy, multiple masters should be allowed per cluster. Only one master at a time will be operational, the others will be in stand-by and perform a leader-election once the primary becomes unavailable.

Ideally, the user could send API requests to any of the managers - if the request lands on a manager that is not currently the master, it will forward it to the right instance.

Multi-tenancy depends on #507 for both shared state and leader election.

 See #377

**Comment by mgoelzer** [comment]
From the Raft paper (section 8):

"Clients of Raft send all of their requests to the leader. When a client first starts up, it connects to a randomly- chosen server. If the client’s first choice is not the leader, that server will reject the client’s request and supply in- formation about the most recent leader it has heard from."

I think you should consider following this behavior exactly instead of allowing non-master nodes to forward requests to master.  Sticking closely to the paper could reduce the risk of subtle concurrency bugs.

Are you planning to use go-raft or roll your own?

**Comment by mgoelzer** [comment]
Btw, I think this is a great feature @aluzzardi.  Happy to help with coding and/or testing.

**Comment by aluzzardi** [comment]
@mgoelzer Thanks.

I think that, since we will need a distributed data store to share state between nodes, we could on rely that to perform leader election.

Similar to discovery, we'd support multiple stores (etcd, consul, zookeeper, ...).

That way, we don't have to implement raft (or use go-raft): we only rely on basic election mechanism of the store (locking and such).

As for
>  that server will reject the client’s request and supply in- formation about the most recent leader it has heard from.

This is a bit hard: The docker CLI expects a response from the server, not "information about the most recent leader". We could maybe do that using `302`s, but some operations won't work with that (`POST` for instance).

Thoughts?

**Comment by mgoelzer** [comment]
Hi @aluzzardi,

I think you are saying that first we would build a distributed key value store into swarm, and then we would rely on that store to do leader election among swarm managers, right?  But the problem I see is, how do the nodes in the distributed key value store know which one of them has the authoritative copy of the store?  They need to agree on a leader, which means we'd need to implement Raft (or Paxos... ugh).  So, aren't we stuck implementing Raft no matter what?

Please tell me if I'm totally missing the point here.  I feel like I might be.

Mike

**Comment by aluzzardi** [comment]
@mgoelzer It has been implemented in #819 #835

**Comment by aluzzardi** [comment]
ping @Fangfenghua @robwithhair @janeczku @jmmills

**Comment by aluzzardi** [comment]
Regarding:

>  that server will reject the client’s request and supply in- formation about the most recent leader it has heard from.

What I did is that *followers* (as in, *slaves* or *non-followers*) know where the leader is located and will automatically forward requests to it.

**Comment by arun-gupta** [comment]
Docs at https://docs.docker.com/swarm/install-w-machine/ say "A single system in your network is known as your Docker Swarm manager." How can multiple Docker Swarm managers be configured?

**Comment by sumitkgaur** [comment]
I believe this feature so far is just master failover (master HA) and not reached till multi-tenancy. Correct me if I am wrong ?
