### ISSUE TITLE
Container Rebalancing

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#599]
In case of node failure, containers should be rescheduled automatically by swarm.

Rebalancing means re-creating the container on another healthy node that fits the original constraints, affinities and requirements of such container.

* Only select containers should be re-scheduled. This strictly includes stateless containers with the go-ahead of the operator
  * Containers with volumes or any other explicit state should not be rescheduled
  * Users should be able to instruct swarm when creating a container whether it can be rescheduled or nor (`-e reschedule:[always,never]`?)
* Handle node resurrection
  * What happens when a failed node comes back to life? If the node has containers that have been rescheduled, we will end up with duplicates. Think of a stateless service that sends daily reports by e-mail: those messages will end up being sent twice. Ideas:
    * Swarm should kill duplicates (keep the last scheduled version)
    * Swarm should rewrite the *restart policy* of the container to `never` and start them manually (based on the restart policy). This way, duplicates would never be automatically started before being destroyed.
* Container IDs
  * Re-scheduling containers means they will change ID. In order to have a consistent ID exposed to the user, we need Virtual IDs. See #600

**Comment by abronan** [comment]
Just a few thoughts:

> Containers with volumes or any other explicit state should not be rescheduled

What if the container uses a distributed block storage (Ceph, GlusterFS, etc.), should it be excluded from rebalancing or could we find a way to rebalance on a host with a mount-point to the same distributed volume?

> Swarm should kill duplicates (keep the last scheduled version)

Should we keep the latest version or the old one? What if the original scheduling of a container was using constraints (using a machine with an ssd storage) but we end up rebalancing on a node that do not have that kind of storage. It makes more sense to keep the older version once the host is back. In the case of a network partition, you would think that the host failed while it is indeed still alive, thus you can't rely on rewriting the restart policy.

**Comment by cultureulterior** [comment]
Speaking as someone investigating swarm, I don't see virtual container IDs necessary for this feature to be useful for me.

**Comment by abronan** [comment]
@cultureulterior It is not **necessary** for sure, but it is way more convenient in a huge cluster. It is easier to reason about your system with a single ID for a container no matter how many failures occurs in the system and how many times you container moves from a host to another.

**Comment by monokal** [comment]
I guess what you're asking for is mainly the functionality already implemented in Google's Kubernetes (Replication Controllers rescheduling Pods when a host dies), perhaps we can take some design decisions from there, or decide how far we want to abstract Swarm before just supporting Kubernetes?

**Comment by aluzzardi** [comment]
@cultureulterior So, virtual container IDs are an internal thing that won't be directly exposed to the user.

Regarding what to do with duplicates (kill first, kill last, do nothing), it should be user configurable through a reconciliation policy.

**Comment by shykes** [comment]
@aluzzardi you say here that "virtual ids won't be directly exposed to the user", but in #600 you say they will. Could you clarify?
Note, my preference is to expose them to the user and make the *physical* ids an advanced field.

**Comment by aluzzardi** [comment]
@shykes Short answer, will elaborate more:

They are exposed to the user as labels (`com.docker.swarm.id`).
One can manipulate a container using either its physical ID or virtual ID.
With docker/docker#12931 (or docker/docker#10255), the virtual ID could show up in `docker ps`.

However, when you do things such as `docker create` the phyID is returned rather than the virtual ID.

This is because:

- Feedback. I can gather the different pieces here for reference, but the overall feedback I got in GH was against that level of indirection

- Phy IDs are already globally unique

- Challenging UX. The phy ID leaks everywhere in Docker. We would have to catch it and rewrite it in many different places, if it's even possible. For instance, the container hostname is the physical short ID - it's very surprising to manipulate a virtual ID, attach to a container and see a random hostname out of nowhere.

- Not all containers have a Virtual ID - only those created through Swarm. We initially had a lot of code around to handle "backward" compatibility, but in the end decided against it. I think it's totally fine to let users manage their cluster the way they see fit - create stuff through swarm or create directly on the machine. This concept allows swarm and our users to make a clear distinction between the two.

**Comment by schmunk42** [comment]
Any news about this feature?
Or is there a 3rd party rescheduling implementation which uses native docker tools (swarm & compose)?

**Comment by bitgandtter** [comment]
This suppose to only re-balance containers that fails since the cluster node fails? or also will re-balance or re-create those containers that stop for some reason? As explained in issue https://github.com/docker/compose/issues/2435 a feature on compose or swarm that keeps track of the running containers and keep the expected amount of containers for a service running will be really helpful for disaster situations.

**Comment by aluzzardi** [comment]
A proposal has been created for this feature: #1488

**Comment by snoopy86** [comment]
What if you have one node on one location and one on the other and then network fails between them? Would node on the other location also run the container as it would not see the other running container?
