### ISSUE TITLE
Docker API Parity

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#602]
Umbrella issue for missing API endpoints.

* #585: `docker load`
* #455: `docker build`
* `docker save`

Also, in order for private images to work, we need auth support (#374).

**Comment by jimmyxian** [comment]
@aluzzardi Also, "docker import " is not implement
I will focus on these APIs'implementation.

**Comment by vieux** [comment]
@jimmyxian thanks can you start by adding a PR to update api/README.md to say it's not implemented ? Thanks

**Comment by vieux** [comment]
@jimmyxian i spoke too fast :D

**Comment by vieux** [comment]
@jimmyxian can you please take a look at `docker save` as you did load, it should be quite similar ?

**Comment by jimmyxian** [comment]
@vieux OK, i will be working on it. :)
