### ISSUE TITLE
Cannot create a swarm

### ISSUE THREAD

**Issue by YanXiaoping** [docker/swarm#607]
Hi,

[root@centos-minion ~]# docker run --rm swarm create
time="2015-04-09T08:43:28Z" level=fatal msg="Post https://discovery-stage.hub.docker.com/v1/clusters: dial tcp 162.242.195.83:443: i/o timeout"

Any idea what could be the problem?

**Comment by jimmyxian** [comment]
Maybe you can't connect the Docker Hub token discovery service. You can try other Discovery backend, such as etcd,zookeeper or local file. 
http://docs.docker.com/swarm/discovery/

**Comment by aluzzardi** [comment]
ping @vieux ?

**Comment by pireslaert** [comment]
I'm having a similar issue:
docker run --rm swarm create
time="2015-04-16T00:23:21Z" level=fatal msg="Post https://discovery-stage.hub.docker.com/v1/clusters: dial tcp: lookup discovery-stage.hub.docker.com: no such host"

wget https://discovery-stage.hub.docker.com/v1/clusters
--2015-04-16 10:24:41--  https://discovery-stage.hub.docker.com/v1/clusters
Resolving intproxy81.prod.srv.westpac.com.au... 10.8.112.68
Connecting to intproxy81.prod.srv.westpac.com.au|10.8.112.68|:81... connected.
Proxy request sent, awaiting response... 404 Not Found
2015-04-16 10:24:42 ERROR 404: Not Found.

Any ideas?

Cheers,

**Comment by pireslaert** [comment]
Also when I try with a local file:

docker run --rm swarm manage -H tcp://XX.XX.XX.XX:2375 file:///tmp/my_cluster
time="2015-04-16T00:39:43Z" level=fatal msg="open /tmp/my_cluster: no such file or directory"

$ cat /tmp/my_cluster
XX.XX.XX.XX:2375
yy.yy.yy.yy:2375

What am I doing wrong? I got the lastest swarm image and running docker:
docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

Cheers

**Comment by YanXiaoping** [comment]
Hi,

Is “/tmp/my_cluster” host directory? To be visible inside container you need to mount volume?

Br, Rip

**Comment by abronan** [comment]
@pireslaert Indeed, as noted by @YanXiaoping, because you run the manager on a container, you need to mount the host directory as a data volume with:

```
docker run --rm -v /tmp:/tmp swarm manage -H tcp://XX.XX.XX.XX:2375 file:///tmp/my_cluster
```

For your issue with the token discovery service, this seems to be a proxy issue.. can you check if the discovery is reachable outside of this setup?

**Comment by pireslaert** [comment]
Hi, indeed! @YanXiaoping was right i had to pass as a volume the documentation needs updating: http://docs.docker.com/swarm/discovery/#using-a-static-file-describing-the-cluster

I do  get another error though:
time="2015-04-16T01:53:43Z" level=fatal msg="listen tcp XX.XX.XX.XX:2375: bind: cannot assign requested address"

But as for the discoveryservice I get a 404 anywhere I tried (outside the setup, outside work network) (https://discovery-stage.hub.docker.com/v1/clusters) 

Cheers,

**Comment by pireslaert** [comment]
I'm trying to run swarm on the simplest way:

 docker run --rm swarm manage -H tcp://XX.XX.XX.XX:2375 nodes://XX.XX.XX.XX:2375,YY.YY.YY.YY:2375
time="2015-04-16T06:39:22Z" level=info msg="Listening for HTTP" addr="XX.XX.XX.XX:2375" proto=tcp
time="2015-04-16T06:39:22Z" level=fatal msg="listen tcp XX.XX.XX.XX:2375: bind: cannot assign requested address"

both nodes are listing on the ports and can run commands remotely:
docker -H tcp://XX.XX.XX.XX:2375 info
Containers: 15
Images: 332
Storage Driver: devicemapper
 Pool Name: docker-253:2-522364-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file:
 Metadata file:
 Data Space Used: 13.1 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 19.22 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: false
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 2.6.32-504.8.1.el6.x86_64
Operating System: <unknown>
CPUs: 16
Total Memory: 29.37 GiB
Name: XX.XX.XX.XX
ID: XX.XX.XX.XX
Debug mode (server): true
Debug mode (client): false
Fds: 16
Goroutines: 17
EventsListeners: 0
Init Path: /opt/fxsw/docker/software/docker

docker -H tcp://YY.YY.YY.YY:2375 info
Containers: 1
Images: 94
Storage Driver: devicemapper
 Pool Name: docker-253:2-261247-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.142 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 3.457 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 2.6.32-504.8.1.el6.x86_64
Operating System: <unknown>
CPUs: 16
Total Memory: 29.37 GiB
Name: YY.YY.YY.YY
ID: YY.YY.YY.YY
Debug mode (server): true
Debug mode (client): false
Fds: 14
Goroutines: 16
EventsListeners: 0
Init Path: /opt/fxsw/docker/software/docker
Docker Root Dir: /var/lib/docker

Any idea of what am missing?

Cheers,

**Comment by pireslaert** [comment]
@abronan its strange that I'm getting this error:
level=fatal msg="Post https://discovery-stage.hub.docker.com/v1/clusters: dial tcp: lookup discovery-stage.hub.docker.com: no such host"

I am using a proxy and can pull images from the hub, but not the discovery service?

**Comment by pireslaert** [comment]
I got the swarm manage working with local files as a discovery service, the problem was that my nodes were not listening on tcp 2375 ports and the container of the swarm manager:
docker run -p 2376:2375 --rm swarm manage -H tcp://X.X.X.X:2375 nodes://X.X.X.X:2375,Y.Y.Y.Y:2375
But I still can't connect to the discovery service though, not the end of the world as i can work with other discovery services.

Thanks for the help @YanXiaoping @abronan 

Cheers,

**Comment by YanXiaoping** [comment]
@abronan @pireslaert , any idea why I get this error:
docker run -p 2376:2375 --rm swarm manage -H tcp://X.X.X.X:2375 nodes://X.X.X.X:4243,Y.Y.Y.Y:4243
time="2015-04-17T09:33:42Z" level=info msg="Listening for HTTP" addr="X.X.X.X:2375" proto=tcp
time="2015-04-17T09:33:42Z" level=fatal msg="listen tcp X.X.X.X:2375: bind: cannot assign requested address"

[root@centos-minion ~]# ps aux| grep docker
root      5939  0.9  2.1 1103792 41348 ?       Ssl  Apr01 222:33 /usr/bin/docker -d --selinux-enabled -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock

Also, why we use --rm here? shouldn't we keep the swarm mnager running?

**Comment by vieux** [comment]
@YanXiaoping you are running the manager in a container, when you use `-H tcp://X.X.X.X:2375` I'm guessing you are using an IP from the machine, which is not available inside the container, what you should do it bind to 0.0.0.0 inside the container and specify your address when you bind in docker. IT would look like :+1: 

```
docker run -p 2376:X.X.X.X:2375 --rm swarm manage -H tcp://0.0.0.0:2375 nodes://X.X.X.X:4243,Y.Y.Y.Y:4243
```

Regarding the `--rm` it is to remove the container when it exits. Usually you want to start the manager in background so, use `-d`

```
docker run -p 2376:X.X.X.X:2375 -d swarm manage -H tcp://0.0.0.0:2375 nodes://X.X.X.X:4243,Y.Y.Y.Y:4243
```

**Comment by YanXiaoping** [comment]
Thank you @vieux, it works
There is one syntax error in this command:
docker run -p 2376:X.X.X.X:2375 -d swarm manage -H tcp://0.0.0.0:2375 nodes://X.X.X.X:4243,Y.Y.Y.Y:4243 
It should be:
docker run -p X.X.X.X:2376:2375 -d swarm manage -H tcp://0.0.0.0:2375 nodes://X.X.X.X:4243,Y.Y.Y.Y:4243

**Comment by vinaychatra** [comment]
Although this issue is closed, just want to mention the workaround I followed which solved the issue. I created my own wrapper swarm image with http proxies defined. 

FROM swarm
MAINTAINER Name <email>
ENV http_proxy http://www-proxy.us.oracle.com:80
ENV https_proxy http://www-proxy.us.oracle.com:80

I then worked with the "wrapper" swarm image instead of the swarm image itself

**Comment by YanXiaoping** [comment]
Hi,

Thanks for this information.

Br, Rip

**Comment by hoeghh** [comment]
Hi, I had the same problem, but found out why. 

I had added a "--dns=192.168.0.1" to my startup of the docker daemon. This is the dns we use where I work, but at home its 192.168.1.1, and then swarm will not run a create command. I corrected the dns, restartet the docker daemon, and then it worked. On Fedora 22 its in this file : /etc/sysconfig/docker
