### ISSUE TITLE
Swarm does not pass pull errors back to the client properly

### ISSUE THREAD

**Issue by huslage** [docker/swarm#608]
When doing a `docker run` of an image in a private repo that doesn't exist on any host in the cluster, we received an error: `invalid character 'v' looking for beginning of value`. 

Doing a `docker pull` of the image directly on the host, we saw that the CA.pem for the registry had not been installed on the client machine.

Swarm should pass the error back to the client instead of trying to parse the error as JSON.

**Comment by vieux** [comment]
@huslage were you using master or 0.1.0 ?

**Comment by huslage** [comment]
Whatever version is in swarm:latest on DockerHub.

On Thu, Apr 9, 2015 at 12:28 PM, Victor Vieux <notifications@github.com>
wrote:

> @huslage <https://github.com/huslage> were you using master or 0.1.0 ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/swarm/issues/608#issuecomment-91319185>.
>



-- 
Aaron Huslage
Solution Architect - Docker, Inc.
+1-919-600-1712

**Comment by vieux** [comment]
@huslage Ok I'm pretty sure it's fixed on master already. I'll make sure of it.

**Comment by aluzzardi** [comment]
Could you try to reproduce on master?

**Comment by phlegx** [comment]
I can also pull just fine outside the swarm env from my local test registry, but I do get the same error as @huslage when pulling form inside the swarm env.

Using newest swarm version ```0.2.0```

**Comment by vieux** [comment]
@phlegx what do you mean by `swarm env` ? Thanks

**Comment by phlegx** [comment]
@vieux  I meant by setting the environment (env) like this:  ```eval $(docker-machine env --swarm swarm-master)```

best
m

**Comment by phlegx** [comment]
I just tried with the master version ```0.3.0 (HEAD)``` but still the error seems to appear:

```
docker pull localhost:5000/postgres
swarm-master: Pulling localhost:5000/postgres:latest... : invalid character 'v' looking for beginning of value
```

**Comment by phlegx** [comment]
I think this has to do something with SSL. My local registry server is running on port 5000 and not SSL and it seems that within the clustering environment this cannot be handled. My remote registry server however runs on SSL and I can pull there just fine, also from the clustering environment.

**Comment by vieux** [comment]
and you can pull the same way with docker (without swarm) on both ? or do you need to specify some parameters ?

**Comment by phlegx** [comment]
@vieux yes I can pull just fine without swarm on both. No special params needed.

**Comment by aluzzardi** [comment]
@vieux Could this be similar to #706?

**Comment by phlegx** [comment]
I have to correct me here: Also with my own remote repository server (SSL with valid startssl cert) I run into trouble when pulling images. I frequently run into timeouts,  please see:

https://github.com/docker/compose/issues/1387

When running  pull then the pull for an image the image is pulled by all of the swarm nodes, one of them in the end times out. Not sure why all of the swarm nodes are pulling the same image, or maybe all of them pulling just parts.

**Comment by phlegx** [comment]
I have to correct me here: Also with my own remote repository server (SSL with valid startssl cert) I run into trouble when pulling images. I frequently run into timeouts,  please see:

https://github.com/docker/compose/issues/1387

When running  pull then the pull for an image the image is pulled by all of the swarm nodes, one of them in the end times out. Not sure why all of the swarm nodes are pulling the same image, or maybe all of them pulling just parts.

**Comment by sayash** [comment]
I face this error when asking swarm to run an image from an insecure private registry. I've added the "--insecure-registry" line on the Docker engine, but I still see the `invalid character 'v' looking for beginning of value` error.

I pulled and started running swarm last week, and a `docker pull swarm` says it is the latest image. Would love to help with logs  if someone can point me to the relevant logs here.

**Comment by aluzzardi** [comment]
@sayash You can try the 0.3.0 release candidate: `docker run swarm:0.3.0-rc2`

**Comment by aluzzardi** [comment]
@sayash Did you have a chance to try with `0.3.0`?

**Comment by sayash** [comment]
Hey - I did try switch to 0.3.0 a couple of weeks ago and I don't see this error anymore.
I should've updated the thread - my bad!

**Comment by aluzzardi** [comment]
Awesome - thanks!

And thanks @jimmyxian, I believe you fixed this issue.
