### ISSUE TITLE
Test cases added but test coverage decreased

### ISSUE THREAD

**Issue by chanwit** [docker/swarm#615]
At least 3 PRs at the moment, #614, #612 and #581 added unit and integration test cases to the code base. All of them are falsely reported that they decreased the test coverage without doing so.

**Comment by abronan** [comment]
@chanwit We are looking into this, thanks for reporting :+1:

**Comment by thaJeztah** [comment]
Perhaps coverall takes the code of the tests *themselves* as non-covered?

**Comment by aluzzardi** [comment]
It's a problem with coveralls - it says "Coverage decreased (-XX%) to YY%", where YY is the current coverage. So there's a problem when computing XX, for some reason.

Let's ignore it for now.

**Comment by abronan** [comment]
Seems to be solved, closing for now.
