### ISSUE TITLE
Warning/Refuse to run integration tests if storage driver is devicemapper

### ISSUE THREAD

**Issue by abronan** [docker/swarm#621]
As of now there are issues running integration tests using `devicemapper` as the storage driver with `dind` on swarm.

We should add a warning message or refuse to run integration tests if docker uses `devicemapper`.

related to #522

**Comment by HisenWu** [comment]
LGTM

**Comment by jimmyxian** [comment]
LGTM
I run integration tests in Centos7 using devicemapper, i fails sometime.
I will rebuild integration test environment in Ubuntu using aufs.

**Comment by abronan** [comment]
Considering that integration tests will run on CI (#651) using `aufs` by default, I'm closing the issue for now.
