### ISSUE TITLE
Improve docker build

### ISSUE THREAD

**Issue by vieux** [docker/swarm#632]
The docker build implementation (#603) is currently pretty basic.
It would be nice to rewrite it the same way load (#609) was implemented so we don't use the proxy anymore.

We should add a `Cluster.Build` method to the cluster interface and add build support in `dockerclient`

**Comment by vieux** [comment]
@jimmyxian do you think you could look into this as you did the load ? Thanks

**Comment by jimmyxian** [comment]
@vieux 
Yes, i think so. 
Swarm Api --> Cluster Api --> Engine Api   --> dockerclient Api
It's much better to do in this way. I will be working on it
