### ISSUE TITLE
Integration tests for discovery

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#644]
The following services need integration tests:

* [x] consul 
* [x] etcd 
* [x] file 
* [x] token 
* [x] zookeeper

**Comment by aluzzardi** [comment]
Hey @chanwit, if by any chance you get bored, do you think you could tackle `consul`?

Similar to `zookeeper`, there is an image ready for consul: https://github.com/progrium/docker-consul

No pressure, we'll do it eventually :)

**Comment by chanwit** [comment]
@aluzzardi no problem. I'll do it, but it would take sometime anyway.

**Comment by snrism** [comment]
@aluzzardi @chanwit I was working on it. Let me try to finish it in next few days and open a PR. If I am unable to get it done, will drop in a note soon.

**Comment by chanwit** [comment]
@snrism great! let me know if you've got the PR up.

**Comment by snrism** [comment]
@chanwit @aluzzardi opened a PR for consul integration https://github.com/docker/swarm/pull/733. If this works, I can work on etcd next in the next few days as well.
