### ISSUE TITLE
Tight loop due to duplicated "/etc/docker/key.json"

### ISSUE THREAD

**Issue by thefallentree** [docker/swarm#657]
Hi,

We ran into a issue where multiple docker machines have same /etc/docker/key,json , caused by cloning. 

And swarm doesn't handle this issue well, it will use ~30% cpu keep looping containers from those machines, driving docker daemon cpu to 100%.

While it is a issue with configuration, but it would be nice to fix the tight loop.

Cheers.

**Comment by vieux** [comment]
@thefallentree I cannot reproduce the problem, can you still reproduce with 0.3.0-rc2 ?

Althouth I found an issue that might help your problem: #657

**Comment by aluzzardi** [comment]
ping @vieux

**Comment by vieux** [comment]
@thefallentree can you try with swarm 0.4-rc1 ? it seems fixed to me.

**Comment by vieux** [comment]
I see I asked this already for 0.3, I'm going to close this issue. please reopen if the problem persists.
