### ISSUE TITLE
while swarm need to https://discovery-stage.hub.docker.com/v1/clusters when i create a token

### ISSUE THREAD

**Issue by chenjie901** [docker/swarm#664]
when i create token use docker run --rm swarm create i get time="2015-04-23T11:46:52Z" level=fatal msg="Post https://discovery-stage.hub.docker.com/v1/clusters: dial tcp 162.242.195.83:443: i/o timeout"

why swarm need to connect  https://discovery-stage.hub.docker.com/v1/clusters

**Comment by bacongobbler** [comment]
The discovery token is generated from DockerHub and is hosted there: https://github.com/docker/swarm/tree/master/discovery#hosted-discovery-with-docker-hub

**Comment by abronan** [comment]
Hi @chenjie901, 

It needs to connect to the discovery service on the docker Hub to give you a unique token. This unique token will be used by the Swarm Agents to register on this service and by your Swarm Manager to access the list of all the docker daemons it needs to connect to (the agents).

```
                                                              register
                                                       |------------------- Swarm Agent (docker daemon)
                                                       |
                access list                            |      register
Swarm Manager ---------------> Hub Discovery Service < |------------------- Swarm Agent (docker daemon)
                                                       |
                                                       |      register
                                                       |------------------- Swarm Agent (docker daemon)
```

For the error connecting to the discovery service, it's really difficult to determine why you can't access to the service. This might be definitely network related. Can you try to run multiple times the command `curl -x POST https://discovery-stage.hub.docker.com/v1/clusters` and see if it returns the token successfully? If not can you give us more details: Are you using a Proxy? etc.

**Comment by jimmyxian** [comment]
hi @chenjie901 I guess you are in China. Maybe you can't connect the Docker Hub token discovery service. You can try other Discovery backend, such as etcd,zookeeper or local file. 

The same issue as https://github.com/docker/swarm/issues/607, you can follow that.

**Comment by chenjie901** [comment]
@abronan yes i use a proxy, i solve this problem by pass HTTP_PROXY ENV to swarm ,an it works

**Comment by doronl** [comment]
I was not able to fix this...

When I run:

sudo docker run swarm create

I get:

2015/10/19 06:15:47 Post https://discovery-stage.hub.docker.com/v1/clusters: dial tcp: i/o timeout

When I add a proxy:

sudo docker run --rm -e https_proxy=http://***:8080 -e http_proxy=http://****:8080 swarm create

I get:

2015/10/19 06:20:52 Post https://discovery-stage.hub.docker.com/v1/clusters: http: error connecting to proxy http://****:8080: dial tcp: i/o timeout

**Comment by jianghaitao** [comment]
@doronl you need to check if you can reach your proxy servers first. I passed proxy settings into swarm and was able to get a token.

**Comment by doronl** [comment]
I eventually gave up using the hub token and used a etcd for discovery.
Thanks
