### ISSUE TITLE
Cluster is not preserved across machine restarts

### ISSUE THREAD

**Issue by arun-gupta** [docker/swarm#668]
Created a Swarm cluster as explained at: http://blog.arungupta.me/clustering-docker-swarm-techtip85/

TL;DR
```
docker run swarm create
docker-machine create -d virtualbox --swarm --swarm-master --swarm-discovery token://117c8d19ba140d7ba3259aae9012e22f swarm-master
docker-machine create -d virtualbox --swarm --swarm-discovery token://117c8d19ba140d7ba3259aae9012e22f swarm-node-01
docker-machine create -d virtualbox --swarm --swarm-discovery token://117c8d19ba140d7ba3259aae9012e22f swarm-node-02
```

Now listing the cluster information using `docker info` shows the correct value:

```
~> eval "$(docker-machine env --swarm swarm-master)"
~> docker info
Containers: 4
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 3
 swarm-master: 192.168.99.108:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 1.025 GiB
 swarm-node-01: 192.168.99.109:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 1.025 GiB
 swarm-node-02: 192.168.99.110:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 1.025 GiB
```

Rebooted the machine, manually restarted the Docker Machines (node1, node2, master) and now `docker info` does not show the correct values:

```
~> eval "$(docker-machine env --swarm swarm-master)"
~> docker info
Containers: 0
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 0
```

The cluster state is not preserved across machine restarts.

**Comment by vieux** [comment]
This is a machine issue I think, @ehazlett ?

**Comment by aluzzardi** [comment]
@arun-gupta Have you given swarm a few seconds to probe the cluster?

**Comment by rafabene** [comment]
This issue also happens with me and doesn't get fixed after waiting a minute.

**Comment by arun-gupta** [comment]
Checked again with 0.3.0 and still the same issue. Here is what is reported:

```
Containers: 0
Images: 0
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 0
CPUs: 0
Total Memory: 0 B
```

**Comment by djenriquez** [comment]
+1, same issue. An issue is open on machine: docker/machine#1518, thanks @arun-gupta

**Comment by djenriquez** [comment]
Maybe an easy question to answer: for now, how would we reattach our docker-machine nodes back onto the swarm?

**Comment by abronan** [comment]
@arun-gupta @rafabene this is actually a TLS certs issue, a parameter gets changed on reboot (can be the private IP of the node if you stop/restart) and the certs are not valid anymore for docker daemons, thus Swarm cannot connect and register the Agents anymore. This needs to be consistently handled for machine restart. Thanks for opening the issue on the `docker-machine` side :)

**Comment by aluzzardi** [comment]
I'll close this since it appears to be a machine issue. Please re-open if something needs to be fixed on swarm side

**Comment by brunoborges** [comment]
When I restart a specific docker-machine swarm node, that machine does not come back to the swarm cluster. Isn't this a problem?

**Comment by StrictlySkyler** [comment]
+1.  If the machine goes down for a reboot from some other mechanism, say scheduled maintenance, the swarm-agent won't automatically reconnect to the swarm master.  This means the swarm-agent, at a minimum, needs to be recreated after any reboot.

**Comment by BruceZu** [comment]
wait patch to fix it too

**Comment by cirocosta** [comment]
are there any issues created on `docker/machine` related to this? If so it'd be good to have it linked here for future references.

**Comment by cirocosta** [comment]
@BruceZu  when this happens here i get it working with `docker-machine provision <machine1> <machine2>...` as suggested on https://github.com/docker/machine/issues/1518
