### ISSUE TITLE
"All" option for running a container on several hosts

### ISSUE THREAD

**Issue by vbichov** [docker/swarm#677]
Hello,

I've been going through the swarm documentation, and something that I (personally) really missed, is an option to ask swarm to run a container on all hosts. (or all hosts that matches a filter)

For example, say you have a logging or monitoring agent container that you would like to run on all hosts, and you don't want to have to: run on host-1, run on host-2 etc...
you just want to: docker run ... -e affinity:container==some-pre-req -e nodeCount:[all | number] ...

that is, you would like to tell swarm to run an arbitrary number of instances of that container (or all) on the nodes that match the filter criteria.

Does this makes sense for anyone else?

**Comment by abronan** [comment]
I guess that what you want refers to Global Scheduling (#601) and it is planned for 0.3.0. The issue being that we need to properly handle the output in `ps` (amongst other things). I'll close this issue as this is a duplicate, but feel free to comment on #601. Thanks!
