### ISSUE TITLE
Improve build

### ISSUE THREAD

**Issue by vieux** [docker/swarm#694]
A few days ago, `-c` and `-m` were added to `docker build`. We should use those to schedule builds.

**Comment by aluzzardi** [comment]
Should this be in 0.3.0 or 0.4.0? I just created a new milestone, feel free to move around.

**Comment by vieux** [comment]
@aluzzardi thanks I moved it to 0.4.0, if we do it before it's even better.

**Comment by garagatyi** [comment]
Consider such situation (docker API is used) :

There is 2 nodes
* node1 with 3 GB RAM left
* node2 with 4 GB RAM left

User1 wants to run container with 2 GB from dockerfile. Layers are not cached yet on instances. 
Swarm schedule build from User1 on instance1.
User2 wants to run container with 2 GB from dockerfile. Layers are cached already. And first build is not finished yet.
Swarm schedule build from User2 on instance1 too.
Swarm finishes second build and User2 creates and starts container.
Swarm finishes first build and User1 tries to create and start container. But there is not enough memory on instance1.

To fix it User1 have to rechedule build/create/start on instance2 and wait until build will be finished again.

Will I be able to avoid such situations with -m ?

**Comment by aluzzardi** [comment]
Thanks @jimmyxian

**Comment by aluzzardi** [comment]
Unfortunately, there's no way to do that.

Keep in mind that supporting `docker build` in Swarm is a "gimmick" and we encourage to push images to a registry before running in the cluster
