### ISSUE TITLE
containers not refreshed after docker wait

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#714]
If you run `docker wait` immediately followed by `docker ps -l`, you will still see the container as running.

Maybe we should force a refresh before having `wait` return.

Thoughts?

**Comment by jimmyxian** [comment]
@aluzzardi Agree

**Comment by aluzzardi** [comment]
@jimmyxian Is this fixed?

**Comment by jimmyxian** [comment]
@aluzzardi 
Yeah, already fixed in https://github.com/docker/swarm/pull/796
```
"/containers/{name:.*}/wait":    proxyContainerAndForceRefresh,
```

**Comment by aluzzardi** [comment]
Awesome
