### ISSUE TITLE
Docs discrepancies (in-container & outside-container)

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/swarm#722]
Someone starting to read Swarm docs here http://docs.docker.com/swarm/ is seeing that `swarm` is executed within a container:

    docker run -d swarm join ...

and then when they go to the next page ("[Discovery service](https://docs.docker.com/swarm/discovery/)") examples suddenly start running `swarm` out of the container:

    swarm join ...

It's probably not a big deal for a person who knows what they're doing but for a newcomer, it is sort of puzzling and one might ask "why I'm starting to run this outside container now?".

**Comment by aluzzardi** [comment]
ping @SvenDowideit @moxiegirl

**Comment by moxiegirl** [comment]
@aluzzardi When you have a few minutes, come chat and I'll get a grasp of this isse; then I'll fix the docs.

**Comment by thaJeztah** [comment]
I saw https://github.com/docker/swarm/pull/839 was rewriting the docs, but looks like there's still both containerised and non-containerised instructions in there

**Comment by moxiegirl** [comment]
@aluzzardi I'll come by in the AM and see what I can do about fixing this for this release.

**Comment by amitshukla** [comment]
Docs look cleaned up
