### ISSUE TITLE
rename: Container ID and Name collision

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#729]
I experienced this in our tests for `rename`, but it might be affecting other:

> Conflict, The name c4 is already assigned to c4faf30b321817bad939eef1c839f61cd5e111f2ff833de80880af754bdadd50. You have to delete (or rename) that container to be able to assign c4 to a container again.

Here we looked up `c4` as a name and collided with a container whose id starts with c4.

**Comment by vieux** [comment]
Oh nice, I'm glad you found the cause, I'll take care of this one.
