### ISSUE TITLE
Bug: Image.Match() matching image using prefix influence some api

### ISSUE THREAD

**Issue by jimmyxian** [docker/swarm#740]
### BUG reproduce
one manage: 127.0.0.1:2222
one node with busybox image:127.0.0.1:2375
* docker rmi API
```
[root@localhost swarm]# docker -H 127.0.0.1:2222 rmi bus
Error response from daemon: localhost.localdomain: 409 Conflict: Conflict, cannot delete image 4986bf8c15363d1c5d15512d5266f8777bfba4974ac56e3270e7760f6f0a8125 because it is tagged in multiple repositories, use -f to force
FATA[0000] Error: failed to remove one or more images 

[root@localhost swarm]# docker -H 127.0.0.1:2222 rmi not_exists
Error response from daemon: No such image not_exists
FATA[0000] Error: failed to remove one or more images

[root@localhost swarm]# docker -H 127.0.0.1:2375 rmi bus
Error response from daemon: No such image: bus
FATA[0000] Error: failed to remove one or more images  
```
We find that "bus image" and "not_exists image"  are not in node, but respond differently. Because the busybox'prefix is bus, in our swarm, will send the request the node with busybox.

* docker history API
```
[root@localhost swarm]# docker -H 127.0.0.1:2222 history bus
FATA[0000] Error response from daemon: could not find image: no such id: bus 
[root@localhost swarm]# docker -H 127.0.0.1:2222 history not_exist
FATA[0000] Error response from daemon: No such image: not_exist 
[root@localhost swarm]# docker -H 127.0.0.1:2375 history bus
FATA[0000] Error response from daemon: could not find image: no such id: bus
```
Also respond differently

* docker save API
```
[root@localhost swarm]# docker -H 127.0.0.1:2222 save bus > /home/aaa.tar
time="2015-05-07T06:14:01-04:00" level="fatal" msg="Error: could not find image: no such id: bus" 
[root@localhost swarm]# 
[root@localhost swarm]# docker -H 127.0.0.1:2222 save not_exists > /home/aaa.tar
time="2015-05-07T06:14:11-04:00" level="fatal" msg="Error: No such image: not_exists" 
```
Also respond differently

* Other API which use proxyImage and Image.Match() maybe have the save problem

### Problem
Image.Match() : match image name using prefix

### How to Solve? Need help
Fix matching image name behavior. 
Sometimes name contains tag, sometimes do not have. How to match, does not have a clear way?
In delete image, if name do not have tag, docker will delete latest.
In save image, if name do not have tag, will save all images with repoName. if have tag, will save that one.

**Comment by jimmyxian** [comment]
ping @aluzzardi @vieux

**Comment by vieux** [comment]
@jimmyxian I think it's fine for `docker history` and `docker save` I'll fix match

**Comment by jimmyxian** [comment]
@vieux In swarm `docker rmi`, two problems:
* I find that calling remove image by id in `engine`. I don't know if it's right. If one image has several tags and we just want delete one of it, In swarm, it can't
* In docker, rmi with no tag, it will delete latest. But in swarm, it can't

So, in my opion, rmi should follow this:
* First,  match image ID, If ID matches: remove image by id
* Second, match image repotag. If Input with no tag, add default latest tag. then match. then remove by repotag.

cc/ @aluzzardi

**Comment by vieux** [comment]
@jimmyxian can you add a PR with the tests that fail ?

**Comment by jimmyxian** [comment]
@vieux OK

**Comment by jimmyxian** [comment]
@vieux I have done to add a PR https://github.com/docker/swarm/pull/788
