### ISSUE TITLE
Port assignment during configuration

### ISSUE THREAD

**Issue by vbichov** [docker/swarm#741]
Hello,

I'm attempting to install swarm on several machines using **Consul** for discovery.
I'm afraid that I've found the documentation for configuring the Swarm cluster to be incredibly unclear:

*$ swarm join --addr=node_ip:2375 consul://consul_addr/path*
what is the "node_ip" and what is the 2375 port? and can it be changed?
i suspect that it is the localhost - that is the host running the swarm container, and also that the port is the Docker port and that it can't be changed - that is, you MUST have Docker listening locally on that port.

*$ swarm manage -H tcp://swarm_ip:swarm_port consul://consul_addr/path*
what is "swarm_ip"? what is the port? and what is "path" for the consul?

Thank you.

**Comment by vbichov** [comment]
I'm closing this due to lack of response. (and since i did get it to work)
I would still advice to revise the documentation and make it - and the Swarm operational model - more clear.

**Comment by snrism** [comment]
The documentation update (after resolving https://github.com/docker/swarm/issues/817) will address this issue. but regarding <path> either in etcd/consul/zookeeper, we can add a sentence in the discovery readme to discuss how to configure it or can add an example command. However, IMO including additional details about individual services should be out of scope.

**Comment by moxiegirl** [comment]
@aluzzardi if you want to assign these to me, that is fine.

**Comment by aluzzardi** [comment]
ping

**Comment by moxiegirl** [comment]
Thanks for the ping @aluzzardi .  I'll work on this Thurs/Friday this week.

**Comment by amitshukla** [comment]
Closing since its a pretty old ticket
