### ISSUE TITLE
integration: zookeeper random failing in janky

### ISSUE THREAD

**Issue by chanwit** [docker/swarm#742]
I saw some random failing of the zookeeper test case at least 2 times in `janky'. Not sure if it's caused by non-existed zookeeper image locally on the CI?

Some time this test on `janky` is fine.
Tested newly `run.sh` locally on my machine is fine.

**Comment by chanwit** [comment]
if it's about port conflicts, is there any chance we can use this `freeport` utility?

https://github.com/phayes/freeport

**Comment by snrism** [comment]
I did see this issue before as well. Same behavior seen in https://github.com/docker/swarm/pull/733

https://jenkins.dockerproject.com/job/Swarm-PRs/79/console

**Comment by vieux** [comment]
I would use `docker run -P` and do a docker port to find it

**Comment by aluzzardi** [comment]
I don't think it's port conflicts - I think this might be the same issue as seen in Consul.

My guess: zookeeper is not ready to serve requests.
