### ISSUE TITLE
Command line variable evaluation on Swarm host - escape for bash

### ISSUE THREAD

**Issue by vbichov** [docker/swarm#760]
Hello,

When scheduling a container using Swarm, it evaluates stuff like: $(hostname) locally.
So, if your command has something like: docker run ... -h $(hostname) ...
it will result in an incorrect expression.

This is a bit of an issue, since the whole point is that you don't know in advance where your container will run.
Yet, some containers require such or similar evaluation in the docker command line.

will there be some way to escape / defer evaluation, so it will run on the target host?

Thank you.

**Comment by vieux** [comment]
This is related to the docker cli, it's not swarm specific, please ask you question on https://github.com/docker/docker

**Comment by vbichov** [comment]
@vieux Swarm already exposes API that does not behave as Docker does.
see: https://docs.docker.com/swarm/API/#endpoints-which-behave-differently
while one could use the Docker client remotely and run into a similar issue, this just might become a prevalent issue when using Swarm. 
please consider addressing this issue.

**Comment by vieux** [comment]
@vbichov we won't.

It's a docker issue, you can have the docker cli on one machine and the docker deamon on another (not use swarm at all) and you still could use the feature your request.

So it has to be done in docker, not swarm.
