### ISSUE TITLE
Repull image on target host

### ISSUE THREAD

**Issue by vbichov** [docker/swarm#761]
How can you repull an image on your target host, assuming you don't know what the target host will be?

**Comment by vieux** [comment]
@vbichov I don't understand what you mean by `you don't know what the target host will be`

**Comment by vbichov** [comment]
you may use swarm to issue a "docker pull" command on some host.
you presumably also use some strategy and a filter to guide the selection of the target host.
ultimately, the target host is selected by swarm - you don't know ahead of time which it will be.
if you wish to pull (specifically, repull) an image before running it, you will run "swarm pull" and then "swarm run".
but these two commands may run on two different hosts.

**Comment by vieux** [comment]
@vbichov not sure it's what you want, but currently swarm pull will pull on all hosts, so the next run will have the last version of the image.

**Comment by vbichov** [comment]
@vieux Thank you.

**Comment by vbichov** [comment]
Is there a plan to change this behavior?
(So that Swarm will not pull on all hosts?)

**Comment by chanwit** [comment]
I'd like to rephrase what @vbichov asked to this one.
@vieux can we do `docker pull -e constraint:node==node1 image` to let it pulls to a specific node.

If not, may be it's a possible one to be a PR.

**Comment by aluzzardi** [comment]
I see what you mean - basically how to update an image on a particular host?

**Comment by vbichov** [comment]
@aluzzardi Yes, but not just a particular host! **the host that is going to run your container**.
You do no possess this information, even if you could pull on a specific host, (which you must be able to do, or Swarm is not scalable and therefore cannot be used) if you use "docker pull" and "docker run" separately, it is conceivable that the host where the image was pulled on, and the host where it will run will not be the same host.

The only solution I can think of - and I know you won't like this - is to break the Swarm abstraction over Docker API and add a "-swarm" flag(s) to the run command.
you will need one to pull before running.
(and very possibly one to "rerun" - kill the running container by name and run - but that's a separate discussion)

**Comment by aluzzardi** [comment]
Got it.

The workaround for now would be to run `docker pull` against Swarm - it will pull on **every** host (therefore including the host that is going to run your container).

But I agree that we need to find a real solution. Perhaps having a swarm specific flag (`-e repull`) or maybe a Docker flags (`docker run --pull`)

**Comment by mikedougherty** [comment]
I don't know if this is the right place to pile on, but a option for the engine (which would get exposed via swarm) to force a pull before running would be very helpful in some situations. +1

**Comment by aluzzardi** [comment]
Actually, there is a better workaround.

1. If possible, rely on tags rather than `latest` when scheduling a container (as in, instead of running `redis`, run `redis:3.0.3`). That way you will be sure that the underlying host will pull the right tag before creating the container
2. Docker supports addressing the content with a digest. You can schedule a container with the exact image you want and swarm will pull it.

**Comment by vbichov** [comment]
@aluzzardi either one of the flags you've suggested would be awesome!
(the workaround would work - of course , but may be tricky to *pull* off under certain circumstances... )

**Comment by kevinsimper** [comment]
@aluzzardi "You can schedule a container with the exact image you want and swarm will pull it." 
How can you do that?

I have runned into the same problem, it is not really a solution to pull the same images on all hosts, and that I am trying to pull a private registry image.

**Comment by garagatyi** [comment]
Maybe in that case `docker pull` should be called on the node implicitly during container creation step?
See https://github.com/docker/swarm/pull/1350#issuecomment-152112163

**Comment by amitshukla** [comment]
Old issue... closing.

**Comment by yellowiscool** [comment]
Why is it closed? Is possible to do it now ?

**Comment by hekaldama** [comment]
Also interested in having a solution for this. Thanks.

**Comment by garagatyi** [comment]
I think that [this](https://github.com/docker/swarm/pull/1350#issuecomment-152112163) improvement suggested by @aluzzardi can help. Actually I need it too. But looks like it was never implemented.
