### ISSUE TITLE
Container labels are ignored

### ISSUE THREAD

**Issue by peebles** [docker/swarm#764]
When launching a container to a non-clustered docker host thru port 2376, I can pass a label which I can then later filter on with 'docker ps':

    $ docker run -d --label=roambee=true --name=busybox busybox sleep 120
    $ docker ps  --filter "label=roambee=true"
    CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
    f4273a4643fc        busybox:latest      "sleep 120"         13 seconds ago      Up 9 seconds                            busybox             

I can 'docker inspect' the container and see the label metadata.  

However, if I launch this container into a docker-swarm thru port 3376, the label is not present on the container.  The 'docker ps' command returns ALL CONTAINERS.  'docker inspect' shows an empty label structure.

**Comment by vieux** [comment]
@peebles this was fixed with https://github.com/docker/swarm/pull/738 are you using 0.2.0 or master ?

**Comment by peebles** [comment]
I am using "docker run --rm swarm create" (etc).  So which version are you talking about?
$ docker --version
Docker version 1.6.0, build 4749651
$ docker-machine --version
docker-machine version 0.2.0 (8b9eaf2)

**Comment by peebles** [comment]
I see.  I can install "swarm" binary itself and use it.  And master has the fix.  Then how do I do things like

  eval $(docker-machine env --swarm cluster-master)
  docker ps

**Comment by peebles** [comment]
Cool, it works with master.  I git-cloned, built the image with Dockerfile
and used that image when launching the swarm nodes and master.  ps
filtering appears to work fine now.
a

**Comment by abronan** [comment]
Perfect! :)
