### ISSUE TITLE
Admin only Swarm master

### ISSUE THREAD

**Issue by arun-gupta** [docker/swarm#771]
Running three containers on a three host cluster, with `spread` strategy, shows the following output:

```
CONTAINER ID        IMAGE                                  COMMAND                CREATED              STATUS              PORTS                           NAMES
7351d1490c5c        arungupta/wildfly-mysql-javaee7:host   "/opt/jboss/wildfly/   About a minute ago   Up About a minute   192.168.99.106:8081->8080/tcp   swarm-master/mywildfly2   
fd49a228591d        arungupta/wildfly-mysql-javaee7:host   "/opt/jboss/wildfly/   5 minutes ago        Up 4 minutes        192.168.99.108:8080->8080/tcp   swarm-node-02/mywildfly   
b49d627a0431        mysql:latest                           "/entrypoint.sh mysq   About an hour ago    Up About an hour    192.168.99.107:3306->3306/tcp   swarm-node-01/mysqldb     
```

A container is started one each on master and two other nodes. It would be beneficial where Swarm master can be made purely admin-only, where no containers are deployed on it.

**Comment by abronan** [comment]
@arun-gupta Are you using `docker-machine`? In this case the Swarm Master will also have a Swarm Agent running on this same machine. It makes sense to have the Master "being" a Swarm Agent so you can use spare resources from the Master to schedule containers onto it.

If you want the master to be admin only, you can use `docker-machine` to create your regular Swarm agents VMs (the same way you did here), and then at the end, launch a `non-swarm` docker machine and setup the Swarm Manager the usual way.

**Comment by vieux** [comment]
@arun-gupta you can always use `-e node!=swarm-master` when you do a docker run ;)

**Comment by arun-gupta** [comment]
Having an admin-only Swarm master would be a usual design pattern and should be supported easily.

**Comment by aluzzardi** [comment]
@arun-gupta It's supported out of the box, actually, that's the default. You are explicitly running `swarm join` on the `swarm-master` machine, which is effectively putting the master into the rotation.

**Comment by arun-gupta** [comment]
@aluzzardi The cluster is created as:

```
docker-machine create -d virtualbox --swarm --swarm-master --swarm-discovery token://e59c8e65543eb2e7e9e90164c288cc61 swarm-master
```

What should be the updated command?

**Comment by aanm** [comment]
@arun-gupta Did you run something like `docker-machine create -d virtualbox --swarm join` on the `swarm-master`? If you did, you shouldn't have to in order to achieve what you want.

**Comment by elabrc** [comment]
I'm having this same problem. I would like docker-machine to create the swarm-master without having it join the swarm as a node eligible for receiving containers. In fact I was sure this is how docker-machine worked in 0.2.0. However since upgrading to 0.3.0 this behavior seems to have changed. @vieux may have the best option for the moment.

I think this output below shows that it runs a 'join' container when it shouldn't? 

```
docker-machine create --driver virtualbox --swarm --swarm-master --swarm-discovery token://a1433143888ea2ae299efa8f656a5c93 localmaster
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
To see how to connect Docker to this machine, run: docker-machine env localmaster
~  eval "$(docker-machine env localmaster)"
~  docker ps -a
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                              NAMES
646ab3a5bb95        swarm:latest        "/swarm join --addr    16 seconds ago      Up 13 seconds       2375/tcp                           swarm-agent
caa4c50e15f8        swarm:latest        "/swarm manage --tls   16 seconds ago      Up 13 seconds       2375/tcp, 0.0.0.0:3376->3376/tcp   swarm-agent-master
```

**Comment by abronan** [comment]
@nathanleclaire Is it possible to create a VM with `docker-machine` with only a Swarm Manager running on it as per `0.5.0`? Seems to me that we always create an Agent alongside the Manager right?

**Comment by nathanleclaire** [comment]
@abronan So far, yes.  https://github.com/docker/machine/issues/2302#issuecomment-157553786 proposes one possible solution to the issue.

**Comment by abronan** [comment]
Closing in favor of docker/machine#2302. Let's continue the discussion here as this is related to docker-machine.
