### ISSUE TITLE
Access containers running on a Docker host in a host-independent way

### ISSUE THREAD

**Issue by arun-gupta** [docker/swarm#773]
Started a MySQL server and WildFly application server on Swarm cluster. The default strategy is to spread them across different hosts. In order to access the MySQL server an application deployed on WildFly, the exact IP address of Docker host where MySQL server is running, and the forwarded port need to be passed as environment variable. This is brittle because MySQL server may get killed, and likely start on a new Docker host. The JDBC references within the applications deployed on WildFly will break.

There need to be a mechanism to access MySQL host/port in a Docker host-independent way.

**Comment by marc-** [comment]
Did you try to use something like HAProxy as frontend for this? So your application JDBC configuration will be always point to same host (HAProxy host) and HAProxy will take care finding working MySQL instance. You can also add discovery service to dynamically reconfigure HAProxy.

**Comment by arun-gupta** [comment]
Got it working using simple container linking: https://github.com/javaee-samples/docker-java/blob/master/chapters/docker-container-linking.adoc

**Comment by ligett** [comment]
@arun-gupta unfortunately the link is not working

**Comment by arun-gupta** [comment]
@ligett Container linking is passe. The latest version of Docker for Java developers workshop is now available at https://github.com/docker/labs/tree/master/developer-tools/java.
