### ISSUE TITLE
Broken TTLs

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#794]
It turns out that:

- zk/etcd/consul were not using any TTLs (entries never expired)
- token discovery "never" expires (one week)

Once we fix **1** (@abronan) and **2** (@vieux) we should probably alter the `discovery-*.bats` tests to, at the end, stop one join, wait `heartbeat` seconds and make sure `swarm list` (and possibly `docker info`) doesn't show up the node.

**Comment by vieux** [comment]
At least etcd used to handle TTLs : https://github.com/docker/swarm/blob/48fd99368feacb2929563ea7ec74931d8101b166/discovery/etcd/etcd.go#L87

**Comment by abronan** [comment]
Actually it is fairly easy to implement the concept of Ephemeral for Consul and Zookeeper. For Zookeeper I create a `Key` with the `Ephemeral` flag while in Consul I create a global session with the attribute `Behavior` to `delete` (which will trigger the node deletion at Session invalidate, when the node is considered down by the failure detector)

The open question is: how to do a similar thing with `etcd`? We can emulate this behavior using TTLs but not sure it's the best idea.

So we need to decide whether we:
- Sacrifice TTLs for Ephemeral behavior (supported by Consul and Zookeeper)
- Use TTLs in place of Ephemeral (supported by Etcd, and Consul through sessions), thus ignoring the fact that Zookeeper does not handle TTLs at all.
