### ISSUE TITLE
--rm and -d concurrent support

### ISSUE THREAD

**Issue by magaal** [docker/swarm#798]
Hi - I'd like to submit containers that have a specific purpose across my cluster nodes with affinity set so that only one container runs per node; and then have them shutdown on task completion, freeing up the node for another container. --rm and -d supported simultaneously seems like it would help me out, otherwise I get a flood of output to where I launched my docker run commands. Is this a bad idea?

**Comment by vieux** [comment]
@magaal not a bad idea, bu this is not supported in docker, so it won't be in swarm.

If you want this behavior to change, please open an issue on docker/docker.
