### ISSUE TITLE
Run local built container on swarm

### ISSUE THREAD

**Issue by aanm** [docker/swarm#806]
I know this is probably something hard to do, but will (or is it right now?) be possible to run a docker image built on the host machine to be ran on a swarm machine? I just figure this out when I tried to run the simplest demo from compose and swarm, where one of the containers is built on my machine.

**Comment by aluzzardi** [comment]
You can either:
- Push the container somewhere, then you'll be able to run it, or
- `docker build` on Swarm (instead of the local machine) then `docker run` using image affinities (no need of image affinities once we address #743)

**Comment by aanm** [comment]
@aluzzardi Where does swarm stores the image made by `docker build`? I mean, is it possible the built result would end up on a node and `docker run` will be addressed to a different node?

**Comment by aluzzardi** [comment]
@aanm Yes, very likely. `docker build` uses the same scheduling as `docker run`, so it will end up on a machine depending of your filters and strategy. `docker run` will likely try to run on a different node.

Right now, you can solve this by using image affinities:
```
docker build -t foo .
docker run -e affinity:image==foo foo
```

The former will build an image on the cluster while the latter will schedule a run and force it to be on a machine that has the `foo` image.

#743 will do that for you automatically

**Comment by jasw** [comment]
Thanks, that helped me.

**Comment by aluzzardi** [comment]
@aanm The `affinity` is not required anymore in `master` (and on the upcoming `0.4.0`) thanks to a PR by @jimmyxian

**Comment by aanm** [comment]
@aluzzardi Thanks for the heads up! Can you tell me the PR number?

**Comment by aluzzardi** [comment]
Proposal is #743 and implementation #971
