### ISSUE TITLE
Why not refresh the Nodes' information when some Node crushed down

### ISSUE THREAD

**Issue by lokikiller** [docker/swarm#808]
In swarm cluster some commands getting information from local cache, like 'docker info' or 'docker run' ..., but when some Node crushed down, the information from that commands may not be right. For example, I have 3 nodes in the cluster, then one node crushed down, when I command 'docker -H tcp://0.0.0.0:2375 info' in the master, I will get there are 3 nodes in my cluster, but not 2 nodes. I think this will mistake user. In another case, when I command 'docker run...', swarm may select the crushed node to create container.
So, I do not understand, why not refresh the Nodes' information when some Node crushed down in the 'refreshLoop()' function.

**Comment by abronan** [comment]
Hi @lokikiller, Yes for now the Swarm Manager will still report dead nodes on `docker info`. This is a duplicate issue of #197.

This is however, not as simple as it seems: we need to gracefully stop the connection and all their attached goroutines in `dockerclient` which is something that is not handled now.

Also we need the discovery service to delete entries of dead nodes. There is some work on #801 and the support for this on the Token discovery service is coming too.

By the way Swarm filters out node marked as `unhealthy` during the scheduling decision even though we don't remove them yet from the Cluster list. So a request may fail but after you'll see your container going to an `healthy` node.

Feel free to add on this on the issue I mentioned above! I'm closing this one. Thanks!

**Comment by lokikiller** [comment]
Thanks for you @abronan , but I think we needn't to stop the connection and all their attached goroutines, because when the node repaired, it will join the cluster automatic. I suggest that validate the healthy attribute of engine when use the engine

**Comment by aluzzardi** [comment]
@lokikiller `docker run` will never run containers on unhealthy nodes because of this:
https://github.com/docker/swarm/tree/master/scheduler/filter#health-filter

We are working on getting `docker info` etc right as well

**Comment by lokikiller** [comment]
@aluzzardi The heartbeat is 30 seconds, so once the node crushed down, and command 'docker run' immediately, it may run containers on unhealthy node?
