### ISSUE TITLE
Feedback wanted: Storage configuration UI problem

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#816]
We're running into a UI problem, would love your feedback.

Right now with Swarm you specify a discovery backend such as:
`swarm manage consul://...`

With the upcoming distributed state storage, we'll need a store configuration as well:
`swarm manage --storage consul://... consul://...`

We also have leader election cooking. It depends on a store:
`swarm manage --leader-election consul://... consul://...`

Combined, this can get as ugly as:
`swarm manage --storage consul://... --leader-election consul://... consul://...`

Some thoughts:
- It **may** make sense to run with a different `discovery` than `storage` (`etcd` storage and `token` discovery)
- It doesn't make sense IMO to run with a different backend for leader-election and discovery though (as in, `zk` for storage and `consul` for leader election)

Therefore we can squash `--storage` and `--leader-election` together:

`swarm manage --storage consul://... --leader-election`

However, the are still two repetitive parameters: discovery and storage.

Thoughts?

**Comment by aluzzardi** [comment]
ping @thaJeztah @chanwit @snrism @JeffChien @jimmyxian 

Any suggestion?

**Comment by thaJeztah** [comment]
Was already giving it some thought, no good suggestions (yet), will let you know when something materialises :smile:

**Comment by amitshukla** [comment]
Really old issue... please reopen if it is still relevant
