### ISSUE TITLE
Docker-Machine(with boot2docker) with Swarm awkwardness on DOCKER_TLS_VERIFY

### ISSUE THREAD

**Issue by jasw** [docker/swarm#818]
Hi all,

I use docker-machine with my OSX macbook.  I would like to use this laptop as the swarm manager to manage a bunch of docker swarm nodes.  In the meantime, I have other containers running in this laptop, so it does need to work besides being a swarm manager. 

I got it all going in the end but with a awkward situation:

I have to keep change DOCKER_TLS_VERIFY to 1 and unset it to be able to probe my swarm manager using this `docker -H tcp://192.168.99.100:<swarm_manager_port> info` (requires TLS to be unset); if I just want to use my actual docker host (the one that on port 2376), I will have to set the TLS value to 1 again. 

For example:

FATA[0000] Post http://192.168.99.100:2376/v1.18/containers/create: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16". Are you trying to connect to a TLS-enabled daemon without TLS?

Currently I am working around this by doing a docker-machine ssh, then I can set DOCKER_HOST to be 0.0.0.0:<swarm_port> on the boot2docker. so the boot2docker vm environment is dedicated for swarm manager. Using docker directly on the OSX commandline to manage the other containers. 

So my question would be, is there a proper solution for this? 

Many thanks,
Jason

**Comment by nathanleclaire** [comment]
I don't fully understand the question or your setup.  Are you using the `--swarm` etc. options when you create the machines?  That will mostly take care of the cluster/swarm management for you, and allow you to point towards the Swarm master pretty easily with something like `eval $(docker-machine env --swarm masternode)`.  Generally it's not a good idea to expose non-TLS protected Docker ports, as it opens you up to some vulnerabilities.

**Comment by thaJeztah** [comment]
> Generally it's not a good idea to expose non-TLS protected Docker ports, as it opens you up to some vulnerabilities

I'd like to emphasise that a bit more; it's a **bad** idea to expose those ports unprotected; anyone that can gain access to the docker remote API effectively has root access to your machine, so is a **big** security issue.

**Comment by abronan** [comment]
Closing this one, as this is specific to `docker-machine`. Generally we want to avoid running the Manager on a local laptop (even though it's possible), it should run on a dedicated machine with dedicated resources for performance, security and reliability reasons.

Proper solution for this kind of setup would be to set up Swarm without `docker-machine` and create the certificates ourselves. But setting up the Manager on a local laptop is only encouraged when developing on Swarm or testing it.
