### ISSUE TITLE
Libnetwork integration

### ISSUE THREAD

**Issue by snrism** [docker/swarm#821]
Now that libnetwork replaced existing docker networking code (docker issue 13060), any inputs/timeline on the `integrate swarm with docker networking` task in ROADMAP is appreciated. If there are any plans already in place, I am happy to be part of this effort. Thanks!

**Comment by aluzzardi** [comment]
/cc @mavenugo @mrjana

We'd love to start the integration work ASAP and are actively working with the `libnetwork` folks.

As soon as we have a clear plan, we'll update our `ROADMAP` and create relevant issues here on GH which everybody will be more than welcome to help us with.

**Comment by snrism** [comment]
Thanks for the update

**Comment by jimmyxian** [comment]
@snrism  @aluzzardi 
Great! I will also waiting for the relevant issues.

**Comment by mavenugo** [comment]
@aluzzardi @snrism :+1: only as early as humanly possible :)

**Comment by rhim** [comment]
Hi Folks,

Is there a better description of this task? For example, can we assume that all docker network and docker service commands will work when pointing to a swarm master?

Is there an experimental repo from where I can try it out?

Thanks

**Comment by abronan** [comment]
Hi @rhim,

> Is there a better description of this task? For example, can we assume that all docker network and docker service commands will work when pointing to a swarm master?

This is the intended goal yes :)

The API is still in the work and changing slightly on libnetwork's side but is near finalized and we'll include it in swarm as soon as possible. On our side, it's just a matter of supporting the new API endpoints: we'll just proxy networking api calls to the right machine or a random one according to what we want to do (create a network or a service, list networks and services, etc.).

You can try the new networking features with Swarm using `docker-experimental`: take a look at [this tutorial](https://github.com/docker/docker/blob/master/experimental/compose_swarm_networking.md) :)

Note that this is just a demo of Multi-Host networking using a default overlay network. You cannot create new networks and services through Swarm yet.

**Comment by rhim** [comment]
@abronan : do you have any timelines on this that you can share? If there is a private branch where this feature is in development, I would be happy to try it out and contribute.

**Comment by feiskyer** [comment]
@aluzzardi Looking forward to it.

**Comment by klaus1982** [comment]
Hi team, any plan & design doc for this integration?

**Comment by abronan** [comment]
Hi @rhim @feiskyer @klaus1982, the new UX for networking is reviewed in docker/docker#16645. Once this is merged I'll work to adapt what I've done so far with the old UX to integrate with Swarm.

**Comment by abronan** [comment]
This issue is being currently solved by #1262

**Comment by abronan** [comment]
Closing this one as we added the libnetwork support in 1.0.0 :)
