### ISSUE TITLE
enlightened container environment variables for cloud scenarios - auto-kill, etc.

### ISSUE THREAD

**Issue by magaal** [docker/swarm#822]
Hi - I have a scenario where in an HPC pleasingly parallel deployment of my containers into a swarm cluster, I'd like for when the container exits to also cause the node to kill itself to cease billing. I can do this easily via script by installing in to my container the cloud specific CLI and having the last line on the script I run at container launch perform the shutdown via cloud provider API's, but I need the hostname of the node the container is running on to do this. 

A further extension of this could be enlightening swarm to cloud providers (potentially leveraging some of the machine drivers) to automatically startup pre-provisioned swarm nodes that are just in a stopped state to accept a run.

**Comment by amitshukla** [comment]
Really old question... closing
