### ISSUE TITLE
Installation Documentation is Irresponsibly Insecure

### ISSUE THREAD

**Issue by grahamc** [docker/swarm#831]
People new to Docker may be likely to try out the whole offering of Docker, including Swarm. Unfortunately the Swarm instructions include such travesties as:

```
$ docker -H tcp://0.0.0.0:2375 -d
```

To users who are already intimately familiar with docker this will immediately be recognized this as a huge problem and risk. However, the documentation makes no indication to docker newbies that this opens up the node to literally running any untrusted and arbitrary code from anyone on the entire internet.

Even publishing this documentation is a disservice to docker's users, a violation of user trust, and opening up great potential to damage the docker name.

Proposed solution: Remove this documentation, or replace with documentation which configures the nodes using SSL.

**Update**: An alternate solution may include information about firewalls, and not binding to `0.0.0.0`.

**Comment by UserTaken** [comment]
I already brought up this in https://github.com/docker/swarm/issues/817 but the existing documentation on how to manually secure the connection is not convenient or easy to understand for new people not familar with OpenSSL, x509 and TLS.

**Comment by grahamc** [comment]
So because the existing documentation is difficult, and the process is difficult, it is preferable to open boxes owned by potential users up to root-equivalent access to anonymous users on the internet?

Remember this is not just a disservice to the user, it is a disservice to the wider internet.

**Comment by UserTaken** [comment]
No, I'm not saying it is more preferable leave unencrpyted ports on the Internet and I agree security should be emphasized and documentation should be improved.

**Comment by grahamc** [comment]
Thank you for the clarification. :)

**Comment by UserTaken** [comment]
Here is an example of more than half a dozen vulnerable machines on a single IP range I mentioned in https://github.com/docker/swarm/issues/817: `167.88.41.216:3375`

**Comment by squillace** [comment]
There is no question that the default machine/swarm installation should be the secure one at some point. Until that time, it would be fantastic if the docs pointed out that in fact the installation described her was for demonstration purposes and should be torn down afterward or only set up in a protected network.

**Comment by NathanMcCauley** [comment]
@grahamc thanks for opening the issue, we agree with your assessment and @abronan has opened a PR to update the docs. See: https://github.com/docker/swarm/pull/833

If there are any other parts of the documentation where we can improve the default security configuration please feel free to let us know -- we're definitely interested in encouraging folks to do the right thing!

**Comment by squillace** [comment]
FWIW, I'm happy to work through this entire setup scenario with documentation, including contributing PRs to docs here. Have a working, secure, basic swarm as "the" way to do the basic scenario is just the right way to go.

**Comment by aluzzardi** [comment]
ping @moxiegirl

**Comment by aluzzardi** [comment]
I think this was fixed by @moxiegirl recent changes (machine by default).

@moxiegirl Do you think we can close this down?

**Comment by moxiegirl** [comment]
@aluzzardi the new getting started provides a very secure way to install. The old installation method is in the new docs/install-manual.md file.  That should be updated but it is put there as the "advanced" --- so yes, I think we can close this as we have a solution.  I still need to redo the manual file tho...

**Comment by moxiegirl** [comment]
Closing per @abronan
