### ISSUE TITLE
Swarm generating certs for TLS usage

### ISSUE THREAD

**Issue by abronan** [docker/swarm#834]
As of now, the TLS setup is tricky because users have to figure out themselves how to configure their own certs (whether self-signed or not). This results in the documentation taking the easy path of explaining how to setup the cluster in a very insecure manner (see #831)

I took a quick look at other projects like CockroachDB and they use a dedicated command to generate self-signed certs. 

This would tremendously help on the documentation part and on explaining how to configure TLS just by doing something like:

```
$ swarm cert create --path=/certs
$ swarm manage --tlsverify --tlscacert=/certs/<CACERT> --tlscert=/certs/<CERT> --tlskey=/certs/<KEY> [...]
```

We could thus remove the insecure setup altogether and replace it with this instead.

Thoughts?

**Comment by abronan** [comment]
cc/ @aluzzardi @vieux

**Comment by cpuguy83** [comment]
fyi, docker-machine handles setting these certs up for you, and also includes swarm provisioning.

**Comment by abronan** [comment]
@cpuguy83 Yep, that's why we are trying to slowly replace our doc with how to setup a Swarm using `docker-machine` instead :+1: 

This only concerns the manual setup part.

**Comment by abronan** [comment]
BTW what I propose is still *insecure* but it's a bit better than what with have now.

**Comment by snrism** [comment]
@abronan +1 for this feature. The `swarm cert create --path=/certs` will be very useful. If this can handle all creation steps,  the setup becomes much simpler.

**Comment by squillace** [comment]
@abronan I'd love it if the docs do not imply that the only "happy path" of creating swarms is run through docker-machine. I'd also love it if the docs pointed out happily that if you used docker-machine to create your vms all this would have been taken care of for you, as that's what it's for!

+1 for `swarm cert create --path=/certs`. Add that, and then the story for secure creation without requiring or implying a dependency on docker-machine is baked and easy for everyone, and then knowing that docker-machine takes care of the earlier steps is just peachy. 

YMMV, as always.

**Comment by abronan** [comment]
@squillace Completely agreed on this :+1:

**Comment by abronan** [comment]
@ehazlett @tiborvass Any way we can reuse the work done in Machine and Docker regarding certs generation and usage here in Swarm? Probably making it a separate repository and using it consistently in every project?

**Comment by ehazlett** [comment]
I'm a huge +1 for this :)

**Comment by chanwit** [comment]
This would be super cool !!

Best regards,

-chanwit

--
Chanwit Kaewkasi
linkedin.com/in/chanwit

**Comment by tiborvass** [comment]
@abronan +1 on having a repo for this, although I'm not sure on the UX: expose it through machine, now swarm, tomorrow docker? I'm wondering whether it should be handled by notary or some libtrust cli. /cc @dmcgowan @NathanMcCauley

**Comment by aluzzardi** [comment]
@tiborvass Agreed.

ping @NathanMcCauley @diogomonica

**Comment by diogomonica** [comment]
Libtrust already has some of the mechanics required for this. We should absolutely have it one one place instead of all over the place, and the idea of generating certificates automatically seems like the right one.
