### ISSUE TITLE
Discovery broken with low TTL

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#838]
On master, this works:

```
go run main.go join --ttl 10s --heartbeat 1s --addr 127.0.0.1:4242 consul://localhost:8500/test
INFO[0000] Registering on the discovery service every 1s...  addr=127.0.0.1:4242 discovery=consul://localhost:8500/test
```

However this fails mysteriously:

```
go run main.go join --ttl 2s --heartbeat 1s --addr 127.0.0.1:4242 consul://localhost:8500/test
INFO[0000] Registering on the discovery service every 1s...  addr=127.0.0.1:4242 discovery=consul://localhost:8500/test
ERRO[0000] Unexpected response code: 400 (Missing session)
```

**Comment by abronan** [comment]
There is a missing check here when the chosen store is Consul: Consul forbids using a TTL < 10s.

This is easy to fix but I don't know if we should forbid a TTL < 10s for every store or just for Consul? (to stay consistent)

**Comment by aluzzardi** [comment]
I guess only Consul could fail. We have to have API consistency however it's probably fine if every store has its own `Options` sanity checking.

Let's do this after `-rc1` as it's not a top priority
