### ISSUE TITLE
Store AtomicPut must return the latest index to honor atomicity

### ISSUE THREAD

**Issue by mavenugo** [docker/swarm#843]
`AtomicPut` operation currently doesn't return the latest index.
This forces the client to perform a `Get` request immediately following the `AtomicPut`.
That doesn't necessarily provide a guaranteed atomicity because the client must retain the latest index that it knows of in order to best utilize the watch functionality.

**Comment by abronan** [comment]
@mavenugo This is a limitation of Key value stores like Consul that does not return any information other than the success of the operation after a Compare and Swap.

Etcd allows you to get back the last Index after a CAS (and we use it for the locking algorithm).

We can use the existing index returned by Etcd and embed the Get operation right after the CAS in `AtomicPut` for Consul (to get the last index). Would that help in your case? Note that we don't have any CAS method for Zookeeper yet.

**Comment by mavenugo** [comment]
@abronan Thanks for the quick response. Do you think we can make use of the `Lock()` mechanism in order to provide this level of atomicity ?
For example, `AtomicPut` becomes :  
1. obtain Lock
2. perform CAS
3. Get Index
4. release Lock
5. return Index

wdyt ?
