### ISSUE TITLE
mesos lacks extensive integration tests

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#855]
It would be cool if the Mesos integration tests would start an entire cluster.

/cc @tnachen @jimenez @vieux

**Comment by chanwit** [comment]
Is there any requirement to help doing integration test over Swarm/Mesos?

I'm impressed by the testing infrastructure of `swarm` that let me fetch the current branch and just calling `run.sh` to test. I expect that I could do the same for Swarm/Mesos.

**Comment by vieux** [comment]
I started working on it in #894

**Comment by abronan** [comment]
We can close this one, Mesos has a handful of tests now for the API and even zookeeper.
