### ISSUE TITLE
spread strategy does not allow memory and / or CPU overcommit 

### ISSUE THREAD

**Issue by hcguersoy** [docker/swarm#868]
Hi Folks,

first of all: this is not a bug report but a enhancement request / call for discussion.

Currently I'm testing swarm very intensive for our environment and have observed that memory overcommit is not possible then I use the default spread strategy.
This is because the method `weighNodes` (in the file `scheduler/strategy/weighted_node.go`) is called by the BinPack strategy (there it is OK) and unfortunately by spread, too.

In a environment there you reserve e.g. a max of 4 Gb for an Application Server container with a normal footprint of only 1 Gb (a typical scenario for Java App Server with different settings for Xms and Xmx) and want to start 10 of them on a docker host with 32Gb you will fail because the sum of the reserved memory (by the memory constraint) is larger then the free memory on the node. But in reality there is only something about 10 Gb used.

This is a different behavior compared to the default docker behavior there I can start any number of containers with memory constraints until the kernel complains about it and calls the oom-killer.

IMHO spread strategy should allow memory overcommit and maybe binpack, too (if applicable in a configurable way like in the kernel with `/proc/sys/vm/overcommit_memory`).

**Comment by aluzzardi** [comment]
Thanks for the feedback. We've had many back and forth with this matter, feedback is very welcome.

A few things:

- We actually already have a configurable overcommit.

It defaults to 5%: `--cluster-opt swarm.overcommit=0.05`

- Overcommit in general:

The default is low for a reason - safety. For instance, in your example you have 10x4GB app servers (40GB total) on a 32GB node - but only 10GB are being actively used.

That's the timeless question of capacity planning: In this case it works fine, only 10 out of 32GB are used.
However, you are actually allowing the app servers to use up to 40GB.

If at some point they wake up and decide, hey, let's use all the memory we have, OOM is going to go on a rampage.

That's fine for app servers - not so much if you end up killing a single-instance database (e.g. MySQL). Coincidentally, the most common offenders that go from a relatively low usage up to their max are databases - they will run just fine at 1GB, then comes a weekly report query and they end up using their maximum amount of resources.

- Overcommit implementation

Right now, overcommit is baked into the strategy and configurable through an option.

We could move it to a filter (such as `resource` filter) or something like that and make the strategies pick the best node without worrying about whether there are enough resources or not.

This means that you get to disable that safety net altogether (as in, infinite overcommit) if you like to do so.

**Comment by hcguersoy** [comment]
Hi Andrea,

thank you for your detailed answer. I've found nothing in the docu and have missed it in the code.
I'll take a look into it again and may come back.

**Comment by amitshukla** [comment]
Issue is old, and the immediate question was answered... closing
