### ISSUE TITLE
Post https://discovery-stage.hub.docker.com/v1/clusters: dial tcp: i/o timeout

### ISSUE THREAD

**Issue by Madko** [docker/swarm#871]
I'm following this guide http://docs.docker.com/swarm/

But I can't have a token:

    # docker run --rm swarm create
    time="2015-05-29T12:57:55Z" level=fatal msg="Post https://discovery-stage.hub.docker.com/v1/clusters: dial tcp: i/o timeout"

Is it normal?

I'm able to do http post to that URL so I don't understand why it fails:

    # https_proxy=http://192.168.1.0:3128 curl -X POST https://discovery-stage.hub.docker.com/v1/clusters
    1ab2e1714b429b145e3c7d545abbda2e 

Here is some details on my docker (CentOS 7, SeLinux disabled):

    # docker version
    Client version: 1.6.2
    Client API version: 1.18
    Go version (client): go1.4.2
    Git commit (client): 7c8fca2
    OS/Arch (client): linux/amd64
    Server version: 1.6.2
    Server API version: 1.18
    Go version (server): go1.4.2
    Git commit (server): 7c8fca2
    OS/Arch (server): linux/amd64

**Comment by vieux** [comment]
When you do `docker run --rm swarm create`, this is probably not using your http proxy.
Can you try: `docker run --rm -e https_proxy=http://192.168.1.0:3128 swarm create` ?

**Comment by Madko** [comment]
Same results when adding -e https_proxy:

    # docker run --rm -e https_proxy=http://192.168.1.0:3128 swarm create
    time="2015-06-01T08:30:41Z" level=fatal msg="Post https://discovery-stage.hub.docker.com/v1/clusters: dial tcp: i/o timeout"

So just to try something I also added -e http_proxy and now this is working! I didn't think about passing the proxy thru the container, thank you Victor for showing me the way.
