### ISSUE TITLE
Newly introduced (#843) Store AtomicPut for Consul under Lock fails

### ISSUE THREAD

**Issue by mavenugo** [docker/swarm#875]
#843 introduced the support for retuning the LastIndex for the AtomicPut operation.
But unfortunately for the Consul backend, the Lock() operation results in the subsequent CAS to fail with ErrKeyModified error in AtomicPut method.

As a quick test, commenting out solved the problem.
```
        /*
                lock, err := s.NewLock(key, nil)
                if err != nil {
                        return false, nil, err
                }

                lock.Lock()
                defer lock.Unlock()
        */
```

**Comment by mavenugo** [comment]
ping @abronan. Any idea why the integration test failed to catch this condition ?

**Comment by abronan** [comment]
We don't use it yet in swarm to be honest and the integration tests only include Put/Get/Delete/Watches/List we can't detect failure for CAS as of now (we'll try to build more extensive integration tests for each backend). I know it works for Etcd and Zookeeper, but those are easy cases as they return the last index as part of the operation.

Now that I look back at the code this lock has nothing to do here, as AtomicPut shouldn't be a blocking operation if multiple goroutines are trying to modify the same key. I should remove that lock altogether.

Removing the lock is not sufficient though, we probably need to enforce the second read as *Consistent* to be sure we get back the last index and not an index from a stale read.

**Comment by mavenugo** [comment]
@abronan thanks for looking into this. I will try #881 and let you know.
