### ISSUE TITLE
Resource management integration tests

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#888]
Docker 1.7 broke our resource management (`Memory` and `CPU` are now in `HostConfig` rather than `Config`).

This should not happen again - we need to add integration tests to verify everything is working correctly.

Basic tests:
- [x] **Resource Propagation**: `docker run -m X -c Y foo` and check if data is shares are propagated correctly (`docker inspect` again swarm and docker host). **Note**: We do weird stuff with CPU shares. We should verify it works correctly.

- [x] **Resource Limits**: `docker run -m BIG` and `docker run -c BIG` should fail to schedule (`not enough resources`)

Strategies: Perhaps, later, we could add some tests that actually try out the strategy, similar to `script/demo/misc/script.sh`:
- [ ] **binpack**
- [ ] **spread**

**Comment by chanwit** [comment]
@aluzzardi could you please make them into a check list, so I can help fixing some of them. I see 4 items here.

**Comment by vieux** [comment]
@aluzzardi I quickly created https://github.com/docker/swarm/pull/886 to track the issue in the engine.

**Comment by aluzzardi** [comment]
@chanwit, sure!

**Comment by chanwit** [comment]
I don't understand what resource propagation is, so I skip it :)
But I think I could handle `binpack` and `spread` tests.
