### ISSUE TITLE
discovery flags

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#891]
Discovery flags today are misleading (and sometimes plain wrong).

`ttl` and `heartbeat` should **only** be available at `join`.

`heartbeat` is currently used by the manager to force a refresh for stores that do not support streaming updates (`token` and `file`).

We should
- Find a better flag name for `heartbeat` in `manage`
- Verify the current flags: Should it be `--ttl` or `--discovery-ttl`? Leader election and other stuff may also have `ttl` flags in the future.

Thoughts?

**Comment by vieux** [comment]
regarding `heartbeat` in `manage`, it's only used when we create the discovery, and Mesos doesn't use discovery, so I think it could be move to `--cluster-opt swarm.*=20s` where * is the new name (I have no idea)

**Comment by abronan** [comment]
`ttl` and `heartbeat` on **join** --> good

On the **manage** side I'd rather do something as suggested by Victor with `--cluster-opt swarm.refresh=20s` or something. You most definitely want to tweak the `ttl` and the `heartbeat` values with **join** but modifying the `refresh` time on discovery with **manage** is a less used, advanced configuration scenario.

**Comment by aluzzardi** [comment]
ping @abronan

**Comment by abronan** [comment]
@aluzzardi Ok will take care of this one, I ignored it for long enough (just worried about the implications of changing flag names post-`1.0` now). Should we have a deprecation policy now for those types of changes?
