### ISSUE TITLE
Performance improvement for store/zookeeper

### ISSUE THREAD

**Issue by chanwit** [docker/swarm#899]
This issue helps tracking samuel/go-zookeeper#59 (support calling `Multi` with `GetDataRequest`). When it gets fixed, performance of the ZooKeeper store can be improved.

Relates to #895

/cc @abronan @aluzzardi

**Comment by abronan** [comment]
:+1:

**Comment by abronan** [comment]
@chanwit we'll probably migrate this issue to `docker/libkv`? What do you think?

**Comment by chanwit** [comment]
@abronan no problem, Please go for it.
