### ISSUE TITLE
Regression for certain versions of Docker

### ISSUE THREAD

**Issue by chanwit** [docker/swarm#905]
Is it possible to setup a set of regression tests across different version of Dockers?
For example, Docker 1.7-rc1 broke Swarm 0.3.0 and we made changes. But how about Docker 1.6.0?

Not sure if there's a kind of backward compatibility plan like this?

**Comment by aluzzardi** [comment]
```
https://github.com/docker/swarm/blob/master/test/regression/run.sh
```

We just need to run it automatically in Jenkins somehow

**Comment by chanwit** [comment]
@aluzzardi is it too much to loop over these sets of integration tests for 2 current version of engines? 
If you're OK, I'll create a PR.
