### ISSUE TITLE
swarm does not pass the --ulimit parmeter

### ISSUE THREAD

**Issue by vbichov** [docker/swarm#906]
how to reproduce:
add "--ulimit nofile=[some number]" to your run command.
check your container.

**Comment by jimmyxian** [comment]
@vbichov 
Can you use `docker inspect -f "{{.HostConfig.Ulimits}}" container_id` to see if `ulimit` passed to docker daemon.

**Comment by vbichov** [comment]
@jimmyxian got "<no value>"

**Comment by vieux** [comment]
@jimmyxian can you take care of this one ?

**Comment by jimmyxian** [comment]
@vieux Sure.
@vbichov Can you provide swarm version and docker version ?

**Comment by vbichov** [comment]
Docker is 1.6.0
Swarm is 0.2

**Comment by jimmyxian** [comment]
@vbichov Yeah, Swarm 0.2 does not support `ulimit `. You can use swarm 0.3 or upstream. Anyway, thanks for reporting this.

**Comment by vbichov** [comment]
@jimmyxian Thank you.
Since you imply that swarm 0.3 solves this issue, I'm closing it.

**Comment by vbichov** [comment]
0.3.0-rc2 is bugged, can't list Consul hosts.
docker run -ti --rm swarm list consul://[ip]:8500/[cluster]
returns a list of ips
docker run -ti --rm swarm:0.3.0-rc2 list consul://[ip]:8500/[cluster]
returns empty
