### ISSUE TITLE
Swarm filter example for image affinity has typo

### ISSUE THREAD

**Issue by mbentley** [docker/swarm#910]
In the documentation on docs.docker.com, the example for using image affinity is incorrect.  See http://docs.docker.com/swarm/scheduler/filter/#affinity-filter and the example is `-e affinity:image=redis` when it should be `-e affinity:image==redis`

**Comment by abronan** [comment]
@mbentley Thanks :+1: Let us know if you want to take care of this.

**Comment by mbentley** [comment]
Sure, I'll submit a PR here is a minute.

**Comment by mbentley** [comment]
I'm only semi-familiar with the docs but I am assuming that they are built from the `.md` files as these were the only instances I could find via a quick grep.

**Comment by thaJeztah** [comment]
Got that right! Thanks for taking care of this!

**Comment by mbentley** [comment]
Sure thing, glad to help :+1:
