### ISSUE TITLE
Consul discovery stopped working for 0.3

### ISSUE THREAD

**Issue by vbichov** [docker/swarm#921]
0.3.0-rc2 is bugged, can't list Consul hosts. (so is rc1)

docker run -ti --rm swarm:0.2 list consul://[ip]:8500/[cluster]
returns a list of IPs

docker run -ti --rm swarm:0.3.0-rc2 list consul://[ip]:8500/[cluster]
returns empty

docker version is 1.6.0

**Comment by abronan** [comment]
Hi @vbichov, just tested with both versions and the exact same command and it works fine. Could you provide us with more details on your setup? Where is your Consul server located? etc.

Can you operate the cluster normally despite the `swarm list` not listing nodes?

**Comment by abronan** [comment]
Also make sure the `consul://[ip]:8500/[cluster]` does not have a typo on the `[cluster]` part, this might be one of the reasons you see an empty cluster list.

**Comment by vbichov** [comment]
@abronan Thank you for you quick response!
I've investigated further and found the cause. This is **not a bug**.

Somebody changed the key-value definition in Consul.
The newer version does not write to `/[cluster]/`
It writes to `/[cluster]/docker/swarm/nodes/`

I have neglected to switch all of my swarm agents...
If this change / convention has been documented somewhere, I'm afraid I haven't seen it.

Thanks again.
