### ISSUE TITLE
FATA[0000] Error response from daemon: invalid character 'I' looking for beginning of value

### ISSUE THREAD

**Issue by marc-** [docker/swarm#927]
Getting this error while executing following command:
```
docker -H 192.168.34.7:2376 run --name my_container 4e8aa3148a132f19ec560952231c4d39522043994df7d2dc239942c0f9424ebd ip route list
```
Specified image exists on certain node only in the cluster (I've committed container from previous run). But seems swarm is unable to locate that node and run container there.
Anyways error message is misleading.

**Comment by aluzzardi** [comment]
@marc- Could you run `docker -H 192.168.34.7:2376 version`?

Also, could you try this with swarm 0.3.0-rc2 (as in `docker run swarm:0.3.0-rc2` instead of `docker run swarm`).

Thanks

**Comment by marc-** [comment]
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: swarm/0.2.0
Go version (server): go1.3.3
Git commit (server): 48fd993
OS/Arch (server): linux/amd64
```
Will give a try to `swarm:0.3.0-rc2` .

**Comment by marc-** [comment]
Still same with `swarm:0.3.0-rc2`:
```
$ docker -H 192.168.34.7:2376 images --no-trunc | grep 4e8aa3148a132f19ec560952231c4d39522043994df7d2dc239942c0f9424ebd
my_image  latest  4e8aa3148a132f19ec560952231c4d39522043994df7d2dc239942c0f9424ebd   40 hours ago   989.8 MB

$ docker -H 192.168.34.7:2376 run 4e8aa3148a132f19ec560952231c4d39522043994df7d2dc239942c0f9424ebd ip route list
FATA[0000] Error response from daemon: invalid character 'I' looking for beginning of value
```

Though, it works following way:
```
$ docker -H 192.168.34.7:2376 run -e affinity:image==4e8aa3148a132f19ec560952231c4d39522043994df7d2dc239942c0f9424ebd  4e8aa3148a132f19ec560952231c4d39522043994df7d2dc239942c0f9424ebd ip route list
default via 172.17.42.1 dev eth0
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.19
```

**Comment by vieux** [comment]
@marc- can you push your image so we can test or is it sensitive information ?

**Comment by aluzzardi** [comment]
@vieux @marc- I think this is a pretty straightforward issue.

1. Unfortunately, you **cannot** run with a *local* image unless you specify an image affinity. That is, either your image can be pulled from a registry from **any** node in your cluster, or you specify an affinity (build, commited, imported images, etc)

2. Swarm is erroring out on you. Unfortunately, it looks like the error message doesn't get parsed correctly by the CLI. Could you check the logs of swarm?

**Comment by marc-** [comment]
@vieux you can just commit any container and try to run from that image.
 
@aluzzardi 
1. It would be really nice if swarm could replicate images across cluster on demand. It will address number of issues about building and committing images. But this is out of this issues scope.
2. Unfortunately nothing useful in logs of swarm manager:
```
time="2015-06-12T21:27:21Z" level=debug msg="HTTP request received" method=POST uri="/v1.18/containers/create"
time="2015-06-12T21:27:21Z" level=error msg="HTTP error: invalid character 'I' looking for beginning of value" status=500
time="2015-06-12T21:27:22Z" level=debug msg="Watch triggered with 6 nodes" discovery=etcd
time="2015-06-12T21:27:22Z" level=debug msg="Watch triggered with 6 nodes" discovery=etcd
```
Run manager with --debug option. Didn't find a way to make it more verbose.

**Comment by marc-** [comment]
Got something from docker daemon, hope it'll help (different image, but same approach):
```
time="2015-06-12T22:07:10Z" level=info msg="POST /v1.15/containers/create" 
time="2015-06-12T22:07:10Z" level=info msg="+job create()" 
No such image: 47a258a070c792dc6afb52812e7dccfe767d16d09ec092e414ea02fb4a1a644e (tag: latest)
time="2015-06-12T22:07:10Z" level=info msg="-job create() = ERR (1)" 
time="2015-06-12T22:07:10Z" level=error msg="Handler for POST /containers/create returned error: No such image: 47a258a070c792dc6afb52812e7dccfe767d16d09ec092e414ea02fb4a1a644e (tag: latest)" 
time="2015-06-12T22:07:10Z" level=error msg="HTTP Error: statusCode=404 No such image: 47a258a070c792dc6afb52812e7dccfe767d16d09ec092e414ea02fb4a1a644e (tag: latest)" 
time="2015-06-12T22:07:10Z" level=info msg="POST /v1.15/images/create?fromImage=47a258a070c792dc6afb52812e7dccfe767d16d09ec092e414ea02fb4a1a644e%3Alatest" 
time="2015-06-12T22:07:10Z" level=info msg="+job pull(47a258a070c792dc6afb52812e7dccfe767d16d09ec092e414ea02fb4a1a644e, latest)" 
time="2015-06-12T22:07:10Z" level=info msg="+job resolve_repository(47a258a070c792dc6afb52812e7dccfe767d16d09ec092e414ea02fb4a1a644e)" 
Invalid repository name (47a258a070c792dc6afb52812e7dccfe767d16d09ec092e414ea02fb4a1a644e), cannot specify 64-byte hexadecimal strings
time="2015-06-12T22:07:10Z" level=info msg="-job resolve_repository(47a258a070c792dc6afb52812e7dccfe767d16d09ec092e414ea02fb4a1a644e) = ERR (1)"
Invalid repository name (47a258a070c792dc6afb52812e7dccfe767d16d09ec092e414ea02fb4a1a644e), cannot specify 64-byte hexadecimal strings
time="2015-06-12T22:07:10Z" level=info msg="-job pull(47a258a070c792dc6afb52812e7dccfe767d16d09ec092e414ea02fb4a1a644e, latest) = ERR (1)"
time="2015-06-12T22:07:10Z" level=error msg="Handler for POST /images/create returned error: Invalid repository name (47a258a070c792dc6afb52812e7dccfe767d16d09ec092e414ea02fb4a1a644e), cannot specify 64-byte hexadecimal strings"
time="2015-06-12T22:07:10Z" level=error msg="HTTP Error: statusCode=500 Invalid repository name (47a258a070c792dc6afb52812e7dccfe767d16d09ec092e414ea02fb4a1a644e), cannot specify 64-byte hexadecimal strings"
```

My guess is that docker swarm can not process error response from docker daemon. And `invalid character 'I'` could come from `Invalid repository` string (last log's raw).

**Comment by aluzzardi** [comment]
ping @vieux

**Comment by jimmyxian** [comment]
@aluzzardi 
It's a bug in dockerclient `PullImage` method. We should check the response status code, if 500, just return the error, not do json decode.

**Comment by vieux** [comment]
@jimmyxian can you take care of this ?

**Comment by jimmyxian** [comment]
@vieux 
Yeah

**Comment by hsubram1** [comment]
Hello All, i am still facing this issue where i have a created a generic driver for Ubuntu box and created a swarm cluster.

When i am trying to pull the docker images either via docker-compose or manual docker pull from a private registry; i get the invalid character 'i' looking for beginning of value  error and as a result the image pull fails.

If i perform the same operation in a non-swarm environment ; the image is pulled from the private repo without errors.

Please let me know if you need additional details.

**Comment by hsubram1** [comment]
Forgot to mention, i used the docker-compose version 1.4.0rc3 and docker swarm version 0.4.0-rc1

**Comment by jimmyxian** [comment]
@hsubram1 
Can you provide a reproducible use case? :)

**Comment by hsubram1** [comment]
Steps to reproduce:

1. Setup a private Docker Registry
2. Have a few images deployed
3. From another docker host machine, connect to the registry
4. Now, run the below commands
            docker pull swarm:0.4.0-rc1
            swarmid=$(docker run swarm create) 
            docker-machine create -d generic --generic-ip-address <IP1> --swarm --swarm-master -- \
                     swarm-discovery token://$swarmid swarm-master
            eval "$(docker-machine env swarm-master)"
            docker-machine create -d generic --generic-ip-address  <IP2> --swarm --swarm- 
                     discovery token://$swarmid swarmNode1
            docker-machine create -d generic --generic-ip-address  <IP3> --swarm --swarm- 
                     discovery token://$swarmid swarmNode2
             eval "$(docker-machine env --swarm swarm-master)"
             docker run swarm list token://$swarmid
5. Now perform a docker pull from the private repo and the below error is seen

docker pull x.x.x.x/imagename/some-name
swarm-master: Pulling  x.x.x.x/imagename/some-name:latest... 
swarmNode1: Pulling  x.x.x.x/imagename/some-namelatest... 
swarm-master: Pulling  x.x.x.x/imagename/some-name:latest... : invalid character 'i' looking for beginning of value

**Comment by jimmyxian** [comment]
@hsubram1 
Also, Can you provide docker damon debug info, just like this https://github.com/docker/swarm/issues/927#issuecomment-111630420 , maybe we can find something useful.

**Comment by hsubram1** [comment]
I have just repurposed that system and dont have it now.

**Comment by appbead** [comment]
I have set "RegistryMirror" incorrectly in ~/.docker/machine/machines/default/config.json
After adding quote mark (") for items, it fixed.

**Comment by cooervo** [comment]
for me what work was deleting all volumes, all containers, kill all process, etc. The rebuild my containers and no longer received that error.

**Comment by sandersaares** [comment]
I am seeing this error message if I have a UTF-8 byte order mark at the beginning of my daemon.json.
