### ISSUE TITLE
Leader Election with configurable TTL

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#930]

**Comment by feiyang21687** [comment]
@aluzzardi are you still working on it?

**Comment by abronan** [comment]
Hi @feiyang21687, it's done on the `libkv` side for at least `etcd` and `zookeeper`.

The only bits left are the `Consul` TTL scheme (with session delete **behavior**) in `libkv` and finally add the flag here to configure the `TTL` accordingly. I guess that this issue should be tracked on both sides now that we have a separate repository to handle the distributed locking logic.

**Comment by abronan** [comment]
Closed by #1228
