### ISSUE TITLE
Swarm nightly images of unstable or HEAD versions

### ISSUE THREAD

**Issue by chanwit** [docker/swarm#945]
In the last two versions, many users keep reporting issues for the stable (`:latest`) of the old version, and it's hard for them to help testing the latest one, HEAD, properly. Moreover, Docker orchestration requires Swarm as an image. So is it possible to have nightly images for Swarm (`swarm:unstable`) on the Hub every a couple of days?

It could be `janky` than help tag and upload HEAD to the Hub after each good PR get merged.

This may start by the next version, 0.4.0:unstable.

What do you think?

**Comment by vieux** [comment]
@chanwit `dockerswarm/swarm:master` should do it.
For now there is no way to combine a library image with an automated build, that's why we have 2 repos.

**Comment by chanwit** [comment]
I see. Thank you @vieux
