### ISSUE TITLE
docker logs fails

### ISSUE THREAD

**Issue by zstarer** [docker/swarm#946]
Hi guys -

I'm not sure what the cause of this is, but I've tried rebooting the manager, all the slaves, all the containers, and pretty much everything short of creating a new token. I'm on CoreOS.

This happens on every container running in the swarm. I can get the logs by ssh-ing into the host and running 'docker logs $id', so it seems limited to getting logs via the master.

```
$ docker logs $id
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x504b1e]

goroutine 1 [running]:
github.com/docker/docker/engine.(*Env).Get(0x0, 0xd18630, 0x4, 0x0, 0x0)
	/go/src/github.com/docker/docker/engine/env.go:21 +0x21e
github.com/docker/docker/api/client.(*DockerCli).CmdLogs(0xc208064280, 0xc20800a020, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/client/commands.go:1975 +0x6dc
reflect.callMethod(0xc20810cf90, 0xc208151b78)
	/usr/local/go/src/reflect/value.go:605 +0x179
reflect.methodValueCall(0xc20800a020, 0x2, 0x2, 0x1, 0xc20810cf90, 0xc208064301, 0xc20805c360, 0x4, 0xc20802c001, 0x7f13683a37f8, ...)
	/usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/api/client.(*DockerCli).Cmd(0xc208064280, 0xc20800a010, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/client/cli.go:81 +0x37e
main.main()
	/go/src/github.com/docker/docker/docker/docker.go:138 +0xcc6

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [runnable]:
net/http.(*persistConn).readLoop(0xc20812b8c0)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc20812b8c0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by zstarer** [comment]
hah. I checked the free memory on the server running the manager, and it only had ~150mb free.

rebuilt the master and I can get my logs again. :)

**Comment by zstarer** [comment]
now I get this, looks the same.. not sure why, there's plenty of memory now.

$ docker logs -f $id
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x504b1e]

goroutine 1 [running]:
github.com/docker/docker/engine.(*Env).Get(0x0, 0xd18630, 0x4, 0x0, 0x0)
	/go/src/github.com/docker/docker/engine/env.go:21 +0x21e
github.com/docker/docker/api/client.(*DockerCli).CmdLogs(0xc20808e6e0, 0xc20800a020, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/client/commands.go:1975 +0x6dc
reflect.callMethod(0xc208104f90, 0xc208147b78)
	/usr/local/go/src/reflect/value.go:605 +0x179
reflect.methodValueCall(0xc20800a020, 0x2, 0x2, 0x1, 0xc208104f90, 0xc20808e701, 0xc20805c3f0, 0x4, 0xc20802c001, 0x7fd9517757f8, ...)
	/usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/api/client.(*DockerCli).Cmd(0xc20808e6e0, 0xc20800a010, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/client/cli.go:81 +0x37e
main.main()
	/go/src/github.com/docker/docker/docker/docker.go:138 +0xcc6

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [runnable]:
net/http.(*persistConn).readLoop(0xc208121130)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc208121130)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

**Comment by vieux** [comment]
@zstarer would you mind opening your issue on docker/docker ? It looks like docker is panicing.

**Comment by zstarer** [comment]
Sure @vieux , I'll move it over now.

**Comment by aluzzardi** [comment]
Resolved in docker/docker
