### ISSUE TITLE
/info does not return SystemTime

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/swarm#949]
The `/info` endpoint does not return a SystemTime.

This issue might in fact be invalid, because that's added in Remote API version 1.18. I am not sure what version Swarm currently supports in the source tree. I saw it makes the requests to the underlying docker hosts as 1.16, however I'm not sure if that is what actually determines Swarm's Remote API implementation.

**Comment by vieux** [comment]
@ahmetalpbalkan where `/info` should return a time ? I don't see it.

**Comment by ahmetalpbalkan** [comment]
@vieux http://docs.docker.com/reference/api/docker_remote_api_v1.18/
