### ISSUE TITLE
Confusing error when discovery proto not specified

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/swarm#951]
When I forget then `token://` part in the discovery URI, it tried to parse the token as `<ip1>,<ip2>`:

```
docker run -d swarm join --addr=0.0.0.0:2376 8a07dda59613edxxxxxxxxxxxxxxxx
time="2015-06-15T05:19:55Z" level=fatal msg="missing port in address 8a07dda59613ed702cf94dea56a4d07c"
```

This probably would be hard to diagnose for a newcomer falling into the same mistake. If the input was parsed more systematically, I think Swarm can show user a better error message.

Since the `<discovery>` argument in `swarm join` is defined as:

```
   discovery	discovery service to use [$SWARM_DISCOVERY]
            	 * token://<token>
            	 * consul://<ip1>,<ip2>/<path>
            	 * etcd://<ip1>,<ip2>/<path>
            	 * file://path/to/file
            	 * zk://<ip1>,<ip2>/<path>
            	 * <ip1>,<ip2>
```

I think the list of static IPs option should also be in `proto://input` format, like:

* `tcp://<ip1>,<ip2>`
* `static://<ip1>,<ip2>`

to be consistent with the rest of the input formats. Does anybody else feel the same?

**Comment by chanwit** [comment]
@ahmetalpbalkan It's `nodes://` and we made it optional. Maybe the doc should mention about this.

**Comment by ahmetalpbalkan** [comment]
@chanwit hmm so it was on purpose. I think users would be more consistent if `nodes://` was enforced. I don't think anybody would complain about some extra prefix?

also between 0.2.0 and 0.3.0-rc2, I can see a slight difference for the `join -h` output in the whitespace between "`<discovery>` and the sentence explaining it.


![image](https://cloud.githubusercontent.com/assets/159209/8153671/f650f124-12e5-11e5-936f-f66dc0067e2a.png)


![image](https://cloud.githubusercontent.com/assets/159209/8153665/e3861f2e-12e5-11e5-8b6e-714c3516ab36.png)

any ideas if this is on purpose?

**Comment by chanwit** [comment]
ping @vieux

**Comment by vieux** [comment]
@ahmetalpbalkan regarding the spaces, it's because we change the whole usage to look more like docker. we could reduce the number of spaces.

I'll open a PR

**Comment by aluzzardi** [comment]
+1

Explicit is better than implicit
