### ISSUE TITLE
Natural sorting in EngineSorter

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/swarm#952]
EngineSorter currently sorts the machines alphabetically like:

```
machine1
machine10
machine11
machine12
machine2
machine3
machine4
machine5
machine6
machine7
machine8
machine9
```

and that's what appears in `docker info` output. By using a natural sorting algorithm (e.g. https://github.com/skarademir/naturalsort) the output can be showed as for better readability:

```
[...]
machine8
machine9
machine10
machine11
machine12
```

**Comment by chanwit** [comment]
I think this could be an improvement for 0.4.0.
@vieux @aluzzardi @abronan what do you think?

**Comment by vieux** [comment]
@ahmetalpbalkan @chanwit good idea

**Comment by thaJeztah** [comment]
Looks like a good improvement! 

(I noticed that https://github.com/skarademir/naturalsort doesn't have any releases or tags yet, perhaps something to ask?)

**Comment by aluzzardi** [comment]
:+1:

**Comment by aluzzardi** [comment]
@chanwit Want to take care of this?

**Comment by chanwit** [comment]
@aluzzardi  no problem. I'll do it.

**Comment by chanwit** [comment]
I don't want to add an extra dependency for the sorting algorithm.
@skarademir would you mind if I'll grab your codes of `naturalsort` and put into a PR?

**Comment by ahmetalpbalkan** [comment]
@chanwit it should be ok as long as we vendor rather than copy/paste.

**Comment by aluzzardi** [comment]
Agreed with @chanwit - but then I looked at `naturalsort` and it turns out it's just a rather small file, so it should be fine to embed it with godep.

**Comment by chanwit** [comment]
Thanks for inputs. I'll go with Godepping `naturalsort`.
