### ISSUE TITLE
Swarm integration with Mesos

### ISSUE THREAD

**Issue by sourav82** [docker/swarm#967]
Does swarm integrate with Mesos as a framework like kubernetes, marathon etc.?

**Comment by tnachen** [comment]
Hi @sourav82 I'm not sure what's the purpose of this issue, but yes it is integrating with Mesos as a framework. This is already merged so I think we can close this ticket.

**Comment by vieux** [comment]
@sourav82 yes, as @tnachen said, it's integrated as a mesos framework, see https://github.com/docker/swarm/blob/master/cluster/mesos/README.md for more information.
