### ISSUE TITLE
before query string to get all the container does not work over swarm.

### ISSUE THREAD

**Issue by shashiranjan84** [docker/swarm#969]
Here I am using limit and before to paginate all the containers. It works on each swarm agent node but not for swarm master.

https://www.dropbox.com/s/gcdbtftrxcra1vs/2015-06-17%2006.55.24.jpg?dl=0

Am I doing something wrong or its just not supported on swarm?

**Comment by vieux** [comment]
@shashiranjan84 you are right, this is not yet supported by the manager. We will work on it.

Thanks for reporting the issue.

**Comment by shashiranjan84** [comment]
is there another way to paginate through all the containers instead of fetching them all once?
