### ISSUE TITLE
Swarm manager crash

### ISSUE THREAD

**Issue by eoghanino** [docker/swarm#973]
Swarm Version: 0.3.0-rc3
Discovery Service: Consul
Docker Version: 1.6.0
Kernel: 2.6.32-504.el6.x86_64 

time="2015-06-18T13:19:28Z" level=info msg="Removed Engine c4t11666.company.com" 
time="2015-06-18T13:19:37Z" level=error msg="HTTP error: No such container: 6b3ed3244b8de3c60accae128906155bd23f4ae9edd94e446cf32c0aadb5747a" status=404 
time="2015-06-18T13:19:37Z" level=error msg="HTTP error: Container 6b3ed3244b8de3c60accae128906155bd23f4ae9edd94e446cf32c0aadb5747a not found" status=404 
time="2015-06-18T13:20:07Z" level=info msg="Registered Engine c4t11666.company.com at c4t11666.company.com:2375" 
2015/06/18 13:43:45 http: panic serving 172.17.42.1:19661: runtime error: index out of range
goroutine 14750 [running]:
net/http.func·011()
	/usr/src/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x963280, 0xcd6a3c)
	/usr/src/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/docker/swarm/api.getContainersJSON(0xc208052540, 0x7fa76b4ef800, 0xc20811ee60, 0xc20816e680)
	/go/src/github.com/docker/swarm/api/handlers.go:199 +0x16e7
github.com/docker/swarm/api.func·008(0x7fa76b4ef800, 0xc20811ee60, 0xc20816e680)
	/go/src/github.com/docker/swarm/api/primary.go:111 +0x2a0
net/http.HandlerFunc.ServeHTTP(0xc2080b72c0, 0x7fa76b4ef800, 0xc20811ee60, 0xc20816e680)
	/usr/src/go/src/pkg/net/http/server.go:1235 +0x40
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20801a320, 0x7fa76b4ef800, 0xc20811ee60, 0xc20816e680)
	/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x292
github.com/docker/swarm/api.(*dispatcher).ServeHTTP(0xc20808a1e0, 0x7fa76b4ef800, 0xc20811ee60, 0xc20816e680)
	/go/src/github.com/docker/swarm/api/server.go:32 +0x9d
net/http.serverHandler.ServeHTTP(0xc2081163c0, 0x7fa76b4ef800, 0xc20811ee60, 0xc20816e680)
	/usr/src/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc2081f0300)
	/usr/src/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
	/usr/src/go/src/pkg/net/http/server.go:1721 +0x313
2015/06/18 13:44:38 http: panic serving 172.17.42.1:19653: runtime error: index out of range
goroutine 14737 [running]:
net/http.func·011()

**Comment by robtec** [comment]
+1

**Comment by abronan** [comment]
Hi @eoghanino and @robtec. I cannot seem to reproduce using swarm `v0.3.0` with the latest Consul and kernel `3.13`. Would be great if you can provide us with the steps that led to the panic :+1: (or out of curiosity, testing with a more recent kernel and the latest version of Consul)

**Comment by eoghanino** [comment]
@abronan kernel version is 2.6.32 rhel 6.3 patched to 6.6

**Comment by abronan** [comment]
@eoghanino Are you running Swarm inside a container or using the binary? We have known issues running Swarm with **rhel**, it is not directly related but you might take a look at #781.

**Comment by aluzzardi** [comment]
@robtec Same issue as well?

**Comment by eoghanino** [comment]
@abronan Ok, thanks for the info, its pretty stable just the removal of nodes from the manager when using consul

**Comment by abronan** [comment]
@eoghanino Ok! #924 will fix the node removal issue with Consul.

**Comment by eoghanino** [comment]
@abronan cool thanks!

**Comment by abronan** [comment]
I'll close the issue ;) feel free to re-open this one or create a new issue if you still have problems running Swarm with Consul
