### ISSUE TITLE
Swarm Manager crashes if Agent docker daemons are stopped and resumed

### ISSUE THREAD

**Issue by abronan** [docker/swarm#981]
Swarm does not like Agent docker daemons being stopped using `SIGSTOP` and resumed using `SIGCONT`. Manager crashes right after `SIGCONT` signal is sent to one of the docker daemons managed by swarm.

We should make sure that swarm recovers the connection gracefully or creates a new one when an agent is `unpaused`.

**Comment by aluzzardi** [comment]
Might already be fixed. Please try to re-produce

**Comment by abronan** [comment]
Can't reproduce, fixed :+1:
