### ISSUE TITLE
Scheduling: Anti-Affinity Deployment Filtering

### ISSUE THREAD

**Issue by JamieCressey** [docker/swarm#989]
Is there currently a way to define anti-affinity filters when deploying new containers, or would it be suitable to be added to the roadmap?

Use case: Deploying a MySQL master and slave. It would be preferred these containers were not scheduled to run on the same host to mitigate down time caused by server outages.

**Comment by vieux** [comment]
@JamieCressey you can do this with:

```
$ docker run -d --name mysql-master -e affinity:container!=mysql-* ...
$ docker run -d --name mysql-slave1 -e affinity:container!=mysql-* ...
$ docker run -d --name mysql-slave2 -e affinity:container!=mysql-* ...
$ docker run -d --name mysql-slave3 -e affinity:container!=mysql-* ...
```

Every container will be schedule on a node where there is no container starting with `mysql-` running.
If you have only 3 machine, the last `docker run` will fail. If you still want to do it you can use soft affinities:

```
$ docker run -d --name mysql-master -e affinity:container!=mysql-* ...
$ docker run -d --name mysql-slave1 -e affinity:container!=~mysql-* ...
$ docker run -d --name mysql-slave2 -e affinity:container!=~mysql-* ...
$ docker run -d --name mysql-slave3 -e affinity:container!=~mysql-* ...
```

This is going to try to apply the affinity, and if it's not possible, discard the affinity.

**Comment by JamieCressey** [comment]
Perfect, exactly what I'm looking for - thank you!
